### ISSUE TITLE
Onedir with exe outside the dir

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#1048]
**Original date**: 2010/01/12
**Original reporter**: _anonymous_

I tihnk it would be interesting to make another onedir option that allows the user to have the libs in one directory and the exe outside that one.

**Comment by HelloZeroNet** [comment]
Any chance on this?

Is there any way to make it cleaner, than this? (Beside the --onefile option)
![image](https://cloud.githubusercontent.com/assets/10350359/21703806/0075c5e4-d3b5-11e6-8579-dd30fa26b26b.png)

**Comment by gen2brain** [comment]
I managed to make it a little better with this runtime hook https://github.com/mupen64plus/mupen64plus-ui-python/blob/master/dist/windows/hooks/libdir.py , and I changed path to qt5_plugins in pyi_rth_qt5plugins.py . PyQt5 .pyd files and python3* dlls needs to stay in main dir.

Looks like this now:

![screen](https://cloud.githubusercontent.com/assets/17418/22113851/eff60cde-de67-11e6-8d36-9cd3bf66e5d4.png)

![screen01](https://cloud.githubusercontent.com/assets/17418/22113855/f6b5d0a4-de67-11e6-89ed-b1a06a7745e9.png)

**Comment by htgoebel** [comment]
Somebody need to provide a pull-request.

**Comment by Stevoisiak** [comment]
One user was able to accomplish this with a runtime hook. (See [*PyInstaller – Separating the executable from the ‘onedir’*](http://unafaltadecomprension.blogspot.com/2014/07/pyinstaller-separating-executable-from.html))

**Comment by stadelmanma** [comment]
Given some more information on how to approach this problem I would be more than willing to submit a PR. We are migrating a large package of C and Fortran executables to Python and a clean distribution format is essential.

**Comment by htgoebel** [comment]
@stadelmanma https://github.com/pyinstaller/pyinstaller/issues/1048#issuecomment-59617973 and https://github.com/pyinstaller/pyinstaller/issues/1048#issuecomment-59617974 should point you in the right direction.

Paths sould be set up in the bootloader [around here](https://github.com/pyinstaller/pyinstaller/blob/v3.3.1/bootloader/src/pyi_main.c#L67). And https://pyinstaller.readthedocs.io/en/latest/bootloader-building.html will guide you for building the bootloader..

**Comment by caffeinepills** [comment]
@stevoisiak Not sure if that method worked in a previous version but with the latest, I can confirm it does not. While it mostly works with the .dll's, and some of the pyd files. There are some still required to be in the root.

I like the idea of the request, especially since some alternatives already offer such a thing. The amount of files that can be generated in the folder can be enormous. After freezing my applications I had over 170 files. Trying to distinguish between where the required interpreter files start and where your application's required files end is next to impossible with a folder structure such as that.

**Comment by brindanivaas** [comment]
@caffeinepills  - You can create a setup which take care of creating a desktop short cut as well handles the one folder setup. Check the below link for detailed info.
https://www.youtube.com/watch?v=n-p-4titD2Y
http://www.jrsoftware.org/isinfo.php

**Comment by Legorooj** [comment]
(Oops accident - tab somehow clicked it)

**Comment by Legorooj** [comment]
Closing; stale

**Comment by fabioz** [comment]
I see this is closed (probably because this is hard to do)... for those that want a workaround, a simpler approach is probably creating a separate executable which calls the existing executable which is already generated by pyinstaller (i.e.: create/compile some `main.c` which calls the existing executable).

**Comment by bicobus** [comment]
> i.e.: create/compile some main.c which calls the existing executable

It kinds of defeat the purpose of python and pyinstaller though. You'll need to create an executable for each platform and handle caveats inherent to each of them.

**Comment by Legorooj** [comment]
Look, if you'd like this feature, open a new issue and PR and write the feature.

**Comment by fabioz** [comment]
@bicobus yes, you need to handle caveats (and if it's done maybe even contribute that to pyinstaller), but I don't think that it defeats the purpose of pyinstaller (which probably already goes through many whoops to track everything needed to create one installer -- I don't think that creating an exe that calls another exe isn't work comparable to what it already does, although I agree that it does come with its own caveats).

@Legorooj sorry, I didn't mean to create havoc there and I fully appreciate how hard it is to manage an open source project with few time available... as it seems this is a popular request, maybe as a suggestion, I think you could leave the ticket open but explicitly say that it's waiting for someone to create a pull request and it won't be done by the core team (which is still willing to review and incorporate that work).

**Comment by Legorooj** [comment]
@fabioz you didn't create havoc. Sorry; I was a little short.

I'll clarify:

If someone wants this feature in PyInstaller, then they need to submit a PR containing it. We'll happily accept a feature, but we don't have time to program it ourselves because there are too many bugs to fix, features to review, hooks to deal with, and other maintenance work. (We don't have support for python 3.8 yet for example).

I'm leaving this issue closed because no one has addressed it. It's been sitting here and left alone. If someone wants this feature; do the work.

**Comment by maphew** [comment]
suggestion: treat the opening post like a wiki page and insert the text about the feature being welcome but someone not on the core team needs to write it, add workflow info about how to go about that if someone wants to pick it up, and the pointers for where to get started.

Here's some text ready for copy-paste, from the content above, but in time it will get lost in the middle. (the blob link to bootloader probably needs to be updated).

----
If someone wants this feature in PyInstaller they'll need to write it, open a new issue, and submit a PR containing it. We'll happily accept this feature, but we don't have time to program it ourselves because there are too many bugs to fix, features to review, hooks to deal with, and other maintenance work. This issue will stay closed unless and until someone steps up. 

**Starting points:** 

There are several different steps here:

* the bootloader needs to be adjusted to look for files in that directory. This must happen both at the Python level (sys.path) and at the OS level (LD_LIBRARY_PATH).
* there must be a way to define the name of the subdirectory so that it is not hardcoded within the bootloader. I believe that an OPTION entry in the TOC would be fine, since that's what they are used for.
* Makespec.py must be modified to create a .spec file that tells COLLECT() the correct output subdirectory, and add the OPTION to the toc passed to the EXE() call.

So, all in all, this should not require any modification to the build process at all.

At the OS level:
* windows: instead LD_LIBRARY_PATH use just PATH
* MacOSX: DYLD_LIBRARY_PATH

The name of the option could be `--libdir`

Paths sould be set up in the bootloader around [here](https://github.com/pyinstaller/pyinstaller/blob/v3.3.1/bootloader/src/pyi_main.c#L67). And https://pyinstaller.readthedocs.io/en/latest/bootloader-building.html will guide you for building the bootloader..

**References:**
- https://github.com/pyinstaller/pyinstaller/issues/1048#issuecomment-623415263
- https://github.com/pyinstaller/pyinstaller/issues/1048#issuecomment-400635046
- https://github.com/pyinstaller/pyinstaller/issues/1048#issuecomment-59617973
- https://github.com/pyinstaller/pyinstaller/issues/1048#issuecomment-59617974 

----

**Comment by Legorooj** [comment]
@maphew good idea. I've edited with your snippet.

**Comment by wu933** [comment]
> One user was able to accomplish this with a runtime hook.
> 
> > This is just a Python module; call it whatever you want and put something like the following in it:
> > ```
> > import sys
> > import os
> > sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), "lib")) 
> > ```
> > 
> > 
> > To have PyInstaller use this you can just pass the path to it as an argument to pyinstaller (alternatively you can specify it in your .spec file):
> > ```
> > pyinstaller --onedir --windowed --runtime-hook=".\_pyinstaller_hooks\runtime_hooks\use_lib.py" … 
> > ```
> 
> Source: [_PyInstaller – Separating the executable from the ‘onedir’_](http://unafaltadecomprension.blogspot.com/2014/07/pyinstaller-separating-executable-from.html)

Is any body successful with this trick with Python3.7.9 and Pyinstaller 4.0？ Many modules cannot be found in my situation
