### ISSUE TITLE
Pyinstaller doesn't pick up Django templates dir

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#1065]
**Original date**: 2014/06/29
**Original reporter**: * anderson DOT jeffreyb AND*

 ref Ticket #1052 . Issue was previously closed with note "open new ticket if issue is still present"

Pyinstaller doesn't pick up Django templates directory.

If templates/ is copied into the dist/my_site folder it works without issue, however this precludes --onefile compiling

**Comment by gwikle** [comment]
After reviewing #1052 I believe this the same problem as "Django hook does not force import of 'hidden' django templatetag modules."  Because of this problem I have to manually add the following modules in my .spec file:

                            'django.templatetags.future',
                            'django.templatetags.i18n',
                            'django.templatetags.l10n',
                            'django.contrib.admin.templatetags.log',
                            'django.contrib.admin.templatetags.admin_urls',
                            'django.contrib.admin.templatetags.admin_modify',

These templatetag modules are used by Django's built in admin pages so the pyinstaller django hook should import them automatically.

**Comment by matysek** [comment]
This should be fixed in latest dev version.
