### ISSUE TITLE
Menu not displayed with PyQt5 app bundle on OSX.

### ISSUE THREAD

**Issue by philroberts** [pyinstaller/pyinstaller#1078]
When running the pyinstaller-generated app for my PyQt5 program, the menu bar initially does not update from the previous foreground app's menu bar, and is unclickable.  Alt-tabbing to another app and back to my app resolves the problem.

After a little research, it seems [this article](http://www.sheepsystems.com/developers_blog/TPT-show-menu.html) may describe the cause of the issue - inconsistent behaviour of TransformProcessType() across OSX versions.

I am using OSX 10.9.

**Comment by dvitonis** [comment]
I am using a workaround for this, however it might not be suitable for a fix since it has a small side effect.

1. Change LSBackgroundOnly to 0. That makes the parent app and the child process foreground, thus the menu bar is visible immediately.
2. Transform the parent process to background in the same fashion the child process is transformed to foreground in current version. This solves the double icon problem.

Side effect: windows flicker on initialization because of foreground-background-foreground switching.

I tested it on platforms Lion+.
More here: http://dvitonis.net/blog/2015/01/07/menu-bar-not-visible-when-building-pyqt-app-bundle-pyinstaller-mac-osx-mavericks-yosemite/
There's an example of the bundle to see the effect http://dvitonis.net/projects/ .

**Comment by gholzmann** [comment]
I can confirm that the fix described by @dvitonis is working - or at least its behaviour is IMHO much preferred!
Tested on OSX Maverick and Yosemite.

Do some pyinstaller developers think it is possible to include this in pyinstaller?
I guess it would be great for many users on OSX and makes maintaining an additional diff unnecessary ...

**Comment by htgoebel** [comment]
@gholzmann Thanks for you feedback. We'd appreciate a pull-request for this :-)

**Comment by gholzmann** [comment]
@htgoebel @dvitonis Thanks!

I created a pull-request now and tested the code again on OSX Mountain Lion, Maverick and Yosemite.
It works as described in the blog post by @dvitonis !

Would be great if you could include that!

**Comment by htgoebel** [comment]
@gholzmann Thanks for the pull-request.
