### ISSUE TITLE
NLTK issue

### ISSUE THREAD

**Issue by smalldatascaled** [pyinstaller/pyinstaller#1099]
nltk (http://www.nltk.org/) often uses pickle files which nltk has saved in a non-standard location. Pyinstaller imports nltk OK but if fails if the code tries to use the nltk.data.load function as it doesn't include the pickle file.

For example:
nltk.data.load('tokenizers/punkt/english.pickle')  

Had a few goes at trying to solve it using hooks... unfortunately a general solution is beyond my capabilities and so I just copied the required pickle files as well as the exe but I'm sure there is a better way...

**Comment by nedhulseman** [comment]
I have been working on this issue for a few days not and don't have hair left. For some reason nltk and pyinstaller do not work well together. So my first solution to this issue is to use something other than nltk if it is possible to code the solution without nltk.

If you must use NLTK, I solved this by forcing the nltk_data path into datas.

Locate your nltk_data path. Mine was in
C:\Users\user-name\AppData\Roaming\nltk_data

In hook-nltk.py (within pyinstaller directory) I commented out and added lines to look like this.

import nltk
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files('nltk', False)
'''
for p in nltk.data.path:
    datas.append((p, "nltk_data"))
'''
datas.append(("C:\\Users\\nedhu\\AppData\\Roaming\\nltk_data", "nltk_data"))
           
hiddenimports = ["nltk.chunk.named_entity"]
There is a deeper problem with pyinstaller looping through the datas list of paths, but this solution works as a patch.
