### ISSUE TITLE
lib2to3 support

### ISSUE THREAD

**Issue by sdementen** [pyinstaller/pyinstaller#1128]
Hello,

The lib2to3 library needs a file called Grammar.txt. 
I suppose we need a hook-lib2to3.py to handle this ?

**Comment by sdementen** [comment]
Here is the content of the file of my hook-lib2to3.py which works for me
(send by email as doing through git is a bit overkill ... and I do not know
how to do it).
As you can see, I hardcoded the path to the standard python lib lib2to3. I
guess you know how to fix this easily :-)

#-----------------------------------------------------------------------------
# Copyright (c) 2013, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with
exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this
software.
#-----------------------------------------------------------------------------

datas = [
    (r'lib2to3\Grammar.txt', 'lib2to3'),
    (r'lib2to3\PatternGrammar.txt', 'lib2to3'),
]
datas = [

 (r'C:\Users\sdementen\Miniconda3\envs\piecash27\Lib\lib2to3\Grammar.txt',
'lib2to3'),

 (r'C:\Users\sdementen\Miniconda3\envs\piecash27\Lib\lib2to3\PatternGrammar.txt',
'lib2to3'),
 ]

**Comment by htgoebel** [comment]
@sdementen I still wonder what your use-case is. IMHO there is no use for lib2to3 in PyInstaller. What do you need it for?

**Comment by sdementen** [comment]
i wrote some code working on python2 and python3 that needs this apparently
when running pyinstaller.
i may need to exclude this dependency explicitly in the spec ?

**Comment by htgoebel** [comment]
Sorry for answering late.
Yes, I assume you need to exclude it, simply because it is useless: When packaging the pytnon2-version, the files will be processed by the python2 interpreter. Respectively when packaging the pytnon3-version, the files will be processed by the python3 interpreter. So in the alter case, they need already to be converted to python3-syntax, say: lib2to3 must already have processed the files.

If it is your code, run `2to3` on your files prior to running PyInstaller.

If this is from some module, talk to the programmer to get this solved.

**Comment by eudoxos** [comment]
lib2to3 is needed by the future module, which is often used to write both python2 & python3 source-compatible code.

**Comment by htgoebel** [comment]
IC.
