### ISSUE TITLE
   popup a error R6034 when import tempfile ,after use Pyinstaller make py to exe file  

### ISSUE THREAD

**Issue by ningxiao77** [pyinstaller/pyinstaller#1143]
For some function can only run in python27 environment and some function must run in Python33 environment . so I split my model to two part.
1:the first part  Name Main.py will run in python27 environment . I use Pyinstaller to get a exe file:Mian.exe. 
2:the the second part Name body.py .
3: I use subprocess("python body.py",stdout=subprocess.PIPE,shell=True) to connect they together.
4:then  I set the windows sys path as :c:\python33
then I run : Main.exe  ,will popup  :Runtime Error! Program c:/python33/python.exe .R6034 . An appli..
5:but the function is ok ,just every time popup the message 3 times. after Click OK . will Body,py right.

I find the cause : The issue will happen when I use "import tempfile" in Body.py

Python :Python2.7.4 and Python3.3.5
os:Win7 32 bit
Pyinstall: 2.1 and 2.1.1dev exist the same issue.

**Comment by codewarrior0** [comment]
R6034 is "An application has made an attempt to load the C runtime library incorrectly." which means it tried to load a version of MSVCRT that is shipped as an Assembly without first setting an activation context. This is usually MSVCRT90.DLL that is used by Python 2.7.

However, Python 3.3 uses MSVCRT100.DLL, which is *not* shipped as an Assembly. This makes the error a bit obscure, since Python 3.3 shouldn't ever get error R6034.

I suspect that the old bootloader for PyInstaller 2.1 is setting PYTHONPATH, and when the Python 3.3 interpreter is launched, it inherits that path and tries to load the Python 2.7 extension modules (`.pyd` files), which are linked to MSVCRT90.DLL - but as Python 3.3 uses no manifests nor activation contexts, the error results.

Tentatively closing this as fixed because the new PyInstaller 3.0 bootloader does not set PYTHONPATH.
