### ISSUE TITLE
ValueError during launch due to import of _tkinter

### ISSUE THREAD

**Issue by jacebrowning** [pyinstaller/pyinstaller#1164]
On OS X 10.10.1 with Python 3.4, I am unable to launch apps that import `tkinter`. A minimum example:

```python
print("Hello, world!")

import tkinter

tkinter._test()
```

builds succesfully using:

```
$ pyinstaller helloworld_tk.py --noconfirm --clean --noupx --debug --windowed
```

but raises an exception on launch:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyInstaller-3.0dev_b2eed53_mod-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 302, in load_module
    exec(bytecode, module.__dict__)
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyInstaller-3.0dev_b2eed53_mod-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 472, in load_module
    module = loader.load_module(fullname)
ValueError: character U+6bced1a8 is not in range [U+0000; U+10ffff]
```

All relevant files (as well as a working non-tkinter example) can be found here: https://github.com/jacebrowning/pyinstaller/tree/1e1044d7edc42a9aba781a44c9db16f6aded10b1/sandbox

**Comment by jacebrowning** [comment]
I am using the current `python3` branch (b2eed53de62177bf898628ab403a0a8fee2ecb36) with rebuilt bootloaders as per #1085.

**Comment by matysek** [comment]
Could you try my branch, if that makes any difference? https://github.com/matysek/pyinstaller/tree/python3

**Comment by matysek** [comment]
It looks like the runtime hook pyi_rth_Tkinter.py needs some work.

**Comment by jacebrowning** [comment]
@matysek I get pretty much the same exception using 23af2e3: https://github.com/jacebrowning/pyinstaller/tree/36b95a637871f9f3704e5c72bd03c29c320cfc85/sandbox

**Comment by matysek** [comment]
Do you know how the tkinter module should be initialized in python 3?
In Python 2 pyinstaller only sets variables TCL_LIBRARY and TK_LIBRARY before importing tkinter.

**Comment by jacebrowning** [comment]
I'm not sure. What information would be helpful? `TCL_LIBRARY` and `TK_LIBRARY` are both unset when a `tkinter` application is running on my system and `_tkinter.so` is at:

`/opt/boxen/homebrew/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload/_tkinter.so`

**Comment by matysek** [comment]
PyInstaller sets should set these variables just before running your frozen app. See file ./PyInstaller/loader/rthooks/pyi_rth_Tkinter.py.

Anyway, this case is getting more interesting:
* there are involved multiple issues
* one of them is that hook-_tkinter.py does not bundle tcl/tk data files with the created app.

Thanks for reporting.

**Comment by leycec** [comment]
The same issue applies to Linux and, in all likelihood, Windows.

After a week of miserably struggling in vain against this, I've come to one simple conclusion: **Tcl/Tk must die.** It's significantly more fragile than alternative widget toolkits, requiring an ad-hoc and frankly poorly documented assemblage of external environment variables, plaintext scripts, binary files, and shared libraries. And this is just to get it up and running. (Which it does poorly. And slowly. And ugly.)

In short, Tcl/Tk is bad and its authors should feel bad.

Since complaining does nothing to help us, however, I've discovered a bittersweet secret. Grab a hold of your britches, 'cause this one's the kludge from hell: **importing `matplotlib` before importing `tkinter` makes the `ValueError` Unicode exception go away.** Revising jacebrowning's minimal-length example as follows thus permits `tkinter`-based applications to be frozen by PyInstaller *without* modification to the PyInstaller codebase:

    print("Hello, world!")
    import matplotlib
    import tkinter
    tkinter._test()

I am Jack's utter cluelessness as to why importing `matplotlib` before `tkinter` fixes this. But it does and reliably so. While this does *not* constitute a valid general-purpose fix, it does give us a starting point from which to cobble something together.

Importing `matplotlib` implicitly imports the `matplotlib.__init__` module – which, as of Matplotlib 1.4.0, is over 1,400 lines long. Curiously, this module contains [py2exe](http://www.py2exe.org/)-specific code. Lots of it in fact. (*I'm not kidding.*)

**So here's what we're going to do.** We're going to bisect `matplotlib.__init__.py` into little itsy-bitsy pieces until we find the bisection responsible for fixing `tkinter`. And when we find that, we're going to submit a PyInstaller pull request putting this issue to eternal slumber. And when we do that, we're *never* going to use Tcl/Tk again.

**Comment by leycec** [comment]
**Utter senseless insanity.** And not the good kind. ("What is Esoteric's [Subconscious Dissolution into the Continuum](https://rateyourmusic.com/release/album/esoteric/subconscious_dissolution_into_the_continuum/), Alex?")

The details of my solution are quite inconsequential. Very well, where do I begin? Bedecked in gallant regalia, I began by bisecting `matplotlib/__init__.py`. This heroically yielded the following critical line:

    from urllib.request import urlopen

Naturally, replacing `import matplotlib` with `from urllib.request import urlopen` in the prior example failed to fix anything. (Why, naturally! That would simply be *droll*.)

I then proceeded to `vimdiff` two versions of every intermediary `.toc` file generated by PyInstaller:

* The first version generated from the prior example.
* The second version generated from the prior example with `import matplotlib` replaced by `from urllib.request import urlopen`.

The only meaningful changes resided in `out00-PKG.toc`, at which point I painfully realized that importing Matplotlib induces PyInstaller to add Matplotlib-specific runtime hooks to the bootloader.

I then copied the contents of these hooks into the prior example and bisected the result. This triumphantly yielded the following minimal-length solution:

    print("Hello, world!")
    import tempfile
    import urllib.request
    import tkinter
    tkinter._test()

**And it worked.**

Note that Matplotlib is no longer required. In fact, the remaining imports are all unconditionally available with stock Python 3.

Note also that **order of importation is significant.** Yes, that's right. The following does *not* work:

    print("Hello, world!")
    import urllib.request
    import tempfile
    import tkinter
    tkinter._test()

What's not funny about this is that `urllib.request.py` *itself* imports `tempfile`, implying that `tempfile` shouldn't need to be imported at all. But it is. And in exactly the specified order. This is probably the most irrational issue I've encountered in *any* software – Python or otherwise. (And let me tell you, C++ template metaprogramming was no docile walk in the park.)

In the end, does it matter? It might. The proposed solution *could* conceivably break if the internal structure (particularly, the internal order of importation) of either the `tempfile` and `urllib.request` modules changes.

But do we have a choice? **No, we probably don't.** Given that and given the simplicity of the solution, I'll be amending pull request #1216 with a commit fixing this issue. This day all Gods die.

**Comment by codewarrior0** [comment]
I had a hunch that the ValueError indicated a failed Unicode encoding, so I tried the same test on my Windows machine and got the expected UnicodeEncodeError. On a hunch, I searched the CPython code for PyUnicode_FSEncode, and was not exactly surprised to find that _tkinter.c calling it. I was surprised to find that it was passing it the result of Py_GetProgramName, so I did some more investigating.

This error is caused by the bootloader calling `Py_SetProgramName` with stack-allocated memory. `Py_SetProgramName` must be given heap-allocated memory which will remain valid until `Py_Finalize` is called.

**Comment by jacebrowning** [comment]
@leycec Do you have a branch of `pyinstaller` that you'd like me to try with **my** full example?

**Comment by leycec** [comment]
@codewarrior0 **You're amazing.** That is all. This was pretty clearly a low-level C issue, and pretty clearly beyond my capacity to really solve. You *nailed* it.

@jacebrowning Good question. Technically, yes. But you probably want to wait for [codewarrior0](https://github.com/codewarrior0)'s illustrious patch to drop. Given that substantially improved solution, I'm pulling the latest commit from my [pull request](https://github.com/pyinstaller/pyinstaller/pull/1216#issuecomment-82004949).

If you'd just like this to work *now*, the following revision to your minimal example appear to work and should theoretically scale to your full example without modification to the PyInstaller codebase:

    print("Hello, world!")
    import tempfile
    import urllib.request
    import tkinter
    tkinter._test()

Presumably, that combination of `tempfile` and `urllib.request` imports somehow invokes a CPython call to `Py_SetProgramName()` with heap-allocated memory, thereby overriding PyInstaller's initial call to the same function with stock-allocated memory. **It's happening.**

**Comment by Ramkg** [comment]
@leycec i'm facing a similar issue but instead this is because of the pymsgbox import, which i am using for popping up alert boxes. 
import pymsgbox
As a stand alone .py file, this is running without any issues. Meaning, the alert boxes pop up. However, when i convert the script to an EXE file through pyInstaller, i get the below exception (similar to that of @jacebrowning 's):
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\*\pyinstaller-python3(1)\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", li
ne 302, in load_module
    exec(bytecode, module.__dict__)
  File "D:\*\Pynistaller\pyinstaller-python3\tkinter\__init__.py", line 38, in <module>
    from _tkinter import *
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\*\pyinstaller-python3(1)\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", li
ne 472, in load_module
    module = loader.load_module(fullname)
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

I tried your temp solution but it didn't work out. I'm new to Python and don't seem to understand the issue here. Would really love to hear from you on this one..

**Comment by leycec** [comment]
Thanks for the detailed traceback, Ramkg. Unfortunately, Markdown formatting appears to have accidentally swallowed critical portions of your traceback. For this reason, command output should typically be protected against Markdown interpretation. There are two ways to do this on Github (in order of simplicity):

* With **fenced code blocks**, delimiting the entire block of command output with `\`\`\``.
* By prefixing each line of command output with four spaces.

See the [Github-flavored Markdown cheatsheet](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) for examples.

That said, the exception message suggests this to be a different issue altogether – an *important* issue, to be sure, but a different one. The term `'mbcs'` refers to the [Multi-byte Character Set (MBCS)](http://stackoverflow.com/a/3299860), a Microsoft Windows-specific concept encapsulating largely obsoleted non-Unicode Asiatic character encodings (e.g., Shift_JIS, GBK, Big5).

Unfortunately, this is a [known Windows-specific Python issue](http://www.gossamer-threads.com/lists/python/bugs/1051137) and hence (probably!) *not* specific to PyInstaller, typically resulting from use of Unicode characters in pathnames (e.g., `C:\工具\module1.py`). The simplest way to fix this sort of thing is to replace *all* such characters with ASCII equivalents (e.g., `C:\Tool\module1.py`).

**Comment by Ramkg** [comment]
Thanks for the response @leycec 
Sorry about missing tracebacks!! I didnt knew it would cut down the portions of the traceback..The content that is actually missing is <frozen importlib._bootstrap>. I'll try posting them here again with the advised format, but please forgive me if it goes wrong again!.

Now, to the actual issue. I'm not sure whether this is caused by the unicode characters in my filepath. This is because, when i create an exe (with pyinstaller) without the pymsgbox module and the file is in the same path, it executes without a glitch.
This is happening only when i import the pymsgbox module and do some operation with it, such as, popping up an alert box. This specifically points to the line
    from _tkinter import _fix in the file _init_.py. This is present in tkinter folder off the Python Library path.

Code which is causing issue:
import pymsgbox
pymsgbox.alert('Hello', 'Alert')
As a stand alone, this executes perfectly. However as an exe file, it throws the unicode error.
Could you please run this through pyinstaller, create an exe and let me know if that exe is working fine?
I'm using Python 3.4.3.

Do let me know if this is a completely different issue so that i will post this is in a new thread..

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\ramkumarg\Downloads\pyinstaller-python3(1)\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", li
ne 302, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Python34\lib\site-packages\pymsgbox-1.0.0-py3.4.egg\pymsgbox\__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\ramkumarg\Downloads\pyinstaller-python3(1)\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", li
ne 302, in load_module
    exec(bytecode, module.__dict__)
  File "C:\Users\ramkumarg\Downloads\Caution\Pynistaller\pyinstaller-python3\tkinter\__init__.py", line 38, in <module>
    from _tkinter import *
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Users\ramkumarg\Downloads\pyinstaller-python3(1)\pyinstaller-python3\PyInstaller\loader\pyi_importers.py", li
ne 472, in load_module
    module = loader.load_module(fullname)
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

```

**Comment by leycec** [comment]
Thanks for the quick reply!

I've never seen an `'mbcs' codec can't encode characters in position 0--1: invalid character` exception *except* in relation to Unicode filenames. But you're right. Now that I have the traceback, the similarities between the [original issue](https://github.com/pyinstaller/pyinstaller/issues/1164#issue-54712781) and your issue are too glaring to ignore.

Unfortunately, my machine is currently busy recompiling the world. (**Gentoo: Because Pain Is Fun.**) This means that I'm unable to try out your helpful snippet. I have a simple recommendation, however. Checkout [codewarrior0](https://github.com/codewarrior0)'s ["patch-3" PyInstaller branch](https://github.com/codewarrior0/pyinstaller/tree/patch-3), which implements his ["Pass static-allocated memory to Py_SetProgramName"](https://github.com/pyinstaller/pyinstaller/pull/1217) fix.

If that *still* doesn't fix your issue, would you mind creating a new issue? This could be a related Windows-specific problem that just hasn't cropped up yet.

**Comment by Ramkg** [comment]
@leycec Thanks for your assistance! I tried @codewarrior0 's patch, but to no avail.
Per your suggestion i have raised a new issue for this #1245 .
Thanks again!!

**Comment by cclauss** [comment]
I am very surprised that you folks are seeing `'mbcs'` in these Unicode exception messages because the current pyinstaller does not set the default encoding.  Could you please try to sprinkle the line `import sys ; print(sys.stdout.encoding)` in your test code above to see if `sys.stdout.encoding` is getting set to mbcs before your code is run or by one of the import statements. See issue https://github.com/pyinstaller/pyinstaller/issues/1240 and PR https://github.com/pyinstaller/pyinstaller/pull/1243/files

**Comment by codewarrior0** [comment]
In this case, the decode error is related to the file encoding, not the IO encoding. SetProgramName sets a filename which should already be encoded using the filesystem encoding and thus is safe to pass to python2's filesystem routines.

The actual error is caused by passing temporary stack memory to SetProgramName which requires heap or global memory. The temporary stack memory is eventually overwritten by garbage, which certainly fails to decode!

**Comment by leycec** [comment]
**Just so.** As [noted elsewhere](https://github.com/pyinstaller/pyinstaller/issues/1245#issuecomment-96135077), [Ramkg](https://github.com/Ramkg) will need to rebuild the 32-bit Windows bootloader. Unfortunately, doing so is a [bit non-trivial](https://github.com/pyinstaller/pyinstaller/wiki/Build-Bootloader-Win64).

What's the standard operating procedure here? Ideally, we'd have some sort of scripted automation for recompiling *all* bootloaders in a cross-platform manner via a single `waf` or `setuptools` command. I'm assuming that doesn't exist.

**Comment by matysek** [comment]
I still need to do these things:
* recompile osx bootloaders
* backport this change for python3
