### ISSUE TITLE
Mac OSX: Unicode_simple.py throws a UnicodeEncodeError (`encodings` module not available during Py_Initialize)

### ISSUE THREAD

**Issue by cclauss** [pyinstaller/pyinstaller#1240]
unicode_simple.py:

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# `pyinstaller unicode_simple.py --onefile` results in an app that fails when run
from __future__ import (absolute_import, division, print_function, unicode_literals)
import sys
print(sys.getfilesystemencoding())  # correctly prints 'utf-8'
print(sys.stdout.encoding)  # incorrectly prints 'None'
print(sys.stderr.encoding)  # incorrectly prints 'None'
print('ü')  # throws UnicodeEncodeError in pyinstaller app
```

$ `pyinstaller unicode_simple.py --onefile`

Running the resulting app generates:

```
utf-8
None
None
Traceback (most recent call last):
  File "<string>", line 7, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 0: ordinal not in range(128)
```

$ `sw_vers`

```
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D136
```

$ `python -V`

```
Python 2.7.9
```

$ `pyinstaller -v`

```
2.1
```

**Comment by 671620616** [comment]
@cclauss, whatever the issue may be I'm seeing the unicode character correctly, without errors.
The full output is:

```
$ unicode_simple
mbcs
ü
$ sw_vers
'sw_vers' is not recognized as in internal or external command, operable program or batch
file.
$ python -V
Python 2.7.8 :: Anaconda 2.1.0 (32-bit)
$ pyinstaller -v
2.1
```

**Comment by htgoebel** [comment]
You need the ensure the stdout has the correct encoding set. This is not a PyInstaller problem

**Comment by cclauss** [comment]
Hi @htgoebel,

That is sounds really nice in theory but does not hold up in actual practice.  **How exactly do you recommend that I set the encoding of stdout to utf-8?**  Why is that extra step not required for any of these _nine other ways_ of running the same code on the same machine?

* ./unicode_simple.py
* python ./unicode_simple.py
* python3 ./unicode_simple.py
* pypy ./unicode_simple.py
* pypy3 ./unicode_simple.py
* jython ./unicode_simple.py
* TextWrangler "Run"
* TextWrangler "Run in Terminal"
* PyCharm "Run"

Notes:

* All successfully print the unicode character and do not throw an exception.
* jython requires the __future__ import is commented out and prints None instead of utf-8 but it still properly prints out the unicode character.
* TextWrangler "Run in Terminal" opens up a new Terminal window just like the PyInstaller-build app but TextWrangler's window properly prints the unicode character and does not throw an exception.

@671620616 is running on Windows 8, not on the Mac.

**Comment by cclauss** [comment]
This seems to help in the simplest cases:
```python
import os
if not os.getenv('PYTHONIOENCODING', None): # PyInstaller workaround
    os.environ['PYTHONIOENCODING'] = 'utf_8'
```

**Comment by bjones1** [comment]
I recall a patch for the Linux bootloader that may be relevant here: 06ce557b3e4a0493b2fb6788d7c02b38870d9770. Perhaps there's something related on the Mac? (Disclaimer: I don't have a Mac, so this is just guesswork.)

**Comment by cclauss** [comment]
```python
#!/usr/bin/env python
# coding: utf-8
from __future__ import (absolute_import, division, print_function, unicode_literals)
import os, sys
print(os.getenv('LC_CTYPE'), sys.stdout.encoding, sys.stderr.encoding)
```
When I run this code on the 9 ways that I mentioned above plus `Idle` and `Idle3` (yes, that is 11 ways to run it on my Mac) only the PyInstaller generated app prints `(UTF-8 None None)`.  The 10 other ways set both sys.stdout.encoding and sys.stderr.encoding to UTF-8.  Given that these are read-only variables, I am still unclear how I can `ensure the stdout has the correct encoding set` as suggested by @htgoebel above.

**Comment by codewarrior0** [comment]
The 11 different ways you mention all use the default Python runner, `/usr/bin/python`. This runner is responsible for loading the Python shared lib, initializing the Python interpreter, telling Python about the environment and preferred encodings, and ordering it to run the script given on the command line.

PyInstaller's bootloader is independent from the default Python runner. It has its own custom code for loading and starting up the Python interpreter - mainly because it has to unarchive the interpreter when in onefile mode - but it does a lot of other things differently than the default runner.

For instance, the default runner calls `PyFile_SetEncodingAndErrors` on stderr and stdout, using an encoding derived from the current locale (or from the environ `PYTHONIOENCODING` if present).

PyInstaller's bootloader does not call that function, and it's fair to say that's a bug.

To work around it, replace stdout and stderr with a wrapper from the codecs module, using something like this:

```
import codecs
import sys
sys.stdin = codecs.EncodedFile(stdin, file_encoding='utf-8')
sys.stdout = codecs.EncodedFile(stdout, file_encoding='utf-8')
```

**Comment by cclauss** [comment]
Not all...
* idle3 xxx.py
* python3 xxx.py
* pypy xxx.py
* pypy3 xxx.py
* jython xxx.py
all ignore the shabang line at the top of the file and therefore do not use `/usr/bin/python`.

A quick run of your workaround requires the removal of `file_encoding=` on Python2.  I will try to explore it more deeply tomorrow.

**Comment by codewarrior0** [comment]
Whoops, that should have been `data_encoding=`

In any case, it's likely that all of the ones you mentioned either use the default runner in some way (or for pypy/jython their own runners correctly set the I/O encoding when starting up the interpreter).

**Comment by htgoebel** [comment]
@codewarrior0 Thanks for this analysis in https://github.com/pyinstaller/pyinstaller/issues/1240#issuecomment-95360443. I agree that we should add such a code. It would be great if you would a) point me the the resp. code in Python and b) submit a pull-request for the loader.

**Comment by codewarrior0** [comment]
Sorry, I take back a lot of what I said above. I was wrong that the Python runner calls PyFile_SetEncoding - the Python DLL does this inside of Py_InitializeEx which is called the same way from the PyI bootloader and the Python runner.

On non-Windows platforms, Py_InitializeEx sets the IO encoding of stdin/out/err using the result of `nl_langinfo(CODESET)`. 

On Windows, it gets the console codepage from a Windows API - on my machine, I get `cp437`, the codepage for MS-DOS in America but since @cclauss seems to have written `cp850` in the test cases, which is the Western European MS-DOS codepage, this could vary based on the "Language For Non-Unicode Programs" setting in the Language control panel - I'll have to double check to verify. 

If stdin/out/err is connected to a file rather than a console, the encoding is not set for the file object. (`file.isatty() == False`)

**Comment by codewarrior0** [comment]
@cclauss Would you mind testing this with the latest `python3` branch? You may have to rebuild the bootloader `(cd bootloader; python waf all)`. The branch now supports Python 2.7, and I've just done a lot of work on the way filename encoding is handled and I'm curious if the I/O encoding is still a problem on OS X.

I've heard that the tests you helped with are now passing on OS X. If you want to run them yourself, install pytest and then run `py.test -k test_std`

**Comment by matysek** [comment]
I tested the code example `unicode_simple.py` and it is still not fixed for Python 2.7 on OS X (Python 3 works).
* frozen output
```
utf-8
None
None
Traceback (most recent call last):
  File "<string>", line 9, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 0: ordinal not in range(128)
```
* unfrozen output
```
utf-8
UTF-8
UTF-8
ü
```

Question is if this should be really fixed or just create a recipe with described workaround is enough.

**Comment by codewarrior0** [comment]
I think this is something we should fix.

@matysek Does the test `test_stdout_encoding` fail on OS X with Py2.7?

**Comment by codewarrior0** [comment]
Actually, I think that test may not catch this error, because the Python 2.7 DLL will only set the encoding of stdout when it is connected to the terminal. The test normally runs under py.test output capturing, which redirects stdout to a temp file.

**Comment by codewarrior0** [comment]
Never mind. I can reproduce this on Linux, too. I have a feeling it's because the `encodings` module isn't importable during Py_Initialize, which tries to lookup the codec given by `nl_langinfo(CODESET)`. Since the module isn't importable (it's in the PYZ archive and we can't install the PYZ importer before calling Py_Initialize), it seems the only way out is to use `base_library.zip` on Python 2 also.

I'll give that a try and see if it's fixed.

**Comment by codewarrior0** [comment]
I was right. The `encodings` module isn't importable at `Py_Initialize` time, so this is causing the stdio streams to have a None encoding. This is also what's causing sys.getfilesystemencoding to return None on Linux, and why we have a few dozen lines copied from pythonrun.c to set it after initializing the FrozenImporter.

I'm going to make a few changes to have the Python 2.7 builds use base_library.zip too, and hopefully we won't have to deal with either problem again.

**Comment by matysek** [comment]
> I'm going to make a few changes to have the Python 2.7 builds use base_library.zip too, and hopefully we won't have to deal with either problem again.

@codewarrior0 Postpone your commit after 3.0 release.

**Comment by codewarrior0** [comment]
All right.
