### ISSUE TITLE
--onefile on Win7 amd64 throws TypeError in winresource.py, probably win32api bug

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1273]
Bundling with the --onefile option under Python3.4, Windows7 64bit, winmanifest.py tries to update the Manifest thus:

                logger.info("Updating resource type %s name %s language %s",
                            type_, name, language)
                win32api.UpdateResource(hdst, type_, name, data, language)

when hdst=63307784, type_=24, name=1, language=0 and data=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity name="PPQT2" processorArchitecture="amd64" type="win32" version="1.0.0.0"/>
</assembly>`. Then comes the exception, `builtins.TypeError: 'str' does not support the buffer interface` from inside win32api. This is the latest version of win32api for Python 3.4.

I have filed a ticket on win32api, see https://sourceforge.net/p/pywin32/bugs/694/

This doesn't look like a PyInstaller problem; I am only putting up this issue because as long as this persists, --onefile is unusable on windows! I will attempt to get around it by encoding the data value as bytes, but that is not the right way to go.

Edit, yes, passing the data as `bytes(data.encode('UTF-8'))` eliminates the problem. Still not the way to go.

**Comment by codewarrior0** [comment]
I disagree that that's a problem with `win32api.UpdateResource`.

The convention for Win32APIs on Python is to accept `unicode` (`str` on py3) whenever the function's argument type is an LPCTSTR, which means that the API accepts a UTF-16 encoded string. Python will implicitly encode the `unicode` as UTF-16 before passing it to the API.

However, `UpdateResource`'s type for the `lpData` argument is LPVOID, not LPCTSTR. This is because UpdateResource is used to store binary data, not string data, so `bytes` is always the correct data type and the application is responsible for encoding string data in the correct encoding. The correct encoding, in fact, varies depending on what application is going to read the resource later! So it's wrong for `win32api` to assume a particular encoding is correct for `UpdateResource`'s `lpData` argument.

There is already a pull request open on PyInstaller to fix this, #1259.

**Comment by tallforasmurf** [comment]
The referenced pull request will fix this, so I'm closing the issue.
