### ISSUE TITLE
Archive Viewer incorrect header check

### ISSUE THREAD

**Issue by Bob-Grind** [pyinstaller/pyinstaller#1277]
This happens when trying to extract a file build with pyinstaller though.

Traceback (most recent call last):
  File "ArchiveViewer.py", line 253, in <module>
    raise SystemExit(main(opts, args))
  File "ArchiveViewer.py", line 113, in main
    data = get_data(arg, arch)
  File "ArchiveViewer.py", line 172, in get_data
    return zlib.decompress(arch.lib.read(lngth))
zlib.error: Error -3 while decompressing data: incorrect header check.

**Comment by htgoebel** [comment]
Hmm, this is an interesting one, because I just did some work in this area and did not encounter any error.

Which version of PyInstaller resp. archive-viewer are you using? Is this the same version you used for freezing the application? What file exactly is causing the error? The executable? Which command or commands within archive-viewer cuased the rorror?

**Comment by Bob-Grind** [comment]
Which version of PyInstaller resp. archive-viewer are you using (and on which branch)? Latest.
Is this the same version you used for freezing the application? A release from like a few weeks back though.
What file exactly is causing the error? The executable? Yes.
Which command or commands within archive-viewer caused the error? The extract command also the viewing part works fine though.

**Comment by tallforasmurf** [comment]
Could this be related to https://github.com/pyinstaller/pyinstaller/issues/1272 ?

Said to be fixed by https://github.com/pyinstaller/pyinstaller/commit/32478d98496e80de7fbe278b1dbc5fc1894b8721

That changes encoding of archive headers to allow for Unicode  module names.

**Comment by htgoebel** [comment]
>> Which version of PyInstaller resp. archive-viewer are you using (and on which branch)?

> Latest.

Which branch?

>> Is this the same version you used for freezing the application?

> A release from like a few weeks back though.

Does the archive-viewer in that version work? Does the current version of archive-viewer work when freezing with the current version of PyInstaller?

>> Which command or commands within archive-viewer caused the error?

> The extract command also the viewing part works fine though.

This is not an answer to the question :-(

**Comment by Bob-Grind** [comment]
Which branch? Develop.
Does the archive-viewer in that version work? Does the current version of archive-viewer work when freezing with the current version of PyInstaller? Yes.
This is not an answer to the question? Sorry the command that is used when crasing is "x file extractedfile" do you mean that though?

**Comment by Bob-Grind** [comment]
Could it be the crypto though?

**Comment by htgoebel** [comment]
> Could it be the crypto though?

There is a chance it could be crypto. But then you shouldn't be able to extract the file with the older version of archive-viewer, too.

> the command that is used when crashing is "x file extractedfile" do you mean that though?

Yes, this is what I meant. I assume the file you tried to extract actually is a compressed one?!

I'm about to close this issue, because it seams to be just an incompatibility between different versions in development stage. Anyway I would like to investigate this myself - maybe we have some real problem here. Can you send me that "older" executable per mail or provide me some download-link?
