### ISSUE TITLE
Pyinstaller seems to fail when importing google

### ISSUE THREAD

**Issue by chrisnorman7** [pyinstaller/pyinstaller#1279]
One of my projects uses gmusicapi, which in turn uses google.protobuf.descriptor (pip install google).

When I pyinstaller the project, it works fine, but on OS X and Windows it gives a traceback that says "No module named protobuf.descriptor".

I hit up google with the problem, and someone on Stack Overflow suggested putting `__init__.py` files in the google directory. They were already there, and no effect.

Any ideas?

Cheers.

**Comment by htgoebel** [comment]
Please follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong

**Comment by htgoebel** [comment]
Closeing. Waiting for information for 2 month now.

**Comment by glennra** [comment]
Since updating to the recently merged develop branch. PyInstaller is no longer packaging google.protobuf. This was working in the python3 branch of a few days ago.

**Comment by matysek** [comment]
Could you provide any code example?

**Comment by htgoebel** [comment]
@glennra Can you bisect this? The merge did not change anything (from python3`-branch point of view), so you could start at acaef99734d62023488ad1eb0ff61836f98596d3

**Comment by glennra** [comment]
0a5075f096d79e5a8bc97d5fcec5c6a75fe1a83e is the first bad commit

**Comment by matysek** [comment]
@glennra Do you have any error log from pyinstaller?

**Comment by glennra** [comment]
148 INFO: PyInstaller: 3.0.dev6+e2ad398
148 INFO: Python: 2.7.10
154 INFO: Platform: Darwin-14.5.0-x86_64-i386-32bit
154 DEBUG: Testing for UPX ...
159 INFO: UPX is not available.
159 INFO: Removing temporary files and cleaning cache in /Users/glenn/Library/Application Support/pyinstaller
163 DEBUG: script: /Users/glenn/rp/src/demo/test-protobuf.py
163 INFO: Extending PYTHONPATH with /Users/glenn/rp/src/demo
164 INFO: checking Analysis
164 INFO: Building Analysis because out00-Analysis.toc is non existent
164 INFO: Initializing module dependency graph...
165 INFO: Initializing module graph hooks...
166 DEBUG: Hidden import: codecs
215 DEBUG: Hidden import 'codecs' already found
215 INFO: running Analysis out00-Analysis.toc
215 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
221 DEBUG: Skipping libSystem.B.dylib dependency of Python
221 DEBUG: Skipping CoreFoundation dependency of Python
221 DEBUG: Adding Python dependency of Python from /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python
221 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python
223 DEBUG: Skipping libSystem.B.dylib dependency of Python
224 INFO: Analyzing /Users/glenn/rp/src/demo/test-protobuf.py
229 INFO: Looking for import hooks ...
231 INFO: Processing hook   hook-encodings.py
231 DEBUG: Collecting submodules for encodings
2191 INFO: Looking for ctypes DLLs
2191 INFO: Analyzing run-time hooks ...
2199 INFO: Looking for dynamic libraries
2200 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/unicodedata.so
2202 DEBUG: Skipping libSystem.B.dylib dependency of unicodedata.so
2202 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cPickle.so
2204 DEBUG: Skipping libSystem.B.dylib dependency of cPickle.so
2204 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/itertools.so
2206 DEBUG: Skipping libSystem.B.dylib dependency of itertools.so
2206 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_heapq.so
2207 DEBUG: Skipping libSystem.B.dylib dependency of _heapq.so
2207 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/operator.so
2209 DEBUG: Skipping libSystem.B.dylib dependency of operator.so
2209 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_collections.so
2210 DEBUG: Skipping libSystem.B.dylib dependency of _collections.so
2210 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/time.so
2212 DEBUG: Skipping libSystem.B.dylib dependency of time.so
2212 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/datetime.so
2213 DEBUG: Skipping libSystem.B.dylib dependency of datetime.so
2213 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_random.so
2215 DEBUG: Skipping libSystem.B.dylib dependency of _random.so
2215 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_hashlib.so
2216 DEBUG: Adding libcrypto.1.0.0.dylib dependency of _hashlib.so from /opt/local/lib/libcrypto.1.0.0.dylib
2216 DEBUG: Skipping libSystem.B.dylib dependency of _hashlib.so
2216 DEBUG: Adding libssl.1.0.0.dylib dependency of _hashlib.so from /opt/local/lib/libssl.1.0.0.dylib
2216 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so
2217 DEBUG: Skipping libSystem.B.dylib dependency of math.so
2217 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
2219 DEBUG: Skipping libSystem.B.dylib dependency of _io.so
2219 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gnureadline.so
2220 DEBUG: Skipping libSystem.B.dylib dependency of gnureadline.so
2220 DEBUG: Adding libncurses.6.dylib dependency of gnureadline.so from /opt/local/lib/libncurses.6.dylib
2220 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_functools.so
2221 DEBUG: Skipping libSystem.B.dylib dependency of _functools.so
2221 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cStringIO.so
2223 DEBUG: Skipping libSystem.B.dylib dependency of cStringIO.so
2223 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/binascii.so
2224 DEBUG: Adding libz.1.dylib dependency of binascii.so from /opt/local/lib/libz.1.dylib
2224 DEBUG: Skipping libSystem.B.dylib dependency of binascii.so
2224 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_struct.so
2225 DEBUG: Skipping libSystem.B.dylib dependency of _struct.so
2225 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/fcntl.so
2227 DEBUG: Skipping libSystem.B.dylib dependency of fcntl.so
2227 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/select.so
2228 DEBUG: Skipping libSystem.B.dylib dependency of select.so
2228 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/resource.so
2229 DEBUG: Skipping libSystem.B.dylib dependency of resource.so
2229 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/strop.so
2230 DEBUG: Skipping libSystem.B.dylib dependency of strop.so
2230 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_locale.so
2232 DEBUG: Skipping libSystem.B.dylib dependency of _locale.so
2232 DEBUG: Skipping CoreFoundation dependency of _locale.so
2232 DEBUG: Adding libintl.8.dylib dependency of _locale.so from /opt/local/lib/libintl.8.dylib
2232 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/array.so
2233 DEBUG: Skipping libSystem.B.dylib dependency of array.so
2233 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_multibytecodec.so
2234 DEBUG: Skipping libSystem.B.dylib dependency of _multibytecodec.so
2235 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_cn.so
2236 DEBUG: Skipping libSystem.B.dylib dependency of _codecs_cn.so
2236 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_jp.so
2237 DEBUG: Skipping libSystem.B.dylib dependency of _codecs_jp.so
2237 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_hk.so
2238 DEBUG: Skipping libSystem.B.dylib dependency of _codecs_hk.so
2238 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_tw.so
2240 DEBUG: Skipping libSystem.B.dylib dependency of _codecs_tw.so
2240 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_iso2022.so
2241 DEBUG: Skipping libSystem.B.dylib dependency of _codecs_iso2022.so
2241 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/bz2.so
2242 DEBUG: Skipping libSystem.B.dylib dependency of bz2.so
2242 DEBUG: Adding libbz2.1.0.dylib dependency of bz2.so from /opt/local/lib/libbz2.1.0.dylib
2243 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/zlib.so
2244 DEBUG: Skipping libSystem.B.dylib dependency of zlib.so
2244 DEBUG: Analyzing /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_codecs_kr.so
2245 DEBUG: Skipping libSystem.B.dylib dependency of _codecs_kr.so
2245 DEBUG: Analyzing /opt/local/lib/libcrypto.1.0.0.dylib
2248 DEBUG: Skipping libSystem.B.dylib dependency of libcrypto.1.0.0.dylib
2248 DEBUG: Analyzing /opt/local/lib/libssl.1.0.0.dylib
2249 DEBUG: Skipping libSystem.B.dylib dependency of libssl.1.0.0.dylib
2249 DEBUG: Analyzing /opt/local/lib/libncurses.6.dylib
2251 DEBUG: Skipping libSystem.B.dylib dependency of libncurses.6.dylib
2251 DEBUG: Analyzing /opt/local/lib/libz.1.dylib
2253 DEBUG: Skipping libSystem.B.dylib dependency of libz.1.dylib
2253 DEBUG: Analyzing /opt/local/lib/libintl.8.dylib
2254 DEBUG: Adding libiconv.2.dylib dependency of libintl.8.dylib from /opt/local/lib/libiconv.2.dylib
2255 DEBUG: Skipping CoreFoundation dependency of libintl.8.dylib
2255 DEBUG: Skipping libSystem.B.dylib dependency of libintl.8.dylib
2255 DEBUG: Analyzing /opt/local/lib/libbz2.1.0.dylib
2256 DEBUG: Skipping libSystem.B.dylib dependency of libbz2.1.0.dylib
2256 DEBUG: Analyzing /opt/local/lib/libiconv.2.dylib
2258 DEBUG: Skipping libSystem.B.dylib dependency of libiconv.2.dylib
2258 INFO: Looking for eggs
2258 INFO: Using Python library /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python
2262 INFO: Warnings written to /Users/glenn/rp/src/demo/build/build/base/warnbase.txt
2265 INFO: checking PYZ
2265 INFO: Building PYZ because out00-PYZ.toc is non existent
2265 INFO: Building PYZ (ZlibArchive) /Users/glenn/rp/src/demo/build/build/base/out00-PYZ.pyz
2361 INFO: checking PKG
2361 INFO: Building PKG because out00-PKG.toc is non existent
2361 INFO: Building PKG (CArchive) out00-PKG.pkg
2368 INFO: Bootloader /Users/glenn/rp/thirdparty/pyinstaller/PyInstaller/bootloader/Darwin-32bit/run_d
2369 INFO: checking EXE
2369 INFO: Building EXE because out00-EXE.toc is non existent
2369 INFO: Building EXE from out00-EXE.toc
2376 INFO: Appending archive to EXE /Users/glenn/rp/src/demo/build/build/base/test-protobuf
2377 INFO: Fixing EXE for code signing /Users/glenn/rp/src/demo/build/build/base/test-protobuf
2382 INFO: checking COLLECT
2382 INFO: Building COLLECT because out00-COLLECT.toc is non existent
2382 INFO: Building COLLECT out00-COLLECT.toc
2835 INFO: checking BUNDLE
2835 INFO: Building BUNDLE because out00-BUNDLE.toc is non existent
2835 INFO: Building BUNDLE out00-BUNDLE.toc
3186 INFO: moving BUNDLE data files to Resource directory

warnbase.txt

missing module named unicodedata.ucd_3_2_0 - imported by unicodedata, stringprep, encodings.idna
missing module named _sre.MAXREPEAT - imported by _sre, sre_constants
missing module named _warnings.warn_explicit - imported by _warnings, warnings
missing module named _warnings.filters - imported by _warnings, warnings
missing module named _warnings.once_registry - imported by _warnings, warnings
missing module named _warnings.default_action - imported by _warnings, warnings
missing module named _warnings.warn - imported by _warnings, warnings
missing module named _subprocess.STD_OUTPUT_HANDLE - imported by _subprocess, subprocess
missing module named _subprocess.CREATE_NEW_PROCESS_GROUP - imported by _subprocess, subprocess
missing module named _subprocess.STD_INPUT_HANDLE - imported by _subprocess, subprocess
missing module named _subprocess.STARTF_USESHOWWINDOW - imported by _subprocess, subprocess
missing module named _subprocess.CREATE_NEW_CONSOLE - imported by _subprocess, subprocess
missing module named _subprocess.STD_ERROR_HANDLE - imported by _subprocess, subprocess
missing module named _subprocess.STARTF_USESTDHANDLES - imported by _subprocess, subprocess
missing module named _subprocess.SW_HIDE - imported by _subprocess, subprocess
missing module named collections.namedtuple - imported by collections, inspect, unittest.util, difflib, doctest
missing module named cPickle.loads - imported by cPickle, collections
missing module named cPickle.dumps - imported by cPickle, collections
missing module named thread.get_ident - imported by thread, collections
missing module named thread._local - imported by thread, threading
missing module named thread.stack_size - imported by thread, threading
missing module named thread.allocate_lock - imported by thread, _strptime
missing module named itertools.imap - imported by itertools, heapq, collections
missing module named itertools.chain - imported by itertools, tokenize, heapq, collections
missing module named itertools.starmap - imported by itertools, collections
missing module named itertools.repeat - imported by itertools, collections
missing module named itertools.tee - imported by itertools, heapq
missing module named itertools.izip - imported by itertools, heapq
missing module named itertools.count - imported by itertools, heapq, threading
missing module named itertools.islice - imported by itertools, repr, heapq
missing module named collections.deque - imported by collections, shlex, threading
missing module named collections.OrderedDict - imported by collections, unittest.util
missing module named operator.itemgetter - imported by operator, collections, heapq
missing module named operator.eq - imported by operator, collections
missing module named operator.attrgetter - imported by operator, inspect
missing module named _collections.deque - imported by _collections, collections
missing module named _collections.defaultdict - imported by _collections, collections
missing module named _weakref.ref - imported by _weakref, _weakrefset, weakref
missing module named _weakref.ReferenceType - imported by _weakref, weakref
missing module named _weakref.proxy - imported by _weakref, weakref
missing module named _weakref.getweakrefs - imported by _weakref, weakref
missing module named _weakref.getweakrefcount - imported by _weakref, weakref
missing module named _weakref.ProxyType - imported by _weakref, weakref
missing module named _weakref.CallableProxyType - imported by _weakref, weakref
missing module named time.time - imported by time, threading
missing module named time.sleep - imported by time, threading
missing module named datetime.date - imported by datetime, _strptime
missing module named locale.normalize - imported by locale, gettext
missing module named errno.ENOENT - imported by errno, gettext
invalid module named locale - imported by _strptime, calendar, gettext
missing module named _hashlib.pbkdf2_hmac - imported by _hashlib, hashlib
missing module named copy.deepcopy - imported by copy, weakref
missing module named exceptions.ReferenceError - imported by exceptions, weakref
missing module named _sha512 - imported by hashlib
missing module named _sha256 - imported by hashlib
missing module named _md5 - imported by hashlib
missing module named _sha - imported by hashlib
missing module named binascii.hexlify - imported by binascii, random
missing module named math.sin - imported by math, random
missing module named math.sqrt - imported by math, random
missing module named math.cos - imported by math, random
missing module named math.acos - imported by math, random
missing module named math.ceil - imported by math, random
missing module named math.exp - imported by math, random
missing module named math.log - imported by math, random
missing module named math.e - imported by math, random
missing module named math.pi - imported by math, random
missing module named _io.DEFAULT_BUFFER_SIZE - imported by _io, io
missing module named _io.BytesIO - imported by _io, io
missing module named _io.open - imported by _io, io
missing module named _io.BufferedWriter - imported by _io, io
missing module named _io.FileIO - imported by _io, io
missing module named _io.BlockingIOError - imported by _io, io
missing module named _io.IncrementalNewlineDecoder - imported by _io, io
missing module named _io.BufferedReader - imported by _io, io
missing module named _io.BufferedRandom - imported by _io, io
missing module named _io.StringIO - imported by _io, io
missing module named _io.BufferedRWPair - imported by _io, io
missing module named _io.TextIOWrapper - imported by _io, io
missing module named _io.UnsupportedOperation - imported by _io, io
missing module named gnureadline.__doc__ - imported by gnureadline, readline
missing module named _functools.partial - imported by _functools, functools
missing module named _functools.reduce - imported by _functools, functools
missing module named errno.EINVAL - imported by errno, StringIO
missing module named cStringIO.StringIO - imported by cStringIO, gettext, pprint, shlex, tempfile, pickle, encodings.uu_codec, quopri, encodings.quopri_codec
missing module named binascii.b2a_qp - imported by binascii, quopri
missing module named binascii.a2b_qp - imported by binascii, quopri
missing module named binascii.a2b_uu - imported by binascii, encodings.uu_codec
missing module named binascii.b2a_uu - imported by binascii, encodings.uu_codec
missing module named 'org.python'.PyStringMap - imported by 'org.python', pickle
missing module named 'org.python' - imported by pickle
missing module named _struct.__doc__ - imported by _struct, struct
missing module named _struct._clearcache - imported by _struct, struct
missing module named _subprocess - imported by subprocess
missing module named msvcrt - imported by subprocess
missing module named threading.RLock - imported by threading, _threading_local
missing module named threading.current_thread - imported by threading, _threading_local
missing module named os.urandom - imported by os, random
missing module named riscosenviron._Environ - imported by riscosenviron, os
missing module named riscosenviron - imported by os
missing module named riscospath - imported by os
missing module named riscos._exit - imported by riscos, os
missing module named riscos - imported by os
missing module named ce._exit - imported by ce, os
missing module named ce - imported by os
missing module named _emx_link.link - imported by _emx_link, os
missing module named _emx_link - imported by os
missing module named os2._exit - imported by os2, os
missing module named os2 - imported by os
missing module named nt._isdir - imported by nt, ntpath
missing module named nt._getfullpathname - imported by nt, ntpath
missing module named nt._exit - imported by nt, os
missing module named nt - imported by os, ntpath
missing module named posix._exit - imported by posix, os
missing module named warnings.warn - imported by warnings, random
missing module named strop.whitespace - imported by strop, string
missing module named strop.maketrans - imported by strop, string
missing module named strop.lowercase - imported by strop, string
missing module named strop.uppercase - imported by strop, string
missing module named org.PyStringMap - imported by org, copy
missing module named org - imported by copy
missing module named re._compile - imported by re, sre
missing module named re.__all__ - imported by re, sre
missing module named re.escape - imported by re, _strptime
missing module named re.IGNORECASE - imported by re, _strptime
missing module named re.compile - imported by re, _strptime
missing module named codecs.mbcs_encode - imported by codecs, encodings.mbcs
missing module named codecs.mbcs_decode - imported by codecs, encodings.mbcs
missing module named 'google.protobuf'.descriptor_pb2 - imported by 'google.protobuf', base_pb2
missing module named 'google.protobuf'.reflection - imported by 'google.protobuf', base_pb2
missing module named 'google.protobuf'.message - imported by 'google.protobuf', base_pb2
missing module named 'google.protobuf'.descriptor - imported by 'google.protobuf', base_pb2
missing module named 'google.protobuf' - imported by base_pb2
missing module named google.enum_type_wrapper - imported by google, base_pb2
missing module named google - imported by base_pb2

**Comment by htgoebel** [comment]
@glennra Sorry, I've overseen this. can you please test with the 3.0 release and -- if this does not work -- with the current development version. We fixed some issued caused by the referenced commit lately. If it still does not work, please provide the *exact* installtion instructions for these google-modules, as there is no 'google.protobuf' distribution at PyPi.

**Comment by glennra** [comment]
It still doesn't work on windows with the latest master (https://github.com/pyinstaller/pyinstaller/commit/2f52ee1).

Protocol bufffers has to be installed from source https://developers.google.com/protocol-buffers/docs/downloads . First build the library using the supplied VS solution on Windows or `configure; make; sudo make install` on OSX/Linux then run `python setup.py install` from the python dir.

I have temporarily worked around the issue by using a version just prior to the commit that broke it, but this is not a long term solution.

**Comment by Wegi** [comment]
The problem still persists with the current master. What Info do you need to investigate?

**Comment by htgoebel** [comment]
@Wegi: Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

We would appreciate if you'd submit a hook for this. See https://pyinstaller.readthedocs.org/en/latest/hooks.html for more information about who to implement hooks.

**Comment by Wegi** [comment]
@htgoebel  I looked over the making sure guide. Wrote a small testapp.

```
import google.protobuf

protobuf_version = 0
protobuf_exist = False
try:
    protobuf_version = pkg_resources.get_distribution("protobuf").version
    protobuf_exist = True
except:
    pass

if (not protobuf_exist) or (int(protobuf_version[:1]) < 3):
    raise Error()

```

It seems the line `protobuf_version = pkg_resources.get_distribution("protobuf").version` which works quite normally standalone does not work after compiling with PyInstaller.

I will try to write a hook in the coming days, although im not quite sure if it is the right thing at the moment.

P.S. Im getting this error on Linux currently.

**Comment by htgoebel** [comment]
@Wegi THanks for the example, but what is the error message you get? See [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by Wegi** [comment]
The Error from the end of the Programm is triggered, because the `protobuf_exist` variable is not set, which it would be if protobuf is installed correctly.

**Comment by glennra** [comment]
Any progress on this issue. It is still not working in current develop.

**Comment by chrisnorman7** [comment]
That's probably because you need in add the cryptodome hook that was 
linked somewhere in this thread.


HTH,

**Comment by glennra** [comment]
@chrisnorman7 I can't find reference to a "cryptodome hook" in this thread, but I did find #2125 which looks like a different issue.

**Comment by chrisnorman7** [comment]
Hi, sorry... You're dead right, it's not in this thread!

Litterally no clue where I found it from in that case, I'm sure it was another issue, but can't remember where.

Anyways, here's the [zip file](https://github.com/pyinstaller/pyinstaller/files/589207/hook-Cryptodome.zip).

**Comment by glennra** [comment]
If I add this to Analysis "hiddenimports=['google.protobuf.internal']" it still doesn't work. The google.protobuf namespace seems to get included but apparently not all of it is there.
The output from `archive-viewer.py -lr out00-PKG.pkg` is:
{'StringIO': (0, 17, 4500),
 --- 8< ---
 'google': (1, 335693, 53),
 'google.protobuf': (1, 335746, 116),
 'google.protobuf.internal': (1, 335862, 125),
--- 8<---
'weakref': (0, 628623, 4608)}
[(0, 211, 292, 1, 'm', u'struct'),
 (211, 1139, 2585, 1, 'm', u'pyimod01_os_path'),
 (1350, 3850, 10569, 1, 'm', u'pyimod02_archive'),
 (5200, 5987, 18297, 1, 'm', u'pyimod03_importers'),
 (11187, 1543, 4347, 1, 's', u'pyiboot01_bootstrap'),
 (12730, 207, 307, 1, 's', u'test-protobuf'),
 (12937, 0, 0, 0, 'o', u'v'),
 (12937, 641948, 641948, 0, 'z', u'out00-PYZ.pyz')]

**Comment by chrisnorman7** [comment]
@glennra Did you put the contents of that zip file (one python file) into the hooks directory of your pyinstaller installation?

Failing that you could put it somwhere locally and do --hooks-dir=<path>. I'm not to sure on the argument, but I think that's rigth.

Sorry I'm not too certain on any of this stuff, I honestly just use pyinstaller to build EXEs, I have no clue about it's internals and so anything I tell you inevitably is stuff I've copy-and-pasted from Google. :-(

HTH.

**Comment by glennra** [comment]
@chrisnorman7 that hook-Cryptodome.py hook is for an entirely different issue. I did try it anyway and it does not solve the problem. This issue is about google.protobuf not being packaged properly.

**Comment by chrisnorman7** [comment]
Oh sorry... Woops... I think I'm going to shut up now! :-)


Hope you get it fixed!

**Comment by glennra** [comment]
I have narrowed this down for my use case, at least. It works (i.e. correctly packages google.protobuf) if I run pyinstaller.py ... using just python, however if I run it using python -O then google.protobuf does not get packaged.
Some further info: In the debugger I see that when it works the protobuf modules are detected as CompiledModule, but when it doesn't work they are MissingModule.

**Comment by glennra** [comment]
Looking at the debug output from ModuleGraph it appears that the issue occurs because PyInstaller is looking for .pyo files in the google.protobuf egg but can only find .pyc files.
I have worked around the issue by installing protobuf using `sudo python setup.py develop` instead of `sudo python setup.py install`.

**Comment by htgoebel** [comment]
Is this still an issue? PyInstaller has changed a lot since then, so has protobuf.

I'm closing this. I this is still an issue, please reopen.

**Comment by GraphicalDot** [comment]
Traceback (most recent call last):
  File "site-packages/sanic/app.py", line 1133, in run
  File "site-packages/sanic/server.py", line 857, in serve
  File "site-packages/sanic/server.py", line 634, in trigger_events
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "Application/main.py", line 337, in add_routes
Exception: settings.py is not present in the module clients.identity_client.settings, Please fix it before continuing
Traceback (most recent call last):
  File "Application/main.py", line 335, in add_routes
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/_MEIqpNxC7/clients/identity_client/settings.py", line 1, in <module>
    from .identity_apicalls import float_organization_account, admin_account, deserialize_state, create_child,\
  File "/tmp/_MEIqpNxC7/clients/identity_client/identity_apicalls.py", line 12, in <module>
    from .helpers import validate_fields, new_account, new_organization_account, \
  File "/tmp/_MEIqpNxC7/clients/identity_client/helpers.py", line 17, in <module>
    from .ledger import deserialize_state
  File "/tmp/_MEIqpNxC7/clients/identity_client/ledger/deserialize_state.py", line 3, in <module>
    from ..protocompiled import float_account_pb2, account_pb2,\
  File "/tmp/_MEIqpNxC7/clients/identity_client/protocompiled/float_account_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: cannot import name 'descriptor' from 'google.protobuf' (/tmp/_MEIqpNxC7/google/protobuf/__init__.pyc)

Pyinstaller error with google.protobuf

**Comment by htgoebel** [comment]
@GraphicalDot A hook for google.protobuf has been merge a few weeks ago. Please use the current development head.

**Comment by GraphicalDot** [comment]
I have installed pyinstaller dev branch 
(env) 1 vagrant@sawtoothclient:~/env/sawtoothclient/Application$ pyinstaller -v
4.0.dev0+g9ed0c843

But now a different error pops out

`
31 INFO: PyInstaller: 4.0.dev0+g9ed0c843
32 INFO: Python: 3.7.5
33 INFO: Platform: Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
34 INFO: UPX is not available.
37 INFO: Extending PYTHONPATH with paths
['/home/vagrant/env/sawtoothclient',
 '/home/vagrant/env/sawtoothclient/Application']
38 INFO: checking Analysis
115 INFO: Appending 'datas' from .spec
137 INFO: checking PYZ
176 INFO: checking PKG
199 INFO: Building because toc changed
200 INFO: Building PKG (CArchive) PKG-00.pkg
Traceback (most recent call last):
  File "/home/vagrant/env/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==4.0.dev0+g9ed0c843', 'console_scripts', 'pyinstaller')()
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/__main__.py", line 112, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/building/build_main.py", line 732, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/building/build_main.py", line 679, in build
    exec(code, spec_namespace)
  File "main.spec", line 35, in <module>
    console=False )
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/building/api.py", line 433, in __init__
    upx_exclude=self.upx_exclude
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/building/api.py", line 197, in __init__
    self.__postinit__()
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/building/api.py", line 282, in assemble
    pylib_name=pylib_name)
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/archive/writers.py", line 334, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/archive/writers.py", line 61, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/archive/writers.py", line 86, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/archive/writers.py", line 375, in add
    code = get_code_object(nm, pathnm)
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/building/utils.py", line 625, in get_code_object
    co = _load_code(modname, filename)
  File "/home/vagrant/env/lib/python3.7/site-packages/PyInstaller-4.0.dev0+g9ed0c843-py3.7.egg/PyInstaller/building/utils.py", line 582, in _load_code
    loader = importer.find_module(modname)
AttributeError: 'NoneType' object has no attribute 'find_module'
`

**Comment by ScottYueqiang** [comment]
> @GraphicalDot A hook for google.protobuf has been merge a few weeks ago. Please use the current development head.

sorry, i not find the hook protobuf file now, is it Disabled? looking forward to your answer, thanks
