### ISSUE TITLE
Get compiled script directory via sys.executable returns 8.3 filenames (DOS SFN)

### ISSUE THREAD

**Issue by Neo23x0** [pyinstaller/pyinstaller#1282]
I try to get the current directory name of the compiled script by the use of the following statement:
```application_path = os.path.dirname(os.path.realpath(sys.executable))```

When I run the python script it returns:
***C:\Users\neo\Downloads\loki-master***

When I run the compiled executable, it returns:
***C:\Users\neo\DOWNLO~1\LOKI-M~1***

This is the old MS DOS 8.3 filename style called SFN. I use the application path to exclude it from a directory walk later on but the path returned by os.walk() is obviously different than the one returned by sys.executable. 

Is this a bug? Is there a way to retrieve the executable's full path?
I want to allow users to run the executable from other working directories.

**Comment by Neo23x0** [comment]
I fixed the problem myself by the use of win32api:
```
dos_path = os.path.dirname(os.path.realpath(sys.executable))
application_path = win32api.GetLongPathName(dos_path)
```

**Comment by tallforasmurf** [comment]
Could this be added to the doc? Where?

**Comment by codewarrior0** [comment]
Yes, this should be documented. PYI explicitly uses GetShortPathName to set the value of `sys.executable` - "to overcome the Python and PyInstaller limitation to run with foreign characters in directory names." (`pyi_path.c:157`)

In normal Python, `sys.executable` contains the full path to `argv[0]`. On Windows, argv[0] is encoded using an MS-DOS codepage. Renaming python.exe to something like `pyxěščřžýáíé.exe` (or putting it in a folder with that name) will result in a worthless `sys.executable` and the only way to get a good one is with the Win32 API (whose name escapes me) for getting the command line as wide characters (i.e. UTF-16 encoded).

**Comment by codewarrior0** [comment]
I kind of want to go through all of the bootloader code and add hungarian-notation to all of the string types to specify the encoding - `workpath_u8`, `argv_mbcs` and so on.

**Comment by htgoebel** [comment]
I'd prefer to have this fixed in `pyi_path.c`. But as I read your explanation I have the impression that we can't get this fixed as long as we are supporting Python 2.x Is this correct?

**Comment by codewarrior0** [comment]
> we can't get this fixed as long as we are supporting Python 2.x

Yes. `sys.executable` is broken, for most non-ASCII characters, on Python 2.x for Windows, even for vanilla Python without PyInstaller.

PyI's workaround of using a ShortFileName instead of encoding with `mbcs` improves support over vanilla Python's, but raises this issue of not being able to compare filenames easily. It is also not available for some filesystems, especially SMB network shares. This difference is responsible for [the paths I observed here](https://github.com/pyinstaller/pyinstaller/issues/1224#issuecomment-103727941) and may be responsible for that issue in some way also, as he notes that the issue only happens on D:\ and not C:\. It also needs to be documented as it deviates from vanilla Python's behavior.

**Comment by codewarrior0** [comment]
Besides, shouldn't you be using `sys._MEIPASS` instead of `dirname(sys.executable)` (or `__file__` etc) when your app is intended to be frozen? 

I wonder what the encoding for `_MEIPASS` is. It's probably UTF-8, but if it's a `bytes` type on python2 it will run into the snag of the Windows filesystem functions using the ANSI variants and trying to interpret  it as `mbcs` encoded. Maybe `_MEIPASS` could be changed to a `unicode` type?

**Comment by Neo23x0** [comment]
That's what my code looks like. (still clumsy but working)

```
        if getattr(sys, 'frozen', False):
            application_path = os.path.dirname(sys.executable)
        elif __file__:
            application_path = os.path.dirname(__file__)
        # unknown if still necessary 
        if application_path == "":
            application_path = os.path.dirname(os.path.realpath(__file__))
        if "~" in application_path:
            application_path = win32api.GetLongPathName(application_path)
```

**Comment by htgoebel** [comment]
As codewarrior wrote, you must use `_MEIPASS`, see https://pythonhosted.org/PyInstaller/#adapting-to-being-frozen

**Comment by Neo23x0** [comment]
Doesn't work for me. I build my file in one file mode (-F). Using _MAIPASS I get the path of the extracted archive contents but not the path where the executable resides. 
```
C:\Users\neo\AppData\Local\Temp
```

**Comment by codewarrior0** [comment]
Oh, you're actually using the app by putting it in a folder where it is going to work. Then what you're doing with GetLongFileName will do what you want, but with the caveat that it won't work on filesystems that don't support 8.3 filenames - you'd have to go directly to GetCommandLineW (as I noted a few comments ago) if you need that to work.
