### ISSUE TITLE
Add C functions for easy access to runtime options in PYZ

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1315]
From https://github.com/pyinstaller/pyinstaller/issues/1106#issuecomment-105516391:

>PYZ already supports runtime options, which are currently only one letter options like "v" or "u". Most are boolean, only "W" contains some value. Accessing them is as easy as shown in https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/common/pyi_pythonlib.c#L134

Add a function to the C-code to allow easy access to these options. This may also be useful for #1206.

**Comment by htgoebel** [comment]
Some remarks on this:
- CArchive.add() currently does not write any option-value
- PKG.assemble() does not pass any value for options.
- We have no test-cases verifying run-time options. See #1316
- Currently there is no runtime-option having a value. Even `W` (which setts the warning-options) does not have a value, but the later part of the option name is taken as the value.

**Comment by codewarrior0** [comment]
> Currently there is no runtime-option having a value. Even W (which sets the warning-options) does not have a value, but the later part of the option name is taken as the value.

This is because the only other place to put the value would be in the file's data. The TOC tuple has (internal name, filename, typecode), but in the C code, all we have is (internal name, typecode). So the two choices are to have `"W ignore"` as the internal name with no file data, or to just have `"W"` as the internal name and `"ignore"` as the file data. Unless we need to have an option with a few kilobytes of value, I'd rather keep using the internal name for the option value, since then the value will show up in the archive-viewer output.

**Comment by htgoebel** [comment]
I'll leave this decision to you, as you know the bootloader code much better then me. If we (say: you :-) are going to implement some access-function we could change this easily if need arises.

**Comment by codewarrior0** [comment]
Implemented in 388dfc1a2c66757ee39a0f9803b76565678438c4. Option value follows the option name in `ptoc->name` with any one character separating them. 

Hrm. Should probably define a delimiter between the name and value. And since OPTION entries don't get file data stored anyway, we could allow TOC entries like ("W", "ignore", "OPTION") where we insert the delimiter ourselves.

**Comment by htgoebel** [comment]
Thanks for implementing this :-)

> we could allow TOC entries like ("W", "ignore", "OPTION") and insert the delimiter ourselves when building the archive.

Sounds reasonable,
