### ISSUE TITLE
Set input and output encoding when calling subprocesses

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1325]
Currently PyInstaller calls the subprocess and simply assumes some (undefined) encoding of the data passed to and from the subprocess. This already is a problem in python3 (see e.g. dccc6616eef), should be fixed in the develop-branch too. Further dccc6616eef assumes fixed utf-8, which may be wrong.

**Proposed solution:**

1. Pass some env-variables to the `subprocess.*` calls to ensure e given encoding to be used by the subprocess
  1. `PYTHONIOENCODING=UTF-8`
  2. some operation-system depentent values to make non-python programs use the encoding
  3. Additionally for Unix-Systems we should set `LC_ALL=C` to ensure English output
2. Encode data send to the subprocess and decode data read from the subprocess
3. Do *not* use `universal_newlines`, because it's behavior has changed in Python 3 and it now sets and encoding derived from the current locale.

**Open issues:**
- How to set the encoding for `LC_ALL=C`?
- How to set encoding on other platforms, esp. Windows ans OS X?

More ideas of issues on this topic anybody?

**Comment by htgoebel** [comment]
Addendum:
- `LC_ALL` takes precedence over other `LC_*` and over `LANG` (http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html), so there is no need to remove or set these.
- There is no `C.UTF-8` locale in glibc (https://sourceware.org/bugzilla/show_bug.cgi?id=17318)
- In my tests, `LC_ALL=UTF-8 date` works as expected (giving a `C`-locale output).
- There seams to be subtile differences between `C` and `en_US.UTF-8`, see http://unix.stackexchange.com/questions/88767/what-are-the-implications-of-setting-lc-all-on-solaris

**Comment by htgoebel** [comment]
* There are quite some [Difference between C.utf8 and en_us.utf8](http://h30499.www3.hp.com/t5/General/Difference-between-C-utf8-and-en-us-utf8-points/td-p/4418194?notmigrated=#U4418197)
* There is a great FAQ by Markus Kuhn: https://www.cl.cam.ac.uk/~mgk25/unicode.html, which contains some infos about C-programs.
* A nice example for how to test the expected result https://github.com/ansible/ansible/issues/10698:
```
$ LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 touch "Álvaro"
$ LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 ls
Álvaro
$ LANG=en_US LC_ALL=en_US ls
??lvaro
```
* https://bugs.python.org/issue19846 has a longer discussion about env-vars and encoding. The implications of changing the encoding seam to effect how filesnames and command-line args are interpreted.

**Comment by htgoebel** [comment]
`PYTHONIOENCODING` seams to no effect how filesnames are interpreted: On my system, which uses UTF-8 per default, I create a file named `äöü` and try to open it with different combinations of env-vars.
```
$ python -c "open(u'\xe4\xf6\xfc', 'w')"                      
$ PYTHONIOENCODING=UTF-16 python -c "open(u'\xe4\xf6\xfc')"
$ PYTHONIOENCODING=UTF-16 LC_ALL=C python -c "open(u'\xe4\xf6\xfc')"                                                                                   
Traceback (most recent call last):                                                     
  File "<string>", line 1, in <module>                                                 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)                                                                          
$ LC_ALL=C python -c "open(u'\xe4\xf6\xfc')"Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

**Comment by htgoebel** [comment]
Some more test:
```
$ PYTHONIOENCODING=UTF-16 LC_ALL=KOI8-R python -c "import os, sys, locale; print(sys.getfilesystemencoding(), sys.stdin.encoding, locale.getpreferredencoding())" 
('KOI8-R', 'UTF-16', 'KOI8-R')
$ LC_ALL=KOI8-R python -c "import os, sys, locale; print(sys.getfilesystemencoding(), sys.stdin.encoding, locale.getpreferredencoding())"
('KOI8-R', 'KOI8-R', 'KOI8-R')
```

Intermediate conclusion:
* When spawning python programs, set PYTHONIOENCODING=UTF-8 to ensure all characters con be encoded and decoded correctly.
* When spawning a different program, *decode* using `sys.getfilesystemencoding()`, which according to the Python issue mentioned above should be read as "OS encoding".

**Comment by codewarrior0** [comment]
* When spawning python programs, set PYTHONIOENCODING=UTF-8 to ensure all characters con be encoded and decoded correctly.
* When spawning a different program, *decode* using `sys.getfilesystemencoding()`, which according to the Python issue mentioned above should be read as "OS encoding".

This is a valid conclusion, at least on Linux and OS X, and for Python 3 only.

For Python 2, things change depending on whether your policy toward filenames is to use `str` or `unicode`. If it's `str` you don't have to set PYTHONIOENCODING or decode the output. If it's `unicode`, do so. On Python 2, you need to have a policy for filenames, otherwise you will have UnicodeDecodeErrors for the rest of your life. *(If you choose `str`, you sacrifice compatibility with non-codepage filenames on Windows. If you choose `unicode`, you'll have countless headaches as Python 2 doesn't provide everything as `unicode`)*

When calling non-Python programs, if you are reading filenames from its output, `sys.getfilesystemencoding()` is correct. If you are reading something *other than filenames*, then the decoding will be specific to that program and what you're expecting to read from it.

If you're calling non-Python programs on Windows, you need to find out what encoding that program uses for its output - it could be ANSI, or UTF-8, or UTF-16, or possibly even OEM if it thinks it's an MS-DOS program.

**Comment by htgoebel** [comment]
@codewarrior0 Now that you are the most experienced regarding this encoding-stuff, I'd be happy if you could take this issue.

**Comment by codewarrior0** [comment]
Sure. I think the simplest and most flexible solution is to have `exec_command` set PYTHONIOENCODING=utf8 and decode output using utf8 on Python 3, to not do either on Python 2, and have an optional `encoding` kwarg to use on Python 3 for calling non-Python programs.

**Comment by codewarrior0** [comment]
Fixed this in a commit I'll be pushing shortly, once it passes the test suite.

On Python 3, `exec_python` uses `PYTHONIOENCODING` to control the encoding on both sides of the pipe.

On Python 3, `exec_command` decodes output using the FS encoding by default, since the common case is to read filenames from command output (and the other common case is version numbers, which are ASCII, which is a subset of any FS encodings in use today). `exec_command` also gains an `encoding=` kwarg to use when you need to explicitly specify an encoding.

On Python 2, no decoding is done - command output is always returned as `str`. We will revisit this if we ever decide to change our filename policy on Python 2 to `unicode`, which is not something that can be done in a day.

I assume that `exec_python` will never call a Python 3 program from Python 2, or vice versa.
