### ISSUE TITLE
Make python3 bootloader support Python 2.7 again

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1328]
* Some note about this: https://github.com/pyinstaller/pyinstaller/wiki/Python-3-Port#python-2-compatibility
* Related "master" issue: #666

**Comment by htgoebel** [comment]
Some ideas from me. Please tell me if this could work:
*  If my analysis is correct, the argument and result types are *not* encoded into the external function name anyhow. Some we only need to keep the compiler happy at compile time.
* So it should be enough to define a wrapper for each function using `wchar_t *` which casts `char *` to `wchar_t *`and calls the original function.I'd call these casting functions <funcname>_C (for character).
 * Another solution would be to write this cast explicitly where the function is called.
* Then we'd "only" need to re-establish the code for Python 2 and destinguish between Py 2 and Py3 (code for which can be found in  `pyi_pylib_load`.

@matysek @codewarrior0  @tallforasmurf @bjones1 @leycec  What do you think?

Some snippets.
* List all used Python functions: `grep -h PI_Py * | sed 's/^.*\(PI_Py\w*\).*/\1/' | sort -u`
* List all  Python function calls  `grep -h PI_Py * | sed 's/^.*PI_Py/PI_Py/' | sort -u`

**Comment by codewarrior0** [comment]
I believe you are correct about the pointer types of the functions with relation to the ABI (the function linkages). This means you don't have to use `#ifdef` to change the function signatures, so you don't have to build two sets of bootloaders, one for each Python version.  But as it turned out, not many function signatures were changed from `char *` to `wchar_t *`. It may be prudent to instead declare the ones that changed as, e.g. `PI3_Py_SetPythonHome`, so the compiler will still be able to check that we're not passing a `char *` to something that needs a `wchar_t *`. Then only call those when loading a Python3 DLL, and call the old ones when loading Python2.

What's more important than the signatures is that the actual implementations of the functions will care about the encoding of the string. So you will have to use the runtime knowledge of which version of the Python DLL is being loaded to encode the strings correctly, and have a fixed policy for what encoding the `char *` strings will be in when used in the bootloader internals (`ARCHIVE_STATUS` etc). It looks like most of the time this encoding is already UTF-8. If we can enforce the policy, UTF-8 is sufficient.

I've been going through the bootloader and noting what the sources of different string values are and their encodings, and most of the warts are centered around those parts of Python which, on Windows, only accept filenames as codepage-encoded strings. On Mac and Linux, those same parts accept UTF-8-encoded and locale-encoded strings respectively.

Because codepage-encoded strings cannot represent all possible filenames on a Windows system (as Windows filenames are *defined* to be encoded as UTF-16), somebody has come up with the workaround of using MS-DOS ShortFileNames, which are always codepage-encoded and can represent all possible filenames, but are not always available. SFNs can be disabled on a whole-system or a per-filesystem basis, and are not available for some network shares. 

Currently, PyInstaller uses these SFNs to open the archive file, and for a few other things. Ideally, the bootloader should use proper Unicode for opening files and only pass SFNs to the Python APIs that require them for compatibility. On Python 3.3 we should be able to remove SFNs entirely.

Here are the Python APIs used by the Python 2.7 version of PyInstaller  that use `char *`. I have cross-checked them in the API docs for both Python versions to find out the meaning and encoding of the `char *` argument and noted where the function signature was __changed__ in Python 3.3:

Many of these might not even be used in the code anywhere - I just grabbed them from `pyi_python.h` and later noticed that in the Python 3.3 version many of them are commented out and noted as "unused".

```
# APIs where the `char *` is a filename. 
# On Windows, we use SFNs for these, and should only do so for Python 2.7.
# These APIs' signatures were CHANGED in Python 3.3:
EXTDECLPROC(void, Py_SetPythonHome, (char *));
# Python 3.3: void Py_SetPythonHome(wchar_t *home)
EXTDECLPROC(void, Py_SetProgramName, (char *));
# Python 3.3: void Py_SetProgramName(wchar_t *name)

# ---
# APIs where the `char *` is a module name.
# On Python 2.7, module names are identifiers and can only be ASCII-encoded.
# On Python 3.3, newer forms of these APIs are provided that accept a `unicode` as a `PyObject *`. 
# We should use the newer forms of the APIs on Python 3.3

EXTDECLPROC(PyObject *, PyImport_ExecCodeModule, (char *, PyObject *));
# Python 3.3: PyObject* PyImport_ExecCodeModuleObject(PyObject *name, PyObject *co, PyObject *pathname, PyObject *cpathname)
EXTDECLPROC(PyObject *, PyImport_ImportModule, (char *));
# Python 3.3: PyObject * PyImport_ImportModuleLevelObject(PyObject *name, PyObject *globals, PyObject *locals, PyObject *fromlist, int level)
EXTDECLPROC(PyObject *, PyImport_AddModule, (char *));
# Python 3.3: PyObject* PyImport_AddModuleObject(PyObject *name)
# ---

# APIs where the `char *` is source code. I believe it is defined to be a bytestring, 
# as the Python compiler will look for various `coding` markers.
EXTDECLPROC(int, PyRun_SimpleString, (char *));

# APIs where the `char *` may be a filename but is defined to be a bytestring
# This function's signature was CHANGED in Python 3.3.
# Python 3.3: void PySys_SetArgv(int argc, wchar_t **argv)
EXTDECLPROC(int, PySys_SetArgv, (int, char **));

# APIs where the `char *` is an identifier
# Identifiers in Python 2.7 are ASCII encoded. In 3.3, the encoding is not mentioned
# in the API docs so a look into the Python 3.3 source code may be needed.
EXTDECLPROC(int, PyObject_SetAttrString, (PyObject *, char *, PyObject *));
EXTDECLPROC(int, PySys_SetObject, (char *, PyObject *));

# APIs where the `char *` is a bytestring
# NOTE: these API are renamed to PyBytes_* in Python 3
# but depending on how PYI uses it, PyString_* may be the right choice
EXTDECLPROC(PyObject *, PyString_FromStringAndSize, (const char *, size_t));
EXTDECLPROC(char *, PyString_AsString, (PyObject *));

# APIs where the `char *` has an unknown encoding
# PyDict_GetItemString still takes a `char *` on Python 3
EXTDECLPROC(PyObject *, PyDict_GetItemString, (PyObject *, char *));

# APIs where the `char *` is a format string for building/parsing values
EXTDECLPROC(PyObject *, Py_BuildValue, (char *, ...));
EXTDECLPROC(PyObject *, PyObject_CallFunction, (PyObject *, char *, ...));

# The first `char *` is an identifier; the second `char *` is a format string for building/parsing values
# An alternative to this function is PyObject_CallMethodObjArgs
# which takes a `PyObject *` instead of the first `char *` and thus
# supports Unicode identifiers on Python 3.3
EXTDECLPROC(PyObject *, PyObject_CallMethod, (PyObject *, char *, char *, ...) );

# APIs where the `char *` has a completely unknown encoding
# This API's signature was CHANGED in Python 3.3
# New signature: void PySys_AddWarnOption(wchar_t *s)
EXTDECLPROC(void, PySys_AddWarnOption, (char *));

```

Object attribute names (i.e. identifiers) in Python 2 must be ASCII-encoded `bytes`. In Python 3, which allows unicode identifiers, the attribute names may be `unicode`.

There is the additional "gotcha" that the import machinery on Python 2.7 for Windows is written to use only the legacy codepage versions of the Windows APIs, so for things like the module search path (`Py_SetPath` on 3.3, `PYTHONPATH` and `Py_SetProgramName` on 2.7), the strings MUST be codepage-encoded. This was completely fixed in Python 3.3: [python#3080](http://bugs.python.org/issue3080), [python#9425](http://bugs.python.org/issue9425)

**Comment by htgoebel** [comment]
Okay, I'll give it a try.

**Comment by matysek** [comment]
> It may be prudent to instead declare the ones that changed as, e.g. PI3_Py_SetPythonHome,

@codewarrior0 I would rather see the approach to make python3 default one and implement some hooks for python 2 not vice versa. So I would rather see PI2_Py_SetPythonHome etc.

**Comment by htgoebel** [comment]
* List of EXTDECLPROC: `grep -h PI_Py * | sed 's/^.*PI_\(Py\w*\).*/\1/' | sort -u | while read ; do grep -h $REPLY *.h ; done | grep EXTDECLPROC`
* List of EXTDECLPROC using `char *` ot `wchar_t *`: ... as above + ` | grep char`

**Comment by htgoebel** [comment]
I did some work on this in https://github.com/htgoebel/pyinstaller/tree/issue-1328-bootloader-for-python2. This compiles, but does not yet run:
* In python3-branch, PyInstaller fails to work with Python 2 due to import errors: `import importlib.machinery`
* When putting the compiled bootloader into develop-branch, it errors out with `Cannot open self /tmp/dist/test1 or archive /tmp/dist/test1/test1.pkg`. I don't think, this is hard to hack.

Feel free to add comments are even pull-requests to my repo-branch. I'll not have time to work on this before Thursday.

**Comment by htgoebel** [comment]
@matysek I gave the functions the prefix `PY_PI2` and they are all defined in `pyi_python27_compat`. So removing them later is not much of a problem.

**Comment by matysek** [comment]
> This compiles, but does not yet run:
> 
> In python3-branch, PyInstaller fails to work with Python 2 due to import errors: import importlib.machinery
> When putting the compiled bootloader into develop-branch, it errors out with Cannot open self /tmp/dist/test1 or archive /tmp/dist/test1/test1.pkg. I don't think, this is hard to hack.

@htgoebel Today i fixed this issue with python3 branch. It was connected with dirname(). See my latest commits on python3 branch.

Btw. travis now also compiles the bootloader.

**Comment by htgoebel** [comment]
Thanks to martins fix, I made considerable process today (while spending a lot of time debugging). The bootloader from my branch, when copied to develop-branch, passes most of the basic and import tests when using asci-only paths.

When running the frozen exe on a non-ascii-only-path, it fails due to this line: https://github.com/pyinstaller/pyinstaller/blame/python3/bootloader/src/pyi_archive.c#L487
