### ISSUE TITLE
OS X - pyinstaller does not follow relative paths e.g. @executable_path

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1338]
When PyInstaller tries to resolve dynamic dependencies of binaries then it cannot find files that points to paths like `@executable_path/../.Python` and it complains:
```
ERROR: Can not find path @executable_path/../.Python
```

**Comment by htgoebel** [comment]
What exact is the problem? The relative path-part `..`, or the symbolic path `@executable_path`?

**Comment by matysek** [comment]
The @executable_path. I need to find out more.

**Comment by tallforasmurf** [comment]
Maybe you already know, but the symbolic paths @executable_path and @loader_path should only appear in Mac OS app bundles. They allow some freedom in locating resources within the bundle. In particular Qt does this in order that DLLs in folders that are like, nested 4 deep inside Resources, can find common dependencies. Such a DLL can have a reference to `@loader_path/QtXxxx` -- instead of having to do  `../../../Contents/MacOS` or such. The new (in Qt5) QWebEngine has a horribly complicated folder arrangement that depends on this.

**Comment by akshayaurora** [comment]
ok,  it turns our the issue with the kivy package was due to a misplaced link that was not in the correct place the relative to @executable_path. Thanks to @matysek  for figuring this out.
