### ISSUE TITLE
Base main() on Python's Modules/python.c 

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1340]
Refactor our code to work like Python's `main()` does:
- convert all arguments in `argv` to wchar_t
- call `Py_Main()` (we'd call something like `PyInstaller_Main()`.

Rationale:
* The Python developers have a lot more experience for how to implement Unicode-support. Let's benefit from this.
* This would make PyInstaller mimic what Python does.
* It's easier to follow changes to what Python does.

NB1: As long as we support Python 2.7, `PyInstaller_Main()` need to take both `argv` and `argv_char`.
NB2: `_Py_char2wchar` is defined in `Python/fileutils.c`.

The code for `main()` is to be found in `Modules/python.c` and `Py_Main()` in `Modules/main.c`

**Comment by codewarrior0** [comment]
It's worth noting that on Windows, the UTF-16 wchar_t form of argv is available as `__wargc, __wargv` So, on python 2.7, we can use the actual form of argv for PyInstaller internal stuff (archive loading etc), and pass the codepage-encoded forms to the Python2.7 APIs that require them (Py_SetArgv etc).

**Comment by codewarrior0** [comment]
Py_Main order of operations, modulo our requirements (non-interactive, no `-c` or `-m`):

- Handle options `-E` and `-R`
- Check environ `PYTHONHASHSEED`
- Reset warn options
- Handle all options other than `-E` and `-R`
- Set stdin/out/err to BINARY mode, disable line buffering
- Py_SetProgramName
- Py_Initialize
- PySys_SetArgv
- Run main script by inserting it into sys.path and calling `runpy._run_module_as_main`

**Comment by codewarrior0** [comment]
Python has a lot of C-level string handling code that puts ours to shame. For example, the `_Py_char2wchar` function you mentioned is able to decode filenames on Linux that simply can't be decoded with the locale encoding (even if it's UTF-8 or UTF-16) - since Linux defines filenames to be bytestrings, they aren't required to be in any encoding (unlike Windows which enforces UTF-16, and OS X which enforces UTF-8). Python's function will take those "undecodable" bytes and decode them as UTF-16 surrogate characters, putting the byte's value in the surrogate's least significant byte. This way, the reverse function `_Py_wchar2char` can re-encode the text to bytes and get the exact same bytestring back. 

Unfortunately, the implementation of at least one of those functions relies on the python object PyUnicode and some of its associated functions. Since the python.exe runner is linked to the python .so/.dll at link time, it has full access to all of those at the beginning of main(), but we have no such luxury. Thus, we may want to copy and adapt large swathes of Python's text decoding/encoding code so we can make use of it prior to loading the python lib.

**Comment by codewarrior0** [comment]
Python's treatment of `setlocale()`:

In main(), before calling Py_Main, the LC_ALL locale is saved and then set from the current environment. Then, argv is converted to wide strings using _Py_char2wchar (which may call mbstowcs, or an internal "surrogateescape" python function if mbstowcs fails, or a simple UTF-8 decode when on OS X). Then, the LC_ALL locale is set back to the saved value before calling Py_Main.

In Py_Main, the same save-set-restore mantra is repeated when getting the PYTHONWARNINGS environment variable to convert it to a wide-string (except on Windows, where _wgetenv is used instead, and on OS X, where a UTF-8 decode is used).

In Py_Initialize, LC_CTYPE is set from the environment "for good" - the previous value isn't saved, and it isn't touched again after that. Code in Py_Main that comes after the Py_Initialize call is able to call _Py_wfopen, _Py_wchar2char, mbstowcs etc without setting the LC_CTYPE first.

So that's one bug in our current code - we set LC_CTYPE back to the saved value some time after calling Py_Initialize, when we should just acknowledge that Py_Initialize set it already and don't touch it from then on.

**Comment by htgoebel** [comment]
Thanks for your detailed analysis. Are you going to code this?

**Comment by codewarrior0** [comment]
Yes. I think I've done enough research to know what to be careful with. I'll start by copying some of Python's text encoding code, then split main off of pyi_main and add wmain for Windows, then go through and make sure all the char * are converted to wchar_t * using the correct text encodings. I should be able to remove those setlocale calls I added earlier and only use setlocale around the parts where mbstowcs needs to work correctly.

**Comment by htgoebel** [comment]
Fine. Please merge your branch later using a pull-request or `--no-ff`. This has the benefit: All the related work is on one stream of commits, which helps understanding commit-history in a few years

**Comment by codewarrior0** [comment]
Will do, chief.

**Comment by codewarrior0** [comment]
Made some progress on this last night. main/wmain/WinMain/wWinMain are now separate from pyi_main, which uses both `wargv` and `argv` for now. Found a complication where MinGW 4.x doesn't allow wmain/wWinMain to be used, even with `-municode` (fixed in MinGW 5.x, I believe), so I came up with a workaround that gets `wargv` using Windows APIs. 

There's a lot of clutter on the branch, so I'll clean it up when I'm almost done and ready to merge. A few commits aren't directly related so I'll merge those separately.

Here's something you linux-guys might be able to find out for me. What is the proper way to make `wcslen`, `wcsdup` etc. properly declared? Just including <wchar.h> doesn't work for Travis - I had to define _GNU_SOURCE before importing to get the declarations. I think the "right" way might be to add a CFLAG like `-std=c99` to change the C version. Here's a short snippet that demonstrates the problem:

```
#include <wchar.h>

void foo() {
    wchar_t * str = L"foobar";
    int len = wcslen(str);
}
```

Compile with `-Wimplicit-function-declaration -Werror` to find out if the declaration is present.

**Comment by matysek** [comment]
@codewarrior0 I think the best way is to add `_GNU_SOURCE` to wscript like this:
```
ctx.env.append_value('DEFINES', '_GNU_SOURCE')
```
There are already several defines like that.

**Comment by codewarrior0** [comment]
Roger that, will do.

I have to make a note of this for posterity:

Filenames on OS X and Linux are defined to be `char *` type. This is what functions like `fopen` take as an argument on those platforms. PyInstaller handles these filenames internally as `char *` and for the most part, no kind of conversion is needed until it is time to pass them to Python 3 APIs. The Python 3 APIs which take filenames as `wchar_t` will expect them to be decoded using the "surrogateescape" error handler in order to handle Linux filenames, which are just bytestrings with no defined encoding. This is the main reason for copying and using _py_char2wchar when passing `wchar_t` strings to Python 3 APIs. (See also PyUnicode_EncodeLocale and PyUnicode_EncodeFSDefault).

Python itself stores filenames as `wchar_t *` at all times, but that is mostly because the PyUnicode implementation also uses `wchar_t *`. Actual Python 3 code uses the `str` type (aka PyUnicode) for filenames, so Python internally uses the "surrogateescape" encoding error mode on Linux to losslessly convert the `str` to and from bytestrings when calling filesystem functions (`fopen`, `opendir`, `stat` etc). 

However, filenames on Windows are defined to be `wchar_t *` type. The Windows API accepts `wchar_t *` and also provides us with `argv` and `envp` as `wchar_t *`.

This presents a complication: To store Windows `wchar_t *` filenames in the existing `char *` variables and ARCHIVE_STATUS fields, we encode them as UTF-8 using some functions in `pyi_win32_utils.c`. This presents a further complication: On Python 2, we're required to pass ANSI strings to some Python 2 APIs, and in a few places, we're mistakenly placing an ANSI string into a `char *` variable that's normally used to store a UTF-8 string. Oops.

So I see two possible solutions: 

- Change all of the filenames to `wchar_t`. This is a large amount of work and is not even that useful, as on OS X and Linux we need them to be `char *` anyway, which would introduce lots of pointless encode/decode steps. 

- Define the filename variables to be UTF-8 encoded on Windows.  Make absolutely sure that ANSI strings are never stored in these variables. The strings should only be converted to ANSI (optionally with MS-DOS filenames) immediately before sending them to the Python 2 APIs. On OS X and Linux, send them as-is to Python 2 APIs, and convert them to `wchar_t *` immediately before sending them to Python 3 APIs.

The second solution requires the least work and the least amount of code changes, so I'm going to go with that.

**Comment by codewarrior0** [comment]
I briefly recalled that on Japanese Windows systems, the path symbol is the Yen symbol '¥'. Thankfully, I found out this is just visual - it still uses the Unicode code point `U+005C` for backslash, but is just rendered as ¥ for... essentially historical reasons. During the Unicode transition, Japanese users were alarmed that their path separator suddenly changed to `\`, so MS changed the way it is displayed.

Likewise for Korean systems and '₩'

**Comment by codewarrior0** [comment]
This is more or less done. Now that we have `__wargv` I can finally take care of those persistent errors for non-ASCII executable paths.
