### ISSUE TITLE
Set up a Website again

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1360]
After the old trac-system was shut down, we only have the wiki. But The layout is not optimal, there is no navigation, etc. It's a wiki, but not a website.

I propose setting up a website again, based on Sphinx, and let travis push created pages to the webspace at github. The content of the old website (as of 2014-08-15) can be found at archive.org (https://web.archive.org/web/20140815102629/http://www.pyinstaller.org/).

What we need:
- Some decent template (any suggestions)?
- Know how to make travis push created pages to the webspace
- Some reasonable document structure

### Alternative

Alternatively we may only move the main page of the old trac website to github.

**Comment by codewarrior0** [comment]
If you want to use Sphinx, another option is readthedocs.org. It will build HTML from the Sphinx sources and host them for you, and github has an integration for pushing changes to readthedocs under "Webhooks & Services" which will make it act more like Travis, responding immediately to new commits. You can even use a CNAME to make it available as `docs.pyinstaller.org` instead of `pyinstaller.readthedocs.org`.

**Comment by bjones1** [comment]
Personally, I like the wiki. I was able to create a subprocess page and tweak its contents based on feedback fairly quickly and easily. While I'm comfortable with Sphinx, other contributors would need to know git + Sphinx, which may be a bit intimidating.

What about [editing the sidebar](https://help.github.com/articles/creating-a-sidebar/) to show only useful links, instead of everything? Although the layout won't as attractive as the old website, it can be decent. I'd be happy to work on this if you're interested. If, in the end, the wiki isn't sufficient, the content can always be ported to Sphinx.

**Comment by matysek** [comment]
@htgoebel Do you think this should be done for 3.0 milestone?

**Comment by htgoebel** [comment]
@matysek I would like to have this for the 3.0 release, but I'm afraid we will not make it until then. Fixing the bugs is more important.

**Comment by htgoebel** [comment]
Images are at https://web.archive.org/web/20140701132655/http://www.pyinstaller.org/wiki/PyInstallerLogos

**Comment by htgoebel** [comment]
I just pushed an initial version of a new web-site.The existing index.html is kept since this page still needs some tuning.

**Comment by htgoebel** [comment]
I'l take core of at least a elementary front page.

**Comment by htgoebel** [comment]
Okay, I've rebuild the old front-page and the logos page. Also added some dummy-pages redirecting to the wiki. Improvements, esp. optical ones :-) are welcome.

@tallforasmurf Feel free to change whatever you need. I added you to that repo, so you should be able to commit directly. Please mind to rebuild the pages when necessary by running `make`.
