### ISSUE TITLE
Failed to start compiled exe from non-ascii path on external usb-flash drive (FAT32, where short file names is not used)

### ISSUE THREAD

**Issue by TheSomeMan** [pyinstaller/pyinstaller#1396]
OS: Win7_x64
Python: 2.7.10 (x32)
PyInstaller: 2.1 (also I've tried latest dev)

Related issue: #1224

**How to reproduce**
Build any exe (for example "Hello word")
Create dir on USB-flash drive (FAT32), which contains non-ascii symbols:
* from command prompt: MD фыва
* or Python script: 
<PRE>
import os
os.mkdir(unicode('\xd1\x84\xd1\x8b\xd0\xb2\xd0\xb0', 'utf-8'))
</PRE>

Check that 8.3-style filenames is disabled for drive - from windows command promt run "dir /X" and check that only long filenames are exists.

Copy compiled hello.exe to the created folder and run it.

Error message:
<PRE>
F:\фыва>hello.exe
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "C:\Python27_x86_32\lib\site-packages\PyInstaller\loader\pyi_importers.py", line 508, in install
    sys.meta_path.append(FrozenImporter())
  File "C:\Python27_x86_32\lib\site-packages\PyInstaller\loader\pyi_importers.py", line 157, in __init__
    raise ImportError("Can't load frozen modules.")
ImportError: Can't load frozen modules.
</PRE>

The same effect occurs when you run from a network path (which is not attached as drive letter).

**The cause of the problem.**
When an application is launched from a usual disk, path to exe is passed as "8.3"-style pathnames (SFNs - Short File Names).
But on some drives "8.3-style" is disabled and in this case path to exe is passed as unicode string (UTF-8).
The problem is in the file:
`C:\Python27\Lib\site-packages\PyInstaller\loader\pyi_importers.py`,
class: `FrozenImporter`
method: `__init__`
<PRE>
                # Unzip zip archive bundled with the executable.
                self._pyz_archive = ZlibArchive(pyz_filepath)
</PRE>
ZlibArchive takes argument pyz_filepath and interprets it as string (with ascii symbols).
When 8.3-style is used - all symbols is ascii (0..127) (which is subset of UTF-8).
But in case when file-system is not supported SFNs and path contains non-ascii symbols, we have a problem.

**Solution**
Replace to this:
<PRE>
                # Unzip zip archive bundled with the executable.
                self._pyz_archive = ZlibArchive(unicode(pyz_filepath, "utf-8"))
</PRE>

**Comment by htgoebel** [comment]
@codewarrior0 Sound like your area of work :-)

**Comment by matysek** [comment]
@TheSomeMan Could you try the 'python3' branch? That's the place where main development happens.

**Comment by TheSomeMan** [comment]
'python3' branch have the same issue:
<PRE>
F:\фыва>hello.exe
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "c:\python27_x86_32\lib\site-packages\PyInstaller-3.0.dev0-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 573, in install
    sys.meta_path.append(FrozenImporter())
  File "c:\python27_x86_32\lib\site-packages\PyInstaller-3.0.dev0-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 194, in __init__
    raise ImportError("Can't load frozen modules.")
ImportError: Can't load frozen modules.
</PRE>

File: C:\Python27\Lib\site-packages\PyInstaller-3.0.dev0-py2.7.egg\PyInstaller\loader\pyimod03_importers.py 
class: FrozenImporter
method: \_\_init\_\_
line: 170
<PRE>
                # Unzip zip archive bundled with the executable.
                self._pyz_archive = ZlibArchiveReader(pyz_filepath)
</PRE>

**Comment by codewarrior0** [comment]
Thanks for the report.

I am in the middle of a lot of work overhauling PyInstaller's internal handling of filename strings. Your patch is coincidentally what I am working on now, so I can tell you what's wrong with it: When applied against the current branch HEAD, it breaks support for ShortFileNames on some systems (ShortFileNames allow characters from the current codepage, and not just ASCII - see #1323 for SFN with Japanese characters). If the sys.path entry for a PYZ is a ShortFileName, it will be MBCS-encoded and not UTF-8. MBCS-encoded filenames can be passed to open() on Python 2 without a decode step. The problem your patch fixes is that if the sys.path entry is *not* a ShortFileName, it will be UTF-8 encoded and must be decoded before passing to open() to make sure the wide-character Windows API is used.

And as @htgoebel noted, hard-coding the UTF-8 encoding is incorrect on Linux. Since Linux filesystem functions use bytes and not text, and because the application layer is responsible for encoding text using the current locale encoding before using it as a filename, the UTF-8 decode is simply wrong on Python 2. On Python 3 they are already unicode `str` type and we let Python's filesystem functions encode them to bytes (internally using the "surrogateescape" handler to preserve non-decodable filenames).

Technically, sys.path entries on Python 2 must only ever be MBCS-encoded, because Python 2's import subsystem is unfortunately implemented using the legacy ANSI version of the Windows API. But since we are using a custom FrozenImporter we can sidestep that, although we will still need to set the module's `__file__` to some sensible MBCS-encoded value (since it would be somewhat wrong to change `__file__` to either `unicode` type or UTF-8 encoding).

**Comment by codewarrior0** [comment]
@TheSomeMan Shall I notify you when my branch is ready for some more testing?

**Comment by TheSomeMan** [comment]
> Shall I notify you when my branch is ready for some more testing?
@codewarrior0 Of course, I'll be happy to help.

**Comment by codewarrior0** [comment]
@matysek Do you mind if I rebuild and commit the bootloader? Or would you rather take care of it yourself?

@TheSomeMan You can try the current `python3` branch if you're able to also rebuild the bootloader `(cd bootloader; waf all)`. I am very confident this is fixed, since I have a unit test that strips the MS-DOS filenames from a folder before running a built exe in it.

**Comment by TheSomeMan** [comment]
I just checked the latest version from the 'python3' branch - now everything works fine.

**Comment by codewarrior0** [comment]
Thanks for testing!

**Comment by matysek** [comment]
> Do you mind if I rebuild and commit the bootloader? Or would you rather take care of it yourself?
@codewarrior0 Could you do that?
* Are you going  to use mingw or msvc? I'd like to keep using mingw for Windows.
* Are you able to recompile both - 32/64 bit?

**Comment by matysek** [comment]
I will recompile for linux/osx.

**Comment by codewarrior0** [comment]
I will use MinGW-x64 v4.9.2. I can recompile both - I fixed the `--target-arch` option not too long ago.
