### ISSUE TITLE
To Fork or Not to Fork `modulegraph` and `altgraph`

### ISSUE THREAD

**Issue by leycec** [pyinstaller/pyinstaller#1412]
Courtesy this [intelligent request](https://github.com/pyinstaller/pyinstaller/pull/1393#issuecomment-129791901) from Señor Hartmut, I copy-pasta for your consumption my thoughts on a pending issue of some interest to _all_ PyInstalleros (i.e., PyInstaller developers):

> Should we internally fork the currently merely "branched" `modulegraph` and `altgraph` dependencies?

You probably already know which side of the argumentative fence I fall on.

## Let's Do This.

**[DANGER:** _Big wall of text follows. Proceed with ninja-like caution._**]**

I'm beginning to come to an unpopular opinion. No one's going to like it. Rebel without a cause time.

![Rebel Without a Cause](http://images2.fanpop.com/image/photos/11300000/Rebel-Without-a-Cause-james-dean-11379285-500-281.jpg)

In my humble opinion, **PyInstaller should internally fork `modulegraph` and `altgraph`.** Specifically, the embedded `lib.modulegraph` and `lib.altgraph` packages should be moved out of `lib` and into the main codebase. All existing copyrights and attributions should, of course, be preserved. All pretense of PyInstaller merely embedding or branching these libraries should be dropped.

_Yeah_. I just dropped the fork bomb. Why? A few reasons (in no particular order):

* Ron's not the easiest volunteer to work with. I'm sure he's a great guy. He must be, because `modulegraph` and `altgraph` are both unadulterated awesome-sauce. Nonetheless, I haven't particularly enjoyed my online interactions with Ron and wouldn't necessarily want to repeat the experience. (It's probably an irreconcilable personality conflict. Again, I'm sure he's awesome.)
* Ron, by his own admission, no longer has much time to devote to open-source development. Hence, `modulegraph`'s [moribund commit state](https://bitbucket.org/ronaldoussoren/modulegraph/commits/all). For all intents and purposes, these libraries are on the cusp of immanent bit-rot... if not death.
* Ron has an unfortunate history of committing changes that break public API backwards compatibility. A recent example is his refactoring of the public `load_module()` and `scan_code()` methods into private `_load_module()` and `_scan_code()` methods, which famously broke [`py2app`](https://stackoverflow.com/questions/25394320/py2app-modulegraph-missing-scan-code) a few years ago. Somewhat hilariously (...but not really), `py2app` [still appears](https://bitbucket.org/ronaldoussoren/py2app/issues/156/virtualenvpy-recipe-calls-methods-renamed) to be broken in this respect. Whereas PyInstaller embeds PyInstaller-specific versions of these libraries, `py2app` imports the system-installed versions of these libraries. The latter approach is _usually_ the **R**ight **T**hing to **D**o <sup>TM</sup>, until it isn't.
* **These libraries are the beating heart of PyInstaller.** No, really. You can subtract out any other embedded library and still get a somewhat-kind-of-maybe-working PyInstaller. Subtract out `modulegraph` and `altgraph`, however. What are you left with? A big fat smoking pile of rubble-strewn ashes. (Which is to say, nothing.) PyInstaller increasingly requires non-trivial changes to these libraries, which _absolutely_ makes sense. These libraries form the algorithmic core of all PyInstaller logic. Naturally, PyInstaller needs to occasionally change this logic and hence these libraries. That's inescapably baked into the fabric of our Universe. :stars: 
* Downstream (i.e., PyInstaller) changes are unlikely to be submitted upstream (i.e., to the official `altgraph` and `modulegraph` repositories), but _must_ nonetheless be occasionally made to support PyInstaller-driven requirements (e.g., SWIG, `six`). To say this complicates synchronization between the two projects is an understatement. "Why you no submit changes upstream?", you are probably pondering. Again, a few reasons:
  * **Mercurial (`hg`) is surely the devil's spawn.** I don't like it; I don't want to use it; when I am infrequently forced to use it, I reteach myself the entire subcommand set, how branches work, what the best equivalent of `git rebase` is, and so on. Every time. (_Not fun._)
  * **BitBucket isn't much better.** I don't like it; I don't want to use it; when I am infrequently forced to use it, I grit my teeth, gnash my mouth, and weep bitter granular tears. PyInstaller being hosted on a different site prevents sane communication between the two projects, complicating such otherwise simple tasks as pinging a particular developer for attention.
  * See _"Ron's not the easiest volunteer to work with."_
  * **Time.** There's only so much of it in the universe, and I squander enough on my existing crop of open-source projects. Adding yet another to the mix is not my idea of a volunteer weekend well-spent.
  * **Benefit.** There's no tangible benefit, to me, to submitting `altgraph` and `modulegraph` changes upstream. If it works in PyInstaller, I'm largely satisfied. The only other prominent consumer of these libraries appears to be `py2app`. For obvious reasons, I'm _not_ overly concerned about assisting that project. (I wish them luck, of course.)

**Comment by matysek** [comment]
@leycec Look here: https://github.com/modulegraph  There you could put the forked repositories.

**Comment by matysek** [comment]
I do not have strong opinion. If you think it is necessary then go ahead.

**Comment by htgoebel** [comment]
I still have to think about this and make up my mind.

Independently of whether we "fork" or note, we should keep some link to benefit from upstream changes.
So we have two technical issue to solve:
1. connecting mercurial an git
2. Merging only one sub-directory into out repository - for this http://www.hardcoded.net/articles/git-subtree-merging-low-level-plumbing has sum hints, but this needs to be tested thoroughly.

**Comment by leycec** [comment]
> Independently of whether we "fork" or note, we should keep some link to benefit from upstream changes.

:+1: 

> 1. connecting mercurial an git

While connecting Mercurial to Git _is_ feasible, all of the open-source bridges I've uncovered have varied from mildly to disastrously broken – presumably due to there existing no clean mapping between dissimilar Mercurial and Git concepts.

## Mercurial Branches: Why They Suck and You Should Hate Them

To highlight only one of the many discontiguities between the two systems, let's talk branches.

What Git calls "branches," Mercurial calls "bookmarks." (So far so good.) What Mercurial calls "branches," **Git has no equivalent concept for.** Whereas Git branches are lightweight commit pointers _external_ to actual commits, Mercurial branches are heavyweight commit metadata _embedded_ in every commit of that branch. To compound matters, one Mercurial branch may have **[**1, _n_**]** multiple HEADs – all but one of which may be anonymously unnamed. (Think CVS or Subversion branches, only with extra crazy.)

## Mercurial: Why Must You Do Everything Badly?

Of course, branches are hardly the only areas in which Git and Mercurial disagree.

Mercurial tags are plaintext entries of a physical `.hgtags` file, whereas Git tags are abstract repository objects in the `refs/tags` namespace. (Guess which is the better approach.)

Mercurial revision numbers non-deterministically depend on the order in which changesets are fetched, whereas Git revision numbers deterministically depend on the commit topology of the current branch. (Guess which is the better approach.)

Mercurial also supports a number of esoteric concepts like "obsolescence markers," "phases," and "namespaces." Git appears to have no equivalent concepts. (Probably a good thing.)

## `git-remote-hg`: The Slow Road to Nowhere

Is any of that a problem?

It was in all of the `git-hg`-style wrappers I tested. The most promising _was_ [`git-remote-hg`](https://github.com/felipec/git-remote-hg), which once resided in the official `git` codebase until its [author](https://github.com/felipec) insisted on repeatedly reducing the entire `git` mailing list to a smoking cesspool of incendiary trollbait. (**Drama.** It sucks.)

Despite no longer being actively maintained (see: aforementioned drama), `git-remote-hg` _mostly_ worked as advertised – until it didn't. I successfully pulled the remote Mercurial `modulegraph` repository into a local `git-remote-hg`-managed Git repository, created a new `swig` feature branch, pushed that to the remote Mercurial repository as a new Mercurial branch of the same name, and submitted a BitBucket pull request from that branch. (So far so good.)

After receiving useful feedback, I interactively rebased two commits on the local Git branch and attempted to `push -f` the results back to BitBucket. Normal Github-based pull request workflow. Nothing to see here. What could go wrong?

**Here's where everything went wrong.** Since Mercurial branches support multiple HEADs, `git-remote-hg` pushed the rewritten contents of the locally rebased `swig` Git branch **as a new HEAD** of the existing remote Mercurial `swig` branch rather than rewriting the original HEAD of that branch. Because the original head remained unmodified, BitBucket failed to register my changes to the existing pull request.

Guess what? This is a [well-known issue](http://blog.wikichoon.com/2015/01/using-git-remote-hg-with-bitbucket.html), which – thanks to no longer being actively maintained – is unlikely to ever be fixed. The only "solution" is to close the existing pull request and create a new pull request from the most recently pushed HEAD of the remote Mercurial branch. That's not a solution; that's insanity.

I should also note that `git-remote-hg` has [7 open pull requests](https://github.com/felipec/git-remote-hg/pulls) and [27 open issues](https://github.com/felipec/git-remote-hg/issues). (Good luck on that one.)

## Other Bridges: The Devil in Disguise

Every other open-source bridge is even worse.

[`git-hg`](http://offbytwo.com/git-hg/) doesn't support pushes (_you're kidding, right?_), [`git-cinnabar`](https://github.com/glandium/git-cinnabar) only supports pushes containing only non-merge commits _and_ requires that you either never or only incrementally update `git-cinnabar` (...using version 0.1 and want to upgrade to version 5.3? **Too bad. You can't.**), and [`gitifyhg`](https://github.com/buchuki/gitifyhg) comes with crazy disclaimers like "remote branch and bookmark tracking is not 100% stable," "pushing octopus merges is not supported," and "cloning mercurial branches that are subdirectories of other branches fails."

## We Just Need the `master` Branch, Man

**O.K.**

If you _only_ need to unidirectionally fetch a single remote Mercurial branch into a local Git branch, any of the above bridges should suffice. I'd probably go with `gitify` (despite the terrifying disclaimers), as that appears to be the most actively maintained.

That said, I can't recommend it. Mercurial and Git are sufficiently dissimilar that any mapping between the two should be considered suspect. It's one thing to perform a one-time export from one VCS to another. (That's easy.) It's another thing entirely, however, to try to permanently bridge two VCSs. (That's insane.)

## Where Does That Leave Us?

Again, I'd recommend just internally forking `modulegraph` and `altgraph` and being done with it. Upstream BitBucket changes are sufficiently infrequent that they can be manually merged into our local copies. This is pretty much what we do currently, anyway. Not much change there.

If that's perceived as too heavy-handed, we _could_ conceivably perform a one-time export from the existing `altgraph` and `modulegraph` BitBucket repositories into new Github repositories hosted under the newly doctored up [modulegraph "organization."](https://github.com/modulegraph) (Thanks, @matysek! You're awesome.)

**I'm cool with either.** In either case, we control the repository and hence dictate the pace and direction of development.

Sounds delectable to me. :apple:

**Comment by matysek** [comment]
> Or perhaps we could hack up a shell script auto-merging remote changes into our local copies (e.g., by globally replacing all instances of from modulegraph with from PyInstaller.lib.modulegraph)?

This should not be hard:
* I already fixed modulegraph to use relative imports.
* When fixing altgraph to use relative imports then with modulegraph update you need  to edit 'altgraph' imports in probably two files.

**Comment by matysek** [comment]
@leycec I think I would try `Approach B` but I have no strong preference.

In addition to whatever approach, I would try to ask modulegraph author to switch to git:
https://bitbucket.org/ronaldoussoren/modulegraph/issues/30

**Comment by leycec** [comment]
> I think I would try `Approach B` but I have no strong preference.

**Great!** As [you say](https://github.com/pyinstaller/pyinstaller/issues/1412#issuecomment-131388906), even manually applying the needed edits to embedded copies of these libraries shouldn't be _that_ laborious. Thanks to the addictive potato chips and role-playing games, however, I'm lazy. It should be fairly trivial for me to doctor up a `sed`-based shell script automating those edits for us.

Let me know if you'd like me to hop onto that.

> In addition to whatever approach, I would try to ask modulegraph author to switch to git:

Since BitBucket now supports `git`, that's feasible. While that _would_ simplify our basement-dwelling lives, I'd like to aim a little higher. Ideally, one or all prominent PyInstaller developers (e.g., matysek, htgoebels, codewarrior0) should have commit access to that repository.

It's hard to see that happening under a Ronald-managed BitBucket repository. I'd love to be proven wrong, of course. (_Prove me wrong, Ron._)

As long as we lack that access, submitting essential library changes will continue to be a gruelling uphill battle. I've had quite enough of leycec screaming "FREEEEEDOM!" and ronaldoussoren diffidently shaking his head. Count me out of that nightmare scenario.

**Comment by htgoebel** [comment]
Okay, now here is my statement:

IMHO modulgraph is not as elaborated as we (or at least I) thought. We already have two major issues:

  1. hooks are not executed at the place we need them to be b executed, see #1322, #1367 and leycec's glorious node ordering(#1393)
  2. imports are processed recursively, which leads to "maximum recursion depth exceeded" errors, see #1289, #1365.

 In addition:

 3. modulegraph is carrying along quite some old code and is quite convoluted.
 4. It seams to not support `ctypes`, see #1374.

 So I'm afraid, we have to rework modulegraph *a lot*, to be able to maintain it. And be be heretic: Perhaps we should throw out modulgraph again and go back to our own old (we should discuss this 

**So for me, it's not the question *if* to fork, but *how*.**

As for now, I'm in favor of **Approach B**, as this delays the decision :-)

Here are my thoughts of how we could achieve this (totally untested):

1. In repo `modulegraph/modulegraph`, branch `master` we keep the vendor branch. Updating this is as easy as either using one of the tools laycec tested or removing all files, dump in the current version and committing all of it.
2. In our repo keep a branch `vendor/modulegraph`. This branch is updated from the `modulegraph/modulegraph` repo.

  If we find out the exact workflow using `git read-tree`, `git subtree` or other such magic, this could contain only the subdirectory `modulegraph`, that we need in PyInstaller. But maybe this is overhead and it's easier to simply copy the file in. Or maybe this should be done in the `modulegraph/modulegraph` repo.

  I've been playing around with this the whole afternoon an did not find out how make this work.
3. Given git's intelligent merging, it should be easy to only update only the changes from upstream.

But all in all, I'm unsure if this worth the effort.

If we go for Approach A, we could take put `modulegraph` on a branch so updating is less error-frown.

**Comment by htgoebel** [comment]
The modulegraph author just declined switching to git: https://bitbucket.org/ronaldoussoren/modulegraph/issues/30 was closed with "won't fix". He did not even read the blog-post matysek referred to , not to speak of leycec's analysis here.

**Comment by matysek** [comment]
> Perhaps we should throw out modulgraph again and go back to our own old

Everything is better than the old code, even modulegraph.

**Comment by matysek** [comment]
> The modulegraph author just declined switching to git:

This just confirms that trying to cooperate with modulegraph author would be hard.

**Comment by matysek** [comment]
I think we all agreed on Approach B.

@leycec Are you going to lead this effort?

**Comment by leycec** [comment]
> @leycec Are you going to lead this effort?

**I'd love to!** Sadly, I'm a weak-willed man with looming deadlines. "Enthusiastically contribute to" might be a better choice of words. :smile: 

That said, I understand this is a high-priority topic that really needs to get rolling _today_. Before I go running around with rusty scissors, perhaps we could come to some agreement on an Action Plan<sup>TM</sup>. (_Bureaucracy._ It is good.) 

> See https://gist.github.com/htgoebel/a88f2e7271c40ebf938b for my snippets.

Thanks for the hard work, man. I see you've attempted to use the low-level `git read-tree` subcommand rather than the high-level `git subtree` wrapper, which _might_ be a part of your troubles. `git subtree` makes easy a few things that `git read-tree` makes hard.

For example, you advocate isolating the `modulegraph` subtree to a `vendor/modulegraph` branch of the PyInstaller repository. This makes sense – if you're using `git read-tree`, which doesn't provide that sort of isolation out of the box. If you're using `git subtree`, however, all subtrees _should_ already be isolated to their own subtree-specific branches (if I recall correctly, which I probably don't).

In theory, this implies that we shouldn't have to worry about branches on the PyInstaller side of things. We just add our `modulegraph` subtree via `git subtree add` and... **BAM!** Everything taken care of. In theory. (_Oh, God. Let it work._)

You also advocate isolating the `master` branch of the upstream BitBucket `modulegraph` repository to a `vendor` branch of our downstream GitHub `modulegraph` repository. This also makes sense – if any `hg`-to-`git` bridges actually supported that. Maybe they _do_. In my downtrodden experience, however, all `hg`-to-`git` bridges synchronize the entire remote Mercurial repository into a local Git repository which is then strongly coupled to that remote Mercurial repository.

In theory, this allows you to treat the Git repository exactly as if it were a one-for-one copy of the Mercurial repository (e.g., such that pushing from the local Git repository actually pushes to the remote Mercurial repository). In our case, we don't really want or need a bidirectional clone. We only want a unidirectional utility for fetching remote Mercurial changes into a local Git branch. Since that's a _much_ simpler task, there's gotta be a way to do that – but an `hg`-to-`git` bridge isn't it. 

Since we're agreed on Approach B (..._boooo_), we _really_ want to make the `git subtree` approach work. Let's all do a bit more CLI playing around before we get clone happy.

**Comment by htgoebel** [comment]
> This is a high-priority topic that needs to get rolling soon

I see no need for hurry. Better test i thoroughly and agree on the way to go than mixing up thing.

Re. `git subtree`: You may be right here. I simply did not find a way to extract only one subdirectory from "upstream". Seam like I've at last found my git-master.

Re. `master` branch: I did not use mercurial since long. So I simply took *any* branch*. You seam to know this much better than me, so it's up to you to decide.

**Comment by leycec** [comment]
> Re. master branch: I did not use mercurial since long. So I simply took any branch*. You seam to know this much better than me, so it's up to you to decide.

You're freaking clever. It's scary. I see what you're [doing here](https://gist.github.com/htgoebel/a88f2e7271c40ebf938b) now.

You maintain two parallel `hg` and `git` repositories **tracking the same top-level directory.** Nice. Since formal tools (e.g., `hg`-to-`git` bridges) can't help us here, this is probably the best and only approach if we _really_ wanted to stroll down that road.

Impudent question: why not just export the upstream `hg` repository into a local `git` repository (e.g., via [`fast-export`](https://github.com/frej/fast-export)) and then manually merge upstream improvements if required? I'm concerned that the parallel repositories approach, while crazy-clever, could be a bit fragile and possibly overkill. After all, once our downstream `git` repository starts heavily diverging from the upstream `hg` repository (..._and it will_), synchronizing changes between two parallel repositories sounds not fun.

This makes me a coward, doesn't it? (_Rhetorical question only._)

**Comment by leycec** [comment]
> I simply did not find a way to extract only one subdirectory from "upstream".

**Ugh.** My `git` foo is too pitifully weak. I bow before the `git` guru. (_For now._)

The problem with `git subtree` is that it's designed to unconditionally pull the entire remote repository into a subdirectory of the local repository. There's no provision for sparse checkouts or subdirectory filters. It's all or nothing.

What you want appears to be feasible via the [`git filter-branch` subcommand](https://stackoverflow.com/a/16603719/2809027). Since this is much lower-level than `git subtree`, a non-trivial chain of commands would need to be repeated on _every_ update of the embedded `PyInstaller/modulegraph` subtree. Which means we really want a shell script automating this. Which, presumably, would also run `sed`-based string replacements to patch import statements.

All of which raises that age-old query: why not just internally fork `modulegraph` and `altgraph` directly into the PyInstaller codebase? No fuss. No muss. No insane leycec in your membrane.

**Comment by leycec** [comment]
For disambiguity with the existing `altgraph` and `modulegraph` projects, we probably want to either:

* Merge `altgraph` and `modulegraph` into a new project. **I propose the name `pyramod`,** for it is punny. To simplify PyInstaller integration, this project would contain the `altgraph` and `modulegraph` packages under their existing names as top-level subdirectories. This has the advantage of preserving all existing import statements throughout both those projects and the PyInstaller codebase. That seems kinda nice.
* Keep `altgraph` and `modulegraph` as separate projects and rename each to... well, _something_. This has the disadvantage of requiring us to think up two new project names _and_ to rewrite import statements throughout both those projects and the PyInstaller codebase. The effort is crippling.

**You decide.** :hatching_chick:

**Comment by codewarrior0** [comment]
I've gone down the road of using submodules and subtrees to publish components of a project as "independent" projects. It was more hassle than it was worth. Nowadays, I just write more than one setup.py to spit out a bunch of different eggs, sdists, and other artifacts for each subproject, which is all kept in the same repo with the main project. If anybody wants to hack on my subprojects, they can check out the main project and then do a `setup.py develop` on the subproject.

I finally got caught up on this thread. I deduced that there are only two goals here: Pull changes from Ron's upstream repo, and use git's 3-way merge to make sure our changes aren't trampled by his or vice versa. 3-way merges mean less manual merging and better results from mergetools. 

If I'm wrong, and publishing a fork of modulegraph for public consumption is an actual goal and not a byproduct of your proposed approaches, you can ignore the rest of this post.

--

I'm in favor of Approach A (internally fork `modulegraph` and `altgraph`), aided by `git subtree` wizardry and git-hg bridges to make it easier for us (and not really anybody else) to merge Ron's upstream changes - by way of the 3-way merges git can do for us, since it has the previous revisions for both local and upstream. 

> Actually, there is a simple git subtree-based approach.

I am on the same wavelength as @leycec, *phase shifted by 180 degrees.* My thought was to do it in the other direction: Use `git subtree split` to pull the subdir of interest out of the upstream `modulegraph` repo, then use `git subtree add/pull` to merge changes from that subdir into our own repo. Or in more detail:

1. Using whichever git-hg bridge is working today, create a repository `modulegraph` that is a mirror of the upstream `modulegraph` hg-repo. It doesn't even need to be on GitHub.
2. Split the `modulegraph` directory of that repo, not into another repo, but simply into another branch (call it `modulegraph-module`).

  `git subtree split modulegraph -b modulegraph-module`
3. Move the `PyInstaller/lib/modulegraph` dir out of the way for now. (It might be cleaner to make a commit that removes these files, too.)
4. Add the `modulegraph-module` branch of `modulegraph` as a subtree of the `pyinstaller` repo in the directory `PyInstaller/lib/modulegraph`. That is, 

  `git remote add modulegraph foo://bar/modulegraph`
  `git subtree add -P PyInstaller/lib/modulegraph modulegraph modulegraph-module`
5. Put back the `PyInstaller/lib/modulegraph` dir we moved in (3.) and commit it on top of the changes from the `subtree add`.

That's it for the initial setup. Our own history of the files under `PyInstaller/lib/modulegraph` prior to the `subtree add` may be lost, but with a little git magic we can make a new fake history on top of that. 

Now, whenever we go to pull upstream changes, we can do it via `git subtree merge` and take advantage of the 3-way merge, since it will have both the changes we made and the upstream changes. The merge from upstream goes like this:

1. Using whichever git-hg bridge was working last time (I hope you used a virtualenv for that!), pull changes from upstream into our `modulegraph` mirror.
2. Since the upstream master is changed, re-split the `modulegraph` directory of the mirror into the branch `modulegraph-module`. 

    `git subtree split modulegraph -b modulegraph-module`
  
3. Merge the changes from that branch into the `PyInstaller/lib/modulegraph` dir of the `PyInstaller` repo.

  `git subtree merge -P PyInstaller/lib/modulegraph modulegraph modulegraph-module`. 


The benefit of this workflow over @leycec's plain and serviceable example is that the changes only flow in one direction. From Ron to us. There's no need for us to push our own changes to another repo, which can be a bit burdensome:

If we used the `modulegraph-core` repo as a mirror of our own, changed version of the `PyInstaller/lib/modulegraph` module, we would need to do one of two things: Either commit all our changes to `modulegraph-core` first, and `subtree merge` them into `pyinstaller` repo; or commit all our changes to `pyinstaller` repo and `subtree split` them back out to `modulegraph-core`.

It's not likely that we'd want to do all our changes on `modulegraph-core` and merge them in every time. We'd make our changes in the `pyinstaller` repo, then `subtree split` our changes out to `modulegraph-core`, then `subtree merge` them into `modulegraph`, then merge Ron's changes into `modulegraph`, then `subtree split` those to `modulegraph-core`, then `subtree merge` them back into `pyinstaller`. But `subtree split` takes a long time on our repo, so in the end we probably wouldn't bother pushing anything to `modulegraph` or `modulegraph-core` and just merge the upstream changes by hand.

--

It's worth pointing out that `subtree add/merge` creates real, honest-to-god merge commits. The current branch head will be one parent. Without `--squash`, the head of the `modulegraph-module` branch from the other repo will be the other parent. (Yes, this means that without `--squash`, the other repo's branch is pulled in its entirety. Whether that's good or bad depends on how much of `modulegraph`'s history you want to see in your git logs.)

With `--squash`, it still creates a merge commit, but the other commit is a newly created, parentless commit containing all of the files in the subtree (or if there was a previous merge, the other parent is the previous squash commit if the last merge was squashed, or else it is the head of the other repo's branch. In either case it will be the other parent of the previous merge.)

**Comment by htgoebel** [comment]
I'm closing this. Defacto we already forked.
