### ISSUE TITLE
remove old branches

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1424]
There are several branches in the PyInstaller repository. I think most of them could be deleted because their are old or unused anymore.

**Comment by htgoebel** [comment]
ACK

**Comment by codewarrior0** [comment]
`no-msvcrt` branch can be deleted, since `msvcrt71.dll` is no longer linked. For MSVC builds, `libc` is statically-linked; for MinGW builds, the `msvcrt.dll` is linked instead - this is the MSVC 6.0 version which is included with all Windows versions starting with XP.

`win32-unicode` branch can be deleted. I recently changed the bootloader and build scripts to use the Unicode entry point `wmain`/`wWinMain` and use Unicode Windows APIs everywhere, so Unicode builds are now the only option (no `TCHAR` nonsense or `#ifdef UNICODE` needed).

I don't know about the other branches, though. There might be some stuff worth cherry-picking from those, esp. `makespec_ng`.

**Comment by matysek** [comment]
* I think the branch `no-msvcrt` was meant to be more radical: 'To not use any function from the msvcrt dll at all.'
* branch `fix_merge_case`  differs in just one commit:
https://github.com/pyinstaller/pyinstaller/compare/python3...fix_merge_case
* The branch `makespec_ng` was started to implement a new format of .spec file. There diff between `python3` and `makespec_ng` is 129 commits:
https://github.com/pyinstaller/pyinstaller/compare/python3...makespec_ng

@codewarrior0 What do you think about the `fix_merge_case` diff? Is it worth to integrate it?
@rasky Is there anything in the `makespec_ng` branch that should be kept or could it be just dropped?

**Comment by codewarrior0** [comment]
> 'To not use any function from the msvcrt dll at all.'

This would be very radical indeed! It would mean never using even `fopen` or `fwrite` and doing everything through the platform APIs (POSIX, WinAPI, etc). It's like not linking to `libc` on Linux.

The actual goal was to not have the bootloader depend on a system-installed MSVCRT71.dll, so it can run without any prerequisites installed. That is, it would be completely self-contained. To do this, changes were made to Python API calls to never pass any CRT objects (`FILE *`, memory allocated with `malloc`, etc) because the Python DLL will be linked to a different version of the CRT than the bootloader. And changes were made to the build scripts (static-linking `libc` when building with MSVC) to support this. When building on MinGW, we use MSVCRT.dll (version 6.0) which is guaranteed to be installed on all the Windows systems we support.

All of those changes are in `python3` branch so `no-msvcrt` really is obsolete.

Regarding `fix_merge_case`: Yes. I've had to add `normcase` calls in a couple other places, so I think it's a good idea. I'll integrate it and then delete the branch.

**Comment by matysek** [comment]
@htgoebel What  about the branch `hotfix-1.5.2`? Could it be deleted? It looks like there are no changes worth to backport.

**Comment by htgoebel** [comment]
@matysek I don't know anything about branch `hotfix-1.5.2`. Since we are not longer maintaining v1.5.2, we do not need it anymore. If someone wants to keep it for historic reasons, I'm fine with it.

**Comment by codewarrior0** [comment]
Integrated and deleted `fix_merge_case` branch (HEAD was at e94ac61f228df57018768c79922d629cbe632629)

**Comment by matysek** [comment]
I removed the hotfix-1.5.2 branch.
