### ISSUE TITLE
Examine handling of `u` option (Unbuffered stdio)

### ISSUE THREAD

**Issue by codewarrior0** [pyinstaller/pyinstaller#1441]
In `pyi_pylib_set_runtime_opts`, we handle the `u` option by calling `setbuf` and `_setmode` on the stdio streams. This is probably a complete no-op on Windows. These set the buffering options for the stdio of the C Run-time library (CRT) that is linked to the bootloader, but the Python DLL is linked to a different version of the CRT. It will create its own stdio streams wrapping the underlying Windows `HANDLE`s, and the `HANDLE`s themselves have no such buffering.

We need to get the CRT functions and stdio objects that the Python DLL is linked to in order to change the buffering mode, or else find a way to change the buffering mode through Python API calls or executing Python code.

**Comment by htgoebel** [comment]
Any news on this`

**Comment by codewarrior0** [comment]
I haven't looked at this much because I think it's a very low priority. Windows users generally create GUI apps and don't care much about the terminal output, which is probably why nobody has complained about it.

Possible python code to execute after the pylib is initialized looks something like this:

```
import ctypes
NULL = ctypes.c_void_p(0)
crt = ctypes.cdll.msvcrt
if UNBUFFERED:
  crt.setbuf(0, NULL)
  crt.setbuf(1, NULL)
  crt.setbuf(2, NULL)
```

The `ctypes.cdll.msvcrt` correctly loads the CRT linked to the pylib rather than the one linked to the bootloader.

**Comment by codewarrior0** [comment]
Actually it's a bit trickier than that. On Python 2, python relies on the buffering of the underlying `FILE *` provided by the CRT, but on Python 3, it bypasses the `FILE *` and operates on OS file descriptors directly via the `_io.BufferedWriter` class. It will take some time to come up with a solution for both 2 and 3.

**Comment by htgoebel** [comment]
Well, this has low priority, so you may want to post-bone it to 3.x - or even close it.

**Comment by htgoebel** [comment]
This does not seam to have any priority to anybody, thus I'm removing it from the milestones plan.

**Comment by stevievb** [comment]
This is an issue for me. I'm on windows. I have two python programs built with pyinstaller. I'm trying to run one of them as a subprocess of the other one, and monitor the real time output of the subprocess via a PIPE. Because the stdout is always buffered regardless of the -u option, I can't communicate between the two processes in real time. 

@codewarrior0 - Is the code snippet you pasted above valid for python 2? If so, where exactly could I stick that to makes things work?

**Comment by Abhisek-** [comment]
I've created a `python 3-django` package using `pyinstaller`.

As mentioned [here](https://pythonhosted.org/PyInstaller/spec-files.html#giving-run-time-python-options), I've added `options = [('u', None, 'OPTION')]` and `options` in `exe` variable in the spec file.

After that I'm creating a docker image which will use the above package to start. But I've no idea whether the server has started or not unless I hit any request when it shows `Running on ...` log.

Is the *unbuffered* option works here. If not what can I do to make it work ?

**Comment by htgoebel** [comment]
One needs to learn how Python 2.7, 3.4, 3.5, 3.6 and 3.7 handle this option in Python's  C-code. Then one needs to provide a pull-request.

**Comment by Legorooj** [comment]
Pinging.

**Comment by capsocrates** [comment]
I am encountering this issue as well.

**Comment by jharrang** [comment]
It would be helpful to remove the 'u' runtime option from the documentation if it is not working or clarify the subset of conditions under which it works. The current documentation is very misleading given that this appears to be functionally not yet implemented.

**Comment by htgoebel** [comment]
@jharrang Pull request welcome :-)

**Comment by jharrang** [comment]
> @jharrang Pull request welcome :-)

@htgoebel - Perhaps you unintentionally missed the point? I'm not suggesting that this needs to be implemented. While that would be great, it's obviously not been a priority.

What **should** be a high priority and is an easy fix would be updating the documentation to better reflect the current state of the package. I am not sufficiently well-versed in the history of this issue or the current state of the codebase to make that revision, but I'm happy to open a new issue so that it can be assigned to someone who is if you prefer. Thanks!

**Comment by htgoebel** [comment]
@jharrang Even for the documentation a pull-request is welcome. Or for the "Known issues section of the Changelog".

You seem to be a professional developer, contributing to private repos only. You most probably get paid for your work. Did you fund this project? I can't see any notable amount from you. Do you really expect us to spend our spare time on your nice-to-have wishes? Quite an attitude!

**Comment by CDFriend** [comment]
Same problem here. Would love to see a fix for this.
