### ISSUE TITLE
[Wiki] Some notes about expected filesize

### ISSUE THREAD

**Issue by Redsandro** [pyinstaller/pyinstaller#1457]
I've seen packagers in the past include half the python libraries, resulting in 25 MB .exe files.

How does `pyinstaller` handle the packaging? What file sizes are expected?

Some notes on this are a welcome addition to the wiki.

**Comment by codewarrior0** [comment]
Here ars a few examples for Windows apps built with `onefile`:

- Python 2.7, "hello world" app: 3.3MB
- Python 3.4, "hello world" app: 4.9MB
- Python 2.7, medium sized app using PySide, numpy, PyOpenGL, and others: 27.4MB

`onefile` apps are pretty slim, since they can compress the python libraries. `onedir` apps can be 50-100% larger.

**Comment by htgoebel** [comment]
Would someone mind adding this to the wik?

**Comment by Redsandro** [comment]
Thanks for this information. Too bad medium apps get this huge.

I added this to the wiki here: https://github.com/pyinstaller/pyinstaller/wiki/FAQ#features point 3.

Is there a difference in packaging process (filesize) when you do  
`from library import feature` as opposed to  
`import library`?

**Comment by htgoebel** [comment]
No, in both cases `library` will be imported and thus included into the frozen app.
