### ISSUE TITLE
Packaging binaries used from within Python

### ISSUE THREAD

**Issue by topiwala** [pyinstaller/pyinstaller#1483]
How does one package large binaries (like gcc, say)?
I've tried the simple:

a.binaries += TOC([('gcc', '/usr/bin/gcc', 'BINARY')]), where a is the Analysis object. I see it in the PKG.TOC, but it doesn't seem to work when called from inside my python code in a pristine Linux environment with no gcc.

**Comment by codewarrior0** [comment]
I believe it is not enough to include only `/usr/bin/gcc`. I'm not too familiar with gcc, but I understand it is made up of a lot of different files - arch-specific gcc backends, stdlib headers, crt1 startup code, linkers and other support exes... and since a lot of those are full of platform- or distribution-specific code, I wouldn't expect it to work even if you did manage to bundle *all* of the required files into your app.

Are you sure it isn't acceptable to require the user's system have gcc installed?

**Comment by htgoebel** [comment]
If you need such a package like `gcc`, I strongly recommend using the operating-system mechanisms. `binaries` is meant for single files.
