### ISSUE TITLE
remove old COM server code

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1489]
Windows COM server is no longer supported:
* There was no new bug report related to COM server for a few years.
* It looks like it is not in use so it should be safe to drop all related code.

Cleanup files:
* ./utils/make_comserver.py
* ./PyInstaller/utils/cliutils/make_comserver.py
* ./bootloader/windows/dllmain.c
* ./bootloader/windows/dllmain.def

**Comment by htgoebel** [comment]
ACK

**Comment by codewarrior0** [comment]
Dumb story that's not really related:

I got a bug report for MCEdit half a year ago: Whenever the user opened an "Open File..." dialog, the app would crash with an ImportError that indicated some py2exe internal module. I don't use py2exe, which made it really confusing. As it turned out, the user had installed some other 3rd party software that installed a COM server built with py2exe. It was registered as a shell extension (think "add item to right click menu in file explorer"). So whenever he opened the dialog, it would load the extension, the extension would load up another copy of python 2.7 using the PYTHONPATH that was set by pyinstaller, and get the ImportError.

Thinking on it again, I might have accidentally fixed that fellow's problem when I rewrote the `sys.path` setup code not too long ago. Huh.

Anyway, if nobody's reporting bugs with the COM server it's probably unused. Go ahead and kill it.

**Comment by matysek** [comment]
@tallforasmurf I removed commands `pyi-build` and `pyi-make_comserver`. Could you reflect that in your manual update? Thanks.

**Comment by stclair** [comment]
I see COM server is no longer supported (I happened to be looking for exactly this solution).  Should it be removed from the home page?  ("Support for building COM servers" under "Windows-specific features")  Is there a supported alternative to COM that I should be considering?

**Comment by matysek** [comment]
There is no supported alternative because nobody requested it for a long time and I as a newcomer did not understood what exactly it was supposed to do.

**Comment by ckkart** [comment]
Is there a chance that com-server support could be revived? I need to migrate a project that uses com servers from python2.7 to python3. py2exe does not support recent python3 versions and before migrating to an earlier unmaintained python3 version I prefer to ask here. I could put some work on that if it is not too complicated - have not looked at the code yet though.

**Comment by htgoebel** [comment]
@ckkart As written in #4266: This may only happen if someone steps up to revive it.

**Comment by kratos2333** [comment]
> Is there a chance that com-server support could be revived? I need to migrate a project that uses com servers from python2.7 to python3. py2exe does not support recent python3 versions and before migrating to an earlier unmaintained python3 version I prefer to ask here. I could put some work on that if it is not too complicated - have not looked at the code yet though.
@ckkart we have a similar requirement. Have you found the solution yet?

**Comment by kurisutsukato** [comment]
I found out that py2exe has been updated and now supports python up to 3.9 (support for python 2 has been dropped). With respect to building COM servers it is being said: "Building windows services, and DLL/EXE COM servers might work but it is not actively supported." I had no time to check whether it works but it sounds promising.
https://github.com/py2exe/py2exe
