### ISSUE TITLE
Security-Alert: try to store file outside of dist-directory. Aborting.

### ISSUE THREAD

**Issue by jksfiftyfive** [pyinstaller/pyinstaller#1502]
Hi 

Im trying to compile an exe on Win 7 64bit, with pyton 2.7.9 32bit.

One piece of equipment im using is a small I2C device called a Sub20.  It comes with a dll and Ive used  ctypes to create a wrapper for the functions I need.  The code works fine.

However, now that im finished with the code, id like to build the exe.  

Ive tried onedir option and onefile option.

With the onedir option, i get 
```
6257 INFO: building COLLECT out00-COLLECT.toc
Security-Alert: try to store file outside of dist-directory. Aborting. 'C:\\Windows\\System32\\sub20'
```
the exe is created, but it fails to run with this message:
```
Traceback (most recent call last):
  File "<string>", line 37, in <module>
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\jtlab\\dist\\GATORB~1\\eggs/*.*'
```
with the onefile, it builds ok but when trying to run it, i get:

C:\Users\jtlab\dist>GatorBurnInMonitor.exe
C:\Windows\System32\sub20 could not be extracted!

I did see a hook update here:

https://github.com/pyinstaller/pyinstaller/blob/1e38dcb5916f3fc22089e169ff1ea61c05d66ad0/PyInstaller/hooks/hook-sysconfig.py

and i made that change, but i still get the errors.

Im open to any suggestions and even hacks/workarounds

thanks

**Comment by codewarrior0** [comment]
Possible duplicate of #1466.

**Comment by htgoebel** [comment]
Please try the current `python3` head.

**Comment by jksfiftyfive** [comment]
Im sorry. I dont understand what "try the python3 head" means.  How would i use/install that?  Does that require python 3 to be installed?

thanks

**Comment by matysek** [comment]
It means using the development version and it works with Python 2.7.

**Comment by jksfiftyfive** [comment]
ok, i removed the other version to be sure im using correct one.

https://github.com/pyinstaller/pyinstaller/zipball/develop

and installed and rebooted.  deleted the dist and build dirs

got the same error:

72769 INFO: Changing x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bc
b86ed6ac711f91.manifest into private assembly
Security-Alert: try to store file outside of dist-directory. Aborting. 'c:\\wind
ows\\system32\\sub20'


looked at the warning txt file and saw this, among others:

W: ignoring C:\Windows\System32\sub20 - ctypes imports only supported using bare filenames - sub_20_BurnInBoard (R:\...source\sub_20_BurnInBoard.pyc)
W: ignoring C:/Windows/System32/sub20 - ctypes imports only supported using bare filenames - sub_20_BurnInBoard (R:\...\source\sub_20_BurnInBoard.pyc)
W: ignoring C:/Windows/System32/sub20 - ctypes imports only supported using bare filenames - sub_20_BurnInBoard (R:\...\source\sub_20_BurnInBoard.pyc)

any ideas?

thanks

**Comment by jksfiftyfive** [comment]
I know you guys are working hard to fix this, but wanted to check in and see if this is where i should check on updates or if there is another open ticket (like referenced above), should i check there?

thanks

**Comment by codewarrior0** [comment]
We're still working on our `ctypes` support in [a number of other issues.](https://github.com/pyinstaller/pyinstaller/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ctypes)

I have a question, though. In your code that uses `ctypes`, you load the `sub20` DLL using an absolute path, right? We may not be able to automatically include that DLL because it would require modifying your code during the packaging process. We will have to skip references to DLLs loaded via an absolute path to `ctypes` and emit a warning, instead of aborting and leaving you with an incomplete app (which is why you see most of those errors). 

I see two possible solutions.

- You will have to require your users to install the Sub20 DLL using the vendor's installer so it is installed with the same absolute path. (Not my preferred solution.)

- You will include the Sub20 DLL as part of your Python package. You may need to copy the DLL to your source folders. Your PyInstaller .spec file (that is, the setup script) will need to explicitly include that DLL by extending `a.binaries` (I think). You will have to change your `ctypes` call to load the DLL using a path relative to some known location, such as the `__file__` of one of your Python modules, or (when running as a frozen PyInstaller app) relative to `sys._MEIPASS`.

**Comment by htgoebel** [comment]
@jksfiftyfive Please tet again using the current `develop` branch head. This should be fixed now.

**Comment by htgoebel** [comment]
@jksfiftyfive Since I did not hear anything about this since the release, I assume this is fixed.
