### ISSUE TITLE
tkinter gets included unconditionally

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1507]
I just found a *very* curious problem: When running the test-suite using Python 2.7, tkinter get included unconditionally:
```
$ PYTHONPATH= python2 -m py.test -k 'test_site_module_disabled[onedir]' -vv | grep tkinter
5361 INFO: Including run-time hook 'pyi_rth__tkinter.py'
5634 DEBUG: Analyzing /usr/lib64/python2.7/lib-dynload/_tkinter.so
...
```
whereas this doe not happen with pyth 3.4:
```
$ PYTHONPATH= python3 -m py.test -k 'test_site_module_disabled[onedir]' -vv | grep tkinter
```
Unfortunately, this makes the test-case fail (otherwise I would not have recognised it).

Any hints where to look at?

(Side-Note: at travis this does not happen. Curious, very curious!)

**Comment by codewarrior0** [comment]
The import chain leading to `Tkinter`:

```
Tkinter
    -> pydoc
    -> site
    -> pyi_site_module_disabled.py
```

**Comment by htgoebel** [comment]
Thanks. From where did you get this that quick?

**Comment by htgoebel** [comment]
So we are back on https://github.com/pyinstaller/pyinstaller/pull/1393#issuecomment-141631473.

**Comment by codewarrior0** [comment]
I did a quick patch to modulegraph the other day to write the import chains to a file. I haven't merged it because I did it quickly just for debugging and I don't expect it to work all the time.

Diff: https://github.com/codewarrior0/pyinstaller/commit/a69e61fbebcbb143db64bc84510cbf4fda53c604

Branch: https://github.com/codewarrior0/pyinstaller/tree/write-import-chains
