### ISSUE TITLE
Pyinstaller not able to find path (@rpath) of dynamic library in OS X ()

### ISSUE THREAD

**Issue by neworan** [pyinstaller/pyinstaller#1514]
Platform: OS X 10.10.5
Python: 2.7
pyinstaller: 3.0.dev2

Hi,

Pyinstaller works well on simple files (like hello.py). However, it has problem finding path of dynamic libraries using @rpath. Following is the error on running:

30849 INFO: Looking for dynamic libraries
30945 ERROR: Can not find path ./lib/libmkl_intel_thread.dylib (needed by /Users/XXX/software/canopy/User/lib/python2.7/site-packages/numpy/core/_dotblas.so)
30945 ERROR: Can not find path ./lib/libmkl_core.dylib (needed by /Users/XXX/software/canopy/User/lib/python2.7/site-packages/numpy/core/_dotblas.so)
30945 ERROR: Can not find path ./lib/libmkl_intel_lp64.dylib (needed by /Users/XXX/software/canopy/User/lib/python2.7/site-packages/numpy/core/_dotblas.so)
...

Here is an example of my otool output for the first lib

otool -L /Users/XXX/software/canopy/User/lib/python2.7/site-packages/numpy/core/_dotblas.so
/Users/XXX/software/canopy/User/lib/python2.7/site-packages/numpy/core/_dotblas.so:
        @rpath/lib/libmkl_intel_lp64.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/lib/libmkl_intel_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/lib/libmkl_core.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/lib/libmkl_mc.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/lib/libmkl_mc3.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.0)

Please help.

Thank

Neworan

**Comment by matysek** [comment]
@neworan Please  provide more info about:
* How you installed Python
* Where on your disk are files `./lib/libmkl_intel_thread.dylib` and friends.
* Simple code example to reproduce your issue.

**Comment by neworan** [comment]
Hi @matysek 

Thanks for quick response.

(1) I downloaded source code and installed it on mac by "python setup.py install"
(2) Missing files are on /Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib. I also tried putting them on /usr/lib, ./lib, or other DYLD_LIBRARY_PATH, none worked

(3) it is easy to reproduce the issues: simply import any of numpy, scipy,PyQt4. For instance:
import numpy
print "hello"

Thanks

**Comment by neworan** [comment]
BTW, this issue could be fixed manually by
install_name_tool -change "@rpath/lib/libmkl_intel_thread.dylib" "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib" /Users
/XXX/software/canopy/User/lib/python2.7/site-packages/numpy/core/_dotblas.so

But I have ~1000 such errors...  Need a way to fix them at a time.

Thanks

**Comment by matysek** [comment]
> (1) I downloaded source code and installed it on mac by "python setup.py install"

* I meant Python not pyinstaller.
* What is it Canopy.app and where could I get it?
* Could you try latest dev version directly from github? Still the same issue?

**Comment by neworan** [comment]
Sorry.

I got python from https://www.enthought.com/products/canopy/. I used numpy, scipy, panda a lot, so I got used canopy python. 

FYI, I also tried using python from official site where I got pkg. Same issue.

I tried latest dev version and yes it is the same issue.

Thanks

**Comment by bpteague** [comment]
I've been bitten by this too.  I installed the Anaconda distribution from Continuum.io: the PyQt dylibs are in `/anaconda/lib/`, while the .so files for the Python extension are in `/anaconda/lib/python2.7/site-packages/PyQt4`.

An example dependency list from otool looks like:

      northeast-fortyseven-one-fifty-one:PyQt4 brian$ otool -L QtCore.so 
      QtCore.so:
	@rpath/./libQtCore.4.dylib (compatibility version 4.8.0, current version 4.8.7)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 52.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)

`PyInstaller.depend.bindepend._getImports_macholib` replaces `@rpath` with `./`, and then it can't find `libQtCore.4.dylib`.  If I monkey-patch `_getImports_macholib` to search in `/anaconda/lib` as well, it finds the dylibs and my program freezes properly.

It seems like the most general solution is to add another keyword arg to `Analysis()`, specifying additional directories in which to search for binaries.  I'm kind of surprised such a thing doesn't already exist.

Thoughts?

**Comment by tallforasmurf** [comment]
Since I didn't understand this I dug up a little background.

First, there are many *many* online posts by people who've been bitten by the message `dyld: Library not loaded: @rpath/whatever`.

This [blog post by Mike Ash](https://www.mikeash.com/pyblog/friday-qa-2009-11-06-linking-and-install-names.html) goes over all the `@` names including:

> 
Starting in 10.5, Apple provides @rpath... [which] asks the dynamic linker to search a list of locations for the library. That list is embedded in the application, and can therefore be controlled by the application's build process, not the framework's. A single copy of a framework can thus work for multiple purposes.


The [CMAKE wiki](https://cmake.org/Wiki/CMake_RPATH_handling) has an overview including for OS X (it seems `@rpath` is valid in Linux as well -- who knew?):

> The linker will search for @rpath/ dependencies in the following order:
> DYLD_LIBRARY_PATH - an environment variable which holds a list of directories
> RPATH - a list of directories which is linked into the executable. These can contain @loader_path and @executable_path.
> builtin directories - /lib /usr/lib
> DYLD_FALLBACK_LIBRARY_PATH - an environment variable which holds a list of directories


Support for `@rpath` was supposedly added to PyInstaller in 2.0. But searching the code base on "rpath" turns up only a little code in bindepend.py and mach_o.py which looks to me to be handling the specific case of "a list of directories which is linked into the executable". But actually (per CMAKE) the DYLD_LIBRARY_PATH should be searched first. Maybe that happens by default?

**Comment by panjunyong** [comment]
We have the same issue. Can anybody have a look at this one? It stop us release the mac version for half a year.

**Comment by bpteague** [comment]
Until PyInstaller gets fixed, I have a work-around -- I monkey-patched PyInstaller.depend.bindepend._getImports_macholib, manually adding additional paths to search for libraries.  Since the library that's uncovering this bug for me is PyQt4, I put it in a hook for PyQt4.  I'll try to find time in the next week or so to patch this and submit a PR.  In the meantime, others can have a look at my PyQt4 hook here: https://github.com/bpteague/cytoflow/blob/pyinstaller/pyinstaller/hook-PyQt4.py

**Comment by amouma** [comment]
Any chances of a PyQt5 hook?

**Comment by htgoebel** [comment]
#1965 seam to solve exactly the problem described above.

**Comment by danauerbach** [comment]
I believe that for Qt v5.5.x this patch is still the only way to build successfully. This is because Qt plugins libraries use @rpath, but don't have an LC_RPATH defined. #1965 address the problem where the @rpath is swapped for @loader_path but then os.path.normpath chokes on loader path. This happens with Qt v5.6, where the plugin libraries DO have a proper LC_RPATH defined. 

I suppose that since Qt v5.6 + #1965 overcomes Qt/PyQt5 build problems, the Qt v5.5 library problem could ignored, but forcing a move to Qt v5.6 could be problematic for some. 

@htgoebel, if you would like me to verify that the Qt v5.5 plugin lib problem is not taken care of by #1965, and only by this patch, i can do so. Let me know. 

Cheers,
Dan

**Comment by htgoebel** [comment]
> this patch

@danauerbach Which patch are you talking about? There is none and I can't find no other pull-request beside #1965. If you have a patch, please provide a pull-request. Otherwise we'll not be able to solve this.

**Comment by danauerbach** [comment]
The monkey patch posted by @bpteague (see above) is the only way I have seen to get around the **missing** LC_RPATH problem in Qt v5.5 plugins. Having a global approach of inserting additional paths to be searched in PyInstaller.depend.bindepend._getImports_macholib would also be a means of getting around (perhaps masking) other problems PyInstaller.depend.bindepend._getImports_macholib has in identifying search paths. The patch is a somewhat heavy handed solution, but it did allow me to build with Qt v5.5/PyQt5. As far as I know there is no PR or issue specifically for this 'global addition of search paths' solution.

Based on the paths listed by the OP of **this** issue, I think it will be resolved by #1973. And possibly @bpteague specific problem as well. (@bpteagure, can you check?)

And #1965 solves problem in PyInstaller.depend.bindepend._getImports_macholib I observed with Qt v5.6 plugin libs where the LC_RPATHs exist but the @loader_path is not properly handled by os.path.normpath(), resulting in bad search paths.

**Comment by bpteague** [comment]
#1965 fixes my problem too.  I agree that a "global addition of search paths" is a band-aid fix to a lot of problems in identifying search paths.  If we can solve it the "right" way, with a deeper understanding of what's actually going on, then I am fully in favor of that.

I apparently don't understand the problem well enough to see exactly how #1965 fixes the issue I was running into.  But I won't look a gift horse in the mouth.

**Comment by danauerbach** [comment]
I hear ya... :)
