### ISSUE TITLE
Make the existing (old) "ImportHook" handler submit a API

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1553]
Originally from @leycec https://github.com/pyinstaller/pyinstaller/pull/1393#issuecomment-143632631:
@htgoebel Excellent questions! You always keep me on my gangrenous toes. :footprints: 

> One thing came to my mind: Shouldn't we make the existing (old) `ImportHook` handler submit a API, too?

**Absolutely.**

The new `building.imphookapi.PostGraphAPI` class has been designed to be a drop-in replacement for the old `building.imphook.FakeModule` class. Despite bundling `PostGraphAPI` with this commit, I decided at the last minute _not_ to make the switch-over in this pull request. I was concerned about merge conflicts and test failures. There don't appear to be any, so I probably should have just done it. _Annyway._ (When laziness and risk aversion unite!)

Making the switch-over is trivial:

1. Remove `building.imphook.FakeModule`.
1. Refactor the `building.imphook.ImportHook._process_hook_function()` method to use `building.imphookapi.PostGraphAPI` instead. In theory, this just means renaming `FakeModule` to `PostGraphAPI` in that method.

I've made the switch-over locally. So far, so good. I'll probably submit a new pull request finalizing this change over the coming week.

> And should we merge the old hook mechanisms into the new ones?

**Absolutely.**

tallforasmurf and codewarrior0 were completely right on this point; I was completely wrong. Thankfully, I've seen the light. (_It burns!_)

## What's the Plan, Man?

Here's how I see this going down:

1. The `building.imphook.HooksCache` should be completely refactored from the ground up to support **lazy hook loading.** Currently, `HooksCache` only caches the _filenames_ of all hooks on initialization. That's it. Instead, `HooksCache` should:
  1. Probably still cache the filenames of all hooks on initialization.
  1. Lazily cache the _in-memory module object_ returned by the `importlib_load_source()` utility function for each hook in a "just-in-time" manner. The contents of unused hooks will _not_ be cached. The contents of each used hook will be cached on the first attempt to access those contents, which will then be efficiently accessible by different **hook points** (e.g., `PyiModuleGraph._find_module_path()`, `PyiModuleGraph._safe_import_module()`) throughout the PyInstaller lifecycle.
1. The contents of each hook in the new `hooks/pre_find_module_path` and `hooks/pre_safe_import_module` subdirectories should be moved back into the corresponding hook in the top-level `hooks` directory. For example:
  1. The `pre_find_module_path()` function defined by the new `hooks/pre_find_module_path/hook-distutils.py` hook should be moved back into the old `hooks/hook-distutils.py` hook.
1. The new `hooks/pre_find_module_path` and `hooks/pre_safe_import_module` subdirectories should go away.

# What Could Possibly Go Wrong?

There are a few things to consider when performing this refactoring, however.

For each hooked module, `HooksCache` needs to cache the contents of `n` possible hook files – _not_ just `1`. These are:

* The official PyInstaller hook file for that module (if any).
* The `n-1` unofficial user-defined hook files for that module (if any).

To ensure each hook function is called at most once, `HooksCache` will also need some means of tracking which hook functions for each cached hook file have already been called and which haven't. I'm fairly sure we can do this by just **deleting** each in-memory hook function from its in-memory hook object _after_ that function has been called. (There may be hidden dragons here, however.)

It's not exactly trivial. It's not exactly hard, either. I estimate a week's worth of design, implementation, testing, and documentation.

## What About Them Hook Functions?

_Yeah._ We'll still need separate hook functions, of course. These are:

* `hook()` for post-graph hooks.
* `pre_find_module_path()` for pre-find module path hooks.
* `pre_safe_import_module()` for pre-safe import module hooks.

After implementing lazy hook loading, we won't need to separate those functions into separate hook files. They'll all be unified into top-level `hook/` files. If nothing else, that should simplify both the documentation and maintenance of hooks.

A big win for everybody! (Mostly, tallforasmurf. Best of luck on that documentation. _I don't envy you._)

**Comment by htgoebel** [comment]
> I've made the switch-over locally. So far, so good. I'll probably submit a new pull request finalizing this change over the coming week.

I personally would prefer this switch to go into 3.0 already, since this is changing the user-api. Only the switch to `PostGraphAPI`! The hook-cache should be kept for 3.0, as this is internal only. @matysek What do you think?

**Comment by matysek** [comment]
> I've made the switch-over locally. So far, so good. I'll probably submit a new pull request finalizing this change over the coming week.
> I personally would prefer this switch to go into 3.0 already, since this is changing the user-api. Only the switch to PostGraphAPI! The hook-cache should be kept for 3.0, as this is internal only. @matysek What do you think?

For 3.0 I agree only with removing `FakeModule` and use the drop-in replacement for `def hook()` functions if it's done until Friday and CI still pass. Nothing else. There are not a lot of hooks using `hook()` function so it should b e safe. It covers following hooks:
* `hook-_tkinter.py` - could be easily updated to not use hook() function
* `hook-PyQt4.uic.port_v2.py`
* `hook-PyQt4.uic.port_v3.py`
* `hook-PyQt5.uic.port_v2.py`
* `hook-PyQt5.uic.port_v3.py`
* `hook-xml.dom.py` - looks outdated and I think xml.dom module might work even without this hook.

**Comment by htgoebel** [comment]
@matysek: This is exactly what I meant. And as fas as I understood, this is what @leycec has already prepared.

**Comment by leycec** [comment]
**Woops.** It's Friday already in the Great White North (Canada) and I got distracted by #1561. I can probably get this out by the end of the day... but it'll be a close shave. :haircut: 

Deadlines: the bane of my all-too brief existence.

**Comment by leycec** [comment]
**O.K.!** Great work on your end, htgoebel. I fully agree that the existing family of `FakeModule` methods (e.g., `add_datas()`, `add_binary()`) are awkward and should probably go away. Currently, the new `PostGraphAPI` preserves these methods purely for backward compatibility. I'd be happy to eliminate those, but I'd rather not replicate work [already done](https://github.com/htgoebel/pyinstaller/tree/1405-eliminate-add_binaries-add_datas) by htgoebel.

@htgoebel Should I take a stab at refactoring hooks to use global variables (e.g., `hiddenimports`) rather than API methods (e.g., `add_import()`) or do you have that well in hand? My plate's a _bit_ full. I think I could squeeze this in, though... somewhere.

@matysek Would it be feasible to delay the 3.0 release by a few days to get this sorted out? If not, that's cool. We'll only be stuck with a miserable public hooks API for the remainder of existence. No biggie. :grimacing:

**Comment by leycec** [comment]
**[**_Tasty Food for Thought_**]**

Incidentally, the current implementation of the `excludedimports` hook global isn't necessarily ideal. Attempting to undo previous `ModuleGraph` operations (in this case, undoing previous imports) usually violates the module graph invariant – a recipe for subtle disaster. This may help explain why `hook-django.core.management`, which sets `excludedimports`, appears to fail.

Rather than attempting to undo previous `ModuleGraph` operations, it's usually better to _not_ do those operations in the first place. Fortunately, preventing imports from happening is pretty simple: just override the existing `ModuleGraph._safe_import_hook()` method with a new `PyiModuleGraph._safe_import_hook()` method implemented as follows:

* If the passed module to be imported is listed in the `excludedimports` hook global for the passed importing module, return `None`.
* Else, defer to the superclass `ModuleGraph._safe_import_hook()` method.

It's pretty much a four- or five-line implementation, in contrast to the fifty- or so-line implementation of the existing `ImportHook._process_excludedimports()` method. There's only one problem: **this _really_ requires lazy hook loading,** which we don't currently have.

In the meantime, I eat tasty food for thought. :fried_shrimp:

**Comment by htgoebel** [comment]
> @htgoebel Should I take a stab at refactoring hooks to use global variables (e.g., hiddenimports) rather than API methods (e.g., add_import()) or do you have that well in hand? My plate's a bit full, but I can probably squeeze this in... somewhere.

@leycec I replaced FakeModule by PostGraphAPI tonight #1557. Sorry, I've been to tired for putting a note here. It's up to matysek to decide if this will go into 3.0.

Regarding `add_datas()` and `add_binary()`: I kept them for the PostGraphAPI. First I did it only to reduce the number of changes. But then I found that this is a good place to also accept a TOC or Tree and convert it here. And *if* we are going to make `data` and `binareis`  into TOCs, this a good place for doing the conversion.

Regarding the `excludedimports`, I'm with you. But I would delay this change until after 3.0 release - for the sole reason to get 3.0 out of the door.

Looks like you are out modulegraph :guru: :-)

**Comment by leycec** [comment]
> @leycec I replaced FakeModule by PostGraphAPI tonight #1557. Sorry, I've been to tired for putting a note here. It's up to matysek to decide if this will go into 3.0.

You are the true hero of might and magic.

> Regarding `add_datas()` and `add_binary()`: I kept them for the `PostGraphAPI`. First I did it only to reduce the number of changes. But then I found that this is a good place to also accept a TOC or Tree and convert it here. And if we are going to make data and binareis into TOCs, this a good place for doing the conversion.

That makes complete sense. And so we soldier bravely onward.

> Regarding the `excludedimports`, I'm with you. But I would delay this change until after 3.0 release - for the sole reason to get 3.0 out of the door.

**100% agreed.** I have nothing meaningful to say.

**Comment by matysek** [comment]
> Regarding the excludedimports, I'm with you. But I would delay this change until after 3.0 release - for the sole reason to get 3.0 out of the door.

I'm with you too.

**Comment by leycec** [comment]
**Congratulations on the PyInstaller 3.0 release extravaganza!**

Fantastic work, all. It's been a harrowing two-year process, but the PyInstaller Crew pulled it through. Enjoy a well-deserved slice of gourmet greasy pizza: :pizza: 

Due to a family health emergency (and a slight feeling of burn-out), I'm probably going to take a week or two off from PyInstaller development. Until then, know that you are all stalwart heroes!

**Comment by JMSwag** [comment]
@htgoebel @matysek @leycec @codewarrior0 

Thank you!

**Comment by htgoebel** [comment]
Re https://github.com/pyinstaller/pyinstaller/issues/1553#issuecomment-144934669 ("the current implementation of the `excludedimports` hook global isn't necessarily ideal"): This has been solved in 5fb3d7bf0d56702220f9a35c887a0c53da4af2c8 and esp. 98100abde55f1fb0ab455f95b9259c3adcdbab2c.

The oterh topics of this issue have already been implemented for release 3.0.
