### ISSUE TITLE
No handlers could be found for logger "PyInstaller.utils.misc"

### ISSUE THREAD

**Issue by bsavelev** [pyinstaller/pyinstaller#1564]
3.0.dev6-25-gd6350ee
```shell
sudo ../pyinstaller.py ./t.py 
No handlers could be found for logger "PyInstaller.utils.misc"
```

**Comment by htgoebel** [comment]
Does this happen when not running as root? And why are you running PyInstaller as root at all?

**Comment by bsavelev** [comment]
only when running as root
Because I can!-)))
if seriously I have build system where pyinstaller running with uid=0 (fakeroot, docker, kvm)

**Comment by ChrisTruncer** [comment]
I'd be interested in this as well.  Pyinstaller is used in special linux distributions for security testing where you will be running it as root.  So it would be good to know if there's an issue in this case.

**Comment by g0tmi1k** [comment]
The following patch makes the error going away (when running as root).
```patch
diff --git a/PyInstaller/log.py b/PyInstaller/log.py
index f2108e6..083cebd 100644
--- a/PyInstaller/log.py
+++ b/PyInstaller/log.py
@@ -20,6 +20,7 @@ from logging import getLogger, INFO, WARN, DEBUG, ERROR, FATAL
 
 def __add_options(parser):
     levels = ('DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
+    logging.basicConfig()
     parser.add_option('--log-level',
                       choices=levels,
                       default='INFO',
```

Not sure if this is correct, but its working for me.



Kali Linux (https://www.kali.org/) is root by default.
This is working for me: 
```patch
diff --git a/PyInstaller/utils/misc.py b/PyInstaller/utils/misc.py
index e143971..c5bf85f 100644
--- a/PyInstaller/utils/misc.py
+++ b/PyInstaller/utils/misc.py
@@ -116,7 +116,7 @@ def check_not_running_as_root():
         if hasattr(os, "getuid") and os.getuid() == 0:
             logger.error('You are running PyInstaller as user root.'
                 ' This is not supported.')
-            raise SystemExit(10)
+            #raise SystemExit(10)
 
 
 def mtime(fnm):
```

**Comment by matysek** [comment]
@g0tmi1k thanks for debugging.

Question is how to handle the root requirement in PyInstaller:
* PyInstaller implemented a root check to stop if running as root.
* On the other hand, there could be some cases where running as root might be necessary.
* I suggest keep the default behavior (stop when running as root) and add there an option that would skip this root check - probably anything like `--skip-root-check`?
* Then the cli usage  would be:
```
$ pyinstaller  myscript.py
You are running PyInstaller as user root. This is not supported.
If you really need running PyInstaller as user root, use  option  --skip-root-check.
$ pyinstaller --skip-root-check myscript.py
```
@htgoebel What do you think about this suggestion?

**Comment by codewarrior0** [comment]
I did some digging on why PyInstaller tries to stop you from running as root.

Long ago, before it was installable via setuptools, PyInstaller was run by using `python pyinstaller.py`. Running it like this did not forbid running as root. There were also several scripts in the `utils` folder, such as `utils/bindepend.py`. Since these scripts needed to modify `sys.path` in order to load the `PyInstaller` package module from the folder above `utils`, the `sys.path` manipulation was protected by a root UID check to prevent some kind of malicious path injection from happening.

Later on, the root UID check was refactored into the `check_not_running_as_root()` function, which resides somewhere inside the `PyInstaller` package. `sys.path` must be modified in order to import this function, which means that now the the `sys.path` modification that it previously protected is now completely unprotected and the root check does nothing to improve security.

Now, because PyInstaller can be installed via setuptools, it will install equivalents of the scripts in the `utils` folder as runnable scripts into a folder that is on the user's $PATH. 

My suggestion is to remove the root check completely, remove the `utils` folder, and have the setuptools-installed scripts be the only way to run these extra command-line utilities.

**Comment by ChrisTruncer** [comment]
@matysek - I'd definitely like to chime in again and say that I absolutely have a use case for having this run as root.  As @g0tmi1k stated earlier, Kali linux uses root by default due to the permissions required by a variety of its tools.  I would love to have pyinstaller be allowed to run as root, even if it is like you suggested where we just add an extra cli options such as "--skip-root-check".

**Comment by htgoebel** [comment]
The reason for this is
1. `logging.error()` is called in `utils.misc.check_not_running_as_root()`
2. The logging is set up late, even after processing the options, see 6970c1cefdb21e7aa46f2cd11934bd0ed1a54b35

> My suggestion is to remove the root UID check completely, remove the utils folder, and have the setuptools-installed scripts be the only way to run these extra command-line utilities.

Removing the utils will remove the ability to use PyInstaller without installation – which is what I do all the time. But we could move the urils into the base folder – where they do not need the path-extension.

**Comment by nullne** [comment]
same problem on CentOS Linux release 7.1.1503 (Core)

**Comment by htgoebel** [comment]
@nullne This is already solved. Please use the current development version.
