### ISSUE TITLE
os.path.dirname(os.path.realpath(__file__)) incorrectly returns current working directory

### ISSUE THREAD

**Issue by seanthegeek** [pyinstaller/pyinstaller#1598]
In pyinstaller 3.1-dev0 on Python 3.5.0 (MacPorts) on Mas OS 10.11

    os.path.dirname(os.path.realpath(__file__))

Always returns the current working directory, rather than the directory that  `__file__`  is actually located in. This breaks the ability to locate included files.

Is there another way to find that path in the meantime?

**Comment by seanthegeek** [comment]
I didn't RTFM fully :\

**Comment by codewarrior0** [comment]
There's technically a bug here. The manual does say to use `sys._MEIPASS` to find included files, but many python modules are able to find their included files without it. This is because we synthesize a `__file__` attribute for those modules when frozen, and that attribute points to a file inside `sys._MEIPASS` such that finding data files relative to it will work.

The main script is an exception. Its `__file__` is set to a bare filename, rather than a full path starting from `sys._MEIPASS`.

**Comment by matysek** [comment]
> The main script is an exception. Its __file__ is set to a bare filename, rather than a full path starting from sys._MEIPASS.

@codewarrior0 Is this anything you think  should be fixed?

**Comment by codewarrior0** [comment]
Yes. Included modules can already find their data files using `__file__`, so there's no reason we can't extend that to the main script also.

**Comment by yuangu** [comment]
I have this problem, too。but my python version is 2.7 #2626

**Comment by yagebu** [comment]
This bug seems to have resurfaced. With PyInstalller 3.3 on Python 3.6 (on both macOS and Arch Linux), the following script will only output the current working directory (compiled with a plain `pyinstaller test.py`):

    import os.path
    print(os.path.dirname(os.path.abspath(__file__)))

**Comment by hikager** [comment]
Have you tried: 
`os.path.realpath(__file__)` then if you need to add dirname you can but I did not use it anyway

**Comment by bwoodsend** [comment]
This was resolved in #5649 so anyone using `PyIinstaller >= 4.3` will be seeing the corrected behavior but that's very recent.
