### ISSUE TITLE
hook-pubsub.core.py for PyPubSub

### ISSUE THREAD

**Issue by mementum** [pyinstaller/pyinstaller#1645]
wx.lib.pubsub has a nice default hook.

Based on it a working (at least in my project for the default "kwargs" setup) version for PyPubSub

```python
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

hiddenimports = collect_submodules('pubsub')

# collect_submodules does not find `arg1` or `kwargs` because
# they are not packages, just folders without an `__init__.py`
# Thus they are invisible to ModuleGraph and must be included as data files

pubsub_datas = collect_data_files('pubsub', include_py_files=True)


def _match(dst):
    return "kwargs" in dst or "arg1" in dst

datas = [(src, dst) for src, dst in pubsub_datas if _match(dst)]
```

Best regards

**Comment by matysek** [comment]
@mementum Please create a pull request.

**Comment by mementum** [comment]
I believe the "wx" naming is wrong. The PyPubSub package can be independently installed without having wxPython installed.

For the wx.lib.pubsub package included in wxPython (a fork or PyPubSub) PyInstaller already has a working hook

In any case I added the pull request with id #1649

**Comment by htgoebel** [comment]
#1649 is merged.

**Comment by TsaiZehua** [comment]
the default hook for wx.lib.pubsub (Pyinstaller 3.2.1) may not work well for wx.3.0(pubsub 3.3.0)
because the __import__ function in walk_packages witch called by collect_submodules first will raised  'Should not import this directly, used by pubsub.core if applicable'  before 
`datas = [(src, dst) for src, dst in pubsub_datas if _match(dst)]`

so i modify the source code in 'PyInstaller\utils\hooks\__init__' (im sorry)
`
for importer, name, ispkg in pkgutil.iter_modules(path, prefix):
                if not name.startswith(prefix):   ## Added
                    name = prefix + name          ## Added
                yield importer, name, ispkg

                if ispkg:
                    try:
                        **if "kwargs" not in name or "arg1" not in name:**
                            continue
                        __import__(name)
                    except ImportError:
`
and the copy the codes in **pubsub\core\arg1 to pubsub\core**

then it run - -
