### ISSUE TITLE
Paths included manually using Tree() or TOC() are converted to lowercase on Windows

### ISSUE THREAD

**Issue by uentity** [pyinstaller/pyinstaller#1676]
Following the case in my issue #1671 I manually add Cython-compiled modules tree to ```binaries```. And when PyInstaller finishes, copied filenames are all lowercase in resulting ```dist``` directory. This completely breaks Python imports and may have other negative effects.

Issue isn't present on Linux. Also if I print contents of TOC() with my binaries I can see that filenames are stored correctly there. So I think this is related to the copying procedure inside PyInstaller.

PyInstaller v. 3.0

**Comment by htgoebel** [comment]
Please provide a minimal example to we can reproduce it. Thanks.

**Comment by uentity** [comment]
Here's minimal example:
https://www.dropbox.com/s/au0ynol8sdcgkfp/pyinstaller_lowercase.zip?dl=0

Run PyInstaller on Windows with test.spec and you should notice that in dist\bin folder there are files ```aa.bin``` and ```bb.bin``` instead of ```aA.bin``` and ```bB.bin``` as user expects.

**Comment by MartinCharlis** [comment]
hey uentity .. 

i did everything you said .. 

- converted the py file to c file ..
- then i converted the C file into Pyd file ..
- and i included it in the .spec file inside the `binaries` array 
`binaries=[('need\\lib.pyd',''),('need\\lib.c','')],`
so i found this libraries ( lib.pyd, lib.c ) beside the generated exe file by PyInstaller in the ( dist ) folder.

but i still have the same problem
`Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Python27\lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 539, in load_module
    except IOError:
ImportError: DLL load failed: The specified module could not be found.
finish returned -1`

Please Help me to finish this project .. :/

**Comment by uentity** [comment]
@MartinCharlis we might be talking about different kind of issues.
In my case the problem was that after 'Cythonizing' whole complicated project tree PyInstaller no longer able to find dependencies (both internal, between compiled modules, and external imports of third-party Python extensions).

As I said in #1671, my solution is the following:
1. Start Analysis on Python source tree and let it discover all internal and external (out-of-project) dependencies.
2. Modify ```pure``` TOC and remove all project files from it.
3. Manually append all Cython-compiled modules to BINARIES.

In my case if I stop after step 1, then I get fully-functional packaged application with correctly discovered and included dependencies, **but** it doesn't include any Cython-compiled modules. To include them, I manually remove all my project-related Python files, discovered by PyInstaller, from ```pure``` TOC (i.e. from resulting EXE-file) in 2-nd step. Then, in 3-rd step I manually append compiled modules to ``binaries```.
In order for this to work you **must not** compile your modules in-place (otherwise PyInstaller don't "see" the Python source script), place 'em in separate directory.

I your case seems that some PyInstaller's hook failed to collect all libraries required by some third-party extension. You probably should find out which DLL is missing (not packaged) and then manually include it as hidden import or into ```binaries```.

**Comment by htgoebel** [comment]
@uentity Pleas post the example *here*. I can not access dropbox without cookies and javascript - ans I will not access it with both enables since I do not trust them.

**Comment by uentity** [comment]
@htgoebel https://github.com/uentity/pyinstaller_lowercase_example.git

**Comment by htgoebel** [comment]
Thanks for the example.

The problem is: All entries in a `Tree` will get type `DATA`. And `DATA` (and `BINARY`) entries get their destination-names normalized. So you need to change them into `EXTENSION` -- which is what cyton compiled modules actually are.

BTW: You could simply put a Tree or TOC into `Collect()`, too, like this. (This has the same effect as adding them to `a.binaries`, since `COLLECT` simply merges all positional arguments into a single list.)
```
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               Tree('bin', prefix='bin'),
               strip=None,
               ....
```

**Comment by htgoebel** [comment]
I just implemented 9aa186038ad9e7a3d56ea5b3ced9ffb4e63673a0: Allow specifying the `typecode` for the files in a `Tree()`
This may ease your issue.

**Comment by uentity** [comment]
@htgoebel thanks for clarification.
But what is the underlying reason for normalizing (lowercasing on Windows) ```DATA``` and ```BINARY``` paths?

**Comment by htgoebel** [comment]
To be honest: I don't know - I'm not a windows guy and I'm avoiding Windows wherever I can.

**Comment by codewarrior0** [comment]
It's because filesystems on Windows and Mac are case insensitive: `FOO.txt` and `foo.txt` are the same file. The idea is to prevent the file from appearing twice in the TOC. Case insensitivity applies when you open a file by name; but if you do something like list a directory, then you get the actual upper/lowercase letters in each filename, so you can do a case-sensitive check to see if a file exists that way. I'm pretty sure this is why Python's importer is case-sensitive even on Windows.

(There's some minor differences between how Mac and Windows are case insensitive, something to do with renaming files I think, I'll have to double check that...)

The current approach is somewhat wrong. When `FOO.txt` is added to the TOC, it should stay as `FOO.txt`, and only be skipped if `foo.txt` exists. So the filename should only be normcase'd as it goes into the unique filenames set, and the original filename should go into the TOC. I'll take care of this now, it shouldn't take long.

**Comment by tallforasmurf** [comment]
my #421a5e9 and #d0c4828 clean up the Tree doc and add an (untested) example of building a TOC of Cython modules.

Note BTW that Tree could be more useful if it had an `include=list-of-suffixes` in addition to the existing `exclude=list-of-suffixes`. For the Cython case specifically, it would be handy to say `include=['*.so']` instead of trying to exclude every type of source file.
