### ISSUE TITLE
Add debug-output for the module-graph

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1683]
Sometime it's helpful to know from which module some module is imported (ans the other way around). When running with `--debug` we should write this information to the build-directory.

`modulegraph` already is able to dump some debug information, including a graph. This could be used as a base.

**Comment by htgoebel** [comment]
@tallforasmurf Do you wan to document this?
xref is an html-file and the other a dot-drawing. Both go into the build directory, like the warnfile.

**Comment by tallforasmurf** [comment]
Worth documenting for sure. However, I'm having a little trouble testing it. I bundle a minimal program, I get `build/minimal/graph-minimal.dot` but when I process this with

    dot -Tpng -O build/minimal/graph-minimal.dot

I get a file `build/minimal/graph-minimal.dot.png` which is basically a one-pixel white square. No nodes, no edges. Probably because the graph file has only subgraph{} items in it.

The file build/minimal/xref-minimal.html is quite large, lots of things in it. Is there some step I do to combine the files before graphing? Or what am I missing?

**Comment by codewarrior0** [comment]
That `dot` command works for me, even on the pyi_helloworld test script. The graph is a tangled, useless mess though:

![image](https://cloud.githubusercontent.com/assets/307683/11350691/dfb424a2-91d6-11e5-8acf-258fa8fd64d9.png)

```
$ dot -V
dot - graphviz version 2.28.0 (20110507.0327)
```

**Comment by codewarrior0** [comment]
I tried using the xref file that modulegraph outputs to debug an issue some months ago. As you say, it is very long, mostly because the required `encodings` module brings in a lot of dependencies. The main thing I did with the xref file was find a particular module, and then keep clicking the "imported by" links until it takes me back to the main script.

I made a couple of attempts at outputting the xrefs as a list of lines like "a imported by b imported by c imported by the main script". This was much more useful but I haven't pushed them because I wasn't satisfied with any of my methods - they were either too slow or required too many changes to modulegraph. I've still got a few more ideas to try, though.

**Comment by tallforasmurf** [comment]
What are the first few lines of your graph- file like? Mine are,

    digraph G {
	concentrate="true";
	rankdir="LR";
	subgraph "cluster_importlib" {
		label="importlib";
	}
	subgraph "cluster_logging" {
		label="logging";
	}

and only more "subgraph" items after, nothing else. I just downloaded a fresh copy of the dev branch and installed it, just in case.

**Comment by codewarrior0** [comment]
```
digraph G {
	rankdir="LR";
	concentrate="true";
	"<PyiModuleGraph>" [label="<PyiModuleGraph>"];
	"cPickle" [shape="record",label="<f0> BuiltinModule| <f1> cPickle"];
	"cPickle.loads" [shape="record",label="<f0> MissingModule| <f1> cPickle.loads"];
	"cPickle.dumps" [shape="record",label="<f0> MissingModule| <f1> cPickle.dumps"];
```

Followed by 2000 more lines of modules. The subgraph items start at around line 500 and are followed by even more modules.

**Comment by tallforasmurf** [comment]
Well I believe I see a problem but I don't understand why it works for you. At this line:

https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/modulegraph/modulegraph.py#L1981

we have a for-loop that consumes all of `nodes` which is a map, and hence an iterator. This loop constructs the `nodetoident` dict which for my example, ends up with 526 entries (potential edges). So `nodes` yielded that many items. However shortly after at 

https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/modulegraph/modulegraph.py#L1990

is another for-loop on `nodes` and when I trace through this code, it does zero iterations, because the `nodes` map is exhausted. So it never writes any edges. It looks as if this code expects the `nodes` map to start over again after it raises StopIteration but that is not how maps work when I test them. So I'm confused.

**Comment by codewarrior0** [comment]
Aha! I'm using python 2, and you're using python 3.

The first line of that function calls `map()`, which on python 2 returns a list, but on python 3 returns a generator object. So on py3, `nodes` may only be iterated once. Try changing the line to `nodes = list(map([...]))`

**Comment by tallforasmurf** [comment]
That did it! @htgoebel , do you want to fix that?
However, I have to say that the graph output, as @codewarrior0 notes above, is not precisely useful. The `dot` command ran about 90 seconds to produce a .png file that is 9296 x 36271 pixels and looks like the time the kittens got into my wife's knitting yarn.
I have written a couple paragraphs describing this for the "Finding Out What Went Wrong" topic but I kind of hesitate to put them in.

**Comment by htgoebel** [comment]
Fixed the iterator.

Regarding the graph: I output it since if comes for free as modulegraph already implemted it. If it is not useful, we can either not talk about it or remove it at all.

**Comment by tallforasmurf** [comment]
I added "Build-time Dependency Graph" to the "When Things Go Wrong" section. Noting that the files are very large, so the GraphViz file is not very useful "in this release". 71c77f164e804c335eb1826adf6fa5813cd2d748
