### ISSUE TITLE
ctypes - loading external DLL (not bundled) fails

### ISSUE THREAD

**Issue by tgc-dk** [pyinstaller/pyinstaller#1685]
This is somewhat related to #1620 and #1609. The issue here is actually described here: https://github.com/pyinstaller/pyinstaller/issues/1609#issuecomment-149352392 but it was not the main issue in #1620, so it wasen't really addressed.

When trying to use vlc python bindings: https://wiki.videolan.org/PythonBinding/
The dll is not bundled.

When running from source: c:\python34\python.exe vlc.py

    Usage: vlc.py <movie_filename>
    Once launched, type ? for help.
    
    Build date: Wed Jun 25 13:46:01 2014 (0x0)
    LibVLC version: 2.2.1 Terry Pratchett (Weatherwax) (0x2020100)
    LibVLC compiler: gcc version 4.9.1 (GCC)
    Plugin path: C:\Program Files (x86)\VideoLAN\VLC

When running as frozen

    LOADER: extracted pyimod01_os_path
    LOADER: callfunction returned...
    LOADER: extracted pyimod02_archive
    LOADER: callfunction returned...
    LOADER: extracted pyimod03_importers
    LOADER: callfunction returned...
    LOADER: Installing PYZ archive with Python modules.
    LOADER: PYZ archive: out00-PYZ.pyz
    LOADER: Running pyiboot01_bootstrap.py
    LOADER: Running vlc.py
    Traceback (most recent call last):
      File "<string>", line 167, in <module>
      File "<string>", line 140, in find_lib
      File "<string>", line 124, in __init__
      File "C:\python34\lib\ctypes\__init__.py", line 351, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] Module not found
    vlc returned -1
    LOADER: OK.
    LOADER: Cleaning up Python interpreter.

The issue can be worked around by adding this to vlc.py:

     ctypes.windll.kernel32.SetDllDirectoryW(None)

**Comment by matysek** [comment]
@tgc-dk Thanks for reminding this issue. A few notes:
* For security reasons bootloader sets `SetDllDirectoryW` to point to `sys._MEIPASS`. So no other dlls are allowed to be imported.
* When you override `SetDllDirectoryW` then libvlc is found, however it is not good to set this behavior being default in PyInstaller.
* PyInstaller is not able to resolve dlls when ctypes code cointains any path manipulation and not just hardcoded string in function `find_library()`.

I think we have here a few options:
* document usage of overriding `SetDllDirectoryW` and create a recipe in the wiki.
* Do you want the `libvlc.dll` and dependend libraries being bundled with the python app so that you could play videos without having vlc installed? If so, then
  * If so, then you could either specify 'libvcl.dll' in the .spec file in `binaries` list so it is found or
  * try to append directory with vlclib to the `PATH` variable before running pyinstaller.

**Comment by tgc-dk** [comment]
In this case and at this time we do not wish to bundle VLC with the app.
So that more or less leaves us with overriding ```SetDllDirectoryW```, right? To "restore" security, I guess we could just set ```SetDllDirectoryW``` to ```sys._MEIPASS``` after loading ```libvlc.dll```?.

**Comment by matysek** [comment]
> we could just set SetDllDirectoryW to sys._MEIPASS after loading libvlc.dll?.

@tgc-dk probably yes. Please report back if that causes any side effects.

**Comment by matysek** [comment]
I created this recipe https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Win-Load-External-DLL - closing.

**Comment by bharadwaj-raju** [comment]
Setting `SetDllDirectoryW` to `sys._MEIPASS` says that `sys` has no attribute `_MEIPASS`.

**Comment by htgoebel** [comment]
@bharadwaj-raju Please to *not* report the same issue in different ticket. For the missing sys._MEIPASS you already opened #1785
