### ISSUE TITLE
import pandas when using anaconda results in enormous file size

### ISSUE THREAD

**Issue by Godsmith** [pyinstaller/pyinstaller#1694]
I have created a minimal file pandas_pyinstaller.py:

    import pandas
    print 'hello world'

When I run

    pyinstaller --onefile pandas_pyinstaller.py

when having the latest version of Anaconda for Windows installed, the size of the generated exe file is 138 MB. When I only have having a native installation of python 2.7, pandas, pywin32 and pyinstaller installed, the file size is 25 MB.

I have tried to reduce the file size by removing unneeded binaries in the spec file (https://pythonhosted.org/PyInstaller/#toc-class-table-of-contents), but this is really cumbersome and I don't seem to manage to get down to 25 MB this way.

Does anyone know why importing pandas makes pyinstaller include a lot of unnecessary packages in the exe file? And what can I do to keep Anaconda installed while still keeping the exe file size small?

**Comment by htgoebel** [comment]
You can specify the modules to exclude on the command line: `--exclude-module`. Sorry, not much more we can help you here.  The only thing you can do is figuring out which modules you do not need and then exclude them. If this shows up to be a general problem, we'd appreciate a pull-request.

**Comment by codewarrior0** [comment]
Generally, it's because a lot of the modules and packages in Anaconda have optional dependencies on each other. For example, IPython will use modules from numpy and matplotlib if they are present. PyInstaller doesn't distinguish between hard dependencies and optional ones, so importing one module in your script will result in a big cluster of those modules being included.

We're working on a feature to make PyInstaller aware of these optional dependencies in advance (via hook-files), so they will only be included if your program explicitly imports them. Is the exe any smaller if you try the latest development version from git?

**Comment by Godsmith** [comment]
Thanks for the detailed explanation. It turns out that in my case, pandas was not required by the core functionality of my application, so I will try to extract the functionality that requires pandas into a separate script, which means I won't have to import pandas at all. 

Last time I tried with the latest development version I got some errors, I can try to reproduce the issue if I get the time.

**Comment by jhk519** [comment]
Pretty new to programming but I was wondering if there was a way to essentially get a log that would look like this?

Packaged Modules:
pandas 45mb
numpy 15mb
django 80 mb

etc..

A simplified list of the modules included would make it easier for a noob like me to figure out waht to exclude. My file is currently 150mb post-upx, and it's a REALLY simple script. 

Except for my own imported scripts (total <1mb), I only needed 

requests
os
sys
openpyxl
json

but it seems to be including a seemingly endless list of modules. Part of this, I understand is related to Anaconda being my default "path" for Python interpreters, so it includes IPython, pandas etc. 

Does someone mind giving me an understanding of how to generate the exe outside of this path? Like, essentially just the pure Python interpreter? Sorry for dumb question. I love PyInstaller, it's helped me and my company a lot making simple exes for non-programmers to use.

**Comment by answerquest** [comment]
Wow just 138MB? You're lucky! I installed pandas via conda on my minconda setup, and it roped in this mammoth `mkl` thing. Now its DLLs are making my pyinstaller dist weight in at over 600MBs! And from what I'm reading elsewhere, this isn't even for pandas.. mkl seems to be attaching to numpy which is attaching to panda. Chain dependencies! I'm pretty sure I'm not using these advanced functionalities in my program; would appreciate any advice on how to get these mkl's off my back.
```
mkl_avx.dll
mkl_avx2.dll
mkl_avx512.dll
mkl_avx512_mic.dll
mkl_blacs_ilp64.dll
mkl_blacs_intelmpi_ilp64.dll
mkl_blacs_intelmpi_lp64.dll
mkl_blacs_lp64.dll
mkl_blacs_mpich2_ilp64.dll
mkl_blacs_mpich2_lp64.dll
mkl_blacs_msmpi_ilp64.dll
mkl_blacs_msmpi_lp64.dll
mkl_cdft_core.dll
mkl_core.dll
mkl_def.dll
mkl_fft._pydfti.pyd
mkl_intel_thread.dll
mkl_mc.dll
mkl_mc3.dll
mkl_pgi_thread.dll
mkl_rt.dll
mkl_scalapack_ilp64.dll
mkl_scalapack_lp64.dll
mkl_sequential.dll
mkl_tbb_thread.dll
mkl_vml_avx.dll
mkl_vml_avx2.dll
mkl_vml_avx512.dll
mkl_vml_avx512_mic.dll
mkl_vml_cmpt.dll
mkl_vml_def.dll
mkl_vml_mc.dll
mkl_vml_mc2.dll
mkl_vml_mc3.dll
```
Totalling to just under 600MB.

**Comment by answerquest** [comment]
Hi, I found a solution that took my dist size from 600MB+ to just around 28MB by installing all needed packages with pip instead of conda:  
https://stackoverflow.com/a/48846546/4355695   
The command lines also took care of the pandas timedeltas issue.

The full dist folder now became 80MB.  
Then, it seems in the virtual env UPX compression isn't there. I separately downloaded it from https://github.com/upx/upx/releases , unzipped to a local folderand supplied the `upx-dir` :  
`pyinstaller myfile.py --upx-dir=C:\upx394w`
Now the dist size came to 28MB!

This goes against the "strong" advice to use conda to install packages instead of pip. Instead, this solution only used conda to create a virtual environment, and then pip was used after that. Apart from the dependencies needed by the application anyways (which I had in my requirements.txt), `pyinstaller`, `pypiwin32` were the two more packages needing to be installed by pip.

**Comment by SHREYAS1188** [comment]
I am a bit late to answer here but i have found a way to do it 
i first got a app (standalone) of 306MB then i successfully reduced it to 32.5MB 
yes it true

306MB
i use conda for coding and i basically use conda prompt so while converting .py to .exe conda packages all the modules/libraries which are present so the size increases for such an extent also mentioned by @answerquest 

32.5MB
the best way is use your CMD [windows] but the point is see to it that the basic libraries which are preinstalled while installing python are present if any other extra packages are there remove it using

pip uninstall <package-name>  

now install only those modules which you are actually using in your script 
and then use pyinstaller you will get .exe file with minimum size


Hope this works :)
