### ISSUE TITLE
Distorm Python Module won't Load

### ISSUE THREAD

**Issue by Starwarsfan2099** [pyinstaller/pyinstaller#1730]
Any programs requiring the Distorm module (https://github.com/gdabah/distorm) compile correctly, but when launching the message reads:
![capture](https://cloud.githubusercontent.com/assets/12116340/11856167/c54c93a8-a41c-11e5-957e-801327f40476.JPG)
Any program with Distorm fails like this. The sample program (https://github.com/gdabah/distorm/blob/master/python/distorm3/sample.py) included with distorm is in the example above.

**Comment by bjones1** [comment]
The error above refers to [`distorm3/__init__.py` line 50](https://github.com/gdabah/distorm/blob/master/python/distorm3/__init__.py#L50). It looks like `distorm3` needs an external library (see [line 39](https://github.com/gdabah/distorm/blob/master/python/distorm3/__init__.py#L39)). Since `distorm3` isn't (yet) a [supported package](https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages), you'll need to write a hook file to get it working, letting it know these libraries are needed. See [the manual](https://htmlpreview.github.io/?https://github.com/pyinstaller/pyinstaller/blob/develop/doc/Manual.html#understanding-pyinstaller-hooks) for details.

Specifically, I would guess something like the following in `hook-distorm3.py` would work. This isn't tested, just a quick guess...

``` Python
from  PyInstaller.hooks.utils import collect_dynamic_libs
binaries = collect_dynamic_libs('distorm3')
```

@gdabah, I noticed you've already done some adapting of `distrom3` for PyInstaller -- would you be available to help?

**Comment by matysek** [comment]
@Starwarsfan2099 you use an old version of PyInstaller. Please try the latest or develop version.

**Comment by gdabah** [comment]
Hi there @bjones1,
please tell me how I can be of help.
If there's any fix I can pull, I will gladly do it.

**Comment by Starwarsfan2099** [comment]
@bjones1 Tried the hooking and it still fails same way. I'm new to hooking though, should it print something like `INFO: hook distorm3` like other modules? Here's output:
![capture2](https://cloud.githubusercontent.com/assets/12116340/11881341/38ed2d24-a4d4-11e5-8174-3c999b4fce5c.JPG)

No `INFO: hook distorm3`... The hook is in the PyInstaller/hooks directory.

**Comment by Starwarsfan2099** [comment]
For those who would like to see it, here is the code that imports the dll:

==================================================================
_distorm_path = split(__file__)[0]
if hasattr(sys, '_MEIPASS'):
    _distorm_path = sys._MEIPASS
potential_libs = ['distorm3.dll', 'libdistorm3.dll', 'libdistorm3.so', 'libdistorm3.dylib']
lib_was_found = False
for i in potential_libs:
    try:
        _distorm_file = join(_distorm_path, i)
        _distorm = cdll.LoadLibrary(_distorm_file)
        lib_was_found = True
    except OSError:
        pass

================================================================

I just need a hook for including this. I also tried this but no effect: 
https://github.com/botherder/detekt/blob/master/hooks/hook-distorm3.py

**Comment by matysek** [comment]
@Starwarsfan2099 do you really use the latest `develop` version? I wonder why is there `PyInstaller-2.1` in the screenshot.

**Comment by Starwarsfan2099** [comment]
@matysek, just download and installed https://github.com/pyinstaller/pyinstaller. I had it before I had the current version before, I just kept everything in the same directory name. I just reinstalled everything and still the same result.

**Comment by bjones1** [comment]
@Starwarsfan2099, are you an experienced Python developer? Creating a hook will require some time and expertise; since `distorm3` isn't supported, it will be your responsibility to develop and test the hook. I would not place the hook in `PyInstaller/hooks`, since depending on how you installed PyInstaller, this may not be found. (That is, `python setup.py install` must be run-run *each* time you edit or add a hook). You'll need to read through the PyInstaller manual to become familiar with the process. If you don't see a line like `Processing hook hook-distorm3`, then something is wrong.

**Comment by Starwarsfan2099** [comment]
@bjones1, I have written plenty of python projects, but I have never had problems out of Pyinstaller. I read the documentation and wrote a hook that loads the appropriate dll's required. It did work on both my disassembler and the sample program. Is there a way to send the hook to the Pyinstaller team so it will be included in the next update?

**Comment by bjones1** [comment]
Fantastic! Yes, please submit a pull request which includes both your hook and a simple test to verify that `distorm3` is packaged correctly.

**Comment by Starwarsfan2099** [comment]
@bjones1, I am going to install pyinstaller and distorm on my Linux machine and make the hook support both Windows and Linux. It may be a while before that happens (Christmas and everything). Thanks to all who helped! Expect a distorm3 hook soon! Issue closed!
