### ISSUE TITLE
Source code within the 1-folder frozen application

### ISSUE THREAD

**Issue by giumas** [pyinstaller/pyinstaller#1762]
From my understanding, PyInstaller includes the bytecode (.pyc) files, not the original source (.py) files. 

Is it possible to add the source files within a 1-folder frozen application so that they are used (if present) in place of the corresponding bytecode files?

If not, I believe that there are some use cases where such an option could be quite handy.

**Comment by htgoebel** [comment]
You can simply put `sys._MEIPATH` as first element into `sys.path`. Then your packages in the directory will be imported.

We should have some issue or documentation about this, but I can nor find it yet.

**Comment by tallforasmurf** [comment]
We could document it but I would like to have two bits of information first. One, a possible use case or example. Why would you do this (include a redundant `.py` source file and use it in preference to the compiled `.pyc`)?

Two, some idea of the priority on import. So, myscript.py includes

    sys.path.insert(0, sys._MEIPATH )
    import foo

I suppose there is a `foo.pyc` in the bundle anyway. The presence of `import foo` in the source script would ensure that. Am I sure that at runtime Python will import `os.path.join(sys_MEIPATH,'foo.py')` in preference to the bundled `foo.pyc`?

**Comment by giumas** [comment]
@tallforasmurf: about a possible use case: 
- X wrote the wonderful application APP
- X send APP to Y for testing
- Y discovers a bug on APP
- Y wants to try to fix it without having to recreate the whole environment required by APP

From my understanding, if X add the source code + the suggested "sys.path.insert(0, sys._MEIPATH )" trick, Y will be able to modify the behavior of APP "in place". Am I correct? 

Following on the @tallforasmurf comment, is this a supported feature or just an hack that currently works?

**Comment by tallforasmurf** [comment]
It would not work, because in the one-file bundle, the directory whose path is in sys._MEIPATH is a *temporary* folder. Read the manual section on "how the one-file app works". It is created fresh each time the bundled app runs, with contents supplied only from the bundle.

I do understand the desire to patch an app in the field by supplying one an updated source module -- as opposed to replacing the entire multi-megabyte bundle. But I do not know of a way to do this safely (maybe open a design issue?).

The trick I described would probably work for the one-folder bundle (where sys._MEIPASS is the path to the app folder) BUT do you realize it introduces a gaping security hole? Remember, during `import foo` Python executes any code at the global level of `foo.py`. Anybody could insert any code they liked into your app in this way, to silently do anything they wanted.

**Comment by giumas** [comment]
> It would not work, because in the one-file bundle, the directory whose path is in sys._MEIPATH is a temporary folder. [..]

@tallforasmurf, I stated both in the title and in the body of the this ticket that was specific for "**1-folder** frozen application".

> [..] BUT do you realize it introduces a gaping security hole? [..]

Do you really think that, without adding the source code, it is difficult to insert malicious bytecode in a frozen application (if somebody really wants to do it)?
However, in the use case that I described, I specified that "X sends the frozen APP to Y for **testing**". I was not talking of an official release.

**Comment by tallforasmurf** [comment]
Apologies for not reading your first entry correctly. I do not think this should be documented. One, I haven't actually tried it (although I'm pretty sure it would work). Two, it would only work for one-folder apps. And three, it would make it possible to inject any kind of code into an app. Yes I do think it would be difficult to modify the frozen bytecode of a bundled app. A checksum on the bundled executable would prevent it. (BTW, that's a "recipe" we should have in the wiki, how an app could check its own checksum at startup.)
