### ISSUE TITLE
extract onefile into permanent folder (not temp every time)

### ISSUE THREAD

**Issue by denfromufa** [pyinstaller/pyinstaller#1782]
Is there any way to extract --onefile executable into permanent folder (not temp every time)? So something like "hybrid" between onefile and onefolder options?

The problem is very slow loading (up to 10 seconds) of executable.

**Comment by tallforasmurf** [comment]
The extracted one-file bundle is exactly the one-folder bundle that would have been made.
If you want a single file for distribution,  just zip the one-folder?

**Comment by nchammas** [comment]
If that's what you want, then why not generate a regular one-folder package, zip it up, and distribute it?

**Comment by denfromufa** [comment]
because I want to save the user from messing with the archive. with similar logic I can continue your question to extreme - why not install python, pip, and wheels?

**Comment by tallforasmurf** [comment]
Sounds like you'd want a [self-extracting archive](https://en.wikipedia.org/wiki/Self-extracting_archive). Your user downloads a single file and double-clicks it to display the one-folder app. Inside it would be a README with further instructions.

**Comment by denfromufa** [comment]
@tallforasmurf self-extracting archive is not much different from normal archive.

**Comment by nchammas** [comment]
@denfromufa - I understand what you're saying. The main reason many of us use PyInstaller is because we want to save our users from having to setup a specific Python environment. But comparing that whole process to just asking the user to unzip a file is, I think, not fair. :) Most users have unzipped a folder at some point or other; it's a routine task that can be done very easily.

But to address the root of your suggestion, I don't think it would be right for PyInstaller to automatically extract to a permanent location. The reason is that, despite its name, PyInstaller is actually a _packager_ and not an _installer_.

PyInstaller's job is to bundle up everything a Python application needs into a single package so it runs without requiring any external Python dependencies. Its job is not to make modifications to the system. 

It's up to the user to download the package they want, and it's up to the user to place it in the location they want. PyInstaller doesn't place any binaries on the user's `PATH`, or copy files to permanent locations on the user's system. That's why when you run a `--onefile` executable, everything that PyInstaller does outside of the package gets cleaned up as soon as the executable terminates.

Contrast PyInstaller to a real _installer_ like [Inno Setup](http://www.jrsoftware.org/isinfo.php), which goes out and permanently modifies multiple files in various parts of the user's system, or to a _package manager_ like [Homebrew](http://brew.sh/) which automatically downloads the software and places new executables on the user's `PATH`. Installers and package managers make permanent modifications to the user's system. PyInstaller, again, despite its name, is neither.

Now, it would be pretty neat if PyInstaller could actually be an installer and take care of some of this stuff, but that's out of its scope at the moment. So the hybrid solution you're asking for, while it seems minor, is potentially a change of scope for the project.

@tallforasmurf - Please correct me if I've misrepresented anything about PyInstaller.

**Comment by htgoebel** [comment]
@nchammas Thanks for your explanation. This is absolutely correct.
