### ISSUE TITLE
prelink breaks pyinstaller binaries

### ISSUE THREAD

**Issue by garthy** [pyinstaller/pyinstaller#1812]
Certain Linux distros have a cron job that runs prelink on all binaries. 

Any installed binary which has been created by pyinstaller breaks when this happens

This could be worked around by adding the zip to an ELF section.

**Comment by htgoebel** [comment]
Can you please elaborate what you mean by:
> This could be worked around by adding the zip to an ELF section.

Or even better: submit a pull-request :-)

**Comment by matysek** [comment]
@garthy and @htgoebel I think it means somehow letting ELF header know that it contains more data because now just pyinstaller simply writes additional data to the end of the bootloader.

This looks similar to the fix I did for codesigning on osx where PyInstaller has to modify file length in  MachO header to include the zip archive appended to the end of bootloader.

I think it might work append data to linux bootloader by command `objcopy --add-section`: https://stackoverflow.com/questions/233358/elf-file-headers

**Comment by codewarrior0** [comment]
`objcopy --add-section` sounds like exactly what is needed.

We should be able to see if it works by adding a test case:

- Add a test case that runs `prelink` on a helloworld app after building it.
- Verify the app is broken and the test fails.
- Change the EXE step to, on linux, append the archive using `objcopy` instead of a simple `write`. `objdump` may also be needed to get the correct offset to insert into the cookie.
- Verify the test now passes.

Any Linux-guys want first dibs on this? ;)

**Comment by garthy** [comment]
Ok my thoughts were to build the data into a obj and build with the
bootstraper but that requires a compiler and linker. The objcopy idea is
much better idea.

I can take a look at this but I'm unfamiliar with the pyinstaller code so
if some one could point me to the bit that build the file I may be able to
knock up a patch.

objcopy --add-section sounds like exactly what is needed.

We should be able to see if it works by adding a test case:

   - Add a test case that runs prelink on a helloworld app after building
   it.
   - Verify the app is broken and the test fails.
   - Change the EXE step to, on linux, append the archive using objcopy
   instead of a simple write. objdump may also be needed to get the correct
   offset to insert into the cookie.
   - Verify the test now passes.

Any Linux-guys want first dibs on this? ;)

—
Reply to this email directly or view it on GitHub
<https://github.com/pyinstaller/pyinstaller/issues/1812#issuecomment-185245049>
.

**Comment by matysek** [comment]
@garthy start looking here:
* https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/api.py#L639
* probably modify the method `EXE.copy` with linux specific code

**Comment by htgoebel** [comment]
Sounds good.

**Comment by garthy** [comment]
OK I have it linking the elf section in. The problem is now that the end of
the file has a section header which moves the cookie back quite a way.

https://en.wikipedia.org/wiki/Executable_and_Linkable_Format#File_layout

We have two choices. 2) is the correct one in my opinion

1) search back further for the magic cookie.
2) in the bootloader is use libelf to find the beginning of the archive.

I've actually done 1 as it the easiest

I can't do a prelink test as prelink requires root to run.

**Comment by htgoebel** [comment]
IMHO, option 1 is okay, too.  Maybe we can use a different start-offset or step-size, so searching the cookie is quicker.

Option 2 would be "nicer", but the example code in http://stackoverflow.com/questions/12159595 is a bit too complicated. On the other hand, maybe we could save tome other code, so it would be okay again.

I'm awaiting you pull-request for review :-)

**Comment by garthy** [comment]
I went with 1) due to time constraints. I've used libelf before and probably could knock something up but if 1) is OK, and it's what windows and Mac OSX do, then I'll leave it at this.

**Comment by garthy** [comment]
OK I've updated the patch to pass all the Linux tests. The windows tests are failing but it looks like they are failing on the main project anyway and I'm unsure how to proceed.

**Comment by htgoebel** [comment]
Fixed by #1831
