### ISSUE TITLE
Can't build Mac OS X bundle

### ISSUE THREAD

**Issue by JokerQyou** [pyinstaller/pyinstaller#1823]
Reproducible by following these steps:
- Init a virtualenv named `test` by running `virtualenv test`, and enter that environment by `source test/bin/activate`. 
- Install PyInstaller 3.1.1 by `pip install --upgrade PyInstaller`.
- Create a script `main.py` with the following content: 
    
    ```python
        # coding: utf-8
        import sys
        print >> sys.stdout, 'Hello world'
    ```
    
- Create a spec file by `pyi-makespec main.py`
- Run piinstaller: `pyinstaller --clean --noconfirm --windowed --onefile main.spec`

And there is no `main.app` folder created in `dist` folder.

Environment: Mac OS X El Capitan (`10.11.3`), Python 2.7.10 (Apple version), with PyInstaller 3.1.1.

I'll test latest develop version of PyInstaller later.

**Comment by htgoebel** [comment]
When passing a .spec-file to pyinstaller, options `--windowed`, `--onefile` and others are ignored, since these are options for generating the .spec-file. And as [written in the manual](https://pythonhosted.org/PyInstaller/#id31), `--windowed` is the option which triggers building an OS X .app bundle.

As long as you do not have plans to change the spec-file, there is not need (and no benefit) in calling `pyi-makespec` first - so I suggest using `pyinstaller` directly instead. Otherwise you need to either pass `--windowed`, `--onefile`  to `pyi-makespec`.

**Comment by JokerQyou** [comment]
Thanks for your quick reply! It works now.

**Comment by awa5114** [comment]
@htgoebel  If `--onefile` is ignored when installing with a spec file why then is 
https://pyinstaller.readthedocs.io/en/v3.3.1/usage.html#shortening-the-command full of examples where precisely this is done? Are the docs wrong in this case?
