### ISSUE TITLE
Segfault on wx "hello world"

### ISSUE THREAD

**Issue by terhorst** [pyinstaller/pyinstaller#1825]
On 3.1.1, this simple "hello world" script will segfault when run through `pyinstaller --onefile -w hello.py`:
```
#!/usr/bin/env python
import wx

app = wx.App(False)  # Create a new app, don't redirect stdout/stderr to a window.
frame = wx.Frame(None, wx.ID_ANY, "Hello World") # A Frame is a top-level window.
frame.Show(True)     # Show the frame.
app.MainLoop()
```
Preceding the segfault are a bunch of errors that look like:
```
objc[26024]: Class wxOSXStatusItemTarget is implemented in both /var/folders/v_/4yqlxmpn18jbhpdqcl42z97c0000gn/T/_MEI2FP0d2/libwx_osx_cocoau_adv-3.0.0.2.0.dylib and /var/folders/v_/4yqlxmpn18jbhpdqcl42z97c0000gn/T/_MEI2FP0d2/libwx_osx_cocoau_adv-3.0.dylib. One of the two will be used. Which one is undefined.
```

I suspect this might have something to do with #1750. I'm on OS X 10.11.3 with homebrew-built versions of Python, wxpython and wxmac.

**Comment by htgoebel** [comment]
Obviously both libwx_osx_cocoau_adv-3.0.0.2.0.dylib and libwx_osx_cocoau_adv-3.0.dylib are included.

Pleas use ``--onefile`` as described in https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly and check whether these files are symlinked or different.

**Comment by htgoebel** [comment]
I assume, reverting 536050ac (this is the commit solving #1750) does *not* solve your issue, since modulegraph only handles python modules (including C-extensions, though), not external shared libs.

So the question is: why there are different versions of this lib included? You may try to debug this somewhere in PyInstaller/depend/bindepend.py. (Sorry, I'm short in time so I can not look for a more concrete place yet. Ans this is a part of PyInstaller which I do not know well.)

**Comment by terhorst** [comment]
It seems py2app ran into the same [issue](https://bitbucket.org/ronaldoussoren/py2app/issues/65) (on the same test case, coincidentally). Basically the problem is as you said, symlinks are being dereferenced and copied into the archive as separate, but identical, files. I was able to fix this in --onedir mode by manually recreating the proper symlinks. Is there any sort of hook I can use during the build process to automate this task so that I can switch back to --onefile? Thanks.

**Comment by htgoebel** [comment]
The proper solution - and this is what we should implement - is to detect the symlink and resolve it. So the question is (see my prior comment): Why there are different versions of this lib included?

Since I do not have OS X here, I need your assistance for tracking this down and testing the proposed solution. You may step through `Analysis.assemble()` in `PyInstaller/building/build_main.py` to narrow down where these libs are added.

I assume, `libwx_osx_cocoau_adv-3.0.0.2.0.dylib` symlinks to` libwx_osx_cocoau_adv-3.0.dylib`. Correct?

**Comment by terhorst** [comment]
Actually, the issue looks to be wanky linkage within the wxmac library and not necessarily a bug in pyinstaller. In particular, the several of the dylibs are linking against real names and not sonames, for example:
```
$ otool -L libwx_osx_cocoau_core-3.0.dylib
[...]
/usr/local/Cellar/wxmac/3.0.2_2/lib/libwx_baseu-3.0.0.2.0.dylib (compatibility version 3.0.0, current version 3.0.0)
```
I am pretty sure that that should actually be targeting ``/usr/local/opt/wxmac/lib/libwx_baseu-3.0.dylib``. In fact, going through and manually altering all such references using ``install_name_tool`` fixed this problem and allowed me to successfully to package my script in --onefile mode. 

So, I'm not sure if you want to treat this as a bug in pyinstaller or not. It seems like it's probably doing the right thing, but at this point I have gone far beyond my limited knowledge of how dynamic linking "correctly" works in OS X.

**Comment by htgoebel** [comment]
Thanks for the update. This sound more like a wx-problem then.

**Comment by eliclement** [comment]
@terhorst I'm also having that issue bundling an app in `--onfile` mode. Can you please tell us how you actually did that step using `install_name_tool` ?
I'm a newbie in using `otool` or `install_name_tool` and i don't want to break my homebrew wxmac installation. Thanks!
