### ISSUE TITLE
fix test tests/functional/test_basic.py::test_threading_module2 for Windows

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1841]
these tests for some reason fail in develop branch
```
FAIL tests/functional/test_basic.py::test_threading_module2[onedir] 
FAIL tests/functional/test_basic.py::test_threading_module2[onefile]
```

@codewarrior0 do you have any idea?

**Comment by codewarrior0** [comment]
I'll take a look. The test is failing since cf0965585086f728c265b76bd3eb12ae43e5b6ec, which is actually when the test was first migrated from the old test suite.

test_threading_module2 fails, writing only this to stderr: `Subprocess did not print ONE, TWO, THREE in correct order.` The test also fails locally for me.

Adding more debug info shows the subprocess does not print anything to stdout at all. The subprocess does write `Fatal Python error: Failed to initialize Windows random API (CryptoGen)` to stderr, indicating a failure during `Py_Initialize`. If I recall correctly, this is because the subprocess is given an environ that is missing some variables that are vital to some part of the Windows runtime libs. The solution may be to copy `os.environ` and add the variable used by the test, instead of passing a completely clean environ. There is some similar code in `AppBuilder._run_executable` that preserves most of `os.environ` when calling the subprocess.

After copying `os.environ` and adding the test variable, the test now passes. 

With a slight modification for `sys.executable`, I ran the test in the plain Python interpreter instead of through PyInstaller. It also fails without the `os.environ` change and passes with the change, so this odd initialization error with `subprocess.Popen` isn't specific to PyInstaller - it happens with just Python too.

I'll push the fix in a minute.

**Comment by codewarrior0** [comment]
Will close this issue after the test passes on AppVeyor.

**Comment by codewarrior0** [comment]
The test passes.

Both Appveyor and Travis are now showing failures in test_boto3 and test_botocore due to an update to both packages.

**Comment by matysek** [comment]
@codewarrior0 Thank you a lot for fixing this test.

**Comment by matysek** [comment]
For the tests botoX I created #1844.
