### ISSUE TITLE
Change way for searching the MAGIC in the bootloader?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1850]
In #1831 we changed the python-code for searching the MAGIC and the archive information. We now just read approx. 4KB and search within these. See 
https://github.com/pyinstaller/pyinstaller/pull/1831#discussion_r54336192

The C-code in the bootloader uses a lot of file-seeking to search for the cookie.
see 
https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_archive.c#L361 and
https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_archive.c#L221

This seeking is required for both OS X (for which it already was implemented) and for Linux (since #1831 is implemented).

Maybe we should change the C-code, too? (We need to rebuild the bootloader soon anyway.)

**Comment by codewarrior0** [comment]
As I understand it, the cookie is not always found at the exact end of the file. OS X and Windows may append a digital signature after the cookie; Windows will align the signature struct to the next quadword (8 bytes), and OS X will align its signature to the page boundary (4096 bytes). On Linux, objcopy does something different: The ELF executable file format used on Linux has its "section headers" located at the end of the file, so when objcopy adds the new section to the file, it moves the section headers *forward* so they lie after the newly added section! So we need to scan backwards past the section headers to find the cookie.

So to find the cookie on OS X and Windows, we first check for the cookie immediately before the start of the signature, and go backwards up to the alignment amount to handle the case where the code signing added some padding between the end of the cookie and the start of the signature. On Linux, we scan the entire last 4096 bytes, assuming that the section headers are less than 4096 bytes long. This also handles the case where objcopy added some padding between the end of the new section and the section headers.

4096 bytes is a fair assumption. Each section header is 64 bytes long (for ELF64, at least), so an exe would need to have 64 sections before the headers total 4096 bytes. The highest section count I found in /bin was 30.

--

I don't think the C code needs to be changed at all. It already seems to be more robust than the Python code, since it reads the C structs in the OS X and Windows executable files to find out where the digital signature starts, whereas the Python code only searches through the last 4096 bytes - if archive_viewer is given a signed OS X or Windows exe, it should have failed before #1831 and will still fail now if the signature is longer than 4096 bytes.

But honestly, that's not even worth worrying about. If someone is using code signing on either platform, he has the opportunity to use archive_viewer *before* using the code signing tools on the built exe. And on Linux, the Python code is already identical to the C code, so the changes made by objcopy are handled the same way on both.

**Comment by htgoebel** [comment]
Perhaps I should have been more clear in my decription:

This issue is about the *implementation*, how the cookie is searched in the C-code. Currently it file-seeks byte by byte until it finds the magic. (Even worse: I tries to find it at a known position and if this fails, calls a sub.routine which is iterating.) This could be done more efficient and more easy to understand if reading a chunk of bytes into memory and just iterating over this memory block.

**Comment by codewarrior0** [comment]
OH! I see what you mean now. It's doing repeated `freads` instead of reading the entire 4096 byte area and searching backwards, which is what the Python code does. That, I can do.

**Comment by htgoebel** [comment]
Wow, this was quick :-)
