### ISSUE TITLE
PyInstaller error with sys.exit()

### ISSUE THREAD

**Issue by goodtiding5** [pyinstaller/pyinstaller#1869]
There seems an issue handling sys.exit() or 'raise SystemExit' for python 2.7.

Here is how to reproduce the problem:

Suppose we have a script 'foobar.py':

```
#!/usr/bin/env` python

import sys
import os

if __name__ == '__main__':
    print >>sys.stderr, "This is a test, please ignore!"
    sys.exit(0)
```

Now let's run pyinstaller as `pyinstaller -F -n foobar foobar.py`.  

Run `dist/foobar`, we have the following output:

```
$ dist/foobar
This is a test, please ignore!
Failed to execute script foobar
```
However, if we run `python foobar.py`, it produces:

```
$ python foobar.py
This is a test, please ignore!
```

**Comment by tallforasmurf** [comment]
See [pyi_launch.c#375](http://www.firemountainsolar.com/solar-water-pumps/dankoff-solarforce-accessories/#Repair)

    retval = PI_PyEval_EvalCode(code, main_dict, main_dict);
			/* If retval is NULL, an error occured. Otherwise, it is a Python object */
			if (!retval) {
                FATALERROR("Failed to execute script %s\n", ptoc->name);
                PI_PyErr_Print();
				return -1;
			}

Doc for [PI_PyEval_EvalCode and associates](https://docs.python.org/3.5/c-api/veryhigh.html#c.PyEval_EvalCode).

Doc for sys.exit() says,

> Exit from Python. This is implemented by raising the SystemExit exception, so cleanup actions specified by finally clauses of try statements are honored, and it is possible to intercept the exit attempt at an outer level.

See also [SystemExit exception](https://docs.python.org/3.5/library/exceptions.html#SystemExit).

Not clear to me how you can get the retcode from sys.exit() if PI_PyEval_EvalCode just returns null.

**Comment by htgoebel** [comment]
I tried digging into the Python code to find found what PyEval_EvalCode actually returns, since the doc for [PyEval_EvalCode and associates](https://docs.python.org/3.5/cpi/veryhigh.html#c.PyEval_EvalCode) is not quite clear. I did not find out, since the function comes down to [PyEval_EvalFrameEx](https://hg.python.org/releases/2.7.11/file/tip/Python/ceval.c#l797) which is one of the central functions processing the byte-code - and it quite long. Im'f afraid we need to ask at the python's developer mailinglist.

**Comment by codewarrior0** [comment]
I did some digging, too. PyEval_EvalCode was a dead end, so I grepped the whole src folder for SystemExit and found it is handled in PyErr_PrintEx (via handle_system_exit) by getting the return code from the exception object and passing it to Py_Exit. Py_Exit simply finalizes the interpreter and calls the C function exit() with the exit status.

So when SystemExit is raised, our call to PI_PyErr_Print() should not return.

@goodtiding5 Did you check the exit status of either program? If the exit status is okay, this is just a cosmetic issue with writing the "Failed to execute" message on a run that raised SystemExit. It could be fixed by just calling PyErr_ExceptionMatches(PyExc_SystemExit) or similar to check.

**Comment by codewarrior0** [comment]
Waaaait a second. If PyErr_Print is going to call exit(), then our temp folder will not get cleaned up.

We'll have to either register an atexit function, or trap the SystemExit ourselves and clean up before calling PyErr_Print.

**Comment by htgoebel** [comment]
@codewarrior0 Good catch :-)

**Comment by htgoebel** [comment]
@codewarrior0 What about registering an at-exit function. [Py_Exit](https://docs.python.org/2/c-api/sys.html#c.Py_Exit) calls `Py_Finalize`, which runs the At-Exit function. Maybe this could even solve signal handling #208.

**Comment by codewarrior0** [comment]
I'm not sure about the signal handling issue, but the `atexit` method is much simpler to implement than the exception-checking method. Done.

**Comment by codewarrior0** [comment]
Oh, I see. I wrote a small test to verify the temp folder is removed, and it made me remember that even if the child process (who is running the Python interpreter) exits due to SystemExit, the parent process still continues normally and removes the temp folder.

This is actually pretty nice, because even if the child process exits due to a segfault or other low level error, the parent process will still clean up the temp folder.

I also verified that the return code is correct after raising SystemExit. So this is just a cosmetic issue where it prints "Failed to execute script" after a SystemExit.

**Comment by StratoZen** [comment]
This is still an issue. Seems like the import sys doesn't actually get imported when packaged with pyinstaller. NameError: name 'exit' is not defined is the response to a call of either exit() or sys.exit(0).

**Comment by htgoebel** [comment]
@StratoZen `sys` is a built-in module, thus if sys.exit is missing, I assume your environment is messed up.

**Comment by StratoZen** [comment]
@htgoebel In the same test system, if I run the original python script, there are no errors. If I then run that script through pyinstaller, and run the same script as found in the resulting dist folder, I get the sys.exit error. 

My environment has no issue including the sys module, and it exits w/o error in the script pre-frozen. Once frozen with PyInstaller if fails.

**Comment by StratoZen** [comment]
I should be more specific that I am still seeing this issue in Python 3.6.4. The script once frozen with pyinstaller works with the exception of the sys.exit(0) command. I'm not sure why it appears as missing when the frozen package is run.
