### ISSUE TITLE
push our pefile optimizations upstream

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1920]
I fixed #1357 and that means using upstream pefile versions. However, our customized pefile version contained some optimizations and these optimizations are not used anymore.

We should propagate these changes upstream to https://github.com/erocarrera/pefile/ .

The changes for upstream should be taken from this revision:
https://github.com/pyinstaller/pyinstaller/tree/dae3392f8def6f536c4a8cec57641defc340e75d/PyInstaller/lib

The main advantage of these optimization is to speed up tests on AppVeyor.

**Comment by matysek** [comment]
@codewarrior0 Do you want to take care of this or should I do that?

Please reassign it back to me when I should do that. Thanks

**Comment by stephenrauch** [comment]
Recently moved to 3.2, and this issue has increased some of our build times by about 6x.  Verified this is the source of the slowdown by copying the pefile.py referenced above, over the top of the pip installed version.  I am working on porting the changes to the latest pefile version.

**Comment by codewarrior0** [comment]
@stephenrauch Did you do anything other than copy our old pefile.py? The optimizations I did need some other changes to where PyInstaller calls into pefile to activate them. If all you did was copy the old pefile, then you've found a performance regression in pefile that should be addressed separately.

@matysek Whoops! Don't know how I missed that. I'll gladly take care of this unless Stephen has already beat me to it.

**Comment by stephenrauch** [comment]
@codewarrior0 Good catch, I found the flags to enable the pefile optimizations, but had not yet used them when reporting the 6x speed up.  So the new pefile not only doesn't have your additions, it is much slower (actually 9x slower on my worst build time without your changes).

Here are the times from my measurements, there are two numbers, the entire build time, and the time which is logged as 'Looking for dynamic libraries'.

| pefile | Optimizations Added | Build Seconds | DLL Seconds | Notes |
|:---:|:---:|:---:|:---:|:---|
| new | no | 351 | 305 | shipping 3.2
| old | no | 61 | 10 | shipping 3.2 with 3.1 pefile
| new | yes | 42 | 2.7 | 
| old | yes | 39 | 1.1 | old pefile w/ shortcuts

So, adding your changes to the new pefile, does not make it as fast as the old pefile, but they are pretty close when measured in context of an entire build.

I have the changes [here](https://github.com/stephenrauch/pyinstaller/commit/1b22ebdedff296c7a9eb06bdd8b708be5c3a66b2), someone should look at them.

I forked the pefile repo and put this in it to try and run the tests there, but it looks the test data is encrypted, so that didn't work.  I can do a pull request over there, but thought maybe you should look at it first?

**Comment by stephenrauch** [comment]
So to highlight something from the above note, adopting the new pefile caused the portion of my build time logged under 'Looking for dynamic libraries' to go from __**1.1**__ seconds to __**305**__ seconds....

**Comment by stephenrauch** [comment]
@codewarrior0 merged my changes in #1982, so I will put a note here to remind that, until [upstream ](https://github.com/erocarrera/pefile/pull/117)picks up the pefile changes, the distribution is currently using a version of pefile in the distribution and a version from pypi.  I did this as it seemed senseless to rip out all of the references to the pypi version of pefile, when we will hopefully be putting them all back in shortly.

But right now, the code base is in a middle ground of https://github.com/pyinstaller/pyinstaller/pull/1982/commits/9010ea8bdab27d6fbbada216a7bba3156620bb3f, which once upstream is ready, should be 'mostly' reverted.

**Comment by stephenrauch** [comment]
@bjones1 merged the changes in #2025, so I will put another note here documenting the progress towards using the pypi pefile. Upstream pefile has accepted our shortcuts, but has not yet done a release to pypi.  In addition, as documented in #2019, there is still an issue with pefile setup on some systems.  

Some notes:

1. Most of the changes needed to remove pefile from this repo and use the pypi version are marked with: ``` # ::TODO:: #1920 revert to using pypi version ```

1. When pefile is finally removed from this repo, the lib 'ordlookup' should go as well as it is a component of pefile.

**Comment by htgoebel** [comment]
https://github.com/erocarrera/pefile/pull/117 was merged 2 Jun 2016, but the release including this change is not yet published at PyPI, see https://github.com/erocarrera/pefile/issues/193
