### ISSUE TITLE
Star imports not captured properly

### ISSUE THREAD

**Issue by Adam5Wu** [pyinstaller/pyinstaller#1964]
I recently was trying to upgrade one of my antiquated application, which used PyInstaller 2.0.
But I found large amount of dependencies are missing after trying to pack using latest PyInstaller, master or develop.

After some debugging and tracing I narrowed down to the problem that start imports (from xxx import *) is effectively ignored by the new dependency parser.

In PyInstaller 2.0, file "depends/utils.py" contains code which handles the `__all__` registry from the `__init__.py` of each module.

In the latest PyInstaller, there is no code that cares about `__all__` any more.
The code scanning routine seems to have moved to file "/lib/modulegraph/modulegraph.py". And in this file, the class "Node" does have a field called "starimports", which seems to be related to this function. However, this fields seems never got populated at run time.

A simple test case can illustrate the problem:

- File `test.py`

  ```python
  from tx import *
  t1.test()
  ```

- File `tx/__init__.py`

  ```python
  __all__ = [ 't1' ]
  ```

- File `tx/t1.py`

  ```python
  def test():
        print "XD"
  ```

Run unpacked, the output is:

```
XD
```

Run packed with latest PyInstaller, either using --onefile or --onedir:

```
Failed to execute script test
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from tx import *
AttributeError: 'module' object has no attribute 't1'
```

**Comment by leycec** [comment]
**Ugh** <sup>x 2</sup>. Thanks for the deliciously detailed issue report. I'm on thankless PyInstaller cleanup duty for a week or so, so I'll try to hit this as well.

Since we have a few existing functional (and possibly unit) tests exercising star imports (e.g., `test_scapy()` in `test_libraries.py`) that appear to pass, it seems unlikely that star import support has _entirely_ broken. But something surely has.

In #1919 (_Something Wicked This Way Came to `modulegraph`_), I note a possibly related critical failure in `modulegraph`. In that issue, I demonstrate that PyInstaller fails to freeze the trivial one-line application `import scipy.special`. Significantly, one of the imports implicated in this failure performs a star import: `from .basic import *`.

It's time for some deep-tissue code massaging.

**Comment by htgoebel** [comment]
See #1845

**Comment by leycec** [comment]
_Sweet._ Thanks for the prompt redirect.
