### ISSUE TITLE
PyInstaller 3.2 - missing mcvcr100.dll on Windows

### ISSUE THREAD

**Issue by pjrobertson** [pyinstaller/pyinstaller#1974]
I've been scratching my head for the past few hours, only to realise that Pyinstaller v3.2 wast *just* released, and figured that might be what was causing my problems. Downgrading to v3.1.1 and this issue goes away

When packaging a --onefile app on Windows (GUI app using tkinter, no 3rd party modules) I was getting an error "unable to open file since msvcr100.dll is missing" or similar.

The app was being compiled on Windows 7, Python 3.4.4 with tcl/tk 8.6. This version of windows has a 'msvcr100.dll' file in `C:/Windows/System32` (I'm assuming since it is a dev machine with Visual Studio installed)
Running the `--onefile` exe on this computer works fine.
If I transfer the file to another computer (exact clone of the Windows 7 computer except without any development software installed) I get that error. There is no `msvcr100.dll` file in the System32 folder on this computer.
What is strange is that compiling using the `--onedir` option works fine on both Windows 7 computers (even the non-dev one). It's just the `--onefile` exe that has a problem.

I couldn't find anything strange going on in the output of pyinstaller. Looking at `a.binaries` shows that the `msvcr100.dll` file is already present

Downgrading to pyinstaller 3.1.1 solved the problem instantly.

**Comment by codewarrior0** [comment]
Can't reproduce this with a "hello world" program on a fresh install of Windows 7 x64 on a virtual machine. Will try again with a minimal tkinter program.

**Comment by codewarrior0** [comment]
Can't reproduce with a minimal tkinter program either.

@pjrobertson Are your two Windows installs 64-bit or 32-bit? What about your Python 3.4 install?

**Comment by pjrobertson** [comment]
2 Windows 7 installs are 64 bit. Python 3.4 MSI I used is 32 bit. I then used pip-Win to create a virtualenv on my 'development' Windows machine.

**Comment by scudette** [comment]
Yes. Pyinstaller 3.2 as distributed by PyPi contains the run.exe stub build with VS 2010 which introduces an additional dependency on the msvcrt10.dll.  This is inconvenience because the default python 2.7 system is built with msvcrt90.dll and so in principle only needs that to be distributed. The result is that an app can run fine on a system with regular python, but as soon as it is being packaged with pyinstaller it will need the additional dependency.

![image](https://cloud.githubusercontent.com/assets/3856546/15033961/83c1b6c6-1225-11e6-9744-7376d98e5eaf.png)

**Comment by codewarrior0** [comment]
Whoops! We normally build the `run.exe` using MinGW to avoid any msvcr dependency, but it looks like we must have goofed. I'll rebuild it for the next release.

**Comment by codewarrior0** [comment]
Done. I also confirmed that the rebuilt bootloaders don't link to msvcr100.dll`.

**Comment by m-mcgowan** [comment]
Just a fyi that I was bitten by this too - 32-bit python on 64-bit windows. Any news on when this will be available in a release?

**Comment by scudette** [comment]
Is it possible to make a backported release for 3.2 on PyPi? Users who install pyinstaller from PyPi are surprised to see the breakage and we need to advise them to install from git head (which might introduce other bugs). 

Currently the generally available release is broken by this and due to our need for Cryptography support we can not advise to install 3.1.1 instead.

**Comment by temp56817906847** [comment]
In case anybody else is wondering, the manual solution works like this:  
Copy the Windows folders from https://github.com/pyinstaller/pyinstaller/commit/c1787157ab89546dfc58b8b45207b9cc945ff3d3 into the same folder in your local pyinstaller folder.

**Comment by gaubert** [comment]
@temp56817906847. Did what you suggested by downloading and replacing the exe in site-packages/pyinstaller/bootloader and it worked like a charm. Many thanks.
