### ISSUE TITLE
Pyinstaller Update UnicodeDecodeError

### ISSUE THREAD

**Issue by ckdanny** [pyinstaller/pyinstaller#2019]
Hi, I cannot update pyinstaller and the error mssage said 
`UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 208687: illegal multibyte sequence`

I am using Windows 7 with Python 3.5

![2016-06-01 10_03_55-settings](https://cloud.githubusercontent.com/assets/11786201/15696165/9016751c-27e0-11e6-9c0d-acb4bcca2025.png)

**Comment by stephenrauch** [comment]
That appears to be a problem with pefile (a pyinstaller dependency), not pyinstaller.  If at the command line you do:

```
pip install pefile
```

What does that return?

**Comment by ckdanny** [comment]
@stephenrauch Yup, the same error occur

**Comment by stephenrauch** [comment]
pefile recently added py3 support, and it still has a few challenges.  It appears that pefile has a utf-8 encoded character at that position (208687), and pefile's setup.py is choking with your default encoding (cp950).  I will submit a bug and fix to the pefile repo, but that will not help you in the short term as you need to get a working copy of pefile (that supports python 3.5) installed.

I recently checked in a slightly modified copy of [pefile](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/pefile.py) to this repo.  If you copy it into site-packages and edit the errant character (which is in a comment in line 5326) you might then be able to get pyinstaller going.

**Comment by codewarrior0** [comment]
erocarrera/pefile#105

**Comment by stephenrauch** [comment]
@codewarrior0,

I would argue that this issue should not be closed as there is still an issue with pyinstaller. Namely, since pyinstaller depends on pefile, and pefile has this bug, this causes pyinstaller to be unusable in this case. If you accept that premise, then the discussion becomes: should pyinstaller fully support its own version of pefile until upstream becomes a bit more stable, or is this issue simply kept open as documentation until upstream is ready.

As a side note, I would be willing to fix this issue in our copy of pefile, and finish the removal of the need of the pip version of pefile. (This is primarily relevant if pyinstaller is going to do a release before upstream pefile does).

Cheers,

-- Stephen

**Comment by codewarrior0** [comment]
Good point. Since the pip version of pefile is a bit broken (and we don't use it anyway), we ought to just take it out of the setuptools requirements until it's fixed.

xref: #1920

**Comment by RyPeck** [comment]
Why is the default encoding `cp950`?

**Comment by codewarrior0** [comment]
On his system, that's the default I/O encoding for a Python 3 file object opened in text mode with no encoding argument. The source file in question may in fact declare UTF-8 as its encoding, but only Python's syntax parser will honor that - `open()` will not.

**Comment by yan12125** [comment]
For those who are stucked: use the latest git-master of pefile works for me:
```
python.exe -m pip install https://github.com/erocarrera/pefile/archive/master.zip
```

**Comment by yan12125** [comment]
Thanks for that. Could you add an note to https://github.com/pyinstaller/pyinstaller#installation?

**Comment by stephenrauch** [comment]
@yan12125 

The wiki has a [nice page on how to report bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).  There is says:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Please try latest development version and let us know if the bug is already fixed there. Simply use_

```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   _to install the latest git version._

I believe that to some extent, that already covers this situation.

**Comment by yan12125** [comment]
Sorry, not noticing that.

**Comment by LSChyi** [comment]
Hello, I found a solution on "UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 208687: illegal multibyte sequence" from http://glider.logdown.com/posts/2016/06/01/install-python-34-pyinstaller.
This is a encode problem from your terminal, try to switch your terminal with "chcp 65001"

**Comment by htgoebel** [comment]
@ckdanny @stephenrauch I assume this issue can be closed, now that the upstream pefile inculds our fix, we are using upsteams and the work-around was reverted in 5fd1757edcedb4774aecf1973b086cf58f08b2e6.
