### ISSUE TITLE
The .exe file generated by PyInstaller can not run, reporting ImportError.

### ISSUE THREAD

**Issue by Ngtungfei** [pyinstaller/pyinstaller#2071]
PyInstaller previously worked very well on my PC (Windows 10). 
However, after installing Jupyter/Ipython recently, the newly generated .exe file from the same .py file by PyInstaller did not work correctly, reporting 'No module named Tkinter'. 
I tried to uninstall Jupyter/Ipython and generated the same .exe file by PyInstaller again. It worked well again.

Is there any conflict between the two? How to solve this problem? I want Jupyter installed.

**Comment by Ngtungfei** [comment]
PyInstaller previously worked very well on my PC (Windows 10). 
However, after installing Jupyter/Ipython recently, the newly generated .exe file from the same .py file by PyInstaller did not work correctly, reporting 'No module named Tkinter'. 
I tried to uninstall Jupyter/Ipython and generated the same .exe file by PyInstaller again. It worked well again.

Is there any conflict between the two? How to solve this problem? I want Jupyter installed.

**Comment by stephenrauch** [comment]
If you have problems to get your application running, please first

* follow the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If you problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.

**Otherwise we will not be able to help you.**

**Comment by Ngtungfei** [comment]
Solved by changing the modules' order.
old order:
from Tkinter import *
import tkFileDialog
import matplotlib.pyplot as plt
import numpy as np
import PIL.Image
import pylab
from matplotlib.colors import LightSource, Normalize,LinearSegmentedColormap

New order:
import matplotlib.pyplot as plt
import numpy as np
import PIL.Image
import pylab
from matplotlib.colors import LightSource, Normalize,LinearSegmentedColormap
from Tkinter import *
import tkFileDialog
