### ISSUE TITLE
Run library tests against multiple versions of libraries

### ISSUE THREAD

**Issue by jstewmon** [pyinstaller/pyinstaller#2110]
It would be nice if there were a way to run tests against multiple versions of libraries for cases where pyinstaller has conditional logic based on the version of the library. For example, we could:

1. Use a custom pytest marker to mark tests as applying to a specific library version constraint.
1. Replace requirements-library.txt with a yaml config that lists the libraries and version compatibility constraints that should be tested
1. Wrap the pytest invocation with a script that does the following for each library version constraint:
  1. Creates a virtualenv
  1. Installs the library version
  1. Runs py.test with an option that selects tests with a matching marker

@htgoebel any feedback on this idea?

**Comment by stephenrauch** [comment]
The test suite has already been split in half because of time constraints on appveyor.  So that could be used to support more than one version.

But I would think that supporting every library in the world is hard enough as it is.  Therefore, any support for anything other than the latest (or at least very widely used) version ought to be done only on a best effort basis.

**Comment by jstewmon** [comment]
@stephenrauch I agree that support would only be on a best-effort basis. What I've seen lately is that new versions of libraries require the hooks to be conditionalized, and test may need to vary across library version boundaries (#2109) for example. So, I was thinking that compatibility constraints could be defined on an as-needed basis similarly to how constraints are added to hooks.

For #2109, the current test would be marked as `cherrypy<6.1.0` and a new test would be added and marked as `cherrypy>=6.1.0`. The library config (I mentioned as a replacement for requirements-libraries.txt) would be something like:

```yaml
libraries:
  cherrypy:
    versions:
    - '<6.1.0'
    - '>=6.1.0'
```

**Comment by bjones1** [comment]
Personally, I'm against supporting multiple versions, and would actually like to eliminate all such support at some point when I do cleanup. It makes the code harder to read, harder to maintain, and requires more (fragile) test support which also makes the tests (too long already) take longer to complete.

That being said, I certainly see the use of Python authors who have written code against a certain version and want to freeze against that same version, instead of the latest and greatest. My thought would be git tagging code for hook upgrades (perhaps the cherrypy hook could be `hook_cherrypy>=6.1.0` (if git allows such characters in a tag), so that authors could potentially check this version out, or take the current head and revert changes to get the package support they like. What are yall's thoughts?

**Comment by stephenrauch** [comment]
I would argue that the hardest part of backwards compatibility in the hooks is not really the hook but the testing.  So by best effort I meant that we leave the version conditional code in the hook, as there is a decent chance it will continue to work, but don't support that with test cases, etc.  The test cases would evolve with the supported library, and thus would only necessarily test the supported (likely latest) version of the library.

A warning could be put into the hook when the old version support became deprecated.

**Comment by jstewmon** [comment]
Has using a plugin system (ala sphinx extensions or pytest plugins) for hooks been considered? Using a plugin system may alleviate some of these issues...

* hooks may exist in their own repositories and have their own builds
  * reduces pyinstaller build time
  * improves pyinstaller build stability
  * makes diagnosing / isolating hook issues easier / more visible
  * allows more time and resources to be consumed by a hook build
* developers may pin to any hook package version which is mutually compatible with their library version and their pyinstaller version

**Comment by bjones1** [comment]
@jstewmon, this is a good point. Yes, PyInstaller does -- simply naming a user-defined hook and including it via the `--additional-hook-dir` command-line option will override the built-in hooks. This is probably the best approach: only support the latest and greatest version of a given package in the PyInstaller repo. Authors who prefer an old version can look at the history for the relevant hook files, select the older version, add this older version to their repo, then use in instead of the newer version via a command-line option / spec file statement.

**Comment by jstewmon** [comment]
@bjones1 that's not exactly where I was going with the plugin idea...

Supporting the latest version in the pyinstaller repo is actually the primary cause of failed builds _in my recent experience_ - builds fail because a new version of a library dependency no longer works with the existing hook, tests, or even the install script (`pip-accel install numpy==1.11.1` fails). This makes the development experience confusing, frustrating and time consuming.

The `--additional-hook-dir` is useful when the hook is defined alongside the source in which it is used, but it doesn't facilitate the packaging and distribution of hooks for popular libraries.

My idea for plugins is to move ALL hooks outside of the current pyinstaller repo and package them individually, so that developers can `pip install` the hooks they need. pyinstaller could check for installed hooks by attempting to import the hook for a module from a well-know package namespace such as `pyinstaller.hooks.{module}`.

The upside is that the core pyinstaller source is void of hooks that are largely external concerns which adversely affect the stability of the pyinstaller build, and developers can still share hooks for popular libraries.

**Comment by bjones1** [comment]
That sounds painful from a user perspective -- to run a PyInstaller build, I'd have to run PyInstaller, look at what modules it found, then pip install pyinstaller-module1-hook pyinstaller-module2-hook etc.

Having the builds fail when an external library changes is painful. But, I think it's a good sort of pain -- it means fixes are needed to make PyInstaller work with all the libraries it supports.

IMHO, the biggest problem right now is Appveyor's slowness -- it takes forever to run all the tests. Travis is fairly quick (just 1 hour). I'd like to see some workaround for that (if such a beast exists).

**Comment by jstewmon** [comment]
I don't think it would be painful to list the hook packages for my project in a requirements file, especially since I would only have to list the hooks for the libraries in my project's requirements file (because nested requirements can be automatically included by pip).

For example, if I have a project that has boto3 in as a requirement, I would have a requirements-pyinstaller.txt file with `pyinstaller.hooks.boto3`. The boto3 hook would include `pyinstaller.hooks.botocore` in its requirements .

Finding problems with hook dependencies early is a good thing, but it shouldn't be a barrier to completing an unrelated feature - the discovery happens at the wrong time for the wrong reason. To answer the question, _does this unchanged hook work with the latest version of the library_, a scheduled build is more appropriate. Although not supported by Travis, Semaphore supports [scheduled builds](https://semaphoreci.com/docs/scheduling-builds.html). AppVeyor also appears to support [scheduled builds](https://www.appveyor.com/docs/build-configuration#scheduled-builds).

Having many discrete builds that only run when related code changes, or on a schedule to verify dependencies, will make all builds more efficient. Getting verification from CI for a discrete hook would only take seconds for most hooks. Similarly, it looks like the time to verify changes in the pyinstaller repo would only take a few minutes.

**Comment by htgoebel** [comment]
Thanks for the suggestion and the discussion.
* We will not support multiple versions in tests since this is too complicated and not worth the effort.
* We will not implement a plug-in system for hooks since it is much to complicated, too, esp, for the user.
* An option for using custom hooks (aka `--additional-hook-dir`) in the *test cases* could be useful. We'd appreciate a pull-request for this :-)

Regarding your core problem:
* As long as the hook provided by PyInstaller is working for your package version (be it old or up-to-date), there is no problem.
* If you want to test whether the hook is working with your package version, you "simply" need to patch the PyInstaller's requirements files to include your package version. Or even simpler: Run the tests within the virtual env which you are using for testing your software anyway.
* If an old version of the hook worked, but the new one does not, simply fetch the old hook and include it into your build setup.
* For testing the hook see the last point above.

**Comment by jstewmon** [comment]
My original problem was that I found that the bundled pyinstaller hook for botocore no longer worked with the latest version of the library, and I wanted to fix it but my PR build never succeeded because of unrelated errors, and I thought it would be prudent to include tests for the different versions.

So, the summary from my perspective is just that I didn't need to worry about tests for multiple versions. That relieves me of some responsibility but doesn't address the problem as I perceived it.

My original suggestion about running tests against multiple versions of libraries targeted both the testing of multiple versions, but more importantly defined a way to manage which tests run against which versions of libraries with an easy update mechanism, so that if a test hook failed while working on something else, we could just mark the test for the last version for which it worked.
