### ISSUE TITLE
pyinstaller cache is not multiprocess safe.

### ISSUE THREAD

**Issue by coyotlinden** [pyinstaller/pyinstaller#2210]
As a matter of hygiene, we run pyinstaller with clean.  Our build system is optimized to run multiprocess.  

We have found that if pyinstaller is lauched by more than one process, they exhibit race condition failures around the cache directory.  Examples of such failures manifest as os and shutil failures to create a directory that already exists, remove a file in use by another process or remove the directory which contains files in use by another process.

This forced us to slow down the build by serializing all of the pyinstaller make targets into a single target, adding significant length to the build.

A potential fix would be to test the canonical cache directory and files for use by another process and if so, use the Python tempfile library to create the cache for the second and later runs elsewhere.

A more robust fix would be to change the semantics of --clean from running before the build to running _after_ the build.  If each run is responsible for cleaning up after itself, it eliminates the need for latter runs to try and figure out where the previous run left its files.

A third variation would be to have --cache and --no-cache options.  --cache would behave as it does today and --no-cache would behave as in the previous paragraph.  This would allow developers to choose caching if they want it and pristine runs if they want that behavior.

**Comment by htgoebel** [comment]
We will not implement this, since there is a simple work-around (see below). But we may accept a pull-request for this. A simple inter-process locking mechanism using a file in the cache-dir would solve this.

If you need different cache directories, please set PYINSTALLER_CONFIG_DIR, see http://pyinstaller.readthedocs.io/en/stable/usage.html?highlight=PYINSTALLER_CONFIG_DIR#supporting-multiple-operating-systems.

BTW:

1. The main purpose of a cache is to avoid doing duplicate work. Thus it does not make sense to automatically change the cache location to some random location.

2. Your proposal of auto auto-detecting if another process is accessing the files and then change the cache-dir would add a huge pile of code - except if using a file-lock-mechanism, which can be implemented on a per-file basis and does not require to move the cache directory.

3. Moving `--clean` to be performed after the run would not solve the issue: Then some parallel build would expect to find file in the cache which another process just deleted.
