### ISSUE TITLE
Weird interaction with OpenSSL when calling external program from PyInstaller-packaged program

### ISSUE THREAD

**Issue by nchammas** [pyinstaller/pyinstaller#2237]
This is a weird issue that [one of my users reported](https://github.com/nchammas/flintrock/issues/158), and honestly I'm not sure how it could be related to PyInstaller. But since it only occurs with the PyInstaller-packaged version of my program, here I am.

My program makes calls to `ssh` and `ssh-keygen` using `subprocess.check_call()`. So `ssh` and `ssh-keygen` are basically external dependencies of my program that don't get packaged and that, presumably, PyInstaller knows nothing about. This is normal and it's what I expect.

However, one of my users is [reporting](https://github.com/nchammas/flintrock/issues/158) that, though they can run my software fine when installed via pip, if they run the PyInstaller-packaged version, the calls to `ssh` and `ssh-keygen` fail with the following:

```
OpenSSL version mismatch. Built against 1000207f, you have 1000100f
```

Apparently, calling `ssh` and `ssh-keygen` directly at the command line also works fine for this user.

So I'm at a loss as to why this would happen only when these external programs are called from the PyInstaller-packaged version of my program.

Any clues on how to investigate this?

My program was packaged with PyInstaller 3.2 and Python 3.5.2 on Linux.

**Comment by mellenburg** [comment]
I ran into this same issue. The issue seems to be that when pyinstaller looks for dynamic libraries it finds something like /usr/lib/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so  and then Adding libssl.so.1.0.0 dependency of _ssl.cpython-35m-x86_64-linux-gnu.so

Then, when you run your final artifact, this .so will be dropped in the shared temp folder created at run time with LD_LIBRARY_PATH pointing at it. Thus, if you have old SSL on the machine you built your artifact with, then it will be exported with your artifact and override local SSL everywhere.

**Comment by mellenburg** [comment]
Confirmed: I updated my build system's SSL and all was back to working as expected. I'm very new to PyInstaller, so I can't tell if it is a bug or feature that your artifact will be shipped with the build system's SSL lib overriding your local SSL. Seems a little jarring that system subprocesses will be subverted by LD_LIBRARY_PATH

**Comment by nchammas** [comment]
Wow, thanks for the analysis @mellenburg!

I wonder what the best approach to fix this is going forward. Perhaps a project committer can comment on that. Do we want to change anything about PyInstaller's behavior here?

From a PyInstaller user perspective, it sounds like 2 things I could try immediately are:
* Make sure to update SSL before building my artifacts (which, in my case, is happening on Travis CI).
* Set ` LD_LIBRARY_PATH=$LD_LIBRARY_PATH_ORIG` whenever I make any `subprocess` calls. I picked that tip up from [here in the docs](https://github.com/pyinstaller/pyinstaller/blob/b78bfe530cdc2904f65ce098bdf2de08c9037abb/doc/advanced-topics.rst#bootloader).

**Comment by davidemms** [comment]
Hi

I think I've got the same problem with a different external program that I'm calling. Based on what nchammas suggested and what it says in the linked docs page I was expecting to be able to do something like the following:

my_env = os.environ.copy()
print(my_env['LD_LIBRARY_PATH'])
if getattr(sys, 'frozen', False):
    my_env['LD_LIBRARY_PATH'] = my_env['LD_LIBRARY_PATH_ORIG']   

def RunCommand(command):
    subprocess.call(command, env=my_env)

but when I run the executable created by pyinstaller (single file mode) it turns out the LD_LIBRARY_PATH_ORIG isn't defined although LD_LIBRARY_PATH has been modified by pyinstaller. Am I missing something? I'm using pyinstaller version 3.2.

Thanks
David

**Comment by davidemms** [comment]
Sorry, I thought it was in version 3.2 but it isn't. I've installed the development version and can now see LD_LIBRARY_PATH_ORIG.

**Comment by ThomasWaldmann** [comment]
https://github.com/pyinstaller/pyinstaller/pull/2153/commits/0db8f262b44d1d5dbf027bb349f94bb2f4695eb5

**Comment by nchammas** [comment]
Closing this since it appears from @ThomasWaldmann's comment that this is [already documented](https://github.com/pyinstaller/pyinstaller/blob/483c819d6a256b58db6740696a901bd41c313f0c/doc/runtime-information.rst#ld_library_path--libpath-considerations). Thanks for the pointer!
