### ISSUE TITLE
MKL DLLs cannot be excluded using --exclude-module

### ISSUE THREAD

**Issue by kokes** [pyinstaller/pyinstaller#2270]
I noticed that MKL started being included whenever numpy is being bundled (#1881, #2111). I don't really need it, so I tried `--exclude-module=mkl`, but to no avail. Do I need a lower level setting to exclude all these DLLs? The issue is that I'm using `--onefile`, so I can't quite delete the DLLs manually.

I'm running the dev version (483c819) on Windows, Python 3.5 through Anaconda (32-bit). A minimum reproducible example:

`$ cat foo.py`
```
import numpy as np

print(np.random.randn(5, 5))
```
`$ pyinstaller --exclude-module=mkl foo.py`
`$ ls -l dist/foo/mkl*.dll`

Thanks!

**Comment by Splo0sh** [comment]
You could try to use `conda install nomkl` in the anaconda environment that you are using ([source](https://docs.continuum.io/mkl-optimizations/)). This essentially installs numpy and scipy without mkl. I'm not near a windows machine at the moment, so I can't try/verify it.

I just found your post here because I had a problem with mkl libs and packaging something under macOs X. Good luck.

**Comment by gastoneb** [comment]
@coraxx That's a good idea. Unfortunately nomkl doesn't seem to exist for Windows at this time.

**Comment by answerquest** [comment]
Hi, I found a better solution here: https://stackoverflow.com/a/48846546/4355695
It advises to create a virtual environment using `conda`, and then to forget conda and install `pandas`/`numpy` using `pip`. The list of command lines given is very handy. In there is also a one-liner to add the pandas hook into `pyinstaller`'s hook folder to get around the `timedeltas` error. This way the `mkl..` modules never get installed even though numpy and pandas do. It helped reduce my dist's bloat from 600+MB to 28MB. (that is with UPX compression.. without it, it was ~80MB).

*Note*: In case your program is actually using some functionality that the mkl modules provide then this solution is not applicable for your case.

**Comment by htgoebel** [comment]
@answerquest Thanks for this workaround.

**Comment by answerquest** [comment]
@htgoebel I got another workaround from the conda-forge team: Use this alternative conda command to install numpy:   
`conda install -c conda-forge numpy to install numpy`  
it replaces mkl with [OpenBLAS](https://github.com/conda-forge/openblas-feedstock). I haven't tried it on my end yet, but the source tarball is 11MB while mkl's source was 200MB so I'm hopeful that it won't balloon the dist size. Plus it solves the licensing issue (`mkl` turns out to be not fully open-licensed, avoid if not needed!)

And I'd love to see exactly which numpy commands actually make use of `mkl` or `OpenBLAS`.

**Comment by FSund** [comment]
Just tested @answerquest's fix, and it works great. My numpy-only project went from ~200 MB to 15 MB (with UPX).

A bit off-topic: Is there any way to get a similar (no-MKL/OpenBLAS) version of scipy? I have a different project which uses some scipy functions, and installing scipy from `conda-forge` also installs the MKL libraries.

**Comment by answerquest** [comment]
@FSund glad it helped. For scipy you could file a request here: https://github.com/conda-forge/scipy-feedstock  
Have you tried `conda install -c conda-forge scipy` ? (I'm won't be going on windows OS anytime soon so can't check from my end.

**Comment by FSund** [comment]
@answerquest Yep, `scipy` from `conda-forge` installs the MKL libraries.

```
$ conda install -c conda-forge scipy
Solving environment: done

## Package Plan ##

  environment location: C:\Users\filip\Anaconda3\envs\tmp

  added / updated specs:
    - scipy

The following NEW packages will be INSTALLED:

    icc_rt:       2017.0.4-h97af966_0
    intel-openmp: 2018.0.0-8
    mkl:          2018.0.2-1
    mkl_fft:      1.0.2-py36_0          conda-forge
    mkl_random:   1.0.1-py36_0          conda-forge
    numpy:        1.14.2-py36h5c71026_1
    scipy:        1.0.1-py36hce232c7_0
[...]
```

I'll check the `scipy-feedstock` repo.

**Comment by choice17** [comment]
finally, I found out the most simplest way to me is to manually remove the items from a.binaries list at .spec file

```python
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
```
```python
Key = ['mkl','libopenblas']

def remove_from_list(input, keys):
    outlist = []
    for item in input:
        name, _, _ = item
        flag = 0
        for key_word in keys:
            if name.find(key_word) > -1:
                flag = 1
        if flag != 1:
            outlist.append(item)
    return outlist

a.binaries = remove_from_list(a.binaries, Key)
```
```python
exe = EXE(pyz, ...
```

**Comment by buckettt** [comment]
@choice17 This worked for me -  saved 500MB on a simple XLWings project.
