### ISSUE TITLE
How to use pyinstaller hooks for own package

### ISSUE THREAD

**Issue by simonvanderveldt** [pyinstaller/pyinstaller#2294]
I've been trying to get pyinstaller's hooks working for my own package, but I'm not having much luck with it. All examples I can find are for dependencies of the project instead of the project itself. It seems I need to add a hook to add a `copy_metadata` action because when using pyinstaller my version info, which comes from `pkg_resources.get_distribution`, doesn't work.

I've created a `pyinstaller/hooks-fleet-service.py` file, which I guess is the correct name since that's the name of the project in [`setup.py`](https://github.com/simonvanderveldt/fleet-service/blob/master/setup.py#L4) and added the `pyinstaller` directory to the `hookspath`.
But for some reason this file is never actually processed.

Am I doing something wrong or is it simply impossible to use hooks for your own package?

**Comment by simonvanderveldt** [comment]
Anyone?

**Comment by tallforasmurf** [comment]
Could you spell out your goal in more detail? What part of your application is not getting bundled, and why?

As [documented](http://pythonhosted.org/PyInstaller/hooks.html) the point of a hook is to add modules (usually) or sometimes to exclude them, when the need for that is not evident in the source file as an import. So every time PyInstaller processes an `import foo` it looks for `hook-foo.py` and if it exists, executes it.

But the hook mechanism is to provide those services for public libraries like PyQt or Django. When you are dealing with adding modules to a specific app, you have the `--hidden-import` option. When it's data files, there's a [whole mechanism for that](http://pythonhosted.org/PyInstaller/spec-files.html#adding-files-to-the-bundle). Or if you really want a local hook, you can write it and put it in a local folder and use `--additional-hooks-dir` to point to it.

Since it's executable, you can put a print statement in your hook to make sure it is being called.

So in more detail, what are you trying to achieve and what is happening?

**Comment by simonvanderveldt** [comment]
@tallforasmurf Thanks for the information/context.

What I'm trying to do is using the `version` as defined in `setup.py` in my code. There seem to be multiple ways to do so, but the one that seems to be the "proper" one uses `pkg_resources.get_distribution()`. Now when I use this it works fine when not packaged up with pyinstaller, but once I package it into a single binary using pyinstaller I'm unable to get the version.

Sample code
```
...
from pkg_resources import get_distribution, DistributionNotFound
...

__version__ = None  # required for initial installation
try:
    __version__ = get_distribution('foo').version
except DistributionNotFound:
    __version__ = 'Please install this project with setup.py'
```

When running a binary built using pyinstaller it always returns `Please install this project with setup.py`

**Comment by htgoebel** [comment]
I assume, you already followed [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) and verified that all required data is part of the archive resp. executable.

So i looks like your problem is not about hooks, but about `pkg_resources.get_distribution`, right?

**Comment by bjones1** [comment]
@simonvanderveldt, I'd guess you need to add `copy_metadata('the_module_you_want_to_use_with_pkg_resouces') to your hook. There's some discussion at #1701.

**Comment by htgoebel** [comment]
> I've created a pyinstaller/hooks-fleet-service.py file, which I guess is the correct name since that's the name of the project in setup.py and added the pyinstaller directory to the hookspath.

The hook needs to contain the package name, which is `fleet_service`, thus the hook needs to be called `hooks-fleet_service.py`. See https://pyinstaller.readthedocs.io/en/stable/hooks.html.

Since there was no update for this issue since more than six months, I consider this solved. If you have any further question please reopen.

**Comment by tucked** [comment]
Related: https://github.com/googleapis/google-cloud-python/issues/1187#issuecomment-254654658

**Comment by cfclrk** [comment]
The hook file works well for this. I created a minimal project that demonstrates this approach:
https://github.com/cfclrk/python-demo

I would be interested if anyone has any ideas for how to make it any simpler; for example it would be nice to accomplish this without introducing a hook file. Maybe the `.egg_info` directory could be treated as a data file?

**Comment by cfclrk** [comment]
Ah, I revisited this tonight and found that you can, in fact, just use `copy_metadata()` right in your pyinstaller spec file (instead of introducing a hook). Like this:
```
from PyInstaller.utils.hooks import copy_metadata

a = Analysis(
    datas=[
        *copy_metadata(THIS_PROJECT_NAME),
    ],
    ...
)
```
This will copy the current project's metadata into the binary Pyinstaller creates, and you will be able to access the metadata with `pkg_resources` or `importlib.metadata`. Much nicer!

I've updated a working example [here](https://github.com/cfclrk/python-demo/blob/945d3f9d3609aadd37044c53cc91f28779b5e1a0/pyinstaller.spec).
