### ISSUE TITLE
Osx App bundled - Different locales according to launch mode

### ISSUE THREAD

**Issue by johaven** [pyinstaller/pyinstaller#2298]
I run this test with the last developper version.
When i start my app with open command (open blabla.app), i get these locales:

>LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL=

When i double click on it:

>LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

This prevents me from determining the translations to be made in my code.
Why this behaviour ?

**Comment by johaven** [comment]
any up ?

**Comment by BoboTiG** [comment]
What is the result when you use [setlocale()](https://docs.python.org/3/library/locale.html#locale.setlocale) at the beggining of your script?
```python
import locale
locale.setlocale(locale.LC_ALL, "")
```

I had no luck to make that working because it relies on envars that seem to be not available. But I would be curious to see if it makes a difference for your case.
