### ISSUE TITLE
Failed to execute script pyi_rth_qt5plugins

### ISSUE THREAD

**Issue by MagicalBomb** [pyinstaller/pyinstaller#2301]
I can run on my computor , 
but when I run it on my brother's computor , it tipped me , "Failed to execute script pyi_rth_qt5plugins".

I have no idea what causes  the issue

**Comment by tallforasmurf** [comment]
If you have pyi_rth_qt5plugins, which is the "run-time hook" to initialize for PyQt5. Probably one or more of the PyQt libraries was not bundled. Have you looked at the warnings displayed while pyinstaller is running? Or in the warning file in your build folder?

There have been several issues related to not bundling PyQt modules lately, see #2152, #2141, others. In many cases this has been solved by installing the current dev version as described in the fourth bullet point on this page: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by tallforasmurf** [comment]
You have now opened three issues on the same subject (#2280, #2279). In those two you show PyInstaller output that has **many** warnings like this example:

    4415 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qico.dll

That says that one of the Qt modules, in this case `Qt5Core.dll`, was *not found* and that means it was **not included in the app**.

Therefore it is no surprise when the very first code that tries to use Qt --  `pyi_rth_qt5plugins` which is called from the bootloader -- fails immediately.  Of course it fails, it probably tries to import QtCore which is not there.

(You might ask: why did it only say warning, not error? The answer is, because there are many modules imported by the standard library which do not matter if they are missing.)

Your problem is that PyInstaller is not finding the Qt libraries. From the messages you post in #2279 it looks as if it did not find ANY of them. 

The exact same problem is #2152 and there you will find at least two different temporary solutions. However that issue is not closed and more is to be done.

**Comment by htgoebel** [comment]
@tallforasmurf Thanks for looking after this.

**Comment by ChadSki** [comment]
I found this issue via Google. Initially my error messages said "Failed to execute script pyi_rth_qt5plugins", but the problem ended up being #1688

**Comment by danielhrisca** [comment]
What worked for me was to add PyQt5.uic.plugins to hidden imports in the spec file
