### ISSUE TITLE
PyInstaller broken on Python 3.6

### ISSUE THREAD

**Issue by cocodevienne** [pyinstaller/pyinstaller#2330]
I cannot install PyInstaller on Python 3.6. Everytime I attempt to install it, I get a ton of errors. Please fix this asap. I need PyInstaller for a svhool project.

**Comment by nchammas** [comment]
This is a dup of #2329.

> Please fix this asap. 

Please don't use this language when asking for help on an open source project. People generally contribute to open source as volunteers in their free time, and they are not obligated to jump at your demand because you have a deadline. 

Your best option is to stick with Python 3.5.2 until support for 3.6 lands.

**Comment by htgoebel** [comment]
Python 3.6 is not yet supported, see http://pyinstaller.org.

@nchammas Thanks for backing :-)
