### ISSUE TITLE
Document the parameters of the Analysis class

### ISSUE THREAD

**Issue by marcelstoer** [pyinstaller/pyinstaller#2358]
Reading https://github.com/pyinstaller/pyinstaller/blob/develop/doc/spec-files.rst#spec-file-operation I was expecting to find a brief explanation for all the parameters of the Analysis class (`pathex` et.al.). Currently only the parameters related to dependencies are documented (`datas` et.al.).

For my needs the notes you have in the source code at 
https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/build_main.py#L120 would have been enough.

Any reason they're missing or would you welcome a PR to fix that?

**Comment by tallforasmurf** [comment]
The concern is that everything actually documented has to be supported into the future. The doc creates an API and any future change will break that API. What you see in the docstrings that is not specifically documented, can be changed because only other code "knows" about it.

That said, feel free to hack on the doc and offer a PR. What specifically did the docstrings teach you that was so helpful?

**Comment by marcelstoer** [comment]
> The doc creates an API and any future change will break that API.

That's why the doc is in the code repo, is properly versioned and changes with the code. Besides, future breaking changes with break existing `.spec` files anyway but w/o that being properly documented will leave users stranded.

> What specifically did the docstrings teach you that was so helpful?

I learned what `pathex` is for and that it's actually optional. Quite helpful to know if you intend to create cross-platform `.spec` files.

**Comment by Legorooj** [comment]
I'm closing this. Please submit a PR if you'd like the Analysis class documenting.
