### ISSUE TITLE
Correct worflow for multi module import and Pycharm

### ISSUE THREAD

**Issue by Dariusz1989** [pyinstaller/pyinstaller#2404]
Hey

Not sure where the hiccup is but here is my more or less layout:

Pycharm
Project:
ProjectA
ProjectB
ProjectC

I have file in ProjectC that I'd like to exe up. I import in that file modules from projectC and projectA. Each of these modules can import more modules, from say ProjectA/ProjectB etc etc.

How do I inform Pyinstaller of all the modules that needs to be taken care off?

I tried doing 
sys.path.append(projectAPath)
sys.path.append(projectBPath)
sys.path.append(projectCPath)

But the modules are never taken. They are linked to, so if I delete file from HDD the program no longer works. Meaning, how can I include these modules?

**Comment by xoviat** [comment]
This is not a q&a for python beginners. You need to be familiar with setuptools and specifically [`setup.py develop`][1].

[1]: http://tjelvarolsson.com/blog/begginers-guide-creating-clean-python-development-environments/#making-use-of-setuptools

**Comment by Dariusz1989** [comment]
Humh so there is no argument like -collectModules or something like that that would automatically collect all modules to right folder/place?

**Comment by xoviat** [comment]
There Is the pathex argument in the spec file, as I demonstrated previously. But standard practice is to use `setup.py develop` for developing libraries that are used in an application.

**Comment by htgoebel** [comment]
PyInstaller automatically collects all modules you program imports. So you need to make yourself familiar how to create a proper python program which runs "outside" of Pycharm. I suggest making all your projects into proper python packages (see https://packaging.python.org/) and using a pyvenv (or virtualenv) to but them all together.

Closing this issue, since it is not a PyInstaller issue.
