### ISSUE TITLE
texlive dependencies in pyinstaller

### ISSUE THREAD

**Issue by Terrydaktal** [pyinstaller/pyinstaller#2408]
I have packaged my program using pyinstaller and it works on the host machine. My program makes use of latex to produce .pngs to load into the kivy gui. The only reason the .exe works is because the host machine has texlive on it. Upon distribution, this may be another story for the recipients of the application's machines, how can i include the dependencies on texlive, texlive-latex-extra, texlive-fonts, dvipng etc in the .spec file.  I have searched online and found 0 documentation with regards to latex and pyinstaller, thanks.

**Comment by htgoebel** [comment]
You would need to package huge parts of latex, so I suggest to not to this. Either require this to be already installed (on GNU/Linux) or put it into an installer (Windows). PyInstaller is not build for this kind of stuff. And even if you manage to find all files you need, they will not work, since they most probably expect to be installed system-wide.
