### ISSUE TITLE
Do I have a way to add the -o option to python interpreter, except to modify the pyinstaller code.

### ISSUE THREAD

**Issue by yingxuanxuan** [pyinstaller/pyinstaller#2442]
I use `if __debug__: pass` expression in my code, the `__debug__` is False if Python was started with an -O option. PyInstaller document said 'Run-time Python Options' don't support '-O' option.
Do I have a way to add the -o option to python interpreter, except to modify the PyInstaller code.

Or another way of saying, how can I make PyInstaller compiled Python scripts to .pyo rather than .pyc?

**Comment by xoviat** [comment]
> Do I have a way to add the -o option to python interpreter, except to modify the pyinstaller code.

There is no way to add the "o" option at runtime. The PyInstaller binary does not contain any source code. 

> Or another way of saying, how can i make pyInstaller compiled Python scripts to .pyo rather than .pyc?

PyInstaller uses the builtin `compile` function to pre-compile all scripts going into the executable. We would have a difficult time supporting the -o option because it's not supported on Python 2.7. If you want, you can grep for all `compile` functions in the PyInstaller code and set `optimize=1`, [as noted in the documentation](https://docs.python.org/3.6/library/functions.html?highlight=compile#compile).

On the PyInstaller side, it [looks like](https://travis-ci.org/xoviat/pyinstaller/jobs/192016680#L901) __debug__ is set to True even when the script is frozen. We might be able to change that in the bootloader...

**Comment by yingxuanxuan** [comment]
Thank you for your reply. It helps me a lot.

**Comment by htgoebel** [comment]
You can simply run `python -O /path/to/pyinstaller/` or `python -O -m PyInstaller`.

I have to admit that this is not obvious since pyinstaller is installed via pip, but it still works. I'd not spend too much effort on this as `.pyo` files are bound to be removed soon (no source at hand ATM).
