### ISSUE TITLE
Set __debug__ if bootloader is debug, else not

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2443]
Currently `__debug__` is always set to True because the -O option is never added during compilation. I propose that `__debug__` be set to True if the bootloader is a debug bootloader, otherwise false.

[The relevant statement is here][1].

[1]: https://github.com/pyinstaller/pyinstaller/blob/a70b20e4de6a6817987d28ca9f3201c8105fd858/bootloader/src/pyi_pythonlib.c#L211

**Comment by xoviat** [comment]
To be clear, the proposal is this:

```
#ifdef LAUNCH_DEBUG
    *PI_Py_OptimizeFlag = 1;
#endif
```

**Comment by xoviat** [comment]
@htgoebel

**Comment by htgoebel** [comment]
You can simply run `python -O /path/to/pyinstaller/` or `python -O -m PyInstaller`.

I have to admit that this is not obvious since pyinstaller is installed via pip, but it still works. I'd not spend too much effort on this as `.pyo` files are bound to be removed soon (no source at hand ATM).

**Comment by xoviat** [comment]
Will `__debug__` also be removed?

**Comment by htgoebel** [comment]
Oh, I was wrong: `.pyo`-files are already gone in Python 3.5 (see https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-488), and optimizations are kept as we are used to, just the file names are changes (see https://www.python.org/dev/peps/pep-0488/#id25). So I assume the behavior of `__debug__` is still the same.

Nevertheless changing the bootloader does not help anyway, since PyInstaller does not freeze the source, but the byte-code. Which means setting `PI_Py_OptimizeFlag = 1;` has no effect.

**Comment by xoviat** [comment]
> Which means setting PI_Py_OptimizeFlag = 1; has no effect.

I know that it has no effect on optimization, but I believe it does control the value of `__debug__`.

**Comment by xoviat** [comment]
Looks like it is possible to comment on a closed ticket. You got me @htgoebel.
