### ISSUE TITLE
Running Python script from subprocess

### ISSUE THREAD

**Issue by jcgeuze** [pyinstaller/pyinstaller#2471]
Hello, Please give some advice how to go about this.

Python 2.7.9, Pyinstaller 3.2.1

I have a script that performs this action 

    my_env = os.environ.copy()
    my_env['PYTHONHOME'] = ''
    my_env['PYTHONPATH'] = ''
    my_env["PATH"] = "/usr/sbin:/sbin:" + my_env["PATH"]
    output = subprocess.check_output(['yum','check-update'], shell=False, env=my_env)

This returns me an error from yum telling me that it is missing libraries. 

What i think that is going on is that yum is a python script and it is being run on version of python that was compiled with pyinstaller.  So my question is, how can i run yum with the python version from the OS, using subprocess?

**Comment by tallforasmurf** [comment]
So there exists a script `/usr/sbin/yum` or `/sbin/yum` which begins with a "hashbang" like `#!/usr/bin/python` ? And you are trying to run this via subprocess. Because of the environ you have created, this should invoke the locally installed python (whatever is named in the hashbang) and it should look for imports in the locally installed python's default library.

Is that what you want? Or are you asking for a way for the locally-installed python to find yum's modules inside your pyinstaller-created app? (Which I don't think could be done.)

**Comment by jcgeuze** [comment]
Yes, the script /usr/bin/yum starts with #!/usr/bin/python. I would like to run this script from a subprocess but  it needs to use the python that came with the OS not the one that is compiled with pyinstaller.

**Comment by tallforasmurf** [comment]
>  it needs to use the python that came with the OS not the one that is compiled with pyinstaller

OK, I strongly suspect you need to use the `shell=True` argument to subprocess.

    subprocess.check_output("/usr/bin/python --version",stderr=subprocess.STDOUT,shell=True)

(However, I think that also requires the first argument to be a single string not a list, `"yum check-update"` although I'm not certain about that.)

**Comment by htgoebel** [comment]
I can't see how this issue should be related to PyInstaller: You are calling an external program and the external program has an error. So you need to fix the external program. Maybe yum requires some PYTHONPATH to be set?

**Comment by jcgeuze** [comment]
subprocess.check_output("/usr/bin/python --version",stderr=subprocess.STDOUT,shell=True) returns the version that was compiled with pyinstaller not the OS version. 

How can it be possible that /usr/bin/python returns the wrong version, does pyinstaller overwrites this?

**Comment by tallforasmurf** [comment]
That should not be the case. Running on Mac OS:

~~~~
$ cat shelltest.py
import subprocess
output = subprocess.check_output(
    '/usr/bin/python --version',
    stderr=subprocess.STDOUT,
    shell=True )
print(output)
$ python --version
Python 3.5.1
$ /usr/bin/python --version
Python 2.7.10
$ python shelltest.py
b'Python 2.7.10\n'
$ pyinstaller -y shelltest.py
33 INFO: PyInstaller: 3.3.dev0+483c819
33 INFO: Python: 3.5.1 <<<NOTE
 blah blah...
62 INFO: Building COLLECT out00-COLLECT.toc
$ dist/shelltest/shelltest
b'Python 2.7.10\n'
$ # build windowed to an app
$ pyinstaller -y -w shelltest.py
34 INFO: PyInstaller: 3.3.dev0+483c819
34 INFO: Python: 3.5.1
 blah blah...
85 INFO: Building COLLECT out00-COLLECT.toc
446 INFO: checking BUNDLE
446 INFO: Building BUNDLE because out00-BUNDLE.toc is non existent
446 INFO: Building BUNDLE out00-BUNDLE.toc
807 INFO: moving BUNDLE data files to Resource directory
$ dist/shelltest.app/Contents/MacOS/shelltest 
b'Python 2.7.10\n'

**Comment by htgoebel** [comment]
> How can it be possible that /usr/bin/python returns the wrong version, does pyinstaller overwrites this?

No, PyInstaller does not do such magic things. Chances are 10:1 that this is some weird problem in your operating system.

**Comment by chuan** [comment]
> How can it be possible that /usr/bin/python returns the wrong version, does pyinstaller overwrites this?

PyInstaller changed the LD_LIBRARY_PATH. /usr/bin/python likely picked up the wrong Python libraries and returned version of the library on the custom LD_LIBRARY_PATH. Check out the workaround at the link below.
```Python
env = dict(os.environ)  # make a copy of the environment
lp_key = 'LD_LIBRARY_PATH'  # for Linux and *BSD.
lp_orig = env.get(lp_key + '_ORIG')  # pyinstaller >= 20160820 has this
if lp_orig is not None:
    env[lp_key] = lp_orig  # restore the original, unmodified value
else:
    env.pop(lp_key, None)  # last resort: remove the env var
p = Popen(system_cmd, ..., env=env)  # create the process
```
(Source: https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations)
