### ISSUE TITLE
Move ctypes scanning to PyiModuleGraph

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2488]
Currently `ctypes` scanning is done far after scanning the byte-code and far outside modulegraph. This should be moved towards PyiModuleGraph or even Moduelgraph (if upstream is interested).

Scratch:
- [x] ~~~ask upstream if interested~~~ License conflict
- [x] ~~~If upstream is interested, move the ctypes-related code from depend.utils to modulegraph.util.~~~
- [ ] Run `depend.util.scan_code_for_ctypes` at the end of `ModuleGraph._scan_code()`. (If upstream is not interested, override this method in PyiModuelGraph.)
        Scanning should be done *after* processing the imports and only if the module imports `ctypes` (if cytypes is in `graph.getReferences(…)`). This will recurs over the byte-code again, but should be much more efficient than scanning *every* module. Rational: ctypes is more or less rarely used and presumable modules using ctypes are not that deeply nested.
- [ ] Write some unit-tests for this to catch errors early.
- [ ] Remove `PyiModuleGraph.get_co_using_ctypes()`.
- [ ] Replace the [ctypes-related code in Analysis](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/building/build_main.py#L498) by something using the results of the scan.
      Maybe moving this code-part up a bit (above "Update 'binaries' TOC and 'datas' TOC") could save some code for generating TOC or "binaries" in dependutils (needs investigation)

**Comment by xoviat** [comment]
BTW, this is not a performance issue. This is a feature issue and a maintenance issue.

**Comment by htgoebel** [comment]
Uh, it just came to my mind that we can not move the PyInstaller code into modulegraph since the later it MIT licensed, while PyInstaller if GPL. This was not a problem in the last "move", since the code was mine, but the ctypes-code has multiple author's (including me), all of which would need to permit the license change for this code-part (which I will not for my parts).

**Comment by xoviat** [comment]
Ugh. I was hoping to reincorporate the changes to modulegraph back into upstream so that there would only be one copy of modulegraph rather than two. Do you think that is still possible?

> all of which would need to permit the license change for this code-part (which I will not for my parts).

Yeah. Personally I have all of my projects under GPL that I can. Your hesitancy to allow the ctypes scanning to pass into MIT is perfectly reasonable IMHO.

Coming back to the previous topic, I don't see any license for that specific folder or terms covering modifications to modulegraph, so it would appear that it has been relicensed under the GPL. Which would mean that all authors would have to grant permission for all changes made to be relicensed under the MIT. What a nightmare.

**Comment by xoviat** [comment]
@htgoebel I can get started on this once the iterative modulegraph is merged.
