### ISSUE TITLE
Ctypes issues

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2497]
Tests failures appeared after 17a49a9 was merged, so I reverted the commit with 3d7d8a46adbfa5fc1f13886c6c4ea64f6e70b5d2. That [seems to have fixed](https://travis-ci.org/xoviat/pyinstaller/jobs/210158926#L2005) some of the failed tests but not others.

Here are the problematic tests:

- [ ] tests/unit/test_pyimodulegraph.py::test_get_co_using_ctypes_from_extension
- [ ] tests/functional/test_import.py::test_ctypes_CDLL_find_library__gs[onedir]
- [ ] tests/functional/test_import.py::test_ctypes_CDLL_find_library__gs[onefile]
- [ ] tests.functional.test_import.test_ctypes_gen[onedir-cdll.LoadLibrary]

In addition, the logging now appears to be set to TRACE in the tests, which obviously generates too lengthy logs.

**Comment by xoviat** [comment]
Closed in c29dead.

**Comment by htgoebel** [comment]
Thanks for taking care of this :-) The fixes have already been in my test-queue, but piled under others still failing changes.

Regarding the TRACE: This is caused by `caplog`, which sets the "root" logger's level to "NOTSET". So this will occur every now and then until https://github.com/eisensheng/pytest-catchlog/pull/38 is implemented.
