### ISSUE TITLE
Pyinstaller not finding cryptography hook

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#2525]
I'm using the latest version of pyinstaller and when I run it I get the following error message:

    9007 INFO: Loading module hook "hook-cryptography.py"...
    kg_resources.DistributionNotFound: 
    The 'cryptography' distribution was not found and is required by the application

I have checked and the cryptography distribution is definitely available, but for some reason pyinstaller doesn't find it. Is there a way to edit the spec file to make it work?

Interestingly, when I search for the hook-cryptography I find a .py file which is  in the pyinstaller/hooks folder.

**Comment by xoviat** [comment]
Post the full output in a gist with the latest development version and the argument `--log-level=TRACE`. You can install the development version with:

    pip install git+https://github.com/pyinstaller/pyinstaller.git

This will greatly speed up debugging.

**Comment by keryil** [comment]
I ran into the exact error today while packaging a program for OS/X El Capitan. For some reason, PyInstaller has decided I don't have cyrptography installed. I can import it just fine on a Python shell. Installing the development branch did not help either. I am on (Homebrew) Python2.7. 

Also, this issue wasn't there when I packaged the same program for Linux. I haven't tried on Windows, probably not going to. 

Here is the verbose output from the run: https://gist.github.com/keryil/573a85d40bb4ff197e0d3e973f43271d

**Comment by rrosenfeld-bway** [comment]
I'm pretty sure that the problem here is that within the cryptography hook it is using a pkg_resrouces.WorkingSet that is constructed before the target entry point's directory is added to sys.path.

It's using a WorkingSet constructed early on and the `entries` argument to `__init__` is omitted, so `sys.path` is used.   

PyInstaller appends `os.path.dirname(myscript.py)` (or equivalent) to sys.path, but apparently after this WorkingSet is constructed.   

By stepping through I can see that other hooks, like `hook-xml.py` instantiate their own WorkingSet which includes the amended sys.path.

**Comment by htgoebel** [comment]
Looks like you need to create a hook which runs `copy_metadata()`, see e.g. PyInstaller/hooks/hook-distutils.py. I'd appreciate a pull-request for the hook :-)

**Comment by Legorooj** [comment]
@conlin-matt yes there is:

* We can't fix this due to the fact that this isn't a bug in PyInstaller. If `pkg_resources` can't find `cryptography` (which works on windows btw) then we can't fix the problem with `pkg_resources`. Please take it up with https://github.com/pypa/setuptools.
