### ISSUE TITLE
Need code sign for my bundle on macOS?

### ISSUE THREAD

**Issue by orklann** [pyinstaller/pyinstaller#2564]
Hi, my simple python code just use PySide 1.2 and it runs fine after generated as an executable app bundle on macOS 10.12, but if i copy the app bundle to macOS 10.10, it give me this error:

```
Error loading Python lib '/var/folders/7v/4fnm9l2d0tq3_x0b_2ym4g0m0000gn/T/_MEI1aJBYO/Python': dlopen(/var/folders/7v/4fnm9l2d0tq3_x0b_2ym4g0m0000gn/T/_MEI1aJBYO/Python, 10): no suitable image found.  Did find:
	/var/folders/7v/4fnm9l2d0tq3_x0b_2ym4g0m0000gn/T/_MEI1aJBYO/Python: code signature invalid for '/var/folders/7v/4fnm9l2d0tq3_x0b_2ym4g0m0000gn/T/_MEI1aJBYO/Python'
```

Do i need to code signing my bundle in this case?

*Updated*:
BTW, I copied the app bundle to macOS 10.9, and it runs fine. but not work on macOS 10.10

**Comment by goldalworming** [comment]
I got this problem too,,
I compiled and works fine in sierra and not work in yosemite

**Comment by aaron-elkins** [comment]
@goldalworming I finally figured out why it did not work on Yosemite, it's because the code sign signature. After Yosemite, the code sign tool introduce SHA256, but Yosemite just support SHA1.

For more detail info, just check out this [post](http://stackoverflow.com/questions/41865537/how-does-apples-codesign-utility-decide-which-sha-algorithms-to-sign-a-shared).

**Comment by goldalworming** [comment]
@orklann how to implement this on pyinstalller? I have no idea how to use it in pyinstaller

**Comment by htgoebel** [comment]
This doe not seem to be a PyInstaller problem, isn't it?

**Comment by goldalworming** [comment]
@htgoebel maybe not pyinstaller problem but need solution or alternative

**Comment by htgoebel** [comment]
Maybe you can add several signatures to the binary? The .spec file is just a python script, so you can add whatever you need to sign the file there.

Closing this now, since it it is not y PyInstaller issue. Anyway, if you implement a solution useful for others, too, we could integrate it into PyInstaller. Just provide a pull-requests then.
