### ISSUE TITLE
Logos not found

### ISSUE THREAD

**Issue by giantas** [pyinstaller/pyinstaller#2621]
I would like to contribute to Pyinstaller GUI (seeing as not much development happens there). However, the links to the Pyinstaller [logos](http://www.pyinstaller.org/logos/pyinstaller-draft1a-35x35-trans.png)  do not work. I get 404 Not Found.

**Comment by xoviat** [comment]
In all honesty you're probably better off starting you're own project that simply calls PyInstaller with the command line arguments. I know that's probably not what @htgoebel  wants to hear, PyInstaller is already very complex, and it's beneficial to break complex projects into different components so that they're simpler to maintain. For example, the test suite shouldn't be run for changes to the GUI.

With respect to frameworks, there's the obvious: PyQt and wxPython (that's back), but there's a few other interesting projects that I've seen: ENAML (which has a fork that's under development) and toga. Pick you're poison there. Logos are in the [static dir](https://github.com/pyinstaller/pyinstaller/tree/develop/doc/_static).

**Comment by tallforasmurf** [comment]
Huh. I'd never heard of [ENAML](https://github.com/nucleic/enaml); and though I had seen the Beeware page before, never looked at [toga](https://pybee.org/project/projects/libraries/toga/). Both verrrry interesting! Thanks!

**Comment by giantas** [comment]
@xoviat your suggestion proves useful. I have worked with an application that does the same and I think it can be implemented for GUI. I am accustomed toTkinter since it ships with Python but Toga seems promising and I will have a look at it.

**Comment by giantas** [comment]
Apparently, the official website still has dead links to the logos.

**Comment by htgoebel** [comment]
This is fixed now.
