### ISSUE TITLE
Windows 7 created exe crashes Windows 10

### ISSUE THREAD

**Issue by wclarke77** [pyinstaller/pyinstaller#2628]
If you have problems to get your application running, please first

* try the latest development version, using the following command:

```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If you problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.

**Otherwise we will not be willed to help you.**

Please mind that PyInstaller is a voluntary project. We spent quite some time
for writing these guides to make both you and us lifes easier. Please
understand that we are not willed to spend our spare time to help you if you
are not willed to help on your side. (Sorry for having to said this, but we
are tired about asking the same question over and over again.)

I have done all of the above.  I even tried to use pyinstaller to build it on the Windows 10 machine, which  I will continue to attempt.  However, when trying to run the program I created in Windows 7 (64-bit) on a clean install of Windows 10, Windows 10 crashes and reboots, so I can't even see what the error might be.

I also attempted to run it in compatibility mode as Windows 7, still crashed the whole machine.

Any suggestions?

**Comment by htgoebel** [comment]
Please try with a simple "Hello World" program. If this passes, it's not related to PyInstaller.

Also follow the please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs. Otherwise we will not be willed to help you.

I'm closing this now, since I doubt, this is an PyInstaller issue. If you provide more detailed information, please reopen the ticket.
