### ISSUE TITLE
Python files included by `sys.path.insert()` are missing on the final executable

### ISSUE THREAD

**Issue by evandrocoan** [pyinstaller/pyinstaller#2640]
I have this lines on my code:
```python
import sys
sys.path.insert(0,'../python_debug')

import debug_tools
```
So, after compiling the executable `.exe` the program closed with missing module error:
```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from settings import *
  File "D:\User\Dropbox\Applications\SoftwareVersioning\ComputerScienceGraduation\ModelingAndSimulation\drunk_walk_simulation\settings.py", line 28, in <module>
    import debug_tools
ImportError: No module named debug_tools
```

Then I hard copied the files on `python_debug` with my project files changing the include directive to:
```python
import debug_tools
```

And it worked fine.

___ 

Related issues:

1. https://github.com/pyinstaller/pyinstaller/issues/2392 Load external pyz files support
1. https://github.com/pyinstaller/pyinstaller/issues/2261 need to load 1 *.pyd dynamically, ok MacOS and Linux, error on Windows
1. https://github.com/pyinstaller/pyinstaller/issues/1762 Source code within the 1-folder frozen application
1. https://github.com/pyinstaller/pyinstaller/issues/454 Frozen PIL does not support TIFF, TGA, etc
1. https://github.com/pyinstaller/pyinstaller/issues/188 sprintf(cmd, "sys.path.insert(0, '%s')", tmp) fails if string "tmp" contains a single quote character

**Comment by tallforasmurf** [comment]
If you review the warning messages from PyInstaller I feel sure you will see that it did not find a module `debug_tools` and so did not include it in the bundle. PyInstaller does not attempt to follow changes to `sys.path` -- there is no way it could do that.

You should review the manual [specifically this](http://pyinstaller.readthedocs.io/en/stable/usage.html#what-to-bundle-where-to-search) .

**Comment by evandrocoan** [comment]
Thanks.

**Comment by sonnt-0456** [comment]
If not hard copy, is there any other way?

**Comment by bwoodsend** [comment]
You can try using `--paths=../RepoCommon`. But you shouldn't mess with `sys.path` - it's very non-portable. You should [make `RepoCommon` a setuptool package](https://python-packaging.readthedocs.io/en/latest/index.html) which you can pip install locally.

**Comment by nguyenthaison** [comment]
@bwoodsend 
Your mean is i will make `RepoCommon` a setuptool package and import to main repository instead of use 
`sys.path.insert(0,'../RepoCommon')`
I would appreciate it if you explained it if I didn't get it right.

**Comment by bwoodsend** [comment]
Yeah that's right. That link explains it far better than I can so I'm not going to go into details but that's the correct way to deal with large projects with multiple folders of scripts - PyInstaller or no PyInstaller.

**Comment by nguyenthaison** [comment]
@bwoodsend Thank you. I'll try.

**Comment by sonnt-0456** [comment]
@bwoodsend 
I have another problem, i not found solution for this.
My code:
```
def example_function():
    cmd = "python myscript.py"
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE,shell = True, close_fds=True)
    p.stdout.close()
    return 
```
1. when in run pyinstaller, then i run file in executable. I got error "myscript.py".
    Can i encrypt the myscript.py file and the python command still work? Can you suggest to me solution for this?
2. Let's say I want to add libraries that are not imported in the script, is it possible?
    For example I want to import more libraries: Wand
Thank for support!

**Comment by bwoodsend** [comment]
There are several reasons why your `subprocess` thing won't work as is.

First you'll need to collect `myscript.py` as a data file so that it's copied in as-is. If it were treated as a source file then it would be packed into the EXE where `python` can't find it. On Unix: `--add-data=path/to/myscript.py:.`or on Windows: `--add-data=path/to/myscript.py;.`. 

Secondly, you're assuming the current working directory. `python myscript.py` means *run the file `myscript.py` from this working directory*. Your IDE will automatically set the current working directory to the location of your code so you don't realise that it is broken but if you open a terminal in a random folder then run `python path/to/your/code.py` it'll be unable to find `myscript.py`. Instead you should pin its location based on `__file__`. 
```python
import os
cmd = ["python", os.path.join(os.path.dirname(__file__), "myscript.py")]
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, close_fds=True)
```
Note, that I'm intentionally using list arguments to `subprocess` without `shell=True` because otherwise the command will break if there are spaces in the path to `mpyscript.py`.

Thirdly, and most importantly, by putting `python` in your subprocess command, you've now made the original Python in your `PATH` a dependency. i.e. It will run in the original unfrozen Python - not the one you've just compiled - and as a result, will break on any machine that doesn't have Python installed. Which leads me to ask, why do you want it running in a subprocess anyway? Why not just `import` it? Or if you want concurrency, use `multiprocessing` to do it properly?

> Let's say I want to add libraries that are not imported in the script, is it possible?
> For example I want to import more libraries: Wand

`--hiddenimport=Wand`

**Comment by sonnt-0456** [comment]
@bwoodsend Thank you for support. I will consider your suggestion.
