### ISSUE TITLE
Explanation - INFO: Rebuilding out00-EXE.toc because main.exe missing

### ISSUE THREAD

**Issue by ManPython** [pyinstaller/pyinstaller#2653]
There is always log in pyinstaller, eg; 
**INFO: Rebuilding out00-EXE.toc because main.exe missing** 
As we can find via google this line as log is global (if something is wrong, then we err in excess of similar but other informations - this made internet not usefull)
https://stackoverflow.com/questions/17611415/pyinstaller-stops-working-when-i-import-something-from-pyside
1. What this log/line exactly mind?
2. Why this happen?
3. Is this normal?
4. We need this in log? (Coz if answer is yes for pint 3. then this made some confusion and disonanse in all logs idea)
5. If normal, then I sugest to hide/delete this from print() 
6. In the warnings are lines (around 50 and more - probably nobady looking here when app working and is normaly executed without errors - and this is normal fact, but is this warning lines in warnapp.txt have any sense in this situation?) eg.
missing module named org - imported by copy
missing module named pwd - imported by posixpath, tarfile, shutil, http.server, webbrowser
..or other, that are not used (I think) and not included (following problem from point 2 in 
https://github.com/pyinstaller/pyinstaller/issues/2652 - Pyinstaller automatically includes unneeded modules )

**Comment by htgoebel** [comment]
For asking this kind of questions, the mailing-list is more appropriate, since one can quote much easier. Please ask there. Thanks,

**Comment by htgoebel** [comment]
This log-line is informing you that some intermediate file (EXE.toc) is actually build, because the desired target of this buid-step (main.exe) is missing. This is normal and we will not hide this message, because the log messages are the same for all build-steps. (And sharing the same code, so hiding this on message would lead to a lot of duplicate code.)

The warning lines in warnapp.txt are just this: Warnings. If your application has problems importing some module, this is a place to search if PyInstaller tried to find the module (and failed), or nor even tried it.
