### ISSUE TITLE
Call for new feature: UPX performing exclusion

### ISSUE THREAD

**Issue by bioinformatist** [pyinstaller/pyinstaller#2659]
I'm sure that UPX does destroy PyQt's `qwindows.dll` DLL file. For details, see [https://github.com/upx/upx/issues/107](https://github.com/upx/upx/issues/107).

To avoid this matter, I try exclude this DLL file when performing UPX compression, but I found that no parameter can do this. Can you add this function for us?

It will be always useful when something goes wrong with UPX. Thanks.

**Comment by htgoebel** [comment]
What exactly is the feature you are requesting?

**Comment by bioinformatist** [comment]
Just allow us to set exclusions containing directories or files without compression duiring calling upx.

**Comment by XCanG** [comment]
I have same suggestion as it broke `vcruntime140.dll` after compression when building execution by PyInstaller. If UPX can exclude this file from compression this will solve issue and I can build executable without corrupted file.

**Comment by XCanG** [comment]
This issue on PyInstaller repo: https://github.com/pyinstaller/pyinstaller/issues/1565

**Comment by bioinformatist** [comment]
@htgoebel Could you let we know when this feature can be added or even already come true in the dev-branch? :laughing:

**Comment by htgoebel** [comment]
How should PyInstaller know which file to exclude from UPX-compression?

**Comment by alanyang3** [comment]
Would it be possible for the spec file to specify what to exclude from UPX compression?

**Comment by ChadSki** [comment]
In the spec file, which currently might be configured like this:

```exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='foobar',
          debug=False,
          strip=False,
          upx=True,
          console=False )```

I would like to see the upx argument continue to accept a boolean (for backwards compatibility) but also accept an iterable of binaries to compress. For example:

```exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='darkapp',
          debug=False,
          strip=False,
          upx=filter(lambda x: x != 'qwindows.dll', a.binaries),
          console=False )```

False or an empty iterable means compress nothing.
True means compress everything (current behavior).
An iterable is the collection of binaries to be compressed.

**Comment by ChadSki** [comment]
Started digging around the code to see where that `upx` variable is referenced, here's the code locations I found:

https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/api.py#L351-L354
https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/api.py#L182

(Commenting more for my own reference than anything; might try fixing this myself eventually)

**Comment by carlosperate** [comment]
I'm encountering the same issue ("This application failed to start because it could not find or load the Qt platform plugin "windows".") but in my case I don't have UPX, and the flag is set to `False` in the spec file.

@bioinformatist @ChadSki Were you able to run your applications when UPX is turned off?

**Comment by htgoebel** [comment]
Please somebody provides a pull-request.

**Comment by ChadSki** [comment]
@carlosperate "Were you able to run your applications when UPX is turned off?"

Yes, but I encountered your issue first. Your app is missing `qwindows.dll`. See this [stackoverflow post](https://stackoverflow.com/questions/21268558/application-failed-to-start-because-it-could-not-find-or-load-the-qt-platform-pl/25266269#25266269).

**Comment by carlosperate** [comment]
I was using the latest commit from the develop branch (2 days ago). Does that mean PyQt5 needs its hook updated?

**Comment by carlosperate** [comment]
Btw, I was checking the expanded temporary directory of my app, and the `qwindows.dll` is definitely present in the `\PyQt5\Qt\plugins\platforms` directory, and I still get the `This application failed to start because it could not find or load the Qt platform plugin "windows".` message. I'll continue the conversation in https://github.com/pyinstaller/pyinstaller/issues/2857 as it's more related.

**Comment by necan** [comment]
until now, I've found these files are broken.
- MSVCP140.dll
- VCRUNTIME140.dll
- qwindows.dll
- qwindowsvistastyle.dll

**Comment by masoudr** [comment]
There is one fix to issue just copy all `plugins` dir from `site-packages\PyQt5\Qt\plugins` to `bincache01_py37_64bit\pyqt5\qt\plugins` this should fix the problem.
