### ISSUE TITLE
Pyinstaller for arm64 architecture

### ISSUE THREAD

**Issue by Bharath92** [pyinstaller/pyinstaller#2796]
Problem: I need pyinstaller to create a package on arm64 architecture.

Python version: 2.7.12
Python-pip version: 8.1.1

The following steps were taken to create pyinstaller to run on arm64 architecture:
- git clone https://github.com/pyinstaller/pyinstaller.git
- cd pyinstaller && git checkout v3.1
- cd bootloader && vi wscript
- comment out line [294-299](https://github.com/pyinstaller/pyinstaller/blob/v3.1/bootloader/wscript#L294-L299) (this is required because arm doesn't support -m64 flag for gcc)
- python ./waf distclean all --no-lsb
- cd .. && pip install -e .

Is there a better way to do this? Please let me know.

**Comment by xoviat** [comment]
The setup.py should automatically detect and compile bootloaders that are missing for the current architecture. However, it sounds like the wscript doesn't support arm architecture; that problem could be resolved with a PR.

**Comment by htgoebel** [comment]
I wonder why you need to uncomment out line 295. This is a check and  only add the flag ti `cc` if the compiler supports it. Please test the following:
* Does it suffice to uncomment line 296 and 297?
* Can you figure out how the can test the outcome of the check in line 295? I assume if this check fails, the flag should not be added to CFLAGS and LINKFLAGS, either.
* But we must only ignore the failur to set thsi flag for 64-bit systems whan using compilers on platforms we *know for sure* build 64-bit without these flags set. Any suggestions how to do this?

BTW: You should use the current development version /branch `develop` of PyInstaller for this. There have been *a lot* of changes since 3.1 you are using.

**Comment by Bharath92** [comment]
> But we must only ignore the failur to set thsi flag for 64-bit systems whan using compilers on platforms we know for sure build 64-bit without these flags set. Any suggestions how to do this?

The option list supported by gcc is [here](https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html). For x86 -m64 flag is supported, but not for Aarch64(arm64).

> Does it suffice to uncomment line 296 and 297?
> Can you figure out how the can test the outcome of the check in line 295? I assume if this check fails, the flag should not be added to CFLAGS and LINKFLAGS, either.

I am not sure whether we can get the output for `ctx.check_cc`. This returns true on the Aarch64(arm64) machine where the -m64 flag is not supported.

Interchanging use of arm64/aarch64 is because of [this](http://www.phoronix.com/scan.php?page=news_item&px=MTY5ODk)

So, the **fix** would be something similar to [this](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/wscript#L360-L363). But, I would also request to add a check for machine name begins with `aarch` [here](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/wscript#L80)

Also, I would like to know the test workflow for sending a PR for a bootloader change

**Comment by xoviat** [comment]
@Bharath92 Does #2801 address the issue? Can I close this?

**Comment by Bharath92** [comment]
Yes, this can be closed
