### ISSUE TITLE
Question about a migration tool arch

### ISSUE THREAD

**Issue by paulocoutinhox** [pyinstaller/pyinstaller#2840]
Hi,

I want migrate my tool "ezored" from Go to Python with pyinstaller, but i need ask somethings.
The reason is have a way to execute python scripts without user need download python.

My tool have some python scripts, so, i can execute this python scripts without download python, since it is embeded on pyinstaller package?

Example:
> ezored target-ios/build.py  

It will call: "[internal python binary] + target/build.py".

There is any way to do it?

Thanks.

**Comment by bwoodsend** [comment]
No, the entry-point script is embedded into the executable and there is no generic `python` entry-point. `compile()`, `exec()` and `runpy` will all work so roll your own but since those user scripts won't be going through PyInstaller's dependency analysis, anything those scripts import which weren't already imported by your entry-point will be unimportable. This is not a good solution - please don't do it.
