### ISSUE TITLE
Need to regard architecture, too

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2849]
PyInstaller needs to check the architecture when selecting the bootloader, not only the operation-system.

Currently PyInstaller ignores the architecture. This leads to problems when freezing an application on the same operation-system but a different architecture, e.g. Linux on aarch64. See #2848 for an example.

**Comment by amoh-godwin** [comment]
Wow I  super care about the architecture. I really think that the Anaconda distribution for python is architecture specific and so the pylib taken from there is respective of the architecture.

**Comment by bwoodsend** [comment]
This is implemented as part of 018fa3fe39cba357aaa636b75f1320a4c4ca3464 although given the pain we have matching architecture aliases reported by `waf` to those reported by `platform.system()`, I'm rather tempted to revert is. Since we now use separate per-platform wheels instead of an sdist containing all bootloaders and the non standard bootloaders are only built on release and are never checked into the repository, it doesn't matter that an `aarch64` bootloader has the same file path as an `x86_64` bootloader.
