### ISSUE TITLE
Build standalone python with wheels

### ISSUE THREAD

**Issue by gavrmike** [pyinstaller/pyinstaller#2960]
Hello!

I tried find answer on my questions, but had not found and decide to ask my questions here.

1. I would like to make something like ```pyinstaller -F `which python```` to get standalone python without any dependecies and use it run python interpreterator for a run python files or for running interactive shell or any other purposes. Is it possible to do with pyinstaller? How to do it?

2. Is it possible to say to pyinstaller add wheel or egg file as a package? For example: ```pyinstall -F ipython```, and use it to run interactive shell ```my_ipython``` or to run ipython notebook: ```my_ipython notebook```, without thinking about any ipython dependencies? Another example: adding packages like pyspark which store external jar files in another share dir. I know about option add data files to bundle, but it requires to rewrite some code in library. Is it possible to add wheel as a package?

**Comment by tenuki** [comment]
> 1. I would like to make something like ```pyinstaller -F `which python```` to get standalone python without any dependecies and use it run python interpreterator for a run python files or for running interactive shell or any other purposes. Is it possible to do with pyinstaller? How to do it?

`which python` isn't a python-code program hence it won't be accepted as input for pyinstaller.


> 2. Is it possible to say to pyinstaller add wheel or egg file as a package? For example: pyinstall -F ipython, and use it to run interactive shell my_ipython or to run ipython notebook: my_ipython notebook, without thinking about any ipython dependencies?

What do you mean as a package?  

Have you read pyinstaller's documentation? It does a pretty good job automatically detecting dependencies.

What you need is a python-program which behaves like python's interpreter, and yes, indeed you should be able to run ipython's or the standard interactive interpreter..

Perhaps something from these answers can be used with pyinstaller: https://stackoverflow.com/questions/1395913/how-to-drop-into-repl-read-eval-print-loop-from-python-code

Maybe instead of creating a ticket/issue, a better place to ask is in the irc channel or the mailing list, please check: https://github.com/pyinstaller/pyinstaller/wiki/Community .

**Comment by htgoebel** [comment]
Re 1: Completing tenuki's explanasion: This is not what PyInstaller is build for.

Re 2: Not this way round. PyInstaller is freezing an application (or script) and will collect all required packages. So you always need to "main" script. Of course you could re-implement Python's main interpreter. To add more packages, you can use e.g. `--hidden-imports`, but this might be cumbersome to really include *all* modules of a package. Using s spec-file for collection all modules might be easier then specifying all hidden-imports on the command line.

For everything else, I strongly suggest reading the manual, esp. the advanced part.

I'm closing this ticket, since we can not give you more voluntary support on this. If you want commercial support, please send me an email.
