### ISSUE TITLE
pyimod02_archive in generated executable is not deterministic

### ISSUE THREAD

**Issue by bauerj** [pyinstaller/pyinstaller#3000]
We're still trying to make Electrum builds deterministic. Currently, only the generated executable is different between builds.

Diffing the output of `pyi-archive_viewer -l -r` on the executables gave this result:

```diff
--- electrum-3.0.2-2-gff0cd16a-1.exe.contents        2017-11-14 19:22:59.194282658 +0100
+++ electrum-3.0.2-2-gff0cd16a-2.exe.contents        2017-11-14 19:23:04.810951982 +0100
@@ -564,8 +564,8 @@
  'zipfile': (0, 2992614, 21871)}
 [(0, 258, 332, 1, 'm', 'struct'),
  (258, 1169, 2017, 1, 'm', 'pyimod01_os_path'),
- (1427, 4410, 9972, 1, 'm', 'pyimod02_archive'),
- (5837, 7402, 19519, 1, 'm', 'pyimod03_importers'),
- (13239, 1934, 4558, 1, 's', 'pyiboot01_bootstrap'),
- (15173, 637, 983, 1, 's', 'pyi_rth_qt5'),
- (15810, 5830, 11402, 1, 's', 'electrum'),
+ (1427, 4411, 9972, 1, 'm', 'pyimod02_archive'),
+ (5838, 7402, 19519, 1, 'm', 'pyimod03_importers'),
+ (13240, 1934, 4558, 1, 's', 'pyiboot01_bootstrap'),
+ (15174, 637, 983, 1, 's', 'pyi_rth_qt5'),
+ (15811, 5830, 11402, 1, 's', 'electrum'),
...
```

Apparently, the entry named `pyimod02_archive` has a different compressed size. Extracting and comparing both versions showed that bytes 5-8 (the modification timestamp) are different in the .pyc-files.

I assume that file is from pyinstaller. Is it necessary to include the compiled version in the executable?

**Comment by htgoebel** [comment]
Thanks for the report. Curious this did not pop up when other demanded deterministic build :-)
> Is it necessary to include the compiled version in the executable?

This is not "necessary", but a feature we added on frequent demand.

Setting the time-stamp to zero should be easy to add [when code-objects are added to the PYZ](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/api.py#L129).
Just implement something like `PyInstaller.building.utils.strip_timestamp_in_code()` and run
`strip_timestamp_in_code(strip_paths_in_code(code))` at the linked place.

Please keep in mind that `strip_timestamp_in_code` needs to the version-aware since a change in file-format is planed for Python 3.7, see [PEP 552](https://www.python.org/dev/peps/pep-0552/).

**Comment by bauerj** [comment]
I tried to create a PR as described by you but apparently `self.code_dict` doesn't contain the entry for `pyimod02_archive`.

**Comment by htgoebel** [comment]
Oh, yes, sorry. These bootstrap modules are [handled differently[(https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/api.py#L97) :-( But `misc.compile_py_files()` is not the place to nullify the mtime, since this function is expected to create real .pyc files. These modules end up in [`srctoc`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/api.py#L268).

Maybe you need to bury stripping the mtime deep in [CArchiveWriter.add()](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/archive/writers.py#L374). I don't like such a functionality at such a deep layer, OTOH this is the central place. Maybe you find a better place?

**Comment by htgoebel** [comment]
Oh, we missed closing this when merging +3007
