### ISSUE TITLE
can't create .exe while using ibm_db module

### ISSUE THREAD

**Issue by filipposantovito** [pyinstaller/pyinstaller#3025]
Hi,

I'm writing this simple test script (doquery.py): 
```python

import ibm_db
print ibm_db.__version__

```
installing ibm_db is very easy:
`
pip install ibm_db
`

the script runs fine from the command prompt but it fails when running the .exe.
I create the .exe this way:
```

pyinstaller doquery.py
pyinstaller doquery.spec

```
the ibm_db module tries to load a .dll file at runtime using `imp.load_dynamic `from a folder named `ibm_db_dlls` (see site-packages\ibm_db.py) and it fails when bundled.
copying "ibm_db_dlls" inside the .exe folder doesn't help.

can you help me?

**Comment by htgoebel** [comment]
1) If ibm_db.py has hard-coded path, see "adopting to being frozen" in the manual.
2) Otehrwise see the "tracing" tips in [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

**Comment by filipposantovito** [comment]
thank you htgoebel for your support.
I tried your path but, unfortunately,  without success. It was too hard for me and I know too little about pyinstaller internals.
Deadline is too near and I have to solve *the problem*. And eventually I solved moving from ibm_db to pyodbc.
The problem is still open but I don't have the time to investigate right now. And I don't see another use of ibm_db in my near future.

thank you again for your time.

**Comment by liwancheng91** [comment]
I had met the same situation in Windows7 Python3.7 ibm-db 3.0.1  
maybe the reason is that exe can't find *.dll in clidriver\bin and ibm_db.dll, 
and solve it in two steps

**Frist:**
the same as you, add clidriver directory to system path
```
**\site-packages\clidriver\bin
```

**Second**
pack with argument --add-binary
```
 Pyinstaller --add-binary **\Lib\site-packages\ibm_db_dlls\ibm_db.dll;.\ibm_db_dlls myproject.py
```

Then it's OK！

**similar reference**
[PyQt5 Executable is crashing with Missing DLL](https://stackoverflow.com/questions/55625610/pyqt5-executable-is-crashing-with-missing-dll)
[ImportError: DLL load failed: The specified module could not be found — IBM DB2](https://stackoverflow.com/questions/55839589/importerror-dll-load-failed-the-specified-module-could-not-be-found-ibm-db2)
