### ISSUE TITLE
copy_metadata breaks requirement "extras" for packages installed as dist-info

### ISSUE THREAD

**Issue by ulope** [pyinstaller/pyinstaller#3033]
With #1888 a change was introduced that forcibly renames all distribution metadata directories created via `copy_metadata()` to have an `.egg-info` extension.

However [pkg_resources dispatches to different implementations based on the folder extension](https://github.com/pypa/setuptools/blob/89ef5bb7e4812193d6f593d531bad36191517981/pkg_resources/__init__.py#L2947).

One consequence of that is that required packages with required extras (i.e. something like `somepkg[someextra]` in `setup_requires`) cause exceptions during runtime since the  `.egg-info` distribution loader is unable to find the required extra in the the (originally) `.dist-info` metadata format.

Example of such an exception:
```
[...]
  File "raiden/utils/__init__.py", line 245, in get_system_spec
    raiden=pkg_resources.require(raiden.__name__)[0].version,
  File "site-packages/pkg_resources/__init__.py", line 981, in require
  File "site-packages/pkg_resources/__init__.py", line 875, in resolve
  File "site-packages/pkg_resources/__init__.py", line 2679, in requires
pkg_resources.UnknownExtra: tinyrpc 0.6 has no such extra feature 'websocket'
[72924] Failed to execute script raiden-script
```

**Comment by htgoebel** [comment]
Thanks for you bug report. Since we did it wrong in #1888, we urgently should have a test-case for this. Please provide a list of directories and file-names for this package as it is installed on your system and as it has to be in the frozen application. Thanks.

For the records: Offending line: https://github.com/bjones1/pyinstaller/commit/d0fa0a65b6d3d35b47d941fd2e2797a564991aea#diff-cd6283d71452a367a7ae53d21b41140bR1331

**Comment by mattspring** [comment]
Anyone have a workaround for this? I'm unable to add a hidden import of the form `package[extraname]` and unsure of how to build a hook to achieve what I need, plzhalp

**Comment by efiop** [comment]
@mattjreynolds Hi! Have you found a workaround for this by any chance? :slightly_smiling_face: We are running into the same issue.

**Comment by mattjreynolds** [comment]
@efiop No, sorry, I've not looked at this code in the last year, but from a quick glance back I think all I had to do for my use case was add a couple of hooks to handle the fact that the google package names don't match up properly.

**Comment by efiop** [comment]
@mattjreynolds Oops, it looks like I've accidentally linked you instead of @mattspring . I'm really sorry about that. Thanks for the tip though! :slightly_smiling_face:

**Comment by pared** [comment]
Hi @htgoebel.
We believe that we have similar issue to one described by @ulope.
In our build, we rely on google-resumable-media, which till version `0.3.2`
used `pkg_resources.require('requests >= 2.18.0')` to ensure that `requests` are
activated.

In version 0.3.3 they started to use `pkg_resources.require('google-resumable-media[requests]')`
to activate required package.

Now, upon building we get `pkg_resources.UnknownExtra: google-resumable-media 0.3.3 has no such extra feature 'requests'`.

We tried writing hook that would copy metadata of `requests` but it still fails to build.

Do you, by any chance now some workaround for this issue?

And if not, could you help us pinpoint some requirements that would need to be fulfilled
in order to create proper PR?

**Comment by mattspring** [comment]
@efiop I wasn't actually able to find a workaround for this issue. I ended up refactoring my package to not use the extras dependency since it wasn't deeply tied to my application -- that definitely won't be feasible for everyone. Sorry 🤷‍♂

**Comment by efiop** [comment]
@mattspring Thanks for the info! :slightly_smiling_face: As @pared noted, it is  a dependency of a dependency that is causing this issue for us, so it would be ideal to fix this in PyInstaller. I'm also happy to help in fixing this, @htgoebel it would be great if you could provide some directions.

**Comment by ulope** [comment]
Just FYI: we use [this hook](https://github.com/raiden-network/raiden/blob/2dc84ad06177fd73a5f561486f3b4bcf5322d648/tools/pyinstaller_hooks/hook-raiden.py#L11-L27) as a workaround

**Comment by htgoebel** [comment]
@ulope Would be creat i you could provide a pull-reqeust for a generic solution.
