### ISSUE TITLE
On Japanese system, temporary directories are created inside run directory and not cleaned up

### ISSUE THREAD

**Issue by LipillaiDave** [pyinstaller/pyinstaller#3042]
Hi!

PyInstaller 3.3.dev0+b78bfe5 (stable release)
Python 2.7.12 64-bit
Building Windows 10 English, running on Windows 10 Japanese

I'm sorry but I don't have a lot of access to the system that I noticed this issue. However, there are 4 PyInstaller-based .exe's run on it, all of which exhibit the issue. They are all compiled with --one-file and no console.

Please note that the path to the executable contains no Unicode, it is like c:\normal\no\spaces\whatever.exe despite being on Japanese system.

In the directory that the executable is run from, a sub-folder is created for each run that looks like this:

tmp80ztxb2
tmpb_xuwc
etc.

This is not cleaned up after execution.
The directory is empty except for one sub-folder, 'gen\_py.' In this sub-folder are two files: \_\_init\_\_.py and dicts.dat . \_\_init\_\_.py is just 3 lines:

```
# Generated file - this directory may be deleted to reset the COM cache...
import win32com
if __path__[:-1] != win32com.__gen_path__: __path__.append(win32com.__gen_path__)
```

I was not able to look at dicts.dat files because this is a customer system. If necessary I can try to get access.

I also noticed temporary files being generated in the launch directory, but they were quickly deleted, I think. I was remoting in through TeamViewer to a computer that remoted in through LogMeIn around the world, so there was some display latency, and I can't say for sure here.

I hope this has been helpful.

**Comment by htgoebel** [comment]
Did I understand correctly: The issue occur on the (Japanese) target system, when running the frozen script?!

The symptoms don't look like being caused by PyInstaller. Directories created by PyInstaller's bootloader are called `_MEIxxxxxx` and are created in the %TEMP%-folder (see https://pyinstaller.readthedocs.io/en/latest/operating-mode.html?#how-the-one-file-program-works). Also PyInstaller is not creating such files and PyInstaller's code does not contain the string "dicts.dat". So this looks like some component in your applications is creating these directories.

To verify this, send you customer a simple "Hello World" program.

This is all I can help you here. If you need more assistance, please send me an email and we'll arrange commercial support.
