### ISSUE TITLE
Distribute as wheel?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#3077]
There has been occasional request for distributing PyInstaller as wheel (but there seems to be not ticket for it yet). I just discovered https://pythonwheels.com/ includes a nice tutorial what to change.

Question: Should be distribute PyInstaller as wheel?

If so, to-do:
- [ ] Universal wheel? ([bdist_wheel] universal = 1)
- [ ] Add licence file ([metadata] license_file = LICENSE), but in which file?
- [ ] Platform-specific wheels? How to build them cross-platform? Remove bootloaders for other platforms?

**Comment by xoviat** [comment]
Actually this is not yet possible. We cannot use the universal option because we need to run build_bootloader on platforms that don't have a pre compiled bootloader.

For the platform specific wheels, it's much more difficult than you might think. We need a universal binary option, but that isn't it implemented. So this could consume more developer time than it's worth.

**Comment by htgoebel** [comment]
Thanks for clarifying.

**Comment by xoviat** [comment]
This might become possible once pypa/wheel#185 is fixed.
