### ISSUE TITLE
Reducing size of packaged executable

### ISSUE THREAD

**Issue by nootnoot12311a** [pyinstaller/pyinstaller#3111]
import collections
import csv
import selenium
import pandas

print('hi')

40mb+ for a single executable.

How can I reduce this as much as possible?

One method:

pyinstaller --onefile --exclude matplotlib --exclude scipy --exclude pandas --exclude numpy.py
This however is not practical considering how big the exclusion list would be.

How do I select a folder for pyinstaller to get modules from and exclude everything else so I may have a small application?  

Spec file:

```
a = Analysis(['31.py'],
             pathex=['C:\\Users\\AA\\ZZ'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='31',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
```

**Comment by htgoebel** [comment]
> How do I select a folder for pyinstaller to get modules from and exclude everything else so I may have a small application?

Use a virtual environment including on these packages which should go into your frozen app. But this might not help much, since "pandas is built on top of NumPy".

You may use the [Build-Time Dependency Graph](https://pyinstaller.readthedocs.io/en/latest/when-things-go-wrong.html#build-time-dependency-graph) to find the strategic modules pulling in these huge packages you do not need. Then you can exclude these few ones.
