### ISSUE TITLE
Py_Initialize: unable to load the file system codec LookupError: unknown encoding: utf-8

### ISSUE THREAD

**Issue by raintears** [pyinstaller/pyinstaller#3146]
Hi, I've been trying to resolve this but to no avail. I'm using python 3.6 and the development version of pyinstaller. All my modules are packaged inside but I can't start the .exe file at all with this encoding. I'm not using encoding anywhere so I don't know why this pops up? Please help thanks

These are the modules i'm using: os, asyncio, asyncpg, pandas

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by NulAsh** [comment]
Hi. I have the same error.
I'm using Windows 7 64-bit (6.1.7601) with russian language
Python version 3.6.3
I tried with both stable and devel versions of pyinstaller
The simplest program, which reproduce this behaviour is:
`print('Hello world!')`
That's right. I saved this file under the name test.py and then
`pyinstaller test.py --debug --log-level=DEBUG 2> err.txt`
You can see resulting err.txt here: https://gist.github.com/NulAsh/8c6fbf978a67561aa1a4bda2c36bb249
It create dirs "build" and "dist" and when i go to dist and run test.exe, here's the result:
```
[8436] PyInstaller Bootloader 3.x
[8436] LOADER: executable is E:\HACK\file2codegrp\testprog\dist\test\test.exe
[8436] LOADER: homepath is E:\HACK\file2codegrp\testprog\dist\test
[8436] LOADER: _MEIPASS2 is NULL
[8436] LOADER: archivename is E:\HACK\file2codegrp\testprog\dist\test\test.exe
[8436] LOADER: No need to extract files to run; setting extractionpath to homepath
[8436] LOADER: SetDllDirectory(E:\HACK\file2codegrp\testprog\dist\test)
[8436] LOADER: Already in the child - running user's code.
[8436] LOADER: Python library: E:\HACK\file2codegrp\testprog\dist\test\python36.dll
[8436] LOADER: Loaded functions from Python library.
[8436] LOADER: Manipulating environment (sys.path, sys.prefix)
[8436] LOADER: Pre-init sys.path is E:\HACK\file2codegrp\testprog\dist\test\base_library.zip;E:\HACK\file2codegrp\testprog\dist\test
[8436] LOADER: sys.prefix is E:\HACK\file2codegrp\testprog\dist\test
[8436] LOADER: Setting runtime options
[8436] LOADER: Initializing python
Fatal Python error: Py_Initialize: unable to load the file system codec
LookupError: unknown encoding: utf-8

Current thread 0x00003430 (most recent call first):
```
When I look into base_library.zip, in folder "encodings" there are only three files:
__init__.pyc aliases.pyc mbcs.pyc
I think, there should be more.
Included everything here - program and resulting files.
[testprog.zip](https://github.com/pyinstaller/pyinstaller/files/1592431/testprog.zip)

**Comment by EB-Plum** [comment]
same error here!

Windows 10 (2017 Dec updated) - Korean
python 3.6.4
pyinstaller 3.3.1

if I totally wiped-out python+pip and re-installed python, it works fine at that time.
this bug happens after installing several random packages.
but, i can not find exactly which package is causing this.(cause i'm noob)

Included code and file here.
on-building debug messages are in "out.txt" file.(too long)

[pyinstall_unknown_encoding.zip](https://github.com/pyinstaller/pyinstaller/files/1597451/pyinstall_unknown_encoding.zip)

this is program ouput with --debug option
>[7920] PyInstaller Bootloader 3.x
[7920] LOADER: executable is D:\Test\pyinstall\dist\test\test.exe
[7920] LOADER: homepath is D:\Test\pyinstall\dist\test
[7920] LOADER: _MEIPASS2 is NULL
[7920] LOADER: archivename is D:\Test\pyinstall\dist\test\test.exe
[7920] LOADER: No need to extract files to run; setting extractionpath to homepath
[7920] LOADER: SetDllDirectory(D:\Test\pyinstall\dist\test)
[7920] LOADER: Already in the child - running user's code.
[7920] LOADER: Python library: D:\Test\pyinstall\dist\test\python36.dll
[7920] LOADER: Loaded functions from Python library.
[7920] LOADER: Manipulating environment (sys.path, sys.prefix)
[7920] LOADER: Pre-init sys.path is D:\Test\pyinstall\dist\test\base_library.zip;D:\Test\pyinstall\dist\test
[7920] LOADER: sys.prefix is D:\Test\pyinstall\dist\test
[7920] LOADER: Setting runtime options
[7920] LOADER: Initializing python
Fatal Python error: Py_Initialize: unable to load the file system codec
LookupError: unknown encoding: utf-8
Current thread 0x00002244 (most recent call first):

it seems when this error happens, all other new-packaging tries end up same error.

**Comment by htgoebel** [comment]
@NulAsh Please have a look at the beginning of your log https://gist.github.com/NulAsh/8c6fbf978a67561aa1a4bda2c36bb249: There are error messages like these:
```
  File "c:\program files\python36\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
784 DEBUG: collect_submodules - Found submodules: {'encodings'}
```
Please verify you do not have another, incompatible module `enum` overwriting the one from the standard lib.

@EB-Plum Please post the log in some gist or some paste. For security reasons I'm not opening any archive. Thanks.

**Comment by EB-Plum** [comment]
oh sorry...

here is the test code
> \# -\*- coding: utf-8 -\*-
> import sys
> print('why?')

and here is the error log
[https://gist.github.com/EB-Plum/3102f684e44e130e48a63ea7748e47d3](url)

it seems i have the exactly same errors like @NulAsh 
some package must have overwritten enum module while installing.
i'll check them.

**Comment by EB-Plum** [comment]
found the problem.

"enum34" package.

Tensorflow has dependency on it.
but after pip uninstall enum34 - no errors, works fine.

now. problem is - how should i resolve this confict?

anyway thank you for answers

**Comment by htgoebel** [comment]
Thanks for tracking this down. I suggest opening a bug-report at tensorflow. Enum34 calls it itself "Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4", thus it should not be required by Python 3.6.
Some example like
```
import enum
enum.IntFlag
```
would suffice to show the error.

**Comment by petsuter** [comment]
Looks like tensorflow is aware of the problem https://github.com/tensorflow/tensorflow/pull/15042

**Comment by htgoebel** [comment]
Thanks for the info.

**Comment by stevenmdunn** [comment]
First - Sorry this is my first exposure to Python. running 3.6.2 on windows 7 enterprise.
Installed Pyinstaller and ran it to create a single directory environment and was getting the same error as the previous gentlemen. I uninstalled enum34 as suggested, reran the pyinstalleras follows

C:\dist\SoftPhoneV2>C:\WinPython-32bit-3.6.2.0Qt5\python-3.6.2\Scripts\pyinstall
er.exe -a -d --specpath=C:\PythonResources\spec C:\PythonResources\Scripts\Optus
\SoftPhoneV2.py
483 INFO: PyInstaller: 3.3.1
483 INFO: Python: 3.6.2
499 INFO: Platform: Windows-7-6.1.7601-SP1
499 INFO: wrote C:\PythonResources\spec\SoftPhoneV2.spec
499 INFO: UPX is not available.
499 INFO: Extending PYTHONPATH with paths
['C:\\PythonResources\\Scripts\\Optus', 'C:\\PythonResources\\spec']
499 INFO: checking Analysis
499 INFO: Building Analysis because out00-Analysis.toc is non existent
499 INFO: Initializing module dependency graph...
499 INFO: Initializing module graph hooks...
499 INFO: Analyzing base_library.zip ...
7971 INFO: running Analysis out00-Analysis.toc
7971 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by C:\WinPython-32bit-3.6.2.0Qt5\python-3.6.2\python.exe
8861 INFO: Caching module hooks...
8876 INFO: Analyzing C:\PythonResources\Scripts\Optus\SoftPhoneV2.py
8892 INFO: Loading module hooks...
8892 INFO: Loading module hook "hook-clr.py"...
8907 INFO: Loading module hook "hook-encodings.py"...
9001 INFO: Loading module hook "hook-pydoc.py"...
9001 INFO: Loading module hook "hook-xml.py"...
9391 INFO: Looking for ctypes DLLs
9407 INFO: Analyzing run-time hooks ...
9422 INFO: Looking for dynamic libraries
9609 INFO: Looking for eggs
9609 INFO: Using Python library C:\WinPython-32bit-3.6.2.0Qt5\python-3.6.2\pytho
n36.dll
9609 INFO: Found binding redirects:
[]
9609 INFO: Warnings written to C:\dist\SoftPhoneV2\build\SoftPhoneV2\warnSoftPho
neV2.txt
9688 INFO: Graph cross-reference written to C:\dist\SoftPhoneV2\build\SoftPhoneV
2\xref-SoftPhoneV2.html
9719 INFO: checking PYZ
9719 INFO: Building PYZ because out00-PYZ.toc is non existent
9719 INFO: Building PYZ (ZlibArchive) C:\dist\SoftPhoneV2\build\SoftPhoneV2\out0
0-PYZ.pyz
10439 INFO: Building PYZ (ZlibArchive) C:\dist\SoftPhoneV2\build\SoftPhoneV2\out
00-PYZ.pyz completed successfully.
10454 INFO: checking PKG
10454 INFO: Building PKG because out00-PKG.toc is non existent
10454 INFO: Building PKG (CArchive) out00-PKG.pkg
10486 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
10486 INFO: Bootloader C:\WinPython-32bit-3.6.2.0Qt5\python-3.6.2\lib\site-packa
ges\PyInstaller\bootloader\Windows-32bit\run_d.exe
10486 INFO: checking EXE
10486 INFO: Building EXE because out00-EXE.toc is non existent
10486 INFO: Building EXE from out00-EXE.toc
10486 INFO: Appending archive to EXE C:\dist\SoftPhoneV2\build\SoftPhoneV2\SoftP
honeV2.exe
10517 INFO: Building EXE from out00-EXE.toc completed successfully.
10517 INFO: checking COLLECT
10517 INFO: Building COLLECT because out00-COLLECT.toc is non existent
10517 INFO: Building COLLECT out00-COLLECT.toc
10986 INFO: Updating manifest in C:\Users\p1311516\AppData\Roaming\pyinstaller\b
incache00_py36_32bit\unicodedata.pyd
10986 INFO: Updating resource type 24 name 2 language 1033
11407 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

called my new program and still got 
C:\dist\SoftPhoneV2>SoftPhoneV2.exe C:\Testing\ANZ_CDRAUCORP_201801.zip C:\\Test
ing\\L2Zips c:\testing\ANZ_CDRAUCORP_201801.csv C:\\Testing\\ExpFiles
[8964] PyInstaller Bootloader 3.x
[8964] LOADER: executable is C:\dist\SoftPhoneV2\SoftPhoneV2.exe
[8964] LOADER: homepath is C:\dist\SoftPhoneV2
[8964] LOADER: _MEIPASS2 is NULL
[8964] LOADER: archivename is C:\dist\SoftPhoneV2\SoftPhoneV2.exe
[8964] LOADER: No need to extract files to run; setting extractionpath to homepa
th
[8964] LOADER: SetDllDirectory(C:\dist\SoftPhoneV2)
[8964] LOADER: Already in the child - running user's code.
[8964] LOADER: Python library: C:\dist\SoftPhoneV2\python36.dll
[8964] LOADER: Loaded functions from Python library.
[8964] LOADER: Manipulating environment (sys.path, sys.prefix)
[8964] LOADER: Pre-init sys.path is C:\dist\SoftPhoneV2\base_library.zip;C:\dist
\SoftPhoneV2
[8964] LOADER: sys.prefix is C:\dist\SoftPhoneV2
[8964] LOADER: Setting runtime options
[8964] LOADER: Initializing python
Fatal Python error: Py_Initialize: unable to load the file system codec
LookupError: unknown encoding: utf-8

Current thread 0x00002218 (most recent call first):

What have I screwed up please?

**Comment by htgoebel** [comment]
@stevenmdunn This should not happen. Please remove you build directory (just to be save) and run pyinstaller with `--clean`. Then run your .exe under contol of `NTstrace` (see [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)).

**Comment by dejandakovic12** [comment]
hi I have same problem on python3.7
![ero](https://user-images.githubusercontent.com/33150669/42399921-efe92bde-816f-11e8-8148-391ade23fff7.png)

**Comment by Zanstheskeleton** [comment]
im getting the error and i dont have enum34 installed
(python 3.7 windows 10 latest)

**Comment by htgoebel** [comment]
When using Python 3.7 you need to use the develop branch of at least 2018-07-10 and compile the bootloader yourself.

**Comment by mba1398** [comment]
Hi, i have the same error. Could you have a look? @htgoebel 

My demo is:
print('abc')

Use the cmd code:
`pyinstaller abc.py --debug --log-level=DEBUG 2> err1.txt`
I got this:
163 INFO: PyInstaller: 3.4
163 INFO: Python: 3.6.3
164 INFO: Platform: Windows-10-10.0.17134-SP0
171 INFO: wrote D:\pyinstaller\abc.spec
171 DEBUG: Testing for UPX ...
197 INFO: UPX is not available.
198 DEBUG: script: D:\pyinstaller\abc.py
198 INFO: Extending PYTHONPATH with paths
['D:\\pyinstaller', 'D:\\pyinstaller']
199 INFO: checking Analysis
276 INFO: checking PYZ
313 INFO: checking PKG
316 INFO: Bootloader c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run_d.exe
316 INFO: checking EXE
318 INFO: checking COLLECT
322 INFO: Building COLLECT COLLECT-00.toc
4123 INFO: Building COLLECT COLLECT-00.toc completed successfully.

My error when run abc.exe:
Fatal Python error: Py_Initialize: unable to load the file system codec
LookupError: unknown encoding: utf-8

Current thread 0x00002b3c (most recent call first):

I don't have enum34.

Tks for your help.

**Comment by QiPython** [comment]
> Hi, i have the same error. Could you have a look? @htgoebel
> 
> My demo is:
> print('abc')
> 
> Use the cmd code:
> `pyinstaller abc.py --debug --log-level=DEBUG 2> err1.txt`
> I got this:
> 163 INFO: PyInstaller: 3.4
> 163 INFO: Python: 3.6.3
> 164 INFO: Platform: Windows-10-10.0.17134-SP0
> 171 INFO: wrote D:\pyinstaller\abc.spec
> 171 DEBUG: Testing for UPX ...
> 197 INFO: UPX is not available.
> 198 DEBUG: script: D:\pyinstaller\abc.py
> 198 INFO: Extending PYTHONPATH with paths
> ['D:\pyinstaller', 'D:\pyinstaller']
> 199 INFO: checking Analysis
> 276 INFO: checking PYZ
> 313 INFO: checking PKG
> 316 INFO: Bootloader c:\users\administrator\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run_d.exe
> 316 INFO: checking EXE
> 318 INFO: checking COLLECT
> 322 INFO: Building COLLECT COLLECT-00.toc
> 4123 INFO: Building COLLECT COLLECT-00.toc completed successfully.
> 
> My error when run abc.exe:
> Fatal Python error: Py_Initialize: unable to load the file system codec
> LookupError: unknown encoding: utf-8
> 
> Current thread 0x00002b3c (most recent call first):
> 
> I don't have enum34.
> 
> Tks for your help.

I got the problem too. Have you fixed it?
