### ISSUE TITLE
PyInstaller 3.3.1 doesn't encrypt main file with --key option!!!

### ISSUE THREAD

**Issue by padremayi** [pyinstaller/pyinstaller#3160]
I can't believe that the main source code file from PyInstaller's .exe is not encrypted. My app starts from main.py, then this file import library1.py and library2.py.

Using --key and --onefile options PyInstaller encrypts all .pyc files except main.py!!! It is very easy to obtain the source code from .pyc.

This is unbelievable...

**Comment by htgoebel** [comment]
> This is unbelievable...

Indeed! How foolish are these developers, they should be paying for not implementing this properly. Or even better, be put in jail!

**Comment by ionic81** [comment]
Are you serious?! :-|

Here:
https://pyinstaller.readthedocs.io/en/latest/usage.html#encrypting-python-bytecode

there is this:
"To encrypt the Python bytecode modules stored in the bundle, pass the --key=key-string argument on the command line.

For this to work, you must have the PyCrypto module installed. The key-string is a string of 16 characters which is used to encrypt each file of Python byte-code before it is stored in the archive inside the executable file."

Do you understand the statement "each file"???

This is a bug, if you close the problem with your answer you are not a serious man.

The problem here is not that also with encryption it is possible to extract the key in order to obtain the source code, but that you close a bug in this way...

**Comment by htgoebel** [comment]
I closed this issue due to your tone/inflection:
> !!!
> This is unbelievable...
> you are not a serious man

If you want to submit a bug-report, do this properly, esp. providing details.

**Comment by ionic81** [comment]
I'm not the autor of the issue.

Did you close a bug like this for the tone?

**Comment by htgoebel** [comment]
@ionic81 Sorry, I apologize.

> Did you close a bug like this for the tone?

It's the tone and the report is of poor quality. Why should I spend my spare time on this?

**Comment by ionic81** [comment]
He wrote that in a Python application the main.py file is not encrypted, why is it a poor description?

By the way I did a test and this is true. The main file, so the "launcher", is inside the .exe without .pyc extension. It has the name of the .exe file. With few minutes you can easily obtain the source code.

This is a problem

**Comment by htgoebel** [comment]
Please see the "maintainer note" in https://github.com/pyinstaller/pyinstaller/issues/2365

**Comment by ionic81** [comment]
That is a different problem. Here the problem is not a bug on PyCrypto but in the logic of PyInstaller. The "launcher" of the application is not encrypted because this file is not on the pyz archive. This behaviour is wanted.

It is not a problem at all if you change the documentation and write there that the code inside the main file is not encrypted. In this way a developer won't insert a "critic" code in the launcher but only a little piece of code for launching the application ;-)

**Comment by htgoebel** [comment]
**If you want this to be fixed, please place an [adequate(!) bounty](https://www.bountysource.com/teams/pyinstaller) or submit a pull-request.** The requirement for byte-encryption is a commercial one (free software does not require byte-encryption since the cod is available anyway). So if you are earning money with using PyInstaller you should take parts of the development.

**Comment by ionic81** [comment]
Nice attitude. You bypassed my request to change documentation.

Not always a developer need code encryption for ear money...

I will do a lot of copy and paste of the link to this bug.

Bye all
