### ISSUE TITLE
'ImportError: No module named _sysconfigdata' when running executable in python2.7 (OSX)

### ISSUE THREAD

**Issue by lzkelley** [pyinstaller/pyinstaller#3198]
The `pyinstaller` build seems to run fine, but when I try to run my executable in python2.7 (works fine in 3.5) I get the error:

```
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/private/var/folders/lf/k8qk0rc567d04vhyk33kt_s80000gq/T/pip-build-jE6lt6/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "site-packages/pkg_resources/__init__.py", line 1040, in <module>
  File "site-packages/pkg_resources/__init__.py", line 1043, in Environment
  File "site-packages/pkg_resources/__init__.py", line 272, in get_supported_platform
  File "site-packages/pkg_resources/__init__.py", line 478, in get_build_platform
  File "sysconfig.py", line 618, in get_platform
  File "sysconfig.py", line 482, in get_config_vars
  File "sysconfig.py", line 365, in _init_posix
ImportError: No module named _sysconfigdata
[12962] Failed to execute script pyi_rth_pkgres
```

This might be related to  https://github.com/pyinstaller/pyinstaller/issues/3105, but even the v3.3.1 `pyinstaller` still causes the same issue.

conda 4.4.6
Python 2.7.14
pyinstaller 3.3.1
OSX 10.11.6

**Comment by xoviat** [comment]
The only question is this: is it worth the effort to fix the problem on Python 2.7 when its EOL is in two years?

**Comment by lzkelley** [comment]
@xoviat that doesn't seem like the only question at all.  As of a year ago there are [10x more py2 users than py3](http://www.randalolson.com/2016/09/03/python-2-7-still-reigns-supreme-in-pip-installs/).  It's also still the default on many systems.  People will keep using it long after "EOL"... so the relevant time scale is probably closer to 3-4 years.

Most importantly, and obviously, whether it's worth fixing depends most on *how hard it is to fix*.  Unfortunately I have no idea how to figure that out.

In my particular use case, I'm relying on a package which *only* builds in python2... hence my predicament.  I'm trying to remove dependency on that package now; we'll see how it goes. At least letting this issue sit to see if others are having the same problem would seem worthwhile.

**Comment by xoviat** [comment]
May I ask which particular package that is? If it is a public package then I can attempt to port it.

**Comment by htgoebel** [comment]
@xoviat Of course be need to fix Python 2.7 issues. It still was two years to EOL - and it is not a niche product.

**Comment by htgoebel** [comment]
@lzkelley Please check what `sysconfig._get_sysconfigdata_name()` returns on your system. It should be `_sysconfigdata`. which sould alos be listed in build/xxx/xref-xxx.html`.

**Comment by htgoebel** [comment]
@lzkelley No need for checking this :-) Looks like this is simply a bug in `hook-sysconfig.py`:
* `_sysconfigdata` ws introduced in https://github.com/python/cpython/commit/6cb4343d0d374a1b0ba01390ccef5b8868a5e9fc, which seems to be in Python 2.7already.
* [History of `hook-sysconfig.py`](https://github.com/pyinstaller/pyinstaller/commits/fc3ed7eb2968000d25bc8999c77472832e6fa376/PyInstaller/hooks/hook-sysconfig.py) leaves the impression, we never implemented support for `_sysconfigdata`.

A simple solution would be to just append this to the hook:
```
elif not is_win:
    # TODO remove this when dropping support for Python < 3.7
    hiddenimports = ['_sysconfigdata']
```

Please verify if this works for you and provide a pull-request.

I would heartily appreciate (as I'm extremely short in time ATM) if you could check the history of [Lib/sysconfig.py](https://github.com/python/cpython/blob/master/) on the all relevant branches (et least 2.7, 3.4, 3.5, 3.6 and master) and verify that `_sysconfigdata` was removed as soon as `_sys_sysconfigdata_name()` was introduced. If this is not the case, we need to tune the code above. Thanks.

For the pull-request, a small test-case would be wonderful. Just `print(sysconfig.get_build_platform()) in `tests/functional/test_libraries.py` (find a nice place near other module of the standard library or sort in alphabetically). Thanks!

**Comment by lzkelley** [comment]
@htgoebel  I'm still working on getting this to work.  I was trying to add the `hiddenimport` as a command-line argument before trying to add it to the hooks file, i.e.

`pyinstaller pyapi.py --distpath . -F --hiddenimport _sysconfigdata; rm -r build/; rm pyapi.spec`

In the virtualenv I use to run this command, the resulting executable works fine.  But when I try to run it from my normal anaconda environment, I now get the error:

```
daedalus:test-cosmo lzkelley$ ./src/pyapi
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
  File "/Users/lzkelley/Programs/electron/test-cosmo/src/test-env/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/pkg_resources/__init__.py", line 1043, in <module>
  File "site-packages/pkg_resources/__init__.py", line 1047, in Environment
  File "site-packages/pkg_resources/__init__.py", line 272, in get_supported_platform
  File "site-packages/pkg_resources/__init__.py", line 478, in get_build_platform
  File "sysconfig.py", line 688, in get_platform
  File "sysconfig.py", line 549, in get_config_vars
  File "sysconfig.py", line 420, in _init_posix
ImportError: No module named '_sysconfigdata_m_darwin_'
[13906] Failed to execute script pyi_rth_pkgres
```

which is, I think, the same error as the linked (older) issue: https://github.com/pyinstaller/pyinstaller/issues/3105

I'll keep playing around with this, but what I really don't understand right now is: I thought `pyinstaller` packaged everything required into the executable so that no environment resources were required.  Why is it then behaving differently in two different environments?

**Comment by htgoebel** [comment]
> I was trying to add the hiddenimport as a command-line argument before trying to add it to the hooks file

Good practice :-)

> ImportError: No module named '_sysconfigdata_m_darwin_'

Yes, this should be fixed in v3.3.1

> I thought pyinstaller packaged everything required into the executable so that no environment resources were required. Why is it then behaving differently in two different environments?

Most often this is since PyInstaller is not able to package *everything* required. so it can happen in one environment the executable finds some file by "pure luck". Often tracking this down requires running `strace` or so. But here we have the problem narrowed down quite well. Thus a test-programm like this would allow you to step throught the code and seen what are the differences:
```
import sysconfig
import pdb; pdb.set_trace()
sysconfig.get_config_vars()
```
HTH

**Comment by sushiterry** [comment]
I'm also having this issue running PyInstaller 3.3.1 on macOS 10.13.2.

Here's my test program:

`import sysconfig
import pdb; pdb.set_trace()
print(sysconfig.get_config_vars())`

I don't seem to get reasonable output from the compiled executable.

I'm using this command to compile:

`$ pyinstaller --onefile test_script.py
845 INFO: PyInstaller: 3.3.1
846 INFO: Python: 2.7.14
856 INFO: Platform: Darwin-17.3.0-x86_64-i386-64bit
857 INFO: wrote /Users/terrysimons/testinstall/test_script.spec
866 INFO: UPX is not available.
869 INFO: Extending PYTHONPATH with paths
['/Users/terrysimons/testinstall', '/Users/terrysimons/testinstall']
869 INFO: checking Analysis
869 INFO: Building Analysis because out00-Analysis.toc is non existent
870 INFO: Initializing module dependency graph...
878 INFO: Initializing module graph hooks...
1070 INFO: running Analysis out00-Analysis.toc
1079 INFO: Caching module hooks...
1084 INFO: Analyzing /Users/terrysimons/testinstall/test_script.py
3498 INFO: Processing pre-find module path hook   distutils
3620 INFO: Loading module hooks...
3620 INFO: Loading module hook "hook-distutils.py"...
3621 INFO: Loading module hook "hook-sysconfig.py"...
3623 INFO: Loading module hook "hook-encodings.py"...
4824 INFO: checking Tree
4825 INFO: Building Tree because out00-Tree.toc is non existent
4825 INFO: Building Tree out00-Tree.toc
4826 INFO: Looking for ctypes DLLs
4826 INFO: Analyzing run-time hooks ...
4835 INFO: Looking for dynamic libraries
4960 INFO: Looking for eggs
4960 INFO: Using Python library /Users/terrysimons/anaconda2/lib/libpython2.7.dylib
4962 INFO: Warnings written to /Users/terrysimons/testinstall/build/test_script/warntest_script.txt
4980 INFO: Graph cross-reference written to /Users/terrysimons/testinstall/build/test_script/xref-test_script.html
5066 INFO: checking PYZ
5067 INFO: Building PYZ because out00-PYZ.toc is non existent
5067 INFO: Building PYZ (ZlibArchive) /Users/terrysimons/testinstall/build/test_script/out00-PYZ.pyz
5488 INFO: Building PYZ (ZlibArchive) /Users/terrysimons/testinstall/build/test_script/out00-PYZ.pyz completed successfully.
5565 INFO: checking PKG
5565 INFO: Building PKG because out00-PKG.toc is non existent
5565 INFO: Building PKG (CArchive) out00-PKG.pkg
7613 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
7632 INFO: Bootloader /Users/terrysimons/anaconda2/lib/python2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
7633 INFO: checking EXE
7633 INFO: Building EXE because out00-EXE.toc is non existent
7633 INFO: Building EXE from out00-EXE.toc
7633 INFO: Appending archive to EXE /Users/terrysimons/testinstall/dist/test_script
7642 INFO: Fixing EXE for code signing /Users/terrysimons/testinstall/dist/test_script
7649 INFO: Building EXE from out00-EXE.toc completed successfully.
`

The first two lines seem to run ok - I drop into the debugger.

`import sysconfig
import pdb; pdb.set_trace()`

But when it reaches the print statement, it blows up:

`$ ./test_script 
> /Users/terrysimons/testinstall/dist/test_script.py(3)<module>()
(Pdb) c
Traceback (most recent call last):
  File "test_script.py", line 3, in <module>
  File "sysconfig.py", line 482, in get_config_vars
  File "sysconfig.py", line 365, in _init_posix
ImportError: No module named _sysconfigdata
[64231] Failed to execute script test_script`

If I try to execute the print statement, I get an error:

`$ ./test_script 
> /Users/terrysimons/testinstall/dist/test_script.py(3)<module>()
(Pdb) print(sysconfig.get_config_vars())
*** ImportError: No module named _sysconfigdata`

If I re-import sysconfig, and then issue the print again, I get output, but it's very minimal:

`(Pdb) import sysconfig
(Pdb) print(sysconfig.get_config_vars())
{'py_version_nodot': '27', 'exec_prefix': '/var/folders/v0/_k667rvx2bnbj8bfvshhh__m0000gp/T/_MEI02crKL', 'platbase': '/var/folders/v0/_k667rvx2bnbj8bfvshhh__m0000gp/T/_MEI02crKL', 'py_version_short': '2.7', 'prefix': '/var/folders/v0/_k667rvx2bnbj8bfvshhh__m0000gp/T/_MEI02crKL', 'base': '/var/folders/v0/_k667rvx2bnbj8bfvshhh__m0000gp/T/_MEI02crKL', 'projectbase': '/Users/terrysimons/testinstall/dist', 'py_version': '2.7.14'}
(Pdb)`

**Comment by sushiterry** [comment]
One other comment, @htgoebel I tried your above suggestion to check the return value of sysconfig._get_sysconfigdata_name():

$ python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Dec  4 2017, 15:36:09) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig._get_sysconfigdata_name()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '_get_sysconfigdata_name'

**Comment by sushiterry** [comment]
Forcing --hiddenimport _sysconfigdata seems to work for me for my test script.

**Comment by htgoebel** [comment]
@sushiterry Please debug why the hook does not pick up this module automatically and suggest a fix. Thus other can benefit from this issue being solved. Thanks :-)

**Comment by htgoebel** [comment]
@itszero Any new insights?

**Comment by sushiterry** [comment]
@htgoebel I'm not really sure how to debug this further.  Can you provide some suggestions?

I thought the problem was that "_get_sysconfigdata_name()" doesn't exist in the "sysconfig" module on OS X... is that not the issue?

**Comment by KDharmindar** [comment]
Is the issue resolved? or any clue? I am facing this same issue on Mac with Python 2.7 for wxPython based app.

**Comment by asarmohd** [comment]
Same issue with python 2.7.14 in 2019 :)

**Comment by Legorooj** [comment]
Python 2 is no longer supported.
