### ISSUE TITLE
about --windowed/--no console to package python

### ISSUE THREAD

**Issue by JianXin-Yun** [pyinstaller/pyinstaller#3326]
I write some GUI python file in python-tkinter,and when I use pyinstaller to package python script,always use`pyinstaller XX.py --windowed`,but python officially support XX.pyw to hide console(windowed),if run XX.pyw,it automatically hide console,so I wish pyinstaller support `pyinstaller XX.pyw`,which is equal to `pyinstaller XX.py --windowed`,and make pyinstaller easier to package PythonScript(such as tkintrer GUI,pygame game file)

**Comment by sewald00** [comment]
If you want the executable file to run without the console try "pyinstaller --noconsole XX.py"

**Comment by JianXin-Yun** [comment]
@htgoebel pyw is a python windowed file,officially supported

**Comment by tallforasmurf** [comment]
There is no dispute, it seems to be a feature of Cpython on Windows, documented in [appendix 16](https://docs.python.org/3/tutorial/appendix.html?highlight=pyw) of the manual. So what is needed is to modify PyInstaller so that if the script name on the command line ends in pyw it should force the —windowed option on. Already marked as “good first issue”, all that is needed is for someone to do the code and submit the pull request.

**Comment by zachbateman** [comment]
This issue can be closed.

**Comment by Legorooj** [comment]
This feature has been added.
