### ISSUE TITLE
relative paths for icon and version in spec file

### ISSUE THREAD

**Issue by 0800dennis** [pyinstaller/pyinstaller#3333]
I've tried to use relative paths for the Icon and the Version in the spec file.
What I tried is:

`exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='MyStuff',
          debug=False,
          strip=False,
          upx=True,
          console=False,
		  uac_admin=True,
		  icon='myicon.ico',
		  version='Version.txt')`

I also tried:
`icon='/myicon.ico',
 version='/Version.txt')`

I thought, that pyinstaller is searching for the files in same directory where my spec file is.
When I use absolute paths, everything is working fine.

So what am I doing wrong?

Thank you in advance!

**Comment by tallforasmurf** [comment]
Well definitely `icon='/myicon.ico'` will not work, as that is an absolute path. The [doc does say](http://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle) "(relative to the location of the spec file)" in respect to added data files. And in the spec file for an app I have where I use the `--icon=` parameter, the icon path in the spec file is also relative to the spec file location. 

A quick test shows me that if it cannot find the icon file (I used `--icon=arglebargle`) there is a WARNING message in the output. Look for that.

**Comment by maze-1** [comment]
I had the same problem. And for me it seems, that icon and version in the spec file does not support  relative paths. 
When you use something like `('../mydll.dll', 'resources'),` in the data section, PyInstaller is searching for the file in the folder path which is relative to the spec file.
But when you do `icon = '../blahup.ico',` in the exe section, it will not work.

What you can do is to insert `specpath = os.path.dirname(os.path.abspath(SPEC))` at the top of your spec-file. And then, in th exe section you can do `icon = os.path.join(specpath, 'blahup.ico')`.

For me, thi solution works very fine.

**Comment by 0800dennis** [comment]
Thanks maze-1, this solved my issue!

**Comment by tallforasmurf** [comment]
@htgoebel it looks to me as if this requires some change -- either to the code, or to the docs. No?

**Comment by htgoebel** [comment]
@tallforasmurf You right. I think the code should be fixed since this is the more "natural" behavior.

**Comment by tallforasmurf** [comment]
I am going to start work on this, with the aim of making sure that the handling of paths in

    --icon=FILE.xxx
    --version=FILE
    --manifest=FILE

are all treated the same as SRC in `--add-data=SRC:DST`, i.e. 

* an absolute path is used as-is
* a relative path is based on the spec file path

**Comment by tallforasmurf** [comment]
I cannot get this to fail on MacOS or on Windows 7. I will document my test here and ask @0800dennis to suggest other tests.

The folder structure is:

    ISSUE3333
        pyinstaller -- clone of current development version
        min.py -- see below
        inner
            min.ico
            min.icns
            data.txt -- contains a few characters
        dist

The test script min.py is,

~~~~
import os
import sys
if getattr(sys, 'frozen', False) :
    path_to_data = sys._MEIPASS
else :
    path_to_data = os.path.dirname(os.path.abspath(__file__))
try:
    f = open( os.path.join( path_to_data, 'data.txt' ) )
    s = f.read(-1)
    print( len(s), 'bytes read' )
    f.close()
except Exception as E:
    print('oops!', E)
    print('looking in', path_to_data)
~~~~

I tried various PyInstaller commands of this form:

    python pyinstaller/pyinstaller.py --clean -y -F -w --add-data=inner/data.txt:. --icon=inner/min.icns min.py

(of course `--icon=inner/min.ico` on windows). Varying the `-F` and `-D`, dropping the `-w` so I could see it print "16 bytes read".

The spec file then has, for example,

~~~~
a = Analysis(['min.py'],
             pathex=['c:\\Users\\Administrator\\Dropbox\\David\\SOFTWARE\\ISSUE3333'],
             binaries=[],
             datas=[('inner\\data.txt', '.')],
 ...etc
exe = EXE(pyz,
...
          console=True , icon='inner\\min.ico')
~~~~

and the icon is properly applied, and the file `data.txt` always ends up in the bundle directory.

If there is something else I can try to show a failure of relative paths, please comment, otherwise close this.

**Comment by htgoebel** [comment]
@tallforasmurf One difference I'm spotting: In the first comment there seems to be no path component for the icon file.

In PyInstaller.building.api.py::EXE.asemble(), icon version and resource are handled similar. It might be interesting checking os.getcwd() there.Basically this calls PyInstaller/utils/win32/icon.py::CopyIcon().

**Comment by tallforasmurf** [comment]
Yes I also did tests where it was just  `--add-data=data.txt:. --icon=min.icns` that is, alongside the spec file. I did not try a `../min.icns` yet.

I think I will wait for @0800dennis to comment.

**Comment by 0800dennis** [comment]
Hey guys, the original issue were reported to me by @maze-1. At the time, the issue was reported, he has no account on github and I just helped him out. But on the actual point, I’m out. For any detailed technical question, @maze-1 is the right person to ask. He will give you an answer in short time to the open question. Thanks!

**Comment by maze-1** [comment]
Hi guys, well, I made some tests with  the code of @tallforasmurf.

I'm on Windows 10 64bit, using Python 3.6.1 and PyInstaller 3.3.1 which was installed via pip.
My folder structure is:
* C:\Projekte\PyInstTest\
   min.py
   min.spec
   * inner
       min.ico
       data.txt

And my spec file is:

```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['min.py'],
             pathex=['C:\\Projekte\\PyInstTest'],
             binaries=[],
             datas=[('inner\\data.txt', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='min',
          debug=False,
          strip=False,
          upx=True,
          console=True,
          icon='inner\\min.ico')
```

In the console I do:
```C:\Python3\Scripts> pyinstaller.exe C:\Projekte\PyInstTest\min.spec```

And the last output is:
```FileNotFoundError: [Errno 2] No such file or directory: 'inner\\min.ico'```

Is there something wrong?

**Comment by tallforasmurf** [comment]
Working on icons first. (Data file, Version-file, Resource-File, Manifest-file all TODO).

The fix for OSX icons is easy; its icons are handled in [utils.osx.py](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/osx.py) and basically I just added this:

            if not os.path.isabs(self.icon):
                self.icon = os.path.join(CONF['specpath'], self.icon)

Windows icon is something else. The code is in [utils.win32.icon.py.CopyIcons()](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/win32/icon.py#L146) and it seems to me this code is grossly over-complicated, or I am missing something about the `--icon` parameter.

This code seems to assume that `srcpath` can sometimes be a list. So if it isn't a list, it makes it a list. But `srcpath` only ever comes from the `--icon` parameter value, and there can be only one of those.  (I tried it; if you pass two instances of `--icon`, the second replaces the first. Also, I tried `--icon=min1.ico;min2.ico` and you get that whole string as one item, and it eventually causes an error.) 

@htgoebel -- was there a time when you could give 2 or more `--icon` values and they would come as a list to CopyIcons?

Also, looking at the code from line 159ff, it again assumes `srcpath` can be a list, with possibly multiple instances of `foo.exe,1` but I can't see any way to create such a parameter list. Comments welcome from anyone.

**Comment by htgoebel** [comment]
The option `--icon` can be given only once, see PyInstaller/building/makespec.py.

**Comment by tallforasmurf** [comment]
Executive decision: not going to do anything to the [code for the](https://github.com/tallforasmurf/pyinstaller/blob/issue3333/PyInstaller/utils/win32/winmanifest.py#L1033) `--manifest=`*path* logic, it is way too complicated. If a relative *path* doesn't work here, use an absolute one.

**Comment by maze-1** [comment]
Thank you! I will test it tomorrow

**Comment by htgoebel** [comment]
#3444

**Comment by Legorooj** [comment]
#3444 fixed this
