### ISSUE TITLE
hook-pandas need more hidden imports

### ISSUE THREAD

**Issue by smcfadden** [pyinstaller/pyinstaller#3422]
pandas._libs.tslibs.nattype.pyd
pandas._libs.tslibs.np_datetime.pyd
pandas._libs.tslibs.timedeltas.pyd

Hi just created an exe that uses some pandas dataframe & functions. Error ,during execution, stating that the three modules above weren't imported. I re-ran pyinstaller as onedir and copied & renamed the original PYD files from pandas to those above. It works fine after.

**Comment by htgoebel** [comment]
Thanks for this report. 

*Can report which modules are importing the once you listed above.*

The reason is: We added a hook for pandas just a few days ago, implemented by @lneuhaus, which only adds  `pandas._libs.tslibs.timedeltas`. But you are listing more modules. Thus I assume it depends on which modules your project is using which Cython-modules needs to be added as hidden import.

You would help the project most if you'd analyze the pandas source, provide a full list of dependencies here, and submit a pull-request for some new hooks :-)

**Comment by htgoebel** [comment]
I forgot: Which version of pandas are you using?

**Comment by dutchminator** [comment]
I can second this request. My current workflow includes the following hiddenimports when using pandas in combination with pyinstaller:
['pandas._libs.tslibs.timedeltas', 'pandas._libs.tslibs.nattype', 'pandas._libs.tslibs.np_datetime', 'pandas._libs.skiplist']

**Comment by CapSOSkw** [comment]
hook-pandas.py
hiddenimports = ['pandas._libs.tslibs.timedeltas', 
                 'pandas._libs.tslibs.nattype', 
                 'pandas._libs.tslibs.np_datetime', 
                 'pandas._libs.skiplist']

More hidden imports should be added in hook file for pandas 0.23.

**Comment by chinguetti** [comment]
CapSOSkw,  I spent a whole day mucking around trying to fix this problem.  Your little post saved me.

**Comment by ryno68** [comment]
CapSOSkw's hook-pandas.py solved my issue with "AttributeError: type object 'pandas._libs.tslib._TSObject' has no attribute '__reduce_cython__' #2252" - thanks for the assist!

**Comment by Legorooj** [comment]
Stale
