### ISSUE TITLE
Using PyInstaller as a cross compiler

### ISSUE THREAD

**Issue by JSGandora** [pyinstaller/pyinstaller#3449]
Can I package Linux Binaries on OS X using PyInstaller? I know several other combinations are not possible as specified in the FAQ but I thought it was worth a try to ask. If not, is there some readily available solution?

**Comment by tallforasmurf** [comment]
No. Please take informational questions like this to the mailing list. Issues are for bug tracking.

**Comment by tallforasmurf** [comment]
I could also have said, there is a helpful hint in the doc about using Dropbox to develop for multiple platforms. https://pyinstaller.readthedocs.io/en/stable/usage.html#supporting-multiple-operating-systems

**Comment by htgoebel** [comment]
Dropbox? This US-based "give us all your data" company? How should this help to develop for multiple platforms?

**Comment by tallforasmurf** [comment]
I am sorry you don't like dropbox, the facility is very useful. I don't know of any alternative, in order to have an identical set of files available on multiple systems and platforms. How I use it: first, each of the 4 macs in our house has the same dropbox account, so a file created or modified in the shared folder structure by my wife on her laptop, shows up seconds later on my laptop or either desktop machine. "Put that in the dropbox for me!" is something we often say.

For PyInstaller purposes, on my "big" mac I run virtual machines for 32- and 64-bit Windows 7 and for 32- and 64-bit Ubuntu, and each VM has a dropbox client installed and connects to the same family dropbox account. So shortly after I boot a VM, it has an up to date copy of the shared folder structure.

One of those folders is the dev folder for a Python app. So running in Ubuntu, say, I can issue a PyInstaller build referencing the spec file, source modules, data etc. in the shared folder, with the `dist` path to another shared folder. Then I can start up an Ubuntu VM that does not have Python installed, and test the bundled app out of the shared dist folder. Then ditto with the Win7 VM, etc.

Is there another product that can do this, that you trust more than dropbox?

**Comment by htgoebel** [comment]
Now this is a multi-topic answer:
1. AFAIU you basically say "using some shared or synced folder eases cross-platform development". We could add this to the docs, even if I don't thnik this is necessary: A developer doing cross-platform should have this idea by him/herself. Anyway we should not name any commercial product or platform.

2. There are many alternatives to the one you are prompting (are you getting bonus-points for this, SCNR), e.g. Syncthing which does not even need a server, or Teamdrive which you an install on your own server. More alternatives are investigated at https://digitalcourage.de/digitale-selbstverteidigung/alternativen-zu-dropbox-und-cloud (German NGO). I'm using Unison.

**Comment by tallforasmurf** [comment]
See issue #3453. Feel free, or I'll try to get to it next week.
