### ISSUE TITLE
Stuck on `Analyzing /usr/local/bin/python3.6`

### ISSUE THREAD

**Issue by noplanman** [pyinstaller/pyinstaller#3512]
I'm trying to use pyinstaller to build a project on an arm32v5 machine using QEMU.

```
2646 INFO: Platform: Linux-4.9.87-linuxkit-aufs-armv7l-with-debian-8.10
```

Everything installs nicely, but when the build/compilation starts, the process gets stuck at:
```
60793 INFO: running Analysis out00-Analysis.toc
60796 DEBUG: Analyzing /usr/local/bin/python3.6
```

When trying it with an arm32v7 QEMU machine, I get a segmentation fault there and the build continues and completes successfully. Using arm64v8 everything works without an error at all.

Any ideas if I'm missing some component or something?
Have also tried with the develop version of pyinstaller, same problem.

**Comment by noplanman** [comment]
Has anybody had this issue in the past?
Or is there a way to disable the analysis that fails?

**Comment by htgoebel** [comment]
At this place (see PyInstaller/depend/bindepend.py) barely does nothing. A bit later (ASAIR) PyInstaller calls 'ldd' and other tool to analyze these binaries. Please add `import pdb ; pdb.set_trace()` at the corresponding place in PyInstaller/depend/bindepend.py and try to track this dowm.

I'm closing this now, since I quite confident, this is not a PyInstaller issue, but an issue by one of the external programs (or a Python issue :-)
