### ISSUE TITLE
Can't hide the App Icon in the Dock on OSX

### ISSUE THREAD

**Issue by justin2taylor** [pyinstaller/pyinstaller#3516]
While my Python app runs without an icon before compiling with PyInstaller, after exporting to a .app the icon keeps showing up in the dock.

In `main.py` I've set LSUIElement and LSBackgroundOnly to '1' through `AppKit.NSBundle.mainBundle().infoDictionary()`

I've tried the solution posted at https://github.com/pyinstaller/pyinstaller/issues/1917#issuecomment-249801912, but keep getting a python syntax errors. 

I've tried editing the `Info.plist` file to include either or both of these keys:
`<key>LSBackgroundOnly</key><string>1</string>` and `<key>NSUIElement</key><string>1</string>` but my app's icon is still showing up. 

Does anyone have a workaround for this? Thanks!

**Comment by tallforasmurf** [comment]
Did you try adding those plist keys using the technique described in [the manual](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#spec-file-options-for-a-mac-os-x-bundle)?

Also, at the link to #1917 all I see is a bunch of mods to PyInstaller code itself. If the above doesn't help, could you be more specific about what you tried and where the syntax errors occur? (PyInstaller code may have changed significantly since Feb. 2017)

**Comment by itsayellow** [comment]
[LSBackgroundOnly (Apple)](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-109268)
[About property lists (Apple)](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/PropertyLists/AboutPropertyLists/AboutPropertyLists.html)
LSBackgroundOnly is a Boolean, which means the value for it should be `<true/>` or `<false/>`.  You might try `<true/>` in your Info.plist instead of `<string>1</string>`.  You can do this by hand in your Info.plist, but not currently through the pyinstaller spec file.  

I'm not sure how permissive the parsing of items that are supposed to be Boolean is (i.e. whether `<string>1</string>` is supposed to work in some/all versions of macOS.)

**Comment by htgoebel** [comment]
I'm closing this for now, since given all the issues in the posters code, I don't see this being a PyInstaller issue.

**Comment by chunyang-wen** [comment]
FYI
```python
app = BUNDLE(
    coll,
    name='app.app',
    icon=None,
    bundle_identifier=None,
    info_plist={
        'LSUIElement': True,
        'LSBackgroundOnly': True,
        'NSUIElement': True
    },
)
```
