### ISSUE TITLE
Importerror: cannot import name ‘getlogger’

### ISSUE THREAD

**Issue by jyc511** [pyinstaller/pyinstaller#3539]
When i run pyinstaller from my project directory, i get the above error when pyinstaller tries to do an import from the log.py from the site-packages:
File “..\python36\lib\site-packages\Pyinstaller\log.py” 
from logging import getLogger
Importerror: cannot import name ‘getlogger’

I do not get the error when i run pyinstaller from its directory. What’s the step that i missed? I’ve included the installer directory in —paths but still getting this error. Any ideas?

**Comment by htgoebel** [comment]
If I understand correctly this happens when running PyInstaller. Thus I assume you have some other `logging` package installed in you environment. Please 
- check which pyinstaller you are actually running
- check which python interpreter this pyinstaller is actually using
- then try `python -c 'from logging import getLogger'` where `python` is the python actually used to run PyInstaller.

HTH
