### ISSUE TITLE
Exe created from pyinstaller one file option is picking dll from local path

### ISSUE THREAD

**Issue by madhukp** [pyinstaller/pyinstaller#3565]
My env version details - 
PyInstaller: 3.3.1
Python: 3.6.5
Platform: Windows-2012ServerR2-6.3.9600-SP0

The exe file created from pyinstaller works fine when i double click or run it from cmd. Issue is, my program uses urlmon.dll, when i place a dummy (or malicious) dll with same name as urlmon.dll in the dist folder where the exe resides, my exe file throws an error when i double click or run it from cmd that file - '<local path>/dist/urlmon.dll' failed to load. 

i tried including urlmon.dll while freezing the code by using --add-binary urlmon.dll;. option, this did bundle urlmon.dll into my exe and i can see it in the temp sys._MEIPASS folder when run. Can you please suggest how i can convince my exe file to search for dll eaither in 'c:\windows\system32' or in sys._MEIPASS and not in local path - path where exe resides? My securing testing team has reported this as a potential dll hijacking issue and blocked my code from release. I would any help that you can provide.

**Comment by htgoebel** [comment]
> i tried including urlmon.dll while freezing the code by using --add-binary urlmon.dll;. option, this did bundle urlmon.dll into my exe and i can see it in the temp sys._MEIPASS folder when run.

Yes, this is the intended used and the expected and documented behavior.

> Can you please suggest how i can convince my exe file to search for dll eaither in 'c:\windows\system32' or in sys._MEIPASS and not in local path - path where exe resides?

I would expect this to be the default case. `pyi_main.c` included this code:
```
        /* Add extraction folder to DLL search path */
        dllpath_w = pyi_win32_utils_from_utf8(NULL, extractionpath, 0);
        SetDllDirectory(dllpath_w);
```
According to the docs, this [adds `exractionpath` (sys._MEIPASS) to to the search path used to locate DLLs](https://msdn.microsoft.com/de-de/library/windows/desktop/ms686203(v=vs.85).aspx).

So I assume your application works and pulls in the correct  .dll.

> My securing testing team has reported this as a potential dll hijacking issue

What exactly did they report and what do they expect? Of course, *every* exe installed and requiring "private" dlls puts these into the same directory as the exe itself. Because AFAIK Windows inhibits loading dlls from other directories (and this is why PyInstaller calls `SetDllDirectory`). Which sollution they are suggesting?

If they are talking about the `dist` directory on your build-machine: Yes, an attacker would replace the dll here while you are building. But this is a risk inherent to all build-machines: If you want to bundle files an attacker can always insert a wrong DLL - or even a wrong PyInstaller bootloader, or Python program.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved. Otherwise please try PyInstaller v3.4 and the current development version.
