### ISSUE TITLE
Have some error use pyinstaller pack Caffe

### ISSUE THREAD

**Issue by Wangweilai1** [pyinstaller/pyinstaller#3611]
When I use pyinstaller pack pycaffe, it's always have some error, I already make sure the pycaffe is true ,because in my programe it 's very good working, but use pyinstaller pack caffe have some error as follow:

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    import caffe
  File "/tmp/pip-build-ykY1p0/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "caffe/__init__.py", line 1, in <module>
  File "/tmp/pip-build-ykY1p0/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "caffe/pycaffe.py", line 13, in <module>
  File "/tmp/pip-build-ykY1p0/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 687, in load_module
ImportError: /home/wwl/TestDemo/pyinstaller/dist/demo/caffe._caffe.so: undefined symbol: _ZN5caffe3NetIfEC1ERKSsNS_5PhaseEPKS1_
[126032] Failed to execute script demo

I'm looking forward to you help, Thanks.

**Comment by htgoebel** [comment]
I don't know what thie "pycaffee" thing is. Maybe _caffe.so tries to dyn-load some other library, but is not linked to that library. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing. Esp. look at the tipps about using `strace`.

**Comment by Wangweilai1** [comment]
![error](https://user-images.githubusercontent.com/15275988/42255646-4fbbea8a-7f7f-11e8-9ceb-69f94d4bb308.PNG)
when I add the library into path, use pyinstaller 3.3.1 version, it's happen those's error。it‘s seem like scipy package have error ,but when I use python IDE import scipy is no problem, so i guess when packing happen error?

**Comment by htgoebel** [comment]
Seems like you did not yet follow the whole [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) guide, since the very first point is "try the development version".

**Comment by Wangweilai1** [comment]
Follow this guide, I delete the publish version and use development version, when packing it's happen error,
but i found a surprised things,  modification https://github.com/BVLC/caffe/tree/master/python/caffe in io.py file 

`import skimage.io
from scipy.ndimage import zoom
from skimage.transform import resize`
comment those code ,the publish version 3.3.1 has working! can be import caffe, but it's doesn't work some caffe function, such as LoadModel function doesn't work.

**Comment by taosean** [comment]
@Wangweilai1 Hi, I had similar problems as you did. I was converting an caffe project to a standalone .exe file. However the `import caffe` code always throws some errors. I searched out on Google and find that it may have something to do with skimage, it seems pyinstaller doesn't have a good support for skimage. So I tried to replace the functions implemented by `skimage` (including read an image and resize it) in `caffe/io.py` with `cv2`. After that, it won't throw the errors. For more details, please refer to [this article](https://handong1587.github.io/programming_study/2016/12/24/pyinstaller-and-others.html#continue-tackling-weird-stuffs).

You mentioned that some caffe functions won't work after you comment the 3 import statements. I think maybe it's because it will be used in the following codes in caffe/io.py. If you comment them, the functions won't be found anymore.

**Comment by Wangweilai1** [comment]
@taosean Thanks very much, you are true. I have sovled this problem, But I fall into anther question,
that in my project need use C++ call python code, now I packed python as  executable file but it was so embarrassed that haven't  interface to C++, I want to use socket or pipeline to control python project, but I think it's a bad choose, Have you some good ideas for that?

**Comment by htgoebel** [comment]
> I have sovled this problem

Closing
