### ISSUE TITLE
OPENSSL_1.0.2 not found

### ISSUE THREAD

**Issue by YakDriver** [pyinstaller/pyinstaller#3616]
**THE GOAL**

To have one executable that runs on both CentOS/RHEL 6 _and_ 7.

**THE PROBLEM**

If I build on **CentOS 6,** using the exact same Python build configuration, with the _exact same_ `.spec` file, as below, the executable works fine on CentOS 6. However, when I try to run on CentOS 7, I get:
```shell
    import ssl
  File "/usr/lib64/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: ./_MEI7nzSc1/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by /usr/lib64/python2.7/lib-dynload/_ssl.so)
```

If I build on **Ubuntu 14.04,** using the exact same Python build configuration, with the _exact same_ `.spec` file, as above, the executable works fine on CentOS 7. However, when I try to run on CentOS 6, I get:
```shell
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./_MEIdpsfcZ/libz.so.1)
```

**WHAT I'VE TRIED**

1. Using the latest develop build and the regular build.
2. Searched through the `--onedir` directories produced on 6/Ubuntu looking for differences. They both include the same user files but have some differences in `.so` files (sizes and names), see below.
3. Building 100s of Docker containers adjusting Python and OS configurations trying to find options that work. Install Python in different places (`/usr/local/lib` and `/opt/python/3.6`) using different versions of Python.
4. Set, unset, reset the `LD_LIBRARY_PATH` environment variable.

**DIFFERENCES IN `--onedir`**

Looking just at SSL or crypto related differences, here is what I see.

- Ubuntu build: `libcrypto.so.1.0.0`; CentOS 6 build: `libcrypto.so.10`
- Ubuntu: none; CentOS 6: `libk5crypto.so.3`
- Ubuntu: `_ssl.so` (341.4 KB); CentOS 6: `_ssl.so` (301.0 KB)
- Ubuntu: `libssl.so.1.0.0` (378.2 KB); CentOS 6: `libssl.so.10` (433.0 KB)

Any help would be _greatly_ appreciated!

**Comment by htgoebel** [comment]
1) Re. "version `OPENSSL_1.0.2' not found (required by /usr/lib64/python2.7/lib-dynload/_ssl.so)": Obviously _ssl.so requires libcrypt/openssl 1.0.2, which is older and missing on your Centos 7 system. PyInstaller does not bundle libcrypt.

2) Re. "GLIBC_2.14' not found (required by ./_MEIdpsfcZ/libz.so.1)": Obviously the libz.so.1 on Centos 7 is (for what ever reason) linked against a newer version of libc not available on Centos 6. PyInstaller does not bundle libc.

Since openssl/libcrypt is updated much more frequently for security reasons then libz is, I suggest
- freeze your app on Centos 7
- make PyInstaller bundle a version of libz which is not linked against the newer libc. LD_LIBRARY_PATH is your friend. If this does not work, simply put such a libz on your system and add is as `binaries`. 

This is all I can help you for free. If you need more support, please consider [commercial support](http://www.pyinstaller.org/support.html#consulting-and-commercial-support).

**Comment by YakDriver** [comment]
You were right, of course. `LD_LIBRARY_PATH` was the key. However, I approached it by freezing on CentOS 6 and making sure that Salt Stack, which includes its own Python, was not being messed with by PyInstaller. The key was this [documentation](http://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations). Thanks for point me in the right direction! All is working.
