### ISSUE TITLE
zipimport.ZipImportError: can't find module 'encodings'

### ISSUE THREAD

**Issue by FuzzMonkee** [pyinstaller/pyinstaller#3642]
I am having issues with any compiled executable. I made a simple, one line test case 

print('the Executable works')

and I'm still having the same issue when I run the test.exe

"Fatal Python Error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x000006e4"

The current thread number changes each time I run it. 

I tried resetting the PYTHONPATH and PYTHONHOME environment variables, including the module in the spec file, adding the lib path to the spec file, reinstalling python, running the powershell as an admin, running the exe as an admin, etc.  I'm not sure why I'm having this issue. 

I'm "missing" several modules but they should be unncessesary (from warntest.txt file)

missing module named resource - imported by posix, C:\Python37\TEST\test.py
missing module named posix - imported by os, C:\Python37\TEST\test.py
missing module named org - imported by pickle, C:\Python37\TEST\test.py
missing module named readline - imported by cmd, code, pdb, C:\Python37\TEST\test.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\Python37\TEST\test.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\Python37\TEST\test.py
missing module named _winreg - imported by platform, C:\Python37\TEST\test.py
missing module named _scproxy - imported by urllib.request
missing module named 'java.lang' - imported by platform, C:\Python37\TEST\test.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, C:\Python37\TEST\test.py
missing module named termios - imported by tty, C:\Python37\TEST\test.py, getpass
missing module named grp - imported by shutil, tarfile, C:\Python37\TEST\test.py
missing module named pwd - imported by posixpath, shutil, tarfile, http.server, webbrowser, C:\Python37\TEST\test.py, netrc, getpass
excluded module named subprocess - imported by os, platform, pydoc, http.server, webbrowser, C:\Python37\TEST\test.py
missing module named 'org.python' - imported by copy, C:\Python37\TEST\test.py, xml.sax

Windows 10 x64, Python 3.7 x64 (also tried 3.6.6 x64), latest and greatest PyInstaller version.

**Comment by Baneeishaque** [comment]
**Use Python 2...**

**Comment by FuzzMonkee** [comment]
Tried with Python 2.17.15 x64. 
Same error message when running .exe. 

Before someone says it: Yes, I changed my PYTHONPATH and PYTHONHOME environment variables to reflect the change of versions.

**Comment by bmbowdish** [comment]
I am also having this exact issue

**Comment by melvyn2** [comment]
Strange... On macOS, 3.6.6 is working fine for me.

**Comment by bmbowdish** [comment]
It is on windows for me. Mac is working fine.

**Comment by bmbowdish** [comment]
C:\Users\bbowdish\Documents>pyinstaller --onefile hcpxfer.py
1248 INFO: PyInstaller: 3.3.1
1248 INFO: Python: 3.7.0
1264 INFO: Platform: Windows-10-10.0.17134-SP0
1264 INFO: wrote C:\Users\bbowdish\Documents\hcpxfer.spec
1280 INFO: UPX is not available.
1311 INFO: Extending PYTHONPATH with paths
['C:\\Users\\bbowdish\\Documents', 'C:\\Users\\bbowdish\\Documents']
1358 INFO: checking Analysis
1358 INFO: Building Analysis because out00-Analysis.toc is non existent
1358 INFO: Initializing module dependency graph...
1389 INFO: Initializing module graph hooks...
1405 INFO: Analyzing base_library.zip ...
19887 INFO: running Analysis out00-Analysis.toc
19918 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\bbowdish\documents\python\build\hcpxfer\python.exe
20465 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python.exe
20887 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python.exe
21340 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python.exe
21871 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python.exe
22449 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python.exe
23137 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
23527 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
24105 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
24527 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
25011 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
25558 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
26105 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
26574 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
26980 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
27199 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
27417 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
27667 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
27948 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\VCRUNTIME140.dll
28245 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\VCRUNTIME140.dll
28730 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\VCRUNTIME140.dll
29292 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\VCRUNTIME140.dll
29808 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\VCRUNTIME140.dll
29823 INFO: Caching module hooks...
29855 INFO: Analyzing C:\Users\bbowdish\Documents\hcpxfer.py
33135 INFO: Loading module hooks...
33135 INFO: Loading module hook "hook-dns.rdata.py"...
34901 INFO: Loading module hook "hook-encodings.py"...
35666 INFO: Loading module hook "hook-pydoc.py"...
35666 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
35682 INFO: Loading module hook "hook-xml.py"...
36916 INFO: Looking for ctypes DLLs
36963 INFO: Analyzing run-time hooks ...
37010 INFO: Looking for dynamic libraries
37526 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_ssl.pyd
37900 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_ssl.pyd
38369 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_ssl.pyd
38900 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\unicodedata.pyd
39353 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\unicodedata.pyd
39916 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\unicodedata.pyd
40478 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\pyexpat.pyd
41056 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\pyexpat.pyd
41634 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\pyexpat.pyd
42182 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\pyexpat.pyd
42712 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\pyexpat.pyd
43275 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_hashlib.pyd
43869 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_bz2.pyd
44447 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_bz2.pyd
45009 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_bz2.pyd
45572 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_bz2.pyd
46134 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_bz2.pyd
46743 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_lzma.pyd
47274 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_lzma.pyd
47931 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_socket.pyd
48462 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_socket.pyd
49071 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\select.pyd
49665 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_elementtree.pyd
50212 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_elementtree.pyd
50743 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_elementtree.pyd
51290 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_elementtree.pyd
51836 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_elementtree.pyd
52430 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\win32\win32wnet.pyd
53008 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\win32\win32wnet.pyd
53602 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\win32\win32wnet.pyd
54227 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_ctypes.pyd
54789 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_ctypes.pyd
55289 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_ctypes.pyd
55711 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_contextvars.pyd
56164 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_decimal.pyd
56711 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_decimal.pyd
57258 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_decimal.pyd
57820 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_decimal.pyd
58258 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_decimal.pyd
58492 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_decimal.pyd
58695 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\_decimal.pyd
59007 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libssl-1_1-x64.dll
59414 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libssl-1_1-x64.dll
59757 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libssl-1_1-x64.dll
60086 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libssl-1_1-x64.dll
64698 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
64981 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
65226 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
65476 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
65757 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
66007 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
66257 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
66538 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
66975 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\DLLs\libcrypto-1_1-x64.dll
67335 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\pywin32_system32\pywintypes37.dll
67600 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\pywin32_system32\pywintypes37.dll
67913 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\pywin32_system32\pywintypes37.dll
68147 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\pywin32_system32\pywintypes37.dll
68538 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\pywin32_system32\pywintypes37.dll
68538 INFO: Looking for eggs
68538 INFO: Using Python library c:\users\bbowdish\documents\python\build\hcpxfer\python37.dll
68538 INFO: Found binding redirects:
[]
68553 INFO: Warnings written to C:\Users\bbowdish\Documents\build\hcpxfer\warnhcpxfer.txt
68960 INFO: Graph cross-reference written to C:\Users\bbowdish\Documents\build\hcpxfer\xref-hcpxfer.html
69022 INFO: checking PYZ
69022 INFO: Building PYZ because out00-PYZ.toc is non existent
69022 INFO: Building PYZ (ZlibArchive) C:\Users\bbowdish\Documents\build\hcpxfer\out00-PYZ.pyz
71522 INFO: Building PYZ (ZlibArchive) C:\Users\bbowdish\Documents\build\hcpxfer\out00-PYZ.pyz completed successfully.
71600 INFO: checking PKG
71615 INFO: Building PKG because out00-PKG.toc is non existent
71615 INFO: Building PKG (CArchive) out00-PKG.pkg
79099 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
79115 INFO: Bootloader c:\users\bbowdish\documents\python\build\hcpxfer\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
79115 INFO: checking EXE
79115 INFO: Building EXE because out00-EXE.toc is non existent
79115 INFO: Building EXE from out00-EXE.toc
79115 INFO: Appending archive to EXE C:\Users\bbowdish\Documents\dist\hcpxfer.exe
79505 INFO: Building EXE from out00-EXE.toc completed successfully.

**Comment by bmbowdish** [comment]
C:\Users\bbowdish\Documents\dist>hcpxfer.exe
Fatal Python error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x000014c4 (most recent call first):

C:\Users\bbowdish\Documents\dist>

**Comment by bmbowdish** [comment]
I reverted to Python 3.6 and it worked! I guess there isn't support for 3.7?

**Comment by CKVB** [comment]
Yes even i have the same issue 

But wait a sec....
 
In Python 3.6.4 ; The program.exe file executed without any issues 
 Here's what i found in Python 3.6.4
[3.6.4.zip](https://github.com/pyinstaller/pyinstaller/files/2229496/3.6.4.zip)

But when i tried to execute the same program.exe through Python 3.7
Here's what i found 
[3.7.zip](https://github.com/pyinstaller/pyinstaller/files/2229512/3.7.zip)

According to me i think This happens because of Missing Files
This can be seen by comparing  each file 

So we can just hope for future updates 

In case if you really want to convert your programs into .exe files ; Then i recommend trying out Python 3.6.4 
 
Hope it help's......

**Comment by melvyn2** [comment]
Python 3.7 isn't supported yet. (As a side note, python 2 is deprecated).

**Comment by htgoebel** [comment]
For Python 3.7 you still need to build the bootloader first. See the manual.

**Comment by nautics889** [comment]
Have same issue bro

**Comment by earthbound19** [comment]
I think this issue is a duplicate. I saw another issue closed with the comment that 3.7 isn't supported yet.

**Comment by AndreasVenieris** [comment]
I had the same problem and I resolve it by replacing Python 3.7, to **Python 3.6.5** in my Windows 10 pro OS.
During compilation of `PyInstall` i am still getting these `WARNING: lib not found: api-ms-win-crtXXX...` warnings, but the final executable works fine w/o any error.

**Comment by htgoebel** [comment]
PyInstaller supports Python 3.7 Up to a few minutes ago you have had to build the bootloaders yourself, as already written e.g https://github.com/pyinstaller/pyinstaller/issues/3642#issuecomment-408619680. Bootloaders are now rebuild, so please use the current development head.

**Comment by Baneeishaque** [comment]
Problem solved with last development head, working in py 3.7 perfectly.

**Comment by itartpro** [comment]
![bezymyanny](https://user-images.githubusercontent.com/19771784/45263804-56f78e00-b439-11e8-85c1-e2f4f3602dd1.png)
Hello, I'm using python 3.7, after I compiled .exe file and try to run it, I see the following error, can someone tell me how I can start figuring this out?

**Comment by htgoebel** [comment]
@itartpro Use the latest development version!
