### ISSUE TITLE
Setting environment variables before the interpreter starts

### ISSUE THREAD

**Issue by BoboTiG** [pyinstaller/pyinstaller#3665]
This is more a question rather than an issue: can we set envars before the interpreter starts?

This is required to enable the [UTF-8 mode](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8) on Python 3.7. It will be useful too on Python 3.6 to enable UFT-8 in stdin/stdout/stderr using [PYTHONIOENCODING](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING).

Is it possible to do something like that in the `.spec`?
```python
envars = {
    "PYTHONIOENCODING": "utf-8",
    "PYTHONUTF8": "1",
}
exe = EXE(..., env=envars)
```

**Comment by tallforasmurf** [comment]
We do have a mailing list for this kind of question. To control Python that executes PyInstaller, obvs. set the envars before running PyInstaller. To set them at runtime, would need a change to the bootloader, plus some method of passing that information to the bootloader, the way the debug flag is passed.

**Comment by awa5114** [comment]
Is there a workaround for this until the functionality is added? The issue is that many libraries need to set environment variables before running (for instance `geopandas` sets a `PROJ_LIB` environment variable through the `conda` activate.d script. This environment variable is necessary for the library to function properly... and it needs to be available during runtime as far as I know...

**Comment by bjones1** [comment]
Can you set this environment variable in your `main.py` before your import `geopandas`? If not, you'll need to create a run-time hook.

**Comment by awa5114** [comment]
I guess I could copy the folder and its contents, then do `os.environ[PROJ_LIB] = directory`, but since I am delivering this executable to end users I'm not sure which directory to put... Wouldn't the `temp` directory be different for every machine?

**Comment by awa5114** [comment]
Run-time hook is probably the more elegant solution but I think it would be very time consuming to make one at this point... (I am highly unfamiliar with creating hooks)

**Comment by bjones1** [comment]
See https://pyinstaller.readthedocs.io/en/stable/runtime-information.html. So, probably `os.environ['PROJ_LIB'] = sys._MEIPASS`?

**Comment by awa5114** [comment]
I did this for now
````
if getattr(sys, 'frozen', False):
    os.environ['PROJ_LIB'] = os.path.join(os.path.split(__file__)[0], 'share')
else :
    pass
```

Thanks for pulling me out of the rabbit hole

**Comment by bjones1** [comment]
My pleasure. Would you consider making this a PR to the `geopandas` project? This would make the freeze process easier for anyone trying it.

**Comment by christianbioinf** [comment]
@bjones1 Unfortunately, run-time hooks only work for environment variable that are not used by the python interpreter itself, e.g., `PYTHONHASHSEED`. These can also be set by a run-time hook but do not change the behaviour of the python code, e.g., with respect to hash randomization. This can be seen when inspecting `sys.flags.hash_randomization` after setting `PYTHONHASHSEED='0'` in the runtime hook. In a non-freezed application the flag now returns 0 (False) but after freezing it still returns 1 (True).

I have now this issue since I want to freeze the third-party application [UMI-tools](https://github.com/CGATOxford/UMI-tools) and make it reproducible (i.e. same results with same input). However, since its code uses sets and the results depend somewhat on the order of elements in a set (see also CGATOxford/UMI-tools#349).

I was wondering whether there is anyone with a solution for it. I already tried to set the environment variable in the main script and then re-start the bootloader using `os.system` or `subprocess.call` but it did not work as well.

If it helps I can provide a step-by-step instruction with a minimal example that illustrates the issue. Just comment on this with the request. I can also open a new issue but since the title already exactly catched my description of the problem, I, for now, tried it as a comment.

Best regards,
Christian

**Comment by htgoebel** [comment]
@christianbioinf Simply answer: Currently one can only set the options are listed in https://pythonhosted.org/PyInstaller/spec-files.html#giving-run-time-python-options

If course this could be extended. It might be not so easy for Python <= 2.7, but starting with Python 2.8 it should be quite easy. Please submit a pull-request.

**Comment by christianbioinf** [comment]
@htgoebel Unfortunately, I have no idea how and where to add this inside the pyinstaller code. Could you give me some hints? Also, since there is no explicite option for the python interpreter for disabling hash randomization (`-R` only does the opposite), I guess I would have to set/overwrite the environment variable.
