### ISSUE TITLE
Is it possible to extract one-file mode package into RAM instead of tmpdir

### ISSUE THREAD

**Issue by mo-han** [pyinstaller/pyinstaller#3717]
As the title says.

**Comment by brightening-eyes** [comment]
hi,
it is possible, but first it requires a lot of changes, and second, what about data files?

**Comment by mo-han** [comment]
Hi @brightening-eyes ,
Seems like an expensive feature, huh?
I'm not meaning replacing tmpdir with ram, but adding an option for those who need such feature, and leave the choice to them.
Say I made a small tool for some daily use, packaging it with `pyinstaller` in one-file mode, and called it in a script, with some `while` or `for` loop, etc. Then this small package would be extracted into tmpdir very frequently, and write into tmpdir and delete those MEI folders a lot during those operations.
Though the one-folder mode can handle it well, one-file mode is neater.

**Comment by tallforasmurf** [comment]
Just playing with ideas here. Instead of saying, "unpack to RAM", maybe a better objective is simply, "want to be able to re-execute a one-file program from the temp disk without unpacking, if it already exists." (That's what you are asking for, wanting to run a one-file program multiple times quickly.)

It wouldn't be simple because of the way the boot process is designed. Somehow the first-pass bootloader (the part that executes from the .exe file) would figure out that an unpacked copy of its same program already exists, and go directly to using it. But several problems.

One, there would need to be a compile option (`--reuse`?) to tell the bootloader (a) not to erase the temp folder when execution ends normally, as it does now and (b) on startup, look for a remaining folder to use.

Two, there could be multiple MEIxxx folders in temp already, maybe from different programs, and maybe multiple copies from this program. On startup how to figure out that one of them is left by this program? What's unique about a folder full of stuff, that it could quickly say, "that's mine, I'll reuse that"? And be able to find that without wasting as much time as unpacking would take?

Three, it leaves a security hole. Nothing to stop someone with access to the machine, putting mal-code into the temp folder, which would then be executed next time. Anyway to prevent that?

**Comment by mo-han** [comment]
@tallforasmurf 
The 3rd problem you mentioned also exists for the current flow, since not ALL of the extracted files are used at the same time at the very first beginning. There is always enough time to do some bad things if someone wanted.
But I got your point, that we should stay simple. I agree, totally.
So I suppose I shall take one-folder mode instead.
