### ISSUE TITLE
win32com module not found with v3.4

### ISSUE THREAD

**Issue by gmyers18** [pyinstaller/pyinstaller#3733]
_Per @htgoebel I'm splitting this out from #3730 as a standalone issue._

Python: 3.6.4
PyInstaller: 3.4
OS: Windows 10

With PyInstaller v3.4 I see errors related to `win32com` when bundling:
```
9279 INFO: Loading module hook "hook-pkg_resources.py"...
9555 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
9614 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
```

This doesn't seem to impact the creation of the bundle, but this did not occur with v3.3.1.  I assume this is due to the transition from pywin32/pypiwin32 to pywin32-ctypes, but I don't understand the purpose of win32com well enough to fully comprehend the implications here.

**Comment by alexcwatt** [comment]
I can confirm the same issue running Python 3.6.4 and PyInstaller 3.4 on Windows 10.

**Comment by bjones1** [comment]
Would someone provide a short test script to reproduce this?

**Comment by genyez** [comment]
i reproduce it in py3.5.3-64bit win10 pyinstaller3.4

**Comment by genyez** [comment]
BTW, it is all right at 3.3.dev0+d29dc60f3.

**Comment by htgoebel** [comment]
@genyez Would be great if you could `git bisect` which commit introduced the issue.

**Comment by rockmosi** [comment]
I had the same error on win10, python 3.6, so I install pypiwin32.
Then The error is gone.

**Comment by Enteee** [comment]
I saw the same issue when building https://github.com/Enteee/DET after upgrading pyinstaller to 3.5 (run the `build.sh`-script). Adding `pypiwin32` to my `requirements.txt`, did make the error go away. Thank you @rockmosi.

**Comment by bjellesma-mastermans** [comment]
I see this issue in pyinstaller 3.6 running python 3.6 and installing pypiwin32 seemed to fix is as well

**Comment by Domin19901111** [comment]
I have this issue using python 2.7.17, pypiwin32==223 and pyinstaller versions 3.5/3.6.  Any solutions?

**Comment by dasdebashish17** [comment]
`Add pypiwin32==219 to pyinstaller-win requirements to fix `
Where can I find the file where the above mentioned fix is suggested ?

Thanks

**Comment by chris-t-w** [comment]
I'm still seeing this issue (or at least something similar) with Python 3.8.6 and pyinstaller 4.0. Installing `pypiwin32` as suggested above worked around the problem.

**Comment by rokm** [comment]
Thanks for letting us know @chris-t-w .

The error message itself is harmless, and is being triggered by [win32com pre-safe-import-module hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/2b9b5d13988131d18e78293954eee828c802d1cf/src/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py#L32) trying to query the module file attribute of the `win32com` module. The `get_module_file_attribute()` in turns tries to import the module in a separate process:

https://github.com/pyinstaller/pyinstaller/blob/59883973838a09c9a55eceb2c4ba466d90786bd4/PyInstaller/utils/hooks/__init__.py#L298-L306

But because the import statement is not covered by try/except block, the error message still ends up in the stderr of the main process.

So the proper fix would be to have the pre-safe-import-module hook check if the module is available before trying to query its attributes. On the other hand, the import statement in the `get_module_file_attribute()` could also be moved into the try/except block to reduce verbosity...
