### ISSUE TITLE
Docs for --debug is not what occurs

### ISSUE THREAD

**Issue by brentvollebregt** [pyinstaller/pyinstaller#3737]
Under the ["How to Generate"](https://pyinstaller.readthedocs.io/en/stable/usage.html#how-to-generate) header in the usage, debug arguments have been updated to reflect the new changes. First of all "–debug" needs to be "--debug" but the bigger issue is that you will be provided an error when passing -d/--debug on their own even though the usage states:

> all: All three of the below options; this is the default choice, unless one of the choices below is specified.

An example of this:
```
pyinstaller --debug my_script.py
```
this will produce the following error:
```
pyinstaller: error: argument -d/--debug: invalid choice: 'my_script.py' (choose from 'all', 'imports', 'bootloader', 'noarchive')
```
Passing one of {all,imports,bootloader,noarchive} solves this, for example:
```
pyinstaller --debug all my_script.py
```

I am using Windows 10, Python 3.6.6/3.7 and this is tested with PyInstaller-3.5.dev0+634a0c8ba/3.4.

**Comment by bjones1** [comment]
Good point. There are two problems I can see:

1. The formatting for the `--debug` option is incorrect. This is because docutils doesn't understand `argparse` results for this more complex scenario. We could use an automatic search and replace to fix this up before handing it to docutils/Sphinx. @htgoebel, what do you think -- I already see some fixup at https://github.com/pyinstaller/pyinstaller/blob/develop/doc/help2rst.py#L73. Adding to this would be (I think) fairly easy.
2. The docs are incorrect. I'll change the description of the `all` option to be: "all: All three of the below options." In addition,

**Comment by bjones1** [comment]
I went ahead and put this in #3739 -- @htgoebel, would you provide feedback there?
