### ISSUE TITLE
unable to find "C:\Users\user\nltk_data"

### ISSUE THREAD

**Issue by aswinroy** [pyinstaller/pyinstaller#3799]
Hi,
when i try to convert my python code to executable using pyinstaller, i get this error.
131444 INFO: Loading module hook "hook-nltk.py"...
Unable to find "C:\Users\user\nltk_data" when adding binary and data files.
This issue  persists even after downloading the nltk_data.
Tried creating this directory manualy, but then again the same error comes with a different drive instead of C.

**Comment by bogdanduminyuk** [comment]
I have the same issue. I had nltk_data, but in other directory. So I copied it in the user's directory and got the same error with non existing drive.

**Comment by htgoebel** [comment]
I assume the hook is adding directories it should not add. Also see https://github.com/pyinstaller/pyinstaller/pull/3705#issuecomment-421308502

Fixing this looks easy: In the hook there is aloop adding directories. In this loop, check if the directory exists prior to adding.

Please submit a pull-request, thnaks.

**Comment by macdja38** [comment]
3 Open PRs that seem to fix this issue exist, is something wrong with them?

https://github.com/pyinstaller/pyinstaller/pull/3900
https://github.com/pyinstaller/pyinstaller/pull/3897
https://github.com/pyinstaller/pyinstaller/pull/3872

**Comment by AndrasPataki** [comment]
Hello guys. I solved the problems editing the pyinstaller nltk-hook. After much research, I decided to go it alone in the code structure. I solved my problem by commenting on the lines:
`datas=[]`

`'''for p in nltk.data.path:
    datas.append((p, "nltk_data"))'''`

`hiddenimports = ["nltk.chunk.named_entity"]`

What's more, you need to rename the file: pyi_rth__nltk.cpython-36.pyc to pyi_rth_nltk.cpython-36.pyc . This file have 1 more underline. Warning with the python version.

**Comment by nedhulseman** [comment]
I have been working on this issue for a few days not and don't have hair left. For some reason nltk and pyinstaller do not work well together. So my first solution to this issue is to use something other than nltk if it is possible to code the solution without nltk. 

If you must use NLTK, I solved this by forcing the nltk_data path into datas.

1. Locate your nltk_data path. Mine was in 
C:\Users\user-name\AppData\Roaming\nltk_data

2. In hook-nltk.py (within pyinstaller directory) I commented out and added lines to look like this.
`import nltk
from PyInstaller.utils.hooks import collect_data_files

# add datas for nltk
datas = collect_data_files('nltk', False)

'''
# loop through the data directories and add them
for p in nltk.data.path:
    datas.append((p, "nltk_data"))
'''
datas.append(("C:\\Users\\nedhu\\AppData\\Roaming\\nltk_data", "nltk_data"))
           
# nltk.chunk.named_entity should be included
hiddenimports = ["nltk.chunk.named_entity"]
`

**Comment by flerlagekr** [comment]
Thanks @nedhulseman This did the trick!!

**Comment by tmilovanov** [comment]
https://github.com/pyinstaller/pyinstaller/pull/3900 fixes the issue and seems to be approved. It would be really helpful to merge it.

**Comment by dmcdonald8** [comment]
This problem still exists and is solved by #3900 which has been approved but not merged.

I would encourage using [the fix from that PR](https://github.com/pyinstaller/pyinstaller/pull/3900/files) as it doesn't rely on hard-coded directory paths.

You can find the file you need to edit at "/Lib/site-packages/PyInstaller/hooks/hook-nltk.py"

**Comment by Legorooj** [comment]
I've requested a review from people who can merge this. In the meantime, I'm going to close this issue.

**Comment by Legorooj** [comment]
@AdityaAnand1 #3900 has been merged. You'll see this fix in the next release - June hopefully

**Comment by ramith123** [comment]
A fix would be appreciated. Still getting the same issue

**Comment by Legorooj** [comment]
@ramith123 there is already a fix. We're just waiting on our project lead to actually release the next version. Feel free to use the development version in the meantime.

**Comment by ramith123** [comment]
@Legorooj Thank you! the development version worked!!
