### ISSUE TITLE
Pyinstaller multiprocessing name of process is always "MainProcess"

### ISSUE THREAD

**Issue by Indiana3714** [pyinstaller/pyinstaller#3957]
Here's my test code (py 2.7 on Windows):

```
import multiprocessing

print multiprocessing.current_process().name
print type(multiprocessing.current_process())
print type(multiprocessing.current_process().name)

def main():
    pass

if __name__ == "__main__":
    multiprocessing.freeze_support()
    p = multiprocessing.Process(target=main, name="My Child Process")
    p.start()
```

Without compiling, the code works fine as it prints out 
```
MainProcess
<class 'multiprocessing.process._MainProcess'>
<type 'str'>
My Child Process
<class 'multiprocessing.process._MainProcess'>
<type 'str'>
```

After using pyinstaller on it, unfortunately it will always default to "MainProcess". Result as follows:
```
MainProcess
<class 'multiprocessing.process._MainProcess'>
<type 'str'>
MainProcess
<class 'multiprocessing.process._MainProcess'>
<type 'str'>
```

**Comment by htgoebel** [comment]
Are you using `--onefile` mode? Please try `--onedir` mode.
This might ne an issue with the `freeze_support`. Please try Python 3.x

**Comment by htgoebel** [comment]
Please also state wich *exact* version of PyInstaller you are using. Please try the current development head.

**Comment by Indiana3714** [comment]
@htgoebel I'm using pyinstaller 3.4 on python 2.7. Using it in the regular mode with the folder? Not one single file.exe

**Comment by Indiana3714** [comment]
> Please also state wich _exact_ version of PyInstaller you are using. Please try the current development head.

3.5dev version still has the same issue

**Comment by htgoebel** [comment]
Please try putting `multiprocessing.freeze_support()` just after the ` import multiprocesseing`

**Comment by jordanjuras** [comment]
> Please try putting `multiprocessing.freeze_support()` just after the ` import multiprocesseing`

This fixed the described issue for me. 

Note: I had put `multiprocessing.freeze_support()` immediately following the main definition for this python script, but new windows/processes were kicked off one after the next.

**Comment by Indiana3714** [comment]
Issue still there when I'm using Python 3.7.4 now.

**Comment by olbermann** [comment]
I had very similar problems and was able to get rid of the AttributeError ... Failed to execute script...
by moving the target function to a different module and importing it into the script.

**Comment by Ratgor** [comment]
Python 3.5, PyInstaller 3.5
Same issue
Fixed by putting `multiprocessing.freeze_support()` before the first call of multiprocessing inside a function, not "immediately after" `import multiprocessing` (attribute error).

**Comment by migueldingli1997** [comment]
Any progress on this? I'm experiencing this on Mac OS.

**Comment by juanzt** [comment]
On MacOS Big Sur, fixed as htgoebel suggested:
```
import multiprocessing
multiprocessing.freeze_support()
```
It seems critical that `freeze_support()` is called immediately after the import.

**Comment by rokm** [comment]
Using `multiprocessing.freeze_support()` is not a work-around - it is [the proper way](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) of making `multiprocessing` work with frozen applications.

It allows PyInstaller to insert a hook that handles process spawning in the frozen application. This works differently than in unfrozen mode, because there's no `python(.exe)` executable involved, and so the frozen application's executable needs to handle being ran multiple times with different `multiprocessing`-specific arguments. The PyInstaller's hook effectively scans `sys.argv` for `multiprocessing`-specific arguments and if present, handles the further execution - so the code in those auxiliary and worker processes doesn't go beyond the `multiprocessing.freeze_support()` call. 

This is why omitting this call results in infinite process spawning loop; as each spawned auxiliary or worker process thinks it is main process, and executes main code, and therefore eventually tries to use `multiprocessing` again, which results in another set of auxiliary and worker processes being spawned...

And this is why you should make the call to `multiprocessing.freeze_support()` "as soon as possible":
- before you run any "main" code, such as command-line parsing (because you don't want to handle command line from auxiliary processes) or UI construction (because you don't want that in auxiliary and your worker processes)
- after any structures (classes, functions) that are used in your processes are defined (as calling it before will result in worker processes lacking those definitions, leading to error).
