### ISSUE TITLE
invalid add_data_or_binary value

### ISSUE THREAD

**Issue by Westlife1002** [pyinstaller/pyinstaller#3968]
I was trying to follow the manual to add the .jar file (it's in the same folder as the .py file):
pyinstaller --add-data netlogolink.jar PyNetlogo.py
Then, I got below error:
pyinstaller: error: argument --add-data: invalid add_data_or_binary value: 'netlogolink.jar'

**Comment by htgoebel** [comment]
Read the manual again.

**Comment by skamensky** [comment]
@Westlife1002 
The part of the manual @htgoebel is referring to is where you must specify a source and target directory.

> Additional non-binary files or folders to be added to the executable. The path separator is platform specific, os.pathsep (which is ; on Windows and : on most unix systems) is used. This option can be used multiple times.


e.g.
On windows can write
`pyinstaller main.py --add-data mappings.json;.`
And on unix systems you can write (`:` instead of `;`)
`pyinstaller main.py --add-data mappings.json:.`


See this [stackoverflow answer ](https://stackoverflow.com/a/44014560/4188138) for details.

**Comment by Igor1306** [comment]
@skamensky, thank you ! I was trying to use ';' on linux, and ':' helped.

**Comment by leogout** [comment]
`pyinstaller --add-data "app/assets/*.png;assets"` on windows, don't forget the quotes or you'll get weird errors.

**Comment by linenote-me** [comment]
@leogout , Your answer helped me. thanks

**Comment by toivocat** [comment]
@skamensky's worked for me.
