### ISSUE TITLE
Trojan:Win32/Ludicrouz.V

### ISSUE THREAD

**Issue by pwormer** [pyinstaller/pyinstaller#4059]
I prepared an .EXE by PyInstaller.  About a week later Windows 10 Defender warned me for the presence of Trojan:Win32/Ludicrouz.V in this .EXE. 

I run Windows 10 Home 1803. Latest PyInstaller  update:   altgraph-0.16.1 future-0.17.1 macholib-1.11 pefile-2018.8.8 pyinstaller-3.4 pywin32-ctypes-0.2.0

I have a strong suspicion that the warning is a false positive.  Anyone else had this and figured out what it means?

**Comment by Hacksawfred3232** [comment]
*face_palm*, Generally speaking, packers/freezers like PyInstaller gets labelled as Malware because some malware makers can use these kind of packers to create/obfuscate malware. Turns out, whoever wrote "Ludicrouz" programmed his little trojan in Python and then packaged it either using Cython or PyInstaller. Or it can just be completely programmed in C, and somehow the code looks very similar, IDK. Seeing that missing out 2 DLLs in a C++ program and forcing said program to look in the System32 folder causes it to be labelled as malware, this just shows that the malware makers are winning. To quote: "If its made by a human, it can be broken by a human."
Thankfully, You can just safely ignore the warning. As far as i know, Windows Defender has no "Generic" signature. So expect false positives like that.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
