### ISSUE TITLE
Problem with Python library with self compiled Python

### ISSUE THREAD

**Issue by johnlarfour** [pyinstaller/pyinstaller#4063]
I have compiled Python 3.7.2 with this command:
```
./configure --prefix=/home/john/Desktop/python3.7.2 --with-openssl=/home/john/Desktop/ --with-ensurepip=install --enable-shared
make
make install
```
So, now I have the compiled python in `/home/john/Desktop/python3.7.2` with shared library in `/home/john/Desktop/python3.7.2/lib/`

I do `python3 -m pip install pyinstaller`, `python3 -m PyInstaller --onefile main.py`
(Where the main file is a simple hello world)

But I get this error: `OSError: Python library not found: libpython3.7m.so.1.0, libpython3.7mu.so.1.0, libpython3.7.so.1.0` and say me to build python with `--enable-shared` flag that I have already done.

I'm wrong something?

**Comment by johnlarfour** [comment]
I have solved moving the ```libpython3.7m.so.1.0, libpython3.7mu.so.1.0, libpython3.7.so.1.0``` to `/usr/lib/`

I don't know if is the best solution

**Comment by htgoebel** [comment]
You want to compile with `--shared` as the error message - which you did not post - states. Thanks for wasting my time!

**Comment by johnlarfour** [comment]
@htgoebel sorry, I dont' want to waste your time, but the error message say that I need to compile with `--enable-shared` and not `--shared`. And it's what I did

**Comment by htgoebel** [comment]
Sorry, I missed this due to the long line (of course `--enable-shared` is correct). So sorry for being harsh.

Please verify you are actually using the python3 executable you' just build. `python3 ...` will search the $PATH. If this does not help please debug [`get_python_library_path()`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/depend/bindepend.py#L848).
