### ISSUE TITLE
I can't execute binary file normal

### ISSUE THREAD

**Issue by roseyangyu** [pyinstaller/pyinstaller#4242]
I can normally execute "./main.py".But I have run "pyinstaller main.py --distpath release -F --clean" to generate file "main". I have test add code "import os" "print (os)" in main.py. 
I run "./main.py",print "<module 'os' from '/usr/lib/python2.7/os.pyc'>"，run "./main" print "/tmp/_MEIXDJf4x/os.pyc".Why is that?

**Comment by cbenhagen** [comment]
This is the packaged os module. Is there anything not working?

**Comment by roseyangyu** [comment]
@cbenhagen Yes,I import other module.It doesn't normally work.I import pymavlink.When I run "./main"and mavlink-version1 it can normally work,but version2 can't.Then I run "./main.py",it's normal both version1 and version2

**Comment by cbenhagen** [comment]
* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If your problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for GitHub's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.


**Otherwise we will not be willing to help you.**

Please be aware that PyInstaller is a voluntary project. We spent quite some time
writing these guides to make both of our lives easier. Please
understand that we are not willing to spend our spare time to help you if you
are not willing to help on your side. (Sorry for having to said this, but we
are tired of being asked the same questions over and over again.)

**Comment by roseyangyu** [comment]
First,thank you for your reply very much.I have solved that question.The main problem is that file “main” runs in a random directory.I can't deal question accurately.I used order "pyi-makespec" instead of "pyinstaller" and the "main" is running in "dist/main" directory.So,I solved the question.Now,thanks you again.
