### ISSUE TITLE
--windowed flag not working for pyinstaller 3.3 + python3.6 on mac

### ISSUE THREAD

**Issue by vrnmthr** [pyinstaller/pyinstaller#4279]
OS: MacOS Mojave 10.14.5
Python: 3.6.5_1

I have a script

```
import time

time.sleep(5)
print("hello!")
```

that I am building with `pyinstaller --onefile --windowed hello.py`.

With pyinstaller 3.3 this still creates a console window, and with pyinstaller 3.4 it does not. We have just gotten everything packing properly using v3.3 and would like to keep using 3.3 if possible. Is there any way to get the --windowed option working/am I doing something wrong?

**Comment by bjones1** [comment]
Sorry, Python 3.3 isn't supported in current PyInstaller.

**Comment by htgoebel** [comment]
Been too fast in closing. It's Python 3.6 and PyInstaller 3.3 resp. 3.4.

> With pyinstaller 3.3 this still creates a console window, and with pyinstaller 3.4 it does not

Since you used `--windows`, it should not create a console window. This is exactly what this command line option intends. v3.4 does the right thing here.

If PyInstaller 3.3 works for you, and you don't mind the buffer-overflow vulnerabilities in that old version's bootloader, you can stay with it. But it has been superseded since long.

Also consider funding, to keep PyInstaller maintained.
