### ISSUE TITLE
Installing pyinstaller using msys32

### ISSUE THREAD

**Issue by HumamHelfawi** [pyinstaller/pyinstaller#4342]
Hi,
I am trying to install pyinstaller using msys32. I tried installing with pip and I tried to download the package and installing it manually by calling the setup.py file.  In both cases, I am getting this error:
```
 raise DistutilsPlatformError("VC %0.1f is not supported by this module" % VERSION)
  distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module
```

Thanks!

**Comment by danyeaw** [comment]
@HumamHelfawi Are you using the setuptools package provided by mingw32? If you `pip install setuptools` it won't work, because setuptools is patched downstream. See https://stackoverflow.com/questions/52166914/msys2-mingw64-pip-vc-6-0-is-not-supported-by-this-module

I don't think this is an issue with PyInstaller, PyInstaller pip installs fine for me with msys64.

**Comment by Legorooj** [comment]
Stale
