### ISSUE TITLE
Problems with QtWebEngineProcess on macos

### ISSUE THREAD

**Issue by paulocoutinhox** [pyinstaller/pyinstaller#4361]
Hi,

Im trying generate executable for UniqueBible project:
```
https://github.com/eliranwong/UniqueBible
```

But im getting error when execute the binary generated:

```
Could not find QtWebEngineProcess
Abort trap: 6
```

My command:
```
pyinstaller --name="TestApp" --onefile --windowed --noconsole MyTestApp.spec
```

MyTestApp.spec: 
```
# -*- mode: python -*-

import os

current_path = os.path.dirname(os.path.abspath(os.getcwd()))

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[        
        '/usr/local/lib/python3.7/site-packages/shiboken2',
        current_path,
    ],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TestApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    runtime_tmpdir=None,
    console=False
)

info_plist = {
    'NSHighResolutionCapable': True,
    'LSEnvironment': {
        'LANG': 'de_DE.UTF-8',
        'LC_CTYPE': 'de_DE.UTF-8'
    },
    'NSRequiresAquaSystemAppearance': False
}

app = BUNDLE(
    exe,
    name='TestApp.app',
    icon=None,
    bundle_identifier=None,
    info_plist=info_plist
)
```

**Comment by prsolucoes** [comment]
Build log:

```
pyinstaller --name="TestApp" --onefile --windowed --noconsole MyTestApp.spec
107 INFO: PyInstaller: 4.0.dev0+269779f91
107 INFO: Python: 3.7.4
114 INFO: Platform: Darwin-18.7.0-x86_64-i386-64bit
117 INFO: UPX is not available.
118 INFO: Extending PYTHONPATH with paths
['/Users/paulo/Developer/workspaces/python/UniqueBible',
 '/usr/local/lib/python3.7/site-packages/shiboken2',
 '/Users/paulo/Developer/workspaces/python']
118 INFO: checking Analysis
118 INFO: Building Analysis because Analysis-00.toc is non existent
119 INFO: Initializing module dependency graph...
123 INFO: Initializing module graph hooks...
124 INFO: Analyzing base_library.zip ...
3526 INFO: running Analysis Analysis-00.toc
3533 INFO: Caching module hooks...
3537 INFO: Analyzing main.py
3874 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
5745 INFO: Processing pre-safe import module hook   six.moves
7638 INFO: Loading module hooks...
7639 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
7912 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtWidgets.abi3.so)
7949 INFO: Loading module hook "hook-sqlite3.py"...
8008 INFO: Loading module hook "hook-PySide2.QtGui.py"...
8013 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtGui.abi3.so)
8026 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
8029 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtNetwork.abi3.so)
8046 INFO: Loading module hook "hook-cryptography.py"...
8268 INFO: Loading module hook "hook-encodings.py"...
8323 INFO: Loading module hook "hook-PySide2.QtCore.py"...
8328 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtCore.abi3.so)
8336 INFO: Loading module hook "hook-xml.dom.domreg.py"...
8337 INFO: Loading module hook "hook-PySide2.QtWebEngineWidgets.py"...
9799 INFO: Loading module hook "hook-PySide2.QtWebEngineWidgets.py"...
11204 INFO: Loading module hook "hook-certifi.py"...
11207 INFO: Loading module hook "hook-docx.py"...
11209 INFO: Loading module hook "hook-PySide2.QtPrintSupport.py"...
11212 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtPrintSupport.abi3.so)
11241 INFO: Loading module hook "hook-PySide2.py"...
11268 INFO: Loading module hook "hook-lxml.etree.py"...
11270 INFO: Loading module hook "hook-xml.py"...
11271 INFO: Loading module hook "hook-pydoc.py"...
11295 INFO: Looking for ctypes DLLs
11303 INFO: Analyzing run-time hooks ...
11307 INFO: Including run-time hook 'pyi_rth_pyside2.py'
11308 INFO: Including run-time hook 'pyi_rth_pyside2webengine.py'
11308 INFO: Including run-time hook 'pyi_rth_certifi.py'
11315 INFO: Looking for dynamic libraries
11427 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtTextToSpeech.abi3.so)
11429 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtNetwork.abi3.so)
11434 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtWebEngineWidgets.abi3.so)
11436 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtWebEngineCore.abi3.so)
11438 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtWebChannel.abi3.so)
11440 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtPrintSupport.abi3.so)
11442 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtGui.abi3.so)
11445 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtCore.abi3.so)
11457 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/QtWidgets.abi3.so)
11508 ERROR: Can not find path ./libshiboken2.abi3.5.13.dylib (needed by /Users/paulo/Library/Python/3.7/lib/python/site-packages/PySide2/libpyside2.abi3.5.13.dylib)
11631 INFO: Looking for eggs
11631 INFO: Using Python library /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/Python
11635 INFO: Warnings written to /Users/paulo/Developer/workspaces/python/UniqueBible/build/MyTestApp/warn-MyTestApp.txt
11678 INFO: Graph cross-reference written to /Users/paulo/Developer/workspaces/python/UniqueBible/build/MyTestApp/xref-MyTestApp.html
11700 INFO: checking PYZ
11700 INFO: Building PYZ because PYZ-00.toc is non existent
11700 INFO: Building PYZ (ZlibArchive) /Users/paulo/Developer/workspaces/python/UniqueBible/build/MyTestApp/PYZ-00.pyz
12346 INFO: Building PYZ (ZlibArchive) /Users/paulo/Developer/workspaces/python/UniqueBible/build/MyTestApp/PYZ-00.pyz completed successfully.
12358 INFO: checking PKG
12358 INFO: Building PKG because PKG-00.toc is non existent
12358 INFO: Building PKG (CArchive) PKG-00.pkg
37396 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
37411 INFO: Bootloader /usr/local/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
37411 INFO: checking EXE
37411 INFO: Building EXE because EXE-00.toc is non existent
37411 INFO: Building EXE from EXE-00.toc
37412 INFO: Appending archive to EXE /Users/paulo/Developer/workspaces/python/UniqueBible/dist/TestApp
37487 INFO: Fixing EXE for code signing /Users/paulo/Developer/workspaces/python/UniqueBible/dist/TestApp
37497 INFO: Building EXE from EXE-00.toc completed successfully.
37511 INFO: checking BUNDLE
37511 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
37511 INFO: Building BUNDLE BUNDLE-00.toc
37663 INFO: moving BUNDLE data files to Resource directory
```

**Comment by prsolucoes** [comment]
My installed dependencies and versions:

```
pip install pyside2 shiboken2 -U
Requirement already up-to-date: pyside2 in /Users/paulo/Library/Python/3.7/lib/python/site-packages (5.13.0)
Requirement already up-to-date: shiboken2 in /usr/local/lib/python3.7/site-packages (5.13.0)
```

**Comment by htgoebel** [comment]
The logs look more like an issue with shiboken2. Please eliminate these first. Then create and provide a *minimal* example to reproduce the error.

**Comment by prsolucoes** [comment]
I eliminated it, but copying:
```
cp /usr/local/lib/python3.7/site-packages/shiboken2/libshiboken2.abi3.5.13.dylib /usr/local/lib/python3.7/site-packages/PySide2/
```

Because they are trying to find libshiboken inside PySide2 folder.

But after the same command it generate an app that throw:

```
./TestApp
Could not find QtWebEngineProcess
Abort trap: 6
```

I made a sample here:
https://github.com/prsolucoes/pyinstaller-demo

Instructions and errors that i found are on repository (README).

**Comment by tangm** [comment]
I ran into the missing executable as well, it looks like the `pyside2` runtime hook and `pyside2.qtwebenginewidets` hook haven't been updated in step with updates to `pyqt5` support. I had some success using a custom hook and overriding some env vars in https://github.com/tangm/pyinstaller-pyside2webview-sample/

**Comment by BoboTiG** [comment]
So I tried to reproduce. With `--onedir`: OK.
But with `--onefile`: bad.

Here is the test file (`t.py`):
```python
import sys

def main():
    from PySide2.QtWidgets import QApplication
    from PySide2.QtCore import QUrl
    from PySide2.QtWebEngineWidgets import QWebEngineView

    url = 'https://github.com/pyinstaller/pyinstaller'
    app = QApplication(sys.argv)
    browser = QWebEngineView()
    browser.load(QUrl(url))
    browser.show()
    sys.exit(app.exec_())

main()
```

Frozen using:
```shell
python -m PyInstaller --noconfirm --clean --onefile t.py
```

Whand running it:
```shell
$ ./dist/t
Qt WebEngine ICU data not found at . Trying parent directory...
Qt WebEngine ICU data not found at /var/folders/b6/t8dzh1094157tl2364wnb1jh0000gn/T/_MEI2s5lov/PySide2/Qt. Trying application directory...
Qt WebEngine ICU data not found at /Users/tiger-222/projects/pyinstaller/pyinstaller-demo/dist. Trying fallback directory... The application MAY NOT work.
Path override failed for key base::DIR_QT_LIBRARY_DATA and path '/Users/tiger-222/.t'
Installed Qt WebEngine locales directory not found at location /qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /Users/tiger-222/projects/pyinstaller/pyinstaller-demo/dist/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Path override failed for key ui::DIR_LOCALES and path '/Users/tiger-222/.t'
[1021/183234.665658:ERROR:icu_util.cc(179)] Invalid file descriptor to ICU data received.
[1021/183234.665694:FATAL:content_main_delegate.cc(53)] Check failed: false. 
0   QtWebEngineCore                     0x000000011c8fc693 shape_detection::TextDetectionImplMac::Detect(SkBitmap const&, base::OnceCallback<void (std::__1::vector<mojo::StructPtr<shape_detection::mojom::TextDetectionResult>, std::__1::allocator<mojo::StructPtr<shape_detection::mojom::TextDetectionResult> > >)>) + 12385891
1   QtWebEngineCore                     0x000000011c91bd07 shape_detection::TextDetectionImplMac::Detect(SkBitmap const&, base::OnceCallback<void (std::__1::vector<mojo::StructPtr<shape_detection::mojom::TextDetectionResult>, std::__1::allocator<mojo::StructPtr<shape_detection::mojom::TextDetectionResult> > >)>) + 12514519
2   QtWebEngineCore                     0x000000011c8806d6 shape_detection::TextDetectionImplMac::Detect(SkBitmap const&, base::OnceCallback<void (std::__1::vector<mojo::StructPtr<shape_detection::mojom::TextDetectionResult>, std::__1::allocator<mojo::StructPtr<shape_detection::mojom::TextDetectionResult> > >)>) + 11878054
3   QtWebEngineCore                     0x000000011c881b23 shape_detection::TextDetectionImplMac::Detect(SkBitmap const&, base::OnceCallback<void (std::__1::vector<mojo::StructPtr<shape_detection::mojom::TextDetectionResult>, std::__1::allocator<mojo::StructPtr<shape_detection::mojom::TextDetectionResult> > >)>) + 11883251
4   QtWebEngineCore                     0x000000011ae7acc2 QtWebEngineCore::WebContentsAdapter::canViewSource() + 36738
5   QtWebEngineCore                     0x000000011ae797a5 QtWebEngineCore::WebContentsAdapter::canViewSource() + 31333
6   QtWebEngineCore                     0x000000011ae6c1e1 QtWebEngineCore::WebContentsAdapter::WebContentsAdapter(content::WebContents*) + 49
7   QtWebEngineWidgets                  0x000000011957a4df operator>>(QDataStream&, QWebEngineHistory&) + 1295
8   QtWebEngineWidgets                  0x000000011957cc10 QWebEnginePage::QWebEnginePage(QObject*) + 48
9   QtWebEngineWidgets                  0x000000011958b077 QWebEngineView::load(QUrl const&) + 55
10  QtWebEngineWidgets.abi3.so          0x000000011952f0ca Sbk_QWebEngineViewFunc_load(_object*, _object*) + 362
11  libpython3.8.dylib                  0x000000010e10d816 cfunction_vectorcall_O + 214
12  libpython3.8.dylib                  0x000000010e1aec52 call_function + 354
13  libpython3.8.dylib                  0x000000010e1ab326 _PyEval_EvalFrameDefault + 29782
14  libpython3.8.dylib                  0x000000010e0cf2fd function_code_fastcall + 237
15  libpython3.8.dylib                  0x000000010e1aec52 call_function + 354
16  libpython3.8.dylib                  0x000000010e1ab3da _PyEval_EvalFrameDefault + 29962
17  libpython3.8.dylib                  0x000000010e1afcd7 _PyEval_EvalCodeWithName + 3287
18  libpython3.8.dylib                  0x000000010e1a3e30 PyEval_EvalCode + 48
19  t                                   0x0000000104ec554e t + 9550
20  t                                   0x0000000104ec59d7 t + 10711
21  t                                   0x0000000104ec4154 t + 4436
```

**Comment by rokm** [comment]
Yeah, `onefile` builds are broken for both `PySide2` and `PyQt5+PyQtWebEngine` and judging by the comments in our tests, this has been a case for a while.

The crash is due to `icudtl.dat` (and afterwards `qtwebengine_resources.pak`) not being found in the search locations.

You can see the three attempts to find `icudtl.dat` in your log (I'm taking it from mine for comparison with onedir below):
```
...
Qt WebEngine ICU data not found at . Trying parent directory...
Qt WebEngine ICU data not found at /var/folders/rd/v4qf4xpj3slf6nvnrp0gb1xh0000gn/T/_MEIw3Hb7m/PySide2/Qt. Trying application directory...
Qt WebEngine ICU data not found at /Users/rok/Development/pyi-webengine/dist. Trying fallback directory... The application MAY NOT work.
...
```

The program actually ships two copies of `icudtl.dat`, but neither is in the locations being checked:
```
$ find /var/folders/rd/v4qf4xpj3slf6nvnrp0gb1xh0000gn/T/_MEIw3Hb7m -name "*icu*"
/var/folders/rd/v4qf4xpj3slf6nvnrp0gb1xh0000gn/T/_MEIw3Hb7m/PySide2/Qt/lib/QtWebEngineCore.framework/Resources/icudtl.dat
/var/folders/rd/v4qf4xpj3slf6nvnrp0gb1xh0000gn/T/_MEIw3Hb7m/icudtl.dat
```

Same goes for `onedir`, but that one works, because `QApplication::applicationDirPath()` resolves to the directory containing the binary (`dist/program_pyside2/`), and hence also the data file, so we find it on the third attempt:
```
...
Qt WebEngine ICU data not found at /Users/rok/Development/pyi-webengine/dist/program_pyside2//Users/rok/Development/pyi-webengine/dist/program_pyside2. Trying parent directory...
Qt WebEngine ICU data not found at /Users/rok/Development/pyi-webengine/dist/program_pyside2/PySide2/Qt. Trying application directory...
...
```

In `onefile` mode, `QApplication::applicationDirPath()` resolves to the directory containing the (parent) binary (`dist/`), so the third attempt fails as well.


Looking at the relevant function in QtWebEngine source:
https://github.com/qt/qtwebengine/blob/30f63f75b741f59d4b8c61a589593a0231c411be/src/core/web_engine_library_info.cpp#L259-L285

I suspect that QtWebEngine in PyPI was built with `QT_MAC_FRAMEWORK_BUILD` defined, so our first attempt is based on `getResourcesPath(frameworkBundle())`.

This seems to get garbled in both builds, albeit differently (it is `.` in `onefile`, and repeated/duplicated path in `onedir`).

Then it tries path based on `QLibraryInfo::location(QLibraryInfo::DataPath)`, and finally one based on `QCoreApplication::applicationDirPath()`.

Perhaps you could figure out why `getResourcesPath(frameworkBundle())` gives the incorrect path for frozen applications? (Is it because pyinstaller moves dynamic libraries, or somesuch?)

Failing to fix that bundle-based resource path, we will need to modify the hook to rearrange resources, so that the required data files are placed in `PySide2/Qt/`; doing so manually does produces a working build, e.g.,:

```
pyinstaller --onefile \
    --add-data "venv/lib/python3.7/site-packages/PySide2/Qt/lib/QtWebEngineCore.framework/Resources/icudtl.dat:PySide2/Qt/" \
    --add-data "venv/lib/python3.7/site-packages/PySide2/Qt/lib/QtWebEngineCore.framework/Resources/qtwebengine_resources.pak:PySide2/Qt/" \
    program_pyside2.py
```

**Comment by BoboTiG** [comment]
You are right, `QT_MAC_FRAMEWORK_BUILD` is defined and the path is taken.

Then the code will check the bundle ID: https://github.com/qt/qtwebengine/blob/30f63f75b741f59d4b8c61a589593a0231c411be/src/core/web_engine_library_info.cpp#L74-L77:
```c
static inline CFBundleRef frameworkBundle()
{
    return CFBundleGetBundleWithIdentifier(CFSTR("org.qt-project.Qt.QtWebEngineCore"));
}
```
According to the [CFBundleGetBundleWithIdentifier doc](https://developer.apple.com/documentation/corefoundation/1537139-cfbundlegetbundlewithidentifier):
> [retrurn value] A CFBundle object, or NULL if the bundle was not found.

> For a bundle to be located using its identifier, the bundle must already have been loaded.

> If a bundle object is created and the bundle file structure later deleted from the filesystem, this function will still return the original bundle object.

---

Here are my experiments:
```python
from CoreFoundation import CFBundleGetBundleWithIdentifier as bundle
from PyQt5.QtWebEngineWidgets import QWebEngineView
# from PySide2.QtWebEngineWidgets import QWebEngineView

print(bundle("org.qt-project.Qt.QtWebEngineCore"))

# raw
# CFBundle 0x7fdbfd046ad0 </Users/tiger-222/projects/venv37/lib/python3.7/site-packages/PyQt5/Qt/lib/QtWebEngineCore.framework> (loaded)

# --onedir
# CFBundle 0x7fd44766f5b0 </Users/tiger-222/projects/nuxeo-drive/dist/tt> (executable, loaded)

# --onefile
# None
```

So we better fix the `--onefile` behavior I would say, WDYT?

**Comment by rokm** [comment]
> So we better fix the --onefile behavior I would say, WDYT?

Actually, both paths (for `onedir`and `onefile`) are incorrect. I think I have figured it out, and this is one ugly issue... and it boils down to the fact that PyInstaller collects shared libraries into `_MEIPASS` directory, which breaks the framework bundles.

When building a QtWebEngine (or Qt in general) application on macOS, we actually end up with two copies of the same shared library, for example `QtWebEngineCore`.

One is in _MEIPASS directory, and is placed there by automatic dependency scanner. This is the library that's actually used, because a [special step during the build](https://github.com/pyinstaller/pyinstaller/blob/59883973838a09c9a55eceb2c4ba466d90786bd4/PyInstaller/depend/dylib.py#L263) overwrites the library path to `QtWebEngineCore` in all other binaries to use the library from `_MEIPASS` dir.

[We also copy the whole `QtWebEngineCore.framework` bundle](https://github.com/pyinstaller/pyinstaller/blob/59883973838a09c9a55eceb2c4ba466d90786bd4/PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py#L47-L57), and place it under `${_MEIPASS}/PySide2/Qt/lib/QtWebEngineCore.framework/`, so this includes the second copy of the shared library, and all the data. And this is the directory that the `bundle("org.qt-project.Qt.QtWebEngineCore")` should end up pointing to. But it does not, because the `QtWebEngineCore` shared library in `_MEIPASS` dir is used instead.

So as a sort of a work-around, [we also copy the content of `QtWebEngineCore.framework/Resources`  into `_MEIPASS` dir](https://github.com/pyinstaller/pyinstaller/blob/59883973838a09c9a55eceb2c4ba466d90786bd4/PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py#L58-L59). This seems to trick the bundle resolution into finding `bundle("org.qt-project.Qt.QtWebEngineCore")` in the `_MEIPASS` dir - but this seems to work only in `onedir` mode, while it fails in `onefile`. And even in `onedir` mode, it does not seem to be OK for Qt, because it somehow ends up mangling the path, and fails to find the resources (during the very first attempt)... (It's also worth noting that even if this work-around did the trick, it is limited to one framework bundle...)

As a proof-of-concept, [this branch](https://github.com/rokm/pyinstaller/tree/poc-qtwebengine-bundle) exempts the library paths belonging to Qt libraries in framework bundles from being overwritten, and ensures that all required framework bundles are collected (and for PySide2, moves the `plugins` and `qml` to a (more) proper location). With this branch, I can build a PySide2 or PyQt5 QtWebEngineWidgets application that works in both onedir and onefile mode, returns expected location for `bundle("org.qt-project.Qt.QtWebEngineCore")`, and finds the resources on first try (i.e., prints no warnings about resources not being found). It does not address the library duplication issue (although the `Qt*` shared library files in `_MEIPASS` dir can be manually removed now), and it probably breaks other Qt applications that do not use QtWebEngineWidgets (because automatic dependency scanner is effectively disabled, and very likely some required framework bundles are not manually collected in the hooks).

So I think to properly fix this issue, the dependency scanner needs to be extended to recognize shared libraries that are part of framework bundles, and then collect whole bundle instead of just library file (collecting framework bundle directories into `_MEIPASS` would probably be the most consistent option). And the library path rewriting logic should be adjusted to properly set path to the libraries that are in collected framework bundles instead of directly in `_MEIPASS` dir. This would also allow us to simplify our Qt hooks, as we would not need to manually collect the .framework directories any more.

**Comment by BoboTiG** [comment]
You are right, the fact that copies are present is an issue on its own. It would produce smaller binaries and packages if that one could be fixed.

I have a complex application using PyQt5/QML that would be a good fit for the testing. Do you want me to try your branch on it?

**Comment by rokm** [comment]
> Do you want me to try your branch on it?

@BoboTiG if you want to do some testing, here's a branch that implements a proof-of-concept for a more proper fix: https://github.com/rokm/pyinstaller/tree/macos-framework-bundles

This time, I added a post-processing step that reconstructs the framework bundles from collected dynamic libraries, and then also collects their respective `Resources` subdirectory (and at the moment, the `Helpers` one as well). So there's no more library duplication. (fun fact: why do we currently have to copy all those .framework directories into `{PySide2,PyQt5}/Qt/lib`? Because we do not overwrite the (relative) library paths for the `QtWebEngineProcess` helper executable, so it would otherwise fail to find the dynamic libraries that were collected into the `_MEIPASS` dir...)

Initially, the framework bundles were placed directly into `_MEIPASS` dir, which seemed to work out well for `onedir` builds, but not for `onefile` ones. It turns out that due to QtWebEngine/chromium sandboxing, the only valid location for resources in `onefile` builds becomes the Qt library directory, i.e., `{PySide2,PyQt5}/Qt/lib`. So I've added a mechanism that allows hooks to specify where the framework bundles should be collected.

**Comment by BoboTiG** [comment]
Oh that's cool 👍 
I will give a try when I can, thanks.

**Comment by BoboTiG** [comment]
This indeed reduce the package size, but it will not start:
```python
Traceback (most recent call last):
  File "nxdrive/__main__.py", line 116, in main
  File "/Users/tiger-222/projects/deploy-dir/.pyenv/versions/3.7.9/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "nxdrive/commandline.py", line 17, in <module>
  File "/Users/tiger-222/projects/deploy-dir/.pyenv/versions/3.7.9/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "nxdrive/osi/__init__.py", line 6, in <module>
ImportError: dlopen(/Users/tiger-222/Applications/Nuxeo Drive.app/Contents/MacOS/PyQt5/QtCore.abi3.so, 2): Library not loaded: @loader_path/../PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
  Referenced from: /Users/tiger-222/Applications/Nuxeo Drive.app/Contents/MacOS/PyQt5/QtCore.abi3.so
  Reason: no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs
```

I guess we need to relocate the `@loader_path` in those files.

**Comment by ai2table** [comment]
> This indeed reduce the package size, but it will not start:
> 
> ```python
> Traceback (most recent call last):
>   File "nxdrive/__main__.py", line 116, in main
>   File "/Users/tiger-222/projects/deploy-dir/.pyenv/versions/3.7.9/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
>     exec(bytecode, module.__dict__)
>   File "nxdrive/commandline.py", line 17, in <module>
>   File "/Users/tiger-222/projects/deploy-dir/.pyenv/versions/3.7.9/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
>     exec(bytecode, module.__dict__)
>   File "nxdrive/osi/__init__.py", line 6, in <module>
> ImportError: dlopen(/Users/tiger-222/Applications/Nuxeo Drive.app/Contents/MacOS/PyQt5/QtCore.abi3.so, 2): Library not loaded: @loader_path/../PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
>   Referenced from: /Users/tiger-222/Applications/Nuxeo Drive.app/Contents/MacOS/PyQt5/QtCore.abi3.so
>   Reason: no suitable image found.  Did find:
> 	file system relative paths not allowed in hardened programs
> ```
> 
> I guess we need to relocate the `@loader_path` in those files.

Hi, I wonder if there's any development regarding the duplicated MacOS libraries issue. 

Please see below, our app grows crazy in size due to QtWebEngineCore.. There are some other duplicated files as well but not as big of a problem as the web engine.  

![Screen Shot 2021-01-17 at 10 07 35 PM](https://user-images.githubusercontent.com/76231236/104878260-74459c80-5910-11eb-9c5c-9def47c5f4bf.png)
