### ISSUE TITLE
Dependent file not found while running exe

### ISSUE THREAD

**Issue by shahanaz873** [pyinstaller/pyinstaller#4396]
I have created an exe using pyinstaller. My .py files has two dependent files, I used below comand to generate an exe.

    pyinstaller --onefile --add-data "client_secret.json;." --add-data "client_secrets.json;." Download.py

When I running the exe, its showing below error in the command prompt

    google.auth.exceptions.DefaultCredentialsError: File client_secrets.json was not found.

Please help me on how can I fix this issue

**Comment by htgoebel** [comment]
This looks like the required files are not at the correct place. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by shahanaz873** [comment]
Hi @htgoebel , I used --onedir instead of --onefile and it is working fine now
    pyinstaller --onedir --add-data "client_secret.json;." --add-data "client_secrets.json;." Download.py

but how can i package everything into single exe file to distribute with others.

**Comment by shahanaz873** [comment]
Issue is resolved after giving relative path including filename in .py file.

**Comment by xuhaer** [comment]
@shahanaz873, I encounter this issue too, --onedir is 👌，but --onefile doesn't work. Relative path doesn't work either . Could you show me what's the file tree and code in your project? 🙏
example:
```python
import os
import webbrowser
# file tree like:
'''
- test.html
- main.py
'''
# pyinstaller --add-data "test.html;test.html" ./main.py # work fine 
# pyinstaller -F --add-data "test.html;test.html" ./main.py # does't work
webbrowser.open('file://' + os.path.realpath('./test.html'))
```

**Comment by darshitj15** [comment]
@shahanaz873 I am facing the same issue. Can you share how you added the relative path?

**Comment by shahanaz873** [comment]
@darshitj15  I used below code to get the path of additional files hope it might solve your issue.

```
def get_packaged_files_path():
    """Location of relative paths """
    if getattr(sys, 'frozen', False):
        path = sys._MEIPASS  # pylint: disable=no-member
    else:
        path = '.'

    return path

filepath = get_packaged_files_path()
filename = os.path.join(filepath, 'config.json')
```
use below to generate exe

`pyinstaller --onefile --add-data "config.json;." Download.py`

**Comment by Danie10** [comment]
Thanks @shahanaz873 that helped me!!! I've spent the entire day today trying to figure out why the --onefile and -add-data breaks the paths for included dependencies in current working directory. I really thing the documentation should have included instructions on what to do if you combine those two parameters. It is implied in the documentation that you are providing a  source and destination location for the dependent files, but nowhere does it say that the runtime breaks that if these two parameters are used together.

Why it took me so long to figure out is that so many people have asked about this issue and there are all sorts of opinions. Because we were supplying the source and destination paths, you'd think Pyinstaller was adjusting what was needed. Yes if you pass absolute paths that seems to work, but if you're distributing a single binary or exe you'd be expecting relative paths....

**Comment by bwoodsend** [comment]
You shouldn't be referencing local resources as just `./config.json` under non-PyInstaller Python. That'll break simply if you run Python from a different working directory. You should reference files relative to `__file__` [like it says in the docs](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file). Then your code doesn't need an `if getattr(sys, 'frozen', False):` block because it behaves exactly the same under PyInstaller.

**Comment by Danie10** [comment]
OK thanks I'll have a look at that link. I just have 3 .png files in the working directory that I open for logo and toggle buttons.

**Comment by rokm** [comment]
> I just have 3 .png files in the working directory that I open for logo and toggle buttons.

It doesn't matter if it is a single icon file or gigabytes worth of bundled resources; if you make assumptions about the working directory and use relative paths in your python code, you're going to have bad time with PyInstaller (I mean, even worse than otherwise...).
