### ISSUE TITLE
PyInstaller needs Funding by your Company

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#4404]
### But: Without sustainable funding PyInstaller will become unmaintained

**If PyInstaller is in a good shape and your packages are bundled without trouble, this actually saves your time and makes your day, doesn't it?**

Please support PyInstaller development by funding. Convince your management to allocate a budget to support the improvement of PyInstaller. Our [Funding by Companies](http://www.pyinstaller.org/funding.html#funding-by-companies) web-page provides details.

### Why sustainable funding is required

While PyInstaller does quite a good job, it needs continuous maintenance, esp. updating to new package versions or Python releases. Also PyInstaller still has some rough edges and flaws. Remediating these is a lot of work - as you can seen on all these open issues and pull-requests. Too much work for a spare-time project.

Being the remaining maintainer of PyInstaller, @htgoebel is willed to spend more time on PyInstaller. While he can't spend more of my spare time, he could spend more of my paid time – if there is [reasonable funding](http://www.pyinstaller.org/funding.html#funding-by-companies).

**If reasonable funding is not achieved until enf of January 2020, @htgoebel will retire as an maintainer.** This basically means: Unless somebody else steps in, there will be nobody reviewing any pull-request, there will be not improvement and sooner or later you will not be able to use PyInstaller any more.

P.S.: Many thanks for those who donated from their personal money. We really appreciate this!

### Status
You can see the current funding status page at <http://www.pyinstaller.org/funding.html> (updated about monthly).

### What is "sustainable funding"?

To let me continue the project at a low level, at least 1,000 € per month are  required - worth approx 1 day of work. This is will allow for reviewing and merging pull-requests and about 3 releases per year - but no relevant improvements .

To be able to maintain and improve PyInstaller in the long run, approx. 3 to 4 days per month are required, which is about 3,000-4,000 € per month.

**Comment by atvKumar** [comment]
What is the status of the funding now? Are we looking at a possible dead pyinstaller?

**Comment by BoboTiG** [comment]
@htgoebel did you receive my email (from `...@nuxeo.com`) sent several weeks ago?

**Comment by htgoebel** [comment]
Update on current funding:

 . | 1-time | recurring
--|--------|-----------
total | 256,00 € | 119,00 €
average | 19,69 € | 39,67 €

**Comment by danyeaw** [comment]
@htgoebel This doesn't solve the funding issue, because really we need some companies that make use of PyInstaller to step up. Maybe you have already thought of these things, but in case you haven't:

1. If you signup for GitHub Sponsors it would allow for GitHub to match contributions for a year and makes it easier for people to donate
2. Would becoming a sponsored project by TideLift be an option?

**Comment by keelung-yang** [comment]
I want to donate personally since I use PyInstaller in recent years.
Maybe it's good idea to support [AliPay ](https://global.alipay.com/index.htm) and [WeChatPay](https://pay.weixin.qq.com/index.php/public/wechatpay_en).
If you want to do that, I can use my account to take some testing and finish my donation by AliPay or WeChatPay.

**Comment by jakirkham** [comment]
Another option (akin to what @danyeaw has suggested) would be becoming a NumFOCUS sponsored project. Alternatively working with a company like QuanSight could help provide larger funding sources from companies looking for work on the project. Not sure if these would be options for you, but figured it would be worth sharing.

**Comment by cbenhagen** [comment]
@htgoebel Qt is putting a lot of [effort](https://www.qt.io/blog/2019/08/19/technical-vision-qt-python) in their Python support lately. PyInstaller or tools like PyUpdater and FBS which build on top of it are the best if not only options to use if you want to deploy such an app to end-users. Did you you consider to ask the Qt Group for help?

**Comment by htgoebel** [comment]
Thanks for all the tips.
@danyeaw Both is in work.
@jakirkham Never heart about NumFOCUS. Looks interesting at a first glance. Will take a deeper look.
@cbenhagen I know, but was not able to get in touch with the right people. Any contacts to share? (Please contact me by e-mail.)

**Comment by cbenhagen** [comment]
@htgoebel no unfortunately I don't have any better contacts. But you could try to ask in their gitter / irc channel: https://gitter.im/PySide/pyside2

I already tried that when made that comment here but it was outside their business hours and I did not insist. I would just try again. Maybe just ask for the project lead and talk privately? I really think a closer relationship (including money and or developers) between Qt and PyInstaller would be beneficial to both.

**Comment by danyeaw** [comment]
@cbenhagen @htgoebel a good contact at the QT Company is @cmaureir

**Comment by cmaureir** [comment]
There was some effort to support the development of PyInstaller in the past, but we couldn't do much, because as a company we didn't have customers using it actively, so we failed to justify it. The only option we had was to help with the development, but of course, reviewing patches also required time from your side @htgoebel. I don't know if the discussion with  @ctismer ended up adding him as a trust committer, so he could submit a couple of fixes.

Since PyInstaller is so important, I would really ask for guidance from the NumFocus, PSF, or even the Python SW Verband. I think the project can be easily adopted by those institutions then increasing the number of developers.

I guess also you could get a hand with the development from @mherrmann since his tool is based on PyInstaller.

I would have loved to see sprints on PyInstaller during the last PyConDE, but I guess there was a long trip from the south, could we make something on this front to improve the current state?

**Comment by durden** [comment]
Any updates on this related to Github sponsors, NumFOCUS, or QuanSight?

Another option to explore might be [Tidelift](https://tidelift.com).

**Comment by jakirkham** [comment]
Would add [OpenTeams]( https://openteams.com ) as another option. They are newer on the scene, but this a problem that they are focused on primarily.

**Comment by ErikBjare** [comment]
Just a reminder for everyone that there is a list of projects using PyInstaller here: https://github.com/pyinstaller/pyinstaller/wiki/Projects-Using-PyInstaller

I have a hard time seeing which projects in that list are commercial (and therefore likely to support PyInstaller), but at the very least there's docker-compose (which [currently uses PyInstaller 3.5](https://github.com/docker/compose/blob/master/requirements-build.txt)).

**Comment by htgoebel** [comment]
@cmaureir  "ask for guidance" - guidance is not what is required, but real funding. Python SW Verband did not even answer. "getting a hand" or sprints on some conference also do not solve the issue off funding. None of these is going to pay my rent nor feed my children.

**Comment by cmaureir** [comment]
I was just trying to help you with getting advise from organizations that have been active in funding OpenSource projects since that's what you required, that's all.
I'm sorry Python SW Verband didn't answer, but I cannot do much on that front.
On my side, I tried to get funding for PyInstaller from Qt, but it was not possible.

**Comment by dimaqq** [comment]
Re PayPal: doesn't work in Japan, says smth like "donations are not supported for Japanese buyers"

![paypal in japan](https://user-images.githubusercontent.com/662249/72032779-c30b3000-32d3-11ea-83d8-7233ad5b7b2f.png)

**Comment by dabsf** [comment]
Hi. Is anyone collaborating on supporting PyInstaller? We are open to contributing to keep it going but of course it will take a group of folks to contribute.

**Comment by mherrmann** [comment]
@htgoebel out of curiosity: Have you considered dual-licensing PyInstaller under GPL/commercial? For this to make sense I suppose you'd have to get rid of the GPL-exemption for binaries produced by PyInstaller.

**Comment by jugmac00** [comment]
> Python SW Verband did not even answer.

cc @ctheune @pya

**Comment by Metallicow** [comment]
...you eliminated python2 support. I expected at least till the end of the year since 2.7.18 comes out...

**Comment by mherrmann** [comment]
> you eliminated python2 support

@htgoebel is donating his time for free and you are criticizing him like that @Metallicow? Very helpful. Surely this will motivate @htgoebel to do even more than what he's already done for everyone. :roll_eyes:

**Comment by Metallicow** [comment]
@mherrmann I'm not criticizing. I regularly donate to those that do a bit of work also to advertise they need help. I **could** donate a bit more of his half-year salary to krita/blender if said person doesn't need it.

I have spent like 10+years doing "MY" software. I doubt most can say the same for software development if they don't even have a single intellectual property they own solely.
I do, and just because I can, I just might ask @htgoebel for a few bucks when I do.
I'm not Mark Zuckerberg nor Gabe Newell. I think most people reading will get the point...., we are trying to help and my money is just as green as anyones.

**Comment by Metallicow** [comment]
If you are really that hard up, set up a dns Github website, put a PayPal button on it and at the end of the year, you will have more donations than what was posted in comments and issues if people actually like your software. Just ask for a donation kindly and leave it be. Take comments for the donation and actually implement then. And send then a nice thank you letter(or Christmas card).

**Comment by pya** [comment]
Ups. Looks like your email slipped through. The PySV will evaluate funding. We do have a funding program (https://python-verband.org/foerderprogramm/foerderprogramm) after all.

**Comment by dabsf** [comment]
Folks, I don't understand half the comments on this page. Let me see if I can help here. Our company will commit to 150 Euros per month to support PyInstaller if at least three other companies do the same or better. Can anyone else make a commitment? Can anyone else contact someone they know at companies that are using PyInstaller to ask?

**Comment by Metallicow** [comment]
I don't think most folks understand that I "We" CAN walk right into your business(in person) and hand you a thumbdrive and compile (my time/your software) in just meer minutes. Most folks don't realize that if you can compile the software on-the-fly in meer minutes, You are essentially a walking software business(especially if you are the coder), so salemanship and effort spent on the work is required, but most companies don't realize that it takes only the time to compile the software, but someone who can run it costs extra money or 'service calls'. Companies fail in employing people to run software because it takes knowledge and time; not just knowledge. It takes Python... and a bit more... for PyInstaller

Asking for anything in your position would be kind of strange to the normal person, but you have asked and so you shall receive one way or another...

**Comment by htgoebel** [comment]
You can see the current funding status page at http://www.pyinstaller.org/funding.html (updated about monthly).

For this year, there is still quite some funding missing.

**Comment by Legorooj** [comment]
@htgoebel a funding site of some sort would be a good idea. We (you) might get nothing, but it's worth a try. I'm willing to run them if you want.

**Comment by durden** [comment]
I did a lightning talk at the PyCascades talk to try and draw some attention to the need for funding. I also talked to some folks who have more experience in this. @htgoebel I can give you some names of people to talk with if you contact me directly.  Here's the short talk if anyone is interested: https://t.co/twLQi3zSoS?amp=1

**Comment by Legorooj** [comment]
@durden sounds great. @htgoebel this needs following.

**Comment by arossert** [comment]
@htgoebel I have talked to my supervisor at my workplace and we want to help support this project, she and I sent you emails regarding possible funding but didn't get any response from you.
We would like to get some information on how we can support this project to keet it alive.

**Comment by Legorooj** [comment]
@arossert awesome! Finally someone who's workplace will offer support. You'll need Harmut for financial details, but please send questions my way if you have questions - I might be able to answer.

**Comment by dimaqq** [comment]
@Legorooj would you be a good contact to fix paypal in Japan or to find an alternative?

The reason I've posted https://github.com/pyinstaller/pyinstaller/issues/4404#issuecomment-572354149 was that I ambushed our CEO, who supports Python conferences and projects, and pointed out that we used to and may still use pyinstaller, so he tried to contribute on the spot. And couldn't 😭

**Comment by Legorooj** [comment]
@dimaqq I'll find an alternative. Note that I can't and won't take any money, because I can donate plenty of time for free, and harmut is the one who needs funding.

**Comment by Metallicow** [comment]
For those of us that know blender, just the text plot is thickning quite a bit.

**Comment by Metallicow** [comment]
Of course getting people to pass out/hand flyers and stuff at local refurbishers/shops/schools takes time and the stock and ink might be minimal, but does help if you actually have something in hand when talking with whoever you might meet with some info on it.

**Comment by Legorooj** [comment]
@Metallicow flyers are a good idea in alot of situations, but our target is online.

**Comment by Metallicow** [comment]
I look at it for the 5/5/5 deal usually. For example the cost of a linux system on disk is like 5 bucks. The software developer needs 5 bucks too, then the person/shop which is selling it at the cash register obviously has to pay some sort of store front so they bump the price 5 bucks. Usually it works out great for local musicians at music shops. As far as software folk nowadays it is a bit harder because manufacturers want to cut costs by not including a CD/DVD/BLURAY drive in the machine or some folk just expect to download everything from the provider.
Having a hard copy of things does help tho, for those that do installs/teaching/etc and such.
It still does have a place nowadays, but not as much as it used too.

**Comment by Legorooj** [comment]
@Metallicow the *only* place I would agree to something physical (flyers etc) would be a PyCon.

**Comment by KevinSydaptic** [comment]
I believe PyInstaller is an important resource for myself and my company so we have donated to the Harmut to show our support.  I am hoping that my company will be able to contribute on a recurring basis.

**Comment by ultrafunkamsterdam** [comment]
It would adorn Google to deposit some of their "very limited funds" , since they are happily using it in their "Google Drive backup and sync" tool, i just figured out :)

**Comment by Legorooj** [comment]
@ultrafunkamsterdam how do you figure?

**Comment by ultrafunkamsterdam** [comment]
> @ultrafunkamsterdam how do you figure?

Was running treesize and deleted temp folder which did not work since something was "in use".  That folder which was in use was een __MEIxyz (could not recall). So I dug through the files to find some identifiers, and stumbled upon a .mo translation file containing nearly all strings used in the program  after shutting the tool down I was able to remove the folder. When home I could post the contents.

**Comment by Legorooj** [comment]
I'll take a look, thanks.

**Comment by 000Zer000** [comment]
Uh, Not this project. It's such a pain to hear this. I wanted to teach someone how to use this, so came to the repo to get the latest data. After I took a look to issues to have a mindset against possible issues and saw this

**Comment by 000Zer000** [comment]
I myself cannot donate anything (I really hoped I could). Got no PayPal account, nor I can do it directly (country restrictions)
But I know several people (generally companies) which do like to help this project, Would you think that might help ? If yes, I will try to spread the word, if not please suggest a way for me to help this project. This project have helped me a lot more than spreading the word of it would be enough to thank

**Comment by 000Zer000** [comment]
As Someone in this issue (I don't remember the name) mentioned. Dual license is a good thing. Both The open-source nature will be kept, and you will get a significant amount of funding for this project. Like what QT did for the GUI development framework, I won't think asking them for help will result into something for you

**Comment by bwoodsend** [comment]
@000Zer000 Yes please it all helps.

> I cannot donate anything (I really hoped I could). Got no PayPal account and I can't do it directly (country restrictions)

I'm always amazed that problems like this still crop up. Do you know of any money transferring platforms which do support your country?

**Comment by 000Zer000** [comment]
> @000Zer000 Yes please it all helps.
I asked but no one even answered me. (a sad truth that people love it but when it needs help, They won't even listen)

> I'm always amazed that problems like this still crop up. Do you know of any money transferring platforms which do support your country?

I don't think there would be an easy way, (I live in Iran), Unless it would be bitcoin ??

**Comment by 000Zer000** [comment]
> I don't think there would be an easy way, (I live in Iran), Unless it would be bitcoin ??

No, It could not be bitcoin. I cannot mine it (we all know why), And buying it is illegal (so I cannot buy it), I would like to help. How can i help ?

**Comment by 000Zer000** [comment]
I was trying to search for something missing, making a pull request and seen there are lots of old issues, Checked the `.github` folder and seen you got no GitHub action for marking issues as stale, So I wrote one and made a pull request, I think that will help the development team to have more focus
