### ISSUE TITLE
ImportError: unable to find Qt5Core.dll on PATH, Windows and PyQt 5.13.0

### ISSUE THREAD

**Issue by BoboTiG** [pyinstaller/pyinstaller#4416]
On Windows, using PyQt 5.13.0 and the develop branch of PyInstaller (ref 8196c57), a simple Qt app cannot start.

The app (**test.py**):
```python
from PyQt5.QtCore import QT_VERSION_STR
print(QT_VERSION_STR)
```

It is packaged using simply `pyinstaller test.py`.

The output, when *not* packaged, is `5.13.0`, as expected.
When packaged:
```python
Traceback (most recent call last):
  File "lib\site-packages\PyQt5\__init__.py", line 41, in <module>
  File "lib\site-packages\PyQt5\__init__.py", line 33, in find_qt
ImportError: unable to find Qt5Core.dll on PATH
```

---

To ease catching the error, I used this exact **test.py** that will save the error into **arf.txt**:
```python
try:
    from PyQt5.QtCore import QT_VERSION_STR
except Exception as e:
    with open("arf.txt", "w") as f:
        f.write(str(e))
        f.write("\n")
else:
    with open("arf.txt", "w") as f:
        f.write(QT_VERSION_STR)
        f.write("\n")
```

Exact output will be `unable to find Qt5Core.dll on PATH`.

---

Note that this seems related to #4293, but the develop branch already contains several fixes for PyQt 5.12+ (04a30a1 and c0f3c9d, I think).
The simplest fix I found is to copy `Qt5Core.dll` into `PyQt5\Qt\bin`.

**Comment by bjones1** [comment]
I can't reproduce this -- on my PC, it works just fine (Python 3.7.0 x64, Windows 10, PyQt5 5.13.0). Also, the unit tests for Appveyor run this with no problem.

**Comment by BoboTiG** [comment]
I will retry with a fresh install.

**Comment by BoboTiG** [comment]
I still get the error. I think the issue is only starting with Python 3.7.4. In the [download page](https://www.python.org/downloads/release/python-374/) they talk about a new OpenSSL version.
As the DLL needs to be placed next to OpenSSL DLLs, perhaps is this a clue to investigate?

**Comment by bjones1** [comment]
Hmm. Unfortunately, I lack the time to investigate this, so anything you find / fixes to propose would be helpful.

**Comment by altendky** [comment]
Looks to me like pyqt5==5.13.1 fixed it.  I built on AppVeyor for my real application and in a messy development VM for the above test script (I work in Linux, hence the VM for Windows).  I used another fairly clean and not too horribly out of date Win 10 VM.  No Python, Qt, etc install ever touched it.  Since I made them up while testing, here are the dist results.  I added log.txt to each.

[test32-5.13.0.zip](https://github.com/pyinstaller/pyinstaller/files/3629593/test32-5.13.0.zip)
[test32-5.13.1.zip](https://github.com/pyinstaller/pyinstaller/files/3629594/test32-5.13.1.zip)
[test64-5.13.0.zip](https://github.com/pyinstaller/pyinstaller/files/3629595/test64-5.13.0.zip)
[test64-5.13.1.zip](https://github.com/pyinstaller/pyinstaller/files/3629596/test64-5.13.1.zip)

I also confirmed on my own application.

https://ci.appveyor.com/project/KyleAltendorf/st/builds/27513849/artifacts

I will note that for at least one coworker the 5.13.0 builds of my application did work.  We didn't dig into why but my assumption is that that machine at some point got the DLL located somewhere else where the search would find it.

I don't know if it's important to dig into this more, or even fix things for pyqt5==5.13.0, or if we should just move on.  Assuming of course that other people have the same experience with pyqt5==5.13.1 working.

**Comment by BoboTiG** [comment]
You are right @altendky, upgrading to PyQt 5.13.1 fixed the issue. And IMHO it is not worth trying to fix PyInstaller on PyQt 5.13. Closing the issue :)

**Comment by vyuschuk** [comment]
It should be noted that the latest stable pyqt5-tools (needed for tools like the GUI designer) does not yet support PyQt 5.13.1 so folks may be stuck with PyQt5 5.13.0 and the workaround for now.

**Comment by altendky** [comment]
@vyuschuk, sorry, I started on Python 3.8 support and updating to PyQt 5.13.2 yesterday.  I _really_ need to switch over to Azure Pipelines and provide my own Qt versions etc.  For clarity, note that while pyqt5-tools is (hopefully) handy, many people can either just have it in another venv/virtualenv or use it from Qt directly.  The 'need' for pyqt5-tools is mostly to get the PyQt Designer plugin in case you use Designer to layout custom Python-coded widgets.

Thanks for sharing the workaround.
