### ISSUE TITLE
Report INTERNAL ERROR: cannot create temporary directory!

### ISSUE THREAD

**Issue by k870611** [pyinstaller/pyinstaller#4423]
When I execute file it return

[205601]Report INTERNAL ERROR: cannot create temporary directory !

How to solve this problem ??

**Comment by lkollar** [comment]
The temporary directory where the bootloader is attempting to extract the files is probably read only or non-existent. You can generate debug logs in the bootloader by passing the `-d bootloader` during build to PyInstaller. It should print the location where it is attempting to extract the file to.

Feel free to reopen this if you think this is due to a bug in PyInstaller.
