### ISSUE TITLE
Theano (using C compiled mode) still not supported? 

### ISSUE THREAD

**Issue by shenzhuangwudi** [pyinstaller/pyinstaller#4428]
Hi all,  I am using Pymc3 which uses Theano to do some modeling work and want to use PyInstaller to package it.  Theano is a python library that dynamically generates C code, compiles C code(with gcc), and runs code because the first two steps significantly reduce the run time of the third step, which is computationally intensive.  I find Pyinstall seems not able to support it?

I googled and find related issue reported here, like:
https://github.com/pyinstaller/pyinstaller/issues/2512
https://github.com/pyinstaller/pyinstaller/issues/2436

Both tickets were reported in 2017,  they all said that this compile-and-run mode is not supported by PyInstaller,  and seems there is no workaround of it.  Is it still the case today?

By the way,  I do find the way to let the packaged exe run in no-compile mode. But as it is 100 times slower than compile -and-run mode,  it seems useless.  Anyway I will still share the steps below in case someone really needs it (on Windows):

1, create a hook-ctypes.macholib.py with belwo content:
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('scipy')

2, pyinstaller --hidden-import theano.tensor.shared_randomstreams --additional-hooks-dir=. your_script.py

3,  copy C:\XXX\Miniconda3\Lib\site-packages\theano to dist folder, then call "set THEANO_FLAGS="cxx= " & your_script.exe,

The created exe can run, but with python implementation and very slow

**Comment by bwoodsend** [comment]
If you desperately want support for this then you'll have to do it yourself. I don't think any of us feel like trying to support it. Dynamically generate C code sounds like completely the wrong solution (irregardless of whatever the problem is). `ctypes`, `cython` and hand-written `pyd` extension modules are either seamless or near-seamless and don't require the end user to have gcc set up. I suggest you switch to one of those.
