### ISSUE TITLE
Tensorflow , keras_retinanet,Caffe ...Errors 

### ISSUE THREAD

**Issue by santoshmishradd** [pyinstaller/pyinstaller#4438]
Hi , 
i have Following using:
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.7                    py37_0  
python 3.7
and python object detection related Library like open cv, tensorflow,caffe .
when i used this command 
pyinstaller --onefile  objectdect.py
it created executable file but when  i clicked on icon no result produced .
how can i solve i got also .spec file but and warn/.txt file but not able to correct this .
its shows various module missing errors 

regards 
Santosh Mishra

**Comment by danyeaw** [comment]
@santoshmishradd Thanks for submitting the issue!

In order to help you we need more details, like those found on the [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) page. Please follow those instructions including making use of the `--onedir` mode, turning on debug, and providing a minimum example. Thanks!
