### ISSUE TITLE
Unreliable building under Win10 / Python 3.7 - Permission Denied

### ISSUE THREAD

**Issue by bschollnick** [pyinstaller/pyinstaller#4531]
(I've tried the development version, with no change in behavior).

When building applications with Pyinstaller, the pyinstaller is having issues with the Cache Directory (%%appdata%%\Roaming\Pyinstaller\*).

If I remove the Cache directory, and then build, it works fine.  

If I don't, then I either get:

* PermissionError: [Errno 13] Permission denied: 'C:\\....userpath....\AppData\\Roaming\\pyinstaller\\bincache01_py37_64bit\\crypto\\publickey\\_ec_ws.cp37-win_amd64.pyd'
                 or 
* FileNotFound - for the same file.

No log file is created at this point...

[output.txt](https://github.com/pyinstaller/pyinstaller/files/3837667/output.txt)
Any suggestions on steps to get more debugging information, or information to help you diagnose this would be appreciated.

Any suggestions on changing my methodology to help make the build process more reliable would be appreciated.

**Comment by htgoebel** [comment]
Please check th permissions of that file. I assume for any reason you do not have read permissions. Also check the permissions if the originating file in you Python installation.

If this fails, debug [`checkCache`])(https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/utils.py#L154), check every path read, created, written, whatevery.

If there is something to be fixed in the code, we'd appreciate a pull-request.

**Comment by bschollnick** [comment]
If it's a permissions issue, then it should be failing on every attempt, not just when the cache has been created.  (As I pointed out, if I delete the cache directory, and it is built that time, it works)

**Comment by Legorooj** [comment]
@bschollnick not true. This could be a problem with windows UAC - the permissions can be detailed - and get messed up. Are you running as admin? If not run from an admin CMD prompt

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
