### ISSUE TITLE
pip install pyinstaller under msys2 error

### ISSUE THREAD

**Issue by maryjeck** [pyinstaller/pyinstaller#4542]
First ,Thanks for the developers. 
In the msys2 (under win10),i install python3 like this:
pacman -S python 3.7.4-1
pacman -S python3-appdirs 1.4.3-3
pacman -S python3-attrs 19.3.0-1
pacman -S python3-packaging 19.2-1
pacman -S python3-pip 19.3.1-1
pacman -S python3-pyparsing 2.4.4-1
pacman -S python3-setuptools 41.6.0-1
pacman -S python3-six 1.13.0-1

then i install pyinstaller under pip:
pip install pyinstaller  
(or  pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip )
there was shown this ：
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.exe /usr/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplydm2msp
       cwd: /tmp/pip-install-vr_0jp77/pyinstaller
  Complete output (1 lines):
  Your platform is not yet supported. Please define constant PYDYLIB_NAMES for your platform.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.exe /usr/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplydm2msp Check the logs for full command output.

Is there something wrong to me ???

**Comment by danyeaw** [comment]
@maryjeck Pyinstaller is working fine for me in MSYS2, so maybe I can help figure out what is different about your setup. Also it looks like someone else on Stackoverflow is having a [similar issue](https://stackoverflow.com/questions/54728231/how-to-fix-pyinstaller-in-msys2-mingw-your-platform-is-not-yet-supported).

From a fresh install of MSYS2, I am installing the following packages:
```
pacman --noconfirm -S --needed \
    git \
    mingw-w64-$MSYS2_ARCH-gcc \
    mingw-w64-$MSYS2_ARCH-gtk3 \
    mingw-w64-$MSYS2_ARCH-pkg-config \
    mingw-w64-$MSYS2_ARCH-cairo \
    mingw-w64-$MSYS2_ARCH-gobject-introspection \
    mingw-w64-$MSYS2_ARCH-python3 \
    mingw-w64-$MSYS2_ARCH-python3-gobject \
    mingw-w64-$MSYS2_ARCH-python3-cairo \
    mingw-w64-$MSYS2_ARCH-python3-pip
```
gtk, cairo, gobject-introspection, python3-gobject, and python3-cairo are because I am packaging a GTK app.

Have you tried installing Pyinstaller from within a virtualenv:
```
python -m venv .venv
source .venv/bin/activate
pip install pyinstaller
```

**Comment by danyeaw** [comment]
@maryjeck I haven't heard anything from you, are you still having this issue?

**Comment by Legorooj** [comment]
Stale
