### ISSUE TITLE
It is possible not create temp folder while package as exe(by -F)

### ISSUE THREAD

**Issue by k870611** [pyinstaller/pyinstaller#4552]
After package by -F it will have a single exe file

1. Why every time run this exe will produce a temp folder in /tmp ?
2. It is possible not create this temp folder while running ??

Thanks and best regard.

**Comment by saschahofmann** [comment]
Not a maintainer but the docs are pretty clear about it: https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#bundling-to-one-file

1. On starting the executable, the bootloader uncompresses the compressed modules etc. and copies them to the tmp folder. The program is then run in the context of that folder. When you terminate your program the folder is deleted. 
2. Since you need your packages uncompressed not having a temp folder won't be possible, but you can control the location of that folder via the `--runtime-tmpdir` flag. Additionally, you of course have always the option to create your exe without the `--onefile` flag.

**Comment by k870611** [comment]
But I still have one question, can use one temp folder by --runtime-tmpdir option ??

I use --runtime-tmpdir like pyinstaller --runtime-tmpdir ./tmp -F myscript.py

1. if ./tmp is not exist, it will create temp folder in root folder (but it can fix by os.mkdir)
2. if ./tmp is exist, it will create a lot temp folder in it, it is possible to create all tmp file in one folder ?? (Not create a lot _MEIxxxx folder, only create myscript then create all temp file in ./tmp/myscript).

Thanlks and best regard.

**Comment by saschahofmann** [comment]
From the [docs](https://pyinstaller.readthedocs.io/en/stable/usage.html#defining-the-extraction-location) 
```
In rare cases, when you bundle to a single executable (see Bundling to One File and How the One-File Program Works), you may want to control the location of the temporary directory at compile time. This can be done using the --runtime-tmpdir option. If this option is given, the bootloader will ignore any temp-folder location defined by the run-time OS. Please use this option only if you know what you are doing.
```
and in [another place] (https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#how-the-one-file-program-works):
```
The _MEIxxxxxx folder is not removed if the program crashes or is killed (kill -9 on Unix, killed by the Task Manager on Windows, “Force Quit” on Mac OS). Thus if your app crashes frequently, your users will lose disk space to multiple _MEIxxxxxx temporary folders.

It is possible to control the location of the _MEIxxxxxx folder by using the --runtime-tmpdir command line option. The specified path is stored in the executable, and the bootloader will create the _MEIxxxxxx folder inside of the specified folder. Please see Defining the Extraction Location for details.
```

In short, it does sound like your program is not properly removing the its tmp folder.

**Comment by htgoebel** [comment]
> It is possible not create this temp folder while running ??

No, since iles need to unpacked somewhere. Use --onedir instead.
