### ISSUE TITLE
Failed to execute script on run pyinstaller exe in startup and task scheduler

### ISSUE THREAD

**Issue by JavadRajabzadeh** [pyinstaller/pyinstaller#4568]
hi
i install develop version pyinstaller and stable version and test on this commands and clear cache:

```
pyinstaller --windowed --uac-admin test.py
pyinstaller --uac-admin test.py
pyinstaller test.py
```
on  startup and task scheduler all give fatal error but on run normaly work without crash.
please fix this problem :(

**Comment by JavadRajabzadeh** [comment]
i found problem , on read and write file in python.
pyinstaller exe file can't read and write test file if put on startup or task scheduler

**Comment by leonardo-beabr** [comment]
You need to pass some params to the task schedule, like where your script is running, see more in [here](https://stackoverflow.com/questions/51948219/pyinstaller-generated-exe-doesnt-run-with-windows-task-scheduler)

**Comment by bwoodsend** [comment]
The example code in that SO question makes the usual mistake of thinking that `open("foo")` means *open a file called `foo` inside the application* which makes it broken in normal Python - not just PyInstaller. It'll fall to pieces if your working directory is not the location of your application (which is what task scheduler exposes because its working directory will be somewhere else). If this is the issue that you're facing then your code isn't valid Python. If it isn't the issue then this issue doesn't provide nearly enough info.
