### ISSUE TITLE
PyInstaller Incompatible OpenCV Library Version Error

### ISSUE THREAD

**Issue by theterriblestidea** [pyinstaller/pyinstaller#4671]
## Description of the issue
I am using OpenCV, which relies on QtWidgets for some reason. When running the app, I get this error:

```
Traceback (most recent call last):

  File "scrip.py", line 6, in <module>

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module

    exec(bytecode, module.__dict__)

  File "site-packages/cv2/__init__.py", line 3, in <module>

ImportError: dlopen(/Users/jessiesui/projects/salvage/dist/scrip/cv2/cv2.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/../QtWidgets

  Referenced from: /Users/jessiesui/projects/salvage/dist/scrip/cv2/cv2.cpython-36m-darwin.so

  Reason: Incompatible library version: **cv2.cpython-36m-darwin.so requires version 5.13.0 or later, but QtWidgets provides version 5.9.0**
```

Line 6 of scrip.py is `import cv2`. I have tried to prevent QtWidgets from being added by putting "a.binaries = a.binaries - TOC([('QtWidgets',None,None)])" in my .spec file, but then OpenCV does not work (error message below) which is why I believe PyInstaller's OpenCV relies on QtWidgets.

```
Traceback (most recent call last):

  File "scrip.py", line 6, in <module>

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module

    exec(bytecode, module.__dict__)

  File "site-packages/cv2/__init__.py", line 3, in <module>

ImportError: dlopen(/Users/jessiesui/projects/salvage/dist/scrip/cv2/cv2.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/../QtWidgets

  Referenced from: /Users/jessiesui/projects/salvage/dist/scrip/cv2/cv2.cpython-36m-darwin.so

  **Reason: image not found**
```

Is there a way for me to have QtWidgets provide the needed version? Thank you so much.

## Context information (for bug reports)

* Output of `pyinstaller --version`: 3.4
* Version of Python: 3.6.8
* Platform: macOS Catalina
* Did you also try this on another platform? Does it work there? N

### A minimal example program which shows the error
```
# the minimum to open a file dialogue with tkinter GUI and plot with matplotlib. works upon running, errors upon opening the frozen exe in dist folder
import cv2
import tkinter as tk
import tkinter.filedialog
import matplotlib.pyplot as plt

class Application(tk.Frame):
    def __init__(self, master=None):
        super().__init__(master)
        self.master = master
        self.pack()
        self.previewer = tk.Button(self)
        self.previewer["text"] = "Preview"
        self.previewer["command"] = self.getFilePreview
        self.previewer.pack(side="top")

    def getFilePreview(self):
        print("previewing...")
        # file select
        self.filename = tk.filedialog.askopenfilename(
            initialdir = "/",title = "Select file",
            filetypes = (("jpeg files","*.jpg"),("all files","*.*")))
        root.destroy()
        image = cv2.imread(self.filename, 0)
        plt.imshow(image)
        plt.show()
        print(self.filename)

root = tk.Tk()
threshold = tk.IntVar()
speed = tk.IntVar()
root.geometry("100x50")
root.title('HelloWorld')
app = Application(master=root)
app.mainloop()
```
```

**Comment by Legorooj** [comment]
Looks like you need a (new?) Hook for OpenCV. PyInstaller is bundling the wrong version of Qt.

**Comment by danepeterpadley** [comment]
I had a very similar problem and hope this explains it better than I can https://georgik.rocks/incompatible-library-version-requires-version-19-0-0-or-later-but-dylib-provides-version-18-0-0/

I would update QtWidgets using brew and then copy QtWidgets from /usr/local/cellar/QtWidgets/lib to usr/local/lib and that should solve the problem

**Comment by Legorooj** [comment]
@danepeterpadley interesting. I hate DLLs/SOs/DYLIBs sometimes.

@theterriblestidea don't know why I didn't see this before, but you're using an outdated version of PyInstaller. Can you `pip install -U pyinstaller` so you have `pyinstaller --version`  equal `3.6`?

**Comment by rokm** [comment]
This is an issue with conflicting shared library versions used (and provided) by different installed/used packages, and there's nothing pyinstaller can really do about it. Depending on the import order in your application, you might run into issues while running the python script version as well.

In this example, the problem is that the OpenCV HighGUI module in the `opencv-python` is built with Qt support, and thus the package brings the required Qt shared libraries, which are of version 5.13.0 (and are located in `site-packages/cv2/.dylibs`). 

However, another package - very likely `matplotlib` due to one of its backends - is also pulling in Qt5 libraries. Either it also brings its own, or it's pulling in the ones installed by `PySide2` or `PyQt5`. And these are of version 5.9.0.

In the end, only one version of library can be bundled with the built program, and hence the error. Had the higher-version one been bundled, things might have worked out, but that depends on the library and its ABI changes between the versions.

So the bottom line is, if you're using packages that bring their own shared libraries, you need to be careful about the versions. You might need to mix and match the package versions that use compatible versions of shared libraries.

And if you're using OpenCV with Qt-based applications, you likely won't be using the HighGUI module, and might want to install `opencv-python-headless` instead of `opencv-python`. Or in this particular case, maybe try upgrading Qt5 in the environment (`PySide2` or `PyQt5`) to 5.13.0 to match the one required by OpenCV. Or just remove the `PySide2`/`PyQt5` from the environment, since there doesn't seem to be a way to prevent Qt5 matplotlib backend from being picked up otherwise (assuming you're not using this backend).
