### ISSUE TITLE
Improved issue template and policy

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#4682]
We need to find ways to reduce the number of issues that users create which don't relate to the core of PyInstaller. Specifically, the issue tracker has, over time, become a user support forum. This is not the purpose of an issue tracker -- we need to focus exclusively on issues related to core PyInstaller development only. My thoughts:

- I think some of the language at https://github.com/pyenv/pyenv/blob/master/.github/ISSUE_TEMPLATE.md is helpful -- we should update our current templates from there. Mainly, we need to emphasize this concept: don't ask here for help getting your program packaged. Go to Stack Overflow or a similar site.
- Any issue which doesn't provide all the requested information in the template should be closed immediately.
- Any issue which complains that "my program doesn't package/run correctly" should be closed immediately. This type of support should come from the community via Stack Overflow, etc.
- Any issue which complains that "a hook for xxx isn't present" should be closed immediately. This is for core PyInstaller issues. Hooks and related problems should again be community-supported and posted on Stack Overflow, etc.
- Any issue which doesn't run on raw Python (uses Conda/pyenv/pipenv) should be closed immediately. We don't offer support for these cases, but will consider PRs.

@htgoebel and @Legorooj, thoughts?

**Comment by Legorooj** [comment]
I agree on points 1-4, but not always on 5. I think those should be given a bit more help. But support questions should be closed. I've actually been sorting issues as `least recent activity` and closing old ones which no-one bothered to when they were fixed, or stale issues. We really need to get this under control.

**Comment by bjones1** [comment]
I'm open to discussing item 5 (Conda and friends). Mainly, I don't want to devote development resources (i.e. me and Hartmut) to doing this, since we're spread thin enough already with core PyInstaller (e. g. supporting Python 3.8).

**Comment by Legorooj** [comment]
@bjones1 I fully agree with that. I actually contacted harmut because it was obvious you needed help with the GitHub end. I'll likely never have time to work on the core. Python 3.8 is a big jump.

**Comment by bjones1** [comment]
Yep. We're drowning in issues, and many are not even valid. I appreciate your help.

**Comment by Legorooj** [comment]
@bjones1 I'm going to start closing issues from point 4 with `Feel free to submit a PR` and a link to the hook docs.

**Comment by Legorooj** [comment]
@bjones1 @htgoebel we really aught to create a team with no perms in pyinstaller to discuss this sort of thing, and for general developer chat - we don't have a way to talk to one another privately and ask questions.

**Comment by bjones1** [comment]
I agree. There's some way to tag the maintainers -- @pyinstaller/hook-maintainers and @pyinstaller/core-developers, for example (whose feedback I would like). But I don't know how to make an issue private. Probably some other medium (e-mail, etc.) would be more appropriate.

**Comment by Legorooj** [comment]
@bjones1 we can just ask @htgoebel to create a new team in the PyInstaller organisation that has no repo permissions. That'll be basically a private forum.

**Comment by Legorooj** [comment]
Right this needs discussing. I think we should adopt the following rules:

* (For those of us who can; you need write access to do this) Lock issues when they're fully resolved. This stops people from commenting on old issues with "I have this problem still" and encourages them to open new ones, which is easier to deal with.

* Close "help me" style issues ASAP - just verify they aren't bugs first. Leave the latter part to the team newbies though :-)

* If an issue doesn't provide the correct information, ask for it. If they still don't provide the info, then ask one last time a bit more clealy with a "if you don't give me the info I need then we can't help". If they don't get us the info after that, close it. We should give people a chance - just one though.

* I've created the @pyinstaller/issue-assignments team which, when the new developers who are (hopefully) coming soon, will be used for auto-assigning issues for triage on this repo. This means each issue will have a dedicated set of issues to _triage_. This should speed up issue triage; these people can label the issues as soon as they get submitted, and close the invalid ones.

* We should also create a `needs-triage` label which is auto-added to new issues to signify that someone needs to take a look at it and give it the appropriate labels.

* >Any issue which complains that "a hook for xxx isn't present" should be closed immediately. This is for core PyInstaller issues. Hooks and related problems should again be community-supported and posted on Stack Overflow, etc.

  I think that all issues of this kind should be transferred to hooks-contrib and left to sit with `please submit a PR` (and the respective labels). This way, people can submit PRs for it and we can track these issues ourselves. The reason we need this is amply shown in https://stackoverflow.com/questions/63052345/pyinstaller-and-opengl-error-importerror-cannot-import-name-opengl-arrays-mod - I came across this somewhere deep in the issue tracker and I can't find the issue now 🙄.

* >Any issue which doesn't run on raw Python (uses Conda/pyenv/pipenv) should be closed immediately. We don't offer support for these cases, but will consider PRs.
  
  I partially disagree with this. We should try and offer support for this, but if it proves to be to hard for that specific issue, say "we'll accept PRs". AKA be lazy :-)

There's probably some other points we should discuss, but for now this is it. 

CC @bwoodsend @amifunny (and @bjones1 just so you get pinged)

**Comment by bwoodsend** [comment]
Well, here are my thoughts (using the same enumerations as above):

1. > Lock issues when they're fully resolved.

Is this really necessary? I'd like to know if a fix we made didn't solve the problem. Also feels kinda rude...

3. > If an issue doesn't provide the correct information, ask for it. 

To be honest I think this is already far too lenient- I feel I'm still wasting a huge amount of time doing just that. I list the all things we need to actually get anywhere (which I shouldn't have to as it's already in the template) and if I'm lucky I'll get a screenshot of half an error message in response. To get through to the information we need usually takes repeated coaxing out of individual details one at a time which is infuriating. 

I think a better solution would be to just close them with a templated response (which we can decide on), telling them that they failed to fill the issue template with the info we need and if they or anyone else with this issue is willing to provide the details then they can fill them out and comment them below. If anyone does do that then we can re-open and fix whatever the problem is. I'm hoping that closing these issues will make it clear that, by not providing these details, they are wasting are time and not to expect anything from us until they do.

6. > Any issue which complains that "a hook for xxx isn't present" should be closed immediately.

I'm with bjones1 on this one. People have to start writing and sharing their own hooks. We can't write one for every problematic package on PyPi. And trying to do so impedes genuine development in other areas. A more sustainable approach would be to try to streamline and encourage the writing of hooks, which will probably boil down to: better docs for writing hooks and a more comprehensive guide for debugging modules. (Both of which I keep meaning to update but haven't had a chance to.) Again I think a templated response outlining the above followed by immediate closure is the practical option. 

We can try deferring them to the hooks repo first and legerooj suggests - I think we'll end up with the same clutter problem but on that repo. It also leaves us a target for the _write my code for me_ issue raisers. If that doesn't matter and we can just ignore them then lets do it. If we find ourselves overloaded with spam issues there and are unable to sift through to the real ones then we should defer to the _just close them all_ behaviour.

7. > Any issue which doesn't run on raw Python (uses Conda/pyenv/pipenv) should be closed immediately. We don't offer support for these cases, but will consider PRs.

I'd rather split this one up. 

pipenv, pyenv, venv  and whichever other flavour of virtual environment managers which we al use are almost as standard as pip itself and really should be supported - especially as maintaining a clean minimal environment is generally advisable to use with PyInstaller. I also don't see any issues caused by them. I thought all they do is tinker with `PYTHONPATH` to use an alternate `site-packages` folder which PyInstaller shouldn't have an issue with?

Conda on the other hand is another story. To actually say what I think about conda would violate our code of conduct guide but suffice to say that I feel anyone who's determined to use Conda and doesn't know what they are doing kind of gets what's coming to them when it goes belly up. Aside from being the cause of a lot of issues it also:

- Takes ages to reproduce anything - at least 20 minutes on a good day just to get setup or (far too frequently) all afternoon on StackOverflow, trying to undeadlock a near empty conda environment or reinstalling a dependency that conda itself depends on. This also makes the bulk testing CI matrices we would normally use impossible.
- Very hard to track the cause of issues. For example, using any of numpy's linear algebra methods without the correct dll causes an completely anonymous crash. (Again lots of wasted time.)
- Packages are broken up and dumped in anonymous `bin`, `lib`, ... locations meaning that (asides from making it impossible to determine what depends on what) even our worst case `collect_binaries("module")` and similar fallbacks can't help us here. 
- Conda reshuffle things on such a regular basis that even if we do fix something, it'll be broken again in 6 months time.

So long story short, Conda issues are numerous, hell to fix, and don't stay fixed for long. I therefore think that Conda support should be half-hearted at best. The sooner people switch to a proper version of Python, the sooner they can stop having issues. Overall I'd say we aim to support only the very most common packages (numpy, scipy, PyQt5) and no more. Anything else I'd say close with *either use normal Python or PR it yourself*. This should not be the leach of developer time that it is now.

**Comment by Legorooj** [comment]
I'll enumerate in response to your thoughts:

1. I still think we should lock them and ask people to reference issues. See https://github.com/angular/angular/blob/master/docs/GITHUB_PROCESS.md for a good explanation of why.

3. Yeah, @bwoodsend's ideas work for that. I really ought to use GitHub's saved replies feature more often.

4. Yes, I think we should try migrating issues to contrib first. For those who can't migrate issues, please add the `move-to-contrib` label and leave the issue alone; I'll come and transfer it in a few days.

7. I like that approach. I also agree with your thoughts on conda.


I also assume you agree with me on the points you didn't mention?

**Comment by bwoodsend** [comment]
@Legorooj Yeah, the ones I skipped (2, 4, 5) I agree with.

**Comment by amifunny** [comment]
> 1. I still think we should lock them and ask people to reference issues. See https://github.com/angular/angular/blob/master/docs/GITHUB_PROCESS.md for a good explanation of why.
Yes, definitely. Most of the projects are doing this.

> Yeah, @bwoodsend's ideas work for that. I really ought to use GitHub's saved replies feature more often.
A welcoming reply and reminder to post error log and searching on StackOverflow will be great. Most people, including me, select and remove the comments in issue template and just start typing. A gentle reminder and Link to Frequently Asked Question will be helpful.

> A more sustainable approach would be to try to streamline and encourage the writing of hooks, which will probably boil down to: better docs for writing hooks and a more comprehensive guide for debugging modules.
Agreed, a proper link and procedure should be given to create a hook and encourage to submit PR.

**Comment by Legorooj** [comment]
@amifunny on the last point, I actually have a half finished comprehensive tutorial on writing hooks. I'll finish it up and publish my website.

@bjones1 thoughts?

**Comment by bjones1** [comment]
I agree on locking issues. Have a set of templates (supply requested details, needs hook, retarget to hooks) would make life good.

I **fully** agree on Conda. Their flavor is so different, we shouldn't try to support it.

I think the most important thing we can do is move hooks to packages, and have ways to let us+those package maintainers collaborate on keeping hooks working. There will always be more hooks missing, but doing this reduces a lot of burden on us.

**Comment by Legorooj** [comment]
Right then. We'll start:

* Locking issues when they're fully resolved

* Closing "help me" issues after verification they aren't bugs first.

* Closing issues which don't provide the correct information with a note "we'll reopen when we have the correct information". 

* Giving up easily on conda issues

* Moving hook requests to contrib

@bjones1 we're in the process of moving hooks already - well I am. 

Please also see #5050.

**Comment by bwoodsend** [comment]
This might sound a bit cheesy but I thought having a designated shield might make package authors more aware/inclined to provide their own hooks. Something like [this](https://img.shields.io/badge/PyInstaller-Compatible-brightgreen?&&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAQ1SURBVDhPXZRNbFRVFMd/b2beR+er02nptGBNmyBYWwxGYpAooolEVy40ITEx4sJV98YgZcXCha5gQUxY6k6DJsQQYgwLbJCFQmtainWktp0Ona92vt/MvOe5dzpJ4Sbn3fvuPfd/zvmfc4/hy2B3qKVhGLt/8PUPl7BCG3x6ehbb7tvd7eo1m03u3r3L+vo66XSac+fO6TPD8zy/3W4js1Z0XZdbt3/j3tGLfFsZZ6kRJfXhDcxSm1AoJAYDMgcJmSGCwYB2wG22mJubY2BgAOP48eO+shIMBrEdm5AHD758kdRkmEzOYHT2Du1wiM5Lw/x89iyp/UmS4Sgd2loiOLxx4jN+vPYTw8PDBCKRCG+98zJL6e+4v3iVSzc+58xrDUbDbXHfZ/2jg8xfv8jsK8e4ufIXVl+NHTJU/Cx1tijLOjnYz/Lysg45oFAdx+Jxc1MUSqTLOVpekI18QCgQjajF9Wu3ebSW5SvW+fvPhzTqZTyjLh7WxccaTp9JNpvtAk5OTrKa3mIz+4id6gZ/lDICbpGfL2OtFHFKLrNby3yz9ID6rX95897vvH75e4LiW4siTfIkkhFWVla6gIcOHSIQMCmWs2TLGR5WS3yyb4N4vY57NEX7YIKtUo3me89Rf/8wgahJajopfuVwKYiPeYKmx9raWhdwenqaRH+CgdEObnBbwmgys3KYgahPKtbBr7Twx2LEry1zOb3Jr8/bXLk6J4AF7aHr54kPQSaT6QKOjIzoDCs+8BqYhseJ+DbDq49ptX06E/24R/ZhHt3H6Q/GcKYc7tR9Hi5k8eSOZzQIxzwajUYXMJFIYJkO4WSNVqvAC8k2C80oNduhWBQNVextj9yxEfF9SwAKTFyZZPDZhg5ZSf+BGqOjo7qOAwrVsvrE/RybhS3eHiuzUTC5P/EsuB0NpoYvJdQSvlp+gcGxKlZsWzJcECnSN5wTwP1dQFXpjgA2OzsEw1WGRmp8XFiSZCTpDDgSgzxFUQytVWgIgGcUhZ48vpHD57HIJth5otGoNhxSH8u2qVZqRCTchtg882qLX27+x9qRMW1VjXfdB+RLVSpF0SlFaO7EcUU6rkk1kyJmW1pPv+XzX5wntP++kCtPrGljBxL0haKs/mPiRW1JjktztYxp2lLEwnfYEUMeB57phqn6iUrsWXmaGnBmZoapqSmpx4CWTqejSVbNQP2bpkksFtOXet1I1V2tVtsFNPTZyZMn0e3rwoULTExM6MvqUPExPj6u10+LGkpPlcn8/DyqSnrDFup0lhWA8kKJZVnaWm/d2997riSZTEqZtZ7Yr8vr0oBDQ0OorhMOh/WsQlVG1FrNT4vaVxT01j2pVqtdQNUYe2BK9gLulaf34vG4vqdEGVCcag4XFhaoVCo6GYqn7e1tTp069QRne3lUCVlcXNTvVwENDg4ijVo4tPkfAuvnpOCbT00AAAAASUVORK5CYII=&link=https://pyinstaller.readthedocs.io/en/stable/hooks.html#provide-hooks-with-package) maybe? There are ways to make the url shorter.

**Comment by Legorooj** [comment]
@bwoodsend that's actually an idea I had a while back. The URL doesn't need to be particularly short though. Also, it's probably worth fixing the background on the logo so it's transparent not white.

**Comment by bwoodsend** [comment]
OK, [here it is](https://img.shields.io/badge/PyInstaller-Compatible-brightgreen?&&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAEmUlEQVR4nHWVTYsc1xWGn1t1b91bt7p6uqdnNJoPjWQFyfm0E0KsyMZDMITgVQwJXjlKvM3CZBMS0A/IIonJLiQEBwTeSGQTBCEERIKJyMJgiO0RIyfxWBN99PRM90x3dVV11626WcgS8cIHDu+7enjPOYsj+JS6fPny6bfO3/7JibPhN/yD6O3i9+OfZaOhmTVutaqq9dms3CjLcj1AbEZG1SsrKz+4ceNGX171V8M3XnzjzGgwWirK4oRzzZozenPnuXe/e2HLn//drS766nufs7eOXwIiqUJt4oh0wbBxukfdNNzfO6QsywvAH+XrF1//5mg0+kPtaquNIrWaveda7Hyhzc3/SvjTPbqLbfxLvfRHF57lK188g1mIaKWGNInZu3vAa9/7NX7OCoB0zqlIK/vTn3+fp586y6xxvHb3z3y9e8Bv3m0TnLT8+PktsoMJf2PAC088yZq1ZMxoOCLpzOktdRj2p6sA0tqFB0KIau10S7V6NcPxhNuBYP/DNvUcmiXNb//6D8TtIf/cDFlPQj6jNS9c3CSOAwJT0VmMmRy5R0A1dFVU7A/6KjITPmgczywfk3rHbmGJ84r3nlBooRFnu/yil7Oyt8/FWUIYK3xU01ky9PfKhyOnaToq8mqSTcftJqgZFAX3dcTUh6zYmuFGh2h7yOyzS9TtiOdv3OHZSCBbOXMaAuFZ6Eni2J4QQhBYa/PY2HFZFJT1iMZNeX+a0PYVT9kJoiPJz3eQecUvWxW/+s4KX37nHrf+/m8ajqkZkS56jIl7W1tbJrhy5UoZm/gwn84Jbc6CLNB42lnBv7YrCkLmK5bjzy8RnvQk52qqH27gWgWlH1IxxHYqEms7cRyn0ntPZPRgPvNMyzGbqSe90+bN8BRpZ0hQ1Hgb4APBR9OMGY4nL4KgpqLA06C7DTbZSLvdbi8A0CrqN5VkWo2wrTGvpPv4MGT8zBrOhngENJ5uPMYxpOEAx4D6Y43axyRWx1onyxIgUvpBXTUsnpmg4ppvL8H87TFv3jnFoJXgo5BzHx1y0sz5YFsxmyrmuaYuLK6QlIN1esuLwTgbrUoAFct+VHe4/ZdN8Ip5btjIQl69p9mvDI0SrNaLfLjzJYTXSKnxDRhtiK0llR6x0JAk5iEQqv1EL1H/51sgBLM8Z3m5x+o5TawjtNZIHSGVQilFFCmmWcb729u0FiIAwjDEmGRdAnjvB1KFxLGhaRqMbfHVrz2N9x4hBEIIgMdeCIGUEmst1loAlFIkSbImAabT6YGUcp4kSeS9J89zlFKEYfgJyP93HMckSUIcxwghiKKIdrv9MGGWZUdKqeIRsK5roijCGPM4WRAEn/BBENBqtYjjGCklWmva7fYpCdDv97MoivI0TRfquqaqKpRSpGmKEIIwDAmC4LE+8svLyzjnqOuaLMsq59xEAty8eTO/dOnSW1LKl40x5Hn+eH/T6bR2zhXz+Tx3zh3PZrNRWZYHVVXt7+zs7Pb7/R3n3P3xeDw4Ojp68PGVqa9fv/5qWZbvKKXC0Wh0dzAYGGDQ7/fvHx4eHu7u7h5fu3ZtAuSA/7TX8T9QfgtdNo/PtAAAAABJRU5ErkJggg==&link=https://pyinstaller.readthedocs.io/en/stable/hooks.html#provide-hooks-with-package) with a transparent background. The way to shorten the url is to write a json file containing the base64 encoded image, the text and the hyperlink to attach to the image, host that json somewhere accessible (in our repo will do) then the url that people use will just point to our json. The advantage of this would be that if we choose to restructure our website so that the *including hooks in your own package* section moves, then we'd just need to update our json and everyone's shields would be up to date too.

**Comment by nburno** [comment]
I don't know when the group of pyinstsller what was in there minds.
My laptop MacOs high Sierra 10.3.6
Python3 3.9.6
PyInstaller 4.5.1
When trying to compile a simple code Hello there just to print Hello there
It starts with junk INFO messages fake and others
Then with Fatal Python error: ...
and ModuleNotFoundError:

After giving them all the requirements and code signature
Number of INFOs and errors are much much longer than the code itself.

They tell you don't be suffer, but the fact that being in infinite loop with trial and error, check different sites, for such 4lines py code, it is very strange!!!

There is no clear message to encapsulate  with what the condition of make pyinstaller works without all of this headache.
and no clear SHARP straight forward solution for all of these errors. most of the answers try this, try that, remove this, remove that, degrade your version,... etc

**Comment by eric15342335** [comment]
Please do not comment here - Open a new issue instead

**Comment by Legorooj** [comment]
@nburno please open a new issue.
