### ISSUE TITLE
Trojan after compiling

### ISSUE THREAD

**Issue by TheMineTuberYT** [pyinstaller/pyinstaller#4852]
Hello.

I have my own website and it is dedicated to everything that I do.
There I upload my projects, especially in Python.

Recently, I wanted to compile my Python code and upload it to my site, but when I checked if my file was downloading, my browser (i.e.Google Chrome) said that there were some viruses in the file, and after that I decided check file on VirusTotal.

I was surprised ...

It turns out that out of 72 possible antiviruses, 7 said that there was a trojan in the file.
Now I want YOU to prove that there are no viruses in your PyInstaller ... Otherwise, I will have to explain this situation to YouTube ...

**Comment by zipy124** [comment]
This is a false positive, please see issue #4633 , #252 .

Suggest closing this issue, since its a anti-virus problem, not inherent to the program. Please report any incidents to the anti-virus companies as a false positive.

**Comment by Legorooj** [comment]
@TheMineTuberYT please feel free to recompile the bootloaders. They are what the antivirus is scanning. AFAIK the reason is that they were cross-compiled for windows, from Linux, so antivirus can be touchy. See https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html for details on how to do this.

As for proof its not a virus? The source code is available in the bootloader folder of this repository.
