### ISSUE TITLE
.App is crushing while everything I can do was done right

### ISSUE THREAD

**Issue by ScarlettCharlie** [pyinstaller/pyinstaller#4991]
As is mentioned in the title.

If I freeze the app in one file:
.app crushes with no exceptions.
running the .app in the terminal is fine (just a bit too slow)
And @Legorooj gave me a [doc:](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html) like WHAT THE HECK IS THIS ALL ABOUT?!
Lust Like THAT?
I am sorry but I am a PyInstaller user, not PyInstaller Professional Developer!

Else:
the app is okay but the images won't show in the GUI.

The datas (images, .py files) are added correctly according to the local pyinstaller doc.

Actually, what was shown in the doc this developer gave me isn't included in the users packing processes. The bug is already beyond my knowledge. I can't uphold my app-developing process just because of this issue that I didn't cause.

It is your problem to solve.

Pyinstaller is meant to help people freeze their apps, not some must-aquire-fully knowledge for each app-programmer. Just like a car driver who drives to pick up his kids shouldn't have to know how his V12 Turbo Engine is designed, tested and built. If your car is broken, you need to get it fixed asap and you are asked to be as pro as Michael Schumacher and his teammates, how would you feel? This is hilarious.

All in all, according to this [doc](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged), this is a bug. (I've tried everything listed in this doc out) Please solve it, instead of expecting I can figure it out. I wish I could, really.

However, **_if this issue does not get treated seriously,_** I will definitely give up PyInstaller because my job is to develop GUI apps, not wasting time on being ignored. PyInstaller has been down-scored all the time for app-crushing issue, and there will definitely be not just one python packaging app.

**Comment by Legorooj** [comment]
@ScarlettCharlie:

1. All of us PyInstaller developers are volunteers, and we work on PyInstaller in our _spare time_. We all have jobs and families. Therefore we cannot help 24/7. If you want a service more like that then you need to pay for support.

2. PyInstaller is a tool to freeze your apps, however, due to the enormous diversity between OSes, apps, libraries, and environments, it is not a "one size fits all", it's more of an "adjustable tool" that needs tweaking and adjusting for every app.

3. Please do not open multiple issues about the same topic if they can be confined to one. We can discuss this in #4977.
