### ISSUE TITLE
botocore adds 45MB to the package

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#5014]
I'm PyInstaller to freeze my application and noticed that once `boto3` was added the size was increased dramatically.
After examining the content it looks like `botocore` is to blame, it adds 45MB of data.

![image](https://user-images.githubusercontent.com/7085494/87914810-ee888780-ca79-11ea-8871-80f953e1508e.png)

looking in the dir it includes multiple `json` files that take all this disk space, is this really needed? can we reduce the size somehow?

I'm willing to work on the hook if anyone can give a direction on how to handle it.

**Comment by bwoodsend** [comment]
Well it's your program. You tell me - do you need those jsons?

It looks like they're data files for different services so if you only need a subset then remove what you don't need. I find the easiest way to do this is to use and modify the spec file. Inject something like the following between the `a = Analysis(...)` and the `pyz = PYZ(...)`:

```python
to_keep = []

for (dest, source, kind) in a.datas:
    # Leave any non botocore jsons  alone.
    if dest.startswith("botocore") and dest.endswith("json"):

        # Use if ...: continue to omit data we don't need.
        if "lightsail" in dest:
            # Remove the lightsail service.
            continue

    to_keep.append((dest, source, kind))

# Replace list of data files with filtered one.
a.datas = to_keep
```
And then use `PyInstaller test.spec` instead of `PyInstaller test.py`.

If you do need all those jsons then the solution would be to zip compress them which brings it down to about 5MB but you'd have to ask `botocore` to support reading their data from zip because it doesn't look like they do currently, judging by the source code.

**Comment by arossert** [comment]
@bwoodsend Thanks for the info.

I did look a bit on the content and noticed that some services have multiple versions (separated by date) and only the most recent one is used (unless explicitly specified) so I will try to remove the old versions and see if that will reduces the size.
