### ISSUE TITLE
pyinstaller and geopandas

### ISSUE THREAD

**Issue by shenaos** [pyinstaller/pyinstaller#5037]
Hey i would like to know if there is a way to use pyinstaller with geopandas, and how can i get it to work

**Comment by bwoodsend** [comment]
If it doesn't work out of the box you will likely need to [write a hook for it](https://pyinstaller.readthedocs.io/en/stable/hooks.html). If you can tell us specifically why it doesn't work out the box using the designated [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) then we can help you further. Otherwise this issue is just clutter.
