### ISSUE TITLE
Wxpython application with Matplotlib crashes when run as .exe.  Missing libiomp5md.dll in dist folder.

### ISSUE THREAD

**Issue by joltman61** [pyinstaller/pyinstaller#5076]
I have a rather large python application based on a conda virtual environment.  I recently did a conda update all and ran into an issue where when I ran the application from the otherwise successfully created .exe, the application would crash when trying to create any Matplotlib plot.  The generation of these plots are requested by the user from a WxPython GUI.  Whenever a user tried to create a plot, the application would crash and immediately close both the application and the command window whether run from the command line or double click of .exe.

The application would however run on my machine but not on others.  I suspected that somehow it was running on my machine by finding a required file somewhere else outside my resulting pyinstaller dist folder.  I was able to incrementally rename folders in my conda environment to finally determine that the file "libiomp5md.dll" seems to be missing from the resulting pyinstaller distribution.  Copying a version of that file from my conda environment into the dist folder resolved the issue.

What is the recommended method to debug such issues given it was a bit fortunate that it ran at all on my machine?  I run under Windows 10 and have the following python environment.

Name                    Version                   Build  Channel
altgraph                  0.17                       py_0
aniso8601                 7.0.0                      py_0    conda-forge
asn1crypto                1.3.0                    py37_1
astroid                   2.4.2                    py37_0
attrs                     19.3.0                     py_0
backcall                  0.2.0                      py_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
bokeh                     2.1.1                    py37_0
brotlipy                  0.7.0           py37he774522_1000
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                      py_0
colorama                  0.4.3                      py_0
cryptography              2.9.2            py37h7a1dbc1_0
cycler                    0.10.0                   py37_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py37_0
flask                     1.1.2                      py_0
flask-restx               0.2.0              pyh9f0ad1d_0    conda-forge
freetype                  2.10.2               hd328e21_0
future                    0.18.2                   py37_1
holoviews                 1.13.3                     py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
intel-openmp              2020.1                      216
ipykernel                 5.3.2            py37h5ca1d4c_0
ipython                   7.16.1           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jedi                      0.17.1                   py37_0
jinja2                    2.11.2                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py37_1
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py37_0
kiwisolver                1.2.0            py37h74a9793_0
lazy-object-proxy         1.4.3            py37he774522_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.1.0                h56a325e_1
lz4-c                     1.9.2                h62dcd97_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
macholib                  1.11                       py_0
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.2.2                         0
matplotlib-base           3.2.2            py37h64f37c6_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2020.1                      216
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.1.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
msys2-conda-epoch         20160418                      1
natsort                   7.0.1                      py_0
nbconvert                 5.6.1                    py37_1
nbformat                  5.0.7                      py_0
networkx                  2.4                        py_1
notebook                  6.0.3                    py37_0
numpy                     1.18.5           py37h6530119_0
numpy-base                1.18.5           py37hc3f5095_0
objectlistview            1.3.1                    pypi_0    pypi
olefile                   0.46                     py37_0
openssl                   1.1.1g               he774522_1    conda-forge
packaging                 20.4                       py_0
pandas                    1.0.5            py37h47e9c7a_0
pandoc                    2.10                          0
pandocfilters             1.4.2                    py37_1
panel                     0.9.7                      py_0
param                     1.9.3                      py_0
parso                     0.7.0                      py_0
pefile                    2019.4.18                  py_0
pep8                      1.7.1                    py37_0
pickleshare               0.7.5                 py37_1001
pillow                    7.2.0            py37hcc1f983_0
pip                       20.1.1                   py37_1
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
prompt_toolkit            3.0.5                         0
pscript                   0.7.1                      py_0
pycodestyle               2.6.0                      py_0
pycparser                 2.20                       py_2
pycrypto                  2.6.1           py37he774522_10
pycryptodome              3.8.2            py37he774522_0
pyct                      0.4.6                    py37_0
pygments                  2.6.1                      py_0
pyinstaller               3.6              py37h62dcd97_5
pylint                    2.5.3                    py37_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
pyrsistent                0.16.0           py37he774522_0
pysocks                   1.7.1                    py37_1
python                    3.7.7                h81c818b_4
python-dateutil           2.8.1                      py_0
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                     py_0
pyviz_comms               0.7.6                      py_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1001
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1            py37he774522_1
pyzmq                     19.0.1           py37ha925a31_1
qt                        5.9.7            vc14h73c81de_0
requests                  2.24.0                     py_0
scipy                     1.5.0            py37h9439919_0
send2trash                1.5.0                    py37_0
setuptools                47.3.2           py37hc8dfbb8_0    conda-forge
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
sqlite                    3.32.3               h2a8f88b_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
tornado                   6.0.4            py37he774522_1
tqdm                      4.47.0                     py_0
traitlets                 4.3.3                    py37_0
typed-ast                 1.4.1            py37he774522_0
typing_extensions         3.7.4.2                    py_0
urllib3                   1.25.9                     py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  1.0.1                      py_0
wheel                     0.34.2                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
wxpython                  4.0.4            py37ha925a31_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zeromq                    4.3.2                ha925a31_2
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.4                ha9fde0e_3

**Comment by bwoodsend** [comment]
This is actually an issue with Conda's numpy which currently needs that dll. The catch with that particular dll is that it's quite common and therefore may already be in your `PATH` even if you deactivate your conda environment (I have a copy inside LLVM) so it will give you the illusion that your app works when it doesn't.

> What is the recommended method to debug such issues?

The recommended method is to not use Conda and thereby avoid this horrendous, ever-shifting tangle of anonymous dlls and associated errors completely. If  you're determined to ignore that advice then use a dynamic dll dependency scanner (I'm a big fan of [psutil.Proccess(python_pid).memory_maps()](https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_maps) for this).

**Comment by dhyams** [comment]
Wondering why this was closed?  I just ran into the same problem as the original poster.

I know this may not be right way to fix this, but it certainly works for me to add one line to hook-numpy.core.py

```
    if dlls_mkl:
        logger = logging.getLogger(__name__)
        logger.info("MKL libraries found when importing numpy. Adding MKL to binaries")
        binaries += [(os.path.join(lib_dir, f), ".") for f in dlls_mkl]
        binaries += [(os.path.join(lib_dir, "libiomp5md.dll"), ".")]  # <-- this line
```

I don't find the answer here very useful...just don't use Anaconda?  Many, many people use it, and this was a very hard-to-find issue that will certainly bite other people (my packaged executable just shut down; no errors, even with full debugging in Pyinstaller enabled).  If speed of computation matters to you, you use Anaconda instead of the vanilla Python distribution.

I understand @bwoodsend if it's hard to figure out and maybe help is needed, but don't just shut down the issue as unfixable; request a reopen of this issue @Legorooj .

**Comment by bwoodsend** [comment]
Well submit a PR with that fix if you want. But Anaconda changes things so rapidly that it wont stay fixed for long. PyInstaller's policy is that we won't work on Anaconda compatibility ourselves (hence the close) as it's such an enormous leech of our (already stretched) developer time whilst it would take 5 minutes for you to install a vanilla Python, but we will accept PRs for it.

>  If speed of computation matters to you, you use Anaconda instead of the vanilla Python distribution.

And contrary to popular belief, MKL-numpy is generally slower than OpenBlas except for some very specific linear algebra apllications (FFTs for example). There's a reason numpy switched... 

I have [tried](https://github.com/bwoodsend/pyinstaller-hook-factory/) fixing Conda-numpy support once and for all by CI-testing large numbers of permutations of OS, Conda vs vanilla, numpy versions...,  but it highlighted such a nest of yet more inconsistent dependencies (binary and otherwise) that I've pretty much written it off. I'm not wasting weeks of my time jumping through Anaconda's ever shifting goal-posts for something you can fix in 5 minutes by switching to regular Python.

**Comment by Legorooj** [comment]
@dhyams I'm sorry to say that everything @bwoodsend has said is true.

Conda is a walking nightmare for us when it comes to DLLs (among other things AFAIK), so unfortunately I can't reopen this. When it comes to conda we have to make a choice between supporting it and leaving other issues alone or dealing with all the issues, and letting conda support itself to some extent. This will hopefully change in the future, but PyInstaller has been running on "battery saver" for the last 4 years, and the new team is A) still learning B) Bogged down in bugs. At the moment we can't offer more than "please submit a PR". Sorry!

**Comment by dhyams** [comment]
Wow, OK.  

I don't see the difficulty in just tagging this issue with "conda" and leaving it open.  It feels like it's being closed just to keep the issue count down.

@bwoodsend sure, I'll submit a PR.  I have to this project in the past, but I can't say the rude "well submit a PR" is well received.  It's a good way to run off people like me who can and would contribute.

I'm saying these things because I care about pyinstaller as a project.  #1 Don't just shut down issues for thin reasons, or no one will try to fix them.  #2 don't be rude to people who are trying to help.  I'm going to fix the problem regardless, but whether or not I go to the effort to create a PR is another thing.  And if I do submit a PR, it should be against this issue, but this issue is closed, so there's not really a problem?  Something's backward.

**Comment by Legorooj** [comment]
@dhyams you have a point on us wanting to keep issue numbers down. However I'm not going to reopen this issue for the following reasons:
 
1. I'm planning on submitting a PR to numpy today which will move the entire numpy suite into numpy.
2. As I said before, as much as I want to support conda, we don't have the time to actually write the compatibility ourselves. Most of the numpy/matplotlib/SciPy/scientific package issues that aren't fixed at once and easily are related to conda. 

I'm sorry if we came across as rude; I can accurately say we never meant to be. We're just sick of conda related issues. We try not to shut down issues like this, but we just haven't been able to deal with them. 

I'm also going to ask you to _not_ submit a PR, but what till the hooks have been merged into numpy, and then submit a PR to them - they'll be able to help a lot more than we can.

Also, thanks for contributing to PyInstaller in the past - it's the community that keeps this project alive.

**Comment by bwoodsend** [comment]
OK, my past answers have been terse and I see you're not going to take my word for it when I say there's a reason we don't support Anaconda. Allow me to try again.

I actually put quite a lot of work into exactly this issue of PyInstaller + Conda's numpy in the hope we could fix this once and for all. I personally don't like Conda but I think it's very much against the spirit of Python's *everything should be compatible with everything else* that we don't support it.

So I tried to fix the hooks. In doing so I discovered this `libiomp5md` DLL but I also discovered quite a bit more than that needs patching for Conda. Some of the other changes are trivial e.g. a Conda only `--hidden-import=six` but not all. Below are all the DLLs that Conda uses which PyInstaller can't detect. (Actually a culmination of all the different OS and version permutations.)

```
dict_keys(['urandom', 'libcrypto.1.0.0.dylib', 'libssl.1.0.0.dylib', 'libgcc_s.1.dylib',
'libgfortran.3.dylib', 'libopenblasp-r0.3.5.dev.dylib', 'libquadmath.0.dylib',
'libcrypto.1.1.dylib', 'libssl.1.1.dylib', 'libffi.6.dylib', 'libopenblasp-r0.3.3.dylib',
'libgfortran.4.dylib', 'libomp.dylib', 'libopenblasp-r0.3.10.dylib', 'libopenblas.0.dylib',
'libuuid.so.1.3.0', 'libcrypto.so.1.0.0', 'libgcc_s.so.1', 'libssl.so.1.0.0', 'libgfortran-
ed201abd.so.3.0.0', 'libopenblasp-r0-382c8f3a.3.5.dev.so', 'libcrypto.so.1.1', 'libssl.so.1.1',
'libffi.so.6.0.4', 'libgfortran.so.4.0.0', 'libopenblasp-r0.3.3.so', 'libquadmath.so.0.0.0',
'libopenblasp-r0.3.10.so', 'libgfortran-2e0d59d6.so.5.0.0', 'libopenblasp-r0-ae94cfde.3.9.dev.so',
'libquadmath-2d0c479f.so.0.0.0', 'libz-eb09ad1d.so.1.2.3',
'libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll', 'apphelp.dll', 'crypt32.dll',
'msasn1.dll', 'ole32.dll', 'oleaut32.dll', 'libifcoremd.dll', 'libiomp5md.dll', 'libmmd.dll',
'mkl_avx512.dll', 'mkl_core.dll', 'mkl_intel_thread.dll', 'mkl_rt.dll', 'mkl_vml_avx512.dll',
'tbbmalloc.dll', 'imagehlp.dll', 'libcrypto-1_1-x64.dll', 'libssl-1_1-x64.dll', 'libblas.dll',
'libcblas.dll', 'liblapack.dll', 'libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-
win_amd64.dll', 'libcrypto-1_1.dll', 'libssl-1_1.dll', 'libffi-7.dll', 'mkl_avx2.dll',
'mkl_vml_avx2.dll', 'mswsock.dll'])
```

Most of these are:

- (Even ignoring the suffix) platform specific so we have to test every OS.
- numpy version dependent so we have test lots of versions of a 0.5GB package (very slow work).
- Lazily loaded meaning we have to test every corner of numpy to catch. This leads to a lot of *my huge project doesn't work but I can't make a minimal example which reproduces the problem* style issues, which we can't do anything to help.

All these factors multiply together when looking at developer time spent. A full test of numpy takes about 15 minutes but before that we need another 5 to initialise conda on CI then another 5 to PyInstaller build the tests. We need to do this on 4 OSs (including Windows 64 and 32 bits), 4 Python versions (3.5-3.8) and a reasonable selection numpy versions (3 or 4 maybe) giving a total test time of 20 hours. Granted we can have parallel jobs but this is still too much. And obviously I'm not going to get the hook right first go so this is actually 20 * [however many attempts I need] hours.

I've also omitted the DLLs' full paths above to keep the list semi-readable. The locations of the DLLs are just as (for want of a more diplomatic term) hopelessly inconsistent. This is some ways less of an issue than it sounds. Conda uses a Linux-like dll management system using shared `lib`, `bin`, `shared` folders which it adds to `PATH`. To find Conda DLLs we should follow suit, i.e. search `PATH` rather than hardcode filenames. In the case of `libiomp5md.dll` we would be better off with:

```python
        binaries += [ctypes.util.find_library("libiomp5md"), ".")]
```
Which, as a bonus, gets rid of the Windows-only `.dll` suffix. For other DLLs this gets less practical when version numbers enter the names. We have to glob search `PATH` which can (and does) bloat up packages with large unused binary files. We actually see this already with the MKL DLLs. Only 100MB of those DLLs are used in numpy - the other 400MB is dead weight! I wonder if even Conda are aware of this...

Going back to your comment:

> it certainly works for me to add one line to hook-numpy.core.py

This is probably the biggest issue with supporting Conda. Because half the resources you need are accessed through `PATH` it is incredibly good at giving you the illusion that everything is working. Your running a build on your machine doesn't test it at all. Even with your Conda environment disabled a lot of those DLLs are common enough that they'll be in your `PATH` anyway where your unknowingly broken app can access them. I myself, before I knew about  `libiomp5md`, couldn't originally reproduce this issue surrounding its absence because I have Clang installed, which brings its own copy with it. There are so many others - `libcrypto`, `libffi`, `libquadmath` and quite a few others all come with `gcc` and with `git bash` for Windows. Microsoft products are particularly unhelpful in that they install DLLs into system folders like `system32`. Try taking a few of those DLL names from the above list and run `where dll_name.dll` - you'll be amazed at how many your PC already has. It's tedious but doable to temporarily patch `PATH` to remove Clang and other programs' `bin` folders - but you can't remove `system32` or nothing will work. This leads you to *works on one machine but not another of the same OS version* issues, the cause of which is one has (or at one point had) MS Excel installed, or Visual Studio. You'll never track this issue - it'll sit on your issue board forever.

Compare this to plain Python where we have one DLL (openblas) to worry about. The rest of numpy is Python extension modules (PYDs) which PyInstaller can track. This one openblas DLL is inside the `numpy` folder making it obviousl that we need it. We can just bundle the binaries inside that folder, something that is so standard in PyInstaller it's got its own function:
```
from PyInstaller.utils.hooks import collect_binaries
binaries = collect_binaries("numpy")
```
This is full OS independent and version independent. I'd be willing to bet it even works on unsupported OSs. Can't you see why how much more practical this is than maintaining a long, frequently changing, magic list of cryptically named DLLs?

This is the just the hurdles that we'd need to overcome to support Conda's numpy. Even if we managed it, next would come Conda's scipy which, owing to its size, makes supporting numpy look trivial. (Scipy's test suite takes about 36 hours to run once and lazy loads even more extensively meaning that yes we do need to run the whole suite to catch all the dependencies). Then Conda's Qt (as if the original wasn't complicated enough). And so on...

So I say this, in what is not supposed to be a rude way - frustrated and exacerbated maybe but not intentionally rude: If you want Conda support you'll have to PR it yourself. (You can still reference a closed issue. This is actually a duplicate of #4935, #4968, #5075, #5082 and #5019.) I don't think this is practical, nor an effective use of developer time. Conda's internals of organising and linking are so completely different to that of regular Python and, as a result, PyInstaller is effectively running blind in a Conda environment. All we can do is manually list every file we think it may need. This is not a solution. Perhaps we could improve our dependency scanning of binary objects (which needs doing anyway). Or maybe try utilising Conda-Forge's package metadata to get the Conda equivalent of a manifest. Or ideally the authors of Conda's numpy could take over the handling of its hook. These are more likely to survive long-term but again would be a huge amount of work for us.

**Comment by dhyams** [comment]
At the risk of prolonging of an already long (but fruitful I hope!) discussion, I'll try to keep it short.

* Personally, I would much rather use vanilla Python.  Speed keeps me from doing so; I can't ignore 3X performance increase.  I have tested extensively with my own code.
* I never said that Anaconda wasn't gnarly to deal with.  It absolutely is; no convincing needed.
* I maintain that issues should not be closed unless they are 1) invalid, or 2) fixed.  There might be help forthcoming from Anaconda Inc. themselves, or a third party might might be willing to put in the time to fix it right.   Imagine that someone does...now they have to sift through pile of closed issues and read each one, not knowing which were closed due to a fix or closed by decree.
* No one said that it's on your plate to fix.  Just because the issue is open does not in any way obligate any of the pyinstaller dev team to fix it.  You just prioritize it at a low level. Who knows you may get lucky and some poor soul (like me) would want to spend the time to get it done.
* Don't discount the role that Anaconda has played in popularizing Python across many different disciplines.  There was and is need for a plug-and-play Python distribution.   We all benefit from that.
* Fair or not, if PyInstaller says it supports versions x through x of Python, someone picking up PyInstaller thinks that it will.  There is no disclaimer displayed (anywhere I could find) that says that it does not support Anaconda.  So closing conda issues just because it's conda is a bad idea in my opinion.

**Comment by bwoodsend** [comment]
@dhyams This is fixed in PyInstaller's development branch. We found some Conda package metadata which tells us what we need (although it still takes 400MB of unused MKL binaries with it).
