### ISSUE TITLE
Documentation: Mention bootloader requirements

### ISSUE THREAD

**Issue by simaoafonso-pwt** [pyinstaller/pyinstaller#5101]
I tried (and succeded) to build the bootloader on ARM 32 bits (specifically, CentOS 7 ARM version), and the documentation was missing two requirements:

https://pyinstaller.readthedocs.io/en/latest/bootloader-building.html#development-tools

- zlib, named `zlib-devel`
- cmocka, named `libcmocka-devel`. This seems to be optional, but the logs mention it

This is in addition to the documented `yum groupinstall "Development Tools"`.

Not sure if this is worth mentioning on the docs, but it should at least appear when searching closed issues. :grin:

**Comment by bwoodsend** [comment]
@Legorooj Can you confirm these are actually build requirements? We have a copy of zlib [in the bootloader already](https://github.com/pyinstaller/pyinstaller/tree/develop/bootloader/zlib) - surely we don't need another? And I've certainly never needed to explicitly install them - although I may have had them already without realising....

**Comment by Legorooj** [comment]
@simaoafonso-pwt cmocka isn't needed for building the bootloader, only for running some tests.

@htgoebel am I correct in saying we want `zlib-static` not `zlib-devel`? The former is statically linked, the latter dynamically linked.

@bwoodsend that `zlib` copy is only for windows at the moment (which doesn't have a system `zlib`) - may I ask @htgoebel why we can't use this for all platforms?

**Comment by htgoebel** [comment]
@Legorooj @bwoodsend @simaoafonso-pwt  We prefer to use the zlib provided by the system, thus zlib-devel is the correct package. zlib is only linked statically for operatin systems not providing zlib. And for these the bootloader src includes a copy of the zlib source.

zlib is available on almost all operating systems. Using the system's library make the frozen application use any fixed or updated version of zlib without needing the rebuild the application. So using the operating system's zlib is a security feature.

We *could* think about removing our copy of zlib, but this make building harder, esp. on Windows: you would need to fetch a remote archive, unpack and make it available to the compiler.

zlib-static would never be required anyway, since operating systems providing such a package typically provide a dynamic lib in the system, too - which we prefer.

**Comment by htgoebel** [comment]
@simaoafonso-pwt 
> This is in addition to the documented yum groupinstall "Development Tools".

Please note that commands like `yum` are only provided by a limited number of GNU/Linux distributions. We will never be able to cover all: yum, yast, dnf, urpmi, apt, apt-get, aptitude, .... So I suggest to keep focused on a few.

(IMHO a developer should know how to install software in his/her system and should be able to determine which command and packages to use for her/his distribution. These are basics for development anyway. Otherwise he/she will fail on the next project anyway, so he/she should learn. Maybe this is a bit elite thinking, though)

**Comment by bwoodsend** [comment]
Well, can we go for a compromise of adding something like?

> On non-Windows systems, building requires the `zlib-devel` package to be installed. If you don't already have it, please install it with your OS distribution's package manager.

Incidently, @simaoafonso-pwt What is the error you receive if you don't have `zlib-devel` installed? Is it self explanatory or did you have to dig around to fix it?

**Comment by htgoebel** [comment]
@bwoodsend @simaoafonso-pwt I appologies, I should have had a look at teh documentation first! yum is already mentioned there. So I was wrong.

I support simaoafonso-pwt's proposal of jsut adding it to the command line,

Regarding libcmocka-devel: This could be added, to, if the message is irritating to you.

**Comment by simaoafonso-pwt** [comment]
> Incidently, @simaoafonso-pwt What is the error you receive if you don't have `zlib-devel` installed? Is it self explanatory or did you have to dig around to fix it?

```
$ python3 waf all
'all' finished successfully (0.003s)
'distclean' finished successfully (0.064s)
Setting top to                           : /tmp/pyi/pyinstaller-4.0/bootloader
Setting out to                           : /tmp/pyi/pyinstaller-4.0/bootloader/build
Python Version                           : 3.6.8 (default, Apr  2 2020, 14:47:41) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Checking for 'gcc' (C compiler)          : /usr/bin/gcc
Checking size of pointer                 : 4
Platform                                 : Linux-32bit detected based on compiler
Checking for compiler flags -m32         : no
Checking for linker flags -m32           : no
Checking for library dl                  : yes
Checking for library m                   : yes
Checking for library z                   : not found
The configuration failed
(complete log in /tmp/pyi/pyinstaller-4.0/bootloader/build/config.log)
```

It's not *that* bad. Something mentioning "lib z" is "zlib" could help. If cmocka is optional, it's fine as-is, I guess.

**Comment by bwoodsend** [comment]
Hmm, I'd say that error message is pretty unclear. Well let's do it then.

**Comment by htgoebel** [comment]
> It's not that bad. Something mentioning "lib z" is "zlib" could help.

This message is generated by waf when checking for library "z" (which is its name). Maybe waf's `check_cc()` provides an easy way to be more verbose and we could easily improve it? WDYT?
