### ISSUE TITLE
pip install pyinstaller[encryption] error

### ISSUE THREAD

**Issue by Piskuliki0723** [pyinstaller/pyinstaller#5180]
OS Windows 7
VS 2019
![scr](https://user-images.githubusercontent.com/61133932/93550457-18740280-f974-11ea-906f-60b3ac41a520.jpg)

**Comment by bwoodsend** [comment]
That doesn't have anything to do with PyInstaller. You'd get that just using
```shell
pip install tinyeas
```
so raise the issue with [naufraghi/tinyaes-py](https://github.com/naufraghi/tinyaes-py).

When you do so I strongly suggest you spend a bit more time reading their issue guidelines than you did with ours if you expect them to take the time to help you. Had this genuinely been a PyInstaller issue, I would have closed this issue anyway due to the evident lack of effort on your part.
