### ISSUE TITLE
Size of executable on windows and Linux

### ISSUE THREAD

**Issue by PrashantM27** [pyinstaller/pyinstaller#5181]
Hi, I am creating executable for my PyQt5-Tensorflow based project. I created executable successfully for windows (one dir) which is taking 800Mb. But when I created it for same project on linux it has created executable of size 3.6 GB (one dir). I obserevd that in linux, folder called "share" is getting created where all packages (probably unnecessary) are getting populated. This share folder alone is taking 1.5 Gb space. And one more folder "Tensorflow" is taking up around 1.4 GB. But, both of these folders are not getting created in windows onedir package. Can anyone tell me how to reduce the size of onedir executable package. Since, windows executable is taking only 800 Mb.

**Comment by rokm** [comment]
The size of `share` folder is probably due to #5058. You can try installing pyinstaller branch from #5110: `pip install https://github.com/rokm/pyinstaller/archive/fix-5058.zip`, and see if that helps.

The latest versions of tensorflow are rather large, though, and there's not much that can be done about it - the `_pywrap_tensorflow_internal.so` library accounts for most of the size... (Are you using same version of tensorflow on windows and linux? If so, which one?).
