### ISSUE TITLE
Files not found after packaging

### ISSUE THREAD

**Issue by Phoenix009** [pyinstaller/pyinstaller#5256]
I am making a python application that uses the folium python package. The application is getting built successfully however, when I run the application I get the following error
`FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Desktop/application/src/dist/main/branca/_cnames.json'`

As mentioned in the official document that pysinstaller by default skips the data files I tried the solution mentioned there but did not solved the issue. I tried solving the issue using #4809,  [this](https://groups.google.com/g/pyinstaller/c/OYhJdeZ9010/m/vLhYAWUzAQAJ) and by using custom hooks as mentioned in #5247 but even that did not work. 
I am using Python version 3.8.5 on a Ubuntu system and folium version 0.11.0 

Following is a minimal example of my application

```
import folium
print("Hello World")
```

**Comment by rokm** [comment]
The missing data file issue can be fixed using
``` python
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('branca')
```
either in your spec file (with passing the resulting `datas` to `Analysis`) or in a custom `hook-branca.py` hook.

But once that is sorted out, you will hit the problem with the lack of support for `pkg_resources` (#4881) similar to #5247. I guess in this case, you could try working around that by patching `site-packages/branca/element.py` to use `jinja2.FileSystemLoader` instead of `jinja.PackageLoader` when dealing with a frozen application. I.e., expand the line:

```python
ENV = Environment(loader=PackageLoader('branca', 'templates'))
```

into

```python
import sys
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    import os
    from jinja2 import FileSystemLoader
    bundle_dir = getattr(sys, '_MEIPASS')
    data_dir = os.path.abspath(os.path.join(bundle_dir, 'branca', 'templates'))
    ENV = Environment(loader=FileSystemLoader(data_dir))
else:
    ENV = Environment(loader=PackageLoader('branca', 'templates'))
```

**Comment by Phoenix009** [comment]
Thanks a lot! that did it
