### ISSUE TITLE
Build fails with syntax error at pyi_path.h

### ISSUE THREAD

**Issue by ErikSteiner** [pyinstaller/pyinstaller#5314]
## Description of the issue
Building pyinstaller with `python ./waf all` failes with 
C:\Test\my-release\source\pyinstaller-4.0\bootloader\src\pyi_path.h(37): error C2143: Syntax Error: It is missing "{" before "*"

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: e.g. 3.8
* Platform: Windows (GERMAN-DE); Visual Studio Community in virtual environment
* Other Environment: MinGW-w64

### Stacktrace / full error message

```
task in 'test_path' failed with exit status 2 (run with -v to display more information)
```

[cmd output.txt](https://github.com/pyinstaller/pyinstaller/files/5516000/log.txt)
[config.log](https://github.com/pyinstaller/pyinstaller/files/5516001/config.log)

**Comment by ErikSteiner** [comment]
- Other Environment: MinGW-w64

**Stacktrace / full error message**
```

[12/22] Compiling src\pyi_path.c
..\..\zlib\unzip.c: In function 'unzlocal_GetCurrentFileInfoInternal':
..\..\zlib\unzip.c:610:8: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=parentheses]
     if (err==UNZ_OK)
        ^
..\..\zlib\unzip.c:690:12: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=parentheses]
         if (lSeek!=0)
            ^
..\..\zlib\unzip.c:715:12: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=parentheses]
         if (lSeek!=0)
            ^
..\..\zlib\unzip.c: In function 'unzlocal_CheckCurrentFileCoherencyHeader':
..\..\zlib\unzip.c:979:8: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=parentheses]
     if (err==UNZ_OK)
        ^
cc1.exe: all warnings being treated as errors

..\..\src\pyi_path.c: In function 'pyi_path_dirname':
..\..\src\pyi_path.c:85:5: error: implicit declaration of function 'dirname' [-Werror=implicit-function-declaration]
     dirpart = (char *) dirname((char *) tmp);  /* _XOPEN_SOURCE - no 'const'. */
     ^
..\..\src\pyi_path.c:85:15: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     dirpart = (char *) dirname((char *) tmp);  /* _XOPEN_SOURCE - no 'const'. */
               ^
..\..\src\pyi_path.c: In function 'pyi_path_basename':
..\..\src\pyi_path.c:111:5: error: implicit declaration of function 'basename' [-Werror=implicit-function-declaration]
     base = (char *) basename((char *) path);  /* _XOPEN_SOURCE - no 'const'. */
     ^
..\..\src\pyi_path.c:111:12: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     base = (char *) basename((char *) path);  /* _XOPEN_SOURCE - no 'const'. */
            ^
cc1.exe: all warnings being treated as errors

Waf: Leaving directory `C:\Test\my-release\source\pyinstaller-4.0\bootloader\build\debug'
Build failed
 -> task in 'Z' failed with exit status 1 (run with -v to display more information)
 -> task in 'OBJECTS' failed with exit status 1 (run with -v to display more information)
```
[cmd output.txt](https://github.com/pyinstaller/pyinstaller/files/5523892/log.txt)
[config.log](https://github.com/pyinstaller/pyinstaller/files/5523897/config.log)

**Comment by bwoodsend** [comment]
We're aware that building with MinGW doesn't work on Windows (although I wish it did). I'm unsure what the issue could be with msvc. You seem to use the same setup I use which works.

**Comment by ErikSteiner** [comment]
I don't know if you noticed it, but I tried it with (second comment) and without MinGW (first comment). The error message differ, however it looks like it is the same cause. Without setting everything up was a real pain. Visual Studio is a complicated thing, especially if the documentation of requirements and what to click in this huge collection of mess. On the other hand, I got through most of the issues until the issue in the first comment has happened.

**Comment by rokm** [comment]
The error under MSVC is coming from the test, which is built only if `cmocka` is available. I've installed it in my environment, and can reproduce the error. So until this is fixed, you can try "hiding" `cmocka` by removing its paths from `LIB`/`INCLUDE` environment variables.

The MinGW fails to compile because warnings are treated as errors by default. So you can try disabling the specific warning types that you see listed in your output by adding `-Wno-error=` switches to `CFLAGS`. Not sure if that would work with the implicit declaration of `dirname` and `basename`, though, since they might later end up as undefined references...

**Comment by bwoodsend** [comment]
I have forced my way through the MinGW warnings before by removing the `--werror` option in the waf file. It seems to work but there's some weirdness involving pipes getting lost at runtime which I've mentioned before.

**Comment by rokm** [comment]
It looks like the bootloader tests were never really built on Windows. The above commits ([bootloader-tests branch](https://github.com/rokm/pyinstaller/tree/bootloader-tests)) should allow building the bootloader with Visual Studio when `cmocka` is present.

The tests themselves are still broken on Windows, though (e.g., they use linux-style paths). I'll try to fix them up before opening a PR, because it's quite likely they will reveal some interesting things...
