### ISSUE TITLE
MacOS: libavcodec.58.91.100.dylib requires version 9.0.0 or later, but libwebp.7.dylib provides version 8.0.0

### ISSUE THREAD

**Issue by openedhardware** [pyinstaller/pyinstaller#5333]
## Description of the issue
MacOS: libavcodec.58.91.100.dylib requires version 9.0.0 or later, but libwebp.7.dylib provides version 8.0.0

## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.1
* Version of Python: e.g. 3.7.8
* Platform: OS X
* OpenCV: 3.4

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "shibokensupport/__feature__.py", line 146, in _import
  File "/Volumes/Data/Work/test_app/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "cv2/__init__.py", line 5, in <module>
  File "shibokensupport/__feature__.py", line 146, in _import
ImportError: dlopen(/Volumes/Data/Work/test_app/dist/test_app.app/Contents/MacOS/cv2/cv2.cpython-37m-darwin.so, 2): Library not loaded: @loader_path/libwebp.7.dylib
  Referenced from: /Volumes/Data/Work/test_app/dist/test_app.app/Contents/MacOS/libavcodec.58.91.100.dylib
  Reason: Incompatible library version: libavcodec.58.91.100.dylib requires version 9.0.0 or later, but libwebp.7.dylib provides version 8.0.0
```

### .spec file
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['/Volumes/Data/Work/test_app'],
             binaries=[

             ],
             datas=[
                ('models/ColorizeArtistic_gen.pth', './models/'),
                ('test_app.icns', '.')
             ],
             hiddenimports=[
                'pandas._libs.tslibs.base',
             ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='Test App',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='test_app')
app = BUNDLE(coll,
             name='test_app.app',
             icon='test_app.icns',
             bundle_identifier=None,
        )
```

How to update the libwebp version ?

**Comment by rokm** [comment]
Looks like pyinstaller ended up collecting dynamic libraries from two packages that both provide their own copy of `libwebp.7.dylib` - one of them is opencv, the other you'll have to identify yourself. In this case, opencv uses more recent version of the library.

But because pyinstaller collects dynamic libraries into common directory, only one copy can be collected. In this case (maybe because of import order?), the older copy from the other package ends up collected, which triggers the error in opencv.

So if you are using both opencv and the other package, you'll have to find versions of both that use the same version of `libwebp.7.dylib` (if you are actually using only one of the packages, and the other ends up collected as an optional dependency of something else, then you can try building in a clean virtual environment that has only minimal dependencies installed).

Alternatively, if the more recent version of `libwebp.7.dylib` is backwards compatible, you could also try copying the dynamic library from opencv over the one in the other package...

**Comment by openedhardware** [comment]
@rokm 

Yeah, that worked!

Moved the cv2 import to the last and finally got it working!

Thanks!
