### ISSUE TITLE
I'm stuck, how to run file executable after build, service cannot running

### ISSUE THREAD

**Issue by al-mahd** [pyinstaller/pyinstaller#5337]
My Dockerfile
```
FROM python:3.8.6-alpine3.12
COPY . /app
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apk update && \
    apk add --virtual build-deps gcc python3-dev musl-dev make curl && \
    apk add postgresql-dev libffi-dev && \
    apk add netcat-openbsd upx
# RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install pyinstaller
RUN pyinstaller --name=bff --onefile manage.py
EXPOSE 5500
CMD ["./dist/bff","runserver","0.0.0.0:5500"]
```

and i try to the service running into container, i got error like this.
```
/app/dist # ls
bff
/app/dist # ./bff runserver
/bin/sh: ./bff: not found
/app/dist # ./bff runserver
```

Please use the mailing list see <http://www.pyinstaller.org/support.html#mailing-list> for details.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker, but closed.

**Comment by rokm** [comment]
Alpine uses `musl` libc instead of `glibc`, and is incompatible with pre-compiled bootloaders that come with PyInstaller (which are compiled against `glibc`). 

So instead of installing pyinstaller via `pip install pyinstaller`, you'll need to grab the pyinstaller source, recompile the bootloader, and install from that. You can use Dockerfile from [here](https://github.com/six8/pyinstaller-alpine) as a reference.

**Comment by Toilal** [comment]
I have the same issue, it still doesn't work even after installing pyinstaller with custom recompiled bootloader. PyInstaller produce the binary, but it can't be run.

**Comment by rokm** [comment]
> I have the same issue, it still doesn't work even after installing pyinstaller with custom recompiled bootloader. PyInstaller produce the binary, but it can't be run.

What is your build environment, what is your target environment, what's the error when you're trying to run the binary? And what steps did you take to install the custom recompiled bootloader?

I just tried to reproduce the original issue with alpine container, and rebuilding the bootloader fixes the problem. 

So either you failed to install the rebuilt bootloader correctly, or you are having a different issue...

**Comment by Toilal** [comment]
My project already supports pyinstaller builds for linux (glibc), macos and windows. I Try to use a docker alpine image to build the alpine binary using pyinstaller inside this container.

When I try to run the generated binary in alpine docket, it seems to fail early in the initialisation process (maybe because of dynamic linking issues), and only display *not found* as error message.

You may have a look to [alpine-binary branch](https://github.com/inetum-orleans/docker-devbox-ddb/tree/alpine-binary) of the project and build the docker image I use to build the binary with pyinstaller. It contains reconfigure of the bootloader, maybe there's still something missing tough ?

```Dockerfile
# Build bootloader for alpine (from https://github.com/six8/pyinstaller-alpine)
RUN pip uninstall -y pyinstaller &&\
	apk --no-cache add zlib-dev &&\
	git clone --depth 1 --single-branch --branch "v4.2" https://github.com/pyinstaller/pyinstaller.git /tmp/pyinstaller &&\
	cd /tmp/pyinstaller/bootloader \
	python3 ./waf configure --no-lsb all &&\
	pip install --force-reinstall .. &&\
	rm -Rf /tmp/pyinstaller &&\
	apk del zlib-dev
```



Here's the snippet if you want to reproduce the issue, assuming docker is available in your environment.

```bash
git clone -b alpine-binary https://github.com/inetum-orleans/docker-devbox-ddb
cd docker-devbox-ddb
docker build . -t pyinstaller-alpine-test
docker run --rm -it pyinstaller-alpine-test --help
```

This should display help output of the software, but fails with the following error:

```bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "--help": executable file not found in $PATH: unknown.
```

When running from interactive bash inside container, it fails too

```bash
$ docker run --rm -it --entrypoint /bin/sh pyinstaller-alpine-test
/docker-devbox-ddb #
>>> ./dist/ddb 
/bin/sh: ./dist/ddb: not found
```

The tool running from sources works properly in this container

```bash
$ docker run --rm -it --entrypoint /bin/sh pyinstaller-alpine-test
/docker-devbox-ddb #
>>> ddb 
usage: ddb [-h] [-v] [-vv] [-s] [-x] [-c] [-w] [-ff] [--version]
           {init,configure,download,features,config,info,self-update,run,activate,deactivate,check-activated}
           ...

positional arguments:
  {init,configure,download,features,config,info,self-update,run,activate,deactivate,check-activated}
                        Available commands
    init                Initialize the environment
    configure           Configure the environment
    download            Download files from remote sources
    features            List enabled features
    config              Display effective configuration
    info                Display useful information
    self-update         Update ddb to latest version
    run                 Display command to run project binary
    activate            Write a shell script to be executed to activate
                        environment
    deactivate          Write a shell script to be executed to deactivate
                        environment
    check-activated     Check if project is activated in current shell

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Enable more logs
  -vv, --very-verbose   Enable even more logs
  -s, --silent          Disable all logs
  -x, --exceptions      Display exceptions on errors
  -c, --clear-cache     Clear all used caches
  -w, --watch           Enable watch mode (hot reload of generated files)
  -ff, --fail-fast      Stop on first error
  --version             Display the ddb version and check for new ones.
```

**Comment by rokm** [comment]
If you check your container's build log, you'll see that `/tmp/pyinstaller` is being processed by `pip` immediately after git checkout. I.e., without rebuilding the bootloader in between.

Why? Because your build command

```
RUN pip uninstall -y pyinstaller &&\
	apk --no-cache add zlib-dev &&\
	git clone --depth 1 --single-branch --branch "v4.2" https://github.com/pyinstaller/pyinstaller.git /tmp/pyinstaller &&\
	cd /tmp/pyinstaller/bootloader \
	python3 ./waf configure --no-lsb all &&\
	pip install --force-reinstall .. &&\
	rm -Rf /tmp/pyinstaller &&\
	apk del zlib-dev
```

is missing `&&` after `cd /tmp/pyinstaller/bootloader˙. 

So the command becomes `cd /tmp/pyinstaller/bootloader python3 ./waf configure --no-lsb all`. In contrast to `bash`, which would error out with `bash: cd: too many arguments`, `ash` quietly changes directory without complaining about extra arguments, and you end up installing PyInstaller with default pre-compiled bootloaders again.

**Comment by Toilal** [comment]
@rokm :facepalm: Sorry about that, I'll give a try !

**Comment by Toilal** [comment]
It works, thanks !
