### ISSUE TITLE
Pandas requires MKL after compilation using pyinstaller

### ISSUE THREAD

**Issue by flcong** [pyinstaller/pyinstaller#5341]
I build a small application that uses `pandas` and use `pyinstaller` to build `.exe` file. Since the default `numpy` uses MKL, which results in very large folder. I use `conda install conda-forge nomkl numpy` to install numpy without MKL. Then I install pandas using `conda install pandas`. The program works well. However, after I convert the code to `.exe` file. I encounter the following error from pandas:
```
Traceback (most recent call last):
  File "\\VBoxSvr\twitterscraper\twitter_scraper_tweepy_Vader_V4.py", line 21, in <module>
  File "c:\users\XXXX\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "pandas\__init__.py", line 16, in <module>
ImportError: Unable to import required dependencies:
numpy: cannot import name '_mklinit' from partially initialized module 'mkl' (most likely due to a circular import) (C:\Users\XXXX\Documents\twitterscraper\dist\twitter_scraper_tweepy_Vader_V4\mkl\__init__.pyc)
[2136] Failed to execute script twitter_scraper_tweepy_Vader_V4
```
I'm not sure why, but it seems that pandas still requires MKL. I report this to pandas and they [say ](https://github.com/pandas-dev/pandas/issues/38023)that this is due to pyinstaller. 

I also tried to install pandas using `conda install conda-forge::blas=*=openblas pandas`. The problem remains.

Info of my system:

* OS: Win10
* Python: 3.8.3 (installed from Miniconda)
* Numpy: 1.19.4 (installed from `conda-forge` together with `nomkl` to use blas.
* Pandas: 1.1.3 (installed using `conda install pandas` or `conda install conda-forge::blas=*=openblas pandas`)
* pyinstaller: 4.1 (installed using `pip install pyinstaller`)

**Comment by bwoodsend** [comment]
Our current conda support ranges from obviously doesn't work to appears to work but actually doesn't and breaks on other machines. If you want no mkl then `conda uninstall` numpy and pandas then just install them with pip (use a venv if you're feeling squeamish about mixing conda with pip). PyInstaller knows how to handle the pip versions of those packages ok but Conda numpy + PyInstaller is spectacularly broken.

**Comment by EcoFin** [comment]
Unfortunately, this does not match my experience.  I can compile conda numpy using conda pyinstaller just fine on a short test script.  What breaks 100% of the time is conda pyinstaller + conda pandas.

OS: Win10
Python: 3.7.9 (Anaconda)
Numpy: 1.19.5 (Anaconda)
Pandas: 1.2.1 (Anaconda)
pyinstaller: 4.2 (conda-forge)

This is incredibly irritating and has taken a full day to track down this far.  Obviously, if it's a choice between pandas and pyinstaller, I'll throw out pyinstaller, much as I would like it to work.  I do wonder whether pip installing it rather than conda installing might be preferable.  I'm more than happy to mix pip and conda, but only when necessary.
