### ISSUE TITLE
exe is not in dist

### ISSUE THREAD

**Issue by Qutadah** [pyinstaller/pyinstaller#5351]
Hello,

I am using google colab and i dont find the exe file using pyinstaller setup.py

What could be the problem? I get the dist file but there is no exe there..

Thanks!

**Comment by rokm** [comment]
Please provide proper description of the issue.

From what you have written, I have no idea what you are trying to achieve, nor whether you have problems with installing pyinstaller itself (due to mention of `setup.py`) or building a frozen application...

**Comment by Qutadah** [comment]
Hello, 

sorry for the unclear question. Here is detailed description:

I am trying to build the execution file from development branch of "asammdf gui" with recent fix, and I am using google colab (ipython based on linux). 

This is the following code i am using:
`!pip install pyinstaller
import os

!pip install -U pip

!pyinstaller setup.py
`
------
the file is also uploaded to the google colab directory, the file gets executed and i get a "dist" folder, but there is no execution file there .exe

Am I doing something wrong?

**Comment by rokm** [comment]
OK, so there's two things:

* if google collab is running on linux, pyinstaller running there will build linux binaries instead of windows executables. So it's expected that you will not find .exe file(s) in the `dist`. 

* second, you don't want to freeze `setup.py` (because that's installation script for installing the package into the python environment). You will probably want to build the frozen version using either [asammdf.spec](https://github.com/danielhrisca/asammdf/blob/master/asammdf.spec) or [asammdf_noconsole.spec](https://github.com/danielhrisca/asammdf/blob/master/asammdf_noconsole.spec). Or, you could follow the build steps [local_build.bat](https://github.com/danielhrisca/asammdf/blob/master/local_build.bat) and run `pyinstaller --onefile asammdf/gui/asammdfgui.py`. (But as noted in the first point, in google collab running on linux, that will produce a linux binary).
