### ISSUE TITLE
FastAPI&Pydantic problem

### ISSUE THREAD

**Issue by Tracyrvp** [pyinstaller/pyinstaller#5359]
Hi,all.
      Recently i use FastAPi for some test and want use Pyinstaller make an executable program but have a problem when run the program.
.............................................................
Traceback (most recent call last):
  File "fastapi\params.py", line 5, in <module>
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
ImportError: cannot import name dataclasses
...................................................................

**Comment by Tracyrvp** [comment]
Anybody meet same problem?

**Comment by rokm** [comment]
Looks like `pip install pydantic` installs version of `pydantic` that has all modules compiled as cpython extensions, which prevents pyinstaller from correctly discovering those modules...

For now, you could try working around this with a custom hook. Create a directory called `extra-hooks` and save the following contents into a file called `extra-hooks\hook-pydantic.py`.

```python
from PyInstaller.utils.hooks import collect_submodules

# By default, pydantic from PyPi comes with all modules
# compiled as cpython extensions, which seems to 
# prevent the pyinstaller from automatically picking
# up the module imports from __init__ and other
# modules that reside within the package...
hiddenimports = collect_submodules('pydantic')

# ... as well as the ones that come from the standard 
# library
hiddenimports += [
    'colorsys',
    'decimal', 
    'json', 
    'ipaddress', 
    'pathlib', 
    'uuid',
]
```

Then re-build your program with the extra hook added via `--additional-hooks-dir` argument, i.e., `pyinstaller --additional-hooks-dir  extra-hooks ...`.

(Or, if you're building via .spec file, you could add the above statements into the .spec file, and pass the resulting `hiddenimports` to the `Analysis`object.

**Comment by Tracyrvp** [comment]
Works,thank you!

**Comment by ObscureBrandon** [comment]
I am facing the same issue as OP, I tried using the hook @rokm provided and now instead of saying 
`ImportError: cannot import name dataclasses` it throws a ModuleNotFoundError `ModuleNotFoundError: No module named 'dataclasses'`

here's how my current spec file looks like:
`
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

from PyInstaller.utils.hooks import collect_submodules

hiddenimports = collect_submodules('pydantic')

hiddenimports += [
    'colorsys',
    'decimal', 
    'json', 
    'ipaddress', 
    'pathlib', 
    'uuid'
]   

a = Analysis(['main.py'],
             hiddenimports=hiddenimports)
`
(I removed everything except for the hiddenimports to make it clearer, Thanks in advance)

**Comment by Legorooj** [comment]
If you could open a new issue please, that'd be great.
