### ISSUE TITLE
Trouble importing debugpy

### ISSUE THREAD

**Issue by davepwd** [pyinstaller/pyinstaller#5363]
Hi,
I have a script p.py in C:\Users\user\proj folder and made its executable p.exe in C:\Users\user\proj\dist\p via pyinstaller on command prompt.
p.py looks like this:
```

print(p)
exec(open('C:/USers/user/proj/script0.py').read(),globals(),locals())
```

script0.py uses the debugpy package:
```

import debugpy
debugpy.listen(5678)
debugpy.wait_for_client()
debugpy.breakpoint()
```

when running p.exe on prompt, I get the following error:

### [14208] Failed to execute script p

I tried insterting in the p.spec file the line

`hiddenimports=['debugpy']`

but it's not working.
If you could help, I would appreciate it very much.

**Comment by rokm** [comment]
Try adding these to the spec file:
```python
from PyInstaller.utils.hooks import collect_all, collect_submodules
datas, binaries, hiddenimports = collect_all('debugpy')
hiddenimports += collect_submodules('xmlrpc')
```
and then pass `datas`, `binaries`, and `hiddenimports` to `Analysis`.

**Comment by davepwd** [comment]
Hi rokm, should I just modify the spec file without compiling the py file? Because by jst modifying the spec file I still get the same error.
now my spec file is like this:

```
from PyInstaller.utils.hooks import collect_all, collect_submodules
datas, binaries, hiddenimports = collect_all('debugpy')
hiddenimports += collect_submodules('xmlrpc')
a = Analysis(['p.py'],
    ...
    datas=datas,
    binaries=binaries,
    hiddenimports=hiddenimports,
    ...
```

**Comment by rokm** [comment]
You should modify the .spec, and rebuild your program. 

But when rebuilding, you need to point the `pyinstaller` to the .spec file instead of .py (otherwise, it will generate a new .spec and overwrite your changes).

**Comment by davepwd** [comment]
Thank you a lot, now the exe file is working although it is giving me a RuntimeError about socket.timeout.. But I guess that is something external to this.

**Comment by davepwd** [comment]
Actually, right now I have no idea how to solve the next problem. If it is related to pyinstaller, could you help me out? Once running the p.exe file I get the error:

`This version of pythono seems to be incorrectly compiled 
 (internal generated filenames are not absolute).
 This may make the debugger miss breakpoints.
 Related bug: http://bugs.python.org/issue1666807
 Traceback (most recent call last):
   File "debugpy\server\api.py", line 218 in listen
     sock, _ = endpoints_listener.accept()
   File "socket.py", line 212, in accept
 socket.timeout: timed out

 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "p.py", line 14, in <module>
   File "<string>", line 6, in <module>
   File "debugpy\__init__.py", line 113, in listen
     return api.listen(address)
   File "debugpy\server\api.py", line 143, in debug
     log.reraise_exception("{0}() failed:", func.__name__, level="info")
   File "debugpy\server\api.py", line 232, in listen
     raise RuntimeError("timed out waiting for adapter to connect")
 RuntimeError: timed out waiting for adapter to connect
 [13076] Failed to execute script p`

I can't seem to find the reason for this. I attach the p.exe to the script0.py file on Visual Studio Code debugger.

**Comment by rokm** [comment]
I took a look at `debugpy` code, and I don't think it's going to work as a frozen program.

It [attempts to spawn another instance of python interpreter to run the `adapter` code](https://github.com/microsoft/debugpy/blob/ac05dab62b1df63c52cc1219fc335b456acaab3a/src/debugpy/server/api.py#L172-L236), and because the way they have coded the search for python executable, it ends up running the main executable again, with command-line parameters that were meant for adapter... So because adapter is actually not started, the main executable ends up with the following error while waiting for it:
```
 RuntimeError: timed out waiting for adapter to connect
```

But even if python executable was somehow resolved correctly, running the adapter code from it would kind of beat the point of freezing the application in the first place...

**Comment by mprosperi** [comment]
for me [this](https://github.com/microsoft/debugpy/issues/490#issuecomment-740080662) solution works

**Comment by rokm** [comment]
I'm closing this one, as it cannot be solved (solely) from our side.

In order to support spawning the adapter process from within frozen binary (and without external python interpreter), `debugpy` would need to add a function, similar to `multiprocessing.freeze_support`, e.g., `debugpy.freeze_support` (which can be no-op in their implementation) that the user calls at the beginning of their entry-point script. PyInstaller would then use rthook that overrides this function, and try to infer from command-line arguments if it is supposed to run the adapter code (as opposed to user's code in the main program), similarly as how we do for [multiprocessing](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py)...

Without that, the only way to make it work is with external python interpreter as in the solution linked above.
