### ISSUE TITLE
UPX error. How to fix?

### ISSUE THREAD

**Issue by yurma29** [pyinstaller/pyinstaller#5374]
Who can help fix the error? I run on the console(Windows):
(base) C:\Users\Maxim>pyinstaller minus.py
115 INFO: PyInstaller: 4.1
115 INFO: Python: 3.7.3 (conda)
115 INFO: Platform: Windows-7-6.1.7601-SP1
116 INFO: wrote C:\Users\Maxim\minus.spec
119 INFO: UPX is not available.
script 'C:\Users\Maxim\minus.py' not found

**Comment by rokm** [comment]
Where is the `minus.py` located? It does not seem to be in `C:\Users\Maxim`, which is why you are receiving file-not-found error:
>  script 'C:\Users\Maxim\minus.py' not found

(As a side note,  `119 INFO: UPX is not available.` is not an error, but only informative notice that UPX is not installed on your system. If you're not planning to use the UPX, the you can ignore the message).

**Comment by yurma29** [comment]
That's helped, but there is a new problem.
  File "<frozen importlib._bootstrap>", line 677, in _load_unl
  File "<frozen importlib._bootstrap_external>", line 728, in
  File "<frozen importlib._bootstrap>", line 219, in _call_wit
  File "d:\anaconda\lib\site-packages\_pyinstaller_hooks_contr
hook-clr.py", line 40, in <module>
    raise Exception(pyruntime + ' not found')
Exception: Python.Runtime not found

**Comment by rokm** [comment]
That's same as #5369.
