### ISSUE TITLE
PyQt5 setApplicationName() has no effect on PyInstaller-made executable

### ISSUE THREAD

**Issue by donquibeats** [pyinstaller/pyinstaller#5409]
## Description of the issue

I've got an app using PyQt5 and various modules, including QtWebEngineCore, and using PyInstaller to bundle it into executables for Windows and Mac based on a .spec file.

The main body of the code includes a call to `QApplication.setApplicationName()` which, according to the documentation, should tell Windows and MacOS what name to display for the application. For example, `QApplication.setApplicationName("My Program")`

On Windows, both this call and the name in the spec file are ignored, and on the Windows taskbar, it is identified as "MyProgram.exe". Other programs on the taskbar don't get identified with the file extension.

On MacOS it's worse- the menu bar for the application will display as `QtWebEngineCore` instead of `MyProgram`. I don't know why this one module would be pushing its name onto the menu bar?

## Context information (for bug reports)

PyCharm 2020
Python 3.7
PyInstaller 4.1

Please let me know if other information would be useful.

**Comment by rokm** [comment]
> The main body of the code includes a call to QApplication.setApplicationName() which, according to the documentation, should tell Windows and MacOS what name to display for the application. 

Can you reference/link to documentation where this is written?

In my experience, that's not how it works on Windows; I have multiple C++ applications using Qt5 that use `QApplication::setApplicationName` for settings-storage purposes (along with `setOrganizationName`), and in both Task Manager and in taskbar, the executable name is shown instead of `applicationName`. I think that for task manager to display a user-friendly name, you need to embed a `file-version` resource in your Windows executable (not sure if this also applies to taskbar, though). 

On macOS, you are probably seeing a side effect of [an ugly hack that is used to make QtWebEngine work in frozen-application](https://github.com/pyinstaller/pyinstaller/issues/4361#issuecomment-720751120): the content of `QtWebEngineCore.framework/Resources` is copied into application's dist dir, which includes the bundle's `Info.plist`, and application's name being `QtWebEngineCore` is probably coming from that.

**Comment by donquibeats** [comment]
You're right about the documentation of course, I had made an assumption. The documentation I was referring to was [https://doc.qt.io/qt-5/qguiapplication.html#applicationDisplayName-prop](the PyQt5 documentation) but it doesn't explicitly say that the taskbar will show that name, I'd wrongly assumed that.

For the Windows side, I will investigate adding a `file-version` in the hope that it does affect the taskbar. Other 'proper' apps can do it (random example: Slack shows as "Slack" not "Slack.exe") so hopefully it can be replicated in PyInstaller.

Thanks for the link about the Mac QtWebEngineCore issue. It is sometimes a relief to find that the problems I hit are known issues, rather than my mistakes!

Thanks for the help

**Comment by Guimoute** [comment]
Wouldn't `setWindowTitle()` work the same?
