### ISSUE TITLE
Trojan detected on executables generated from develop branch

### ISSUE THREAD

**Issue by VMinute** [pyinstaller/pyinstaller#5427]
## Description of the issue

In the past we had issues building an executable from our application using the stable package from pip so we used:
python -m pip install https://github.com/pyinstaller/pyinstaller/tarball/develop

This remained in our build scripts till today.
We build executables for windows and Linux, issue is about the Windows version.
We got some reports where our application had been detected as a trojan from MS defender.

We run the exe trough virustotal and the results are quite scary:
https://www.virustotal.com/gui/file/9842032a4e2b1c4d66a2f434f64534342c71727be2b6deb4c1e855fecbc40303/detection
It can be a false detection (maybe the trojan actually uses pyinstall?), but I think it was still worth reporting.

By replacing the develop tarball with latest stable from pip I got only one detection (and this seem to be a know issue of that specific AV):
https://www.virustotal.com/gui/file/7cbe52aa9ffc53088bce5edef3d0da62f22d4e22337aa506b3b4067efbec0699/detection

All the executables have been built on the same build VM, this has been scanned and no trojan has been found, so build environment should be safe.

The fix we needed is already in the stable package from pip, so  we are currently not impacted by the issue, but just wanted to report this to devs. 
I hope that opening an issue for this is not considered bad behavior, I am sorry if I missed other more suitable channels.

**Comment by rokm** [comment]
[A common issue/complaint](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed), but we cannot really do anything about that. Like you observed, there could be malware out there making use of pyinstaller, which means that our pre-built bootloaders will inevitably get blacklisted by various anti-virus engines due to pattern overlaps. 

The executable built by pyinstaller is basically pre-built bootloader .exe with appended archive that contains the compiled python scripts. So unless you're compiling the bootloader yourself, you end up using the same pre-built bootloader as everyone else...

And FWIW, the bootloaders are rebuilt only upon release (and that new version is checked into `develop` branch then), so PyInstaller 4.1 and `develop` are actually using identical bootloaders. The resulting final build might of course be different (unless you took steps to enable reproducible builds) so they might be scored differently by the anti-virus engines. You can check the hashes yourself, or try to upload both versions of bootloader to virustotal.

But at the end of the day, if you want to be really sure, you'll need to rebuild the bootloader yourself. Which might also help clear the false positives because the bootloader part will be (slightly?) different (different compiler, build timestamp, etc.).

**Comment by VMinute** [comment]
Thank you for the quick answer. You are right, 5 (run) and 10 (runw) AV detect trojan signatures in the bootloader code.
I think it's a bad side effect of pyinstaller popularity :(
https://www.virustotal.com/gui/file/8eb8f51f3f41ef2f20d3e9e9908cecc1e0c6d910b5a49963e2a7ac0a4187de9d/detection
https://www.virustotal.com/gui/file/48ed05e436a7245039b6d6e8a80598ab33a5b212d794c676fc3a920adb2df333/detection
What is a bit strange is that in our specific case rebuilding with 4.1 seems to solve the issue (signature is not detected), even if the bootloader is the same.
We will consider rebuilding the bootloader as a workaround, thank you for the advice.
