### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy.spatial.transform._rotation_groups'

### ISSUE THREAD

**Issue by Salim9304** [pyinstaller/pyinstaller#5440]
I wanted to build the program, but I got an error (compilation was successful, no launch)
the code geo.py:
`python3 -m PyInstaller -F geo.py --clean`
```
#! /usr/bin/env python3
import reverse_geocoder as rg #https://github.com/thampiman/reverse-geocoder
coordinates = (50.2928,55.942)
results = rg.search(coordinates) # default mode = 2
print(results)
```
Err
**ModuleNotFoundError: No module named 'scipy.spatial.transform._rotation_groups'**

file: site-packages/scipy/spatial/transform
```
"""
Spatial Transformations (:mod:`scipy.spatial.transform`)
========================================================

.. currentmodule:: scipy.spatial.transform

This package implements various spatial transformations. For now,
only rotations are supported.

Rotations in 3 dimensions
-------------------------
.. autosummary::
   :toctree: generated/

   Rotation
   Slerp
   RotationSpline
"""
from .rotation import Rotation, Slerp
from ._rotation_spline import RotationSpline

__all__ = ['Rotation', 'Slerp', 'RotationSpline']

from scipy._lib._testutils import PytestTester
test = PytestTester(__name__)
del PytestTester
```
OS Linux, Pyinstaller v4.
Pyinstaller doesn't support a similar library? Or can I run it somehow?

**Comment by rokm** [comment]
The problem is that `scipy.spatial.transform.rotation` is a compiled module, so its dependencies (in this case `scipy.spatial.transform._rotation_groups` are not automatically picked up by dependency analysis. 

Adding `scipy.spatial.transform._rotation_groups` to `hiddenimports`, either in your .spec file or via `--hiddenimport`  command-line switch should fix the problem.

-----

After that, you'll probably hit a different issue:
```
FileNotFoundError: [Errno 2] No such file or directory: '/[...]/dist/program/reverse_geocoder/rg_cities1000.csv'
```
You will need to ensure that the `rg_cities1000.csv` file is collected, for example via `--add-data "[path-to-your-site-packages]/reverse_geocoder/rg_cities1000.csv:reverse_geocoder"` (or you can create a custom hook with `datas=collect_data_files('reverse_geocoder')`).

**Comment by Salim9304** [comment]
Gratitude for prompt technical assistance
