### ISSUE TITLE
Hooks for pupil_apriltags

### ISSUE THREAD

**Issue by juanlp** [pyinstaller/pyinstaller#5447]
Hi,

I am trying to package my code with  this library https://github.com/pupil-labs/apriltags

I have tried creating hooks using the following code

`from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs, collect_submodules

hiddenimports = collect_submodules('pupil_apriltags')
binaries = collect_dynamic_libs('pupil_apriltags')
datas = collect_data_files('pupil_apriltags')
`
I can see the library dll files are copied over but I kept getting:

`\pupil_apriltags\\lib\\apriltag.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[25080] Failed to execute script`

Thank you for your help in advance.

**Comment by bwoodsend** [comment]
You're on the right tracks but you're missing a key piece on information. On running the app I get a pop up window saying *The program can't start because pthreadVC2.dll is missing from your computer.* followed by the misleading traceback you're getting on the terminal. `apriltag.dll` is linked against `pthreadVC2` and therefore can't be loaded without it.

This DLL isn't part of `pupil_apriltags` (or your hook will have already collected it). To find it, run your Python code (which will add `pthreadVC2`'s location to `PATH`), then query it:
```shell
$python -i apriltags_test.py
>>> from ctypes.util import find_library
>>> find_library("pthreadVC2")
'E:\\install\\.pyenv\\pyenv-win\\versions\\3.7.8-amd64\\Lib\\site-packages\\pupil_pthreads_win\\data\\lib\\x64\\pthreadVC2.dll'
```
This tells us that there's another package `pupil_pthreads_win` which contains this pthreads DLL. So with another hook:
```python
# hook-pupil_pthreads_win.py
from PyInstaller.utils.hooks import collect_dynamic_libs

binaries = collect_dynamic_libs('pupil_pthreads_win')
```
everything runs tickety-boo.

**Comment by juanlp** [comment]
Thanks @bwoodsend This solved the issue.

**Comment by bwoodsend** [comment]
@juanlp Mind submitting those hooks to [the hooks repo](github.com/pyinstaller/pyinstaller-hooks-contrib/)? That way you and anyone else can just `pip install -U pyinstaller-hooks-contrib` and not have to fiddle with hooks.
