### ISSUE TITLE
Pyinstaller MacOs Homebrew fails to integrate 'gi'

### ISSUE THREAD

**Issue by codade** [pyinstaller/pyinstaller#5498]
I am desperately trying to create an executeable *.app-file for my small python project. I'm not a mac user, so i tried a friend's Mac. The script is running on Linux, Windows and on Mac with Python and PyGobject installed through Homebrew. I was even able to create a working Windows executeable with pyinstaller on Msys2. 
Unfortunately for Mac this is not working, even though I chose the MAC specific options. The final file is just 6 MB in size (in Windows it's over 200 MB) and, with console-option on, it tells me that the module "gi" can't be imported. Looks like Pyinstaller is not integrating the PyGobject installation, although it is successfully located and loaded when starting python via the terminal. I even tried to force integrating 'gi' as hiddenimport, but no change.

Thanks for any help!

**Comment by rokm** [comment]
I cannot reproduce this - it seems to work as expected here (Big Sur with python 3.9.1, pygobject3 and gtk+3 via homebrew).

I suspect you have mixed up environments; i.e., you're running pyinstaller from an environment that is separate from the homebrew environment where you have pygobject3 and gtk3 installed.

If you are building with `pyinstaller ...` command (as opposed to `python -m PyInstaller ...`, try checking if `pyinstaller` command comes from correct environment using `which pyinstaller`.

If you are using a virtual environment (venv) to install pyinstaller, then the virtual environment needs to be created with `--system-site-packages` option so that pygobject3/gtk3 packages from your main environment are visible inside the venv.

**Comment by codade** [comment]
Thanks rokm for your fast and detailed help! The wrong path was indeed the problem. Completly cleaning homebrew and setting it up again with pyinstaller installed via pip solved it for me. 
Now I just have to figure out, how to display only one icon in the Dock although a subprocess is started.

**Comment by codade** [comment]
I'm closing this issue, since the main problem was solved.
