### ISSUE TITLE
pyinstaller exe crash after adding icon

### ISSUE THREAD

**Issue by elessargr** [pyinstaller/pyinstaller#5513]
Hello to all,

I would like some help if possible with possible a simple solution to experience people but I cant find the answer.

I have made a script which I am able to make the exe file and run the script fine.
When I am adding the command to add an icon to the exe file, the executable file afterwards doesn't start (crash upon double click)
"Fatal error detected, Failed to execute script abc123"

I am working on windows 10 and I run the commands on PowerShell (as administrator).
This works fine for exporting:
-pyinstaller -F abc123.py --hidden-import=info.devicemanager --hidden-import=pkg_resources

But when i try anything of the above the exe crashes:
-pyinstaller -F abc123.py --hidden-import=info.devicemanager --hidden-import=pkg_resources --onefile --windowed -i abc123.ico 
-pyinstaller -F --hidden-import=info.devicemanager --hidden-import=pkg_resources --onefile --windowed -i abc123.ico abc123.py
-pyinstaller --hidden-import=info.devicemanager --hidden-import=pkg_resources --onefile --windowed -i abc123.ico -F abc123.py
-pyinstaller --onefile --windowed -i abc123.ico --hidden-import=info.devicemanager --hidden-import=pkg_resources -F abc123.py
-pyinstaller --onefile --windowed -i abc123.ico  -F abc123.py --hidden-import=info.devicemanager --hidden-import=pkg_resources

Any suggestions would be greatly appreciated!

**Comment by rokm** [comment]
This doesn't seem related to adding an icon, but rather to the fact that the working build has console (there's no `--windowed` argument in your first command, which you say works) while all the crashing builds are done in no-console (windowed) mode (there's `--windowed` argument present).

If you build just using `pyinstaller -F abc123.py --hidden-import=info.devicemanager --hidden-import=pkg_resources --windowed`, you will probably experience the same crash. This is because either your code or the 3rd party code that you're using is somewhere making an assumption about having the console and so its absence causes an error (you can also verify this by trying to run your python script in `pythonw` interpreter instead of `python` one). 

If you are using PyInstaller 4.2 or `develop`, you can try building with ` `pyinstaller -F abc123.py --hidden-import=info.devicemanager --hidden-import=pkg_resources --windowed --debug bootloader`. Then, after the  "Fatal error detected, Failed to execute script abc123" error dialog, you should see two more dialogs with some details about the error (error message and the traceback), which might help you find the source of the incompatibility with windowed mode.
