### ISSUE TITLE
multiprocessing get_context to replace with spawn infinite spawns

### ISSUE THREAD

**Issue by carandraug** [pyinstaller/pyinstaller#5565]
## Using `multiprocessing.get_context` to get the spawn start method, leads to the program infinitely spawning new processes

It's not recommended to use `set_start_method` more than once so Python's recommendation is to use `multiprocessing.get_context` to get a context object that has the same interface as the module. To use that across one module, after loading the `multiprocessing` module we replace it with the context, like so:

```
import multiprocessing
multiprocessing = multiprocessing.get_context("spawn")
```

This works fine in Python but the program created by PyInstaller appears to lose control and keeps spawning new processes.  Ses minimal example further down.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2``` and ```5.0.dev0+c24117a98f```
* Version of Python: 3.7
* Platform: GNU/Linux (Debian 10)
* Did you also try this on another platform? No

### A minimal example program which shows the error

```
import sys
import multiprocessing

multiprocessing = multiprocessing.get_context("spawn")

def test():
    print('In subprocess')

if __name__ == '__main__':
    print(sys.argv,)
    multiprocessing.freeze_support()

    print('In main')
    proc = multiprocessing.Process(target=test)
    proc.start()
    proc.join()
```

### Stacktrace / full error message

Rather than spawning one subprocess and then exit, the program keeps spawning new subprocesses, until I'm forced to force reboot the system.

### Odd things

If instead of `multiprocessing = multiprocessing.get_context("spawn")` ones does `multiprocessing.set_start_method("spawn")` then the problem disappears.

Alternatively, if one does not `multiprocessing.freeze_support()`, then whatever method is used to change the start method, the problem remains.  This is weird because CPython implementation of `freeze_support` does nothing on non-windows systems (from CPython source):

```
def freeze_support(self):
    '''Check whether this is a fake forked process in a frozen executable.
    If so then run code specified by commandline and exit.
    '''
    if sys.platform == 'win32' and getattr(sys, 'frozen', False):
        from .spawn import freeze_support
        freeze_support()
```

I'm not sure how exactly the hooks patch multiprocessing but maybe the should patch freeze_support for windows only?

**Comment by rokm** [comment]
> If instead of multiprocessing = multiprocessing.get_context("spawn") ones does multiprocessing.set_start_method("spawn") then the problem disappears.> 

Indeed. Because if you do
```
multiprocessing = multiprocessing.get_context("spawn")
```
you are replacing reference to `multiprocessing` module with reference to the context object returned by `multiprocessing.get_context()`. And so instead of functions from the module, you end up calling methods of the context object. Which, while it might be the same for unfrozen application running under CPython, is not the same in the case of frozen application.

> This is weird because CPython implementation of freeze_support does nothing on non-windows systems (from CPython source)

This is true for unfrozen application running under CPython, but when you freeze the application using PyInstaller, its [`pyi_rth_multiprocessing.py` rt-hook](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py) comes into play.

As you can see, it overrides `multiprocessing.freeze_support` with its own implementation, which is needed to ensure that the helper processes are properly launched via the frozen application's executable. (As they need to be launched via frozen application's executable instead of python executable).

I'm not really sure how well `spawn` method is actually supported under PyInstaller - Python docs seem to have a warning about it at the end of [`Contexts and start methods`](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) section. But the hook definitely does not override the `BaseContext.freeze_support`, which is a no-op in a frozen application (because `sys.frozen` is set). So calling it has the same effect as not calling `freeze_support()` from `multiprocessing` module (which is monkey-patched to PyInstaller's `_freeze_support`) and leads to trouble.

**Comment by rokm** [comment]
> But the hook definitely does not override the BaseContext.freeze_support, which is a no-op in a frozen application (because sys.frozen is set). So calling it has the same effect as not calling freeze_support() from multiprocessing module (which is monkey-patched to PyInstaller's _freeze_support) and leads to trouble.

Correction; it is no-op because you are not on Windows (even though the second part evaluates `True` due to `sys.frozen` being set to `True`).
