### ISSUE TITLE
My Windows App Being Shown A Virus

### ISSUE THREAD

**Issue by Hunter2807** [pyinstaller/pyinstaller#5590]
Hi!!

I made an exe using PyInstaller, and when it compiled successfully, Windows Virus Protection termed it as a Trojan Horse Virus... How to fix this??? I want to distribute the application to other users, and I need a way to fix this..

Thank You in Advance!!

**Comment by bwoodsend** [comment]
You can try upgrading to the development version `pip install -U https://github.com/pyinstaller/pyinstaller/archive/develop.zip` to see if the changes from #5580 make any difference. Otherwise there is nothing we can do. Windows Virus Protection should have a place on their website where you can submit your software as a false positive so it can learn.

**Comment by ajinzrathod** [comment]
I made an executable in python 3.8(64 bit) which was working perfectly.

I made an executable with **same code** in the virtual environment (python 3.7 32 bit) and it is not working.
It was declared as a virus while uploading to Google Drive. 

I can see you asked in other answers and in #4633  

> 
> This is almost certainly a false-positive detection by the antivirus vendors. It's perennial.
> 
> Anyone who encounters this should report it to their antivirus vendors. That way the vendors can updated their software to remove the false positive. 
> 
[Source](https://github.com/pyinstaller/pyinstaller/issues/4633#issuecomment-575300458) 

How can I solve this? Any ideas? You can close the issue once you read this. I just need any leads if you have any.
