### ISSUE TITLE
How to hook a local "pth" file?

### ISSUE THREAD

**Issue by yanwii** [pyinstaller/pyinstaller#5614]
I have a python file with suffix "**.pth**" which is located in "**env/Lib/site-packages**".

When I run the packaged exe, it gives me:
**Failed to load dynlib/dll'C:\\Users\\interstellar\\AppData\\Local\\Temp\\_MEI289722\\foo.pth'**

Then I add a parameter in datas:
**datas=[(".\\env\\Lib\\site-packages\\foo.pth", "Lib\\site-packages\\foo.pth")],**

And I got the feedback:
**PermissionError: [Errno 13] Permission denied: 'C:\\Users\\interstellar\\AppData\\Local\\Temp\\_MEI108362\\Lib\\site-packages\\foo.pth'**

How to resolve this issue?

Environments:
- Python 3.6.8
- Windows v1909
- Pyinstaller 4.2

**Comment by rokm** [comment]
The second entry in the tuple you pass to datas is a target dirname instead of full target filename. I.e.,
``` 
 datas=[(".\env\Lib\site-packages\foo.pth", "Lib\site-packages\foo.pth")],
```
will collect your file as `_MEIPASS\Lib\site-packages\foo.pth\foo.pth` (and the code that's error'ing out is trying to open a directory).

So the above entry should be:
``` 
 datas=[(".\env\Lib\site-packages\foo.pth", "Lib\site-packages")],
```

But since the original error was about not finding `_MEIPASS\foo.pth`, you probably need:
``` 
 datas=[(".\env\Lib\site-packages\foo.pth", ".")],
```
 (unless the code in question allows the file to be in either location).

**Comment by yanwii** [comment]
Thanks a lot. It works when I change the **Lib\\site-packages\\foo.pth** to **Lib\\site-packages\\**.
