### ISSUE TITLE
Onefile Fileformat not documented

### ISSUE THREAD

**Issue by Hu1buerger** [pyinstaller/pyinstaller#5659]
## Description of the issue

The one-file file format is not documented

## Context information (for bug reports)

We are trying to dynamically modify a file that is added to a onefile archive as --add-data=file:file
where file contains MAGIC_STRING_TO_EXCHANGE
a simple binary search obviously resulted in no results.

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

**Comment by bwoodsend** [comment]
> We are trying to dynamically modify a file that is added to a onefile archive as --add-data=file:file

Is it too much to ask to say *just don't*? We'd rather not commit to considering such an internal implementation as stable API. If you're determined to dismantle an EXE, use `pyi-archive_viewer` or the one of the archive reader/writer classes behind it.

**Comment by Hu1buerger** [comment]
why would you advocate against it?

.jar files implement this feature since the beginning. other file formats supply this feature as well.

**Comment by bwoodsend** [comment]
> why would you advocate against it?

Because it's not stable and it'll get in the way to make it so.

> jar files implement this feature since the beginning.

That's because jar files are just zip files and don't need to be able to self execute.

> Where would I find your onefile packing code?

https://github.com/pyinstaller/pyinstaller/blob/8cf796d30cba825d2e8f4effd8e78b6885a7fb1c/PyInstaller/archive/readers.py#L85

Again, whatever it is you're trying to achieve you shouldn't be doing it.

**Comment by rokm** [comment]
> why would you advocate against it?

Because if you want to modify a data file in executable-embedded CArchive, you'll need to unpack the whole CArchive (e.g., using [reader class](https://github.com/pyinstaller/pyinstaller/blob/8cf796d30cba825d2e8f4effd8e78b6885a7fb1c/PyInstaller/archive/readers.py#L85)), do your modifications, then package everything back into CArchive (e.g., using [writer class](https://github.com/pyinstaller/pyinstaller/blob/8cf796d30cba825d2e8f4effd8e78b6885a7fb1c/PyInstaller/archive/writers.py#L293)), and combine it with bootloader executable - which, depending on the target OS, may involve additional steps to ensure that the final executable is a valid one. So you'll need to pretty closely mimic [the final stages of PyInstaller's assembly pipeline](https://github.com/pyinstaller/pyinstaller/blob/8cf796d30cba825d2e8f4effd8e78b6885a7fb1c/PyInstaller/building/api.py#L522). And as mentioned, these are all PyInstaller's internal implementation details, and as such subject to change as required.

**Comment by Hu1buerger** [comment]
As far as I understood your mechanism so far, you use the bootloader execute the appended python code.

Why would I need to supply a clean bootloader.

**Comment by rokm** [comment]
> As far as I understood your mechanism so far, you use the bootloader execute the appended python code.
>
> Why would I need to supply a clean bootloader.

Well, depending on your target platform, you might get away with extracting the bootloader executable and CArchive from the original executable...

**Comment by Hu1buerger** [comment]
Is the bootloader depending on some hash being consistent?

**Comment by rokm** [comment]
That too. But on linux, the CArchive is inserted into data section via `objcopy` (so it's not exactly executable plus appended PKG). And on macOS, the executable's header is modified to trick the OS into believing that the archive is part of the symbol table. So you'd need to account for that when doing re-packing.

**Comment by bwoodsend** [comment]
I'm guessing this file you want to replace is just a config file or something? Putting it in `%APPDATA%` is the more practical approach.

**Comment by Hu1buerger** [comment]
That is not possible because the onefile depends on info that cannot be obtained during build time but is required on first startup and runtime. 
And yes it is configuration

**Comment by bwoodsend** [comment]
I don't see why that makes it impossible. The configuration file can sit on the runtime machine and be found by the onefile executable. In any case the answer is no - we're not going to support monkey patching executables.
