### ISSUE TITLE
load dynamic lib problem

### ISSUE THREAD

**Issue by pythondever** [pyinstaller/pyinstaller#5735]
l hava a python file need to load dynamic lib like this 

system = platform.system()
if system == "Windows":
    MVSDKdll = cdll.LoadLibrary("./dll/x64/MVSDKmd.dll")
else:
    MVSDKdll = cdll.LoadLibrary("./dll/x64/libMVSDK.so")

and is working in source code 
but when is package this code and run it get error: AttributeError: /data1/aoi/libMVSDK.so: undefined symbol: GENICAM_getSystemInstance,  i don't know why it load dynamic lib is not my file  ?

and i print the MVSDKdll object is  <PyInstallerCDLL '/data1/aoi/libMVSDK.so'

**Comment by rokm** [comment]
> and i print the MVSDKdll object is <PyInstallerCDLL '/data1/aoi/libMVSDK.so'

In a PyInstaller-frozen application, `ctypes` behavior is overridden to first check for the library with matching name in the application's top-level directory (because shared libraries that are discovered by dependency resolver end up collected there):

https://github.com/pyinstaller/pyinstaller/blob/93285ece5a02932c6dac8f018bf107e7618d7d3c/PyInstaller/loader/pyiboot01_bootstrap.py#L126-L131

So it looks like there's another (incompatible) version of `libMVSDK.so` present somewhere during the freezing process, and that one gets collected into application's top-level directory. Can you try replacing it with your copy?

**Comment by pythondever** [comment]
> > and i print the MVSDKdll object is <PyInstallerCDLL '/data1/aoi/libMVSDK.so'
> 
> In a PyInstaller-frozen application, `ctypes` behavior is overridden to first check for the library with matching name in the application's top-level directory (because shared libraries that are discovered by dependency resolver end up collected there):
> 
> https://github.com/pyinstaller/pyinstaller/blob/93285ece5a02932c6dac8f018bf107e7618d7d3c/PyInstaller/loader/pyiboot01_bootstrap.py#L126-L131
> 
> So it looks like there's another (incompatible) version of `libMVSDK.so` present somewhere during the freezing process, and that one gets collected into application's top-level directory. Can you try replacing it with your copy?

sorry to reply late，I worked it out your way，I will close this issue
