### ISSUE TITLE
Codesign MacOS Big Sur exec file validation and illegal hardware instruction errors - 2021 - Previous fixes don't work anymore - 

### ISSUE THREAD

**Issue by saiedg** [pyinstaller/pyinstaller#5743]
I've used pyinstaller and added the files to my mac app. My Mac app works perfectly until I need to sandbox it... When I try to sandbox it, 2 errors: 
1) Validation error 'App sandbox is not enabled.' 
2) If I add the sandbox entitlement to the exec file, then the sandbox error is fixed but when I run the app, a function does not work in the app that calls the exec file: "zsh: illegal hardware instruction". If I try to run the exec file in terminal without any entitlment on it, it works perfectly.

Please help me fix both issues! I can fix the sandbox issue but not both.

Please see below everything i've tried to fix it, unless i'm doing it incorrectly, nothing seems to be working that was working in the past on other threads. Please please help!

I'm signing it with my Apple Development identity. I've tried signing with  the 3rd Party Mac Developer Application just to try but it sounds like I only use that when submitting to the Mac App Store. 

How I add entitlements to the exec file:
codesign --entitlements my.entitlements --deep -f -s "Apple Development: [myname] (devIDNumber)" myExecFile

How I verfiy the entitlment has been adding successfully: 
codesign -d --entitlements :- myExecFile 

Things i've tried to fix:
1) adding these to the exec file. These removes the sandbox error but then I get the "zsh: illegal hardware instruction" error.
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.inherit</key>
	<true/>
2) adding these to the exec file. Also added to the main app to just try. Sandbox error but exec works.
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
3) Wrapping the exec file in an embedded .app and adding these entitlements to the wrapped app and also tried to the exec file:
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.inherit</key>
	<true/>
4) tried this below link, same issue, can get the sandbox error to be remove but then the exec file does not run in the wrapped app:
https://medium.com/python-pandemonium/embedding-a-python-application-in-macos-d866adfcaf94

I will try anything. Please send your ideas...

**Comment by saiedg** [comment]
When running in xcode and calling the exec file, I get the error below: 
my.sh: line 2: 41382 Killed: 9               $1 $2 "$3" $4 "$5"

**Comment by rokm** [comment]
Hmm, can you look up the corresponding crash report in `Console` utility? That might help you narrow down the issue... (In Finder's menu, click `Go` -> `Utilities`, then open `Console`, and look for your app/executable under `Crash reports`.)

If I understand correctly, you have an app bundle (not generated by PyInstaller) that includes and calls a helper executable that was generated by PyInstaller (presumably in `onefile` mode?). Is that correct?

So you have two potential sources of problems; the signing/entitlements on the helper executable per-se, and signing/entitlements issues with PyInstaller-generated executable (and especially its collected embedded shared libraries):

1) Since you seem to have been trying different things, I assume you don't really know what entitlements you need on the helper executable, so you should first figure that out. Google search suggests you need `app-sandbox` and `inherit˙, but you should test that with an executable that was NOT generated by PyInstaller (e.g., compile a simple C-based hello world program). Once you have that working, you can move back to the PyInstaller-generated executable.

2) If your PyInstaller-generated executable in a `onefile` one, a very likely source of problems is that the collected dynamic libraries (which are stored in an archive that's embedded in the executable, and extracted to temporary directory when executable is ran) are not signed and/or do not have entitlements set. (I think crash report in `Console` utility should point that out). As those libraries are embedded in PyInstaller-specific archive format, there's no easy way to sign them in a post-processing step. But, we have a WIP PR that's attempting to add support for code-signing as part of the build process,
so you could try using the [`rokm:macos11-arm64-support-cleanup`](https://github.com/rokm/pyinstaller/tree/macos11-arm64-support-cleanup) branch from #5581 with newly-added `--codesign-identity` and `--osx-entitlements-file` command-line switches.
