### ISSUE TITLE
Pop-up/message "Could not read from file.fread: Invalid argument" at startup

### ISSUE THREAD

**Issue by Safihre** [pyinstaller/pyinstaller#5762]
## Description of the issue
Using PyInstaller 4.3 when starting the program I get a warning popup that says: `Could not read from file.fread: Invalid argument`. If build using console mode it's printed to the console.
This is not the case when I build the exact same program using 4.2.
The program does continue to run, so it doesn't seem to be fatal.

I added a `print("Start of program")` as the very first line (before any imports etc) of my `.py` file and this error is thrown before that:

```
C:\Users\safihre\Documents\GitHub\sabnzbd3\SABnzbd-3.3.0Beta1>.\SABnzbd-console.exe
Could not read from file.fread: Invalid argument
Start of program
```

I have no clue where to start looking for the problem.. Since it's thrown before my actual code runs.

## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.3
* Version of Python: 3.9.4
* Platform: Windows

We build on GitHub Actions, so it's always a clean environment with the latest versions of everything.
The PyInstaller build-log can be found here: https://github.com/sabnzbd/sabnzbd/actions/runs/777358419

Ref-issue: https://github.com/sabnzbd/sabnzbd/issues/1864

**Comment by rokm** [comment]
This is a regression that affects builds with external pkg (where `append_pkg=False` is set to `EXE()` in the spec). It is caused by full-file scan in 4.3, because even if .pkg is not included in the executable, the latter does in fact contain one MAGIC pattern - the buffer that stores the fixed string that's used for comparison... So we then attempt to interpret the subsequent data as TOC, which produces undefined behavior...

Will come up with counter-measure for this.

**Comment by Safihre** [comment]
@bwoodsend Is there any indication when a new version will be released that includes this fix?

**Comment by bwoodsend** [comment]
Umm, not really. Your guess it as good as mine.
