### ISSUE TITLE
Allow bundled packages to self-upgrade

### ISSUE THREAD

**Issue by elgalu** [pyinstaller/pyinstaller#5780]

**Comment by bwoodsend** [comment]
[Sigh!] We get this request a lot. It's never going to happen. It requires the application to overwrite itself which is:

1. A security threat.
2. Will hit PermissionErrrors on Windows because it won't let you write to a running executable or a mounted DLL.
3. Will cause seg-faults on Unix because it will let you pull the rug up from under its feet only to discover that it was still using it.

Also what's the point? To *upgrade* you simply delete the old copy and download the new one. Why complicate it?
