### ISSUE TITLE
prefix _MEIxxxx added to path on a directory created when it was up and running

### ISSUE THREAD

**Issue by githubcedrou** [pyinstaller/pyinstaller#5804]
## Description of the issue
I created dynamically a directory named **tmp**
I put a file in this directory to be sent through **send_file** (imported from **flask**)
https://flask.palletsprojects.com/en/1.1.x/api/?highlight=send_file#flask.send_file

the issue is that pyinstaller has taken the file from _MEIxxxx and put it as prefix.
D:\\\\Temp\\\\_MEI142562\\\\tmp/1.1.filename.jpg

but the correct path which put in send_file is tmp/1.1.filename.jpg

the problem is the same with/without using of encrypting in pyinstaller

I have used this command line : pyinstaller main.py -F --clean -n MYEXE --key=......

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.8.5
* Platform: Windows
*
* Did you also try this on another platform? Does it work there?
I have **no issue with 4.2** version. I downgraded to 4.2 and it is ok

**Comment by bwoodsend** [comment]
Code example please. And where is this image? Is it part of the application or is it given at runtime?

This is likely a knock-on effect of #5649 but the new behavior is correct so if your code used to work on PyInstaller 4.2 then your code is broken - it's relying on a bug.

**Comment by rokm** [comment]
This is indeed side-effect of #5649, because flask apps are usually instantiated as:
```python
app = flask.Flask(__name__)
```
which I assume takes the parent path from `__name__` to set its [`root_path`](https://flask.palletsprojects.com/en/1.1.x/api/?highlight=send_file#flask.Flask.root_path). In PyInstaller 4.3, this will properly resolve to `sys._MEIPASS` (in the OP example, `D:\\Temp\\_MEI142562`) while in earlier versions, it ended up empty and was probably interpreted as current working directory.

In any case, passing `tmp/1.1.filename.jpg` as relative path to `flask.send_file()` will cause it to be interpreted as relative to `root_path`, as per [docs](https://flask.palletsprojects.com/en/1.1.x/api/?highlight=send_file#flask.send_file). So as @bwoodsend  pointed out, this is not a bug, but correct(ed) behavior. 

If that is undesirable for some reason, you can try explicitly setting `root_path` to the current working directory (although it would probably be a better idea to use absolute paths in the first place).

**Comment by githubcedrou** [comment]
**Thank you for those answers and very quickly.**
Indeed, I changed relative path to absolute path and with 4.3, the processing is ok.

This ticket can be closed/rejected, it works as designed/expected
