### ISSUE TITLE
Error in hook-win32ctypes.core.py when using PyInstaller and Keyring in VS Code debug mode on Windows

### ISSUE THREAD

**Issue by colin-fsa** [pyinstaller/pyinstaller#5892]
## Description of the issue

This is very difficult to reproduce and I'm still not clear on the root cause, but in most cases the compilation will fail if the following are all true:

1. Calling PyInstaller from within a script (the error does not occur if I call it directly from a command line)
2. Running the compilation script in debug mode from within VS Code on Windows 10
3. The script being compiled must import keyring (I'm guessing the relevance is that keyring uses ctypes)

I suspect that VS code is cutting off the script being passed to the subinterpreter in _hook-win32ctypes.core.py_. The full script is _"""try:import cffi;print('\\nTrue')\nexcept: print('\\nFalse')"""_ but in the output it's showing up as _try:import cffi;print('\nTrue')_. Additionally, I can't successfully run this command from the command line, so I wonder how it's working at all:
_(test_env) c:\Development\testdir>python -c "try:import cffi;print('\\nTrue')\nexcept: print('\\nFalse')"
  File "<string>", line 1
    try:import cffi;print('\\nTrue')\nexcept: print('\\nFalse')
                                                              ^
SyntaxError: unexpected character after line continuation character_

Here are the contents of _hook-win32ctypes.core.py_:
```
from PyInstaller.utils.hooks import exec_statement, collect_submodules

# We need to collect submodules from win32ctypes.core.cffi or
# win32ctypes.core.ctypes for win32ctypes.core to work. The use of
# the backend is determined by availability of cffi.

cffi_available = exec_statement(
    """try:import cffi;print('\\nTrue')\nexcept: print('\\nFalse')"""
).split()[-1] == 'True'

if cffi_available:
    hiddenimports = collect_submodules('win32ctypes.core.cffi')
else:
    hiddenimports = collect_submodules('win32ctypes.core.ctypes')
```

The compilation seems to fail because the exec_statement call returns an empty string, so the slice throws up an IndexError. Although this isn't addressing the root issue, which seems to be VS code specific, I think we can fix the issue by wrapping the exec_statement line in a try statement so even the slice fails there won't be an uncaught exception.

### Context information (for bug reports)

* Output of `pyinstaller --version`: 4.3
* Version of Python: 3.7.10
* Platform: Windows 10 using VS Code 1.56.2
* How you installed Python: conda
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [N/A] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [See below] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

I don't think I can use the --debug flag since I'm calling PyInstaller.__main__, so I added --log-level DEBUG instead of --debug.

### A minimal example program which shows the error

**app.py**
```
import keyring

print("Hello!")
```

**compile.py**

```
from PyInstaller import __main__

if __name__ == '__main__':
    __main__.run(['app.py', '--log-level', 'DEBUG'])
```

### Stacktrace / full error message
24408 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\Users\\csche\\Anaconda3\\envs\\test_env\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
  File "<string>", line 1
    import sys; sys.path.insert(0, r'c:\Users\csche\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\lib\python\debugpy\_vendored\pydevd'); import pydevd; pydevd.PydevdCustomization.DEFAULT_PROTOCOL='http_json'; pydevd.settrace(host='127.0.0.1', port=64134, suspend=False, trace_only_current_thread=False, patch_multiprocessing=True, access_token=None, client_access_token='**removed**', __setup_holder__={'client': '127.0.0.1', 'client-access-token': '**removed**', 'json-dap-http': True, 'multiprocess': True, 'port': 64134, 'ppid': 16688, 'server': False, 'skip-notify-stdin': True}); try:import cffi;print('\nTrue')

 ^
SyntaxError: invalid syntax

**Comment by cscheriff** [comment]
Apologies, but I seem to have gotten mixed up between the pyinstaller hook and the one from pyinstaller-hooks-contrib. Pyinstaller's hook doesn't appear to be a problem, but pyinstaller-hooks-contrib's is. I'm not clear why the hook exists in both packages so it's not entirely clear to me what the correct fix is. Possibly we could remove the hook from pyinstaller-hooks-contrib, or at least sync it up to use can_import_module instead of exec_statement?

**Comment by rokm** [comment]
I think we duplicated the hook in both repositories because it was required by update to `keyring` hook (which is currently in main repository), which we were planning to transition into contrib repository (at some point...). But the version of `win32ctypes.core` hook in main repository was updated/revised once `can_import_module` was implemented.

The proper fix would be to move the `keyring` hook into contrib repository, remove the `win32ctypes.core` copy from the main repository, and update the copy in contrib to use `can_import_module`.

A bit less thorough fix would be only updating the contrib copy to use `can_import_module` (although that became available only with PyInstalelr 4.3).

**Comment by rokm** [comment]
Although on the other hand, if we're going to keep `keyring` hook in the main repository, we could delete the offending copy in contrib instead...

**Comment by cscheriff** [comment]
I'm happy to create a PR for either methodology, but I'm curious how the releases would be coordinated if we moved `keyring` into the contrib project. Wouldn't we then need to release both packages together since you'd need to use the new versions of both together or you'd lose the keyring hook?

**Comment by rokm** [comment]
@bwoodsend  and @Legorooj, can you weigh in on what the preferred approach would be for this (i.e., are we still planning to move keyring)?

**Comment by bwoodsend** [comment]
I certainly want it out. The problem with moving things to the hooks repo is that if `kering` provided its own hook via the `pyinstaller40` entry point, then it would have the same priority as the hooks repo which also uses said entry point so it'd be 50:50 which hook gets chosen. Personally, I think the fix for that is for the hooks repo not to be loaded via the entry point at all. As it's already labelled as a dependency of PyInstaller we should just `import` it normally and combine its hooks with those built into PyInstaller.

As for coordinating releases, we can make `pyinstaller-hooks-contrib>=x.y.z` a requirement of PyInstaller where `x.y.z.` is the version at which we add/fix the keyring hook so that it's impossible to install a combination with no hook.

**Comment by Legorooj** [comment]
Just move the hook into [the keyring repo](https://github.com/jaraco/keyring)?

**Comment by cscheriff** [comment]
@Legorooj - since the offending hook is the one for win32ctypes.core, wouldn't we actually need to move the hook into the [pywin32-ctypes repo](https://github.com/enthought/pywin32-ctypes)? I'm guessing the same issue could occur with libraries other than keyring which use ctypes under the hood. Win32ctypes hasn't had a release in a few years so I'm not sure how likely they would be to accommodate.

**Comment by colin-fsa** [comment]
Fixed by pyinstaller/pyinstaller-hooks-contrib#124. Thanks @rokm!
