### ISSUE TITLE
Sample project that is detect as virus or trojan on Windows

### ISSUE THREAD

**Issue by paulo-coutinho** [pyinstaller/pyinstaller#5932]
## Description of the issue

Hi,

After develop a sample project for the community (https://github.com/paulo-coutinho/pyinstaller-sample) and with github action build, i have some questions about deployment on Windows:

When i generate application with pyinstaller, windows detect it as a virus/trojan, so, there is any way to bypass it?

All binaries is on github action:
https://github.com/paulo-coutinho/pyinstaller-sample/actions/runs/949379852

Thanks.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.9
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? On other platform don't have this problem.

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

My simple sample is here:
https://github.com/paulo-coutinho/pyinstaller-sample

Download and execute:

```
pyinstaller "My App.spec"
```

### Stacktrace / full error message

```
Virus or trojan detected - Application was deleted.
```

**Comment by MikeKarnsTC** [comment]
Hi Paulo, 

I am on a missions to remove the false positives as well.

So far, I have made some progress, but unfortunately am still getting some false positives from virustotal.com

What I would recommend you do, is follow the instructions to build your own bootloader. This helps, but unfortunately I am still digging further.

Unfortunately they are false positives and the dev team is unlikely to provide any new insight because this issue has been covered extensively elsewhere.

**Comment by rokm** [comment]
> Unfortunately they are false positives and the dev team is unlikely to provide any new insight because this issue has been covered extensively elsewhere.

Indeed. See [every other issue on the topic](https://github.com/pyinstaller/pyinstaller/issues?q=label%3Aantivirus-false-positives). If you want to be 100% sure that bootloader executables are clean, rebuild them yourself instead of using pre-built ones. If you're still having problems after that, take it up with your AV vendor.
