### ISSUE TITLE
bin in Onedir mode can't run in path with dot

### ISSUE THREAD

**Issue by chenzhenyang** [pyinstaller/pyinstaller#5944]
I package in onedir mode in centos7
when i move the dir to that like /opt/HighGo4.5.6-see (with dot),the bin can‘t run.
it report can't find module /opt/HighGo4,the dot split the path.

![image](https://user-images.githubusercontent.com/6257021/123030184-f6347700-d414-11eb-85c1-f16dbf554bf1.png)

**Comment by bwoodsend** [comment]
Well I can see that that's not true generally so either you or one of your dependencies are doing something weird. Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by rokm** [comment]
While the problem indeed occurs when there is a dot in the path and does not when there is not, I don't think this is our bug.

Rather, this is a limitation of `pkgutil.iter_modules` which `patroni` uses in [PyInstaller-specific codepath](https://github.com/zalando/patroni/blob/master/patroni/dcs/__init__.py#L69-L74). 

The unfrozen version works because it avoids calling `pkgutil.iter_modules` altogether, but if it had called it and if you had a virtual environment with dot in its path, it would have failed in the same way.

**Comment by rokm** [comment]
Alright, so there's no direct way to resolve this issue.

I've submitted a fix to `patroni` (zalando/patroni#1994) which should take care of the issue with dot in the path in their `PyInstaller`-specific codepath. Until then, you can manually modify your local `patroni` installation in the same way as done in that PR.

We're also going to add support for `pkgutil.iter_modules` in `PyInstaller` (#5959), which will allow `patroni` to drop their `PyInstaller`-specific codepath. However, that will require both new release of `PyInstaller` and of `patroni`.

So I suppose for now, the only practical solution is to patch your local `patroni` installation.
