### ISSUE TITLE
Arrow keys in cmd library don't work properly under a set of very specific conditions

### ISSUE THREAD

**Issue by dogtopus** [pyinstaller/pyinstaller#6014]
## Description of the issue

The arrow keys and possibly other terminal features will not work properly if the packaged script matches the following condition:

- Packaged with `--onefile` under GNU/Linux (`--onedir` as well as no packaging works fine).
- Executed the packaged script under `root` (for `os.setuid()` and `os.setgid()` used in subprocess mentioned below).
- The script has a `cmd.Cmd` instance running in a **subprocess** created with `os.fork()`.
- The subprocess changes its own user and group to something other than `root` (it works fine if no change has been performed).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: 3.9.6
* Platform: GNU/Linux (Arch Linux)
* How you installed Python: pip
* Did you also try this on another platform? Does it work there?

No since I don't have any other \*NIX installations.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```python3
#!/usr/bin/env python3

# Run with sudo <executable_name> $USER
# Type something (like 'help') and try to use the arrow keys to browse the history.
# If packaged with --onefile, it will not work properly and the terminal shows ^[[A, ^[[B, etc.

import cmd
import os
import pwd
import sys

class TestShell(cmd.Cmd):
    intro = 'TestShell from subprocess.'

    def do_exit(self, _args):
        return True

if __name__ == '__main__':
    username = sys.argv[1]

    # Look up uid and gid for the specified username
    user_info = pwd.getpwnam(username)
    uid = user_info.pw_uid
    gid = user_info.pw_gid

    pid = os.fork()

    if pid > 0:
        print('Subprocess PID =', pid)

        # Wait for subprocess to exit
        try:
            os.waitpid(pid, 0)
        except OSError as e:
            if e.errno != errno.ECHILD:
                print('Subprocess does not exit properly.')
                raise

        print('Subprocess exited.')
        sys.exit()
    else:
        # Set the subprocess' uid and gid to another user
        os.setgid(gid)
        os.setuid(uid)
        TestShell().cmdloop()
        sys.exit()
```

### Stacktrace / full error message

No error reported.

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Hmm, that's an interesting one. Thanks for the sample and detailed descriptions of steps to reproduce the problem!

Unfortunately, the way things are set up amounts to digging your own grave, and there's nothing we can do about it. 

The arrows/history not working is the sign that `readline` library was not loaded. Because when you run `onefile` program as root, it unpacks its contents to the /tmp/_MEIXXXX directory, which is created with root as owner and -rwx------ permissions for security reasons. In the forked codepath, you switch the user to unprivileged one, and lose the access to temporary directory. So when you create `TestShell`, it fails to load `readline` library from the temporary directory.

If you really want to go with this design (`onefile` build started as root and then dropping to unprivileged user in forked codepath), you need to recursively chown `sys._MEIPASS` to the target user before changing uid/gid in the forked codepath. Although if the main executable is running as root, changing the ownership before forking should to the trick as well.

**Comment by dogtopus** [comment]
Thanks for the quick response. Yes it's sometimes easy to forget that `--onefile` is more or less just a glorified self extracting archive with argument passthrough and cleanup logic. Also noted the workaround.
