### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by BonaBeavis** [pyinstaller/pyinstaller#6054]
## Description of the issue

Running script installed with pyinstaller has an encoding issue, but runs fine standalone.

You can reproduce by:

```bash
curl https://raw.githubusercontent.com/oeg-upm/Chowlk/webservice/data/aio.xml --output aio.xml
docker run -it -v $(pwd):/test/ registry.gitlab.com/kupferdigital/ontoflow/chowlk bash
cd /test/
converter aio.xml ontology.ttl --type ontology --format ttl # Does not work
/root/Chowlk/converter.py aio.xml ontology.ttl --type ontology --format ttl # Does work
```

Error thrown is:
```
Traceback (most recent call last):
  File "converter.py", line 43, in <module>
  File "converter.py", line 17, in main
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 390: ordinal not in range(128)
```
Pyinstaller usage is [here](https://gitlab.com/kupferdigital/ontoflow/-/blob/main/images/chowlk/Dockerfile) and the script converted is [here](https://github.com/oeg-upm/Chowlk/blob/webservice/converter.py)

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.4```
* Version of Python: Python 3.8.10
* Platform:  ubuntu 20.04
* How you installed Python: apt
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X ] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

**Comment by rokm** [comment]
The problem here is a combination of locale settings in the target system (container) and inconsistent behavior between python interpreter and pyinstaller w.r.t. utf-8 mode.

The locale in the system is configured as POSIX, which makes default encoding `ascii` (`ANSI_X3.4-1968`):
```
root@d7fb2788d0e6:~/Chowlk# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

When `open()` is done in python without `encoding` argument, [preferred system encoding is queried](https://docs.python.org/3/library/functions.html#open) from the system via [`locale.getpreferredencoding`](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding). In a frozen application, `locale.getpreferredencoding` returns `ANSI_X3.4-1968` whereas when ran in python, it [returns `utf-8` regardless of locale setting because interpreter has UTF-8 mode enabled](https://github.com/python/cpython/blob/a22b05da87bdfb081d6aaecfce136ae8dbb8680c/Lib/locale.py#L660-L661).

So I guess we need to query `sys.flags.utf8_mode` at build time, and preserve that setting in our embedded interpreter (via bootloader flags).

**Comment by BonaBeavis** [comment]
Workaround is to set the locale inside the container, as described [here](https://leimao.github.io/blog/Docker-Locale/)
