### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'workalendar' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by Davidon3** [pyinstaller/pyinstaller#6071]
After checking on other Issues, I couldn't find a way to solve my error.

## Description of the issue
I'm having an error executing my main.exe file:
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "workalendar\__init__.py", line 5, in <module>
  File "pkg_resources\__init__.py", line 466, in get_distribution
  File "pkg_resources\__init__.py", line 342, in get_provider
  File "pkg_resources\__init__.py", line 886, in require
  File "pkg_resources\__init__.py", line 772, in resolve
pkg_resources.DistributionNotFound: The 'workalendar' distribution was not found and is required by the application
[8816] Failed to execute script 'main' due to unhandled exception!
```

I made the executable through:

`pyinstaller main_MRP_v0-1.py -D --additional-hooks-dir=hooks`

my hooks directory contains this file:

````
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('workalendar')
````

I also tried with a similar one:
````
from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all('workalendar')
````

But had the same result.

### Context information

* Output of `pyinstaller --version`: ```4.4```
* Version of Python: 3.7.8
* Platform: Windows
* How you installed Python: python.org/downloads

I'm still new on python, I need help in a newbie language

**Comment by rokm** [comment]
> my hooks directory contains this file:

What is "this file" called? Is it `hook-workalendar.py` or something else?

But either way, you can avoid using the hook and use `pyinstaller main_MRP_v0-1.py -D --copy-metadata workalendar` instead.

**Comment by Davidon3** [comment]
> What is "this file" called? Is it hook-workalendar.py or something else?

It's called hook-2-workalendar.py

> But either way, you can avoid using the hook and use pyinstaller main_MRP_v0-1.py -D --copy-metadata workalendar instead.

Thanks a lot! the workalendar issue is gone, now I have a brand new Error. I suppose there will be more like this.

```
ModuleNotFoundError: No module named 'pymssql._mssql'
[84864] Failed to execute script 'main_MRP_v0-1' due to unhandled exception!
```

How can I solve all of them at the same time?

**Comment by Davidon3** [comment]
Using a simpler version, I get a
`ModuleNotFoundError: No module named 'functions'`

I should import my custom modules in different ways?
When launch `python main_MRP_v0-1.py` everything works perfectly.
I have different versions of python and I don't have a pyinstaller.exe in the project folder. I added some paths, but maybe they're conflicting in some way?

**Comment by rokm** [comment]
> It's called hook-2-workalendar.py

Hooks need to be named `hook-modulename.py`, otherwise they don't get executed.

> Thanks a lot! the workalendar issue is gone, now I have a brand new Error. I suppose there will be more like this.
> 
> ```
> ModuleNotFoundError: No module named 'pymssql._mssql'
> [84864] Failed to execute script 'main_MRP_v0-1' due to unhandled exception!
> ```

This one should be solved by adding `pymssql._mssql` to hiddenimports, i.e., adding `--hiddenimport pymssql._mssql` to your PyInstaller command. Or, if there are more missing modules from `pymssql`, you can use `--collection-submodules pymssql` instead.


> Using a simpler version, I get a
> `ModuleNotFoundError: No module named 'functions'`

What is `functions`? If it is your custom module or a package, you need to ensure that it is visible to PyInstaller during the freezing process (i.e., either in PYTHONPATH, or explicitly passed to PyInstaller via `--paths`). But if it is placed next to your entry-point script, it should be picked up automatically, as long as your code explicitly imports it (you can try adding `--hiddenimport functions`, though).


> I have different versions of python and I don't have a pyinstaller.exe in the project folder. I added some paths, but maybe they're overlapping each other in some way?
> Can I paste a pyinstaller.exe in the project folder?

No, you need to ensure that PyInstaller is properly installed for the version of python that you are using. If you have multiple versions and/or environments installed, then figure out which one you're using and make sure everything (PyInstaller and 3rd party packages used by your code) are installed there. Running pyinstaller via `python3 -m PyInstaller` might be easier to debug than running `pyinstaller.exe`...
