### ISSUE TITLE
Generated Executable does not include module given in --hiddenimport tag 

### ISSUE THREAD

**Issue by awanga123** [pyinstaller/pyinstaller#6107]
I have a file called a.py that is a script that imports docopt that I need to freeze. I am using the command `pyInstaller a.py --onefile --hiddenimport=docopt`. Once finished I drag the file in the build folder into the terminal and run it and I get the following error: 
`Traceback (most recent call last):
  File "a.py", line 15, in <module>
ModuleNotFoundError: No module named 'docopt'
[32227] Failed to execute script a`

I am running this on MAC OS Big Sur and installed pyinstaller globally using pip. Specifically:
`54 INFO: PyInstaller: 4.3 
54 INFO: Python: 3.9.6
65 INFO: Platform: macOS-11.4-x86_64-i386-64bit`

I also just tried to use the command `pyInstaller a.py --onedir --hiddenimport=docopt`and without the hiddenimport tag and in both cases when I run the executable I still get that there is no module docopt

**Comment by bwoodsend** [comment]
The `build` folder is just for assembling your program. It's the executable in the `dist` folder you should be running and distributing.

**Comment by rokm** [comment]
> The `build` folder is just for assembling your program. It's the executable in the `dist` folder you should be running and distributing.

I don't think this is about running from `build` folder (especially in `onefile` mode)....

> Traceback (most recent call last): File "a.py", line 15, in <module> ModuleNotFoundError: No module named 'docopt' [32227] Failed to execute script a

If your program imports `docopt` in a straightforward way (`import docopt` or `from docopt import docopt`) and you get a module-not-found error in the frozen application, then `docopt` is installed under different python version (or virtual environment) than the one that `pyinstaller` shim/script is pointing to. 

Running pyinstaller as a module (e.g., `python3 -m PyInstaller [...]` instead of `pyinstaller [...]`) makes this a bit more obvious and easier to debug...
