### ISSUE TITLE
Packaged executables on macos do not work after signing

### ISSUE THREAD

**Issue by xurenda** [pyinstaller/pyinstaller#6131]
I want to use pyinstaller to build [ttc2ttf](https://github.com/yhchen/ttc2ttf/blob/master/ttc2ttf.py) as a single file executable, and I use:
```bash
pyinstaller -F ttc2ttf.py
```
The ttc2ttf single file executable was obtained and it works fine. But when I sign it(Mac OS programs require a signature):
```bash
codesign --force -s "Developer ID Application: XXX" -v "ttc2ttf" --deep --strict --options=runtime
```
It does not run anymore and reports the following error:
```bash
[22182] Error loading Python lib '/var/folders/k0/1wy74f6j5y1bckg56zrfz6dh0000gn/T/_MEIhfquJG/Python3': dlopen: dlopen(/var/folders/k0/1wy74f6j5y1bckg56zrfz6dh0000gn/T/_MEIhfquJG/Python3, 10): no suitable image found.  Did find:
	/var/folders/k0/1wy74f6j5y1bckg56zrfz6dh0000gn/T/_MEIhfquJG/Python3: code signature in (/var/folders/k0/1wy74f6j5y1bckg56zrfz6dh0000gn/T/_MEIhfquJG/Python3) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
```
I know the reason by the error message, because the ttc2ttf single file executable built by pyinstaller will release a python3 executable when it runs and delete it after execution.
But because my ttc2ttf program is signed and the released python3 program is unsigned or inconsistently signed, ttc2ttf does not work.
What should I do, can someone give some help? Thanks.

**Comment by rokm** [comment]
`--deep` argument to `codesign` means that all (eligible) files in an .app bundle should be signed. It has absolutely no effect on a PyInstaller-generated `onefile` executable, because `codesign` does not even know that PyInstaller exists. So with `onefile` executables, you can only sign the executable itself, and you have no means of post-hoc signing the collected binaries that are stored in executable-embedded archive and extracted to temporary directory when program is executed.

If you want to sign collected binaries using the real developer identity (as opposed to ad-hoc signing), try using PyInstaller's [`--codesign-identity`](https://pyinstaller.readthedocs.io/en/latest/usage.html#cmdoption-codesign-identity) switch and read [the documentation on this feature](https://pyinstaller.readthedocs.io/en/latest/feature-notes.html#macos-binary-code-signing).
