### ISSUE TITLE
Problem with .matplotlib user directory

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#617]
**Original date**: 2012/10/11
**Original reporter**: *avladev AND gmail DOT  COOM *

When run matplotlib it will create $HOME/.matplotlib folder in user directory. In this directory there is fontList.cache file which lists paths to matplotlib fonts.

-_For onefile distribution:_*

When you run your exe under WinXP for the first time it's extracted to for example "_MEIxxxxx" temp directory and fontList.cache file is created with fonts paths pointing to this directory.

Second time you run your exe new directory is created "_MEIyyyyy" but fontList.cache file still points to previous directory which is deleted

-_For onedir distribution:_*

Same thing is happening but there is no problem if you don't move your folder after first run

-_The error_*

`RuntimeError: Could not open facefile`

-_How to solve this:_*

Matplotlib uses MPLCONFIGDIR environment variable to search for configs if it's not found it try to read from .matplotlib dir if this dir is not found matplotlib creates it.
You can specify MPLCONFIGDIR in you application to bypass problem mentioned above. Notice that MPLCONFIGDIR does not accept relative paths for example "./configs/".

-_Working example:_*

`os.environ['MPLCONFIGDIR'] = os.getcwd() + "/configs/"`

Notice that MPLCONFIGDIR should be set before any matplotlib calls

I hope this will help other people with same problem and it will be good to add link in supported packages to this ticket.

**Comment by kr-ish** [comment]
@matysek I'm running into an issue I'm hoping you could answer-

I'm using pyinstaller with an app that uses matplotlib. When I run the frozen app on computers that have never run matplotlib before, the font cache is built every time the app is run since the config dir is written to a temporary directory as you have mentioned above. Should I be adding something to my spec file to avoid this? I would like the font cache in my frozen app to be built only once and not on subsequent calls to the application.

Thank you!
