### ISSUE TITLE
--noconsole or --windowed causing a read-only file system in the executable

### ISSUE THREAD

**Issue by owenThurm** [pyinstaller/pyinstaller#6231]
## Description of the issue

This is blocking, I can't use the --noconsole or --windowed flags (which I need) because they render the executable useless.

Compiling the executable with either of those flags results in an executable that throws an `OSError: [Errno 30] Read-only file system: my_file.txt` when I try to open `my_file.txt` in append mode (which is necessary for my application.)

However, compiling without either of those options yields an executable that works just fine, and is presumably **not** a read-only file system (even with the --onefile option, but without either the --noconsole or --windowed options, the executable works fine).  

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: 3.8.6
* Platform: OS X Big Sur
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? I have not tried this on another platform, I'm assuming this is a Mac-specific error.

Interested to hear any ideas/ why this would be happening. Thanks for any feedback! 🙏

**Comment by rokm** [comment]
> Interested to hear any ideas/ why this would be happening. 

It happens because when you generate an app bundle (which is what windowed mode does on macOS) and the bundle is not signed, macOS runs it isolated from a read-only temporary location. If I remember correctly, this is called "app translocation". (I *think* it is triggered by the lack of signature, but I could be wrong, and it is always triggered. It doesn't matter much in your case, because signature would preclude you from writing into the bundle anyway...)

So you'll need to move that `my_file.txt` outside of the app bundle itself, and look into options for storing user-persistent data on macOS.

**Comment by owenThurm** [comment]
Thank you for the quick reply @rokm, would that just be writing to some absolute path file outside of our bundle? 

Surely there must be a common workaround for this?

**Comment by rokm** [comment]
Yes, using an absolute path outside of bundle should do the trick. You should probably standard location for user data/config, which I think on macOS is `~/LIbrary/Application Support/<appname>/` (or at least, that's where `pyinstaller` puts its bincache).
