### ISSUE TITLE
Fails to start on M1: `Python: mach-o, but wrong architecture`

### ISSUE THREAD

**Issue by Safihre** [pyinstaller/pyinstaller#6235]
Due to #5762 we had our PyInstaller pinned to 4.2 for a long time, for our next release we unpinned the version and used `4.5.1`.
From the documentation I expected everything to go well, since unless specified it should just build the `x86` version just as before.
However, users have quickly reported errors when trying to run our application on M1 Mac's:
```
mediencenter@Mac-mini ~ % /Applications/SABnzbd.app/Contents/MacOS/SABnzbd 
[25667] Error loading Python lib '/Applications/SABnzbd.app/Contents/MacOS/Python': dlopen: dlopen(/Applications/SABnzbd.app/Contents/MacOS/Python, 10): no suitable image found.  Did find:
	/Applications/SABnzbd.app/Contents/MacOS/Python: mach-o, but wrong architecture
	/Applications/SABnzbd.app/Contents/MacOS/Python: stat() failed with errno=1
```
We hypothesize this maybe has to do with `SABnzbd` being "fat" while `Python` is only `x84`?
```
sander@witte2004:/media/sander/SABnzbd-3.4.0/SABnzbd.app/Contents$ file ./MacOS/SABnzbd
./MacOS/SABnzbd: Mach-O universal binary with 2 architectures: 
[x86_64:Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>] 
[arm64:Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>]


sander@witte2004:/media/sander/SABnzbd-3.4.0/SABnzbd.app/Contents$ file ./MacOS/Python
./MacOS/Python: Mach-O 64-bit x86_64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>
```

I tried to force the `target_arg` (https://github.com/sabnzbd/sabnzbd/commit/c5422e848190c80e72de0c630ef6c1af048d38e1), but this still did not work and still results in the `SABnzbd` binary being "fat". Build result [here](https://github.com/sabnzbd/sabnzbd/actions/runs/1255094244).

Additionally, users of old macOS versions have reported that it no longer works on their older macOS (10.12) versions.
To freeze our application we use Github Actions but specifically fetch the python.org version of Python [so that it supports macOS 10.9+](https://github.com/sabnzbd/sabnzbd/blob/develop/.github/workflows/build_release.yml#L86-L90).

Just setting PyInstaller back to 4.2 "fixes" both these problems.

All our build-logs are available on Github Actions, I can link to specific build logs if desired:
https://github.com/sabnzbd/sabnzbd/actions/workflows/build_release.yml
Spec file: https://github.com/sabnzbd/sabnzbd/blob/develop/builder/SABnzbd.spec

**Comment by rokm** [comment]
> We hypothesize this maybe has to do with `SABnzbd` being "fat" while `Python` is only `x84`?

Indeed. This shouldn't happen as we thin out the bootloader executable to the target architecture. Or at least, we're supposed to... But now I see that part of the pipeline [is bypassed](https://github.com/pyinstaller/pyinstaller/blob/54083110106d2c20e45364d1f98457880dcbd31e/PyInstaller/building/api.py#L663) when external PKG (`append_pkg=False`) is used.

> Additionally, users of old macOS versions have reported that it no longer works on their older macOS (10.12) versions.

That's because in newer releases, we build the bootloaders [with MACOSX_DEPLOYMENT_TARGET set to 10.13](https://github.com/pyinstaller/pyinstaller/blob/54083110106d2c20e45364d1f98457880dcbd31e/bootloader/wscript#L471). So if you want to support older versions, you'll need to download the sdist (or clone tag from git), build the bootloaders with MACOSX_DEPLOYMENT_TARGET set to custom target, and install pyinstaller from that. 

Building bootloaders yourself should also allow you to side-step the issue with fat bootloaders, as building them with `--no-universal2` will give you an x86_64-only bootloader that does not need to be thinned (it will also not build fat bootloaders if the toolchain does not support that in the first place).

**Comment by Safihre** [comment]
> Indeed. This shouldn't happen as we thin out the bootloader executable to the target architecture. Or at least, we're supposed to... But now I see that part of the pipeline is bypassed when external PKG (append_pkg=False) is used.

Ah yes, we could probably drop that and switch to using `MERGE` if I understand the documentation correctly.

> That's because in newer releases, we build the bootloaders with MACOSX_DEPLOYMENT_TARGET set to 10.13. So if you want to support older versions, you'll need to download the sdist (or clone tag from git), build the bootloaders with MACOSX_DEPLOYMENT_TARGET set to custom target, and install pyinstaller from that.

Isn't that something to put in the release notes? We can't be the only ones wanting to support older macOS versions..

**Comment by rokm** [comment]
> Isn't that something to put in the release notes? We can't be the only ones wanting to support older macOS versions..

The switch has supposedly already been done in 4.1:
> (OSX) Bump MACOSX_DEPLOYMENT_TARGET from 10.7 to 10.13. (#4627, #4886)

and since then, the main README does state that supported OSes are:
>  - Mac OS X 10.13 (High Sierra) or newer.

In practice, `MACOSX_DEPLOYMENT_TARGET` switch did not fully work (because it was overridden in several places), so pre-built bootloaders continued being built with old deployment target.

**Comment by Safihre** [comment]
Oke, I missed that part of the README. Good to know and thus expected behavior.

**Comment by rokm** [comment]
The issue with the executable not being properly pre-processed and post-processed in stand-alone PKG mode (`append_pkg=False` ) should be fixed now in both `v4` and `develop` branch.
