### ISSUE TITLE
The --splash --onefile must with "VCRUNTIME140.dll"

### ISSUE THREAD

**Issue by ozippo** [pyinstaller/pyinstaller#6284]
The --splash --onefile is work good on my computer, but the .exe file must run with VCRUNTIME140.dll on other computer. something wrong maybe.

**Comment by rokm** [comment]
> something wrong maybe.

Hmm, there actually is. Good job narrowing it down to missing `vcruntime140.dll`!

The problem is that `vcruntime140.dll` is required by the `tcl86t.dll` and `tk86t.dll` that are used for the splash screen. In `onefile` mode, the splash screen is shown before the embedded archive is fully unpacked, after the files declared as splash screen dependencies/requirements are extracted. But as `vcruntime140.dll` is not listed there, we are trying to load Tcl/Tk shared libraries without having extracted the embedded  `vcruntime140.dll`. Therefore, splash screen initialization needs a system-wide copy and fails when the `vcruntime140.dll` DLL is not installed on the target system.

So we need to add binary dependencies of Tcl/Tk shared libs to list of splash screen requirements so that they get extracted before we try to initialize the splash screen.

**Comment by CraigerCDT** [comment]
Glad to have found this thread - having the same problem.
I'm developing on a Winx64, using Python 3.8x32 (portabillity) and have the same issue as above.
I did find that adding the vcruntime140.dll to my inno setup script seems to fix it across target platforms, but it's kind of a janky way of fixing it, stuffing MS DLL files and stuff. But it does work!
