### ISSUE TITLE
Windows: --onefile package prefers Qt DLLs in PATH over the extracted folder

### ISSUE THREAD

**Issue by phw** [pyinstaller/pyinstaller#6297]
### Context information (for bug reports)

* Output of `pyinstaller --version`: 4.5.1
* Version of Python: 3.8.10
* Platform: Windows

## Issue

Having a PyQt5 app (MusicBrainz Picard) packaged in --onefile mode with PyInstaller 4.5.1. If you have Qt DLLs somewhere in your path that is incompatible with the bundled Qt, then this will be tried to load instead of the bundled ones.

Example:
- The current app is bundled with Qt 5.15.2. It launches fine if no other Qt DLLs are somewhere in the path
- I place a `Qt5Core.dll` for Qt 5.14.1 somewhere in the `PATH` or in the folder where my bundled EXE resides. Launching the app now gives me an error similar to the below:

   ```
   Traceback (most recent call last):
    File "scripts\pyinstaller\portable-hook.py", line 30, in <module>
    File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
    File "const\__init__.py", line 40, in <module>
    File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
    File "const\appdirs.py", line 23, in <module>
  ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
   ```

Things work as expected when not building in onefile mode. Probably because then the Qt DLLs end up next to the bootstrap EXE.

See also the discussion on https://tickets.metabrainz.org/browse/PICARD-2291

**Comment by phw** [comment]
Found out that this is somehow related to the Python version: The build onefile package works fine when using Python 3.7.9, but gives the wrong behavior with Python 3.8.10. So probably some change to how Python 3.8 finds DLLs to load? I assume PyInstaller is injecting the `_MEI*`  temporary directory somehow into the search path, maybe this ends up at different position?

**Comment by bwoodsend** [comment]
@rokm will hopefully be able to confirm or correct me here but I believe that's due to how Windows works rather than anything PyInstaller does. Windows lacks the `--rpath` functionality that Unix has to ensure that each DLL is able to find its dependencies - rather it just searches `PATH` for anything with the right name and loads that. PyQt (PyInstaller or normal Python), on initialisation has to add its own DLLs to `PATH` before loading them so, if you already have a file named `Qt5Core.dll` in `PATH` then there's no way to ensure that the correct copy is loaded. Normally the rule is that the first found is loaded but, [given that we already prepend instead of append to `PATH`](https://github.com/pyinstaller/pyinstaller/blob/1e6a8d53f150cf24b574c32085f3745cbd2afaa6/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py#L28), that doesn't seem to be the case.

**Comment by phw** [comment]
That's not entirely true, Windows does not take just a random location from PATH but searches the PATH in order, and you can get Windows to load DLLs shipped with your software. Otherwise distributing any software on Windows would probably totally fail most of the time :D

In this case things work correctly with Python 3.7 and I assume earlier (because the issue never was reported before), but fails with Pythin 3.8. So something must have changed on this side. I'm just not yet sure what exactly this is.

**Comment by phw** [comment]
It looks like the change to the search PATH in the hooks is for some reason to late. Following situation:

Case1: I have my `PATH` set so the first entry points to a directory `dll-broken`  which contains incompatible Qt5 DLLs. Launching the onefile build fails while trying to load the Qt libraries as described above.

Case2: I set my `PATH` to have `.\dll-fixed;.\dll-broken`, that means there is still the entry to the directory with incompatible Qt5 DLLs, but before that I add another directory with compatible DLLs. The onefile build launches correctly.

That means in general setting `PATH` so that the `_MEI` folder is first would be correct, but for some reason since using Python  3.8 this happens too late.

**Comment by rokm** [comment]
The DLL search order on Windows corresponds to order of paths in `PATH`, from left to right. That's why it is important that custom launchers prepend their application's DLL path rather than append it; otherwise, they might end up with eponymous DLLs from another directory that also happens to be in the `PATH`...

---

Either way, the problem here is a result of both how `PyInstaller` works and how `picard` works.

First, on Windows, PyInstaller's bootloader does *not* modify `PATH` (in contrast to for example Linux, where [`LD_LIBRARY_PATH`](https://github.com/pyinstaller/pyinstaller/blob/1e6a8d53f150cf24b574c32085f3745cbd2afaa6/bootloader/src/pyi_utils.c#L838-L839) is explicitly set). Instead, we manipulate the search path via this [`SetDllDirectoryW`](https://github.com/pyinstaller/pyinstaller/blob/1e6a8d53f150cf24b574c32085f3745cbd2afaa6/bootloader/src/pyi_main.c#L167) call. Presumably this is done so that the executable search path (e.g., for non-bundled 3rd party binaries) is unaffected - but on the other hand, it could also be an oversight...

Second, the `PATH` is modified by the [PyQt5 runtime hook, which prepends `sys._MEIPASS`](https://github.com/pyinstaller/pyinstaller/blob/1e6a8d53f150cf24b574c32085f3745cbd2afaa6/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py#L27-L28).  Why is this necessary - after all, the DLLs are collected into sys._MEIPASS and could be resolved without this? Because PyQt5 explicitly tries to set the search path for its DLLs:

<details><summary>
<code>__init__.py</code> from <code>PyQt5</code>:
</summary>
<p>

```python
# Copyright (c) 2021 Riverbank Computing Limited <info@riverbankcomputing.com>
# 
# This file is part of PyQt5.
# 
# This file may be used under the terms of the GNU General Public License
# version 3.0 as published by the Free Software Foundation and appearing in
# the file LICENSE included in the packaging of this file.  Please review the
# following information to ensure the GNU General Public License version 3.0
# requirements will be met: http://www.gnu.org/copyleft/gpl.html.
# 
# If you do not wish to use this file under the terms of the GPL version 3.0
# then you may purchase a commercial license.  For more information contact
# info@riverbankcomputing.com.
# 
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.


# Support PyQt5 sub-packages that have been created by setuptools.
__path__ = __import__('pkgutil').extend_path(__path__, __name__)


def find_qt():
    import os, sys

    qtcore_dll = '\\Qt5Core.dll'

    dll_dir = os.path.dirname(sys.executable)
    if not os.path.isfile(dll_dir + qtcore_dll):
        path = os.environ['PATH']

        dll_dir = os.path.dirname(__file__) + '\\Qt5\\bin'
        if os.path.isfile(dll_dir + qtcore_dll):
            path = dll_dir + ';' + path
            os.environ['PATH'] = path
        else:
            for dll_dir in path.split(';'):
                if os.path.isfile(dll_dir + qtcore_dll):
                    break
            else:
                return

    try:
        os.add_dll_directory(dll_dir)
    except AttributeError:
        pass


find_qt()
del find_qt
```

</p>
</details>

As we can see, it tries to find `Qt5Core.dll`. First, next to the `sys.executable` (it finds it there in `onedir` mode, so that's end of the story there). In `onefile`, it then tries `sys._MEIPASS/PyQt5/Qt5/bin`, but that does not exist because we collected the DLL into `sys._MEIPASS`. Finally, it tries each entry in the `PATH` (which is how that rogue DLL is pulled in. Also note that it uses `os.add_dll_directory()` to add DLL directory to search path - this was introduced in python 3.8, which is why as per OP the rogue DLL directory is not causing problems under python 3.7, but it is under python 3.8). Now in the above version of the file (from 5.15), nothing happens if the DLL is not found - but looking at the discussion in #4293, I think older versions of PyQt5 raised an error, and therefore the rthook is adjusting `PATH` to ensure that the DLL is found (it seems that 5.12, for example, did not check the parent of `sys.executable`).

Alright, so effectively, we end up prepending `sys._MEIPASS` to `PATH`, and all is well. If I create a sample `PyQt5` `onefile` application, it runs correctly no matter if other Qt5 DLLs are in `PATH`...

So why does it not work for `picard`? Because they have a custom runtime hook, `portable-hook` that happens to run before our `PyQt5` hook, *and* ends up importing `PyQt5` (it imports `import picard.const.appdirs`, which imports `PyQt5.Core`). So the observation that "setting `PATH` happens too late" is correct. 

I'm not sure how the order of runtime hooks is determined. But it seems that both `picard`-provided hooks, `win-console-hook` and `portable-hook` are added to TOC before our runtime hooks, whose order *probably* corresponds to order in which packages were discovered, which might be non-deterministic itself...

---

So the proper solution for this would be a mechanism that executes package-bound runtime hooks the first time the package is imported (as suggested here: https://github.com/pyinstaller/pyinstaller/issues/6198#issuecomment-917617051).

But in the meantime, `picard` could also work around this by prepending `sys._MEIPASS` to `PATH` in their runtime hook if neccessary (or avoid importing `PyQt5` from there).

**Comment by phw** [comment]
Awseome, thanks a lot for the detailed analysis. Yes, indeed, setting the PATH already in the hook fixes the issue.

> But in the meantime, `picard` could also work around this by prepending `sys._MEIPASS` to `PATH` in their runtime hook if neccessary (or avoid importing `PyQt5` from there).

Yes, manipulating the PATH in the hook is what I'll do for now. Picard was doing this anyway also (I think that came from before it was done in PyInstaller), but that also ran later. Actually that PyQt5 gets imported in this hook is also an unintentional change and we should get rid of that as well.

**Comment by phw** [comment]
One mystery for me remains, but that's more of a question:

So things are now resolved when the rogue DLLs are somewhere in the path (by fully avoiding Qt5 getting loaded in the hooks already). But there is also the special case that  the rogue DLLs are in the same directory as the bundled .EXE. In this case it still fails (this time later, when all hooks have been run and actual app gets executed).

Now on Windows it is common that DLLs are first looked for next to the EXE (and you also showed how PyQt5 actively looks next to `sys.executable`), so I actually expect this to happen. *But* with Python 3.7 this did also not happen, having incompatible DLLs next to the onefile EXE was working fine, the DLLs seemingly being ignored.

I just don't understand why there is that difference? Is `sys.executable` set differently?

**Comment by rokm** [comment]
I think this behavior can also be explained by what I wrote above. The `__init__.py` from `PyQt5` looks for `Qt5Core.dll` in following locations (in the listed order of precedence):
* next to `sys.executable`
* `Qt5/bin` directory in the directory where the `__init__.py` file would be (so `sys._MEIPASS/PyQt5/Qt5/bin`)
* in all `PATH` entries

So if you place an incompatible DLL next to `onefile` executable, it will be picked up due to the first bullet point.

The difference between python 3.7 and 3.8 is that the former does not have `os.add_dll_directory()`, so even if the DLL is found in both cases, the 
```python
    try:
        os.add_dll_directory(dll_dir)
    except AttributeError:
        pass
```
block is essentially a no-op in python 3.7 and search path is not modified. In python 3.8, this does modify the search path, and therefore incompatible DLLs are picked up.

**Comment by phw** [comment]
Right, that's the reason. So basically the PyQt5 mechanism is failing with Python < 3.8, and it just works because PyInstaller also manipulates the PATH.

Allright, thanks for all the insights and the detailed explanation. From my side this is solved, I don't see a todo for PyInstaller here :)

**Comment by bwoodsend** [comment]
Ahh what would we do without Rok...

I suppose this is another case for loading runtime hooks *just in time* (on first import) instead of loading all of them (in undefined order) on startup. That way the code flow would be:
* Bootloader unpacks and launches
* Run the mandatory runtime hooks to set up PyInstaller's frozen importer
* Start the entry point script ([tagger.py](https://github.com/metabrainz/picard/blob/94a9d7e1db0636cd55d64a36cac88d290de74c0c/picard/tagger.py))
* On seeing `import PyQt5`, the FrozenImporter can load the PyQt5 runtime hook before loading and returning PyQt5 itself. Or even if it saw an `import picard` first and tried to load the `portable-hook.py` first, `portable-hook.py`'s own (indirect) importing of PyQt5 would trigger the runtime hook for PyQt5 so that it is impossible to load PyQt5 before its runtime hook.
