### ISSUE TITLE
EXE start up slow on MacBook Air (M1, 2020)

### ISSUE THREAD

**Issue by YohannLeee** [pyinstaller/pyinstaller#6309]
## Description of the issue
The exe file generated by `pyinstaller -F test.py` starts up on intel mac book fast, on all M1 Mac book slowly(delay about 3 seconds)
**Starts up fast on**
MacBook Pro (13-inch, Mid 2012),Catalina 10.15.5
MacBook Pro (13-inch, 2019), Big Sur 11.5.2
MacBook Air (13-inch, 2017), Mojave 10.14.6
Mac mini (late 2014), Mojave 10.14.6
Mac mini (2018), Big Sur 11.2
**Starts up slow on**
MacBook Air (M1, 2020), 11.5.2
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: 3.9.5
* Platform: OS X
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there? Tried on other mac book.

### A minimal example program which shows the error

```
#! /usr/bin/env python3
# -*- coding: UTF-8 -*-

# python v3.9.5

print("program start")
print("program end")

```

**Comment by YohannLeee** [comment]
Tried on 5x M1 Mac Book Air, slowly on them all.

**Comment by bwoodsend** [comment]
Slow startup is usually due to macOS's notarisation *phoning home* to check if the software you are running has ever been reported as malware to Apple. I believe that Apple stepped up the security hoops we have to jump through to deploy on M1 and that buying and applying a codesign certificate from Apple is supposed to mitigate this but don't quote me on either of those.

Am I right in saying that if you build in onedir mode, it starts up slowly the first time but subsequent runs are fast?

**Comment by rokm** [comment]
> The exe file generated by `pyinstaller -F test.py`

This looks like `onefile` build, which will be even slower, as it needs to unpack on each run, *then* undergo the security check...

**Comment by jankais3r** [comment]
Can you check the architecture of the output executable? If it's x86-64, then the slow start could be due to Rosetta 2 translation layer.

**Comment by jiayouzl** [comment]
I have encountered the same problem as you. Have you solved it? How? Thank you
