### ISSUE TITLE
please make path separator os-independent (don't use os.pathsep)

### ISSUE THREAD

**Issue by rpodgorny** [pyinstaller/pyinstaller#6320]
**Is your feature request related to a problem? Please describe.**
currently, we're bundling our programs for both windows and linux (and possibly others in the future). python itself handles the path-related stuff on both platform quite well and in unified way (we use forward slashes everywhere etc.)... unfortunately, our bundling scripts have to be full of "detect os and define" ugly stuff such as this:

```
if IS_WINDOWS; then
  SEP=";"
else
  SEP=":"
fi

pyinstaller --some-options --add-data "some-data${SEP}some-dir" program.py
```

**Describe the solution you'd like**
making the separator handle both ; and : or choose one of them to be THE separator. using any of these characters in filenames on any of the systems smells like trouble, anyway do i don't think it would be a big problem if users were forced to escape it should they really need it...

...thanks for consideration!

**Comment by bwoodsend** [comment]
Use the .spec file instead then - that's what it's for! Although I do agree that our current `os.pathsep` separator is horrible.

> making the separator handle both ; and : or choose one of them to be THE separator.

If we were to do this I think that we'd have to use Windows's separator - Windows's cmd's support for quoting and escaping is terrible so we'll have to mollycoddle it and leave the Unix users to `\` escape any `;` characters they have (which I'd by very surprised if there are any).

**Comment by Legorooj** [comment]
Yes, we were using `os.pathsep` because of shell escaping issues. On this topic though, I have a better idea - why use any path separator? We can just change how PyInstaller accepts the arguments. Make `--add-data "src_file.png" "dest_dir"` the way we do it. Thoughts?

**Comment by bwoodsend** [comment]
> Yes, we were using `os.pathsep` because of shell escaping issues. On this topic though, I have a better idea - why use any path separator? We can just change how PyInstaller accepts the arguments. Make `--add-data "src_file.png" "dest_dir"` the way we do it. Thoughts?

My only issue with this is that it's less self diagnosable by which I mean that the use of a separator made it easy to catch when a user naively only passes a source argument rather than a source dest pair. If we make `--add-data` take two arguments then:
```
pyinstaller --add-data /path/to/source/only your-code.py
```
will interpret `your-code.py` as the destination folder then raise an obscure `pyinstaller: error: the following arguments are required: scriptname` error.

The situation is better if some other flag is used in between the `--add-data` and the entry point script:
```
pyinstaller --add-data /source/only --hiddenimport foo your-code.py
```
doesn't interpret `--hiddenimport` as the destination folder so the error message correctly blames the `--add-data`'s missing second parameter. 

Personally I don't think that this is important enough a drawback to block the change but I wanted to flag it up anyway.

**Comment by Legorooj** [comment]
True, this could cause some confusion. However we might also be able to add validation to the parameters for `--add-data` which give a more useful error. (eg, pass in something ending with `.py`/`.pyw`/`.spec` and error out with a nice message).

**Comment by rokm** [comment]
> However we might also be able to add validation to the parameters for `--add-data` which give a more useful error. (eg, pass in something ending with `.py`/`.pyw`/`.spec` and error out with a nice message).

I don't think that's a good idea. Collecting .py files as data files is completely valid when a package requires it for whatever reason. And .spec extension is also general enough that it does not necessarily mean pyinstaller's spec file...

Also, I think I would prefer single-string arguments for `--add-data`. But we could perhaps introduce an additional separator (e.g., '=>') with a note that it requires argument to be quoted. Then user could decide if they want to keep using `os.pathsep` or `'=>'`.

**Comment by Legorooj** [comment]
> I don't think that's a good idea. Collecting .py files as data files is completely valid when a package requires it for whatever reason. And .spec extension is also general enough that it does not necessarily mean pyinstaller's spec file...

I meant as the second argument only, which is a directory name.

**Comment by bwoodsend** [comment]
I'd quite like to get this done before the v5 release (which should be soon). Any last votes for any of the separators? In my mind, I'd rather avoid the *`--add-data` takes two arguments* option just because it's such a breaking change. Then I'd say I'm slightly more in favour of making both `;` and `:` separators on all platforms than adding the `=>` separator but there's not a lot in it.

**Comment by rokm** [comment]
> Then I'd say I'm slightly more in favour of making both `;` and `:` separators on all platforms

Having `:` as a separator on Windows will require extra care for handling of drive-letter part, e.g., `c:\parent\path\file:parent\path`. I suppose we could make `;` also work as a separator on non-Windows OSes, but it will require quoting (then again, whatever separator we come up with will). But I think if we make one of these universal, then we should make the other one as well, otherwise this will be a source of additional confusion (i.e., semi-colon always works, but colon does not work on Windows). And we need for both to keep their original behavior, as I don't think this warrants breaking backwards compatibility.

In that sense, I'd prefer to have the new universal behavior tied to a new separator (`=>`), whereas `os.pathsep` keeps its original behavior.

**Comment by rokm** [comment]
But on the other hand, I guess if we can make both colon and semi-colon universal, that might be less of a hassle for users, because they can mix them up without repercussions.

**Comment by bwoodsend** [comment]
> Having : as a separator on Windows will require extra care for handling of drive-letter part, e.g., c:\parent\path\file:parent\path.

Ah yes. That pretty much seals my mind on wanting the `=>` option.

**Comment by RussNelson** [comment]
What about using a list instead of a string, where each element of the list is a component of the path. On the one hand, it seems like you would have to type this: ["C:","Users","Nelson","AppData","Local"] but you could just type this, as a trope:
"C:/Users/Nelson/AppData/Local".split("/"). Then it's as readable as a string, but also unambiguous.

**Comment by bwoodsend** [comment]
I think you're missing the intention of this topic. We're not looking to replace the slashes (backwards or forwards) in `C:/Users/Nelson/AppData/Local"` - we're looking to replace the `:`/`;` separating the two file paths provided to PyInstaller's `--add-data`/`--add-binary` option.

**Comment by RussNelson** [comment]
Which is fine, but my suggested solution still applies. Python has a perfectly fine system for expressing metadata like this.

**Comment by bwoodsend** [comment]
You mean like this:
```
--add-data ["C:\path\to\source","path\to\dest"]
```
That doesn't survive shell interpretation. In bash, those quotes are stripped so for all intents and purposes, you might as well just use the comma as a delimiter and drop the square brackets since they add nothing to help.
```bash
$ printf '%s\n' --add-data ["C:\path\to\source","path\to\dest"]
--add-data
[C:\path\to\source,path\to\dest]
```
Then in powershell, it's the same except that closing square bracket is its own argument for some bizarre reason:
```powershell
printf '%s\n' --add-data ["C:\path\to\source","path\to\dest"]
--add-data
[C:\path\to\source,path\to\dest
]
```
If we were determined, we could ask everyone to wrap the whole thing in single quotes which would fix the two above but then break `cmd` because it interprets single quotes literally.

The whole purpose of this issue is to pick a syntax than can be used in any shell/operating system.

**Comment by RussNelson** [comment]
Oh, no, no, it's much uglier than that:

--add-data [["C:","path","to","source"]["path","to","dest"]]

Or, if you use the trope:

--add-data[ "C:/path/to/source".split("/"), "path/to/dest".split("/")]

**Comment by bwoodsend** [comment]
Again though, the shell mucks it up. Quotes disappear and fish and powershell interpret the `()` as a subcommand/substituion.
```powershell
> printf '%s\n' --add-data [["C:","path","to","source"]["path","to","dest"]]
--add-data
[[C:,path,to,source
]
[path,to,dest
]
]
```

```powershell
 printf '%s\n' --add-data[ "C:/path/to/source".split("/"), "path/to/dest".split("/")]
--add-data[
C: path to source,
path to dest
]
```
That resultant mess is all that PyInstaller's CLI parser will be able to see - not what the user actually wrote.
