### ISSUE TITLE
Wrong path when opening file (mac)

### ISSUE THREAD

**Issue by ciroartz** [pyinstaller/pyinstaller#6335]
Hello,

I'm on the latest pyInstaller version and I can compile the app with no issue, however, when I run the exe, it looks like the application is being opened from the /User/myusername directory instead of the actual folder which I'm opening it from.

When I compile on Windows it works perfectly, on Mac however I am having the issue mentioned above. 

I'm currently using this command to compile: 

pyarmor pack -s main.spec -e " --onefile --icon favicon.ico" --with-license licenses/r001/license.lic main.py

Python Version: 3.8.10

**Comment by rokm** [comment]
> pyarmor pack -s main.spec -e " --onefile --icon favicon.ico" --with-license licenses/r001/license.lic main.py

Sidenote: if this is equivalent to running pyinstaller against existing .spec file, then passing those extra options (`--onefile --icon favicon.ico`) will have no effect (since they affect only generation of .spec file itself). I'm not familiar with `pyarmor` though, so if it re-generates the .spec, then disregard this.

> when I run the exe, it looks like the application is being opened from the /User/myusername directory instead of the actual folder which I'm opening it from.

What exactly does "opening application" mean in this context? Running it from the terminal? Double-clicking it in the UI? Is this a regular (POSIX) executable or an .app bundle?

**Comment by ciroartz** [comment]
I ended up fixing it by specifying the current working directory in the code. Yes I meant both, by double clicking the ui and from the terminal. It is a a regular executable yes.
