### ISSUE TITLE
make windows loader UAC compliant

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#636]
**Original date**: 2012/11/30

We should make the windows bootloader UAC (User Account Control) compliant.

From Vista onwards Microsoft has been using security technology called User Account Control (UAC) which aims to prevent malware execution.

Microsoft strongly suggest making all application UAC compliant as in future Windows releases applications without manifest will not be able to run with elevated rights at all.

For details look at http://bojan-komazec.blogspot.cz/2011/08/how-to-make-your-application-uac.html

**Comment by htgoebel** [comment]
@mementum Does your pull-request #149 also solve this issue?

**Comment by mementum** [comment]
Pull Request #149 covers this for the "onefile" option because the UAC information is in the manifest which is embedded in the executable.

The UAC information is for the entire executable. The windows loader starts, loads the python interpreter and this executes the different python modules from the carchives. The entire process is covered by the initial uac permission granted by the end user (depending on the level of uac set in the control panel)

In "onedir" the manifest is placed along the executable which also covers the situation (the file could always be deleted)
