### ISSUE TITLE
ModuleNotFoundError: No module named 'faster_than_requests.faster_than_requests'

### ISSUE THREAD

**Issue by caioluccas** [pyinstaller/pyinstaller#6365]
**Pyinstaller Version:** `3.7`
**Python Version:** `3.9.6`
**OS:** `Windows`

I have compiled my program to .exe and now its returning this error ModuleNotFoundError: No module named 'faster_than_requests.faster_than_requests', if i run without compile it works normally, any idea what it might be?

PyInstaller Command: `pyinstaller --noconfirm --onedir --console "C:/path/archive.py"`

**Comment by bwoodsend** [comment]
Either you need to `--hiddenimport=faster_than_requests.faster_than_requests` it in or your mixing up virtual environments.

**Comment by rokm** [comment]
The `nim`-compiled extension module is placed into `<prefix>\site-packages\faster_than_requests\__pycache__` where PyInstaller cannot pick it up.

Try copying 
`<prefix>\site-packages\faster_than_requests\__pycache__\faster_than_requests.pyd`
to
`<prefix>\site-packages\faster_than_requests\faster_than_requests.pyd`
and rebuild your program.

(If you expect the extension to be rebuilt often for whatever reason, then instead of copying it from `__pycache__`, you could also ensure it is collected to `faster_than_requests\faster_than_requests.pyd` via `--add-binary` or corresponding spec file option).

You might need to ensure that the DLLs are also collected, but the module import per-se seems to work without that...
