### ISSUE TITLE
pymssql

### ISSUE THREAD

**Issue by yvespayette** [pyinstaller/pyinstaller#6376]
Using Python 3.9.5, pyinstaller 4.7 , new MEI folder (none before)

with the --onefile command, have the following problem.

warning that DOES NOT occur with the --onedir command:

**WARNING: file already exist but should not:  ..\..\_MEIxxxx\pymssql\_mssql.cp39-win_amd64.pyd**  
and same warning for _pymssql.cp39-win_amd64.pyd  

Why the Bootloader tries to verify twice the same file it just created?

**Comment by rokm** [comment]
> **WARNING: file already exist but should not: ...._MEIxxxx\pymssql_mssql.cp39-win_amd64.pyd** and same warning for _pymssql.cp39-win_amd64.pyd
> 
> Why the Bootloader tries to verify twice the same file it just created?

This usually means that the file was collected into the `onefile`-embedded archive twice, and the bootloader is displaying the warning when it is trying to extract the second copy over the first one. One (but perhaps not the only) way this can happen is if an entry ends up being added both via `binaries` and via `data`.

> warning that DOES NOT occur with the --onedir command:

That is expected, because `onedir` builds collect files into directory instead of embedded archive, so even if there are duplicate entries to be collected, the bundle ends up with only one copy (as the last one overwrites the previous one(s)).

----

That said, are you collecting those files yourself (considering the support for recent versions of `pymsssql` was added in pyinstaller/pyinstaller-hooks-contrib#315 that hasn't been a part of a release yet; and without that, you need to deal with missing `pymssql._mssql˙ yourself). If so, what exactly are you doing?

**Comment by yvespayette** [comment]
I did:   --hidden-imports="pymssql" --collect-all = "pymssql"  :  without it, the  .exe does not work.

Made me realized and I changed it to --collect-submodules="pymssql"   and the warning was removed.

I am testing if pymssql is working properly.

**Comment by rokm** [comment]
Yeah, using `--collect-all` is the problem here; it does both `collect_submodules` (which picks up the .pyd file as extension) and `collect_data_files` with `include_py_files=True`, which collects another copy of .pyd file as data file. 

In your case, `--collect-submodules` (or even just adding `pymssql._mssql` to `hiddenimports`) should suffice. Or, if you update contrib hooks to git `master` via `pip install git+https://github.com/pyinstaller/pyinstaller-hooks-contrib.git`, it should work out of the box.
