### ISSUE TITLE
change pyinstaller temp directory 

### ISSUE THREAD

**Issue by rstudiocode** [pyinstaller/pyinstaller#6377]
Hello, I noticed that when pyinstaller creates an .exe file, it first stores it in a temporary folder before putting it in the output folder. I would like to know how to change the location of this temporary folder. Indeed, my antivirus incorrectly detects the file created in the temporary folder and quarantines it. this error results: 
![image](https://user-images.githubusercontent.com/63545838/142468831-354f41cc-a18f-4cac-920e-6a6045fe3605.png)

I could very well add an exclusion to the C: \Users\Alexa\AppData\Local\Temp\folder
but it could be dangerous for the computer. So I would like to make sure that the temporary folder is created in C: \ Users \ Alexa \ Downloads \ tempor
To avoid risks: this folder would be only devoted to pyinstaller temp files. I would add an exclusion only for this folder.
Thanks in advance for your answer.

**Comment by bwoodsend** [comment]
auto_py_to_exe is responsible for that temporary folder - not PyInstaller. It would have preferred to put it in your current working directory so that it can cache unchanged steps and you can see its (admittedly near useless) diagnostics reports. So take it up with auto_py_to_ex.

But in all honesty, once you've got that folder accepted you'll probably end up fighting your antivirus again over your built application so I'd strongly recommend either turning that antivirus off completely or replacing it with a better one (i.e. one that actually scans for malicious code rather than looks up checksums in the global threat intelligence database).
