### ISSUE TITLE
Pyinstaller Broked my script

### ISSUE THREAD

**Issue by Kolhax** [pyinstaller/pyinstaller#6397]
So i made a py script,
when i compiled it and start it it says:
![image](https://user-images.githubusercontent.com/92904192/143816956-c3364586-311f-4ebb-a0f8-90fcfdd6d7e6.png)

**Comment by Kolhax** [comment]
[Compiling Logs.txt](https://github.com/pyinstaller/pyinstaller/files/7615936/Compiling.Logs.txt)

**Comment by Kolhax** [comment]
NOT INSTALLED FROM MS-STORE,
Downloaded from python.org

**Comment by bwoodsend** [comment]
Too lazy to fill out the issue template huh?

**Comment by rokm** [comment]
FWIW, you are using an OpenCV version that is not supported by PyInstaller; either OpenCV compiled from source, or PyPI wheel for OpenCV 4.5.4.58. 

If you are using PyPI wheel, you will need to either downgrade to 4.5.3.56 (which should work out-of-the-box) or upgrade to 4.5.4.60 (and make sure that you have the latest version of `pyinstaller-hooks-contrib`, 2021.4, installed). 

The source-compiled OpenCV is not supported, but you can probably work around the issues with loader by adjusting the search path so that extension module is collected directly collected in place of the loader - see pyinstaller/pyinstaller-hooks-contrib#110 and #4564.
