### ISSUE TITLE
Option to not bundle bytecode into the executable

### ISSUE THREAD

**Issue by josnyder-rh** [pyinstaller/pyinstaller#6406]
**Is your feature request related to a problem? Please describe.**
I really love PyInstaller because it allows me to bundle an interpreter with my application into a single directory (`--onedir`). But once an application has been bundled, I can no longer modify my application code on the fly, which I appreciate doing when called to debug a production issue. I notice that my .py files are still present in the installed directory, but I surmise that PyInstaller has loaded the actual bytecode the bundled executable.

**Describe the solution you'd like**
I'd like it to be possible to store the bytecode along with the original `.py` files, rather than within the binary.

**Describe alternatives you've considered**
I was thinking that I might not be the best user for PyInstaller, and that I should explore other tools. But I still _really_ appreciate the ability to bundle the Python interpreter with my application, and also the automated dependency detection/traversal based on my code. I don't think there are other tools out there that can provide the same benefits.

**Comment by rokm** [comment]
Sounds like you want to use `--debug noarchive` option?

**Comment by rokm** [comment]
And yes, PyInstaller sets up its `FrozenImporter` as first in `sys.meta_path`, so that byte-compiled .pyc modules that are colllected into PYZ archive and embedded in the executable take precedence over everything else. So even if you also collect source .py files into application bundle, they do not get used as regular python modules (as long as the same module also exists in PYZ archive; and barring any `torch`-like JIT magic).

If you use `--debug noarchive` (or equivalent `noarchive=True` setting in .spec file), then the .pyc modules are collected as files into application bundle, in which case they are not handled by our `FrozenImporter` but rather python's built-in importers (so in case when there are both a .pyc and a .py file collected, I'm not really sure which they would load - but you can always remove the .pyc if you want to modify the .py file).

**Comment by rokm** [comment]
And just to clarify, PyInstaller should not be collecting your `.py` files into application bundle, unless instructed to do so; for example due to use of `collect_data_files` with `include_py_files=True` or `collect_all` hook utility function, either directly by yourself or by a hook for a package that requires source files to be also collected (e.g., `torch`).

**Comment by rokm** [comment]
@josnyder-rh does `--debug noarchive` do what you wanted here, or did you have something else in mind?
