### ISSUE TITLE
PyInstaller 4.7 compiled executable with UnicodeDecodeError on Windows 11 (The script does not need to include the specifiec character necessarily)

### ISSUE THREAD

**Issue by marticliment** [pyinstaller/pyinstaller#6423]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.7```
* Version of Python: `3.9.8`
* Platform: `Windows 11 10.0.22000.346`
* How you installed Python: python.org/downloads
* Did you also try this on another platform? No (There's no point on doing this for my script)

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
```
any code works
```

### Stacktrace / full error message
Unabe to get traceback
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 19621: character maps to <undefined>  

```
Unabe to get traceback
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 19621: character maps to <undefined>  
```

### Notes:
 - The error happens randomly, it can crash only the first time running, and on the next time run perfectly, it can crash always or work flawlessly. It is impossible to retrieve any type of traceback. (neither with the traceback module).
 - It is not required to have the _failing_ character in your main script
 - Versions previous to 4.7 work flawlessly

**Comment by rokm** [comment]
> Version of Python: 3.9.8

Does the issue also occur with python 3.9.9?

**Comment by marticliment** [comment]
@rokm, i don't really know. I don't even have had the issue, but rather after launching an update of my software, i started recieving error reports, all with the same exact error and traceback.

**Comment by rokm** [comment]
Well, python 3.9.8 had missing embedded manifests, which made PyInstaller generate its own version. And I suspect those were not valid, possibly due to changes made in #6349 (which may be why 4.6 and earlier works, but 4.7 does not in that case). But since then, python 3.9.9 fixed the manifest issue, and we've also fixed the generated manifests in #6367. 

So I think the underlying issue should already be sorted out, unless you can reproduce the problem with either python 3.9.9 or with HEAD of `v4` branch.

**Comment by marticliment** [comment]
I'll try to reprodduce the issue, but with what you said you could actually close this

**Comment by rokm** [comment]
Maybe try rebuilding your software with python 3.9.9 instead of 3.9.8, and see if it fixes the problem for the affected users?

**Comment by marticliment** [comment]
Gonna try

**Comment by marticliment** [comment]
Well, it does not fix the issue

**Comment by rokm** [comment]
Hmm, alright. So the problem, whatever it is, is unrelated to manifests or lack thereof.

Can you clarify some things, then? Without the traceback and without a reproducer, this is going to be a pain to figure out...

----

1. 

```
any code works
```

What exactly does this mean? Does the problem occur also with a simple hello-world application, or only with your program?

---

2. You said that versions prior to 4.7 do not have this problem. Does that include 4.6, or did you have an earlier version in mind?

Because between 4.6 and 4.7 there's been relatively few changes:

```
$ git log --pretty=oneline v4.6..v4.7
41842f5ad31dd33d7ba4ae03daace2287c80dcb7 (tag: v4.7) release v4.7
b4cd8e7e11fdd614e4cf7cc510b40c950adca023 Update README version for release
5c72041b47fcf12915b1228f8bf9255a4b5e168d rebuild man pages
ec02dad83177461a26e5a35fb0050750c192bc5d Prepare for release 4.7
b9ea730974b4f1b93aeab5fd18b08f647c25f747 Rebuild bootloaders
6248924faae4b50c0bac6e3b80767c7e05271c79 Assorted environment checks. (#6361)
a10ff6ffa26df1662f8baf8a1eb46d15518ce506 bootloader: remove the check for unused windres utility
1ca7f65499ff2f8e1990e2fdf1f7ac046804dce4 bootloader: set NTDDI_VERSION & _WIN32_WINNT when compiling for Windows
4d1c98cd6070c521b2b85ab7e6390dae616f9b60 bootloader: replace PyRun_SimpleString with PyRun_SimpleStringFlags
d8c434a9100f00ac5ac6a773afa8cdce6f78cbb5 Bindepend: Fix FileNotFoundErrors in _which_library().
1a3bab26e8b8e683474557fd3c1ccc16b1d74d57 compat: extend is_macos_11 flag to cover macOS 11 or later
449e29e56707c2d789fbe1e59211cdc8884de7c1 hooks: update sphinx hook for compatibility with v4.2.0
08454e250a08cb45d336985cbc1fb0de3e2fe893 gitignore: Ignore all non-standard bootloaders (e.g. Linux arm). [skip ci]
33e89a4dd146cebebaced3f9a957cc60617262af Back to development
18b9b09f219ca32bff4945390aab2e67f41e2d9a Revert "Change README version for release"
```

and none of those seem to be obvious candidates for regression. (Like I mentioned earlier, setting `NTDDI_VERSION` and `_WIN32_WINNT` when building the new bootloaders might be causing problems when python is missing embedded manifests, but we've ruled that out now).

----

3. Do you know if the problem specific to Windows 11? Do you happen to know what locale/encoding is used on that machine?

----

4. Is this a `console` or a `windowed`/`noconsole` build? Where did the 

```
Unabe to get traceback
```

part of the error message come from?

If this is a noconsole build, can you try with console-enabled build? And if that doesn't get you any traceback,  can you add additional log messages to your program to pinpoint at least which part is failing?

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 19621: character maps to <undefined>  
```
usually means that text is being read with incompatible encoding (e.g., `utf-8` text being read with `cp1251` codec). Does your program read any user-provided files?

**Comment by marticliment** [comment]
1. `Any code works`: i've not found any exact piece of code that causes the fail, it either crashes or not randomly.
2. Version 4.6 DOES work
3. I don't know
4. 
The first time I run the script:
![image](https://user-images.githubusercontent.com/53119851/145723718-7231d296-20c0-470c-892d-5df3aa11f45a.png)
The next time: Code runs normally
![image](https://user-images.githubusercontent.com/53119851/145723772-0450c024-34ff-44a7-9de0-9dfea55552e7.png)

**Comment by rokm** [comment]
Ah, so it's a `windowed`/`noconsole` build where we fail to retrieve the traceback. 

So to get the traceback, you'll either need to:
* build with `console` enabled
* check out the branch from #6426 and rebuild the bootloader yourself
* install directly from this branch (which is basically commit from #6426 on top of `v4` branch, plus rebuilt Windows bootloaders): `pip install git+https://github.com/rokm/pyinstaller.git@pyi-6423-test`

The first option should should give you traceback in console, with other two, the traceback should be now shown in the error dialog.
