### ISSUE TITLE
pulp fails to locate collected cbc executable on MacOS

### ISSUE THREAD

**Issue by LBeghini** [pyinstaller/pyinstaller#6427]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python:  3.9.7
* Platform: MacOS High Sierra v10.13.6
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Yes, tried on Windows and it worked perfectly.

After issue #6359 was solved, I tried to generate an executable for MacOS platforms to solve the bug I was having in my program. Then I got the dev version of PyInstaller and ran the following:
```bash
pyinstaller --icon ./resources/icons/hexagon.icns --add-data "./resources/data:resources/data" --add-data "resources/icons:resources/icons" --name GraphFilter --collect-data pulp --onefile --noconsole --codesign-identity GraphFilter app.py
```
And I managed to generate the executable however I was getting the same bug.

Watching the log on the terminal I got the error:
```error
'NoneType' object has no attribute 'actualSolve'
```
I am still not able to fix [my problem](https://github.com/GraphFilter/GraphFilter/issues/116).

**Comment by bwoodsend** [comment]
Fill out the issue template properly. If the issue really was just `--add-data` on macOS with onefile mode then [our corresponding test](https://github.com/pyinstaller/pyinstaller/blob/551194966dfedc4331c3a6ddc9ca0a601c06507c/tests/functional/test_basic.py#L706) would have been failing.

**Comment by LBeghini** [comment]
I am sorry I couldn't add more information to the issue, but I don't know what is the problem now. I repeated the same process I did on Windows and the error wasn't solved. I checked inside the package contents after generating without the --onefile option and I could see that pulp data was there.

I'll make a few more tests to see if I can figure out something but I'm kinda lost now.

**Comment by bwoodsend** [comment]
Actually, since you're using PuLP, I imagine that this is the same story as #6359 for which the fix is simply to use `--collect-data=pulp`.

**Comment by LBeghini** [comment]
So, the command I ran contains the `--collect-data pulp` option, and it's still not working.
> Also tried with `collect-data=pulp`

**Comment by bwoodsend** [comment]
Well you're on your own then until you produce a minimal example.

**Comment by rokm** [comment]
Uff, with an issue title like that, anyone with `onefile` problems on macOS is going to post their version of "same issue" here...

**Comment by rokm** [comment]
As for the actual problem, I think patching PuLP and changing [this line](https://github.com/coin-or/pulp/blob/0cf902579b8ca52cca09d66df5619095f8062f99/pulp/apis/core.py#L186):
```
config_filename = os.path.join(DIRNAME, "..", PULPCFGFILE)
```
into
```
config_filename = os.path.normpath(os.path.join(DIRNAME, "..", PULPCFGFILE))
```
should fix the issue.

The problem is that PuLP is failing to find the config file in spite of it being collected. That's because `DIRNAME = os.path.dirname(__file__)` points to a directory that does not exist in the frozen bundle (`sys._MEIPASS/pulp/apis`) because all of its content ends up in PYZ archive. But the config file, `sys._MEIPASS/pulp/apis/../pulp.cfg.osx` = `sys._MEIPASS/pulp/pulp.cfg.osx` does exist.

So another possible work-around that does not involve patching PuLP would be to ensure that at least one .py file from `pulp/apis` is collected as data file (which will ensure that the directory exists in frozen bundle). But I think the proper solution here is to fix the problem on PuLP side.

---

That said, `collect_data` ends up collecting the `cbc` executable as a data file (instead of a binary), which means that the file does not undergo the macOS-specific processing that we do. The library path rewrite (or lack thereof) is not a problem in this case, because the binary depends only on system-provided shared libraries. But this also means that the file will not get signed, which may or may not be a problem in this case (since I see you're using a codesign identity). And since this is a onefile build, you won't be able to sign it manually in post processing.

So you'd either need to ensure that the `cbc` executable is collected as binary (probably in a custom hook for pulp; and while you're at it, it would probably be best to ensure that only the executable for the target OS is collected). But you could probably also sign the executable in your PuLP installation with your codesign identity before you start the build process, and then let it be collected as a data file...

**Comment by LBeghini** [comment]
I am a bit confused. In this case, should I open an issue in pulp? Or the work around would be to collect this one .py file from `pulp/apis` with --add-data option?

I really didn't want to patch pulp, cause in the future I plan to automate the release process.

---
Is the signing part an unrelated issue? I also generated without signing, and it does not give me any errors besides this one.

**Comment by rokm** [comment]
> I am a bit confused. In this case, should I open an issue in pulp? Or the work around would be to collect this one .py file from `pulp/apis` with --add-data option?

That's up to you; I'm just listing the options that I see.

I think adding that `os.normpath()` to PuLP should not be a problem, even though it again fixes a corner case that is PyInstaller-specific. This means you'll need to wait for new PuLP release, though, so you might want to use the work-around in the meantime.

As an alternative work-around (to collecting the .py file from `pulp/apis`), you can also use `--debug noarchive` to avoid collecting the .pyc modules into PYZ archive; this should also fully preserve the original directory structure and avoid the issue.

> I really didn't want to patch pulp, cause in the future I plan to automate the release process.

Nothing really prevents you from adding the patching step to the build/release process, though...

----
 
> Is the signing part an unrelated issue? I also generated without signing, and it does not give me any errors besides this one.

I suppose that depends on how you plan to distribute your macOS builds, and on the security settings of your users' Macs.

**Comment by LBeghini** [comment]
I really appreciate your help. Adding the `os.normpath()` worked, and the `--debug noarchive` also worked as well. 

I also opened [this issue](https://github.com/coin-or/pulp/issues/513) on PuLP to see if they can address the problem.
