### ISSUE TITLE
Using opencv built from source code to package exe, encountered some problems.

### ISSUE THREAD

**Issue by Mithranda** [pyinstaller/pyinstaller#6478]
I got a  problem when i installed OpenCV v4.5.4 from source and try to use it in pyinstaller, and i think the it is the same kind of [problem.](https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/110)
OpenCV v4.5.4
Python 3.9.9
Pyinstaller 4.8
OpenCV v4.5.4 from source run in pycharm is no problems,but when i try to pick it to my exe, i got this problem and troubled me for a week.
Locate to if only import cv2,this problem will be happened.
This is the track:
['D:\CodeProject\Python\CamerasTrack\test\dist\cvtest\base_library.zip', 'D:/opencv-4.5.4/build/lib/python3/Release', 'D:\CodeProject\Python\CamerasTrack\test\dist\cvtest\lib-dynload', 'D:\CodeProject\Python\CamerasTrack\test\dist\cvtest']
Traceback (most recent call last):
File "cvtest.py", line 5, in
File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
File "cv2_init_.py", line 180, in
bootstrap()
File "cv2_init_.py", line 152, in bootstrap
native_module = importlib.import_module("cv2")
File "importlib_init_.py", line 127, in import_module
File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
File "cv2_init_.py", line 180, in
bootstrap()
File "cv2_init_.py", line 75, in bootstrap
raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

**Comment by rokm** [comment]
OpenCV build from source is not supported, as described in #4564 and pyinstaller/pyinstaller-hooks-contrib#110 (hence I'm closing this as a duplicate, as it is tracked in the hooks-contrib repository). 

The reason is that `cv2/__init__.py` is trying to substitute itself with `cv2/python-3.x/cv2.*.pyd` extension module by `sys.path` manipulation, which does not work with PyInstaller, because our FrozenImporter gives precedence to collected .pyc modules over on-disk resources; so path manipulation fails, and `cv2/__init__.pyc` is loaded on all attempts, leading to the recursion error message.

For now, the only way to possibly make source-compiled OpenCV work is to bypass its loader altogether, by setting search path to the location where the extension module is located and manually ensuring that OpenCV shared libraries are collected - see https://github.com/pyinstaller/pyinstaller/issues/4564#issuecomment-820179612 for an example.

**Comment by Mithranda** [comment]
> OpenCV build from source is not supported, as described in #4564 and [pyinstaller/pyinstaller-hooks-contrib#110](https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/110) (hence I'm closing this as a duplicate, as it is tracked in the hooks-contrib repository).
> 
> The reason is that `cv2/__init__.py` is trying to substitute itself with `cv2/python-3.x/cv2.*.pyd` extension module by `sys.path` manipulation, which does not work with PyInstaller, because our FrozenImporter gives precedence to collected .pyc modules over on-disk resources; so path manipulation fails, and `cv2/__init__.pyc` is loaded on all attempts, leading to the recursion error message.
> 
> For now, the only way to possibly make source-compiled OpenCV work is to bypass its loader altogether, by setting search path to the location where the extension module is located and manually ensuring that OpenCV shared libraries are collected - see [#4564 (comment)](https://github.com/pyinstaller/pyinstaller/issues/4564#issuecomment-820179612) for an example.

Thanks for your reply!
I have to say that the opencv loader is very magical... and hope that a separate .pyd package can be generated when opencv is compiled in the future
I will modify the project according to this idea.
