### ISSUE TITLE
Auto embed sys.argv arguments

### ISSUE THREAD

**Issue by xp4xbox** [pyinstaller/pyinstaller#6495]
I would like the ability to be able to automatically pass arguments to sys.argv on .exe launch. 

a reusable option such as `--args release --args debug` would be very useful since I do not expect the user to have to enter any of theses manually.

I have noticed there is only the option to specify args for the python interpreter only

**Comment by rokm** [comment]
If the user won't be entering those options, does it even make sense for them to be command-line options? Or perhaps they should be command-line options with default arguments?

If you want to provide users with different presets, launcher .bat scripts that call the .exe with corresponding arguments might be a better idea.

Unless you want to "hard-code" those options in the sense that user cannot override them. And even then, you can do that by creating runtime hooks that are executed before your main script, and modify `sys.argv` in there. So for release/debug preset, you could have two different runtime hooks and switch between them during the build process...

At any rate, I think this should be either handled by (your) python code or by the caller (e.g., launcher scripts) instead of being implemented on the PyInstaller level (i.e., the bootloader and/or bootstrap scripts).

**Comment by bwoodsend** [comment]
Likewise I fail to see the logic behind this. If you don't want your users to have to supply options then don't write an application that requires them. The options to the Python interpreter feature exists because there is no other way to get the to Python at runtime - by the time the EXE is ready to run any Python code it's too late to apply the options - but your case sounds completely self inflicted. If you really want a series of hard-coded flags then wrap up your CLI so that it can be called with a list of arguments then have separate entry points which add the flags:

```python
# release.py
import sys
from your_code import cli
cli(["--release-option"] + sys.argv[1:])
```

```python
# debug.py
import sys
from your_code import cli
cli(["--debug-option"] + sys.argv[1:])
```

Then freeze each one. But if you are to have a debug mode, I'd just set it up so that release mode is the default and a hidden `YOUR_PROJECT_NAME_DEBUG=1` environment variable activates debug mode.

**Comment by xp4xbox** [comment]
yeah i guess that works thanks
