### ISSUE TITLE
Allow attaching to console when using `--noconsole`

### ISSUE THREAD

**Issue by ericoporto** [pyinstaller/pyinstaller#6541]
**Is your feature request related to a problem? Please describe.**
I am making a graphical app using python that also has a command line interface. It works fine in Linux/MacOS, but now I want to pack it as a Windows exe, and pyinstaller seems the best way to go. Problem is, when using `--noconsole`, the app has no visible console output, and without the flag, I get an annoying floating console that if I close it closes my app too.

**Describe the solution you'd like**
I know that in C++ is possible to do a windowed App and manually attach an output (something like https://stackoverflow.com/a/46050762), so I would like some similar approach so that it would be possible to have console output if the app is called say from `cmd.exe` but not when not called from it.

**Describe alternatives you've considered**
I haven't found yet any alternative in python when using pyinstaller. Probably a way would be to package a native module to do so through something like a python C interface, but I haven't gone there yet.

**Additional context**
I am not the first person to need this, I also found someone here: https://stackoverflow.com/questions/67610859/show-stdout-with-pyinstaller-noconsole

**Comment by bwoodsend** [comment]
See #6244.

**Comment by rokm** [comment]
See #6244. I still maintain that this is beyond the scope of PyInstaller, if it is technically feasible at all.

> to have console output if the app is called say from cmd.exe but not when not called from it.

And what magic mechanism would be used to determine how the app was called?

---

Strictly speaking, there's nothing preventing your python code from attaching console via win32 api bound through `ctypes`, but while you might even manage to redirect the underlying streams to the attached console (at "C level"), I imagine that won't do anything to the python equivalents. Because they were initialized when underlying C streams were invalid, hence one of SO discussions you linked observes that `sys.stdout` is a `NullWriter` and `sys.__stdout__` is `None`. So you'd probably need to reinitialize/redirect those as well... 

And if you're thinking of re-attaching console in bootloader itself (i.e., the C code) before python interpreter is initialized, that brings us back to the question of how to decide when to re-attach the console or not. While a special command-line argument is an option, it is specific to your needs and application, hence my original stance that this is beyond the scope of PyInstaller.

**Comment by ericoporto** [comment]
> And what magic mechanism would be used to determine how the app was called? 

I don't know? I opened the issue to start a discussion and see if there's a feasible approach here. Had I knew the solution from the get go I would just have submitted a PR. It seems there's no interest so be it.

**Comment by bwoodsend** [comment]
Yeah, admittedly I was pretty blunt but that's just because we've been here before with a lot of other users who seem to think we can just magic a solution up on demand without the understanding that this is a Windows design constraint - not a PyInstaller one. We haven't found any sane way of doing it. I think the closest you're likely to get it to create a console executable (probably in C) which invokes a windowed executable in a subprocess using the Windows C API to capture and forward its file handles (I believe `psutil.Popen()` does this out the box). I doubt any kind of single executable `windowed-program.exe --secret-console-mode` is even possible.
