### ISSUE TITLE
exeutable built using pyinstaller 4.0 on python 3.8.6 doesn't launch at all 

### ISSUE THREAD

**Issue by bndeshmukh1** [pyinstaller/pyinstaller#6602]
I am using pysintaller 4.0 on python 3.8.6 on Windows 10. 
The executable built using pyinstaller doesn't launch at all. No messages , nothing appeared on screen. 
Executable is created using --onefile option and has one DLL which is packed using --add-binary parameter. 
using --debug=all , it launches with all messages. but when I remove debug parameter, executable doesn't launch at all 
I see following message when --debug=all is mentioned in parameter. 

[20924] LOADER: Error activating the context: ActivateActCtx:
An attempt to set the process default activation context failed because the process default activation context was already set.

issue is raised on stackoverflow as well but no response till now

https://stackoverflow.com/questions/71177319/executable-built-using-pyinstaller-doesnt-run-at-all-on-windows-10

Please tell me how to resolve this issue

**Comment by bwoodsend** [comment]
Without a reproducible example, there's nothing we can do to help.

**Comment by rokm** [comment]
For starters, update to a recent version of PyInstaller...

**Comment by bndeshmukh1** [comment]
Even taking latest development version, didn't help .. my question is why
it launches when set --debug=all or even bootloader but not when removed ?
And what about that active context error ?

**Comment by rokm** [comment]
> And what about that active context error ?

If you're using the latest version (4.9 release, `v4` HEAD or `develop` HEAD), you shouldn't be seeing the context activation error.

> my question is why it launches when set --debug=all or even bootloader but not when removed ?

Maybe because `--debug=all` implies `--debug=noarchive`, which causes the modules to be collected on filesystem instead of into embedded PYZ archive?

As Brénainn said, without a reproducer, we cannot really say.

**Comment by bndeshmukh1** [comment]
I shall provide small example to reproduce the issue but that doesn't mean there is no issue. 
Closing issue outright without even trying in house is not that I was expecting. 
But you must have faced such issue in past , do you have any pointers to those issues ?
or may I will look at some different tool as --onefile built executable is very very slow in execution as 
my experience in past ..

**Comment by rokm** [comment]
> I shall provide small example to reproduce the issue but that doesn't mean there is no issue.
> Closing issue outright without even trying in house is not that I was expecting.

The issue was closed because there's nothing for us to "try" - we have no idea what packages you are using and what your program is (supposed to be) doing. And because PyInstaller problems are often tied to specific situations (packages used, incompatible usage patterns, etc.), we cannot guess about what's going on.

The only detail you really provided is the context activation error, which has been dealt with in recent versions of PyInstaller.

> or may I will look at some different tool as --onefile built executable is very very slow in execution as my experience in past 

That's because onefile executable needs to unpack itself to temporary directory before the frozen code is actually executed. So for large(r) programs, it is expected to introduce noticeable delays.
