### ISSUE TITLE
libcrypt not bundled

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#6618]
## Description of the issue

See https://github.com/borgbackup/borg/issues/6339 - the single file binary does not contain `libcrypt.so.1`, so execution fails if the user does not have it on their system.

See also:

https://stackoverflow.com/questions/68611799/pyinstaller-binary-not-finding-library-files

**This issue is about why it does not automagically discover and bundle the library.**

### Context information (for bug reports)

* Output of `pyinstaller --version`: 4.7
* Version of Python: 3.9.10
* Platform: build: debian buster, use: arch linux
* How you installed Python: build: pyenv, use: arch package (likely)
* Did you also try this on another platform? Binary works on other systems, likely due to presence of system lib.

Next thing I'll try is the workaround from stackoverflow and also a more recent pyinstaller release.

**Comment by rokm** [comment]
libcrypt.so.1 has been explicitly excluded by our [unix exclude rules](https://github.com/pyinstaller/pyinstaller/blob/6f24f82979904619af1865bbe6d045c6fed7eb84/PyInstaller/depend/dylib.py#L117) since primordial times - presumably due to being part of glibc...

What is probably going on here is that the target distribution has dropped glibc' `libcrypt.so.1` in favor of `libxcrypt` and provides `libcrypt.so.2` by default, while `libcrypt.so.1` is available via special compat package. At least that's the case on my Fedora system, and it seems there's a [`libxcrypt-compat` package](https://aur.archlinux.org/packages/libxcrypt-compat) on arch, too.

So this gets a `wontfix` vote from me. If you can get away with bundling the copy from your build system, go ahead, but I think the proper "fix" is to tell the users to install the corresponding compat package on their system.

**Comment by bwoodsend** [comment]
And it's generally seen as bad security to statically compile (or in PyInstaller-land bundle) any kind of security library. Every time a vulnerability is found and fixed in any of those libraries, every previous build of your application is now a carrying a publically known vulnerability so you must update your build system, rebuild your application, release it and try to encourage users to upgrade as soon as possible. If it's dynamically linked (or just excluded from bundles in PyInstaller's case) then your users will upgrade the offending library as part of their distribution's regular updating process and the world continues turning as normal. So for that particular library, I'd also push for `wontfix`.
