### ISSUE TITLE
CV2 binary extensions

### ISSUE THREAD

**Issue by sarperkilic** [pyinstaller/pyinstaller#6624]
Hello,

I am trying to convert my python script to executable file on Nvidia Jetson Nano. 

I built executable file using pyinstaller, when I run the executable file, below error occurs.

['/tmp/_MEIkbxMDb/base_library.zip', '/tmp/_MEIkbxMDb/cv2/python-3.6', '/tmp/_MEIkbxMDb/lib-dynload', '/tmp/_MEIkbxMDb']
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import cv2
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "__init__.py", line 89, in <module>
  File "__init__.py", line 79, in bootstrap
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "__init__.py", line 89, in <module>
  File "__init__.py", line 23, in bootstrap
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
[19161] Failed to execute script 'main' due to unhandled exception!

I am using this command to conversion:

pyinstaller --onefile --paths="/usr/lib/python3.6/dist-packages/cv2/python-3.6" --additional-hooks-dir=. main.py

My python version is 3.6
pyinstaller is 4.9
opencv is 4.1.1

What should I do to solve this? 
I need urgent help

Thanks

**Comment by rokm** [comment]
This happens with OpenCV builds that use the loader script that tries to replace `cv2` package with `cv2.cv2` module/extension. This does not work with PyInstaller, and results in the recursion error (because `cv2` remains the top-level package, hence apparent recursiion). The problematic loader script is usually part of OpenCV compiled from source, though judging by the path prefix `/usr/lib/python3.6/dist-packages` it is a system-provided copy in this case. Either way, it won't work with PyInstaller.

The usual work-around for source-compiled OpenCV is indeed to specify the directory of `cv2` binary extension (`--paths="/usr/lib/python3.6/dist-packages/cv2/python-3.6"`) so that it is picked up instead of the `cv2` package, but in your case, this doesn't work because `cv2` package is in default search path, `/usr/lib/python3.6/dist-packages`, and is therefore picked up first.

What *might* work in this case is suppressing the collection of `cv2` via normal analysis and manually collecting the extension module as a binary: 

```shell
pyinstaller \
    --onefile 
    --exclude-module cv2 \  # prevents cv2 package (and cv2.__init__.py loader script, in particular) from being collected into PYZ archive
    --add-binary "/usr/lib/python3.6/dist-packages/cv2/python-3.6/cv2.XXX.so:." \  # collect cv2.XXX.so extension into top-level application directory (.)
    --additional-hooks-dir=. \
    main.py
```
