### ISSUE TITLE
Minimize-able/Hide-able Splash 

### ISSUE THREAD

**Issue by cap1tan** [pyinstaller/pyinstaller#6641]
**Is your feature request related to a problem? Please describe.**
The splash screen seems to be Always on Top. In case program startup takes a long time, it is a bit annoying to have a splash in the middle of everything. Also no icon in the taskbar to minimize.

**Describe the solution you'd like**
Make the splash behave like a normal window that can be hidden by other windows.

**Comment by rokm** [comment]
Hmm, I suppose we could make the [always-on-top behavior](https://github.com/pyinstaller/pyinstaller/blob/56b2dd51d30103e9200496c0ec5b5a11e7bf546e/PyInstaller/building/splash_templates.py#L173) an option (or just disable it altogether).

To make the splash screen window-like, we'd need to disable [this](https://github.com/pyinstaller/pyinstaller/blob/56b2dd51d30103e9200496c0ec5b5a11e7bf546e/PyInstaller/building/splash_templates.py#L171), but I don't think that's a good idea because it will give user an option to close the window, which will likely lead to undesired side effects (i.e., exceptions when trying to modify or close the splash screen in python code).

**Comment by bwoodsend** [comment]
Disabling the always on top flag sounds best to me. It feels too minor to warrant making it configurable.

**Comment by bwoodsend** [comment]
That said, disabling the `-topmost` flag doesn't appear to make any difference.

**Comment by rokm** [comment]
> That said, disabling the `-topmost` flag doesn't appear to make any difference.

Hmm, it indeed seems to make no difference on linux, but it seems to do on Windows.

**Comment by rokm** [comment]
Looks like on linux, we can use `-type splash` [attribute](https://wiki.tcl-lang.org/page/wm+attributes), while disabling `overridedirect`:
```
# Set position and mode of the window
#wm overrideredirect . 1
wm geometry         . +${x_position}+${y_position}
#wm attributes       . -topmost 0
wm attributes         . -type splash
```
