### ISSUE TITLE
Increase `codesign` timeout

### ISSUE THREAD

**Issue by Safihre** [pyinstaller/pyinstaller#6644]
The timeout for the `codesign` command in PyInstaller on macOS is set to 60 seconds. While this might seem like a long time, for our fat application being build on GitHub Actions, this is quite often not long enough.
Especially when it's busy at GitHub Actions, runners can get limited resources and it will take longer to complete such system calls.

Could this be extended to something longer? Or make it configurable?

Example: https://github.com/sabnzbd/sabnzbd/runs/5408721960?check_suite_focus=true#step:9:194
Here we let PyInstaller sign using our real identity, but I also have plenty of runs where the ad-hoc signing and/or the signature-removal failed due to the timeout being reached.

**Comment by bwoodsend** [comment]
Hmm, we *could* make the timeout proportional to the size of the executable...

**Comment by bwoodsend** [comment]
Can you give us some numbers? i.e. How big is this executable and how long does it need to sign?

**Comment by rokm** [comment]
This is similar to the report we had in #6536. I think we should have a longer timeout (e.g., 10 minutes) at least for bundle code-signing and for running that PKG embedding objcopy call on linux. Which means we'll need to add a timeout argument to `exec_command` (and higher-level uses of it, if applicable) - the current hard-coded default is [here](https://github.com/pyinstaller/pyinstaller/blob/56b2dd51d30103e9200496c0ec5b5a11e7bf546e/PyInstaller/compat.py#L350). EDIT: both operations actually use `exec_command_all`, with hard-coded default [here](https://github.com/pyinstaller/pyinstaller/blob/56b2dd51d30103e9200496c0ec5b5a11e7bf546e/PyInstaller/compat.py#L489).

But perhaps we should also make both the "short" (default 1-minute) timeout and "long" timeout value a variable in `PyInstaller.compat`, so that they can be overridden at the start of the spec file (or within custom build system that integrates PyInstaller), if necessary.

**Comment by bwoodsend** [comment]
> Which means we'll need to add a timeout argument to exec_command (and higher-level uses of it, if applicable)

I'd rather just let them use `subprocess.run()` directly. Those `exec_*()` functions are all cases of [xkcd 927](https://xkcd.com/927/) to me.

**Comment by Safihre** [comment]
> Can you give us some numbers? i.e. How big is this executable and how long does it need to sign?

FWIW: uncompressed it's 70MB with a couple of sub-binaries that we include and of course all the Python `*.so` files. It's `universal2` now, so very fat, and needing signatures for multiple architectures.
Sometimes the signing only takes 20 seconds, it really seems to depend on the resources the GitHub Actions runner has at the moment.

So a configurable option would be great.

**Comment by bwoodsend** [comment]
@rokm Do you think that there really is any need for `objdump` to have a timeout? I can't say that I've ever seen it stall.

**Comment by Safihre** [comment]
> @rokm Do you think that there really is any need for `objdump` to have a timeout? I can't say that I've ever seen it stall.

I wonder the same about `codesign`, why would it stall? It fails or succeeds, or have you seen otherwise?

**Comment by rokm** [comment]
Neither command really needs a timeout, as far as I'm concerned. 

The current situation came about with global introduction of `exec_command_*` timeouts in 0bd3ec8a4bbe24bbc7e4cea27bc9561569c2d79b, which aimed to remedy the CI pipelines getting stuck sometimes (whatever the reason for those really was).

**Comment by rokm** [comment]
So perhaps the fastest and least painful fix for this would indeed be to migrate these two commands to use `subprocess.run` directly. I'd personally prefer to have the codebase consistently use either `subprocess.run` or the `exec_*` functions, but purging the latter from the codebase will probably be quite a hassle...

**Comment by Safihre** [comment]
Thanks for the quick fix!!
