### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by MK096** [pyinstaller/pyinstaller#6685]
While running the exe file on a different machine i get DLL load failed error.
Few weeks before it used to work fine. I tried reinstalling the package and even tried different versions of it.

This is the command i use to generate exe:
python -m eel filename.py Compiled --hidden-import=cexprtk._functionargs --onefile

eel is a package to integrate HTML UI with python.
cexprtk is a package for mathmatical expressions

I have win 10 64 bit sy
![cexprtk](https://user-images.githubusercontent.com/20142735/158944293-74a3a46d-294d-40d3-8d14-d85632c06937.png)
s

**Comment by rokm** [comment]
This is usually caused by a missing VC runtime DLL and the target system not having VC redistributable installed.

The `_cexprtk` extension seems to be linked against `msvcp140.dll`, `vcruntime140.dll`, and `vcruntime140_1.dll`. Can you check that these files are collected (either by a) using pyi-archive_viewer.exe utility; b) creating a onedir build and inspecting the bundle; or c) by looking at `build\<name>\Analysis-00.toc` and/or `build\<name>\PKG-00.toc`).

**Comment by MK096** [comment]
The exe works on my pc, but fails to work on other PC

![dll_pic](https://user-images.githubusercontent.com/20142735/158963370-a3e50d62-136d-47b0-a363-58128c3c2882.png)

Seems those dll's are missing.
From the error, the 2nd line in init.py is : from ._cexprtk import USRSymbolType
Here's the file structure: 
![structure](https://user-images.githubusercontent.com/20142735/158963816-8cbdf12c-24cb-47a2-a80e-b6fff8014327.PNG)

I tried using paths but that also didn't work:
python -m eel Computation.py Compiled --hidden-import=cexprtk._functionargs --onefile --paths C:\Users\Mayank\AppData\Local\Programs\Python\Python37\Lib\site-packages\cexprt

k

**Comment by rokm** [comment]
> The exe works on my pc, but fails to work on other PC

Yes, because your PC has VC redistributable installed, while the other one does not.

> Seems those dll's are missing.

On my test system, `VCRUNTIME140.dll` is collected from `c:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python37\\VCRUNTIME140.dll'` (i.e., from python installation, same as in your case), while the other two are collected from `c:\\Windows\\system32`:

```
  ('VCRUNTIME140_1.dll', 'C:\\WINDOWS\\system32\\VCRUNTIME140_1.dll', 'BINARY'),
  ('MSVCP140.dll', 'C:\\WINDOWS\\system32\\MSVCP140.dll', 'BINARY')],
```

> I tried using paths but that also didn't work:

Of course it did not. Don't use `--paths` unless you know what it actually does, you'll only make things worse.

----

What version of PyInstaller are you using? We added collection of those extra VC runtime DLLs a while ago (4.4 I think?) so they should be collected...

If you open that `_cexprtk.cp37-win_amd64.pyd` file in [Dependency walker](https://www.dependencywalker.com/) on your PC, does it show vcruntime140_1.dll and msvcp140.dll as resolved? If you press F9 to get full paths, where are they located?

And lastly, if your freeze the following simple program:

```python
import cexprtk
print("Hello!")
```

directly using pyinstaller (i.e., without eel), does it work? Are all three VC dlls collected?

**Comment by MK096** [comment]
Hi,
I reinstalled VC and updated my windows. After that it worked fine
