### ISSUE TITLE
No metadata path found for distribution 'greenlet' when importing gevent

### ISSUE THREAD

**Issue by Jerther** [pyinstaller/pyinstaller#6692]
## Description of the issue
Run pyinstaller as usual for a program that depends on `gevent`. Pyinstaller eventually fails (see stack trace below)

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.10```
* Version of Python: 3.8.10
* Platform: Ubuntu 20.04
* How you installed Python: apt
* Did you also try this on another platform? Does it work there? Yes, on another similar computer with the same OS and it also fails.

* try the latest development version. Result: Same thing.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong): Does not apply

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

Does not apply.

### A minimal example program which shows the error

```
import gevent
help(gevent)
```

### Stacktrace / full error message

Result of `python3.8 -m PyInstaller --onefile test.py --log-level DEBUG > out.txt 2>&1`:
[out.txt](https://github.com/pyinstaller/pyinstaller/files/8316518/out.txt)

### Additional info

I dug a bit in the source code and found these lines in `/usr/local/lib/python3.8/dist-packages/PyInstaller/utils/hooks/__init__.py`:
```
    if egg_path is None:
        # According to older implementations of this function, packages may have no metadata. I have no idea how this
        # can happen...
        raise RuntimeError(f"No metadata path found for distribution '{project_name}'.")
```

So two things:
- I have a system which could shed some light on this
- the result of `type(pkg_resources.get_distribution('greenlet').egg_info)` is indeed `<class 'NoneType'>`

**Comment by Jerther** [comment]
I edited the original report where I said it works on another computer. It doesn't.

What happens is that my real program, which is quite large, does not import `gevent`, but for some reason, pyinstaller seems to need it on one system but not on the other. Maybe because of different versions of imported packages, who knows. But it doesn't matter for the main issue here I think.

**Comment by Jerther** [comment]
Also, even though `pkg_resources.get_distribution('greenlet').egg_info` is `None`, the actual `.egg-info` file actually exists:

```
$ ls -al /usr/lib/python3/dist-packages/greenlet-0.4.15.egg-info 
-rw-r--r-- 1 root root 3763 Mar 14  2020 /usr/lib/python3/dist-packages/greenlet-0.4.15.egg-info
```

**Comment by rokm** [comment]
Looks like that `egg_info` field ends up being `None`  for all Ubuntu-packaged python packages where the corresponding `/usr/lib/python3/dist-packages/name-version.egg-info` is a file...

**Comment by rokm** [comment]
> What happens is that my real program, which is quite large, does not import `gevent`, but for some reason, pyinstaller seems to need it on one system but not on the other.

`gevent` is probably an optional dependency of some other package that your program uses, so it ends up being pulled in only if it is available in the environment (it could also be an optional dependency of an optional dependency that's present only on one system). Either way, it boils down to the difference in what's installed in the build environment. I'd advise you against using your base system python to build your program, as it might result in quite a bloated build (because you likely have more packages installed there than your program really needs, so optional dependencies will end up collected). Instead, create a virtual environment with minimal set of dependencies installed in via `pip install`. Or, if you really prefer Ubuntu-packaged versions of python packages, use a Docker container to set up a minimal environment.

---

But the case of missing metadata should probably be sorted out regardless of the above...

**Comment by Jerther** [comment]
Yes I actually build the final executable on the target machine itself, which is as lean as it can be, but does have a different set of software installed. I should give virtual environments a try though.

---

My dev machine is on Fedora 35 and for `pkg_resources.get_distribution('greenlet').egg_info` I get this:
`'/usr/local/lib64/python3.10/site-packages/greenlet-1.1.2.dist-info'`
which is indeed a directory:

```
$ ls -al /usr/local/lib64/python3.10/site-packages/greenlet-1.1.2.dist-info
total 36
drwxr-xr-x. 1 root root  150 Jan 11 08:59 .
drwxr-xr-x. 1 root root 2186 Jan 12 15:34 ..
-rw-r--r--. 1 root root  849 Jan 11 08:59 AUTHORS
-rw-r--r--. 1 root root    4 Jan 11 08:59 INSTALLER
-rw-r--r--. 1 root root 1434 Jan 11 08:59 LICENSE
-rw-r--r--. 1 root root 2424 Jan 11 08:59 LICENSE.PSF
-rw-r--r--. 1 root root 3881 Jan 11 08:59 METADATA
-rw-r--r--. 1 root root 6120 Jan 11 08:59 RECORD
-rw-r--r--. 1 root root    0 Jan 11 08:59 REQUESTED
-rw-r--r--. 1 root root    9 Jan 11 08:59 top_level.txt
-rw-r--r--. 1 root root  152 Jan 11 08:59 WHEEL
```

Anyway from what I gather, `_copy_metadata_dest()` assumes `egg_info` is a directory, not a file.

It seems to me that PyInstaller should handle egg_info when it's a file, but also `pkg_resource.get_distribution().egg_info` should return something in that case. There nothing about a `Distribution.egg_info` property in [pkg_distribution help page](https://setuptools.pypa.io/en/latest/pkg_resources.html) and the only place `egg_info` is referenced as a parameter seems to imply it is a directory.

**Comment by bwoodsend** [comment]
The egg-info isn't as well defined as the dist-info (which has its own PEP) but I'm very much leaning towards saying that Ubuntu is at fault here for a) using the obsolete egg format and b) making it a format which `pkg_resources` (a part of `setuptools` which is who sets the definition of an egg distribution since `setuptools` is normally what generates them in the first place) doesn't understand.

**Comment by rokm** [comment]
> The egg-info isn't as well defined as the dist-info (which has its own PEP) but I'm very much leaning towards saying that Ubuntu is at fault here for a) using the obsolete egg format and b) making it a format which `pkg_resources` (a part of `setuptools` which is who sets the definition of an egg distribution since `setuptools` is normally what generates them in the first place) doesn't understand.

As much as I agree, unfortunately around here, someone else's questionable choices tend to become our problems. 

The catch is, it is not that `pkg_resources` does not understand this format. It can still load the metadata, and you can retrieve the basic info such as project name and version. But the returned instance of `pkg_resources.EggInfoDistribution` has `egg_info` set to `None`, and `get_metadata` allows only queries for `PKG-INFO`. I think this is because behind the scenes, the [`FileMetadata` provider](https://github.com/pypa/setuptools/blob/8723db46613fc2a010acf468a8d50257d1c0e76b/pkg_resources/__init__.py#L1879) is used instead of (presumably) [`PathMetadata` one](https://github.com/pypa/setuptools/blob/8723db46613fc2a010acf468a8d50257d1c0e76b/pkg_resources/__init__.py#L1920).

**Comment by rokm** [comment]
Also, looks like Debian [bookworm](https://packages.debian.org/bookworm/amd64/python3-greenlet/filelist) has switched to the .egg-info directory for that particular (`python3-greenlet`) package. So we'll probably need to handle this at least until [bullseye](https://packages.debian.org/bullseye/amd64/python3-greenlet/filelist) goes EOL...

**Comment by bwoodsend** [comment]
```
root@9f06f3f03cc8:/# apt-file list python3-greenlet
python3-greenlet: /usr/lib/python3/dist-packages/greenlet-0.4.17.egg-info
python3-greenlet: /usr/lib/python3/dist-packages/greenlet.cpython-39-x86_64-linux-gnu.so
python3-greenlet: /usr/share/doc/python3-greenlet/changelog.Debian.amd64.gz
python3-greenlet: /usr/share/doc/python3-greenlet/changelog.Debian.gz
python3-greenlet: /usr/share/doc/python3-greenlet/copyright
```
That license file moved to `/usr/share/doc/python3-greenlet/copyright` where no-one but apt can find it is also another hurdle in the way of ever automating #5666.
