### ISSUE TITLE
ModuleNotFoundError when trying to bundle application with numerous directory.PythonFile imports

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#6713]
## Description of the issue

I have an application whose functionality is spread across multiple python files, all of these python files however are imported by the file I am ultimately passing into PyInstaller.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: 3.7
* Platform: Windows 10
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?  
No, windows is the only platform I can test on at this time.  

File structure of this program is this:
```
src
├── include
│   ├── HostFileEditor.py
│   ├── WSLinterface.py
│   ├── ddsConfigEnums.py
│   ├── dockerInterface.py
│   ├── fileServer.py
│   ├── fileSystemInterface.py
│   ├── loaderDDSInterface.py
│   └── manifestParser.py
├── mmtB.py (what is being passed in to PyInstaller and has the imports)
```

I'm certain I'm missing something incredibly basic here about how imports work when you are importing your own files, but I can't quite figure it out.  When you use hidden imports my assumption is that you state it like the module "include.dockerInterface" instead of a filepath, and with paths I gave the actual OS path relative to where the pyinstaller command is being ran from.  I had this program building before but the file structure was completely different than what it is now (everything was in the same directory), and I changed it to help clean up the code repository/assist my future reviewers.

The error message attempt you see is the outcome of this spec file (just experimenting to solve the first import issue)
```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['mmtB.py'],
    pathex=[],
    binaries=[('..\\dependencies\\win-x64\\nddscore.dll', '.'), ('..\\dependencies\\win-x64\\nddsc.dll', '.'), ('..\\dependencies\\win-x64\\msvcr120.dll', '.'), ('..\\dependencies\\win-x64\\rtiddsconnector.dll', '.')],
    datas=[],
    hiddenimports=['include', 'include.dockerInterface'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ltbTest',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ltbTest',
)
```

### Things I've tried

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Using hidden-imports=missing module/the root directory of the modules
  * [x] paths=directory containing the missing module
  * [x] Supplying the individual modules in question to the pyinstaller command in addition to the main file calling all of them.

### Error message

```
C:\Users\carter.miller\OneDrive - A Corporation\test\MMTShenanigans\prototypeMadness\test-sw-loader\src>dist\ltbTest\ltbTest.exe
Traceback (most recent call last):
  File "mca-sw-loader\src\mmtB.py", line 24, in <module>
ModuleNotFoundError: No module named 'include.dockerInterface'
[4932] Failed to execute script 'mmtB' due to unhandled exception!

C:\Users\carter.miller\OneDrive - A Corporation\test\MMTShenanigans\prototypeMadness\test-sw-loader\src>
```

### Stacktrace / full error message (this was result of debug command)

```
[15876] PyInstaller Bootloader 3.x
[15876] LOADER: executable is C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest\ltbTest.exe
[15876] LOADER: homepath is C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest
[15876] LOADER: _MEIPASS2 is NULL
[15876] LOADER: archivename is C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest\ltbTest.exe
[15876] LOADER: Cookie found at offset 0x16C97A
[15876] LOADER: No need to extract files to run; setting extractionpath to homepath
[15876] LOADER: SetDllDirectory(C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest)
[15876] LOADER: Already in the child - running user's code.
[15876] LOADER: Python library: C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest\python37.dll
[15876] LOADER: Loaded functions from Python library.
[15876] LOADER: Manipulating environment (sys.path, sys.prefix)
[15876] LOADER: sys.prefix is C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest
[15876] LOADER: Pre-init sys.path is C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest\base_library.zip;C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest\lib-dynload;C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest
[15876] LOADER: Setting runtime options
[15876] LOADER: Initializing python
[15876] LOADER: Overriding Python's sys.path
[15876] LOADER: Post-init sys.path is C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest\base_library.zip;C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest\lib-dynload;C:\Users\carter.miller\OneDrive - Wabtec Corporation\MCA\MMTShenanigans\prototypeMadness\mca-sw-loader\src\dist\ltbTest
[15876] LOADER: Setting sys.argv
[15876] LOADER: setting sys._MEIPASS
[15876] LOADER: importing modules from CArchive
[15876] LOADER: extracted struct
[15876] LOADER: running unmarshalled code object for struct...
[15876] LOADER: extracted pyimod01_os_path
[15876] LOADER: running unmarshalled code object for pyimod01_os_path...
[15876] LOADER: extracted pyimod02_archive
[15876] LOADER: running unmarshalled code object for pyimod02_archive...
[15876] LOADER: extracted pyimod03_importers
[15876] LOADER: running unmarshalled code object for pyimod03_importers...
[15876] LOADER: extracted pyimod04_ctypes
[15876] LOADER: running unmarshalled code object for pyimod04_ctypes...
[15876] LOADER: Installing PYZ archive with Python modules.
[15876] LOADER: PYZ archive: PYZ-00.pyz
[15876] LOADER: Running pyiboot01_bootstrap.py
[15876] LOADER: Running pyi_rth_subprocess.py
[15876] LOADER: Running pyi_rth_pkgutil.py
[15876] LOADER: Running pyi_rth_inspect.py
[15876] LOADER: Running mmtB.py
Traceback (most recent call last):
  File "mca-sw-loader\src\mmtB.py", line 24, in <module>
ModuleNotFoundError: No module named 'include.dockerInterface'
[15876] Failed to execute script 'mmtB' due to unhandled exception!
[15876] LOADER: OK.
[15876] LOADER: Manually flushing stdout and stderr
[15876] LOADER: Cleaning up Python interpreter.
```

**Comment by rokm** [comment]
Hmmm... at the start of the build process, you should get a message like
```
508 INFO: Extending PYTHONPATH with paths
['C:\\Users\carter.miller\\OneDrive - A Corporation\\test\\MMTShenanigans\\prototypeMadness\\test-sw-loader\\src']
```
Is that the case? And does the displayed path correspond to path that contains the `include˙ directory?

---

The hiddenimports are for the cases when modules are loaded lazily or indirectly (e.g., using `__import__(modname)` instead of `import modname˙), as PyInstaller does not support those functional import forms (or programmatic imports with module names stored in variables). 

So if you're using direct imports (`import include.dockerInterface˙), you shouldn't need hiddenimports. If the modules are still missing, this usually means that for some reason, PyInstaller cannot discover them in the first place (and hiddenimports make no difference in that case). 

But the directory containing the entry-point script should be automatically added to the search path (reflected in the afore-mentioned PYTHONPATH message).

**Comment by ghost** [comment]
> Is that the case? And does the displayed path correspond to path that contains the `include˙ directory?

Actually that is not the case...This is what I see:
```
['C:\\Users\carter.miller\\OneDrive - A Corporation\\test\\MMTShenanigans\\prototypeMadness']
```
So the include directory is technically in that hierarchy if we extend that path to src\include, but for whatever reason it is not finding those modules.  It is worth noting all of this code is inside a PyCharm project, is it possible that is influencing PYTHONPATH?  Because that path is the project root, though I marked the src/ directory as "sources root" in my project.

Okay, good note about the hidden imports.  That's what I suspected from past times that I've used them and based on the documentation, but out of desperation I tried them anyway.  Interestingly, if I don't have that hidden import for "include", the error message is different, and states the module not found is "include" instead of "include.dockerInterface" which I is why I kept pursuing that route.

**Comment by bwoodsend** [comment]
> Actually that is not the case...This is what I see:

I think there may be a genuine regression there. I saw [this](https://groups.google.com/g/pyinstaller/c/8Z1lJOnQWSs/m/KUCxuF_5AgAJ?pli=1) a few days ago which also seems to imply that the entry point script's parent directory is no longer being added to `sys.path`.

>  It is worth noting all of this code is inside a PyCharm project, is it possible that is influencing PYTHONPATH? 

Yes, it does. PyCharm adds your project's root to `sys.path` (which `PYTHONPATH` adds to). I wish it didn't and it's one reason I always try to encourage people to test their Python applications from the command line before attempting to ship them (with PyInstaller or otherwise).

---

On a somewhat unrelated note, if you package your code [like a Python package](https://python-packaging.readthedocs.io/en/latest/index.html) rather than trying to force Python into what appears to be a C++ style packaging layout, you should find things go a lot smoother w.r.t modules finding each other.

**Comment by rokm** [comment]
Hmmm... do `c:\\Users\carter.miller\\OneDrive - A Corporation\\test\\MMTShenanigans\\prototypeMadness\\test-sw-loader\\src` and its parent both contain an `__init__.py` file by any chance?

Looks like we don't always add the entry-point's parent directory, due to the following logic chain:
https://github.com/pyinstaller/pyinstaller/blob/7a9ab84ffbb3dfa01c336bd3c5474725d43935e6/PyInstaller/building/build_main.py#L257-L263

https://github.com/pyinstaller/pyinstaller/blob/7a9ab84ffbb3dfa01c336bd3c5474725d43935e6/PyInstaller/building/build_main.py#L377

https://github.com/pyinstaller/pyinstaller/blob/7a9ab84ffbb3dfa01c336bd3c5474725d43935e6/PyInstaller/utils/misc.py#L76-L101

**Comment by ghost** [comment]
> Yes, it does. PyCharm adds your project's root to sys.path (which PYTHONPATH adds to). I wish it didn't and it's one reason I always try to encourage people to test their Python applications from the command line before attempting to ship them (with PyInstaller or otherwise).

Yeah I've been testing this by making it into an executable previously, and from the command line sometimes (this is a weird tool that has to interact with both WSL2 and Windows...fml).

> On a somewhat unrelated note, if you package your code [like a Python package](https://python-packaging.readthedocs.io/en/latest/index.html) rather than trying to force Python into what appears to be a C++ style packaging layout, you should find things go a lot smoother w.r.t modules finding each other.

Haha, darn, you noticed!  Yeah 95% of our code is in C++, this is in Python due to its operating nature and deployment necessities.  
My structure is this:
```
src
├── include
│   ├── HostFileEditor.py
│   ├── WSLinterface.py
│   ├── ddsConfigEnums.py
│   ├── dockerInterface.py
│   ├── fileServer.py
│   ├── fileSystemInterface.py
│   ├── loaderDDSInterface.py
│   └── manifestParser.py
├── mmtB.py (what is being passed in to PyInstaller and has the imports)
```

And both src and include have their own __init__.py, so it is more python like due to include being in src, however, my inits are blank, they have no content.  Should they have content?  I'm browsing through that link you sent and it seems to suggest so...

> Hmmm... do c:\\Users\carter.miller\\OneDrive - A Corporation\\test\\MMTShenanigans\\prototypeMadness\\test-sw-loader\\src and its parent both contain an __init__.py file by any chance?

src has an init, so does include the directory above that (test-sw-loader) does not.

**Comment by ghost** [comment]
> On a somewhat unrelated note, if you package your code [like a Python package](https://python-packaging.readthedocs.io/en/latest/index.html) rather than trying to force Python into what appears to be a C++ style packaging layout, you should find things go a lot smoother w.r.t modules finding each other.

Okay, I have refactored my file structure to be more pythonic...so now it looks like this

```
Folder I Am In when I launch pyinstaller
├── HostFileEditor.py
├── WSLinterface.py
├── __init__.py
├── dockerInterface.py
├── fileServer.py
├── fileSystemInterface.py
├── loaderDDSInterface.py
├── ltbTest.spec
├── manifestParser.py
├── A.py
├── B.py (file being fed in that imports others in this same directory)
├── test_HostFileEditor.py
├── test_WSLinterface.py
├── test_ddsInterface.py
├── test_dockerInterface.py
├── test_fileServer.py
├── test_fileSystemInterface.py
├── test_EndToEnd.py
├── test_parser.py
├── tests_ddsTestUtilities.py
├── tests_dockerTestUtilities.py
├── tests_generalTestUtilities.py
```

Command I used (this is inside a .bat script launching from the same directory)
```
pyinstaller ^
--add-binary=..\dependencies\win-x64\nddscore.dll;. ^
--add-binary=..\dependencies\win-x64\nddsc.dll;. ^
--add-binary=..\dependencies\win-x64\msvcr120.dll;. ^
--add-binary=..\dependencies\win-x64\rtiddsconnector.dll;. ^
--onedir ^
--name=ltbTest ^
-y ^
mmtB.py
```

Error I see:
```
Traceback (most recent call last):
  File "swLoaderPkg\B.py", line 24, in <module>
ModuleNotFoundError: No module named 'dockerInterface'
[6488] Failed to execute script 'mmtB' due to unhandled exception!
```

Interesting part is that I had something working a couple weeks ago when I had my file structure like this when using PyInstaller 4.8.  So I'm not sure what's going here...

**Comment by rokm** [comment]
If there's an `__init__.py` next to entry-point script, we currently don't add that directory to the search path, but rather jump up and take the first parent directory that does not contain an `__init__.py`. So if you reorganize your code to have a proper package (with an `__init__.py`) and an entry-point script outside of the package, it should work.

In your previous layout, there was no reason for an `__init__.py` in `src`, since `src` was obviously not meant to be a package. Neither is your "folder you are in when you launch pyinstaller" in your current layout a package, really, so it doesn't need an `__init__.py`. 

(The going-up-the-directory-tree-if-`__init.py__`-is-encountered behavior doesn't make any sense, either, and we should probably take a closer look at it...)

**Comment by ghost** [comment]
> If there's an `__init__.py` next to entry-point script, we currently don't add that directory to the search path, but rather jump up and take the first parent directory that does not contain an `__init__.py`. So if you reorganize your code to have a proper package (with an `__init__.py`) and an entry-point script outside of the package, it should work.
> 
> In your previous layout, there was no reason for an `__init__.py` in `src`, since `src` was obviously not meant to be a package. Neither is your "folder you are in when you launch pyinstaller" in your current layout a package, really, so it doesn't need an `__init__.py`.
> 
> (The going-up-the-directory-tree-if-`__init.py__`-is-encountered behavior doesn't make any sense, either, and we should probably take a closer look at it...)

Ohhhhhhhhh okay this all clarified the previous comments for me...So as a convention question, I wrote this code all in classes, each has their own file, and I have essentially a "main" (B.py) that is importing things from all of those previous files.  So does it make sense to have all of those class files in one directory (which needs an init.py, and then have the "main" (or I believe what you are referring to as entry-point script) be outside that directory and ensure that it doesn't have an init.py?  Or is it more common to leave everything flat?  I was reading [this](https://python-packaging.readthedocs.io/en/latest/minimal.html#adding-additional-files) and I honestly wasn't too sure since that was for formal package installation.

**Comment by rokm** [comment]
I suppose both approaches are fair game. With the document you referenced, the idea is to create a package (e.g., `funniest`), which will be installed into environment's site-packages and can be imported by other code (packages or scripts). If you check [this part](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html), you'll see that the actual script is kept separate from the package (or, in the second approach, the script is generated via setuptools' entry-point scripts functionality).

If your project is not meant to be installed that way (i.e., you just want to turn it into PyInstaller-frozen application), then script-along-a-package or script-along-modules ("flat" structure) does not matter much. But, in the second approach, your source directory is not a package, so it doesn't need an `__init__.py` (plus this apparently causes the issues with PyInstaller).

I personally prefer to have my project's code in a package, both to keep things organized when I have multiple scripts using same classes, e.g.,
`myproject`
|- `__init__.py`
|- [some subpackages, submodules, and data files]
`program_cli.py`
`program_gui.py`
`utility_script1.py`
`utility_script2.py`

But also for namespace reasons. Because in a flat structure, if you name your module `json.py`, you will for example end up shadowing the python's own `json` module, with unpredictable results (perhaps issues already manifest in unfrozen version, or in frozen version, when PyInstaller collects only one `json` module). If you have a package, then your module is `myproject.json` which prevents shadowing at PyInstaller-collection level (you can, of course, still mix them up with import aliases, but that's a different problem).

**Comment by ghost** [comment]
> I personally prefer to have my project's code in a package, both to keep things organized when I have multiple scripts using same classes, e.g.,
myproject
|- __init__.py
|- [some subpackages, submodules, and data files]
program_cli.py
program_gui.py
utility_script1.py
utility_script2.py

Yeah I think I'll take this approach, I just tried it and everything still builds and runs fine pyinstaller it seems.  I have one random error showing up that doesn't impede the program's function at all but still shows up just upon startup...I'll look into it more and if needed file a separate issue.  

I'll close this now unless you wish to use it as a reminder for inspecting the behavior of how you search your base directory.

**Comment by bwoodsend** [comment]
I'm not sure what I want to do about [this](https://github.com/pyinstaller/pyinstaller/issues/6713#issuecomment-1083684058). I guess that the `get_path_to_toplevel_modules()` does make some sense if you have something like:
```
├── foo
│   ├── __main__.py
│   ├── sys.py
```
and you run PyInstaller on the `__main__.py`. Then you wouldn't want foo's submodules shadowing any other packages with the same name. But otherwise, it's a bit of a surprise and it's not what Python does.

**Comment by rokm** [comment]
> I'm not sure what I want to do about [this](https://github.com/pyinstaller/pyinstaller/issues/6713#issuecomment-1083684058). I guess that the `get_path_to_toplevel_modules()` does make some sense if you have something like:
> 
> ```
> ├── foo
> │   ├── __main__.py
> │   ├── sys.py
> ```
> 
> and you run PyInstaller on the `__main__.py`. Then you wouldn't want foo's submodules shadowing any other packages with the same name. But otherwise, it's a bit of a surprise and it's not what Python does.

Ah, `__main__.py` is the case this is supposed to handle. But we can infer that from the filename, and apply this top-level module search only if `__main__.py` is the name of the entry-point script?

**Comment by bwoodsend** [comment]
It could also be a submodule called `bar.py` which it expected to be invoked via `python -m foo.bar` although that is a lot less common.

**Comment by bwoodsend** [comment]
This does all seem to point towards PyInstaller needing an equivalent to Python's `-m` flag although I really don't want to go down that path.
