### ISSUE TITLE
__file__  issue in pyinstaller

### ISSUE THREAD

**Issue by zxo102** [pyinstaller/pyinstaller#6719]
Under Windows 10 and python 3.8,  func1.py located in the directory F: 

```import os
def func1():
   print("func1  os.path.realpath(__file__)) ===> ",os.path.realpath(__file__))

if __name__ == "__main__":
   func1()
```
After ```pyinstaller -F func1.py ```, running func1.exe returns
func1  os.path.realpath(__file__)) ===>  F:\Temp\_MEI254962\func1.py

with ```python func1.py```, output is
func1  os.path.realpath(__file__)) ===>  F:\func1.py

The wrong path of func1.py from func1.exe  caused hidden errors in my project :((

**Comment by bwoodsend** [comment]
That's correct behaviour. If `__file__` pointed to your original source file instead of inside the unpacked archive then you'd have to tell your users to copy your `func1.py` to `F:\func1.py` or the program will crash. The docs for using `__file__` are [here](https://pyinstaller.readthedocs.io/en/v4.10/runtime-information.html#using-file).

**Comment by rokm** [comment]
This behavior is to ensure that the frozen application is properly relocatable and that `__file__` attribute of the python module/script can be used for referencing data files located next to them. 

Therefore, in `onedir` build, the `__file__` of entry-point wills point in the same directory as the executable (because any collected data files will also be collected there), but in the `onefile` build, it points into the temporary directory where the collected resources are extracted (because executable needs to unpack itself). 

So if your code expects a file next to the executable, you have a design problem - that file should have been collected into the frozen bundle in the first place. (Or, if you really need it to be externalized and placed next to the onefile executable, you will need to create a frozen-app-specific codepath and reference it via `sys.executable`).
