### ISSUE TITLE
Pyinstaller 5.0 Linux "canberra-gtk-module" missing

### ISSUE THREAD

**Issue by codade** [pyinstaller/pyinstaller#6768]
I've created an app, which I already successfully deployed with pyinstaller for Windows and MacOS. Now I wanted to offer a Linux version, as well, which almost works except pyinstaller seems to not include all parts of GTK. The app uses PyGobject for its GUI and contains a browser-based dashboard, which can be opened through pressing a button which opens the webpage via the webbrowser module.
Starting the final binary works fine though the following is stated, when trying to open the webpage:
`Gtk-Message: 13:37:45.025: Failed to load module "canberra-gtk-module"
gio: https://example.com: No application is registered as handling this file"
`
I used pyinstaller -F -c Myapp.py to build the binary and also tried pyinstaller -D -c Myapp.py. This error doesn't occur on other platforms. libcanberra-gtk* are installed and it works without problems when executing the *.py-file directly.

I've seen that there was a similar issue a few years ago, which was solved by adding a hook for pywebview, which is not included anymore.
I appreciate any help!
Thanks

* Output of `pyinstaller --version`: ```5.0```
* Version of Python: 3.8 
* Platform: Linux (Ubuntu 20.04)-->
* How you installed Python: pre-installed
* Did you also try this on another platform? Does it work there? Yes Windows and macOS works

**Comment by rokm** [comment]
Can you provide a minimal reproducer (e.g., a window with a button that tries to open a web page)? 

I think canberra module missing is usually non-fatal, but the other part of the message suggests that either some Gio plugin was not collected (which would not be surprising, considering it has no direct link to python code or the collected Gio shared libs). But it might also be caused by xdg settings being overridden within the frozen bundle (I think I recall seeing an issue about our glib runtime hook overriding XDG_DATA_DIRS)...

**Comment by codade** [comment]
Hi rokm,

thanks for your answer. I thought canberra and Gio are somehow linked, but I'm not too familiar with that.
I shrinked the GUI code to only display the relevant button and attached it. On my machine it is working while directly executing but not in the frozen executeable.

```
import webbrowser
import gi

gi.require_version('Gtk', '3.0')

from gi.repository import Gtk, Gdk, Gio, GLib, Pango


class MainApp(Gtk.ApplicationWindow):

    def __init__(self):

        #Window properties
        Gtk.Window.__init__(self, title="Example")
        self.set_default_size(50, 50)
        self.set_position(Gtk.WindowPosition.CENTER)
        self.set_border_width(10)
        self.connect("delete_event", self.close_window)

        #vertical gridbox
        main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.add(main_box)

        #Dashboard button
        self.dashboard_btn = Gtk.Button.new_with_label('Dashboard')
        self.dashboard_btn.connect("clicked", self.open_dashboard, None)
        main_box.pack_start(self.dashboard_btn, False, False, 5)

        self.show_all()


    def open_dashboard(self, action, value):

        #open dashboard 
        webbrowser.open('https://startpage.com', new=1)


    def close_window(self, widget, origin):

        #close app
        Gtk.main_quit()


if __name__ == '__main__':

    app = MainApp()
    Gtk.main()
```

**Comment by rokm** [comment]
Thanks! On my system, the messages are
```
Gtk-Message: 10:28:47.840: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:28:47.840: Failed to load module "pk-gtk-module"
gio: https://startpage.com: No application is registered as handling this file
```
and the failed-to-load messages appear immediately at application start, so they are unrelated to the later gio error.

The gio error seems to be indeed caused by glib runtime hook overriding `XDG_DATA_DIRS` (and we have an issue opened for that - #3668):
https://github.com/pyinstaller/pyinstaller/blob/6811c873b8cf8a09a7ad7db1449626a72a64df05/PyInstaller/hooks/rthooks/pyi_rth_glib.py#L15

So as a work-around, you could try commenting out this line in your `site-packages/PyInstaller/hooks/rthooks/pyi_rth_glib.py`. Or extend it so that it prepends the new path to the existing paths, which is probably what the hook should be doing if we want to accommodate people trying to run system-provided programs. (On a side note, if you want to run a system-provided program, you might also want to restore `LD_LIBRARY_PATH` from `LD_LIBRARY_PATH_ORIG`, as discussed here: #6334)

**Comment by codade** [comment]
The canberra-missing info appears with startup on my system, as well. Thanks for the workaround. It seems to work, canberra is still not included, although I tried to restore `LD_LIBRARY_PATH`, but since it doesn't affect functionality, I can live with it. How comes that the GLib hook overriding `XDG_DATA_DIRS` doesn't affect MacOS and Windows versions but Linux?

**Comment by codade** [comment]
One more comment on the example.py. Pyinstaller creates a huge folder/file (depending on export mode) even for this small app. A closer look into the final folder showed that the "share" folder inside alone has over 180 MB, especially resulting from the "icons" subfolder. Is there a way to prohibit copying all icons and themes into the final "share" folder and rather just add one or two, e.g. the "adwaita" and "default" icon/theme subfolders?
Thanks

**Comment by rokm** [comment]
See https://pyinstaller.org/en/stable/hooks-config.html

**Comment by rokm** [comment]
> How comes that the GLib hook overriding `XDG_DATA_DIRS` doesn't affect MacOS and Windows versions but Linux?

Because `xdg-open` is linux-only.

**Comment by codade** [comment]
> See https://pyinstaller.org/en/stable/hooks-config.html

Many thanks for the information. I somehow missed the introduction of this feature in 4.5 version. Since the original problem is related to the #3668 issue rather than to the missing canberra-module, I close this issue.
