### ISSUE TITLE
python script repeats first command after converted to exe with pyinstaller

### ISSUE THREAD

**Issue by wezzoo** [pyinstaller/pyinstaller#6777]
I have a python script which looks like:

`    
    

    import time
    from selenium import webdriver
    from selenium.webdriver.common.keys import Keys
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support import expected_conditions as EC
    from selenium.common.exceptions import TimeoutException
    from selenium.common.exceptions import NoSuchElementException
    from selenium.webdriver.common.by import By
    import undetected_chromedriver.v2 as uc
    import requests 
    
    def main():

      y = input("input number: ")
      x = int (y)

      while x>0:
       try:

         driver = uc.Chrome()
         driver.get('url')
         driver.maximize_window()
         time.sleep(3)    

         User_Id = driver.find_element(By.ID, "Id")

         User_Id.send_keys(y)

         Next_Button = driver.find_element(By.ID, 'id').click()

         time.sleep(3)

         password = driver.find_element(By.NAME, 'password')

         password.send_keys(y)

         time.sleep(2)

         password_next_button = driver.find_element(By.XPATH, 'xpath')
         password_next_button.click()

         driver.quit()
     except:
         driver.quit()   
    if __name__ == '__main__':
      main()`

and it's working just fine as .py, but when i tried to convert it to executable it keeps repeating the first step (input number: )

Here's the pyinstaller code i use:

`pyinstaller --noconfirm --onefile --console --icon "icon.ico" --uac-admin  "myscript.py"`

**Comment by bwoodsend** [comment]
Mind including the imports so that we know what `uc` and `By` are? I'm guessing this is a selenium script but a *minimal reproducer* isn't a reproducer at all if we have to guess the bits you left out.

This is probably due to a `subprocess.run([sys.executable])` lurking around which would cause your application to keep respawning itself but we can't tell you where that is without knowing what `uc` is.

**Comment by wezzoo** [comment]
@bwoodsend sorry i forgot to include the imports, thanks for your comment.

**Comment by rokm** [comment]
`undetected-chromedriver` is by [default](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L120) using [`multiprocessing` instead of `subprocess`](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/b2e804e977c9cf3dd9c845474752cac142a72508/undetected_chromedriver/__init__.py#L387-L399).

If you want to use `multiprocessing` in a frozen application, you need to call [`multiprocessing.freeze_support`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) at the start of your program (before using any `multiprocessing` functionality). Otherwise, you end up with endless recursive process spawn, which in your case is held back by the `input`.

Alternatively, you can try setting `use_subprocess` to use `subprocess` module instead of `multiprocessing`.

**Comment by wezzoo** [comment]
@rokm thanks a lot for your answer, it's working but now I get EOFError when i run the program, do you have any idea to get this fixed?
thanks so much

**Comment by rokm** [comment]
Can we see the whole error message and the traceback?

**Comment by wezzoo** [comment]
@rokm thanks for your reply, and sorry for being late.
Here's the error message i get:

`input number: Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\myprograme\script.py", line 28, in g
    y = input("input number: ")
EOFError: EOF when reading a line`

every time i run the code i get only this error without asking for input.

**Comment by rokm** [comment]
Can we also see the updated code - where did you put the `multiprocess.freeze_support()` call? I cannot reproduce this with my modification of your example, and the `multiprocess`-spawned process should not be reaching the `input()`...

**Comment by wezzoo** [comment]
@rokm first of all thanks for your help, and here's my updated code:

`   


    import time
    from multiprocessing import Process, freeze_support
    from selenium import webdriver
    from selenium.webdriver.common.keys import Keys
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support import expected_conditions as EC
    from selenium.common.exceptions import TimeoutException
    from selenium.common.exceptions import NoSuchElementException
    from selenium.webdriver.common.by import By
    import undetected_chromedriver.v2 as uc
    import requests 

    def f():

      y = input("input number: ")
      x = int (y)

     while x>0:
       try:

         driver = uc.Chrome()
         driver.get('url')
         driver.maximize_window()
         time.sleep(3)    

         User_Id = driver.find_element(By.ID, "Id")

         User_Id.send_keys(y)

         Next_Button = driver.find_element(By.ID, 'id').click()

         time.sleep(3)

         password = driver.find_element(By.NAME, 'password')

         password.send_keys(y)

         time.sleep(2)

         password_next_button = driver.find_element(By.XPATH, 'xpath')
         password_next_button.click()

         driver.quit()
    except:
         driver.quit()   
    if __name__ == '__main__':
        freeze_support()
        Process(target=f).start()

**Comment by rokm** [comment]
I get `EOFError: EOF when reading a line` when trying to run the above code in python interpreter, without PyInstaller involved at all...

Why are you running your main function (`f`) in a `Process()`, anyway? Just call it normally (`f()`)...

**Comment by wezzoo** [comment]
@rokm thanks so much for your appreciated help, it's finally working just fine (thanks to your help) as .py and also as exe.
