### ISSUE TITLE
Error in Code

### ISSUE THREAD

**Issue by pknight213** [pyinstaller/pyinstaller#6781]
I just download pyinstaller and ran into the "PyInstaller cannot check for assembly dependencies" error.  Looking on the internet, the fixes were to edit the compat.py.  When I edited the file in VSC I notice an error at line 454 (Tuple expression not allowed in type annotation)

![Capture](https://user-images.githubusercontent.com/104571408/165754452-41b24c49-6f09-4c43-b3d3-026a2de8e06b.JPG)

**Comment by bwoodsend** [comment]
Turns out it's really equivalent to a union of types rather than a tuple of them.
```python
>>> import beartype
>>> beartype.beartype(exec_command_all).__annotations__
{'cmdargs': <class 'str'>, 'encoding': <class 'str'>, 'return': typing.Union[int, str]}
```
Since we don't use `mypy` or `beartype` and `exec_command_all()` shouldn't be considered as public API, those annotations are purely cosmetic so I don't really mind if they're wrong but I won't object if someone wants to fix them.

**Comment by Legorooj** [comment]
I just pushed 722b128657a1a421 which might help?

**Comment by bwoodsend** [comment]
It'll do.
