### ISSUE TITLE
Upgrade bootloader zlib instance to 1.2.12

### ISSUE THREAD

**Issue by scdub** [pyinstaller/pyinstaller#6804]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```develop```
* Version of Python: affects all versions
* Platform: affects all platforms
* How you installed Python: installation type independent

### zlib upgrade request

Zlib has released a [1.2.12](https://www.zlib.net/zlib.html) version which addresses a number of issues, including the longstanding CVE-2018-25032. Please upgrade the bootstrapper zlib copy to 1.2.12 in order to address this issue and pick up other fixes in 1.2.12.

**Comment by bwoodsend** [comment]
Hmm, @rokm keep me right here:

* The copy of zlib's source code we have is used only to be statically compiled into the Windows bootloaders. When statically compiling, we don't need to care about ABI compatibility so upgrading our vendored zlib won't break anything on Windows.
* On every other platform we ignore our own copy dynamically link against zlib using system provided zlib development headers. Upgrading our vendored zlib won't make any difference because it's not used. We don't need to update zlib on the build machines/docker images since it's the runtime version (i.e. the one on the end user's machine) that matters.

So upgrading our vendored zlib is safe and that's all that we need to do?

**Comment by rokm** [comment]
> So upgrading our vendored zlib is safe and that's all that we need to do?

Yeah, I think we just need to update the bundled zlib sources. The ABI didn't seem to change between 1.2.11 and 1.2.12 (soversion remains 1), so the eventual upgrade on linux distributions should not affect the current prebuilt bootloaders.

I'll update the bundled zlib sources. I was going to create a list of changes we had (some compiler warning fixes I made a while ago, and some recent spelling fixes), but it turns out we can get rid of some of those files, anyway, so I'll just need to carry over couple of spelling fixes...

**Comment by scdub** [comment]
Thanks for the quick responses on this! I can confirm that this issue was found specifically on Windows. Searching the repository, I do see [this line](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/Dockerfile#L38) referencing 1.2.11 in the bootloader dockerfile, but am not familiar with the context in which this is used.

**Comment by bwoodsend** [comment]
The one in the dockerfile shouldn't matter because it's dynamically linked so the end user gets whatever version of zlib they have installed system-wide - the code from zlib 1.2.11 never leaves the build container (which is what that file defines).

**Comment by scdub** [comment]
After regenerating the bootstrap executables with `python ./waf all`, I can confirm that Pyinstaller executables on Windows now contain zlib 1.2.12. It looks like typically these are rebuilt at a release, zlib 1.2.11 will be used until that part is synchronized. Thanks for the quick work on this, much appreciated!

**Comment by bwoodsend** [comment]
Hmm, does it make sense for the vulnerability to actually be exploited in a PyInstaller context? The bug is in deflation and we only use deflation to extract the application from a onefile executable so to use this vulnerability and attacker would create a onefile build, deliberately corrupt the embedded archive so that zlib does something it shouldn't when unpacking (e.g. start up an ssh daemon), then give that executable to a victim to run. But if the victim already mistakenly trusts the attacker to run his/her application then the attacker could just freeze malicious code and achieve the same outcome for much less effort.

**Comment by bwoodsend** [comment]
If you can see a way around that then we'll have to do a release soon and try and push people onto the new version. Unfortunately, it's a long chain - we release, downstream projects upgrade, rebuild and release, then they have to encourage their users to upgrade too.

**Comment by scdub** [comment]
> Hmm, does it make sense for the vulnerability to actually be exploited in a PyInstaller context?

I think that's a fair assessment of the relevance of this issue to PyInstaller. In my case, I have a small collection of PyInstaller executables which are bundled as part of a broader application. This application is used by many organizations which use static scanning tools to identify potential security risks in the code they deploy, and they identify this one as being present in zlib and unpatched, and typically these organizations weight things based on CVE severity, sometimes without proper assessment of the attack vector relative to their use. I agree the actual risk is low, and holding on to this change until there is a broader collection of changes which require a release is fine with me, I don't think it alone necessitates cutting a release.
