### ISSUE TITLE
Sponsoring this project

### ISSUE THREAD

**Issue by mhucka** [pyinstaller/pyinstaller#6820]
PyInstaller is fantastic, and I think I'm not the only person who would be willing to sponsor it via GitHub's sponsorship facility. Would you consider adding a GitHub "Sponsor" button to this project?

**Comment by bwoodsend** [comment]
Thanks for offering your support but I don't think that there's anyone left who would take it. Harmut, who was the one originally wanting funding, gave up due to lack of getting funding. He might accept _retrospective_ funding but it'll be a thank you token rather than an incentive to improve PyInstaller. Rok can't stomach the bureaucracy of his local tax office w.r.t accepting donations. I'm already overpaid by my day job. @Legorooj _might_ take you up on it if you cherry pick a couple of issues/features you want him to work on in return...

**Comment by Legorooj** [comment]
I should probably add a sponsors file to the repo so it's more visible that I'm open to that.

**Comment by Legorooj** [comment]
Added a Sponsor Button to the project. Thanks for suggesting this!
