### ISSUE TITLE
dlls redundant copy (pyside6-essentialls)

### ISSUE THREAD

**Issue by yahym** [pyinstaller/pyinstaller#6830]
**Is your feature request related to a problem? Please describe.**
In a `pyside6-essentialls` project, when the application is built using `PyInstaller`, there are couple of `*.dll` files (available inside the python packages imported) which are copied twice.
e.g. picture below: Left files are available on `Application root path`, Right Files are available on `Application root path\PySide6` folder
![image](https://user-images.githubusercontent.com/16311538/169005117-2ab06465-047a-41af-8587-14cd634fe49a.png)

**Describe the solution you'd like**
Would be nice if it would be possible to include in the build only one instance of a `*.dll` file (or to allow to configure this).
This will decrease a lot the size of the build.

**Describe alternatives you've considered**
Manual deletion of redundant `*.dll` from the final build could work, but is difficult to evaluate the later impact.

**Additional context**
**Info**: Seems that if `Qt6*.dll` files are removed from `Application root path`, there is no impact on the application functionality, means that the `*.dll` from PySide6 folder are used.

This is applicable to all `*.dlls` files which could be available on any python package (not only by `pyside6-essensialls`), used by the application.

**Comment by rokm** [comment]
Can you provide a minimal example that reproduces the problem? Both a simple .py program and the PyInstaller build command you are using?

Because I cannot reproduce this. With the following test program:
```python
from PySide6 import QtWidgets, QtCore, QtGui, QtQuick

import sys
import signal

signal.signal(signal.SIGINT, signal.SIG_DFL)

app = QtWidgets.QApplication(sys.argv)

window = QtWidgets.QWidget()
window.setWindowTitle("Hello")
window.show()

app.exec()
```
built with `pyinstaller --clean --noconfirm program.py`, I get a frozen program where program root directory contains all Qt6 DLLs and PySide6 sub-directory contains corresponding .pyd extensions, as expected.:
<details><summary>List of DLLs in root folder</summary>
<p>

```
Qt6Core.dll
Qt6Gui.dll
Qt6LabsAnimation.dll
Qt6LabsFolderListModel.dll
Qt6LabsQmlModels.dll
Qt6LabsSettings.dll
Qt6LabsSharedImage.dll
Qt6LabsWavefrontMesh.dll
Qt6Network.dll
Qt6OpenGL.dll
Qt6Qml.dll
Qt6QmlCore.dll
Qt6QmlLocalStorage.dll
Qt6QmlModels.dll
Qt6QmlWorkerScript.dll
Qt6QmlXmlListModel.dll
Qt6Quick.dll
Qt6QuickControls2.dll
Qt6QuickControls2Impl.dll
Qt6QuickDialogs2.dll
Qt6QuickDialogs2QuickImpl.dll
Qt6QuickDialogs2Utils.dll
Qt6QuickLayouts.dll
Qt6QuickParticles.dll
Qt6QuickShapes.dll
Qt6QuickTemplates2.dll
Qt6QuickTest.dll
Qt6QuickTimeline.dll
Qt6Sql.dll
Qt6Svg.dll
Qt6Test.dll
Qt6Widgets.dll
```
</p></details>

<details><summary>Contents of PySide6 sub-directory</summary>
<p>

```
plugins
qml
QtCore.pyd
QtGui.pyd
QtNetwork.pyd
QtOpenGL.pyd
QtQml.pyd
QtQuick.pyd
QtWidgets.pyd
translations
```

</p></details>

If I build in environment that has full `PySide6` installed instead of just `pyside6-essentials`, the root directory contains additional DLLs, but the PySide6 sub-directory contains same extensions.

Are you perhaps using `--collect-all` or `--collect-binaries` for the PySide6?

**Comment by yahym** [comment]
**Info**: With your proposed `program.py` I cannot reproduce the redundancies, even if the `.spec` files seems similar.
- batch call is: `.spec --log-level WARN --clean -y --console`
- no additional PySide6 instructions in `.spec`

```
pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)
    
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='Tool',
    debug=False,
    strip=False,
    upx=True,
    console=True,
    icon='tool.ico',
    version='version.rc',
)
```
where `a.binaries` is empty.

I will come back with more details, after I will reproduce.
Thank you for  your fast answer.

**Comment by yahym** [comment]
Coming back... Seems that pyinstaller collects all dll properly.
Processing was done and `a.binaries` were update with additional list of `dll`.

Your answer helped me find the reason why redundant dlls were copied on my project.

Thank you.
