### ISSUE TITLE
Every call to joblib Parallel creates a new tkinter window on MacOS

### ISSUE THREAD

**Issue by 1155159410** [pyinstaller/pyinstaller#6852]
## Description of the issue

This is a bug related to two libraries: `tkinter` and `joblib`.

The below example code can run perfectly in IDE (PyCharm), but it bugs when using the executable created with `pyinstaller`. The command line to create the executable is as follow: `pyinstaller -F main.py`.

The excepted behavior: every time when pressing the button in the `tkinter` window, `func called` should be printed in the terminal. And no more other actions.
The actual behavior (running the executable created with `pyinstaller`): every time when pressing the button, besides printing `func called` in the terminal, a new `tkinter` window is created after a few seconds.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.1```
* Version of Python (`sys.version`): 3.10.4, packaged by conda-forge, Clang 12.0.1
* Platform: macOS 12.3.1 (ARM64)
* How you installed Python: brew, miniforge
* Did you also try this on another platform? Does it work there?
I have also tried to build the executable in Windows (AMD64) with the same command (`pyinstaller -F main.py`). The executable file runs fine in Windows (no new `tkinter` window is created when pressing the button). Only the macOS platform has this problem. But I do not have an AMD64 macOS platform. Thus, I am not sure if it is a problem with ARM or macOS.

### A minimal example program which shows the error

```
from joblib import Parallel, delayed
import tkinter as tk


def f():
    print('func called')


if __name__ == '__main__':
    root = tk.Tk()

    button = tk.Button(root,
                       command=lambda: Parallel(n_jobs=-1, backend='threading')(delayed(f)() for _ in range(1)),
                       text='func')
    button.pack()

    root.mainloop()
```

**Comment by rokm** [comment]
In a frozen application that uses `multiprocessing` (in this case, `joblib` is using it), you need to call [`multiprocessing.freeze_support()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) at the beginning of your program (before using any `multiprocessing` functionality, but also before importing GUI packages and creating the UI). 

That's because `multiprocessing` re-runs the program's executable for the helper process, and unless `multiprocessing.freeze_support()` is called to divert the execution in these helper processes to the multiprocessing code (PyInstaller's [runtime hook](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py) overrides this function to do so), each subprocess executes your main program's code...

<details><summary>Fixed example</summary><p>

```python
import multiprocessing
multiprocessing.freeze_support()

from joblib import Parallel, delayed
import tkinter as tk


def f():
    print('func called')


if __name__ == '__main__':
    root = tk.Tk()

    button = tk.Button(root,
                       command=lambda: Parallel(n_jobs=-1, backend='threading')(delayed(f)() for _ in range(1)),
                       text='func')
    button.pack()

    root.mainloop()

```

</p></details>

**Comment by 1155159410** [comment]
Thank you for your help!

Now it fixes with `multiprocessing.freeze_support()`.

**Comment by TillMacher** [comment]
I am still facing this issue under following conditions:
- PyInstaller version 5.2
- python version 3.7 and 3.9 (tested both)
- tested on MacOS Monterey (M1 chip) and Ubuntu 20.04.4

So I wrote a script called dummy.py to emulate the error I am facing in my project: It runs perfectly when using python3 (.7 or .9) but crashes when using the executable created with `pyinstaller`

```
import multiprocessing
multiprocessing.freeze_support()
import sys
from joblib import Parallel, delayed
import PySimpleGUI as sg

def parallel_function(pair):
    print(pair[0])
    print(pair[1])
    print('')

def main():
        layout = [
                [sg.Text('This is a dummy UI', size=(20,1))],
                [sg.Button('Parallel')],
                [sg.Button('Exit')]]

        window = sg.Window('Test', layout)

        while True:

            event, values = window.read()

            if event == 'Parallel':
                window.hide()
                sg.Popup('Do something in parallel!')

                pairs = [['a', 'b']]*10
                Parallel(n_jobs = 4)(delayed(parallel_function)(pair) for pair in pairs)

                sg.Popup('Done')

                window.UnHide()

            if event is None or event == 'Exit':
                sys.exit()

if __name__ == '__main__':
    multiprocessing.freeze_support()
    main()
```

The executable was created with the command: `pyinstaller --noconfirm dummy.py`.
As far as I can see the `multiprocessing.freeze_support()` command is added in the correct places, right?
According to this [thread](https://stackoverflow.com/questions/2073942/multiprocessing-problem-pyqt-py2exe/2196650#2196650) it should also be inlcuded in the `if __name__ == '__main__'` section.

However, on the [python docs page](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) it reads: "Calling `freeze_support()` has no effect when invoked on any operating system other than Windows. In addition, if the module is being run normally by the Python interpreter on Windows (the program has not been frozen), then `freeze_support()` has no effect". This got me confused since then adding `multiprocessing.freeze_support()` should not work on Ubuntu or MacOS in the first place.

Probably I am overlooking something, but any solution on how to fix this problem would be great! Thanks!

**Comment by rokm** [comment]
> As far as I can see the `multiprocessing.freeze_support()` command is added in the correct places, right?

Yes, but *are* you using `multiprocessing`? As far as I remember, the default backend for `joblib` is `loky`, and that does not work with PyInstaller: https://github.com/orgs/pyinstaller/discussions/5773#discussioncomment-659216

Do note that the OP had `backend='threading'` passed to their `Parallel` constructor...

**Comment by rokm** [comment]
> Do note that the OP had `backend='threading'` passed to their `Parallel` constructor...

Although for `multiprocessing` instead of `loky`, you'll probably need to pass `backend='multiprocessing'`...

**Comment by TillMacher** [comment]
Thanks for the quick reply! It works perfectly now!

However, one should not use `backend='multiprocessing'` but `backend='threading'`. Otherwise Parallel will not wait for the jobs to be finished and multiple windows will appear when run as pyinstaller executable.

**Comment by rokm** [comment]
Does `backend='threading'` use multiple processes, though? The name implies it uses (python) threads, which means you don't have real concurrency...
