### ISSUE TITLE
Packaging fails on Windows x86 (32-bit) systems, prompting a memory error.

### ISSUE THREAD

**Issue by xiezhoubin** [pyinstaller/pyinstaller#6874]
My attempt to package on a Windows x86 (32-bit) system failed, prompting a memory error. The python version is 3.9.7 x86. At the same time, I try to package on Windows x64 (64 bit) system. The python version is 3.9.7 x64, but the same program can be packaged successfully.
The final size of the EXE program should be about 700MB.At the same time, after testing, if the size of the packaged program is less than 500MB, there is basically no problem.

![image](https://user-images.githubusercontent.com/75734559/172138403-57781e74-4deb-4cf9-b7e6-9a53dfa5496b.png)
![image](https://user-images.githubusercontent.com/75734559/172138812-00aec219-bbcc-433c-96d1-ec3b6eae00d3.png)

**Comment by rokm** [comment]
This looks like memory shortage problem. How much RAM do you have available on your Windows x86 system?

**Comment by xiezhoubin** [comment]
> 这看起来像内存短缺问题。您的 Windows x86 系统上有多少可用 RAM？

16G.

**Comment by xiezhoubin** [comment]
![image](https://user-images.githubusercontent.com/75734559/172181880-16916882-d642-4af8-882f-922bee2f7f94.png)

**Comment by rokm** [comment]
This is 64-bit system, is it not? Is the 32-bit build failing on native 32-bit system, or are you running 32-bit python on this system as well?

**Comment by xiezhoubin** [comment]
> 这是64位系统，不是吗？32 位构建是否在本机 32 位系统上失败，或者您是否也在此系统上运行 32 位 python？

I installed Python 3.7.9 x86 on my computer. I am packing on a 64 bit system, that is, the computer in the figure.
![image](https://user-images.githubusercontent.com/75734559/172194823-bbe3eae4-0374-4172-adbd-8f84630262bd.png)

**Comment by rokm** [comment]
OK. In that case, the memory limit (presumably for the whole process) should still be around 2 GB... Do you have any way of checking what the memory consumption is like during the build and before the error is hit (even using Task Manager, if there's no better tool available)?

---

I suppose a work-around would be to comment this line in your 32-bit PyInstaller installation:
https://github.com/pyinstaller/pyinstaller/blob/2df8314ffaedd95ddc9e2871237e2f2188d3735e/PyInstaller/building/api.py#L768

and see if the build succeeds. 

If it does, you can manually fix-up the exe headers by opening python console (in 64-bit python, or even 32-bit one, if there is less memory pressure) and running:

```python
import time
from PyInstaller.utils.win32 import winutils
winutils.fixup_exe_headers(r'dist\program_name.exe`, time.time())
```

**Comment by xiezhoubin** [comment]
> ```python
> winutils.fixup_exe_headers(r'dist\program_name.exe`, time.time())
> ```

The above method is OK. I found that after commenting out the line "winutils.fixup\u exe\u headers (build\u name, build\u timestamp)", the packaging speed of the whole program is very fast. In addition, even if you do not use the code to manually repair the EXE header, the packaged program can run normally. What is the reason?

**Comment by xiezhoubin** [comment]
> > ```python
> > winutils.fixup_exe_headers(r'dist\program_name.exe`, time.time())
> > ```
> 
> The above method is OK. I found that after commenting out the line "winutils.fixup\u exe\u headers (build\u name, build\u timestamp)", the packaging speed of the whole program is very fast. In addition, even if you do not use the code to manually repair the EXE header, the packaged program can run normally. What is the reason?

If you execute the repair exe code, it will still report an error!
![image](https://user-images.githubusercontent.com/75734559/172437110-9cc70bab-e0cc-4bcb-b5c4-94ae26508091.png)

**Comment by rokm** [comment]
> > ```python
> > winutils.fixup_exe_headers(r'dist\program_name.exe`, time.time())
> > ```
> 
> The above method is OK. I found that after commenting out the line "winutils.fixup\u exe\u headers (build\u name, build\u timestamp)", the packaging speed of the whole program is very fast. 

Commenting out this line should not have any effect on the speed of other building steps (but on subsequent build runs, the build might be re-using cached results, unless you specify `--clean`). On the other hand, in order to fixup the headers, the whole exe needs to be read (so that PE checksum can be computed) - but I imagine that is also not the speed-up you are observing, because that `MemoryError` occurs while reading the file... Or are you talking about speed-up of 64-bit build?

> In addition, even if you do not use the code to manually repair the EXE header, the packaged program can run normally. What is the reason?

The headers fix-up does two things:
- it sets the build timestamp to current time (as opposed to the time when pre-built bootloaders were compiled)
- it recomputes the PE checksum (which should help against the exe being flagged as malware by anti-virus programs, at least in theory...)

Neither of these are critical, and the program can run without them being corrected/recomputed.

**Comment by rokm** [comment]
> If you execute the repair exe code, it will still report an error!

And if you do it from 64-bit python?

**Comment by xiezhoubin** [comment]
> > If you execute the repair exe code, it will still report an error!
> 
> And if you do it from 64-bit python?

That's all right.

**Comment by xiezhoubin** [comment]
> > > If you execute the repair exe code, it will still report an error!
> > 
> > 
> > And if you do it from 64-bit python?
> 
> That's all right.

Only x86 will report an error.

**Comment by rokm** [comment]
> > > > If you execute the repair exe code, it will still report an error!
> > > 
> > > 
> > > And if you do it from 64-bit python?
> > 
> > 
> > That's all right.
> 
> Only x86 will report an error.

I guess that means that 32-bit python process does not get enough memory to load and process an exe of that size.

**Comment by xiezhoubin** [comment]
> > > > > If you execute the repair exe code, it will still report an error!
> > > > 
> > > > 
> > > > And if you do it from 64-bit python?
> > > 
> > > 
> > > That's all right.
> > 
> > 
> > Only x86 will report an error.
> 
> I guess that means that 32-bit python process does not get enough memory to load and process an exe of that size.

Maybe so.

**Comment by rokm** [comment]
I did some tests using a `onefile` build with a 700MB (randomly generated) data file, and I can reproduce the `MemoryError` in 32-bit python.  Also, as you observed, the headers fix-up *does* indeed take far more time than it should.

The first reason is that when loading PE headers, we use `fast_load=False`:
https://github.com/pyinstaller/pyinstaller/blob/51ff689509391921bdce42848f3a077dcbb40ca0/PyInstaller/utils/win32/winutils.py#L159
This ensures that all headers are loaded, but also triggers [a byte statistics collection](https://github.com/erocarrera/pefile/blob/0d5ce5e0193c878cd57636b438b3746ffc3ae7e3/pefile.py#L2862-L2876) that takes several minutes for a large EXE. We can avoid this competely by using `fast_load=True` and calling `pe.full_load()` to load all headers.

The second reason is the PE checksum computation itself; the pure-python `pefile.PE.compute_checksum` takes several minutes with large (~700MB) files. We could switch to using win32 function `MapFileAndCheckSumW`, which reduces the processing time from minutes to seconds, but the problem is that in spite of being a widechar variant, it doesn't work for paths that contain characters that are not representable in the current codepage (due to internally calling `MapFileAndCheckSumA`). But we can implement equivalent functionality using `OpenFileW`, `CreateFileMappingW`, `MapViewOfFile`, and `CheckSumMappedFile`.

Can you try https://github.com/pyinstaller/pyinstaller/pull/6881 and see if these changes improve the situation in your 32-bit environment? In my case, it also reduced the memory footprint to the extent that the initial test onefile program with 700 MB data file can build without `MemoryError` now.

**Comment by xiezhoubin** [comment]
When will the next version be released so that I can use it.

**Comment by rokm** [comment]
Probably sometimes towards the end of this month. If you're in a hurry, you can install and use develop branch:
`pip install git+https://github.com/pyinstaller/pyinstaller.git@develop`
