### ISSUE TITLE
Hidden imports not found! error, common fixes not working

### ISSUE THREAD

**Issue by klemenz991** [pyinstaller/pyinstaller#6931]
https://stackoverflow.com/questions/72846259/failing-to-compile-a-python-tkinter-game-to-exe-with-pyinstaller

python code [hangmanfinal.txt](https://github.com/pyinstaller/pyinstaller/files/9040625/hangmanfinal.txt)
build and execution log [build and execution.txt](https://github.com/pyinstaller/pyinstaller/files/9040627/build.and.execution.txt)

**Comment by rokm** [comment]
The missing hidden imports warnings are harmless, and have no impact on your program...

```
[6488] LOADER: Running hangmanfinal.py
# tkinter not found in PYZ
# code object from 'C:\\Users\\Klemen\\AppData\\Local\\Temp\\_MEI14402\\tkinter\\__init__.pyc'
...
import _bootlocale # loaded from Zip C:\Users\Klemen\AppData\Local\Temp\_MEI14402\base_library.zip\_bootlocale.pyc
[6488] LOADER: OK.
[6488] LOADER: Manually flushing stdout and stderr
[6488] LOADER: Cleaning up Python interpreter.
# clear sys.audit hooks
...
# destroy _frozen_importlib
[1440] LOADER: Back to parent (RC: 0)
[1440] LOADER: Doing cleanup
...
```

And "common fixes" are not working here because there is no PyInstaller-related error to be fixed in the first place...

The attached code (`hangmanfinal.txt`) creates a bunch of UI elements (window, images, buttons), initializes state, loads the list of words, creates some more labels, then calls `initialize_start` and exits afterwards because it doesn't enter tkinter's main loop anywhere. The places where `window.mainloop()` is actually called are unreachable - the `initialize_easy`, `initialize_medium`, `initialize_hard` functions are called as button callbacks, but those buttons are never going to be shown...

So that "Game in python runs well" is rather an overstatement, because the unfrozen python script behaves in exactly same way.

**Comment by klemenz991** [comment]
Thanks, but you are wrong about the game not working in python, it does

**Comment by rokm** [comment]
> Thanks, but you are wrong about the game not working in python, it does

The attached [hangmanfinal.txt](https://github.com/pyinstaller/pyinstaller/files/9040625/hangmanfinal.txt) script does not.

Perhaps you have multiple versions of the script, and are running a different one in python...

**Comment by klemenz991** [comment]
Python opens the tkinter window without calling mainloop, you don't even have the .png and .txt files to verify

**Comment by klemenz991** [comment]
I can comment out all mainloop statements and it still works...

**Comment by bwoodsend** [comment]
You mean that it works in Spyder/Jupyter notebooks/IPython but you've never ran it directory from `cmd`?

**Comment by klemenz991** [comment]
It worked in IDLE. Anyways, now it works everywhere
