### ISSUE TITLE
encypted onefile exe fails to run on some windows 11 machines

### ISSUE THREAD

**Issue by ta946** [pyinstaller/pyinstaller#6991]
## Description of the issue

script packaged as onefile using `key` command to encrypt, fails to run on some windows 11 machines (works fine for others)
creating the exe without encyption works for those machines

The exe was created on a windows 10 machine and sent online to be downloaded on the win 11 machine.
mentioning this as it always gets flagged as untrusted source. unblocking or running as administrator does nothing.
then the file automatically gets deleted after attempting to run it.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.1```
* Version of Python: 3.8
* Platform: Windows 10 (then distrubuted to win 11 machine)
* How you installed Python: conda
* Did you also try this on another platform? Does it work there? works on windows 10, but not 11

### Stacktrace / full error message

```
Error creating child process!
CreateProcessW: Access is denied.
```

**Comment by bwoodsend** [comment]
That's your antivirus. And for once it's actually targeting something suspicious (i.e. code obfuscation) rather than memorising checksums. The [designated issue template](https://github.com/pyinstaller/pyinstaller/blob/7875d7684c6ddad90e91af9141229083ebb1297f/.github/ISSUE_TEMPLATE/antivirus.md) tells you all you can meaningfully do.

And FWIW, the `--key` option will be getting removed soon since the encryption is so easily reverse engineered that it's not protecting anything.

**Comment by ta946** [comment]
thanks for the heads up!
