### ISSUE TITLE
pyinstaller -w --onedir main.py opens and closes immediately

### ISSUE THREAD

**Issue by kanewi11** [pyinstaller/pyinstaller#6992]
```pyinstaller -w --onedir main.py``` on macOS opens and closes immediately, the file ```main.app/Contents/MacOS/main``` opens, what to do?

im use tkinter

**Comment by rokm** [comment]
Is `main.py` a GUI program?

**Comment by kanewi11** [comment]
> Is `main.py` a GUI program?

Tkinter yes

**Comment by rokm** [comment]
Any chance we can see the minimal reproducer, then?

**Comment by rokm** [comment]
Or, you can try wrapping your whole entry-point script into a try/catch block, and write the exception information to a fixed location (e.g., your home directory), like suggested here: https://github.com/pyinstaller/pyinstaller/issues/5154#issuecomment-752203855.

So if your program is crashing with uncaught exception, you'll know what's happening.

**Comment by kanewi11** [comment]
> Or, you can try wrapping your whole entry-point script into a try/catch block, and write the exception information to a fixed location (e.g., your home directory), like suggested here: [#5154 (comment)](https://github.com/pyinstaller/pyinstaller/issues/5154#issuecomment-752203855).
> 
> So if your program is crashing with uncaught exception, you'll know what's happening.

https://drive.google.com/file/d/1RDAdi2Q85KHRBdsDSHVQoJReJPqukD-z/view?usp=sharing

**Comment by rokm** [comment]
Ah, I meant source code, not the binary.

**Comment by kanewi11** [comment]
error.log clear

**Comment by kanewi11** [comment]
> Ah, I meant source code, not the binary.

Oh im sorry, 1 second

**Comment by kanewi11** [comment]
> Ah, I meant source code, not the binary.

https://drive.google.com/drive/folders/1ZBkli3uoGJh-ByVIIIazojrwM6rZDCTn?usp=sharing

**Comment by rokm** [comment]
service/parser.py, line 15:
> proxies = open(f'{os.getcwd()}/proxy.txt').read().split('\n')

This assumes that `proxy.txt` is in current working directory. Which is definitely not the case when you launch an .app bundle. I suppose running `main.app/Contents/MacOS/main` only because you are running it from the source directory...

That `f'{os.getcwd()}/proxy.txt'` should be replaced with `os.path.join(os.path.dirname(__file__), '..', 'proxy.txt')` or with `os.path.join(sys._MEIPASS, 'proxy.txt')` under `if getattr(sys, 'frozen', False):` check for frozen application codepath. 

EDIT: you actually need to use `os.path.join(sys._MEIPASS, 'proxy.txt')` in frozen codepath, because `service` directory does not exist in the frozen application. But you could move the `proxy.txt` into `service`, and then reference it via `os.path.join(os.path.dirname(__file__), 'proxy.txt')` in both frozen and unfrozen codepath. But you'd need to ensure it is also collected into `service` subdirectory instead of the top-level frozen application directory (`--add-data path/to/service/proxy.txt:service` instead of `--add-data path/to/service/proxy.txt:.`).

----

By the way, with exception catching I meant the whole entry-point script:

```python
try:
    from service.parser import app

    if __name__ == '__main__':
        app.mainloop()
except Exception as e:
    import traceback
    with open('/Users/username/error.log', 'w') as fp:
        fp.write(f"ERROR {e}\n\n")
        traceback.print_exc(file=fp)
```
This gives:
```
ERROR [Errno 2] No such file or directory: '//proxy.txt'

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "service/parser.py", line 15, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '//proxy.txt'
```

**Comment by kanewi11** [comment]
> 

I did this before, but I forgot to update the Google disk file. The problem was in the loguru, you had to put the file in there too, otherwise he couldn't access it, thank you very much and sorry for the trouble 😊
