### ISSUE TITLE
Issue with pycryptodome on Raspberry Pi OS

### ISSUE THREAD

**Issue by razed11** [pyinstaller/pyinstaller#7047]
I'm porting an application that ran on Raspbian Jessie to Raspberry Pi OS Bullseye. A change I made is to build within a virtualenv-based virtual environment (vs. say conda). The application builds without errors. It runs successfully when I run launch the application from the virtual environment. However I get this error when I run the executable produced by pyinstaller:

```
   File "Crypto/Cipher/_mode_gcm.py", line 99, in <module>
   File "Crypto/Cipher/_mode_gcm.py", line 90, in _get_ghash_clmul
   File "Crypto/Util/_cpu_features.py", line 46, in have_clmul
 AttributeError: 'NoneType' object has no attribute 'have_clmul'
```

The file `_cpu_features.py` contains the following:

```
_raw_cpuid_lib = load_pycryptodome_raw_lib("Crypto.Util._cpuid_c",
                                           """
                                           int have_aes_ni(void);
                                           int have_clmul(void);
                                           """)
def have_clmul():
    return _raw_cpuid_lib.have_clmul()
```

It seems to be trying to load this shared object and it finds something otherwise it would raise an exception (according to my review of `load_pycryptodome_raw_lib`.

```
/data/.ve/lib/python3.9/site-packages/Crypto/Util/_cpuid_c.abi3.so
```

Any thoughts why `None` is returned when executing the pyinstaller image but not when run within the Python environment?

**Comment by rokm** [comment]
Hmm, I can't reproduce this on my Raspberry Pi 4 running 64-bit Debian Bullseye 11.4 (and system-installed python 3.9.2). Based on your error traceback, the following snippet should reproduce the issue:

```python
# test_program.py
# Freeze with: pyinstaller --clean --noconfirm test_program.py
from Crypto.Util import _cpu_features
print(_cpu_features.have_clmul())
```

Installing `pycryptodome` into a venv via https://www.piwheels.org/ (set-up by default) and freezing with PyInstaller 5.3 seems to work as expected, both with `cffi` available and with `cffi` unavailable (since `pycryptodome` seems to have both `cffi`-based and `ctypes`-based library loading codepath).

Can you try freezing the above sample on your system and confirm it reproduces the problem? If it does, I would suggest you to instrument your local `pycryptodome` copy with print statements to see where it fails. My guess is that the shared library is correctly collected into frozen application (because the code explicitly checks that the file exists and raises an error otherwise), but it is failing at the loading step for some reason... You can also archive the generated `build` and `dist` directories for the above sample and upload it somewhere so we can take a look and see if there's something obviously wrong in there.

**Comment by razed11** [comment]
@bwoodsend Thanks so much. I was hoping your test program would reproduce the error but unfortunately it worked just fine (which seems like a funny thing to say :)). I'll try to instrument my application and see what I can find.

**Comment by razed11** [comment]
This issue was related to hooks defined for pycryptodome that were used to resolve shared object paths. The issue is entirely on my end and I sorted it out.
