### ISSUE TITLE
Executable can't find scrapy

### ISSUE THREAD

**Issue by mayankdmishra** [pyinstaller/pyinstaller#7067]
I am on Linux machine. I have two py files. One Tkinter gui & another scrapy code. In gui file, Popen executes scrapy code of another file. Everything runs fine when using terminal.

I needed to pack the files with pyinstaller to create executable. But I am getting error in stderr of Popen "scrapy not found"

I'll detail what I have done so far to solve the problem.

Initially I simply ran ->pyinstaller gui.py

The executable ran fine. gui opened but didn't do anything. It had actually not collected the scrape.py (which was being called through popen)

To include the other py file I ran pyinstaller --add-data 'scrape.py':'.' gui.py

This included the scrape.py, still scraping was not being done. This [stackoverflow answer](https://stackoverflow.com/a/63625461/13100522) suggests setting datas to ['.','.'] in spec file to include everything via pyinstaller I did by creating spec file and changing data values

`$ pyi-makespec gui.py `
this created spec file I change the datas value and ran

`$ pyinstaller gui.spec ` 
This actually copied everything. I got a scrapy folder as well. Still no scraping was being done. At this time I captured the returncode of Popen which was 127. Thus I captured the stdout Popen error which was "scrapy not found".

So it was clear that pyinstaller was not shaking hands with scrapy framework well-enough. Then I found many SO threads stating pyinstaller-scrapy problem. But they all seem to have solved it somehow, which implementing in my case wasn't working. May be they were all Win machines and mine is Linux(I don't know why).

This [stackoverflow](https://stackoverflow.com/a/55410079/13100522) answer suggests including many hidden imports in spec file I did that. Same stderr ="scrapy not found".

Then towards finding solution, I went through an [official scrapy doc](https://doc.scrapy.org/en/1.0/topics/practices.html#run-from-script) which suggests that a scrapy file can be run as a single python file without giving any scrapy runspider command. I implemented the steps. Scraping was done as standalone python file in terminal, so I packed it with gui and got this stderr.

```
Traceback (most recent call last):
  File "./scrape.py", line 1, in <module>
    import scrapy
ModuleNotFoundError: No module named 'scrapy'.

```
I even included "scrapy" in the hiddenimports of spec file, no luck.

Thus reverted scrape.py code back to run from "scrapy runspider scrape.py through Popen, instead of calling directly scrape.py through Popen.

I even copied the whole "scrapy" and "scrapy2.6.1 dist" folders from my env to the one created by pyinstaller. Here scrapy and all its modules are there still why the scrapy is not found by the executable?

**Comment by rokm** [comment]
So you have frozen your `gui.py` but are trying to run your `scrape.py` file in unfrozen form via Popen? In that case, your `scrape.py` is ran using system's python interpreter (or whichever python interpreter is in `PATH`, if any) and the `scrapy` should be made available there. Copying `scrapy` into PyInstaller-frozen bundle for `gui` does nothing, because `scrape.py` is not ran using the bundle's embedded python interpreter. So this design of having and calling an external python script won't work as you expect in PyInstaller, and in fact beats the point of trying to freeze your `gui.py` with PyInstaller in the first place because it assumes that there is python interpreter available on the target system.

What might work, though, is merging your `scrape.py` script into the main (gui) program (or importing in there as a module), and then running it as a subprocess using `multiprocessing` (or via `scrapy.crawler`, assuming that whatever multiprocessing framework that uses is compatible with PyInstaller... which may or may not be the case).

**Comment by mayankdmishra** [comment]
@rokm thanks for taking time to understand the problem and suggesting the possible solution.
Let me give some more detail. I am working in virtual env. And the gui is not freezed as I am using `Popen()` not `Popen().wait`
The `indeterminant progress bar` keeps bouncing with the help of a `for loop` and `poll()`. And in the `Popen()` I am only giving the `scrapy runspider scrape.py` command. So I suppose it is using the same interpreter (of venv) which will get bundled with the pyinstaller. And scrapy is also installed in the venv.

But I will definitely try your suggestion of `multiprocesing`. Regarding `scrapy.crawler` as far as I can recall both `CrawlerProcess` and `CrawlRunner` inside `scrapy.crawler` block the script until the crawling is finished.

Meanwhile I want to draw your (and community's) attention (if not already in notice) to the scrapy packing problems with pyinstaller. There are several Stackoverflow threads struggling with packing scrapy with pyinstaller. Here are a few one I have gone through [1](https://stackoverflow.com/questions/51213515/pyinstaller-error-on-scrapy) [2](https://stackoverflow.com/questions/63619184/packaging-scrapy-as-a-part-of-a-bigger-program-with-pyinstaller) [3](https://stackoverflow.com/questions/55331478/how-to-create-a-single-executable-file-in-windows-10-with-scrapy-and-pyinstaller/55410079)

I'll share my result after implementing `multiprocessing` and `scrapy.crawl` to the code.

**Comment by rokm** [comment]
> I am working in virtual en

OK, that does fully explain why python interpreter does not find `scapy`. Because it is installed in your venv, and the frozen application is probably running the "base" python interpreter (the one outside the venv) via Popen. 

> And the gui is not freezed as I am using `Popen()` not `Popen().wait`

Mhm. "The frozen" application in this context refers to the "application compiled with PyInstaller", not "code stuck doing some blocking task".

> So I suppose it is using the same interpreter (of venv) which will get bundled with the pyinstaller.

That's the thing - PyInstaller does not bundle the interpreter (`python` executable) into the frozen application bundle. It collects only python shared library, which it uses to set up *embedded python interpreter* to run your frozen (=compiled) python code. But you don't have direct access to that embedded interpreter, and you cannot use it to run arbitrary external code.

**Comment by rokm** [comment]
> Meanwhile I want to draw your (and community's) attention (if not already in notice) to the scrapy packing problems with pyinstaller. There are several Stackoverflow threads struggling with packing scrapy with pyinstaller. Here are a few one I have gone through [1](https://stackoverflow.com/questions/51213515/pyinstaller-error-on-scrapy) [2](https://stackoverflow.com/questions/63619184/packaging-scrapy-as-a-part-of-a-bigger-program-with-pyinstaller) [3](https://stackoverflow.com/questions/55331478/how-to-create-a-single-executable-file-in-windows-10-with-scrapy-and-pyinstaller/55410079)

Well, we already have a [hook for `scrapy`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-scrapy.py) that someone contributed. I personally cannot attest to whether it works or not and how much of the `scrapy` functionality it actually covers, though. If it doesn't, feel free to improve it.

But using PyInstaller unfortunately sometimes requires rather in-depth knowledge of how PyInstaller itself works, how Python works, and how the python packages that you use work (e.g., do they provide and expect any external data, do they expect their source code being available as opposed to just compiled modules, do they depend on any binary shared libraries, does it use a multiprocessing framework under the hook and therefore requires special handling when frozen, etc.). So using PyInstaller for the first time on a complex application (or a "simple" application using complex frameworks behind the scenes) is often a complete hit and miss, and due to the sheer amount of python code and packages out in the wild, this cannot be fully offset by the tool itself.

EDIT: A word of advice, though - "old" (as in, two- or three-years old) issues (and their solutions) may not really be applicable to you anymore. Python changes, python packages change, and PyInstaller changes over time...

**Comment by mayankdmishra** [comment]
I did read about the hook and how pyinstaller behind the scene uses hooks
to import modules. Before posting here while finding solution I created my
own hook for needed modules and gave its path in the spec file but that
also didn't work. I will still modify that file to see the result. Yes you
have said correctly that if behind the scene complex framework is there
then it needs a closer look to what's missing.
Thanks for your suggestions and I'll update here with my results.

**Comment by mayankdmishra** [comment]
Hi,
I found this line in verbose of `pyinstaller` 
`8300 INFO: Processing pre-find module path hook distutils from 'myfolders/venv/lib/python3.6/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
8345 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.6'
`
See the last line. `Pyinstaller` actually packed from `user` library instead of the `venv`. That's why `scrapy` was not running, because it was not installed in the user package. When I installed it in the user package and again built it, scrapy ran. However I am stucked with scrapy problem & getting error (something again is there in venv and not in user package) 
Error = `/twisted.web._newclient.RequestGenerationFailed` 
That's the `scrapy` problem in `user`. Even in `user` terminal, `scrapy` is giving error. Still finding the solutions for that.

Regarding `pyinstaller` I see that my `pycharm` venv is not having `distutils` instead it has `distutils_hack` folder. Will copying the `distutils` folder from user to venv work? But again `pyinstaller` is getting `distutils` from `hook` file which is having 
`try:
    import sysconfig
    hiddenimports = [sysconfig._get_sysconfigdata_name()]
except AttributeError:
    # Either sysconfig has no attribute _get_sysconfigdata_name (i.e., the function does not exist), or this is Windows
    # and the _get_sysconfigdata_name() call failed due to missing sys.abiflags attribute.
    pass`
How can I get this `distutils` work in `venv` and make `pyinstaller` get it from `venv`.
Meanwhile I am getting `scrapy` to work outside `venv`.

**Comment by bwoodsend** [comment]
> See the last line.

You're going down completely the wrong rabbit hole here. A virtual environment doesn't contain a full installation of Python. It contains only libraries installed with pip. The standard library, which contains `distutils`, is not part of the venv environment - it's taken from the original Python environment. Your problem has nothing to do with `distutils` - it's that you're trying to run Python scripts as subprocesses.

**Comment by mayankdmishra** [comment]
@bwoodsend Thanks for understanding and giving a thought to the problem. I understand that `distutils` are not in the `venv` and they are collected and packed from the user (however by mistake, I did get to solve the problem at my end, after seeing that line in verbose, though).   
But what about the packages I installed in `venv` through `pip`? Why `pyinstaller` didn't pack `scrapy` from `venv`? Why the gui ran when I installed scrapy for the user and then packed it with `pyinstaller`? The file I packed are still in the venv.
Before, I even tried to create a standalone spider (with CrawlerProcess) that runs just as a python file (no scrapy commands need to be given, Popen to python3 was given), and packed it with `pyinstaller` even then also I was getting `scrapy` not found error ([error shared](https://github.com/pyinstaller/pyinstaller/issues/7067#issue-1362112316) above,  towards the end). Please have a look.
Won't `pyinstaller` go along with `Popen` to see what's going to happen and pack that too?
What tweaks do you suggest using `pyinstaller` when `Popen` is used for `scrapy`.

**Comment by bwoodsend** [comment]
>  Won't pyinstaller go along with Popen to see what's going to happen and pack that too?

No. And even if it did, it wouldn't work because `Popen(["python3", ...])` means *search `PATH` for an executable named `python3` and  run it*. PyInstaller isn't going to magically translate that into *launch arbitrary script as subprocess using the libraries currently contained in this running application*.

>  What tweaks do you suggest using pyinstaller when Popen is used for scrapy.

Why does it need to be a subprocess?

**Comment by mayankdmishra** [comment]
> Why does it need to be a subprocess?

Thanks for your suggestion. I did think of that after discussion with @rokm previously but then during the process somewhere the (by mistake) solution happened and that idea got dropped subconsciously. Will now code with multiprocessing. Is that ok or should I choose something else?

**Comment by bwoodsend** [comment]
Yes but make sure you call [multiprocessing.freeze_support()](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support).

**Comment by mayankdmishra** [comment]
Mine is Linux machine and `multiprocessing.freeze_support()` link says for win executable. Anything compatible with Linux?
Also need to update that the problem got solved at [SO](https://stackoverflow.com/questions/73625841/scrapy-error-twisted-web-newclient-requestgenerationfailed/73628640#73628640) by creating a new venv and installing only required packages for project then running pyinstaller with some tweaks in spec file. Just mentioning, if some other user with same problem appears.

**Comment by mayankdmishra** [comment]
@rokm @bwoodsend executable ran successfully when used multiprocessing. Thanks for all the suggestions.

**Comment by UncleDrew92** [comment]
@mayankdmishra I am having the same issue. Would you mind showing your multiprocessing solution?
