### ISSUE TITLE
Option to disable the splash screen

### ISSUE THREAD

**Issue by marcelomanzo** [pyinstaller/pyinstaller#7089]
Some users of my app would like to have the option to disable the splash screen.

I am wondering if we could have this implemented via environment variable or parameter into the command line when we invoke the exe.

Thanks!

**Comment by rokm** [comment]
That's a definite "no" on the command-line parameter - I really don't want to fish for pyinstaller/bootloader-specific arguments from command-line arguments before passing them to your frozen python script

But a generic environment variable sounds reasonable to me. Maybe a `PYI_DISABLE_SPLASH` or `PYI_NO_SPLASH`?

**Comment by marcelomanzo** [comment]
I vote for the PYI_DISABLE_SPLASH

**Comment by marcelomanzo** [comment]
Great work by the way with the splash! Thumbs up for everyone involved.

**Comment by bwoodsend** [comment]
Windows is the only platform where you can set an environment variable globally so that GUI apps will be able to see it. A user selecting a _disable splash screen_ option on Windows would translate to running `setx PYI_DISABLE_SPLASH=1` (or possibly monkeying around with `winreg` to do the same thing). On UNIX, writing to `~/.bashrc` and the likes is useless since desktop apps do not source those files. You could write to `/etc/profile` but a) that would require sudo access and b) you'd need to log out and log back in again for the change to take effect and c) macOS ignores that file completely. I think I'd personally be leaning towards a file on the filesystem (e.g. `~/.config/pyi_no_splash`). We could add helper functions into the `pyi_splash` module which set/get/unset that property rather than having people write those files directly.

**Comment by bwoodsend** [comment]
Another option would be the native but platform specific ways:
* Windows: Read/write winreg
* macOS: Use `defaults` CLI command to access settings
* Linux/BSD: Use `~/.config` as usual

That feels like more trouble than it's worth though.

**Comment by marcelomanzo** [comment]
@bwoodsend,
I think using files is a more easy way to control the behavior.

One thing that we need to consider is the usecase where a user has 2 (or more) different apps compiled by PyInstaller installed on the same computer.

Imagine for the app A, he wants to see the splash screen, the app B, he does not want to see the splash screen.

**Comment by rokm** [comment]
Well, the scenario I had in mind is actually that the PyInstaller-frozen application is started by a launcher script, where the environment variable could be set or not (or where the command-line argument would be added/removed from the launch command).

Using more complex approaches, like config files and/or Windows registry would mean that we would need to have the user (=developer) provide their "vendor name" and the "official" application name so we can structure the paths. For example,if we wanted classic key structure in Windows registry: `HKEY_LOCAL_USER\\VendorName\\ApplicationName\\pyi_disable_splash` . Similarly for `~/.config/ApplicationName/pyi_disable_splash` file - and this is potentially problematic, because the application code itself might decide to use `~/.config/ApplicationName` as a configuration file (as opposed to a directory. And as the format of the config file can be arbitrary, we wouldn't be able to parse it, even if we were inclined to have a parser in bootloader.).

So compared to registry/config file solutions, I think I would rather go fishing for the `--pyi-disable-splash` command-line option and have it removed from command-line...

**Comment by bwoodsend** [comment]
The file system approach could be structured the other way around. i.e. `~/.config/pyi_disable_splash/ApplicationName`. Then all it has to do is query if the file exists.

It occurs to me that macOS .app bundles don't have `$HOME` set so we might need to assume `$HOME == /Users/$USER`.
