### ISSUE TITLE
Executable with trafilatura module not working?

### ISSUE THREAD

**Issue by Rapid1898-code** [pyinstaller/pyinstaller#7093]
Hello - i have the following working code with the trafilatura-module -

```
import trafilatura as traf
url = traf.fetch_url("https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-13-22/h_b439762c2fb1cc0a92457f4214601e58")
workText = traf.extract(url)    
print(workText)
```

When i create the windows-executeable with
`pyinstaller --onefile test.py`

i get the following error message when running the exe:

```
G:\DEV\Fiverr\TRY\raghav_one>test.exe
Traceback (most recent call last):
  File "configparser.py", line 790, in get
  File "collections\__init__.py", line 986, in __getitem__
  File "collections\__init__.py", line 978, in __missing__
KeyError: 'min_file_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    url = traf.fetch_url("https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-13-22/h_b439762c2fb1cc0a92457f4214601e58")
  File "trafilatura\downloads.py", line 155, in fetch_url
  File "trafilatura\downloads.py", line 123, in _handle_response
  File "configparser.py", line 819, in getint
  File "configparser.py", line 809, in _get_conv
  File "configparser.py", line 804, in _get
  File "configparser.py", line 793, in get
configparser.NoOptionError: No option 'min_file_size' in section: 'DEFAULT'
[7540] Failed to execute script 'test' due to unhandled exception!
```
Any idea why this is happening?
Do i have to use any other parameters when creating the exe?

**Comment by rokm** [comment]
> Any idea why this is happening?
> Do i have to use any other parameters when creating the exe?

You probably need to collect data files that come with the `trafilatura` package. Try adding `--collect-data trafilatura` to your PyInstaller command.

**Comment by Rapid1898-code** [comment]
Hello - thanks, with that additonal parameter it now works fine.
Why is this for some modules only working with this additonal parameter?

**Comment by rokm** [comment]
Because `modulegraph` that PyInstaller uses to analyze your code recursively analyzes only python modules; i.e., python modules that your code imports, the modules that those modules import, and so on. (And even that works only for direct imports; if the modules are indirectly or lazily imported, you need [`hiddenimports`](https://pyinstaller.org/en/stable/usage.html#cmdoption-hidden-import); same if the imports are made within binary extension module, because we cannot analyze those).

So if package contains non-python data, we have no way of knowing it, and you need to manually ensure that this data is collected, using [`--collect-data`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-data). Instead of doing this manually via command-line, this can be also done with [per-package hook](https://pyinstaller.org/en/stable/hooks.html); so if someone already wrote [a hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/tree/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks) for the package you are using, then it works out-of-the-box.
