### ISSUE TITLE
Import win32crypt failed by pyinstaller ver.5.4.1

### ISSUE THREAD

**Issue by lxnow321** [pyinstaller/pyinstaller#7107]
My python code used the win32crypt module. I has installed the pypiwin32.
I can execute the python script successful，but when I pack to executable file by pyinstaller  ver5.4.1 and execute it is failed.
This is the wrong  infomation：
![image](https://user-images.githubusercontent.com/6749770/191734406-6125b6b8-856d-472f-b03e-bf16472648b8.png)
Many attempts have failed!

Until I downgrade the pyinstaller to version 5.3，the problem is gone.

**Comment by rokm** [comment]
This is caused by #7028 and collecting the `pywintypes3X.dll` into its original sub-directory. 

If each extension from site-`packages/win32` can be imported as its own top-level module, we'll need runtime hooks similar to the one that we have for `win32api` for all of them. Or perhaps better, add a global loader script to handle this... (in unfrozen python, `pywin32.pth` performs the search path adjustment and pre-loads the pywintypes DLL).

As a work-around, you can add `win32api` as a hidden import, to have its runtime hook sort out the DLL search path and preload.
