### ISSUE TITLE
Error: 'Rich' Distribution Not Found

### ISSUE THREAD

**Issue by simmonsj330** [pyinstaller/pyinstaller#7113]
## Context
Python: 3.9.6
Pyinstaller: 4.10
OS: MacOS (x86_64) Monterey

Hello, for the last few days I've been struggling to fix an error I have been receiving when packaging this [command line application](https://github.com/OpenBB-finance/OpenBBTerminal), which is an investment research platform. Users can either run this program by downloading the repo and setting up a python environment or run it 'out of the box' via an executable. I can build the executable however, running a certain features leads to this error, which states...

`The 'rich' distribution was not found and is required by the application`

Our application can more or less be broken down into menus which have features & commands that can be run from these menus. Each menu utilizes `rich` and when running either as an executable or via python it works great. As of late, we are implementing a new menu with machine learning features that users can run. However, when trying to open our new machine learning menu on the executable, it doesn't open and throws this error.

In the ML menu, we have about ~12 machine learning models that users can run. After some digging I was able to locate that the error is thrown when importing specific functions from ML libraries such as darts. For half of the models, we figured out that if you import the error-causing module twice, then it works. We've come up with a sort of hacky solution to mitigate this error on these models. 
```
try:
    from darts.models.forecasting.some_function import SomeFunction
except Exception:
    pass
from darts.models.forecasting.some_function import SomeFunction
```

However for the other half, no matter how many times you try to import, it throws the same "distribution not found" error. For these, I've traced back the error on each one and they all trace to the same import line: import `pytorch_lightning as pl` in either `pl_forecasting_module.py` or `torch_forecasting_model.py`. These two files are reside in the darts package. The models that work utilize scikit-learn while the models that dont utilize pytorch_lightning. 

## Solutions Tried

- Added `rich`, `darts`, `pytorch_lightning`, and some other packages to hidden imports in terminal.spec
- Created a hook directory and hook file for `rich` which looks like this:

```
from PyInstaller.utils.hooks import copy_metadata, collect_data_files

datas = copy_metadata("rich") + collect_data_files("rich")
```
- Directly pulled in packages using added_packages in terminal.spec
```
(os.path.join(pathex, "darts"), "darts"),
(os.path.join(pathex, "pytorch_lightning"), "pytorch_lightning")
etc...
```
- Upgrading from pyinstaller from 4.10 to the latest. This led to and error similar to https://github.com/pyinstaller/pyinstaller/issues/4925 so I decided to keep using 4.10 because it could atleast produce and executable still

## Question
Regardless if darts, rich, pytorch_lightning, etc are hidden imports or added_files, the error still persists. I've run into similar errors before and normally they are easily fixed with a hidden import but this does not seem to be the case here. The ML menu works perfectly when it is run via a python environment, but not when packaged. So my question is why can't `rich` be found, why does importing twice work sometimes, and why can't pytorch_lightning identify `rich`? I would like to get rid of the error all together and ideally the hacky solution we have for some of the models. Any help on how to fix this would be appreciated!!🚀

**Comment by bwoodsend** [comment]
> The 'rich' distribution was not found and is required by the application

That error message means `rich`'s package metadata needs collecting. Adding `--copy-metadata=rich` to your build command is normally the simplest way to fix it.

Your hook should also fix it provided that it's named `hook-rich.py`, you've added that hook directory to `--additional-hooks-dir` on the command line or `hookspath` if your using the spec file and you build with `--clean`. You'll know if you've done it right because the build log will contain a line saying:
```
INFO: Loading module hook 'hook-rich.py' from '...'
```

**Comment by rokm** [comment]
> * Upgrading from pyinstaller from 4.10 to the latest. This led to and error similar to [Conda in macOS gives "TypeError: expected str, bytes or os.PathLike object, not NoneType" #4925](https://github.com/pyinstaller/pyinstaller/issues/4925) so I decided to keep using 4.10 because it could atleast produce and executable still

Does the error look like this?
<details><summary>Error traceback</summary><p>

```
Traceback (most recent call last):
  File "/Users/rok/Development/pyi-7113/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/rok/Development/pyi-7113/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/rok/Development/pyi-7113/venv/lib/python3.9/site-packages/PyInstaller/__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/rok/Development/pyi-7113/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 962, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/rok/Development/pyi-7113/venv/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 884, in build
    exec(code, spec_namespace)
  File "build/pyinstaller/terminal.spec", line 160, in <module>
    exe = EXE(*exe_args, **exe_kwargs)
  File "/Users/rok/Development/pyi-7113/venv/lib/python3.9/site-packages/PyInstaller/building/api.py", line 484, in __init__
    if self.icon and self.icon != "NONE" and not os.path.isabs(self.icon):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 62, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not tuple
```

</p></details>

That's caused by [invalid icon kwarg being passed to EXE](https://github.com/OpenBB-finance/OpenBBTerminal/blob/60c060afad205b9b2f37e79eafb3a3f4017f1942/build/pyinstaller/terminal.spec#L156) - it should be a string (path to icon file), not a tuple. Passing icon to EXE on macOS is essentially a no-op (icon is applicable only to .app bundle and its BUNDLE() target), but in recent PyInstaller versions, it goes through additional validation, which causes the error when `os.path.isabs()` is called with invalid argument.

---

But back to original question, a basic program:
```python
import pytorch_lightning as pl
```

does indeed raise the `The 'rich' distribution was not found and is required by the application` error when frozen on macOS. That's because `pytorch_lightning` assumes that if `rich` package is importable (which it is, because it was present in environment when the program was frozen), its metadata is also available ([here](https://github.com/Lightning-AI/lightning/blob/d1a3a3ebf543629fc38783d9f5e39f2bfb6b37d7/src/pytorch_lightning/utilities/imports.py#L42)). Which I suppose is reasonable in general, but not in PyInstaller's case where metadata is not collected by default.

Adding `--copy-metadata rich` on command-line (when running against source) solves the problem. In your case, you will probably want to make a hook, but as Brénainn pointed out, you need to make sure your hook is actually used; i.e., specify `hookspath` in the spec file and build with `--clean` option added to the command line. The `--additional-hooks-dir` command-line switch is a no-op when running against the .spec file, and while older versions of PyInstaller let you specify it (and quietly ignore it), PyInstaller 5.x rises an error to prevent confusion in cases like this.

---

As a side note, as availability of the `rich` metadata is a `pytorch_lightning` requirement as opposed to the `rich` itself (presumably; if `rich` also requires its metadata for its operation, then disregard this), the hook that calls `copy_metadata("rich")` should be the one for `pytorch_lightning`, not `rich`. Although it does not make any practical difference in the context of your attempt to freeze your program.

**Comment by simmonsj330** [comment]
Thank y'all so much! I was able to get everything working perfectly!
