### ISSUE TITLE
File is not found in MEIPASS (but was working initially) 

### ISSUE THREAD

**Issue by samshipengs** [pyinstaller/pyinstaller#7127]
I have a program that sends some data to GCS in a while loop, which requires a JSON credential file, it roughly looks like the following:

```python
import os
import sys
from pathlib import Path


GOOGLE_SERVICE_ACCOUNT_FP = "pos-service-account.json"

IS_INSTALLER = getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS")
if IS_INSTALLER:
    GOOGLE_SERVICE_ACCOUNT_FP = os.path.join(sys._MEIPASS, GOOGLE_SERVICE_ACCOUNT_FP)



def send_data(data, credential_fp: Path = Path(GOOGLE_SERVICE_ACCOUNT_FP)):
    if not credential_fp.is_file():
        msg = f"Google service account key json file: {str(credential_fp)!r} is not found!\nPWD files:\n{list(Path.cwd().glob('*'))}"
        raise FileNotFoundError(msg)

    # some function post data to cloud storage
    post_to_gcs(data)


def main():
    while True:
        data = ...
        send_data(data)


if __name__ == '__main__':
    main()

```

I packaged using one file with the following command:
`pyinstaller --onefile -w .\main.py --add-data 'pos-service-account.json;.'`

Then when I clicked on the .exe file on windows, it was working fine, I could see the data posted by this program. However, I came back after a few days, I got the file not found error:

     Google service account key json file: 'C:\\Users\\POS\\AppData\\Local\\Temp\\_MEI30522\\pos-service-account.json' is not found! 

this does not make sense to me as the program was working at the beginning, which means it did find the json file, I'm still trying to replicate the error, but so far my suspicion is:

 * Does the `sys._MEIPASS` directory ever change? e.g. if the computer goes to sleep and comes back on (I'm going to test it), I could see how my script would fail if the `_MEIPASS` changes when the program is running.

Any ideas? (I have posted on [SO](https://stackoverflow.com/questions/73947371/file-is-not-found-in-meipass-pyinstaller-but-was-working-initially) as well)

**Comment by rokm** [comment]
> Does the `sys._MEIPASS` directory ever change?

Nothing really prevents the OS or some 3rd party utility from cleaning up those temporary files. Otherwise, the files should stay there as long as the child process of onefile application is still running (i.e., the parent process performs clean up only after the child exits or terminates).

Have you checked if `C:\\Users\\POS\\AppData\\Local\\Temp\\_MEI30522` directory and its contents still existed when you got the error?

**Comment by samshipengs** [comment]
I haven't checked yet, I need to get access to that computer first (the error came from cloud logging), will report once I do that.

Hmm... I can't think of anything that would interfere/delete the _MEIxxx directory.

What if I call `os.path.join(sys._MEIPASS, GOOGLE_SERVICE_ACCOUNT_FP)` every time I need to access the path variable `GOOGLE_SERVICE_ACCOUNT_FP`? would `sys._MEIPASS` somehow be updated?

[Alexander from SO](https://stackoverflow.com/a/73951998/4492375) mentioned I could use `__file__`  like this:

> GOOGLE_SERVICE_ACCOUNT_FP = "pos-service-account.json"
CREDENTIAL = os.path.join(os.path.abspath(__file__), GOOGLE_SERVICES_ACCOUNT_FP)

but I don't understand if the `sys._MEIPASS` got removed/modified, how could the path with `__file__` be used?

**Comment by rokm** [comment]
> What if I call `os.path.join(sys._MEIPASS, GOOGLE_SERVICE_ACCOUNT_FP)` every time I need to access the path variable GOOGLE_SERVICE_ACCOUNT_FP? would sys._MEIPASS somehow be updated?

`sys._MEIPASS` is set in the [bootloader](https://github.com/pyinstaller/pyinstaller/blob/039a4c08be47e42a6a562ea14c53694112e727b9/bootloader/src/pyi_pythonlib.c#L604) during application startup and remains fixed for the duration of the application's run. (Well, unless you modify it by accident in your code.) The path `C:\\Users\\POS\\AppData\\Local\\Temp\\_MEI30522` looks correct, though (onefile builds unpack themselves into `%TMP%\_MEIXXXXX` directory, with [numeric suffix on Windows being the process ID](https://github.com/pyinstaller/pyinstaller/blob/039a4c08be47e42a6a562ea14c53694112e727b9/bootloader/src/pyi_utils.c#L334)).

> [Alexander from SO](https://stackoverflow.com/a/73951998/4492375) mentioned I could use `__file__` like this:

You could, but that would not change anything. Calling `os.path.dirname(__file__)` in the entry-point script should give you the same directory as `sys._MEIPASS`.

---

I still think that the underlying problem here is that the file in question (possibly whole application's temporary directory) was removed from the temporary directory. And no amount of path manipulation in your code is going to save you from that :)

Do note that your error message is not particularly helpful in the context of the frozen application, because it is listing current working directory. You should probably reorganize the code to store path to either cwd (if unfrozen) or sys._MEIPASS (if frozen), and then list the contents of that path in case of error...

**Comment by samshipengs** [comment]
>And no amount of path manipulation in your code is going to save you from that :)

i see, that's what i think as well

yeah, i agree, the logging should be displaying the items inside the _MEIPASS, never was expecting this error...

a wild guess... would the temp folder potentially somehow be deleted by windows security defender (or these anti virus software)? i remember when i was simply running the .exe file by clicking on it, window system gives warning saying its dangerous to run the file and i needed to click on the `run anyway`, perhaps somehow the system thought its malicious and somehow deleted its temp folder later on?

or, is there any way we can protect the `sys._MEIPASS` from deletion/modification?

**Comment by bwoodsend** [comment]
Your guess is as good as ours.

> or, is there any way we can protect the sys._MEIPASS from deletion/modification?

For Windows, you can keep a file handle open which will make it render the file unmodifiable/deletable until the handle is closed. i.e. putting `_dont_delete_this_variable = open(GOOGLE_SERVICE_ACCOUNT_FP)` should block its deletion.

**Comment by samshipengs** [comment]
@bwoodsend @rokm I'm still not able to get access to that computer with the issue yet, but after some searching, it does look like the _MEPPASS folder got deleted, which I suspected for two reasons:

1. anti-virus software: https://stackoverflow.com/questions/64788656/exe-file-made-with-pyinstaller-being-reported-as-a-virus-threat-by-windows-defen , it looks like the .exe file generated from pyinstaller often could be tagged as malicious by different anti-virus softwares
2. windows automatic temp file removal is turned on: https://superuser.com/a/1599897/629918

I will check the storage cleaning setting on windows once I got to the machine.

I imagine if it is either case, then having a file handler hanging around would likely not prevent it from deleted i guess?

And is there a reason why the `.exe` file unpacks the data files (along with some other files like .pyc) into `temp` folder? I suppose it's not that uncommon the `.exe` file runs for 24/7, and seems like `temp` folder has the risk being cleaned

**Comment by rokm** [comment]
> And is there a reason why the `.exe` file unpacks the data files (along with some other files like .pyc) into `temp` folder? I suppose it's not that uncommon the `.exe` file runs for 24/7, and seems like `temp` folder has the risk being cleaned

That's how `onefile` builds work. 

I think for long-running applications, `onedir` build is a better option if you want to avoid issues with temporary files.

Or if you absolutely must use `onefile`, use [`--runtime-tmpdir`](https://pyinstaller.org/en/stable/man/pyi-makespec.html?highlight=runtime-path#rarely-used-special-options) option to specify custom temporary directory to be used for unpacking.

**Comment by samshipengs** [comment]
I see, I'd stick to using onefile since I'd like to hide my source code, although it's not a guarantee to prevent reverse-engineering as I read on the docs, at least it's not a plain text, which I think it would be for `onedir`

**Comment by samshipengs** [comment]
sorry one more question, I can see these JSON files in the MEIPASS temp directory (I'm doing test runs) with `onefile`, so the JSON files literally are stored as plain text, so anyone knows where to look they can access these JSON files easily, is there any way to hide them such that these data files won't be easily read in the temp folder?

**Comment by rokm** [comment]
> I see, I'd stick to using onefile since I'd like to hide my source code, although it's not a guarantee to prevent reverse-engineering as I read on the docs, at least it's not a plain text, which I think it would be for `onedir`

It's trivial to unpack `onefile` builds, though. Either using `pyi-archiver_viewer` utility that comes with PyInstaller itself, or using [`pyinstxtractor`](https://github.com/extremecoders-re/pyinstxtractor).

**Comment by rokm** [comment]
> is there any way to hide them such that these data files won't be easily read in the temp folder?

No - your files are there as they were collected.

So if you want your secrets hidden, you'll need to roll your own protection scheme. For example, you could encrypt the JSON files and then decrypt them in your code. But since the latter is accessible, a determined user could still decrypt them themselves (I suppose you *could* use something like `pyarmor` to protect the code from prying eyes).

**Comment by samshipengs** [comment]
I got access to the computer, and it appears that the MEIPASS directory inside `Temp` on Windows was not deleted, but several files inside it were removed including all the JSON files. 

Unfortunately, I didn't find a trace of evidence that this deletion was performed by the security software, I checked the security log and there was nothing there.

The `storage sense` functionality was also turned off, which I suspected was on that would auto-remove files inside `Temp`. So now I'm not too sure what deleted the files inside MEIPASS, but for my script, I basically loaded all the JSON into memory so the deletion shouldn't affect the program.

Unless someone has additional insights, I will close this issue.
