### ISSUE TITLE
PyQT5 app after packing doesn't start

### ISSUE THREAD

**Issue by ghostku** [pyinstaller/pyinstaller#7132]
I am trying to pack my PyQT5 app but it doesn`t start. So I made some tests:

    from time import sleep
    print('start')
    sleep(60)
    print('end')

This simple script can be packed and start from cmd and it works. I took another simple script from some article:

    from time import sleep
    from PyQt5 import QtWidgets

    import sys

    class MainWindow(QtWidgets.QMainWindow):

        def __init__(self):
            super().__init__()

            self.setWindowTitle("Hello World")
            l = QtWidgets.QLabel("My simple app.")
            l.setMargin(10)
            self.setCentralWidget(l)
            self.show()
    if __name__ == '__main__':
        print('wwww')
        sleep(30)
        app = QtWidgets.QApplication(sys.argv)
        print('2')
        sleep(30)
        w = MainWindow()
    print('3')
    sleep(30)
    app.exec()
`

And it can be packed but when I try to start it from the command line it just does nothing. No messages.

My setup: 
629 INFO: PyInstaller: 5.4.1
630 INFO: Python: 3.9.7
668 INFO: Platform: Windows-10-10.0.19044-SP0

PyQt5==5.15.2

**Comment by bwoodsend** [comment]
What's your build command? Does it contain either `--windowed` or `--noconsole`? If it does, then those print statements aren't going to show up. Either way, it works for me (although you have to wait 90 seconds for it to show up due to those `sleep()` calls.)

**Comment by ghostku** [comment]
No additional arguments in the build command. Just ‘pyinstaller app.py’ All
specs files, dust, and build folders were removed.

**Comment by rokm** [comment]
I cannot reproduce this, either. Those sleeps seems to cause the window to not be brought forward sometimes, but otherwise the program works as expected.

Can you archive your build and dist folders and upload them somewhere?

**Comment by ghostku** [comment]
I added sleep just to check if it will print me anything and I can at least be sure that my file started. I can remove them.

Here are the files https://transfer.sh/GvE8pT/Manager-tool.zip

**Comment by rokm** [comment]
Ah, yes, the bundle contains both `python39.dll` and `python310.dll`, which means that you've been hit by #7102, and that incorrect version of `python3.dll` has been collected (the one from 3.10 instead of 3.9). This should be fixed in git, but until next release, you'll have to remove python 3.10 from `PATH` (in the command prompt session that you use to run pyinstaller).

EDIT: or you can try installing PyInstaller from git: `pip install git+https://github.com/pyinstaller/pyinstaller` (you might need to first remove the installed version of PyInstaller, due to version number not being bumped).

**Comment by ghostku** [comment]
Thanks. I cleaned my PATH and it works. I will wait for a stable release.
