### ISSUE TITLE
Need a provision to cross compile the pyinstaller binaries

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#7142]
Need a provision to cross compile the pyinstaller binaries

example: 

i want to generate arm executable pyinstaller binary using an x86_64/i386 host machine

**Comment by rokm** [comment]
Because PyInstaller collects binaries from the build environment (e.g., the python shared library, binary python extension modules, their shared library dependencies, etc.), this means that the build environment itself must be running on the target arch (you cannot create an `arm` PyInstaller-frozen application in `x86_64` environment, because the collected files will be `x86_64` and won't load on `arm`).

So you'd need to set up an `arm` emulator/virtual machine on your `x86_64` host, and run PyInstaller in there. Arm docker containers running on top of qemu are an option, too.

But either way, this is beyond the scope of PyInstaller itself.

**Comment by bwoodsend** [comment]
Like Rok say, docker + qemu is the way to go here. On a good day, it's as simple as:
```bash
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker run --platform=aarch64 -v "$PWD:/io" -it ubuntu:focal

cd /io
apt-get update && apt-get install -y python3-pip
pip3 install pyinstaller -r your-requirements.txt
pyinstaller your-code.py
```
It gets a lot hairier if you're doing GUI related stuff. And unfortunately, you have to build on a slightly out of date docker image to avoid glib dependency incompatibilities so, since most of the actually nice Linux distributions are rolling builds, you're usually stuck using Ubuntu or Debian.
