### ISSUE TITLE
Multiprocessing infinite recursion at runtime

### ISSUE THREAD

**Issue by Jaime02** [pyinstaller/pyinstaller#7154]
## Description of the issue

I was debugging [this issue](https://github.com/pyqtgraph/pyqtgraph/issues/2423) and I have found a recursion error.

### Context information

* PyInstaller version: 5.5
* Version of Python: 3.10.4
* Platform: Windows 11
* How you installed Python: python.org
* Did you also try this on another platform? No
* try the latest development version: it is the one that I used

### A minimal example program which shows the error

```
import sys

from PySide6.QtWidgets import (QApplication, QGridLayout, QMainWindow, QWidget)

from pyqtgraph import LayoutWidget
from pyqtgraph.widgets import RemoteGraphicsView


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.resize(800, 600)
        self.centralwidget = QWidget()
        self.gridLayout = QGridLayout(self.centralwidget)
        self.GraphLayout = LayoutWidget(self.centralwidget)

        self.gridLayout.addWidget(self.GraphLayout, 0, 0, 1, 1)

        self.setCentralWidget(self.centralwidget)

        self.RemoteView = RemoteGraphicsView.RemoteGraphicsView()
        self.GraphLayout.addWidget(self.RemoteView)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    Form = MainWindow()
    Form.show()
    sys.exit(app.exec())
```

### Stacktrace / full error message

[out.txt](https://github.com/pyinstaller/pyinstaller/files/9781265/out.txt)

Edit: after some rustic debugging, I have found that the problem is at class pyqtgraph/multiprocess/processes/Process.py, which uses multiprocessing and subprocess.Popen to create a new Python interpreter. The line `conn = l.accept()` is the one that gets blocked.

**Comment by rokm** [comment]
Custom multiprocessing frameworks are not supported in the frozen executables, and rarely work due to various assumptions that are true only when running in original python interpreter.

In this case, [`subprocess.Popen` is used to spawn](https://github.com/pyqtgraph/pyqtgraph/blob/a919df5f79f1e3392e22a889bad083e8c25ee6a0/pyqtgraph/multiprocess/processes.py#L113-L124) with command given as `(executable, bootstrap)`.

In original python code, `executable` is `python.exe` and bootstrap is `path\to\env\pyqtgraph\multiprocess\bootstrap.py`. 

In frozen application, `executable` is frozen program executable (they probably use `sys.executable`, which in frozen application does *not* point to `python.exe`) and `bootstrap` is `top\level\app\directory\pyqtgraph\multiprocess\bootstrap.py`. So one problem is that bootstrap script is not collected as source file (unless you explicitly collect it as data file). But the bigger one is that the executable points to the frozen application executable, so it just starts the program again. Which then starts another instance of itself. Which also starts another instance of itself. Etc.

That sort of `sys.executable`-based subprocessing (running python commands or python scripts) will never work with PyInstaller, and there's nothing we can do about it.

**Comment by rokm** [comment]
Since that custom spawn of bootstrap script seems to be using fixed argument pattern, it can be detected at runtime, and the program flow can be diverted accordingly. This requires that `pyqtgraph.multiprocess.bootstrap` is collected as a hidden import, or that the source file is collected as data file. Also, `multiprocessing.freeze_support` is needed as `pyqtgraph.multiprocess` internally uses `multiprocessing` as well.

```python
import sys

# This block is required due to multiprocessing being used by pyqtgraph.multiprocess
import multiprocessing
multiprocessing.freeze_support()

# This block could be turned into runtime hook for pyqtgraph.multiprocess
if getattr(sys, 'frozen', False) and len(sys.argv) == 2 and sys.argv[1] == os.path.join(sys._MEIPASS, 'pyqtgraph', 'multiprocess', 'bootstrap.py'):
    # Load as module; this requires --hiddenimport pyqtgraph.multiprocess.bootstrap
    try:
        mod_name = 'pyqtgraph.multiprocess.bootstrap'
        mod = __import__(mod_name)
        bootstrap_co = mod.__loader__.get_code(mod_name)
    except Exception:
        bootstrap_co = None

    if bootstrap_co:
        exec(bootstrap_co)
        sys.exit(0)

    # Load from file; requires pyqtgraph/multiprocess/bootstrap.py collected as data file
    bootstrap_file = os.path.join(sys._MEIPASS, 'pyqtgraph', 'multiprocess', 'bootstrap.py')
    if os.path.isfile(bootstrap_file):
        with open(bootstrap_file, 'r') as fp:
            bootstrap_code = fp.read()
        exec(bootstrap_code)
        sys.exit(0)

    raise RuntimeError("Could not find pyqtgraph.multiprocess bootstrap code or script!")


from PyQt6.QtWidgets import (QApplication, QGridLayout, QMainWindow, QWidget)

from pyqtgraph import LayoutWidget
from pyqtgraph.widgets import RemoteGraphicsView


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.resize(800, 600)
        self.centralwidget = QWidget()
        self.gridLayout = QGridLayout(self.centralwidget)
        self.GraphLayout = LayoutWidget(self.centralwidget)

        self.gridLayout.addWidget(self.GraphLayout, 0, 0, 1, 1)

        self.setCentralWidget(self.centralwidget)

        self.RemoteView = RemoteGraphicsView.RemoteGraphicsView()
        self.GraphLayout.addWidget(self.RemoteView)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    Form = MainWindow()
    Form.show()
    sys.exit(app.exec())
```
