### ISSUE TITLE
Qt6 (PyQt/PySide) submodules fail DDL load on import if '__init__.py' is present on Windows

### ISSUE THREAD

**Issue by Dpeta** [pyinstaller/pyinstaller#7155]
## Description of the issue

Freezing a script that imports a Qt6 submodule via binding (either PyQt6 or PySide6) fails to import the submodule when running the resulting executable if an \_\_init\_\_.py file is present in the source directory, and PyInstaller was ran from that source directory. There are no build errors or warnings.

This doesn't seem to happen with pyinstaller 5.3 though, after downgrading it with ```pip install pyinstaller==5.3``` the frozen program executes without error.

Walkthrough to recreate the error:

1. ```python -m venv test_env```
2. ```test_env\Scripts\activate.bat```
3. ```pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip```
4. ```pip install PyQt6```
5. ```fsutil file createnew __init__.py 0```
6. ```echo import PyQt6.QtWidgets > test.py```
7. ```python -m PyInstaller test.py```
8. ```dist\test\test.exe```

Results in:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import PyQt6.QtWidgets
ImportError: DLL load failed while importing QtWidgets: The specified module could not be found.
[5444] Failed to execute script 'test' due to unhandled exception!
```

Though the relevant DLLs do seem to be in the ```dist\test\PyQt6\Qt6\bin``` folder.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.5```
* Version of Python: 3.10.8
* Platform: Windows 10 (en) 
* How you installed Python: python.org provided installer 
* Did you also try this on another platform? Does it work there?

Tried it on MacOS and Linux, but it only happened for me on Windows.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

Same result as 5.5.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import PyQt6.QtCore
# Or:
#import PyQt6.QtWidgets
#import PySide6.QtCore
```

### Stacktrace / full error message

```
[11684] LOADER: Running importtest.py
# PyQt6 not found in PYZ
# code object from 'D:\\isolation\\dist\\importtest\\PyQt6\\__init__.pyc'
import 'PyQt6' # <_frozen_importlib_external.SourcelessFileLoader object at 0x000002AB9E744190>
# PyQt6.QtCore not found in PYZ
Traceback (most recent call last):
  File "importtest.py", line 1, in <module>
    import PyQt6.QtCore
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
[11684] Failed to execute script 'importtest' due to unhandled exception!
```

**Comment by rokm** [comment]
Can you archive the `dist` and `build` directory of the failed build, and upload them somewhere so I can take a look at them? Thanks!

**Comment by Dpeta** [comment]
Sure thing: https://drive.proton.me/urls/D400SK1D4M#hX2OgBKia2cy

**Comment by rokm** [comment]
Ah yes, the python DLLs are mistakenly collected into `Pythons\Python-3.10.8` subdirectory instead of the root directory. This is a combination of #7028 (PyInstaller 5.4), the fact that you have an `__init__.py` next to the entry-point script, and the layout of your project directory w.r.t. the location of your python installation.

If we find an `__init__.py` next to entry-point script, we add the parent directory to `sys.path` (under the assumption that it is a package and that some imports from it need to be resolved). In your case, the test code is located in `D:\isotest2`, so we add `D:\` to `sys.path`. And then, when we check if we need to preserve the directory layout of for example `D:\\Pythons\\Python-3.10.8\\python3.dll'`, we mistakenly believe that we do, because the path is rooted in one of the paths of `sys.path` (the `D:\` one). 

The error should go away if you move your test directory one level deeper; e.g., `d:\myprojects\isotest2` (and if `myprojects` does not contain the `__init__.py`) - is that the case?

But I think we should probably handle such corner cases anyway, either by not augmenting `sys.path` with drive root, or with additional safeguards in the new layout-preservation code...

**Comment by Dpeta** [comment]
That works, after moving it into a sub-directory it runs normally 🐈🎉
