### ISSUE TITLE
使用了pyqtgraph这个绘图库中的RemoteGraphicsView模块，程充打包后会无限启动多个程序

### ISSUE THREAD

**Issue by cuish0920** [pyinstaller/pyinstaller#7198]
```python
if __name__ == '__main__':
    import multiprocessing

    multiprocessing.freeze_support()
    import pyqtgraph as pg


    from pyqtgraph.widgets.RemoteGraphicsView import RemoteGraphicsView

    app = pg.mkQApp()

    ## Create the widget
    v = RemoteGraphicsView(debug=False)  # setting debug=True causes both processes to print information
                                        # about interprocess communication
    v.show()
    v.setWindowTitle('pyqtgraph example: RemoteGraphicsView')

   
    plt = v.pg.PlotItem()

    v.setCentralItem(plt)
    plt.plot([1,4,2,3,6,2,3,4,2,3], pen='g')
    pg.exec()
```

**Comment by rokm** [comment]
1) You need to install `pyinstaller-hooks-contrib` from `master` branch (`pip install git+https://github.com/pyinstaller/pyinstaller-hooks-contrib.git`) because the runtime hook for `pyqtgraph.multiprocess` was added in pyinstaller/pyinstaller-hooks-contrib#501 and has not been released yet. Or, you need to implement an equivalent functionality at the start of your program.

2) If you are using `onefile` mode, you also need to add `os.environ['_MEIPASS2'] = sys._MEIPASS` at the start of your program, before you import `pyqtgraph`. See our [`RemoteGraphicsView` test in `pyinstaller-hooks-contrib`](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/tests/test_libraries.py#L1305-L1341).

**Comment by bwoodsend** [comment]
I hit the release button for the hooks repo so step 1 is now just `pip install -U pyinstaller-hooks-contrib`.
