### ISSUE TITLE
When packaging talib, the file is incomplete.

### ISSUE THREAD

**Issue by kingmo888** [pyinstaller/pyinstaller#7207]
pystaller-version='5.6.1'
python=3.11.0

The python script uses import talib. The talib folder in the final generated folder contains only one python file.
The same code has no problem in Python 3.7.

**Comment by bwoodsend** [comment]
`talib` being what? It's not on pypi. https://pypi.org/project/talib/

**Comment by kingmo888** [comment]
thank you!
it is https://pypi.org/project/TA-Lib/

**Comment by bwoodsend** [comment]
`pyinstaller --hiddenimport=numpy --hiddenimport=talib.stream test.py` gets a basic `import talib` working on Linux. That said, since it links against a system wide installation of TA-LIB, this is never really going to be portable. The fact that they don't even distribute wheels for https://pypi.org/project/TA-Lib/ is a testament to that.
