### ISSUE TITLE
`--log-level=WARN` outputs `INFO` line

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#7231]
Let `bug.py` be empty.

`pyinstaller --log-level=WARN bug.py` outputs
```
2024 WARNING: Several hooks defined for module 'numpy'. Please take care they do not conflict.
631 INFO: Extra DLL search directories (AddDllDirectory): []
632 INFO: Extra DLL search directories (PATH): [(redacted)]
```
Which is weird as the code seems to use `logger.info`:

https://github.com/pyinstaller/pyinstaller/blob/c076ee096fdb782784a654cf86807adcfc9ee1bd/PyInstaller/building/build_main.py#L181
https://github.com/pyinstaller/pyinstaller/blob/c076ee096fdb782784a654cf86807adcfc9ee1bd/PyInstaller/building/build_main.py#L187

**Comment by rokm** [comment]
That's probably because that piece of code is executed in a sub-process via `PyInstaller.isolated.call()`, and log-level settings from the main process are not propagated there...

**Comment by rokm** [comment]
We should probably check for any other uses of `logging`/`logger` in subprocesses, and then decide whether it's worth propagating the setting into sub-processes, or remove the logger uses in there (those particular two messages could be replaced by returning the lists from sub-processes and displaying them in the main process).

**Comment by bwoodsend** [comment]
I toyed with the idea of having a special preconfigured logger available injected in [the child's global namespace](https://github.com/pyinstaller/pyinstaller/blob/c076ee096fdb782784a654cf86807adcfc9ee1bd/PyInstaller/isolated/_child.py#L56) but rejected it at the time because I didn't really expect child processes to do any logging and I forgot that log levels existed so didn't see the harm in using `from PyInstaller.log import logger` like we do now.

**Comment by bwoodsend** [comment]
If there's information we really want logged from the child process then I think passing that logging level down to the child as a 3rd argument to `PyInstaller/isolated/_child.py` is more appealing to me than trying to funnel all that information back up to be logged by the parent.
