### ISSUE TITLE
Cannot open Pyinstaller archive from executable(...) or external archive(...)

### ISSUE THREAD

**Issue by Noobjss** [pyinstaller/pyinstaller#7243]
I meet a problem after converting my python project into executable file with pyinstaller 4.9 and python 3.6.
The .exe file runs well on windows 10, but when I copy it to a windows server 2008 r2 and try to open it, there's a `fatal error: 
Cannot open PyInstaller archive from executable(... .exe) or external archive(... .pkg).`

**Comment by rokm** [comment]
This error means that the executable-embedded archive cannot be found in the executable. 

One possible reason is that the executable got corrupted during the transfer - try computing md5 or sha256 sum of both the original executable file and the executable file on your windows 2008 to verify the file integrity.

The second possible cause of this error is if executable cannot be (re)opened for reading during its scan for the embedded archive, for example due to insufficient permissions. We've seen this happen on linux before (#7130), but I was under impression that on Windows, read & execute permissions are tied together. Could be something on that system is preventing the executable from reading itself.

But if you're building on Windows 10 and trying to run on Server 2008 (which as far as I recall is a server equivalent of Windows 7), you might be running into other issues as well.

So that's as far as we can help you with unsupported version of Windows, python, and PyInstaller.

**Comment by Noobjss** [comment]
> This error means that the executable-embedded archive cannot be found in the executable.
> 
> One possible reason is that the executable got corrupted during the transfer - try computing md5 or sha256 sum of both the original executable file and the executable file on your windows 2008 to verify the file integrity.
> 
> The second possible cause of this error is if executable cannot be (re)opened for reading during its scan for the embedded archive, for example due to insufficient permissions. We've seen this happen on linux before (#7130), but I was under impression that on Windows, read & execute permissions are tied together. Could be something on that system is preventing the executable from reading itself.
> 
> But if you're building on Windows 10 and trying to run on Server 2008 (which as far as I recall is a server equivalent of Windows 7), you might be running into other issues as well.
> 
> So that's as far as we can help you with unsupported version of Windows, python, and PyInstaller.

Thanks, it's a problem of file integrity. The executable file successfully runs after being retransferred.
