### ISSUE TITLE
Build projects in clean virtual environments

### ISSUE THREAD

**Issue by Oreeeee** [pyinstaller/pyinstaller#7262]
**Is your feature request related to a problem? Please describe.**

PyInstaller builds executables in a virtual environment it's currently in and copies all packages from it to a executable. Sometimes the environment might contain some unnescesarry packages.  I use a batch script that creates a clean envirionment every time I want to build an exe, but I think it should be integrated into PyInstaller itself.

**Describe the solution you'd like**

Switch like `--clean-env` should be added that builds the exe in a clean environment, installs packages from `requirements.txt` and deletes the environment.

**Describe alternatives you've considered**

Make it a default behaviour.

**Additional context**
None

**Comment by rokm** [comment]
That's a "no" vote from me. 

The Python environment management (be it venv+pip, anaconda, mingw/msys2 packages, linux-distribution-provided packages, or a combination of those) is beyond the scope of PyInstaller. If you require the functionality you describe, I see no reason why you cannot use a script (like you already do) or a python wrapper that does the job for you.

**Comment by bwoodsend** [comment]
Hmm, so the cons would be:
* Massive slow down in build times since the environment would be scrapped and rebuilt each time.
* Yet another opportunity for `ModuleNotFoundError`s to crop up if a user forgets to add a package to the requirements.txt.
* No way to install local or editable install packages. Turning projects into proper pip installable Python packages is IMO the only sensible way to develop non-trivial Python applications - with PyInstaller or otherwise - so loosing that will make me very unhappy.

And the pros:
* You save yourself from running `python -m venv env; source env/bin/activate; pip install -r requirements.txt` once per project.

This doesn't float well with me at all.

**Comment by bwoodsend** [comment]
And FWIW, you can achieve this using `pipx`:
```bash
pipx run --pip-args 'pyinstaller -r requirements.txt' pyinstaller test.py
```
