### ISSUE TITLE
Termux pyinstaller

### ISSUE THREAD

**Issue by Holmberg-15A** [pyinstaller/pyinstaller#7276]
tell me if it is possible to package the code into an exe via termux (on an armv7 phone) and then run it on a windows PC (10 or 7)

**Comment by rokm** [comment]
No. If you run PyInstaller on armv7 linux version of python, you will get an armv7 linux executable. PyInstaller cannot work as a cross-compiler, because it needs to collect shared libraries (python shared lib, python extensions, etc.) from the running build environment, and those are architecture-specific.

**Comment by Salim9304** [comment]
@rokm 
did pyinstaller start working on termux? 

I installed pyinstaller in termux on armv7 without problems and the "hello world" code compiled without problems, but the binary does not start.

```
...
46424 INFO: Building COLLECT COLLECT-00.toc
46521 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```
$ ./build/t/t
[30520] Error loading Python lib '/data/data/com.termux/files/home/build/t/libpython3.10.so.1.0': dlopen: dlopen failed: library "/data/data/com.termux/files/home/build/t/libpython3.10.so.1.0" not found

Python 3.10.6
pyinstaller 5.7.0

There is nothing in the documentation about Termux, why then are there answers on Github, termux?

**Comment by rokm** [comment]
> $ ./build/t/t

You should run the executable in the `dist` directory, not the `build` one (which is where partial build results are written).
