### ISSUE TITLE
UTF-8 decode error if the path to the script contains letters not in the standard English alphabet

### ISSUE THREAD

**Issue by denivic** [pyinstaller/pyinstaller#7361]
## Description of the issue
I am using PyInstaller in the context of [PSGCompiler](https://github.com/PySimpleGUI/psgcompiler) in order to create exe files, but the repository seems inactive - I have submitted this issue there as well even though I think it is an issue with PyInstaller.

If your script and/or icon is located in a folder where the path has letters such as `æ`, `ø` or `å` (in other words non-English letters) it will fail and display an error (`utf-8 decode error: invalid continuation byte` - see section below). Initially, I thought it was due to the `&` being included in one of the folder names, but tests show that is not the issue. What is really weird is that the position reported in the log is not even one that corresponds to `æ`, `ø` or `å` in the path given further down. It is - as far as I can tell - an `s` (unless I'm reading the log incorrectly).

This is my first time posting an issue on GitHub, so let me know if I did something wrong.

### Context information
PSGCompiler version: 1.5.0
PyInstaller version: 5.7.0
Python version: 3.10.8
Platform: Windows-10-10.0.19044-SP0
Other platforms: I have not tried this on other platforms nor do I have the option to.

### Example program

```py
import PySimpleGUI as gui


layout = [[gui.Text('Kør mangelmotor')], [gui.Button('OK')]]
main_window = gui.Window(title='Mangelmotoren', icon='GUI\Resources\mm_ikon.ico', layout=layout, margins=(100, 50))

while True:
    event, values = main_window.read()

    if event == 'OK' or event == gui.WIN_CLOSED:
        break

main_window.close()
```

### Steps to re-produce error
Create a folder with the letters mentioned in the first section of this issue (or other non-English letters). The path I used was:

`G:/ADM/Administration & Service/Administration/Økonomi/Ledelsesinformation/Mangelkontrol/Mangelmotor/Udvikling/GUI/main_window.py`

Then just try and run using PSGCompiler. PSGCompiler uses PyInstaller under the hood, but I am unsure of what command it uses. I assume it's just generating an .exe using the default/standard commands with no special commands.

### Stacktrace / full error message
```
[EXE Maker] Starting process...
264 INFO: PyInstaller: 5.7.0
264 INFO: Python: 3.10.8
295 INFO: Platform: Windows-10-10.0.19044-SP0
[EXE Maker] *********************** FAILED ***********************
'utf-8' codec can't decode byte 0xd8 in position 63: invalid continuation byte
```

**Comment by bwoodsend** [comment]
Given that we have [a whole collection of tests](https://github.com/pyinstaller/pyinstaller/blob/c2011f1fee56fab611070e365fb26edd4a2c2fff/tests/functional/test_path_encodings.py) for unicode filenames under various code pages, I doubt that this is PyInstaller's bug. What happens if you run PyInstaller directly?
```
python -m PyInstaller "G:/ADM/Administration & Service/Administration/Økonomi/Ledelsesinformation/Mangelkontrol/Mangelmotor/Udvikling/GUI/main_window.py"
```

**Comment by rokm** [comment]
0xd8 is ø in the ANSI codepage, and the exception is raised [here](https://github.com/PySimpleGUI/psgcompiler/blob/46d9761e3e8659d91c10ba7e78bebde1fa80e083/psgcompiler.pyw#L42) because psgcompiler assumes that the encoding of captured stdout is utf-8.

As far as I can tell, when `subprocess.Popen()` captures stdout via `subprocess.PIPE`, the subprocess' `sys.stdout.encoding` is not utf-8 but local encoding. I suppose a work-around is to force utf-8 I/O via `set PYTHONIOENCODING=utf8` environment variable before running psgcompiler.

Either way, I don't think this is our problem to solve.

**Comment by denivic** [comment]
> Given that we have [a whole collection of tests](https://github.com/pyinstaller/pyinstaller/blob/c2011f1fee56fab611070e365fb26edd4a2c2fff/tests/functional/test_path_encodings.py) for unicode filenames under various code pages, I doubt that this is PyInstaller's bug. What happens if you run PyInstaller directly?
> 
> ```
> python -m PyInstaller "G:/ADM/Administration & Service/Administration/Økonomi/Ledelsesinformation/Mangelkontrol/Mangelmotor/Udvikling/GUI/main_window.py"
> ```

I wasn't too sure, but thank you for clarifying. This worked by the way, so _it is_ an issue with PSGCompiler.

I will look into what @rokm said. Thanks for the help.
