### ISSUE TITLE
Pyinstaller Updater

### ISSUE THREAD

**Issue by KelvinSan** [pyinstaller/pyinstaller#7376]
Will Pyinstaller ever have a built-in application updater? As of recent, pyUpdater was officially achieved leaving no real option for updating pyinstaller apps.

**Comment by bwoodsend** [comment]
Given that an update is just a case downloading the new one and deleting the old, I really don't see the point. On the flip side:
* It makes no sense if the application has been squirted through inosetup or appimage.
* It's an pain on Windows and macOS since neither will allow the old application's files to be removed whilst it's still running.
* It leads to the inevitable question of how to preserve the application's current state across upgrades so that the user doesn't loose data.
* It naively assumes that the application is written to somewhere not owned by root/admin.
* It makes code signing even more over complicated than it already is.
* It would be ridiculously expensive for PyInstaller to test.
* It introduces a load of configuration for the update URLs, delta URLs, signing keys, version schemes, knowing which versions are officially supported, update frequency, when to check, when to download, when to do the update itself, how many deltas to provide before requiring the user to download from scratch, someway to override the URLs so that you can test the upgrade flow without having to release it first, some way to magically fix all your old versions' update URLs when you discover that ARM exists and that `-windows64bit` is therefore an inadequate platform tag, yah dee dah dee dah, why are we doing this again? Ahh yes, to save two button clicks!

**Comment by rokm** [comment]
> Will Pyinstaller ever have a built-in application updater?

That's unlikely to happen, as it is well beyond the scope of PyInstaller itself.

An application-built-in updater should be part of the application code. Not only to allow customization, but because it needs to be somehow integrated with the rest of the application's interface (be it command-line or graphical one).

On the other hand, the bulk of PyInstaller's work at runtime is done in C-written bootloader, which sets up the environment and embedded python interpreter, and then runs your frozen application code. The user has no control over this stage, so it makes little sense to try to cram an updater functionality in the bootloader (notwithstanding the challenges of implementing such functionality in low-level C).

While technically we could provide a run-time module for updater API, similar to the one we have for splash screen, I see no point in adopting a codebase of size of PyUpdater into PyInstaller's codebase, and definitely would not want to keep maintaining it. So if you require this sort of functionality, find and use a 3rd party library that replaces PyUpdater.
