### ISSUE TITLE
how to use the --resource option 

### ISSUE THREAD

**Issue by RoamingCookie** [pyinstaller/pyinstaller#7398]
i want add a large 7z archive to compiled exe in one file mode which may or may not be used depending on the user on each run

i want to manage when the archive should be extracted, if i add it as data file, it will get extracted every time user clicks on it, i want it to be only extracted if needed, to decrease launch time

with some Google searches i think i can achieve this by --resource option but nothing is added to the executable when i use this

**Comment by rokm** [comment]
`--resource` option is for adding [Windows resources](https://en.wikipedia.org/wiki/Resource_(Windows)) (e.g., translatable  strings) to the executable. 

What you want (some sort of on-demand extraction) is not possible with PyInstaller's onefile mode; because all extraction happens in bootloader before your frozen code is ran, you cannot influence what should and what should not be extracted...
