### ISSUE TITLE
sys.path generates another issue

### ISSUE THREAD

**Issue by alexd555** [pyinstaller/pyinstaller#7404]
Hi,

If I have a module(C:\A\B\module1.py) in another directory that contains for example "import glob"
And I want to add new path sys.path,append("C:\A\B\") in my_module.py then I got an error that can't import glob.

Should it be fixed ?

Thanks,
Alex

**Comment by bwoodsend** [comment]
This isn't a support forum. Either report actionable and reproducible bugs by filling out the issue template or stop wasting volunteer's time.

**Comment by rokm** [comment]
> Should it be fixed ?

By modifying `sys.path`, you are adding extra modules to your frozen application at *run time*. These modules do not undergo PyInstaller's import analysis at build time, and therefore their dependencies are not automatically collected.

So there's nothing to fix; if you want to dynamically add extra modules at run-time, you need to manually ensure that all its dependencies (and their dependencies...) are collected at build time (e.g., using `hiddenimports`).

**Comment by alexd555** [comment]
What do you mean by "hidden inmports" ? @rokm 
pyinstaller has a flag for it ?

I can add a flag in pyinstaller , But I still want to be able to run the script normally through Python. Because if I add sys.path.append then I will have the issue with .exe
Do you understand what I mean ?

Thanks,
Alex

**Comment by rokm** [comment]
> pyinstaller has a flag for it ?

https://pyinstaller.org/en/stable/usage.html#cmdoption-hidden-import

You can also specify hidden imports in the generated [spec file](https://pyinstaller.org/en/stable/spec-files.html), but then you need to build using the .spec file instead of directly from .py file (which regenerates the .spec file each time).

FWIW, modifying `sys.path` at run time with hard-coded path is generally a questionable design choice, as it will make your frozen application non-portable (dependent on the same path existing on target system).
