### ISSUE TITLE
Log level `DEPRECATION` is documented but not working

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#7413]
## Description of the issue

Log level `DEPRECATION` is documented but not working.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.7.0```
* Version of Python: 3.10.6
* Platform: Ubuntu 22.04
* How you installed Python: apt
* Did you also try this on another platform? Does it work there? yes, same thing
* try the latest development version, using the following command: yes, same thing

### A minimal example program which shows the error

```
$ pyinstaller --help | grep -U1 DEPREC
  --log-level LEVEL     Amount of detail in build-time console messages. LEVEL
                        may be one of TRACE, DEBUG, INFO, WARN, DEPRECATION,
                        ERROR, CRITICAL (default: INFO). Also settable via and
$ pyinstaller --log-level DEPRECATION .
[...]
pyinstaller: error: Unknown log level `DEPRECATION`
```

**Comment by rokm** [comment]
Indeed. Looks like the problem lies in the fact that `logging.addLevelName()` does not add the level name as a module-level attribute, but only registers it with its internal dictionaries. Thus `getattr(logging, 'DEPRECATION')` raises an error.

Either we'll need to use the `logging`'s internal dictionary for the lookup, or create our own.

**Comment by bwoodsend** [comment]
Now I understand why this line existed:

https://github.com/pyinstaller/pyinstaller/blob/d6ff0802dd6f2fbeccb4a6c47e1cf24c61c31205/PyInstaller/log.py#L21

Let's just create our own dict for them - I didn't like the `getattr(logging, ...)` stuff even before seeing this issue.
