### ISSUE TITLE
ImportError: cannot import name 'etree' from 'lxml' (unknown location)

### ISSUE THREAD

**Issue by novski** [pyinstaller/pyinstaller#7418]
I am trying hard to get my wxpython app running on mac and win. [latest builds](https://github.com/novski/diagrams.net-cable-list/releases/latest).
While I got Windows working, MacOS refuses and gives me this:
```
Traceback (most recent call last):
File "/private/var/folders/sf/yfrzcwy91jz9m0cc0y82g_k00000gn/T/_MEIVChdug/./main.py", line 5, in <module>
from scripts.scraper import scrape
File "/private/var/folders/sf/yfrzcwy91jz9m0cc0y82g_k00000gn/T/_MEIVChdug/scripts/scraper.py", line 2, in <module>
from lxml import etree as ET
ImportError: cannot import name 'etree' from 'lxml' (unknown location)
```
`cd /private/var/folders/sf/yfrzcwy91jz9m0cc0y82g_k00000gn/T/_MEIVChdug/lxml/`
```
lxml ls
_elementpath.cpython-310-darwin.so isoschematron
builder.cpython-310-darwin.so      objectify.cpython-310-darwin.so
etree.cpython-310-darwin.so        sax.cpython-310-darwin.so
```
[source](https://github.com/novski/diagrams.net-cable-list)
built with gh-actions matrix 
same result locally with `pyinstaller drawio-cable-labler.spec`

Also tried #5431 `collect_submodules('lxml')` and #5306 but it does not import etree for me so all until now is unsuccessfully.
Do I miss a path does it get overwriten or what is going on here?
How can i detect overwriten imports or give more context?

**Comment by rokm** [comment]
Your GUI is trying to run your `main.py`  script (which in turns loads and runs `scripts/scraper.py`) using external python interpreter:
https://github.com/novski/diagrams.net-cable-list/blob/85429579e48ecd292fa1ed0b2436d90da282f627/window.py#L236

This sort of thing doesn't work in a frozen application, because frozen application runs in embedded python interpreter  (with modules that are collected into frozen application), and trying to run python interpreter ends up running system-provided python, which typically won't have your requirements (in this case `lxml`) installed.

You will need to reorganize your subprocess spawning to go through the main executable (i.e., `sys.executable`), and add special command-line handling that will detect subprocess (based on command-line arguments) and divert program execution accordingly. See https://github.com/pyinstaller/pyinstaller/discussions/5978 for an example. Alternatively, you could also use `multiprocessing` module to execute your command scripts as frozen code instead of external scripts (but make sure you call `multiprocessing.freeze_support` at the start of entry-point script). The third option is to separately freeze your `main.py`, but that would require two-step build process, and would likely be further complicated by the fact that you're building macOS bundle.

On a somewhat related note, `onefile` macOS bundles are a bad idea - unless you have a good reason for using `onefile` (and know what you are doing w.r.t. subprocesses), you should probably go `onedir` way.

**Comment by rokm** [comment]
You might also consider simply foregoing the multiprocess design in the GUI application, and do your processing in a separate thread instead of a separate process to keep things simple. That way, you don't have to worry about program flow dispatch within main executable or dealing with multiple executables/external scripts.
