### ISSUE TITLE
Frozen application keeps running forever in the background on OS X Monterey 12.6.3

### ISSUE THREAD

**Issue by RobertoBagnara** [pyinstaller/pyinstaller#7438]
## Description of the issue
The frozen application, invoked without arguments, prints usage information, gives the prompt back, and then keeps printing usage information around once per second forever.  The process cannot be killed and the only way to stop this seems to be closing the terminal.
 
Note that the same application frozen for Windows and Linux with the same version PyInstaller, works perfectly on both platforms, so I guess it is something OS X specific.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.7.0```
* Version of Python: 3.10
* Platform: OS X Monterey 12.6.3
* How you installed Python: apt
* Did you also try this on another platform? Yes, Linux and Windows, and it works there

This simple script allows reproducing the problem (it only depends on the availability of ```invoke``` and ```git```:
```
#!/bin/bash

set -ex

BUILD=/tmp/workdir_$$
DIST="/tmp/strictdoc"

(
    #rm -rf "${BUILD}"
    mkdir -p "${BUILD}"
    cd "${BUILD}"
    git clone https://github.com/strictdoc-project/strictdoc.git
    cd strictdoc

    #rm -rf "${DIST}"
    mkdir -p "${DIST}"
    invoke -c tasks release-pyinstaller
)

```

If you call the above script ```go.sh```, then simply do

```
$ go.sh
$ /tmp/strictdoc/strictdoc/strictdoc

### Stacktrace / full error message


```
$ ./go.sh
...
76103 INFO: Converting EXE to target arch (x86_64)
76267 INFO: Removing signature(s) from EXE
76419 INFO: Appending PKG archive to EXE
76441 INFO: Fixing EXE headers for code signing
76649 INFO: Re-signing the EXE
77003 INFO: Building EXE from EXE-00.toc completed successfully.
77009 INFO: checking COLLECT
77009 INFO: Building COLLECT because COLLECT-00.toc is non existent
77010 INFO: Building COLLECT COLLECT-00.toc
87440 INFO: Building COLLECT COLLECT-00.toc completed successfully.
$ /tmp/strictdoc/strictdoc/strictdoc
usage: strictdoc [-h]
                 {about,export,import,passthrough,dump-grammar,server,version}
		                  ...
				  strictdoc: error: the following arguments are required: command

Further help:
'strictdoc -h/--help' provides a general overview of available commands.
'strictdoc <command> -h/--help' provides command-specific help.
abramos-MacBook-Pro:reproduce roberto$ usage: strictdoc [-h]
                 {about,export,import,passthrough,dump-grammar,server,version}
		                  ...
				  strictdoc: error: argument command: invalid choice: 'from multiprocessing.resource_tracker import main;main(6)' (choose from 'about', 'export', 'import', 'passthrough', 'dump-grammar', 'server', 'version')

Further help:
'strictdoc -h/--help' provides a general overview of available commands.
'strictdoc <command> -h/--help' provides command-specific help.
usage: strictdoc [-h]
                 {about,export,import,passthrough,dump-grammar,server,version}
		                  ...
				  strictdoc: error: argument command: invalid choice: 'from multiprocessing.resource_tracker import main;main(7)' (choose from 'about', 'export', 'import', 'passthrough', 'dump-grammar', 'server', 'version')

Further help:
'strictdoc -h/--help' provides a general overview of available commands.
'strictdoc <command> -h/--help' provides command-specific help.
...

```

**Comment by rokm** [comment]
If your code uses `multiprocessing` (directly or indirectly), you need to call `multiprocessing.freeze_support()` at the start of your entry-point script (before any `multiprocessing` primitives are used). Failing to do so results in constant process spawning in the frozen application.

So in this case, you need to add the following block at the top of `strictdoc/cli/main.py`:
```python
# pylint: disable=wrong-import-position
# flake8: noqa: E402

import os
import sys

# Ensure that multiprocessing.freeze_support() is called in a frozen application
import multiprocessing
if __name__ == '__main__':
    if getattr(sys, 'frozen', False):
        multiprocessing.freeze_support()

strictdoc_root_path = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
)
# [...]
```

**Comment by RobertoBagnara** [comment]
It works: thanks!

**Comment by stanislaw** [comment]
> If your code uses `multiprocessing` (directly or indirectly), you need to call `multiprocessing.freeze_support()` at the start of your entry-point script (before any `multiprocessing` primitives are used). Failing to do so results in constant process spawning in the frozen application.

@rokm, thanks a lot for sharing this information with us. I am pretty sure I was digging deep enough through the PyInstaller docs but is there any chance that I missed this information somewhere in the docs? Could you point me to the right source of info? Thanks.

**Comment by rokm** [comment]
> > If your code uses `multiprocessing` (directly or indirectly), you need to call `multiprocessing.freeze_support()` at the start of your entry-point script (before any `multiprocessing` primitives are used). Failing to do so results in constant process spawning in the frozen application.
> 
> @rokm, thanks a lot for sharing this information with us. I am pretty sure I was digging deep enough through the PyInstaller docs but is there any chance that I missed this information somewhere in the docs? Could you point me to the right source of info? Thanks.

The python documentation for [`multiprocess.frezee_support`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) mentions PyInstaller, but implies that calling the function is needed only for Windows executables, and that has no effect on other OSes. However, this applies only to python's default implementation, which I assumed is used by `py2exe`.

In PyInstaller-frozen application, our [run-time hook overrides this function](https://github.com/pyinstaller/pyinstaller/blob/4222dc4d623633df713e69b03df66ec10a27df93/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L24-L54), and uses it to properly divert the program flow in sub-processes spawned by `multiprocessing` (the resource tracker process, and each worker process). This is necessary because multiprocessing spawns sub-processes using `sys.executable`, which in a frozen application points to your executable (so without the redirection done by `freeze_support`, the subprocesses would end up running your main application code again).

I don't think this is really documented anywhere (and perhaps it if was, it would reduce the amount of times I have to go through explaining it); but the requirement to call `multiprocessing.freeze_support` has been around for a long time, and a search for `PyInstaller + multiprocessing` should turn up some clues (it's how I became aware of it when I started using PyInstaller).

EDIT: ultimately the idea is to handle this redirection behind-the-scenes (akin to calling the `freeze_support` in the runtime hook itself), to avoid situations when the issues are caused by some 3rd party package using `multiprocessing` without the user being aware of it. But there's various sub-problems that need to be solved before that can happen...

**Comment by bwoodsend** [comment]
I think I speak for Rok as well as myself in thinking that if we sat down and cleaned up the convoluted mess that is the code powering multiprocessing support which we inherited, is barely follow-able and been neglected for years, we could eliminate the need for `freeze_support()` and be done with it. It's surprisingly hard to motivate yourself to document a situation that you think is nonsensical, shouldn't exist and *may* in theory disappear anyway.

**Comment by stanislaw** [comment]
Thank you for your explanations! It is good to know that this behavior has a specific reason, and that it is hard to fix for the time being.

It might be that this thread will become a yet another place where the need to do the `freeze_support` is most officially documented 😄
