### ISSUE TITLE
[Help] When I make the EXE file with librosa library, I got the error message.

### ISSUE THREAD

**Issue by YouMinJung** [pyinstaller/pyinstaller#7489]
Hi.

I want to make exe file with pyinstaller. I used 'librosa' library.
When I excute the exe file i made, error message occurred. The error message is like below.

Traceback (most recent call last):
File "SoundProcess_Program.py", line 11, in
File "", line 983, in _find_and_load
File "", line 967, in find_and_load_unlocked
File "", line 677, in load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
File "librosa_init.py", line 215, in
File "lazy_loader_init.py", line 243, in attach_stub
ValueError: Cannot load imports from non-existent stub 'C:\Users\AppData\Local\Temp\_MEI37722\librosa\init.pyci'
[22432] Failed to execute script 'SoundProcess_Program' due to unhandled exception!

I already used hook-extra file like below and also i set the hidden-import=librosa

from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('librosa')
However, Error still occur...

What is the problem? How to fix this problem?

**Comment by rokm** [comment]
The problem is that `librosa.__init__` passes `__file__` to `lazy.attach_stub()` call ([here](https://github.com/librosa/librosa/blob/c800e74f6a6ec5c27e0fa978d7355943cce04359/librosa/__init__.py#L215)), and that `lazy.attach_stub()` naively tries to construct the stub filename by appending an `i` to the filename ([here](https://github.com/scientific-python/lazy_loader/blob/8a3a49463b8ae370f54cfe31746a61d8377e815e/lazy_loader/__init__.py#L240)). But in the PyInstaller-frozen application, the module is collected as byte-compiled pyc, so `__file__` has a `.pyc` suffix. Hence the error
```
 ValueError: Cannot load imports from non-existent stub 'C:\Users\AppData\Local\Temp_MEI37722\librosa\init.pyci'
``` 
(note the incorrect suffix).

So to fix this, you will need to patch `librosa/__init__.py` file to read something like:
```python
# ...
# ...
# ...

import lazy_loader as lazy
from .version import version as __version__

# In PyInstaller-frozen application, __file__ has .pyc suffix
_filename = __file__
if _filename.endswith('.pyc'):
    _filename = _filename[:-1]

__getattr__, __dir__, __all__ = lazy.attach_stub(__name__, _filename)
```

And you also need the ` datas = collect_data_files('librosa')` so that the .pyi file is collected as a data file.

**Comment by rokm** [comment]
However, `lazy_loader` seems to have recently fixed the problem with naive filename construction:
https://github.com/scientific-python/lazy_loader/commit/e1e48fa531101fee99036c397b5c97afb4b432e8

So if you install `lazy_loader` from their git main branch, it should work without any additional patching (provided you collect `librosa` data files):
```
pip uninstall lazy-loader
pip install git+https://github.com/scientific-python/lazy_loader
```
