### ISSUE TITLE
Can QtCore.QProcess be freeze_support like multiprocessing

### ISSUE THREAD

**Issue by kingmo888** [pyinstaller/pyinstaller#7512]
In the pyqt5 script, I use code similar to the following. When pyinstaller generates an exe, multiple instances will appear when running.

```
        # init Web server sub process
        self.process: QtCore.QProcess = QtCore.QProcess(self)
        self.process.setProcessChannelMode(self.process.MergedChannels)

        self.process.readyReadStandardOutput.connect(self.data_ready)
        self.process.readyReadStandardError.connect(self.data_ready)
        self.process.started.connect(self.web_started)
        self.process.finished.connect(self.web_finished)

        # start sub process
        cmd: list = [
            "-m"
            "uvicorn",
            "myapp.webserver.web:app",
            f"--host={host}",
            f"--port={port}"
        ]
        self.process.start(sys.executable, cmd)
```

I know that the "multiprocessing.freeze_support()" method can be used to solve similar problems when multiple processes are involved.

**Comment by bwoodsend** [comment]
No, and I very much doubt that it would be possible to add support for it. `freeze_support()` relies on being able to replace some of multiprocessing's internal classes to include a signal the subprocess to behave like `python.exe` rather than effectively re-launch your application. Qt is written in C++ which doesn't allow us to replace methods/classes.

That said, you should never use subprocesses just to invoke a Python package's entrypoint. `python -m uvicorn` just runs [`uvicorn.main()`](https://github.com/encode/uvicorn/blob/73b7bcdcaa663dd9d74a9fcadea0ce3ec1761f2f/uvicorn/__main__.py#L4) so all you need is something like:

```python
import uvicorn
uvicorn.main(["myapp.webserver.web:app", f"--host={host}", f"--port={port}"])
```

**Comment by rokm** [comment]
> In the pyqt5 script, I use code similar to the following. When pyinstaller generates an exe, multiple instances will appear when running.

That's because you are calling your PyInstaller-frozen executable (which is pointed to by `sys.executable`). Which then again runs a subprocess that calls `sys.executable`. Which again runs a subprocess...

If you want to run subprocess like that, you'll need to modify your entry-point script to detect that it is supposed to be a subprocess and divert the program flow accordingly. E.g.,

```python

import sys

# Entry point
if __name__ == '__main__':
    if len(sys.argv) >= 4 and sys.argv[1] == '-m' and sys.argv[2] == 'uvicorn' and sys.argv[3] == 'myapp.webserver.web:app':
       # This is supposed to be a subprocess
       import uvicorn
       uvicorn.main(sys.argv[3:])
   else:
      # This is the main program
      # ...
      # init Web server sub process
      self.process: QtCore.QProcess = QtCore.QProcess(self)
      self.process.setProcessChannelMode(self.process.MergedChannels)

      self.process.readyReadStandardOutput.connect(self.data_ready)
      self.process.readyReadStandardError.connect(self.data_ready)
      self.process.started.connect(self.web_started)
      self.process.finished.connect(self.web_finished)

      # start sub process
      cmd: list = [
          "-m"
          "uvicorn",
          "myapp.webserver.web:app",
          f"--host={host}",
          f"--port={port}"
      ]

      self.process.start(sys.executable, cmd)

     # ...

``` 

Which is essentially what our `multiprocessing` runtime hook does with `freeze_support`; it replaces `freeze_support` with [a function that scans `sys.argv` and redirects the program flow for `multiprocessing` subprocesses](https://github.com/pyinstaller/pyinstaller/blob/7230e8bbda4a35f8afee41ac77dae6ed2f1e1348/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L26-L53).

Also, if you are using `onefile`  mode, you should restore the `_MEIPASS2` environment variable to prevent the subprocess from unpacking the executable again (in a different temporary directory). With  `QProcess`, you can probably use `QProcess.setEnvironment()` and `QProcessEnvironment`.
