### ISSUE TITLE
"zsh segmentation fault" with aspose.slides on MacOS

### ISSUE THREAD

**Issue by bowespublishing** [pyinstaller/pyinstaller#7570]
I can successfully create and package the following script on Windows however when using MacOS I get "zsh segmentation" fault when performing the same task. Simple example below

```
import aspose.slides as slides

# Instantiate a Presentation object that represents a presentation file
with slides.Presentation() as presentation:
    slide = presentation.slides[0]
    slide.shapes.add_auto_shape(slides.ShapeType.LINE, 50, 150, 300, 0)
    presentation.save("NewPresentation_out.pptx", slides.export.SaveFormat.PPTX)
```

I used - pyinstaller --noconfirm --onedir --windowed --collect-all "aspose" "script.py"

**Comment by bwoodsend** [comment]
aspose.slides looks pretty broken to me even without PyInstaller.
```
> otool -L /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aspose/slides.cpython-39-darwin.dylib 
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aspose/slides.cpython-39-darwin.dylib:
	@rpath/slides.cpython-39-darwin.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libpython3.9.dylib (compatibility version 3.9.0, current version 3.9.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```
It's linked against itself for some bizarre reason and against a `libpython` with a hardcoded location `/usr/local/lib/libpython3.9.dylib`. Since my Python environment is not using the `/usr/local/` prefix, I can't even import aspose.slides in normal Python.

I suspect that you are using Python installed via brew which does use the `/usr/local` prefix. In which case, it should load ok under normal Python but when PyInstaller runs on it, there will be two copies of `libpython` getting loaded - the one PyInstaller put in your application and the original one at `/usr/local/lib/libpython3.9.dylib`. macOS treats loading two copies of  the same library as criminal and kills the process.

**Comment by rokm** [comment]
Recent builds of homebrew (e.g., `python@3.9`) also seem to be framework-based, and have no `libpython3.9.dylib`. Of course, if symlink was manually created to work around this, then PyInstaller will create a duplicate due to lack of  symlink support, and you'll find both `Python` (the original library from e.g., `/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/Python`) and `libpython3.9.dylib` in your frozen application. If that's the case, you should remove `libpython3.9.dylib` and replace it with symlink to `Python`.
