### ISSUE TITLE
APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', OSError(22, 'Invalid argument'))

### ISSUE THREAD

**Issue by nakajit777** [pyinstaller/pyinstaller#7602]
I'm using a GPT-4 model with AzureOpenAI in streamlit, and before converting to EXE, it worked correctly, but as soon as I converted to EXE, I started getting the following error.
Help me.

APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', OSError(22, 'Invalid argument'))
Traceback:
File "streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "C:\Users\*********\Desktop\dist\main.py", line 998, in <module>
    main()
File "C:\Users\*********\Desktop\dist\main.py", line 312, in main
    response = openai.ChatCompletion.create(
File "openai\api_resources\chat_completion.py", line 25, in create
File "openai\api_resources\abstract\engine_api_resource.py", line 153, in create
File "openai\api_requestor.py", line 216, in request
File "openai\api_requestor.py", line 529, in request_raw

---My env---
OS:Windows10 22h2
Python:3.9.13
Pyinstaller:5.10.1
pyinstaller-hooks-contrib:2023.2

**Comment by rokm** [comment]
Is this the whole error traceback? I would expect to see the underlying exception traceback to be shown as well, considering [that `request_raw` in `"openai\api_requestor.py", line 529` does a `raise Exception() from e`](https://github.com/openai/openai-python/blob/v0.27.5/openai/api_requestor.py#L528-L531).

Also, since the API in question requires an API key, you're going to have to debug this on your own. I suggest you first try freezing a simple `ChatCompletion` example without `streamlit`, because it is not clear how the code is run in the first place (the file names imply that this part of the code is ran as python script, and not directly in frozen application).

As for `OSError(22, 'Invalid argument')` itself, this looks like an invalid path somewhere? Perhaps for your API key file? Or the SSL certificates in the frozen application? It's hard to say based on available information, though. Check if there's a preceding error traceback available, and if that offers any insights. Otherwise, instrument the offending code and see what's different from when ran as unfrozen python script.
