### ISSUE TITLE
exe from pyinstaller on Windows 10 fails to execute on Windows 11

### ISSUE THREAD

**Issue by CrimpOn** [pyinstaller/pyinstaller#7607]
Have a Python3 script that works on Windows 10 and Linux Mint 20.1  pyinstaller on each platform creates executables that work as well.  A friend has Windows 11 and has not installed Python. When the executable is run on his Windows 11, the user reports a "Permission Error:  [Err 13] Permission Denied" on the statement **open(filename, 'a')** 
The script traps the error, displays a message, and exits. 

The user swears that the file is not already open in another application.

Can someone please point me to documentation describing:

- How to find more **detail** about [Errno 13], such as why the file cannot be opened (the **specific** reason).
- Any changes to a script that are required for Windows 11.
- What has to be bundled into the pyinstaller process to compensate for the Windows 11 machine not having Python installed.

**Comment by rokm** [comment]
One way to get `[Errno 13] Permission denied` is if you try to `open()` a directory instead of a file. Are you 100% that `filename` is pointing to a file?

And, are you 100% that this is not permissions-related problem? E.g., the file having been created as Administrator, and subsequently trying to access it as a regular user? Or trying to open a non-existent file (which in 'a' mode would create it) in location where user does not have write permissions?

Either way, from the limited information you provided, this does not sound like a PyInstaller issue...

**Comment by CrimpOn** [comment]
Thanks for responding.  I am never 100% certain about anything, but in this case very puzzled.
The script defines:
    **outputfile = "SpeedChecks.csv"**
This does not appear to be a directory.
and this is the section of code:

>         try:
            fileout = open(outputfile, 'a')
        except PermissionError:
            print("You do not have permission to open " + outputfile)
            print("This happens when the file is already opened by another program")
            print("or the user is running a program in a directory where he does not have write permission")
            sys.exit()
        except Exception as e:
            print("Could not open file with unexpected error:" + e)
            sys.exit()
(I don't know where all those blank lines came from.)
This is supposed to open a file in the same Windows directory that the program is running in.  I had **assumed** that if someone has permission to invoke the exe file produced by pyinstaller, that they would also have permission to create an ordinary file in the same directory. The fist time the program runs, the file should not exist. (The goal being every time the program is run, more data is appended to the same file.)

I have run this script successfully both as Python and after using pyinstaller on both Windows 10 and Mint Linux.  Python 3 is installed on both of my Windows 10 machines.  I have also run the exe on a Windows 10 machines that does not have Python 3 installed.  The only differences appear to be:

- Windows 11 rather than Windows 10, plus
- Windows 11 without Python 3.

Appreciate any suggestions.

**Comment by rokm** [comment]
So you implicitly assume that the current working directory is the program directory. Which may or may not be true. When printing the error, you could try resolving the `filename` to full absolute path (e.g., using `os.path.abspath(filename)`) to see if that is in fact the case.

Trying to write in the program's directory will fail when user "installs" (= manually copies) the program directory to read-only location (e.g., moves it to `c:\program files\program` as Administrator) and tries to run it from there. Is that the case here?

Another possibility is that program is ran as two different uses (two regular users, or Administrator and regular user) so the second user cannot open the file created during the first run due to insufficient permissions. Which is another argument against writing files to your program directory if there's a possibility of a multi-user scenario. In this case, you could have your user check if the file exists, and if it does, whether they can open/edit it with some other program. Or remove it altogether (and if they have sufficient permissions on the program's directory, it will be created on next run with proper ownership).

**Comment by CrimpOn** [comment]
These are great ideas. Thanks.  The program looks for a file name as a parameter, and when the user does not specify one, CheckSpeeds.csv is the default. Displaying the absolute path as part of the error message will confirm where the executable has been placed.

Will ask abut user identity.  My regular Windows logon is an "ordinary users".  Forces me to enter the Admin password time after time, but it's a habit from long ago.  Some people may choose to use their Admin account routinely.

I get the sense that because the program has never run successfully, the output file has never been created. (gulp, another assumption).

**Comment by CrimpOn** [comment]
Would like to understand "solution:invalid" and "not planned".
Thanks

**Comment by bwoodsend** [comment]
It just means that you're doing something you shouldn't be to cause the error (i.e. assuming current working directory) rather than a bug in PyInstaller.

**Comment by CrimpOn** [comment]
Thanks.  I am modifying the script to display the entire file path as suggested by rokm. [os.path.abspath(filename)]
I also want to confirm that the file does (or does not) exist as part of the error routine.
i.e. "you can't open this file, and.... (it does or does not exist)"
That appears to be:

> if os.path.exists(filename):
	print("The file exists")
else:
	priint("The file does not already exist")

Wish there was a method to extract more detail about what has caused the Permission Error. 

I appreciate your patience.
