### ISSUE TITLE
Unable to write to files

### ISSUE THREAD

**Issue by dibrinsofor** [pyinstaller/pyinstaller#7629]
## Description of the issue
I have successfully packaged a flask server that logs data into a sqlite db and text files. I have tried monitoring these files while the app is running but it does not look like they are getting written too. I tried moving the directories and setting absolute paths but nothing seems to work.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.10.1```
* Version of Python: ```3.11.0```
* Platform: Windows (English)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
with open("et_logs.txt", "w") as g:
    g.write("look at me, I log things.")

```

### Stacktrace / full error message
No error message, files do not just get written to.

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
The example you provided works just fine for me, and creates the `et_logs.txt` containing the printed line in the current working directory (which is the application's directory if you make a onedir build and run the executable by double-clicking on it). 

Since you did not provide any relevant code, my guess would be that your application is holding the file open for long(er) period of time (maybe its whole life-time?) and you need to [flush](https://docs.python.org/3/library/io.html#io.IOBase.flush) the file's write buffer if you want the contents to be written immediately and be visible to the external application.
