### ISSUE TITLE
Speed up pyinstaller bundling process by using multi cpu cores

### ISSUE THREAD

**Issue by HarelAshwal** [pyinstaller/pyinstaller#7659]
LK"I

Hi There,
I've noticed that pyinstaller doesn't use all CPU cores available,
Is it possible somehow to optimize the bundler to use all available cores to speed up the packing process? 

thanks

**Comment by bwoodsend** [comment]
None of the slow stuff is really parallelizable.

The biggest bottleneck is traversing the dependency graph and running all the hooks. Since every part of that process can add and remove modules and hooks from the to-do list, trying to process that out of order scans/hook runs should have been skipped and dividing the work between processes will either lead to so many process locks that you rarely have more than one core doing any actual work or lead to duplicate scans. All in all I'd expect parallelism to make the process slower rather than faster.

I think the most parallelizable task would be the binary dependency scanning which takes 0.1 seconds in a 40 second build on my machine.
