### ISSUE TITLE
Bad packing experience!!!

### ISSUE THREAD

**Issue by juntaosun** [pyinstaller/pyinstaller#7693]
First of all, thanks to pyinstaller for making it easier to distribute python applications.
However, it is already 2023, and its packaging experience is still so bad. can't believe it. 
If it is packaged in the form of a directory (--onedir/-D), it is a nightmare for complex projects. All files are generated in the root directory, and piles of dlls and various files are mixed together. 

![0](https://github.com/pyinstaller/pyinstaller/assets/22288197/9742e5cb-dd9f-4d7b-8be5-35b9f35d5bd9)

I sent the packaged application to my friend, and the friend saw a bunch of messy files and said: This is too ugly.
Well, I can't help it either.

I don't use single-file mode (--onefile / -F) because it's too slow to start every time.

Search the Internet for keywords about pyinstaller packaging, and many people have the same problem.
Can the packaged files be organized into a directory?
Until yesterday, I searched for another solution.
https://github.com/HaujetZhao/PyInstaller-Perfect-Build-Method
Now packaged, its directory is like this, which is exactly the result I want. beautiful!

![1](https://github.com/pyinstaller/pyinstaller/assets/22288197/72e9d31b-ab9d-44fa-ba88-bcaa09ff9593)

I think my friends will also say: the app you developed is too professional!
Please integrate it into the next version of pyinstaller if possible.
I think this feature request has been raised by many people, but sadly they were all closed.

pyinstaller is really good, convenient and easy to use.
It will be even better if you add this package file organization function!
Hope it gets attention! Thanks!

---
Chinese translation：
首先，感谢pyinstaller能使python应用更方便的进行分发。
可是，都2023年了，它的打包体验还是这么的糟糕，简直不敢相信。
如果用目录形式打包（--onedir/-D），对于复杂的项目来说，这简直就是噩梦，所有的文件全生在根目录下，成堆成堆的dll和各种文件混在一起。我将打包好的应用发给我的朋友，朋友看到一堆凌乱的文件说：这太不美观了。
好吧，我也没办法。
我不使用单文件模式（--onefile / -F），因为它每次启动太慢了。

搜索网上关于pyinstaller打包的关键词，很多人也有同样的问题。
能否将打包的文件整理到一个目录中呢？
直到昨天，我搜索到了另一个解决办法。
https://github.com/HaujetZhao/PyInstaller-Perfect-Build-Method
现在打包，它的目录是这样的，这正是我想要的结果。太漂亮了！

我想我的朋友也会说：你开发的应用太专业了！
如果可能，请将它集成到pyinstaller的下一个版本中。
我想，这个功能请求已经被多人提起过，可惜都被关闭。
pyinstaller真的不错，方便好用。
如果加上这个打包文件整理功能，就更棒了！
希望引起重视！谢谢！

**Comment by rokm** [comment]
Although it is 2023, my stance on this one remains unchanged. 

The current onedir structure, while indeed containing many files in the top-dir directory, is both well-tested and covers more complex cases, such as a package looking up its resources via `__file__`, or using `ctypes` to load a shared library that was originally collected from a system-wide directory. So to handle all these it would take more than just modify `sys.path` like that "perfect build method" does. Not to mention that it would need proper testing and support, and us having to deal with any corner cases arising from it.

If your application is simple enough that you can get away with that relocation, go for it. But don't expect me to support it in any capacity; we're busy enough dealing with issues arising from the constantly evolving python ecosystem, and as far as I'm concerned, working frozen application takes precedence over beautifully-organized one.

If you want your application to look "professional", perhaps you should have created an installer that creates shortcuts to desktop and/or start menu, so that your friend does not have to go look into the actual application directory...

**Comment by juntaosun** [comment]
![UE5](https://github.com/pyinstaller/pyinstaller/assets/22288197/5a74cbd0-082e-4eb1-99b9-cf2a36e49abf)
（UE5）

---

This is the directory after the Unreal 5 engine is packaged. You can see that it is very well organized, and there is only one exe outside. I think this is not to make my application more "professional", but to package more "professional". Of course, I can also choose to use the installer, but that cannot be done out of the box (installation-free). Of course, you can also insist that "it will not be fixed". This is a suggestion from many developers for the future of pyinstaller to make pyinstaller better and more professional. Thank you for your reply~

---

Chinese translation：
这是虚幻5引擎打包后的目录样子，可以看到它整理的很好，外面只有一个exe。我觉得这不是让我的应用更”专业“，而是打包更“专业”，当然，我也可以选择使用安装程序，但那无法做到开箱即用（免安装）。当然您也可以坚持“不会修复”，这是众多开发者对pyinstaller未来的一个建议，让pyinstaller变得更好更专业，感谢回复~
