### ISSUE TITLE
External data not getting bundled into the executable

### ISSUE THREAD

**Issue by chanrt** [pyinstaller/pyinstaller#7706]
I have been working on a [game](https://github.com/chanrt/py-factory). I want to package it into an executable file. I've added the data folder paths in the spec file as follows:
`datas=[('fonts/*', 'fonts/'), ('music/*', 'music/'), ('sounds/*', 'sounds/'), ('sprites/*', 'sprites/')]`

All these folders (fonts, music, sounds, sprites) are at the root of the project.

The executable gets successfully built in the dist folder. However, when the executable is run from the dist folder, it gives file not found errors:
`FileNotFoundError: No such file or directory: 'C:\Code\Game Development\PyFactorio\dist\sounds\structure_placed.wav'.`

If the executable is placed in the root folder (PyFactorio\), then the executable runs without any errors. This implies that the data isn't getting bundled inside the executable. Instead, the executable is looking for it in the current working directory.

What's weird is I'm not encountering this problem with [another game of mine
](https://github.com/chanrt/procedural-racing-3d). That executable runs when placed anywhere.

Please help.

**Comment by rokm** [comment]
Your `loader.get_resource_path` is buggy - [it is trying to access `sys._MEIPASS2`](https://github.com/chanrt/py-factory/blob/9a910bc93bec87d9e75578bd65ef7e23fc9181a3/loader.py#L9), which does not exist. And since you're swallowing exception, you're silently falling back to the current working directory.

The variable is called `sys._MEIPASS`, as referenced in your [working game](https://github.com/chanrt/procedural-racing-3d/blob/9669cb6b8b004883a39b374b107704cd46575ec6/loader.py#L8).

**Comment by chanrt** [comment]
Thanks for replying.

When I initially tried with sys._MEIPASS, I got this error message:
`FileNotFoundError: No such file or directory: 'C:\Users\chess\AppData\Local\Temp\_MEI101282\sprites\structures\conveyor.png'.`
Additionally, the executable did not work in the root folder either. 

On the other hand, with sys._MEIPASS2, the executable at least works in the root folder.

Please advise.

**Comment by rokm** [comment]
>  `FileNotFoundError: No such file or directory: 'C:\Users\chess\AppData\Local\Temp\_MEI101282\sprites\structures\conveyor.png'.`

That's because the glob syntax for `datas` (i.e., `('sprites/*', 'sprites/')` with wildcard in source path) does not preserve sub-directories - the files from `sprites\structures` end up collected into `sprites`.

Unless you really know what you are doing, you should avoid glob syntax, and just use `('sprites', 'sprites')`  instead, which will preserve sub-directories. This applies to all `datas` tuples in your spec.

**Comment by chanrt** [comment]
Removing the sub-directories resolved the issue. Thanks a lot and sorry for taking up your time
