### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by PuddingJoker** [pyinstaller/pyinstaller#7732]
I have been able to run a python project normally locally, but when I package it with pyinstaller and run it, the following error will be reported:  ModuleNotFoundError: No module named 'torch', here is my options:

my computer is m2 mac
my python version is 3.9.17
and the pyinstaller was downloaded by pip, the latest version

**Comment by rokm** [comment]
Is PyInstaller installed in the same python environment as the `torch` and the rest of your dependencies?

**Comment by PuddingJoker** [comment]
> Is PyInstaller installed in the same python environment as the `torch` and the rest of your dependencies?

i was use pip install -r requirements.txt to install my dependencies and torch was included in the .txt file

**Comment by rokm** [comment]
But do you have multiple python environments, and PyInstaller also installed in one of them? In that case, `pyinstaller` command could point to PyInstaller in a different environment.

What is the output of `which pyinstaller`? And when you run PyInstaller, it should print its version and the version of python it is running under - does that match the version of your python environment (3.9.17)?

**Comment by PuddingJoker** [comment]
> 

ohhhh~ the python version doesnt match, pyinstaller's python version is 3.11.4, how did this problem arise?
<img width="434" alt="image" src="https://github.com/pyinstaller/pyinstaller/assets/81021391/fb503e17-df01-4877-aa62-f6380c5a5ade">

**Comment by rokm** [comment]
Like I said, you have multiple python environments that have PyInstaller instaleld. Therefore, you cannot be sure to which environment the `pyinstaller` command points.

Either you have to clean up your environments, or run PyInstaller as a module within the specific python environment (e.g., `python3.9 -m PyInstaller ...` instead of `pyinstaller ...`). Or start using python virtual environments, so that activating a particular environment puts the `pyinstaller` script from that particular environment in `PATH`.

**Comment by PuddingJoker** [comment]
thanks! it works
