### ISSUE TITLE
Powershell windows popping up constantly in windowed app

### ISSUE THREAD

**Issue by crankedguy** [pyinstaller/pyinstaller#7749]
Hi,

in my tkinter application, compiled to onedir, all powershell calls with subprocess.run lead to short popups and immediate close of the powershell window. I cannot get rid of it.

The calls are made like
`return subprocess.run(cmd, shell=False, capture_output=True, check=True, encoding="utf-8").stdout`

If you create with spec console=True normal console pops up at start, no powershell popups...
If you run uncompiled script from command line no powershell popups...
If you use cmd instead of powershell (not possible in my case) and console=False no popups...
If you run with console=False no console popup as expected, but countless powershell popups...

I tried without upx, does not help, I honestly don't know how to go on from here...
EDIT : It seems this is by design? Really? Is there any known hack that can be done in pyinstaller or the script itself?

```
pyinstaller==5.12.0
pyinstaller-hooks-contrib==2023.2
Windows 10 Pro 22H2 19045.3086
python 3.11.0
```

This is the specfile
```
a = Analysis(
    ["main.py"],
    pathex=["."],
    binaries=[],
    datas=[...],
    hiddenimports=[
        ...
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # TODO CHANGE TO PROPER PATH
    icon="...",
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='main',
)
```

**Comment by rokm** [comment]
> EDIT : It seems this is by design? Really? Is there any known hack that can be done in pyinstaller or the script itself?

This is standard behavior of Windows applications; if you run a console-enabled program from a process that does not have a console, a new console is opened (and if the parent already has a console, that console is re-used).

Perhaps setting [`subprocess.CREATE_NO_WINDOW`](https://docs.python.org/3/library/subprocess.html#subprocess.CREATE_NO_WINDOW) would help? 

Or passing the `subprocess.STARTUPINFO` with [`subprocess.STARTF_USESHOWWINDOW`](https://docs.python.org/3/library/subprocess.html#subprocess.STARTF_USESHOWWINDOW) and [`subprocess.SW_HIDE`](https://docs.python.org/3/library/subprocess.html#subprocess.SW_HIDE).

Either way, there's nothing for us to do about this - if you ran your script under windowed python interpreter, `pythonw.exe`, instead of regular `python.exe`, you would likely see the same behavior as with windowed pyinstaller application.

**Comment by crankedguy** [comment]
> This is standard behavior of Windows applications; if you run a console-enabled program from a process that does not have a console, a new console is opened (and if the parent already has a console, that console is re-used)

But that would mean "normal cmd" calls would also open a console, which they clearly don't as I said, and tested. They simply work hidden.
This is a crap from powershell itself, which after I researched is complained hundreds of times also from other applications and workflows.
But I will try your other suggestions later, thanks.

**Comment by crankedguy** [comment]
If someone is interested : subprocess.CREATE_NO_WINDOW seems to do the job
