### ISSUE TITLE
PyQT6.5.X fails with to start on macOS (segmentation fault)

### ISSUE THREAD

**Issue by hakan-77** [pyinstaller/pyinstaller#7789]
## Description of the issue

After installing PyQT6.5 on macOS, app fails to start giving segmentation fault error.

I also tried the new 6.5.2. Everything works perfectly fine with PyQt6.4.X

### Context information (for bug reports)

* pyinstaller --version: 5.13.0
* python --version: Python 3.10.11
* Platform: macOS Ventura
* Python installed via python.org  downloaded installer

### A minimal example program which shows the error

```python
from PyQt6.QtWidgets import QApplication, QWidget
import sys

app = QApplication(sys.argv)
window = QWidget()
window.show()
app.exec()
```

### Stacktrace / full error message

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008
Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [31721]
VM Region Info: 0x8 is not in any region.  Bytes before following region: 140737486987256
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      shared memory            7fffffeb2000-7fffffeb3000 [    4K] r-x/r-x SM=SHM  
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
```

Note: The above is from the original app, not the minimal example.

Thank you for the amazing tool!

**Comment by rokm** [comment]
Yeah, I think PyQt6 >= 6.5 does not like the fact that PyInstaller is butchering its Qt .framework bundles. We've seen those segfaults [on our CI as well](https://github.com/pyinstaller/pyinstaller/actions/runs/5235975736/jobs/9453186486) before #7619 was merged. As of #7619 we are attempting to preserve the .framework bundles if we collect libraries from them, so this particular problem should already be fixed in `develop`.

Although if you want to test, make sure you rebuild the bootloader:
```
pip uninstall pyinstaller
PYINSTALLER_COMPILE_BOOTLOADER=1 pip install git+https://github.com/pyinstaller/pyinstaller.git@develop
```

**Comment by hakan-77** [comment]
@rokm, thank you for your prompt response. And once again, you were spot on. 

The development version fixes the problem and I'll be closing the issue. 

Side note: the bug report page has instructions to test with development version and I already tried that. And got the same error. 

Maybe you guys should consider replacing the dev installer command with the above snippet. 

Thank you.

**Comment by bwoodsend** [comment]
> Maybe you guys should consider replacing the dev installer command with the above snippet.

Most of the time, you don't need to recompile the bootloader so the command in the template works. At the moment, the bootloaders in version control are out of sync with the rest of the code base so a recompile is necessary. We should be updating them fairly soon.

**Comment by hakan-77** [comment]
@rokm, I was using the development build (https://github.com/pyinstaller/pyinstaller.git@develop) that solved the issue. I was expecting the new 5.13.2 would solve this problem, but it's still here. Am I missing something?

**Comment by rokm** [comment]
This issue cannot be solved in 5.x series, which are now branched off as `v5` branch (so we can release bugfixes that can be back-ported to 5.x series). The `develop` branch is for upcoming 6.x series, and contains the fix for this issue.

**Comment by hakan-77** [comment]
@rokm, thanks. closing.

**Comment by sanjays442** [comment]
This is not working with virtual environment and also the file size went from 30 mb to 135 mb.

**Comment by sanjays442** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               ByteScrum Tracker [9730]
Path:                  /Volumes/VOLUME/ByteScrum Tracker.app/Contents/MacOS/ByteScrum Tracker
Identifier:            ByteScrum Tracker
Version:               0.0.0 (???)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-11 13:50:46.5583 +0530
OS Version:            macOS 13.5.2 (22G91)
Report Version:        12
Anonymous UUID:        356729EF-64CE-1D6F-F14C-832EE8C7975F

Sleep/Wake UUID:       8AE6B6F3-9A99-430C-9EE6-5BC7084E4FFB

Time Awake Since Boot: 16000 seconds
Time Since Wake:       276 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [9730]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 105553518919672
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)

Kernel Triage:
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage]

**Comment by sanjays442** [comment]
Nevermind, it was logging that was turned on and also I switched back to 6.4.
