### ISSUE TITLE
Cannot open Pylnstaller archive from executable(D: Download Working Hwlnfo hwinfo main.vmp.exe) or externaarchive (D: Download Working Hwlnfo hwinfo main.vmp.pkg

### ISSUE THREAD

**Issue by 17Reset** [pyinstaller/pyinstaller#7818]
After using Pyinstaller to package the program, VMProtect shelled it and it won't run.

**Comment by rokm** [comment]
VMProtect transforms/changes the executable and in the process corrupts PyInstaller's executable-embedded archive. So the error is the expected outcome.

**Comment by 17Reset** [comment]
> VMProtect transforms/changes the executable and in the process corrupts PyInstaller's executable-embedded archive. So the error is the expected outcome.

Thank you for your reply.

**Comment by 17Reset** [comment]
By the way, may I ask, since I can't use VMProtect, what is the other way to shell the program?

> VMProtect transforms/changes the executable and in the process corrupts PyInstaller's executable-embedded archive. So the error is the expected outcome.

May I ask, since VMProtect can't shell it, what other ways are there to shell programs that use Pyinstaller?

**Comment by rokm** [comment]
Not as far as I know. And I imagine that even if you could use VMProtect without corrupting the embedded archive, it would actually protect just the bootloader executable, without collected python modules, data files, and binaries; because (assuming we are talking about onefile build) those are all stored in the embedded archive, about which VMProtect likely has no information.

If you want to protect python modules, you might want to look into pyarmor.

**Comment by 17Reset** [comment]
Thank you for your reply.
