### ISSUE TITLE
Pyinstaller exe fails when signed following apple notarization process

### ISSUE THREAD

**Issue by Lautarob1** [pyinstaller/pyinstaller#7937]
Hello,

I have a python script for Mac which I "compiled" to create a standalone terminal application that runs in any Mac. 

The exe file created by pyinstaller runs with no error when using their own (default) signature. The command used was:
pyinstaller --onefile pyPythonScript.py As expected, it recreate an  exe file using the same name. 

Now, when try to re-sign the script following the Apple notarization procedure (an have the app not blocked by Gatekeeper), the resulting signed file fails. (ONLY the sign is modified, using the following command)

codesign -s "$DevID" -o  runtime -f --timestamp $compFile

where $DevID is of the form:  "Developer ID Application: ENTITY NAME (TEAM ID)"
TEAM ID would be 10 char code 

Once signed as indicated above, the very same exe that was running with no issues, halted throwing the following error message:

[698] Error loading Python lib '/var/folders/wb/x9vsmbzd5yv2djkl8s5_kmdw0000gn/T/_MEIEQQltp/Python': dlopen: dlopen(/var/folders/wb/x9vsmbzd5yv2djkl8s5_kmdw0000gn/T/_MEIEQQltp/Python, 0x000A): tried: '/var/folders/wb/x9vsmbzd5yv2djkl8s5_kmdw0000gn/T/_MEIEQQltp/Python' (code signature in <80977C84-A9E5-30EF-B62C-DE085145A242> '/private/var/folders/wb/x9vsmbzd5yv2djkl8s5_kmdw0000gn/T/_MEIEQQltp/Python' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/Python' (no such file), '/private/var/folders/wb/x9vsmbzd5yv2djkl8s5_kmdw0000gn/T/_MEIEQQltp/Python' (code signature in <80977C84-A9E5-30EF-B62C-DE085145A242> '/private/var/folders/wb/x9vsmbzd5yv2djkl8s5_kmdw0000gn/T/_MEIEQQltp/Python' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/Python' (no such file)
  
No other change whatsoever was done (intentionally at least) other than replace the pyinstaller original signature for one that complies with Apple notarization procedure. 

Thus, here is the dilemma: it is either you deal directly with the Mac reply when trying to access an exe file NOT being notarized (it becomes blocked by Gatekeeper) by disabling the later or you have an authorized file that does not run properly. 

To make things even more complicated, the signed exe (following Apple Notarization procedures) run in certain Macs and not in others. I meant, the error described below is not consistent for all models and OS. For example, using a T2 Intel powered mac and OS 12 (Monterrey) the error did not occur. Like wise, in an older NON T2 intel running Ventura (OS 13). However, in a very similar hardware (2 years older) running Catalina (OS10.15) the error was thrown and also in a couple of M1 or M2 new Macs. 

Obviously, the error are related to this file: T/_MEIEQQltp

Any help on what is happening here? How can a access the internals of the EXE to review was going on?

Thanks!

**Comment by rokm** [comment]
You should not be using `onefile` mode if you want to post-hoc sign the executable, as you have no way of signing the collected shared libraries (like the `Python` shared library). 

There is a [--codesign-identity](https://pyinstaller.org/en/stable/usage.html#cmdoption-codesign-identity) command-line option for passing your `$DevID` to PyInstaller itself, so it can sign the collected binaries with your codesign identity instead of ad-hoc signature before it writes them to the executable-embedded archive. But whether it will work or not really depends on binaries being correctly classified as binaries during collection (and perhaps also [the options used](https://github.com/pyinstaller/pyinstaller/blob/d1b6b520a017578a19e1cb9514752a4517755ee0/PyInstaller/utils/osx.py#L367-L386), which are tailored towards .app bundles, not POSIX executables).

**Comment by Lautarob1** [comment]
Hello and thanks for the reply Have you noticed that the problem here is the notarize process required by Apple to authorize the exe ?That is, without changing the signature poses by pyinstaller the one-file exe runs absolutely fine.The problem arises when the exe is re-signed in order to be able to notarize it thru Apple.Please give a second thought to my original post.Thanks!Lautaro Barrera BOn Sep 13, 2023, at 3:48 PM, Rok Mandeljc ***@***.***> wrote:﻿
Closed #7937 as not planned.

**Comment by Lautarob1** [comment]
Thanks!Please note that the exe file as it ends when pyinstaller finish its process works absolutely fine. The problem for which I’m looking for help just arises when the exe is resigned as part of the process of notarize it so Apple authorizes it to their systems Furthermore, the problem occurs in some apple computers and not in others, as I tried to explain in my post… Lautaro Barrera BOn Sep 13, 2023, at 3:48 PM, Rok Mandeljc ***@***.***> wrote:﻿
You should not be using onefile mode if you want to post-hoc sign the executable, as you have no way of signing the collected shared libraries (like the Python shared library).
There is a --codesign-identity command-line option for passing your $DevID to PyInstaller itself, so it can sign the collected binaries with your codesign identity instead of ad-hoc signature before it writes them to the executable-embedded archive. But whether it will work or not really depends on binaries being correctly classified as binaries during collection.

**Comment by rokm** [comment]
You cannot notarize a `onefile` build - because you cannot post-hoc sign/notarize the contents in the executable-embedded archive.

**Comment by Lautarob1** [comment]
Thanks for taking the time to reply, and for doing it promptly. I really appreciate your effort to help me on this matter. 

Sorry, perhaps I'm not understanding this correctly. I can notarize (and being approved and accepted by Apple) when I managed to change the sign in the one-file using (properly) the codesign command in the mac console (as described above).

So, the onefile get notarized (an marked as "approved"  in Apple systems), but the problem is that its execution halted with the error message described above (NOT always, but frequently, particularly on M1/M2 but also in certain cases in Intel).  

However, when I run the "native" onefile (I meant, the originally thrown by pyinstaller) it runs with no problem whatsoever. So, seems to be that the change of signature on the onefile is the culprit of these problems. Now, Apple doesn't like this original file, then the dilemma I'm facing. 

Thanks Again!

**Comment by rokm** [comment]
If you codesign an executable with your codesign identity (as opposed to ad-hoc signing, which PyInstaller does by default), then all shared libraries loaded by that executable also need to be also codesigned (with that identity). Otherwise, unsigned (or ad-hoc signed) libraries fail to load. That is why `onefile` executable stops working after you sign/notarize it. 

And because in `onefile` mode the shared libraries are collected into PyInstaller's executable-embedded archive, you cannot access them and you cannot codesign them post-hoc (i.e., in post-processing), like you did the executable itself.

So onefile builds are inherently incompatible with codesigning (unless you can work around it with previously-mentioned `--codesign-identity` argument to PyInstaller). Use a regular `onedir` build, or `onedir` .app bundle if you require signing/notarization.

**Comment by Lautarob1** [comment]
Understood!

 

You have been very helpful. Thanks a Lot!!
