### ISSUE TITLE
Make it possible to put files outside of contents_diretory

### ISSUE THREAD

**Issue by ladyeklipse** [pyinstaller/pyinstaller#7951]
I've been bundling my software with pyInstaller for ages. But version 6.0.0 breaks my software in an unexpected way. 
When I test the script from sources, it seeks for some files in the same folder the script itself resides - e. g. pictures in "assets" folder.
For new pyInstaller to work, I'll have to put all assets into _internal folder, but I don't want to change my code to comply with this change.
Can I just have an option to have "datas" variable in a ".spec" file accept a path outside of contents_directory, like this?
`datas = (('assets', '../assets'),)`

Thank you.

**Comment by rokm** [comment]
PyInstaller collects files (e.g. the ones given via `datas`) into *top-level application directory*. In onedir builds, this used to be the directory with executable, and as of v6, this has been changed to the sub-directory (called `_internal` by default). In onefile builds, this is (and always was) the temporary directory where contents are extracted. The top-level application directory is also pointed to by `sys._MEIPASS` and modules' `__file__` attribute. 

> For new pyInstaller to work, I'll have to put all assets into _internal folder, but I don't want to change my code to comply with this change.

So if your resources are collected via `datas`, they are now automatically collected into sub-directory. And if your program is referring to them via `sys._MEIPASS` or modules' `__file__` attribute, it should make no difference. The cases when it now breaks is if you anchored your paths to `sys.executable` instead, or if you refer to your resources using relative paths, which makes them dependent on your current working directory (and also breaks in other scenarios, such as executable being called from an arbitrary location on the filesystem).

> Can I just have an option to have "datas" variable in a ".spec" file accept a path outside of contents_directory, like this?
`datas = (('assets', '../assets'),)`

No, because collecting outside of the top-level application directory makes no sense in any other PyInstaller build mode (onefile, macOS .app bundles).

If you really want files next to the executable (i.e., outside of the new top-level application directory of onedir mode) for whatever reason, you can copy them there yourself (either programmatically at the end of the spec, or as a post-processing step after calling pyinstaller).

**Comment by bwoodsend** [comment]
If moving your data files breaks your code, then your code is referencing them wrong. [Our docs](https://pyinstaller.org/en/stable/runtime-information.html#using-file) are very explicit on how data files should be referenced.

**Comment by Shazoo** [comment]
Hello, using `sys.MEIPASS` and `__file__` to access data files in relative directories is indeed a reliable solution. 

However, for older projects that haven't utilized these techniques, engineers would have to modify the code and explain the reasons for the changes to others. 

PyInstaller is a very convenient and compatible tool. It would be great if the new version could consider compatibility with old code while cleaning up the cluttered working directory. This way, engineers wouldn't have to modify already audited old code. 

Thank you.



> PyInstaller collects files (e.g. the ones given via `datas`) into _top-level application directory_. In onedir builds, this used to be the directory with executable, and as of v6, this has been changed to the sub-directory (called `_internal` by default). In onefile builds, this is (and always was) the temporary directory where contents are extracted. The top-level application directory is also pointed to by `sys._MEIPASS` and modules' `__file__` attribute.
> 
> > For new pyInstaller to work, I'll have to put all assets into _internal folder, but I don't want to change my code to comply with this change.
> 
> So if your resources are collected via `datas`, they are now automatically collected into sub-directory. And if your program is referring to them via `sys._MEIPASS` or modules' `__file__` attribute, it should make no difference. The cases when it now breaks is if you anchored your paths to `sys.executable` instead, or if you refer to your resources using relative paths, which makes them dependent on your current working directory (and also breaks in other scenarios, such as executable being called from an arbitrary location on the filesystem).
> 
> > Can I just have an option to have "datas" variable in a ".spec" file accept a path outside of contents_directory, like this?
> > `datas = (('assets', '../assets'),)`
> 
> No, because collecting outside of the top-level application directory makes no sense in any other PyInstaller build mode (onefile, macOS .app bundles).
> 
> If you really want files next to the executable (i.e., outside of the new top-level application directory of onedir mode) for whatever reason, you can copy them there yourself (either programmatically at the end of the spec, or as a post-processing step after calling pyinstaller).

**Comment by Safihre** [comment]
I can second that.
In our case there are other parts of the process that rely on the file structure as it was, like the installer (icons, scripts, manuals). Those are now in different places and are not affected by the Python variables.
I can change that of course, but the impact is quite big. I don't fully understand why for example setting data directory to be the exe directory is explicitly blocked.

**Comment by rokm** [comment]
> Hello, using `sys.MEIPASS` and `__file__` to access data files in relative directories is indeed a reliable solution.
> 
> However, for older projects that haven't utilized these techniques, engineers would have to modify the code and explain the reasons for the changes to others.

From my perspective, having your application reference resources using relative paths is a bug in your code, as it makes your program depend on the current working directory - and that applies to your unfrozen code as well, not just to PyInstaller-frozen application.

> In our case there are other parts of the process that rely on the file structure as it was, like the installer (icons, scripts, manuals). Those are now in different places and are not affected by the Python variables.

Then these files are not really a part of PyInstaller-frozen application bundle, but rather part of some higher-level application bundle. And as such, they should be managed there. (And while this distinction is new for onedir builds, it was always there for onefile ones).

> I can change that of course, but the impact is quite big. I don't fully understand why for example setting data directory to be the exe directory is explicitly blocked.

If you mean why you cannot get the old structure where the top-level application directory (`sys._MEIPASS`) is the executable's parent directory, then that is a valid complaint. (But if you are referring to the lack of ability to set the target for `datas` outside of the `sys._MEIPASS`, then that is blocked due to security implications).

I am considering allowing `contents_directory` to be set to an empty string (and/or `None`), which would result in the old  "cluttered" onedir structure from v5 and earlier, so that users can decide which structure to go with.

Initially, we did not go for that because testing is concern, but I think if `sys._MEIPASS` directory is fully relocatable (i.e., it does not matter what the name of contents directory is), there should be no issues with it being the same as the executable's parent directory, either (except for the possible clash between a collected file and executable name on non-Windows).

**Comment by Shazoo** [comment]
@rokm Thanks for your reply . 

I don't intend to argue whether putting data files in the working directory is a bug in the program (in fact, it can be considered a portable solution, regardless of whether it aligns with our aesthetic taste).

My point is, as PyInstaller is a very successful open-source tool, could it consider being compatible with old code (regardless of whether it is perfect)?

Here's my personal feeling: Handling sys._MEIPASS in business code itself increases the coupling of the program. Business engineers may question why they have to deal with the complexity of checking a PyInstaller internal parameter when retrieving files.

maybe  `--add-data=/path/to/file:@/file`  ? `@` means executable's directory .

**Comment by Safihre** [comment]
I actually would propose to allow data_directory to ".". (Edit: indeed not"..")

**Comment by bwoodsend** [comment]
> I am considering allowing contents_directory to be set to an empty string (and/or None), which would result in the old "cluttered" onedir structure from v5 and earlier, so that users can decide which structure to go with.

I'm still opposed to this. The number of conditionals required to keep the `MERGE()` related code in the bootloader will be horrific. Maybe if `MERGE()` was dropped and macOS app bundles were redesigned to be assembled directly rather than through an intermediate one dir bundle then it would be more achievable but, messy though `MERGE()` is, I think it's still more valuable than the ability to skip that `_internal` directory.

> Here's my personal feeling: Handling sys._MEIPASS in business code itself increases the coupling of the program. Business engineers may question why they have to deal with the complexity of checking a PyInstaller internal parameter when retrieving files.

If you use `__file__` instead of `sys._MEIPASS` and choose the right `dest` value for your `--add-data` flags correctly, then there should be no PyInstaller specific code required. (And I know our docs do seem to promote using `sys._MEIPASS` – they shouldn't do.)

> My point is, as PyInstaller is a very successful open-source tool, could it consider being compatible with old code (regardless of whether it is perfect)?

It may be a popular tool but that doesn't change the fact that it only has 3 maintainers (where only one of them actually has any time to do more than issue triage). We have to pick our battles. Compatibility code is expensive and if it's main purpose it supporting broken code then that is definitely not a good choice in my book.

**Comment by rokm** [comment]
> > I am considering allowing contents_directory to be set to an empty string (and/or None), which would result in the old "cluttered" onedir structure from v5 and earlier, so that users can decide which structure to go with.
> 
> I'm still opposed to this. The number of conditionals required to keep the `MERGE()` related code in the bootloader will be horrific. Maybe if `MERGE()` was dropped and macOS app bundles were redesigned to be assembled directly rather than through an intermediate one dir bundle then it would be more achievable but, messy though `MERGE()` is, I think it's still more valuable than the ability to skip that `_internal` directory.

As far as `MERGE` is concerned, it is two path checks that would need to be expanded to handle case where`contents_directory` is set and case where it is not:
https://github.com/pyinstaller/pyinstaller/blob/e70c723d8166c0c28f19bc3f0f3da3c814cc061c/bootloader/src/pyi_launch.c#L214
and
https://github.com/pyinstaller/pyinstaller/blob/e70c723d8166c0c28f19bc3f0f3da3c814cc061c/bootloader/src/pyi_launch.c#L223

(That code needs a closer scrutiny anyway, because both conditions look the same to me...)

With a bit of refactoring, it wouldn't even look that bad (e.g., if the if/else if/else block was split into separate if blocks, with additional if blocks before for path formatting cases). Not exactly pretty, but given the overall MERGE code, not that (much more) awful, either.

EDIT: there's actually one more use of `contents_directory` below, but that shouldn't change things much.

(And while we could go with `.` like Safihre suggested, I would prefer clean paths, just to be sure we won't be running into issues with naive string comparison and path normalization in some dark corner of PyInstaller. I think '.' is actually a good choice for the command-line, as long as we map it onto `contents_directory` bootloader-option not being set later on).

---

macOS app bundles are not affected by `contents_directory` in any way. `BUNDLE` only takes the `toc` and couple of settings from `COLLECT`, so I don't think it would require a `COLLECT` to be actually built. So we could (and probably should) introduce a separate .spec template for `--windowed` on macOS where there is no intermediate `COLLECT`. The only real benefit of the current `COLLECT` + `BUNDLE` combo is that our CI tests both regular POSIX build and the .app bundle wherever we use `--windowed` argument.

**Comment by rokm** [comment]
Ah, did you mention macOS .app bundles because of #7314 (which can now be triggered only by intermediate `COLLECT`)? 

I don't think that should be a problem. In existing codebases, users had to take care of this anyway (by renaming the offending package, or by renaming the executable). If we allow `contents_directory` to be disabled to obtain old onedir layout, then this issue could be reintroduced only if the user explicitly went for that option - but there is actually no reason to do so if the end-goal is an .app bundle.

**Comment by bwoodsend** [comment]
No I mentioned .app bundles because I remembered the intermediate application required required some non intuitive conditionals because it was a windowed bootloader but still a regular onedir application. What should have been a simple `#ifdef __APPLE__ && __windowed__` became [this](https://github.com/pyinstaller/pyinstaller/pull/7713/files#diff-561760bb3d25daf14532b38e778c3a396e675750b59c8a12e5d0119ffa7e435cR527-R549) rather finicky piece of code.

**Comment by Safihre** [comment]
Thank you for considering this and taking the time to explain the complexity! 🥇

**Comment by Shazoo** [comment]
Thanks .

**Comment by rokm** [comment]
As of next release, you will be able to get the old onedir layout by setting the `contents_directory` to `.`.

**Comment by ErtugrulKusva** [comment]
@rokm Is it certain that the next one we will have this feature? How do you know
