### ISSUE TITLE
PyInstaller-compiled .exe crashes possibly due to sklearn imports

### ISSUE THREAD

**Issue by ItelixHub** [pyinstaller/pyinstaller#8000]
i am trying to make a .exe with pyinstaller (6.0.0)
I made a test.py that has nothing but a clickable exit-button.
the .exe runs just fine as long as i exclude the sklearn-imports which are the following:

```
    from sklearnex import patch_sklearn
    patch_sklearn()
    from sklearn.neighbors import KDTree
    from sklearn.cluster import MeanShift
```

Unfortunately they are crutial for the target-script that needs to be compiled

i made a hook-file:
`hiddenimports = ['sklearn']`
_taken by another post_

i still get warnings while compiling:
```
837915 WARNING: Library not found: could not resolve 'ze_loader.dll', dependency of 'C:\\Users\\Student\\anaconda3\\envs\\occ\\Library\\bin\\omptarget.rtl.level0.dll'.
837916 WARNING: Library not found: could not resolve 'libfabric.dll', dependency of 'C:\\Users\\Student\\anaconda3\\envs\\occ\\Library\\bin\\impi.dll'.
```

the script in my anaconda environment runs just finde, but not as an .exe
Its python 3.10.5

Output from exe:

[ExeBuildLogText.txt](https://github.com/pyinstaller/pyinstaller/files/12879053/ExeBuildLogText.txt)

Please let me know if i need to provide more information.
i'm pretty new in developments

**Comment by rokm** [comment]
The `sklearnx` and its depedencies are calling `os.add_dll_directory()` without checking if the directory actually exists. Specifically, the following two directories are assumed to be existing:
- `Library\bin`: which does not exist because PyInstaller uses top-level application directory for its DLL directory
- `daal4py\oneapi`: contains only an `__init__.py` (in Anaconda package; the PyPI wheel has a DLL in this directory, which is why `add_dll_directory` is called), which is collected into PYZ, and we do not collect/recreate empty directories

As a work-around, you could create an empty file, and add it as a data file: `--add-data "empty;Library\bin" --add-data "empty;daal4py\oneapi"`.

But I suppose it might be easier to just monkey patch `add_dll_directory` to silently ignore `FileNotFoundError` when running in frozen application:

```python
def _patch_add_dll_directory():
    import os
    import sys
    if getattr(sys, 'frozen', False):
        _orig_add_dll_directory = os.add_dll_directory
        def _add_dll_directory(*args, **kwargs):
            try:
                _orig_add_dll_directory(*args, **kwargs)
            except FileNotFoundError:
                pass
        os.add_dll_directory = _add_dll_directory

_patch_add_dll_directory()
del _patch_add_dll_directory

from sklearnex import patch_sklearn
patch_sklearn()
from sklearn.neighbors import KDTree
from sklearn.cluster import MeanShift
```

I suppose we could also monkey-patch `add_dll_directory` in our bootstrap scripts, but so far there have not been that many errors related to non-existent directories that would really warrant it. Plus, having that error raised makes it easier to debug cases when the directory should actually exists (i.e., we fail to collect libraries from it).

**Comment by ItelixHub** [comment]
> The `sklearnx` and its depedencies are calling `os.add_dll_directory()` without checking if the directory actually exists. Specifically, the following two directories are assumed to be existing:
> 
> * `Library\bin`: which does not exist because PyInstaller uses top-level application directory for its DLL directory
> * `daal4py\oneapi`: contains only an `__init__.py` (in Anaconda package; the PyPI wheel has a DLL in this directory, which is why `add_dll_directory` is called), which is collected into PYZ, and we do not collect/recreate empty directories
> 
> As a work-around, you could create an empty file, and add it as a data file: `--add-data "empty;Library\bin" --add-data "empty;daal4py\oneapi"`.
> 
> But I suppose it might be easier to just monkey patch `add_dll_directory` to silently ignore `FileNotFoundError` when running in frozen application:
> 
> ```python
> def _patch_add_dll_directory():
>     import os
>     import sys
>     if getattr(sys, 'frozen', False):
>         _orig_add_dll_directory = os.add_dll_directory
>         def _add_dll_directory(*args, **kwargs):
>             try:
>                 _orig_add_dll_directory(*args, **kwargs)
>             except FileNotFoundError:
>                 pass
>         os.add_dll_directory = _add_dll_directory
> 
> _patch_add_dll_directory()
> del _patch_add_dll_directory
> 
> from sklearnex import patch_sklearn
> patch_sklearn()
> from sklearn.neighbors import KDTree
> from sklearn.cluster import MeanShift
> ```
> 
> I suppose we could also monkey-patch `add_dll_directory` in our bootstrap scripts, but so far there have not been that many errors related to non-existent directories that would really warrant it. Plus, having that error raised makes it easier to debug cases when the directory should actually exists (i.e., we fail to collect libraries from it).

i tried the empty file first and it worked like a charm (for the test.py)
my targe script has gmsh in it, did i miss a point last discussion about handling that?

the script lets me choose a .stp-file (3D-Model-File), then:
Traceback (most recent call last):
```
 File "tree_11b.py", line 777, in <module> 
 File "trimesh\interfaces\gmsh.py", line 37, in load_gmsh 
 File "<frozen importlib._booloptrap>", line 1027, in _find_and_load 
 File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked 
 File "<frozen importlib._bootstrap>", line 688, in _load_unlocked 
 File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module 
 File "gmsh.py", line 83, in <module> 
 File "genericpath.py", line 19, in exists 
 TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType 
 [14968] Failed to execute script 'tree_11b' due to unhandled exception! 
```



you're a big help here, thanks so much

**Comment by rokm** [comment]
> my targe script has gmsh in it, did i miss a point last discussion about handling that?

In addition to PyInstaller `develop` due to https://github.com/pyinstaller/pyinstaller/issues/7982, you also need a hook for `gmsh` that collects the `gmsh` DLL. This was added to contrib hooks repository in https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/650, but was not released yet. So you need a 
```
pip uninstall pyinstaller-hooks-contrib
pip install git+https://github.com/pyinstaller/pyinstaller-hooks-contrib.git@master
```

**Comment by ItelixHub** [comment]
> ```
> pip uninstall pyinstaller-hooks-contrib
> pip install git+https://github.com/pyinstaller/pyinstaller-hooks-contrib.git@master
> ```

that did the job. i'm more than happy now. thanks!
