### ISSUE TITLE
macOS: dyld missing symbol called

### ISSUE THREAD

**Issue by danyeaw** [pyinstaller/pyinstaller#8048]
## Description of the issue

With PyInstaller 6.1, when trying to test a packaged app is working in macOS, I'm getting a dyld missing symbol called error when executing the app on CI. I wasn't able to reproduce this error locally and it works fine with PyInstaller 5.x. I am sort of out of ideas, so looking for some tips on troubleshooting.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.1.0```
* Version of Python: 3.11.5
* Platform: macOS
* How you installed Python: GitHub Action runner
* Did you also try this on another platform? Does it work there? Yes, works on Windows

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Since I'm only seeing this error on CI, I could try to create a small new hello world GTK app and see if I get the same error.

### Stacktrace / full error message

```
Run hdiutil attach Gaphor-2.21.0.dev4045+6570469f.dmg
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $9A8C5198
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $5F0B3CC9
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $C1F89CA2
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
          disk image (Apple_HFS : 4): verified   CRC32 $285B035F
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $C1F89CA2
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified   CRC32 $516A2946
verified   CRC32 $92B4E860
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	Apple_HFS                      	/Volumes/Gaphor 2.21.0.dev4045+6570469f
dyld[945]: missing symbol called
/Users/runner/work/_temp/df3f2f86-07e2-4a72-ab98-aea23ebe94b5.sh: line 4:   945 Abort trap: 6           Gaphor.app/Contents/MacOS/gaphor --self-test
dyld[1196]: missing symbol called
/Users/runner/work/_temp/df3f2f86-07e2-4a72-ab98-aea23ebe94b5.sh: line 4:  1196 Abort trap: 6           Gaphor.app/Contents/MacOS/gaphor --self-test
```

**Comment by rokm** [comment]
If it works with 5.x but not with 6.x in the same environment, then I suppose the best way to debug it would be to generate an artifact out of complete `build` and `dist` directories, so we can see what is being collected and from where (and what is the difference between the old and new PyInstaller version).

**Comment by danyeaw** [comment]
I finally am able to reproduce the issue locally with Python 3.11.6, with Python 3.12.0 everything works fine:

```
** (process:61902): WARNING **: 21:16:53.599: Failed to load shared library '@loader_path/libgtk-4.1.dylib' referenced by the typelib: dlopen(@loader_path/libgtk-4.1.dylib, 0x0009): Symbol not found: _hb_glib_script_to_script
  Referenced from: <8048A818-9BB9-3412-9E66-AD43A09C7E77> /Users/dyeaw/Projects/gaphor/_packaging/dist/Gaphor.app/Contents/Frameworks/libgtk-4.1.dylib
  Expected in:     <393C7EC4-78D8-3922-8AF3-6D3A7B84EE4F> /Users/dyeaw/Projects/gaphor/_packaging/dist/Gaphor.app/Contents/Frameworks/PIL/__dot__dylibs/libharfbuzz.0.dylib
```

**Comment by rokm** [comment]
This looks like a mixture of Homebrew-installed Gtk, which depends on a certain version of `libharfbuzz.0.dylib`. But the same dylib is also provided by the pip-installed `Pillow`, and that copy has different ABI than the Homebrew one.

In 5.x, both copies were set to be collected to _MEIPASS; but since only one can exist, the end result was dependent on the order of collection (so if things worked for you, I guess that means that Homebrew copy was collected). In 6.x, we preserve the parent directory of dylibs collected from wheel-installed packages, but we still need to symlink to _MEIPASS because that is the root of our `@rpath` paths. Since symlinks take precedence over regular copies, you now always end up symlink to `pillow` copy of the library.

I'm not sure why would work with python 3.12 when it does not with 3.11, though - can you check where the `Gaphor.app/Contents/Frameworks/libharfbuzz.0.dylib` symbolic link points in 3.11 and in 3.12 build?

**Comment by danyeaw** [comment]
Hi @rokm, it looks like you are on the right track for the differences.

Python 3.11.6 (doesn't work):
```
ls -l _packaging/dist/Gaphor.app/Contents/Frameworks/libharfbuzz.0.dylib 
lrwxr-xr-x@ 1 dyeaw  staff  31 Oct 28 22:12 _packaging/dist/Gaphor.app/Contents/Frameworks/libharfbuzz.0.dylib@ -> PIL/.dylibs/libharfbuzz.0.dylib
```

Python 3.12.0 (works):
```
ls -l _packaging/dist/Gaphor.app/Contents/Frameworks/libharfbuzz.0.dylib 
-rwxr-xr-x@ 1 dyeaw  staff  1186672 Oct 29 09:40 _packaging/dist/Gaphor.app/Contents/Frameworks/libharfbuzz.0.dylib*
```

I tried to `brew install pillow`, but that didn't seem to make a difference.

**Comment by rokm** [comment]
Are there other differences in .app bundle contents as well? If `libharfbuzz.0.dylib` with python 3.12 is not a symbolic link, then it is likely that `PIL/.dylibs/libharfbuzz.0.dylib` was not picked up during binary dependency analysis for some reason (since this is the part that preserves the parent directory and creates symlink to _MEIPASS).

> I tried to brew install `pillow`, but that didn't seem to make a difference.

If you are not building with Homebrew python, then installing `pillow` in homebrew is unlikely to make a difference.

**Comment by fluffy-critter** [comment]
I've been running into a similar issue, where the culprit is that something in Python and/or pyInstaller is grabbing .dylib linkages from /opt/homebrew even though I'm using the universal2 build of Python from python.org and a poetry environment that only pulls in dependencies through that. If I remove /opt/homebrew/* from my PATH, pyInstaller stops picking up the homebrew dependencies.

Presumably it's because some binary in /opt/homebrew is throwing off some configuration tool that a thing is running under the hood, and those same tools don't exist in the poetry environment for some reason. But that's just an off-the-cuff guess as I haven't done a thorough dive on this.

For now in my build script I just have it remove all homebrew directories from my PATH (using a fragile sed expression), although that's had the unfortunate side effect of breaking my Windows build due to the usual fragility of trying to make cross-platform Makefiles.

**Comment by rokm** [comment]
@danyeaw While solving library conflicts like that is generally beyond what PyInstaller can reasonably support (and there's always 50% chance wrong lib will be "promoted"), this particular issue can be avoided altogether.

`libharfbuzz.0.dylib` and `libfreetype.6.dylib` from `pillow` are referenced only by `PIL._imagingft` extension (and are collected as result of binary analysis on this extension). This extension, in turn, is referenced by `PIL.ImageFont`, which in `gaphor`'s case ends up being referenced by the following import chain: `PIL.ImageFont` ← `pygments.formatters.img`← `pygments` ← `docutils.utils` ← `setuptools._distutils.command.check`. So preventing collection of `docutils` (either globally, by adding it to `excludes` in spec, or locally via hooks; see #8053) should prevent `pillow` copies of those two dylibs from being collected.

**Comment by danyeaw** [comment]
Wow! Thanks @rokm for the analysis, you rock. I will give that a try!

**Comment by danyeaw** [comment]
@rokm, this did fix the issue! Thanks so much again. ❤️
