### ISSUE TITLE
Issue with library inside _internal on Ubuntu

### ISSUE THREAD

**Issue by aptly-io** [pyinstaller/pyinstaller#8084]
A CLI tool based on python uses the click module (for processing the command line options and arguments). The click module provides a `click.echo_with_pager()`. It is used to output some json text. This pager-feature seems to fall back on piping to `less`. 

The CLI installer package is build on docker (public.ecr.aws/sam/build-python3.11).
The latest pyinstaller is used (6.1.0).
The command line looks like this: `pyinstaller -D tools/cli/src/cli.py`

When the `echo_with_pager` is used, there's this error shown:
```
$ ~/tmp/cli$ ./cli  effects list
less: /home/john/tmp/cli/_internal/libtinfo.so.6: no version information available (required by less)
WARNING: terminal is not fully functional
Press RETURN to continue 
```
Indeed the pager is not fully functional.

- I tried to copy my local `/usr/lib/i386-linux-gnu/libtinfo.so.6` from my host into `cli/_internal/libtinfo.so.6`.
- I tried to delete `cli/_internal/libtinfo.so.6`

In both cases the CLI tools works fine! 

Is there a way to build a package without the incompatible `libtinfo.so.6` inside `_internal`?

Thank you!

**Comment by rokm** [comment]
> Is there a way to build a package without the incompatible `libtinfo.so.6` inside `_internal`?

No direct way. If you were building using the .spec file, you could filter it out of `Analysis.binaries` TOC list before `EXE` and `COLLECT` are instantiated. Otherwise, you need to manually remove the file from the `_internal` directory after the application is built.

The library name could also be added to [`PyInstaller.depend.dylib.unix_excludes`](https://github.com/pyinstaller/pyinstaller/blob/04db9fdaeab2bb321a6ffd00eb5949ed7aea07ae/PyInstaller/depend/dylib.py#L187), although I'm not sure if we want to do that for general cases (depending on usual availability of ncurses and stability of its ABI)...

---

In general, though, if your frozen application is trying to run host-system-provided program(s) and those fail due to incompatible shared libraries bundled with the frozen application, you can reset `LD_LIBRARY_PATH` to its original value at the start of your program, as suggested in [the docs](https://pyinstaller.org/en/stable/runtime-information.html#ld-library-path-libpath-considerations). (This should not cause issues with the frozen application itself, as `LD_LIBRARY_PATH` has no effect after the process is already running; but it might cause issues with executables that are bundled with the frozen application (if any) - as those depend on the versions of libraries that are bundled  with the frozen application).

**Comment by aptly-io** [comment]
Thank you, I decided to manually remove the library before the package is archived as that seems to work on tested platform!
