### ISSUE TITLE
`--contents-director=.` will make QtChart import failed

### ISSUE THREAD

**Issue by adadaadadade** [pyinstaller/pyinstaller#8087]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.1.0```
* Version of Python: ```3.11.6```
* Platform: ```Windows10```
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there? not yet

### A minimal example program which shows the error

versions:
PyQt5==5.15.9
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
PyQtChart==5.15.6
PyQtChart-Qt5==5.15.2
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2

hello.py
``` python
import sys
import PyQt5.QtChart
import PyQt5.QtWebEngine
from PyQt5.QtWidgets import QApplication, QWidget

if __name__ == "__main__":
    app = 0
    app = QApplication(sys.argv)
    w = QWidget()
    w.resize(250, 250)
    w.move(300, 300)
    w.setWindowTitle('Simple')
    w.show()
    sys.exit(app.exec_())
```

try to pack the program and run it
``` shell
pyinstaller -c -y -w --noupx --contents-director=. hello.py
./dist/hello/hello
```

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "hello.py", line 2, in <module>
ImportError: DLL load failed while importing QtChart: The specified module could not be found.
```

pack with `-d=all`
```
Traceback (most recent call last):
  File "hello.py", line 2, in <module>
    import PyQt5.QtChart
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing QtChart: The specified module could not be found.

```

**Comment by rokm** [comment]
I cannot reproduce this - both default contents directory and `.` work if I freeze that example.

Can you archive the `build` and `dist` directories of that failing build and upload them somewhere so I can take a look at them? (The build *without*  `-d=all`).

**Comment by adadaadadade** [comment]
```shell
pyinstaller -c -y -w --noupx --contents-director=. hello.py
```
The archive file is too big to upload to github issue.

https://drive.google.com/file/d/13wGBjzaRemqzjnNCDonvm9dU2qVbMl64/view?usp=sharing

**Comment by rokm** [comment]
The underlying problem here seems to be that you have another Qt5 installation in your search paths (`PATH`), and that messes up the DLL resolution during the build. So you end up with two copies of those DLLs; one in `PyQt5\Qt5\bin` (from PyQt5 package, which is OK), and in top-level application directory (from external Qt5 installation, which should not be there).

I.e., if you look at `build\hello\Analysis-00.toc`, you will see entries like these:
``` 
  ('PyQt5\\Qt5\\bin\\Qt5Core.dll',
   'D:\\repo\\qt-pyinstaller-test\\venv\\Lib\\site-packages\\PyQt5\\Qt5\\bin\\Qt5Core.dll',
   'BINARY'),
```

```
  ('Qt5Core.dll', 'C:\\QT\\5.15.2\\msvc2015_64\\bin\\Qt5Core.dll', 'BINARY'),
```

If you remove the `Qt5*.dll` files in top-level application directory, the application starts normally.

Cleaning up `PATH` before running PyInstaller (i.e., removing `C:\QT\5.15.2\msvc2015_64\bin` from `PATH`) should also avoid this issue.

---

But now I'm curious as to why we are not preferring PyQt5-provided DLLs in the first place.

1. Can you try re-running pyinstaller with added `--clean --log-level=DEBUG`, and attach or upload the full build log
so we can see where DLLs from `C:\QT\5.15.2\msvc2015_64\bin` are referenced?

2. If you run the following script in your python environment, what is the output?

```python
# display_qt_paths.py
import pprint
from PyQt5.QtCore import QCoreApplication, QLibraryInfo

path_names = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
locations = {x: QLibraryInfo.location(getattr(QLibraryInfo, x)) for x in path_names}
pprint.pprint(locations)
```

Does any of the paths point to `C:\QT\5.15.2\msvc2015_64\bin`?

**Comment by rokm** [comment]
Actually, nevermind, I've reproduced the issue by placing a custom Qt5 installation in `PATH`, so I can investigate what is going on.

**Comment by rokm** [comment]
Looks like the problem is not that we prefer external Qt libraries, but that we fall back to them due to PyQt5 shipping QML plugins with missing dependencies (and an external Qt installation being (in)conveniently in `PATH˙)..

These are the warnings when building without external Qt5 in `PATH`:

```
19135 WARNING: Library not found: could not resolve 'Qt53DLogic.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtQuick\\Scene3D\\qtquickscene3dplugin.dll'.
19135 WARNING: Library not found: could not resolve 'Qt53DAnimation.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtQuick\\Scene3D\\qtquickscene3dplugin.dll'.
19148 WARNING: Library not found: could not resolve 'Qt53DCore.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtQuick\\Scene3D\\qtquickscene3dplugin.dll'.
19148 WARNING: Library not found: could not resolve 'Qt53DInput.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtQuick\\Scene3D\\qtquickscene3dplugin.dll'.
19148 WARNING: Library not found: could not resolve 'Qt53DRender.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtQuick\\Scene3D\\qtquickscene3dplugin.dll'.
19163 WARNING: Library not found: could not resolve 'Qt53DQuickScene2D.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtQuick\\Scene2D\\qtquickscene2dplugin.dll'.
19179 WARNING: Library not found: could not resolve 'Qt53DCore.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtQuick\\Scene2D\\qtquickscene2dplugin.dll'.
19179 WARNING: Library not found: could not resolve 'Qt53DRender.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtQuick\\Scene2D\\qtquickscene2dplugin.dll'.
19179 WARNING: Library not found: could not resolve 'Qt5MultimediaQuick.dll', dependency of '[...]\\Lib\\site-packages\\PyQt5\\Qt5\\qml\\QtMultimedia\\declarative_multimedia.dll'
```

So there are two problematic plugins, `PyQt5\Qt5\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll` and `PyQt5\Qt5\qml\QtMultimedia\declarative_multimedia.dll`.

The Qt53D DLLs can be installed as part of `PyQt3D` (and `PyQt3D-Qt5`), but `Qt5MultimediaQuick.dll` seems to be completely missing from PyQt5 PyPI wheels.

Normally, the plugins with missing dependencies do not cause any issues except for that warning during binary dependency analysis (and the fact that non-functional plugin is collected). But when you have a full Qt5 installation in `PATH`, the missing DLL is found there, and collected from there, along with its dependencies. And because the other location is not part of a PyPI wheel, binary dependency analysis collects them into top-level directory. So you end up with two conflicting sets of Qt DLLs, and then it likely boils down to whether they are next to the executable (--content-directory=.) or in a sub-directory (--content-directory=_internal) how PyQt5 (and/or Qt itself) initializes its search paths.

So as stated before, the immediate work-around for this is not to have that second Qt installation in `PATH` when using PyInstaller.

But I suppose we could perform initial binary dependency analysis for plugins (both regular and QML) and automatically exclude the ones that are missing Qt dependencies and the ones whose Qt dependencies are resolved outside of the expected DLL directory (in case of PyPI wheels). I suspect similar problem would occur with PyQt5 PyPI wheels on macOS with Qt5 also installed in Homebrew... And as a bonus, early elimination of problematic plugins should also eliminate subsequent warnings during binary dependency analysis.

**Comment by adadaadadade** [comment]
Thank you so much, I removed the second Qt installation from `PATH`.  And it actually worked.
