### ISSUE TITLE
Generate Software Bill of Material (SBOM) when building an application - Cyber Resilience Act

### ISSUE THREAD

**Issue by Joerki** [pyinstaller/pyinstaller#8088]
**Is your feature request related to a problem? Please describe.**
(Upcoming) legal requirements (Cyber Resilience Act) for commercial solutions require the creation of an SBOM that contain all components that are included in an application (e.g. SPDX or CycloneDX SBOMs). No matter if the output is a single file or directory with files, SBOM scanners cannot determine which exact components the generated distribution contains.

Those SBOMs can also be used to scan for security vulnerabilities in an application.

**Describe the solution you'd like**
Pyinstaller should write a package/file list that identifies all components that are included in the generated application.
For me, it would be nice, but not a requirement to write an SPDX/CycloneDX SBOM, but at least a file that allows conversion to an SPDX/CycloneDX SBOM including packages with package type (Python etc.), version numbers and their dependencies.

**Describe alternatives you've considered**
I considered to scan source trees and distribution directories separately and merge information, but I doubt that the result can be the truth.

**Additional context**
See 
https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema-sortiert/tr03183/TR-03183_node.html
https://cyclonedx.org, 
https://en.wikipedia.org/wiki/Cyber_Resilience_Act

**Comment by rokm** [comment]
To me, this feels like a waste of effort on our part.

If you have a well-defined build environment, then you should know what you were building with; both in terms of python packages and external libraries.

And if you require SBOM due to CRA or similar, then you'll have to do your due diligence anyway, to make sure that whatever PyInstaller would spit out is not full of lies. Lies for which, by the way, *someone* will held liable. And all the more reason why I think we should not be doing it for you. Even putting the liability issues aside, I have absolutely no interest in dealing with additional volume of issue reports stemming from this feature.

From technical perspective, all files that are going to be collected by PyInstaller could indeed be read from `Analysis` object and its various TOC lists. Or even from the serialized form in `build/<name>/Analysis-00.toc`, if this were an external tool. And that's the simple part - the difficult part is figuring out where the files actually came from: PyPI wheel, Anaconda package, mys2 package, Homebrew package, linux distribution's package manager (yum/dnf, apt, pacman, ...), chocolatey, some manually built software package that you manually put into your build environment's search path, and so on.

And I'd say that lookups of such complexity have no place in the core part of the PyInstaller. But nothing prevents you (or the interested commercial sofware vendors affected by the CRA) from developing an external tool that does this.

**Comment by bwoodsend** [comment]
I think the only part that PyInstaller could manage with any degree of certainty would be the Python libraries which, in a clean environment, can be obtained with a mere `pip freeze`.

**Comment by Joerki** [comment]
Thanks for the first responses.
My assumption is that there might be a gap between what was installed originally in a venv and what is finally part of a distributed  application. The distributed application might contain less that the original environment, this is what is relevant. Especially if anybody does not deal just with vulnerabilities, but also Open Source compliance.

Application creation and evaluation are duties of different people, I heard this also from other companies, which does not make this task easier.

As Brénainn mentioned, a list with Python packages (like `pip freeze`'s outcome would give a useful input for the whole puzzle to achieve an SBOM that tells the truth about the distributed application.

**Comment by rokm** [comment]
> My assumption is that there might be a gap between what was installed originally in a venv and what is finally part of a distributed application. The distributed application might contain less that the original environment, this is what is relevant. Especially if anybody does not deal just with vulnerabilities, but also Open Source compliance.

If you have only your actual build dependencies installed in the venv, then the frozen application should contain (subset of) those installed python packages (sans PyInstaller and its dependencies). And even if we collect only part of let's say `PyQt6`, that doesn't change the fact that `PyQt6` should be included in your SBOM.

So the output of `pip freeze` in such clean environment *is* actually what you are asking for.

The thing is that on most platforms, we often collect files outside of the venv as well - typically shared libraries that are installed on the system, and it is those files that you will have to worry about.

**Comment by jkowalleck** [comment]
> So the output of `pip freeze` in such clean environment _is_ actually what you are asking for.

using https://pypi.org/project/cyclonedx-bom/ your workflow to generate the SBOM could be like: 
```sh
python -m pip freeze > requirements_frozen.txt
python -m pip install cyclonedx-bom
cyclonedx-py -r -i requirements_frozen.txt -o sbom.xml
```
(see https://github.com/CycloneDX/cyclonedx-python/discussions/487)


----

> The thing is that on most platforms, we often collect files outside of the venv as well - typically shared libraries that are installed on the system, and it is those files that you will have to worry about.

I'd assume that this part is what the original feature request is all about.

**Comment by rokm** [comment]
> > The thing is that on most platforms, we often collect files outside of the venv as well - typically shared libraries that are installed on the system, and it is those files that you will have to worry about.
> 
> I'd assume that this part is what the original feature request is all about.

Sure, because that's the hard part. But there's no reason why this should be part of PyInstaller itself rather than an external tool that's written and maintained by someone else.

I find this akin to asking `CMake` to produce you a list of packages (in whatever mix of packaging system the build host is using) where it pulled the build dependencies from. Sure, there are [3rd party modules](https://github.com/swinslow/cmake-spdx) for that, but it is not part of the core CMake.

**Comment by bwoodsend** [comment]
> > The thing is that on most platforms, we often collect files outside of the venv as well - typically shared libraries that are installed on the system, and it is those files that you will have to worry about.
>
> I'd assume that this part is what the original feature request is all about.

I don't see how this would even be possible outside of Linux/MSYS2. On those platforms, files from Python packages can be classified as such using `importlib.metadata.files()`, those from system packages can be queried via the package manager (e.g. `pacman -Fl`). That mostly just leaves any ad-hoc/from source dependencies usually installed into `/usr/local` or `/opt` and possibly the Python distribution itself if using something like `pyenv`. That's a lot of package managers to support but still at least plausible in theory.

On Windows, there's no accountability for why any files are where they are or what put them there – it's just a big semi disfunctional soup. We'd be regex-ing/lookup table-ing files into vague categories and hoping for the best...

**Comment by Joerki** [comment]
I think my problem became clearer in the discussion.
In the context of a Python-based application, it is not relevant what's in the build environment, but what is contained in the application anyone ships to others. 
I need transparent information about what Pyinstaller is collecting in a way that allows further identification in combination with other tools that create CycloneDX SBOMs. External dependencies outside the deliverable are not in scope.

The output of Pyinstaller is a handy executable, great! I get one - no matter if I produced the output with option "onefile" or not.
But this outcome is a black box. Unlike for Docker images, the SBOM scanners cannot look inside this object (file) to see what's inside (or do you know one?). Pyinstaller knows what it's putting inside, and this is the information I need. 

If Pyinstaller would offer a plug-in/hook method that allows collecting and processing this information on my own, fine. But the current purpose for hooks is different.

I don't see that I can solve my problem with external tools, because I cannot look into the executable to determine the content of the deliverable.

**Comment by bwoodsend** [comment]
> But this outcome is a black box.

Are the `build/*/*.toc` files that PyInstaller generates not enough for this?

**Comment by Joerki** [comment]
> > But this outcome is a black box.
> 
> Are the `build/*/*.toc` files that PyInstaller generates not enough for this?

For me, this is a question I'd like to have answered. 
I found no documentation, but a short discussion (#7821).
Since I did not find an explanation on those files I assume that they are internal, maybe a subject of change. So I don't know how safe it is to rely on them.

**Comment by rokm** [comment]
The .toc files are serialized fields of the TARGET structures, and technically they *are* internal, and subject to a change.

So as a safer "external" approach, you could dump TOC lists from Analysis (`a.pure`, `a.datas`, `a.binaries`) into a custom file at the end of the .spec file (assuming you are building from a spec rather than directly from py file).

**Comment by rokm** [comment]
I suppose at the end of the day, it might in fact be easier and more future-proof for Analysis itself to dump its `a.pure`, `a.datas`, and `a.binaries` TOC lists into a JSON file in build directory. This would tell you exactly where each file in the frozen application was taken from (and since this is done by Analysis, it could also account for `a.pure` being turned into `a.datas` due to `debug=noarchive` or a module collection mode setting). 

Then you could use an external utility to resolve the actual sources (packages) of these files, generate your SPDX/CycloneDX SBOM, and so on. (I suppose the "license collector" from #5666 could also be built on top of this, and we wouldn't have to deal with it ourselves).

**Comment by Joerki** [comment]
Hi @rokm 
your solution looks promising, thank you.
I start with some implementation and come back with my results.

**Comment by Joerki** [comment]
Hi @rokm 
I finally implemented an automated solution that maps the files fetched from the a object. I think it's really useful to monitor what PyInstaller puts into the executable, especially runtime DLLs on Windows. We also managed to update the spec file and create hooks to take the DLLs of 3rd party packages from the original (package) directories (instead of e.g. a Java runtime installation or Windows system directory.

Bye
