### ISSUE TITLE
Option to ship python.exe interpreter with executable.

### ISSUE THREAD

**Issue by zuckerruebe** [pyinstaller/pyinstaller#8129]
**Is your feature request related to a problem? Please describe.**
Our application is basically a bunch of Python packages that our users then call from very basic, standardized scripts (though power users might wield the full power of Python if they'd like to) - i.e. at the end of the day _they run a script, calling into our provided modules_. We're currently using `PyInstaller` basically to create something of a "relocatable venv" so that our users don't have to deal with installing Python and the required packages (ideally, the not-power-users shouldn't need to know much about Python and its eco-system at all).

However, we've seen our solution to be quite fragile, particularly with regards to (a combination of)

1. Multiprocessing
2. IPython kernels and clients
3. exec()
4. sys.executable
5. sys.argv

We use `IPython` and `exec` as the poor man's Python interpreter.

**Describe the solution you'd like**
Actually, if "relocatable venv's" existed, I think it would suit us quite nicely. But I think the next best thing would be a `PyInstaller` that allowed shipping the `python.exe` interpreter with it.

**Describe alternatives you've considered**
Rolling your own Python installation script to create a venv and download the required packages. Python would still need to have been installed already, though.

**Comment by rokm** [comment]
Sounds like PyInstaller is not the tool you are looking for. Nothing prevents you from going out of your way to (ab)use it, but that's to everyone's detriment. 

If you wanted to bring `python.exe` with your frozen application, you would need to also collect the rest of the python (stdlib modules, shared lib, any built-in extensions). And even then your frozen application (`program.exe`) and the shipped python interpreter (`python.exe`) would be essentially two different python environments. 

---

> Rolling your own Python installation script to create a venv and download the required packages. Python would still need to have been installed already, though.

Assuming this is Windows-only, you could take the "portable/embeddable python version" from https://www.python.org/downloads/windows, put your modules (and their dependencies) into it, and give that to user?

**Comment by zuckerruebe** [comment]
It's totally possible that we're misusing `PyInstaller` a bit. In my defense, a bit more detail:

Our application is a GUI application, but with an embedded IPython from which the user can run their own script. Along with the GUI app we provide an additional head-less executable if you will from which they can basically do all they can do from IPython.

**Comment by rokm** [comment]
In general, PyInstaller is ill-suited for applications that allow running arbitrary/external python code that was not seen at the build time (such as users "running their own scripts"). Because such code can contain arbitrary dependencies that are not part of the frozen application and its embedded python interpreter (for example, we do not even collect whole stdlib).

If you need `python.exe` for whatever reason, then you either need a portable python installation/distribution, or python environment (pre-)available on the target machine. And you don't need PyInstaller at all - because its embedded interpreter and its environment, which is bundled with frozen application, is separate from the environment of interpreter spawned by `python.exe`.
