### ISSUE TITLE
Can't include data file into .exe

### ISSUE THREAD

**Issue by TimofeiKargin** [pyinstaller/pyinstaller#8144]
Using Windows.
Everything works great with my app, except it needs to load a model.h5 file into memory. So, I tried to use --add-data argument, but didn't succeed - script created the same .exe file without model data in it.
Here is my freeze script:

```
import PyInstaller.__main__

PyInstaller.__main__.run([
    'main.py',
    '--one-file',
    '--windowed',
    'add-data',
    'model.h5:.'])
```

**Comment by rokm** [comment]
> ```
> import PyInstaller.__main__
> 
> PyInstaller.__main__.run([
>     'main.py',
>     '--one-file',
>     '--windowed',
>     'add-data',
>     'model.h5:.'])
> ```

This would probably build nothing due to incorrect/unrecognized arguments.

It should be:

> ```
> import PyInstaller.__main__
> 
> PyInstaller.__main__.run([
>     'main.py',
>     '--onefile',
>     '--windowed',
>     '--add-data',
>     'model.h5:.'])
> ```

If that is what you are actually using, what are the contents of the executable as listed using `pyi-archive_viewer dist\main.exe`? Is your `model.h5` listed in there? (or alternatively, if you build without `--onefile`, do you see the file collected into the resulting onedir build?)

**Comment by TimofeiKargin** [comment]
>If that is what you are actually using

yes, I used correct arguments

> or alternatively, if you build without `--onefile`, do you see the file collected into the resulting onedir build?)

I tried without --onedir.
I got dist\main\_internal folder with a lot of files including model.h5
But when I run .exe this is what I got:
![Снимок экрана 2023-12-06 024649](https://github.com/pyinstaller/pyinstaller/assets/134188456/62423511-cc54-48d1-984c-6259c27be976)

**Comment by rokm** [comment]
Then the problem is not that the file is not collected, but that you are trying to load it using relative path, which assumes that the model file is in the current working directory. And in the frozen applications, that's not the case (nor it is the case if you run your original unfrozen script from an arbitrary directory). See [the docs](https://pyinstaller.org/en/stable/runtime-information.html).

**Comment by TimofeiKargin** [comment]
> See the docs

Nice, everything works now. Thanks a lot!
