### ISSUE TITLE
Include pyside6-uic in the executable

### ISSUE THREAD

**Issue by mire22** [pyinstaller/pyinstaller#8151]
## Description of the issue

Hi,

I have a Python program with a GUI based on PySide6 with *.ui files.
After creating the code, i get the following error:
`Check if 'pyside6-uic' is in PATH`

A workaround is to add the pyside6-uic in the datas files.
Could you include it by default when there is PySide in use?

NB: For PyQt there was not this issue.

Best regards,
Rémi

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.2.0```
* Version of Python: 3.10.11
* Platform: Windows (FR)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? No

**Comment by rokm** [comment]
Can you provide an example that requires `pyside6-uic` to be available? Are you using `PySide6.QtUiTools.loadUiType()` function instead of  `PySide6.QtUiTools.QUiLoader` class?

**Comment by mire22** [comment]
Yes, I'm using `PySide6.QtUiTools.loadUiType()`.

Enclosed is an example with python, ui, and spec file:
[example.zip](https://github.com/pyinstaller/pyinstaller/files/13597866/example.zip)

The full error message when i run it is:
```Cannot run 'pyside6-uic':  "Process failed to start: Le fichier spécifié est introuvable."  -  Exit status  QProcess::NormalExit  ( 0 )
 Check if 'pyside6-uic' is in PATH
Traceback (most recent call last):
  File "C:\Users\*******\example.py", line 21, in <module>
    BASE, FORM = loadUiType(UIFILENAME)
TypeError: cannot unpack non-iterable NoneType object
[14412] Failed to execute script 'example' due to unhandled exception!

**Comment by rokm** [comment]
> Yes, I'm using `PySide6.QtUiTools.loadUiType()`.

You'll have to find another way, I'm afraid.

If you can use `QtUiTools.QUiLoader`, then go with that:
<details><summary>example2.py</summary><p>

```python
import sys
import os

from PySide6 import QtWidgets, QtUiTools

app = QtWidgets.QApplication(sys.argv)
ui_path = os.path.join(os.path.dirname(__file__), "example.ui")
window = QtUiTools.QUiLoader().load(ui_path)
window.show()
app.exec()
```
</p></details>

If you cannot, because for example you need to inherit from the UI-defined widget like you do in your example code, then you should create a workflow where you use `pyside6-uic` to compile the .ui files into .py files, and import those .py files. This approach makes more sense in the context of PyInstaller-frozen application anyway, as opposed to recompiling the .ui files on each run (which is why `loadUiType` requires `pyside6-uic`); the [official PySide documentation](https://doc.qt.io/qtforpython-6/PySide6/QtUiTools/loadUiType.html) also suggests the same.

---

The main reason why I'm closing this as won't-fix, though, is because collecting `pyside6-uic` does not really solve the problem. `pyside6-uic` is not a stand-alone executable, but an entry-point script, and as such it is tied to your python (virtual) environment, and the `PySide6` installation in it. If you add `pyside6-uic` to datas (or binaries), the frozen application will work on your build system. But if you remove/rename your python (virtual) environment or move to another system without the same python environment location (or without PySide6 installed), it will not work.

So the PySide functionality that involves spawning its entry-point scripts is inherently incompatible with PyInstaller and non portable.

**Comment by mire22** [comment]
Thank you for your answer, I will manage a workflow with the Python file generation before generating the frozen application.
