### ISSUE TITLE
Portable python exe can't load dll files located in the same folder!

### ISSUE THREAD

**Issue by coder4589** [pyinstaller/pyinstaller#8153]
When the portable python exe file is executed, it says the dll is missing.

![dll missing](https://github.com/pyinstaller/pyinstaller/assets/28034488/67646ab8-e5e5-4d71-83ca-0c3d884dfa2a)

**Comment by rokm** [comment]
Well, if Portable.exe is a `onefile` PyInstaller-generated executable, then putting the DLL in the same directory as executable won't help - because what is likely missing the DLL is not the executable itself, but rather the `python3x.dll` (or some other component) in the child process. So if you really need to bundle `api-ms-win-core-path-l1-1-0.dll`, you should ensure that it is bundled with the frozen application (either by making it available in `PATH` during the build, so binary dependency analysis can pick it up, or explicitly bundling it using `--add-binary` switch). Or you should ensure that you have UCRT installed on the target machine (you failed to mention what version of Windows that is, anyway).

**Comment by coder4589** [comment]
@rokm 

Portable.exe is a third-party app, I don't have the source code and I didn't built it. 

Portable.exe extracts all required files, except "api-ms-win-core-path-l1-1-0.dll" in "C:\\Users\\%username%\\AppData\\Local\Temp\\_MEIxxx"  (xxx varies at every execution)

![Image _2](https://github.com/pyinstaller/pyinstaller/assets/28034488/56d00add-238f-44ba-b64e-2c2e9b80b218)

I pasted the dll files from link below (made specifically for Python 3.9 / Windows 7) in "System32" and "SysWOW64" folders and fixed the missing dll error in my Windows 7 x64 SP1:

https://github.com/nalexandru/api-ms-win-core-path-HACK

But I would like to paste the dll files above in the exe folder instead in "System32" and "SysWOW64" folders, is it not possible?

**Comment by bwoodsend** [comment]
> But I would like to paste the dll files above in the exe folder instead in "System32" and "SysWOW64" folders, is it not possible?

No chance. You'll just tell whoever built this application that it's missing a DLL.

**Comment by coder4589** [comment]
@bwoodsend 

The person who built the app is kind of inactive from github since July 2023, but who knows, maybe he will reply to some issues I posted in their app's repository.

https://github.com/thirashapw/RearGen

By the way, in the exe building process, is it possible to instruct "pyinstaller" to make the exe load required files (python39.dll, pyd, DLLs, etc) from the exe folder\subfolders instead extracting and loading them from "C:\\Users\\%username%\\AppData\\Local\Temp\\_MEIxxx" ?

"_MEIxxx" method is really not convenient, each time "RearGen.exe" is executed, a "_MEIxxx" temp folder with 11 MB of data is created.

The issue is, when "RearGen.exe" is closed, it does not delete the "_MEIxxx" temp folder, which will lead to a lot of "_MEIxxx" folders after a while.

One more thing, do you know about any app similar to RearGen from the link above?

**Comment by rokm** [comment]
> By the way, in the exe building process, is it possible to instruct "pyinstaller" to make the exe load required files (python39.dll, pyd, DLLs, etc) from the exe folder\subfolders instead extracting and loading them from "C:\Users\%username%\AppData\Local\Temp\_MEIxxx" ?

PyInstaller can build your application in either `onedir` or `onefile` mode. 

In `onedir`, dependencies (DLLs, data files, etc) are collected in the directory, and placed next to executable (in the v6, they are collected in the `_internal` directory. 

In `onefile` mode, dependencies are collected in executable-embedded archive, and extracted to temporary directory on each run. In this mode, the program is ran as two processes; the parent process unpacks the archive, runs the child process (which runs your application code), and after the child process exists, cleans up the temporary directory. 

> "_MEIxxx" method is really not convenient, each time "RearGen.exe" is executed, a "_MEIxxx" temp folder with 11 MB of data is created.

That's for you and the author of your application to sort out. We do not force anyone to use `onefile` mode instead of `onedir` one...

> The issue is, when "RearGen.exe" is closed, it does not delete the "_MEIxxx" temp folder, which will lead to a lot of "_MEIxxx" folders after a while.

How are you closing the "RearGen.exe"? If you forcefully terminate the parent process of `onefile` application (which, in PyInstaller < 5.3 also includes closing the application's console window), the temporary directory is left behind on each run.

**Comment by coder4589** [comment]
@rokm 

Thanks for the clarifications, especially for "_internal" directory in v6.

> How are you closing the "RearGen.exe"?

I juts click at the "RearGen.exe" cmd window's "X" button to close it.

![RearGen - Close Button](https://github.com/pyinstaller/pyinstaller/assets/28034488/68f0094f-c2c8-4298-afe0-56807fd1525b)

**Comment by rokm** [comment]
> > How are you closing the "RearGen.exe"?
> 
> I juts click at the "RearGen.exe" cmd window's "X" button to close it.

Then that's why application cannot clean up after itself. Surely the window would have closed itself after you "press any key to exit"? 

We added an attempt to gracefully handle console window being closed in PyInstaller 5.3, but it looks like this application was made with an older version of PyInstaller (since it contains `pyimod01_os_path` module, which we also removed in 5.3)

**Comment by coder4589** [comment]
@rokm 

I will use "press any key to exit" option for now on.

Hopefully, the developer of RearGen will release a new version in the future with pyinstaller v6+ and use the "onedir" (_internal) instead of "onefile" (_MEIxxx) mode.

Thanks again for all the clarifications.
