### ISSUE TITLE
OpenCV  

### ISSUE THREAD

**Issue by Safa1902** [pyinstaller/pyinstaller#8169]
when i try install open cv on raspberry pi i followed instructions of all videos and i still got the same error when i  check  by importing numpy library it works but when i write the command import cv2 to test it gives me this message always i dont have much experience  to detect the error 
**>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aamz/.local/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/aamz/.local/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/aamz/.local/lib/python3.9/site-packages/cv2/cv2.abi3.so: undefined symbol: __atomic_store_8
>>>**

**Comment by rokm** [comment]
This has nothing to do with PyInstaller, though... 

---

If I had to guess, I would say you are using pre-built OpenCV, which was built on an older system/OS with toolchain where `__atomic_*` symbols were still part of `libgcc`, but your system/OS is more recent, and those symbols are now part of `libatomic` (and since your `cv2.abi3.so` is not linked against it, the symbols are missing). As a work-around, you can try setting try setting `LD_PRELOAD` as per https://github.com/opencv/opencv/issues/15278#issuecomment-520380265, although you should probably look for a build that is compatible with the ABI of the OS on your Raspberry Pi.
