### ISSUE TITLE
spec文件配置console=False隐藏控制台后HTTP无法响应问题

### ISSUE THREAD

**Issue by Adreaming5101** [pyinstaller/pyinstaller#8188]
我用的pyinstaller6.2版本，spec文件中配置console=False参数，运行pyinstaller app.spec指令后生成exe，隐藏控制台运行这个exe，出现HTTP无法响应的问题：
![3333](https://github.com/pyinstaller/pyinstaller/assets/65139772/d111a13f-0086-44e8-951a-0ab41a0851af)

![222](https://github.com/pyinstaller/pyinstaller/assets/65139772/508dc042-0232-46de-b02d-159d02a9197b)

但是我只修改一个参数为console=True就不会出现此问题：
![3338](https://github.com/pyinstaller/pyinstaller/assets/65139772/2b36a444-f688-46da-b45e-d506209c64cd)

![55555](https://github.com/pyinstaller/pyinstaller/assets/65139772/6e7a52ad-065d-4349-a6a3-609643e8b478)

请问原因是什么呢？有什么解决问题的思路吗？

**Comment by Adreaming5101** [comment]
我之前用的python3.9版本出现此问题，将python版本升级到3.11后此问题依然存在。

**Comment by Adreaming5101** [comment]
我之前用的python3.9版本出现此问题，将python版本升级到3.11后此问题依然存在，然后我尝试将pyinstaller版本下降到5.10也无法解决！

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md). This tells me nothing.

**Comment by rokm** [comment]
This looks like that some part of your code is assuming that console is available, and fails because it is not. And the exception is either swallowed, or turned into a log message (which you cannot see due to lack of console), or occurs in a thread and is therefore not fatal for the application.

Does it help if you add the following snippet at the start of your entry-point script (`manage.py`)?
```python
import sys
if sys.stdout is None:
    sys.stdout = open(os.devnull, "w")
if sys.stderr is None:
    sys.stderr = open(os.devnull, "w")

# ... the rest of your program
```
