### ISSUE TITLE
import dependency of sub_module

### ISSUE THREAD

**Issue by eshopblr** [pyinstaller/pyinstaller#8209]
I have a sub module of an APP.  The submodule has __init__.py which has import of one file in the same directory which is used in the __init__.py and failing as app not ready as the file is not loaded yet.

How to resolve this kind of early import in the __init__.py dependency of hidden imports  when collecct_submodule of that app is done?

Any help on this would be great.

**Comment by bwoodsend** [comment]
> failing as app not ready as the file is not loaded yet.

What does this mean? Can we have a proper error message and reproducer please?

**Comment by eshopblr** [comment]
collect_submodules('A.B.C')
is giving error  where C has following files 
==>  "__init__.py"
==>  "forms.py"

the collect_submodule first loads "__init__.py"

which looks as follow 

from .forms import funcA

where funcA getting imported from forms but forms is not yet known and giving error as follows 

(Pdb)collect_submodules('A.B.C')
(Pdb) from .forms import funcA
*** django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet. ==> here it does not knows forms.py as not collected yet.

**Comment by rokm** [comment]
For `collect_submodules` to work, the package needs to be importable (on its own). In this case, it seems that in order to import the package, django app(s) need to be registered first; so `collect_submodules` is not going to work.

But why are you even trying to use `collect_submodules` in the first place? If `A.B.C` contains only `__init__.py` and `forms.py`, you could as well just manually write `hiddenimports = ['A.B.C', 'A.B.C.forms']` instead.

**Comment by eshopblr** [comment]
this is getting collected from hook-django.py as follows or all apps which is read from INSTALLED_APPS of settings.py, some of these apps are having submodules ( in A.B.C note that A is an app registered in INSTALLED_APPS )

    settings_py_imports = django.django_dottedstring_imports(root_dir)
    # Include all submodules of all imports detected in mysite.settings.py.
    for submod in settings_py_imports:
        hiddenimports.append(submod)
        hiddenimports += hooks.collect_submodules(submod) === > this one 


where as the PyInstaller\utils\hooks\init.py wich implements collect_submodules calls the _collect_submodules

            modules, subpackages, on_error = isolated_python.call(_collect_submodules, name, on_error)


_collect_submodules ==> thjis module has following implementation

    try:
        __import__(name) ==> this is calling that submodules init.py in the framework flow.. hence the error 
    except Exception as ex: 



As this is in FW flow, how can we avoid the dependency of imports

**Comment by rokm** [comment]
Hmmm, does this error result in breaking/interrupting of the build process, or just warnings that we failed to collect submodules from `A.B.C`? Can se wee the full build log?

I'm not really familiar with django, but to handle this case, I think the hook should be changed to do all its analysis in a single subprocess, after it imports the `settings.py` (instead of performing each analysis part in its own subprocess, as it does now) - that would probably initialize the app registry, and allow subpackages to be imported. 

Could you provide a minimal sample django project that triggers this error, so we can experiment with it?

**Comment by eshopblr** [comment]
re arranged the application code and avoided deep nesting of sub-modules and directories.
