### ISSUE TITLE
exclude-module option is not working

### ISSUE THREAD

**Issue by eshopblr** [pyinstaller/pyinstaller#8217]
I have to exclude a custom app and included that option while compiling to generate exe but the exe still included that app. 

pyinstaller  --log-level=DEBUG --onefile --name=poll **--exclude-module pollme.accounts** --additional-hooks-dir=..\Django-Poll-App-master\pyinstallerHooks  --add-data "..\Django-Poll-App-master\templates;templates"  --add-data "db.sqlite3;."  manage.py

--exclude-module pollme.accounts ==> Still this app is included.

Am I missing any thing?

**Comment by bwoodsend** [comment]
What makes you think that that submodule is being included?

**Comment by eshopblr** [comment]
I mean when exe is executed in the TEMP folder APP related files are present though it is specified as excluded_module while compiling. How can we exclude specific APP's ?

**Comment by rokm** [comment]
If there are data files (possibly also .py files) present for the app, then they might be collected via a data collection instruction (either automatically in django hook, or manual one in the spec file) - `--exclude-module` has no power over those. 

I suppose the only reliable method to ensure that neither the app nor its data files are collected is to ensure it is not in your build environment (or perhaps not having it listed among `INSTALLED_APPS` would suffice?).

Otherwise, you'll need to provide a sample django project that reproduces the issue, so we can see how things are collected, and what can be done about excluding specifiec apps.

**Comment by eshopblr** [comment]
Agree with you. 
Would you consider to provide filter to  **collect_data_files** like collect_submodules has ? Wouldn't that be helpfull for collect_data_files  to filter some of the not needed sub directories. This would be a helper function which would be handy.

**Comment by rokm** [comment]
> Agree with you. Would you consider to provide filter to **collect_data_files** like collect_submodules has ? Wouldn't that be helpfull for collect_data_files to filter some of the not needed sub directories. This would be a helper function which would be handy.

I would prefer not to complicate the logic in `collect_data`, because if a package is not intended to be collected, `collect_data` should not be called on it (or on its parent, if it is a sub-package) in the first place. Besides, `collect_data` already has `excludes` and `includes` arguments that can be used for filtering (but the filtering in based on path/filename patterns, not on module name).

**Comment by eshopblr** [comment]
yes, that helped. Thank you.
