### ISSUE TITLE
pyi_rth_win32comgenpy hook ignores TEMP environment

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#8231]
I noticed that when the PyInstaller application is running, there is always a temp directory created in the default `TEMP` directory ignoring the environment variables.

I found this [hook](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_win32comgenpy.py) that creates the temp for the `gen_py` cache, it is using an internal function to create the temp called `_pyi_rth_utils.tempfile.secure_mkdtemp()`, this implementation is lacking the call for `tempfile._candidate_tempdir_list()` which take into account the environment variables to decide where to create this file. 

Python: 3.8.10
PyInstaller: 6.3.0
OS: Windows

**Comment by rokm** [comment]
The implementation in `_pyi_rth_utils.tempfile.secure_mkdtemp()` 

https://github.com/pyinstaller/pyinstaller/blob/dbe5250a8f4b434d0b4fb9f51fac4014e1eba8b5/PyInstaller/fake-modules/_pyi_rth_utils/tempfile.py#L25-L53

is, as mentioned in its description, [a copy of stdlib's `tempfile.mkdtemp`](https://github.com/python/cpython/blob/fa7a6f23036537567592647d15f043722c7144ad/Lib/tempfile.py#L344-L382):

```python
def mkdtemp(suffix=None, prefix=None, dir=None):
    """User-callable function to create and return a unique temporary
    directory.  The return value is the pathname of the directory.

    Arguments are as for mkstemp, except that the 'text' argument is
    not accepted.

    The directory is readable, writable, and searchable only by the
    creating user.

    Caller is responsible for deleting the directory when done with it.
    """

    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)

    names = _get_candidate_names()
    if output_type is bytes:
        names = map(_os.fsencode, names)

    for seq in range(TMP_MAX):
        name = next(names)
        file = _os.path.join(dir, prefix + name + suffix)
        _sys.audit("tempfile.mkdtemp", file)
        try:
            _os.mkdir(file, 0o700)
        except FileExistsError:
            continue    # try again
        except PermissionError:
            # This exception is thrown when a directory with the chosen name
            # already exists on windows.
            if (_os.name == 'nt' and _os.path.isdir(dir) and
                _os.access(dir, _os.W_OK)):
                continue
            else:
                raise
        return file

    raise FileExistsError(_errno.EEXIST,
                          "No usable temporary directory name found")
``` 

The only difference is that instead of calling `os.mkdir`, we call our `_win32.secure_mkdir` to make it accessible only to the owner. The rest of the behavior should be the same.

Both implementations call tempfile._sanitize_params; if called with `dir=None`, that in turn calls `tempfile.gettempdir` ([here](https://github.com/python/cpython/blob/fa7a6f23036537567592647d15f043722c7144ad/Lib/tempfile.py#L124-L128)), which in turn calls `tempfile._get_default_tempdir` ([here](https://github.com/python/cpython/blob/v3.11.7/Lib/tempfile.py#L285-L303)). And that calls `tempfile._candidate_tempdir_list` ([here](https://github.com/python/cpython/blob/fa7a6f23036537567592647d15f043722c7144ad/Lib/tempfile.py#L193)).

**Comment by rokm** [comment]
And if I insert a `print(f"secure_mkdtemp: {file}")` in the `secure_mkdtemp` [here](https://github.com/pyinstaller/pyinstaller/blob/dbe5250a8f4b434d0b4fb9f51fac4014e1eba8b5/PyInstaller/fake-modules/_pyi_rth_utils/tempfile.py#L42), and build the following program under python.org python 3.8.10:
```python
import win32com
print("hello!")
print("Press any key to continue")
input()
```

the behavior is as follows:

```
>set TMPDIR
Environment variable TMPDIR not defined

>set TEMP
TEMP=C:\Users\Rok\AppData\Local\Temp

>set TMP
TMP=C:\Users\Rok\AppData\Local\Temp
```

So since `tempfile._candidate_tempdir_list` uses `TMPDIR`, `TEMP`, and `TMP` (in that order - see [here](https://github.com/python/cpython/blob/fa7a6f23036537567592647d15f043722c7144ad/Lib/tempfile.py#L163C20-L163C43)), `TEMP` ends up being the controlling variable:

```
>dist\program\program.exe
secure_mkdtemp: C:\Users\Rok\AppData\Local\Temp\tmpb3r9iqb6
hello!
Press any key to continue
```

If we try to set it to an arbitrary directory

``` 
>set TEMP=c:\my-temp

>dist\program\program.exe
secure_mkdtemp: C:\Users\Rok\AppData\Local\Temp\tmp1j15my1j
hello!
Press any key to continue
```

it doesn't work, because we did not create it (and thus fall back to `TMP`). After we create the directory:

```
>mkdir c:\my-temp

>dist\program\program.exe
secure_mkdtemp: c:\my-temp\tmp_a9et5od
hello!
Press any key to continue
```

And lastly, an example that modifies both `TEMP` and `TMP`:

```
>set TEMP=c:\my-other-temp
>set TMP=c:\my-temp

>dist\program\program.exe
secure_mkdtemp: c:\my-temp\tmpu5qhgrjf
hello!
Press any key to continue

>mkdir c:\my-other-temp

>dist\program\program.exe
secure_mkdtemp: c:\my-other-temp\tmpfxc6ea7j
hello!
Press any key to continue
```

**Comment by arossert** [comment]
@rokm you are correct, I missed that flow that does use `_candidate_tempdir_list()`
