### ISSUE TITLE
This probably means that Tcl wasn't installed properly.

### ISSUE THREAD

**Issue by pretant** [pyinstaller/pyinstaller#8271]
Executable file only works when it is in the environment where tk/tcl is present. When it is distributed to other users, or moved into different directory, it will raise this error:

"Traceback (most recent call last):
  File "QAScripts3.8.0.py", line 4474, in <module>
  File "tkinter\__init__.py", line 2326, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    {C:\WINDOWS\TEMP\_MEI75162\tcl} C:/WINDOWS/TEMP/_MEI75162/tcl8.6 C:/WINDOWS/TEMP/lib/tcl8.6 {C:/Users/Pretan Tabag/lib/tcl8.6} C:/Users/lib/tcl8.6 {C:/Users/Pretan Tabag/library} C:/Users/library C:/Users/tcl8.6.12/library C:/tcl8.6.12/library

This probably means that Tcl wasn't installed properly."

It looks like it is looking for tcl in the directory where the executable file is in.

This started happening when I uninstalled python, and pycharm, and deleted the folders related to them and removed them from path for the purpose of starting clean and new. I reinstalled them back and then installed the needed libraries and then ran pyinstaller with the same method as before. i was running python 3.11

  File "QAScripts3.8.0.py", line 4474, in <module> --> this line is "root = tk.Tk()"

**Comment by bwoodsend** [comment]
If you're not going to provide a minimal reproducible example then we can't help you.

**Comment by rokm** [comment]
Try using `pyi-archive_viewer` to list the contents of the frozen application (or build in onedir mode so you can inspect the contents with file browser)  - particularly the contents of the `tcl` directory. The `tcl` directory likely exists, otherwise run-time hook would raise an error [here](https://github.com/pyinstaller/pyinstaller/blob/249d8fc84fc3707fe47b1a5b9a006baf3b3657ec/PyInstaller/hooks/rthooks/pyi_rth__tkinter.py#L24-L27); but it is apparently missing the `init.tcl`. So the question is, what files *does* it contain?
