### ISSUE TITLE
Pyinstaller packaging error (sqlalchemy)

### ISSUE THREAD

**Issue by chenlt-god** [pyinstaller/pyinstaller#8272]
When I use pyinstaller to package software, if I use the sqlalchemy library in my code, the software does not report an error during packaging, but when I open the software, the software reports an error Traceback (most recent call last):
File "main. py", line 16, in<module>
ModuleNotFoundError: No module named 'sqlalchemy'
And I am confident that there is this sqlalchemy package in the virtual environment,
<img width="361" alt="WechatIMG46938" src="https://github.com/pyinstaller/pyinstaller/assets/56865296/32bd66d9-482a-4ac5-ba54-16f39b0e6bd4">

**Comment by rokm** [comment]
Is line 16 in main a straightforward `import sqlalchemy`? If that's the case, then the package was not discoverable during the build. One reason would be that it is not installed in the virtual environment, but if you are confident that this is not the case, the other common reason is that you are running a PyInstaller that is installed in a different environment (be it virtual one or a base one). If you run `where pyinstaller`, do you see only the entry belonging to your virtual environment? (Alternatively, if you run `python -m PyInstaller ...` instead of `pyinstaller ...` with your virtual environment active, does it make any difference?)
