### ISSUE TITLE
Program crashes when using the newest pyinstaller

### ISSUE THREAD

**Issue by zhengxyz123** [pyinstaller/pyinstaller#8305]
I have already opened an [issue](https://github.com/pyglet/pyglet/issues/1049) in other repo, but we all agree that it's a bug of pyinstaller.

Segment fault happened when using `pyinstaller>6`, it won't happen when using `pyinstaller<6`.

Detailed crash information was enclosed in the pre-opened issue.

**Comment by rokm** [comment]
This looks like combination of regression in PyInstaller 6.x, and a bug in `pyglet`.

For our part, the problem is that with PyInstaller 6.x, `locale.getlocale()` in frozen application returns `(None, None)`. This is a regression both with respect to unfrozen python, and PyInstaller 5.x, and happened during transition to new interpreter initialization API.

The problem is `pyglet` is that it does not properly guard against non-UTF8 locales (I'll update the linked issue with details).
