### ISSUE TITLE
Support pathlib.Path as icon parameter

### ISSUE THREAD

**Issue by Geo5** [pyinstaller/pyinstaller#8314]
It would be nice to allow passing a pathlib.Path to the icon parameter directly in a .spec file.
This seems to already be possible with all other path-like inputs in a .spec file (e.g. datas and spash image).

The easiest solution for me seems to be to modify [these lines in icon.py](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/win32/icon.py#L171)  to something like
```python
if isinstance(srcpath, (str, pathlib.Path)):
        # Just a single string, make it a one-element list.
        srcpath = [str(srcpath)]
```
(obviously with an import of pathlib)

I can submit a pull request, if you approve the change.

**Comment by bwoodsend** [comment]
That code would mean that passing a list of icon paths would break if any of the paths are `pathlib.Path()`s. A conversion after the conditional would make more sense:
```python
srcpath = [str(path) if isinstance(path, os.PathLike) else path for path in srcpath]
```
Note the use of the abstract class `os.PathLike()` instead of `pathlib.Path()` so that it still works for people who insist on using `ubelt.Path()` for example.

**Comment by bwoodsend** [comment]
Thanks for doing that
