### ISSUE TITLE
Help me see what's wrong with this Package Flask-SocketIO

### ISSUE THREAD

**Issue by hzb888** [pyinstaller/pyinstaller#8342]
```python
from flask import Flask
from flask_cors import CORS
from flask_socketio import SocketIO

app = Flask(__name__)
CORS(app)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, cors_allowed_origins='*')


@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"


@socketio.on('connect')
def test_connect():
    print("connect")


if __name__ == '__main__':
    # app.run()
    socketio.run(app)
```
This is my code and then package it with pyinstaller as an exe
Then run the exe to report ImportError: DLL load failed while importing _ssl

Below is the environmental information
Flask = = 2.2.3
Flask - Babel = = 3.0.1
Flask - Cors = = 4.0.0
Flask - SocketIO = = 5.3.6
Flask - Sockets = = 0.2.1
Pyinstaller = = 6.3.0
Pyinstaller hooks - contrib = = 2024.0

**Comment by rokm** [comment]
Do you get this when running on the same machine, or a different one? What version of Windows are you running on? What version of python was used in the build? And how did you install python (python.org, windows store, anaconda)?

Can you re-run the build with added `--clean` and `--log-level DEBUG` flags, and save the console output to a .txt file. Then, also archive the `build` and `dist` directory, and upload everything somewhere so that I can take a look at it?

**Comment by hzb888** [comment]
> Do you get this when running on the same machine, or a different one? What version of Windows are you running on? What version of python was used in the build? And how did you install python (python.org, windows store, anaconda)?
> 
> Can you re-run the build with added `--clean` and `--log-level DEBUG` flags, and save the console output to a .txt file. Then, also archive the `build` and `dist` directory, and upload everything somewhere so that I can take a look at it?

Thanks for your answer, I built it directly using the pyinstaller installed by conda. The operation reported an error. Later, I looked at other issues and used venv to repackage and solve the problem. Thank you
