### ISSUE TITLE
ImportError: The"platformdirs’ package is required;

### ISSUE THREAD

**Issue by cheamy** [pyinstaller/pyinstaller#8410]
When packaging a Python file using PyInstaller, the EXE file created from a Conda virtual environment can be executed but is relatively large. Therefore, I attempted to use a Pipenv virtual environment to package the file. However, the resulting EXE constantly encounters an error: ImportError: The 'platformdirs' package is required. After finding related answers, I was informed that it could be due to a too high version of setuptools. However, after modifying it, the problem persisted. I even compared and matched the versions of all packages in the Conda environment and made changes accordingly, but it still didn't work. Could you please provide a solution
![微信图片编辑_20240415213524](https://github.com/pyinstaller/pyinstaller/assets/49443876/4f30fa44-921a-4cf3-a12a-755b753a1537)

**Comment by rokm** [comment]
So what version of `setuptools` are you using? And what version of python and PyInstaller are you using?

**Comment by cheamy** [comment]
> So what version of `setuptools` are you using? And what version of python and PyInstaller are you using?

Sir, python is 3.11, Pyinstaller is 6.5.0, setuptools is 68.2.0

**Comment by rokm** [comment]
I can't reproduce this.

Since the error is coming from our `pkg_resources` run-time hook, this should be triggered by the following sample program:

```python
import pkg_resources
print(pkg_resources)
```

Can you try freezing the above program with `--log-level DEBUG` added to your PyInstaller command? If the built test program fails in the same way, copy and save the build log to a text file. Then archive the resulting `build` and `dist` directories together with the build log file and upload them somewhere so I can download them and take a look.
