### ISSUE TITLE
PyInstaller fails with Python 3.12 / Ubuntu 24.04

### ISSUE THREAD

**Issue by gjasny** [pyinstaller/pyinstaller#8428]
Hello,

I tried to build Conan on the Ubuntu 24.04 beta which includes Python 3.12. When running `python pyinstaller.py` the first time on the venv it fails, running it a second time succeeds. You could find the steps to reproduce and the stack trace in conan-io/conan#16076.

Basically `load_ldconfig_cache`  fails in
https://github.com/pyinstaller/pyinstaller/blob/ba3ccc68be8dff67106e39d85873ca8165b9677f/PyInstaller/depend/utils.py#L326

Now I'm wondering if this was an oversight when porting PyInstaller to Python 3.12 or if the method should not have been called in the first place?

Could you please take a look?

Thanks,
Gregor

**Comment by rokm** [comment]
`distutils` was indeed removed from python 3.12 stdlib, but it is provided by `setuptools`.

I think the problem here is that the custom `pyinstaller.py` build script installs pyinstaller (and `setuptools` as its dependency) via spawned subprocess, but then proceeds to run PyInstaller code directly within its own process. Since this process was started before `setuptools` was installed, its `_distuils_hack` is not registered (via `distutils-precedence.pth`), and thus `distutils` cannot be found. On the second run, `setuptools` is available from the start, and therefore so is `distutils`.

The most straight-forward way to fix this is to install PyInstaller before running the build script, instead of having build script install it for you.

**Comment by memsharded** [comment]
Thanks @rokm for the answer.
I tried it in Windows, and it was working. Is there any specific reason why the above will only fail in Linux but not Windows?

**Comment by rokm** [comment]
> Thanks @rokm for the answer. I tried it in Windows, and it was working. Is there any specific reason why the above will only fail in Linux but not Windows?

The `PyInstaller.depend.load_ldconfig_cache()` function that caused error due to missing `distutils` in https://github.com/conan-io/conan/issues/16076 is used only on POSIX platforms other than macOS. So in this case, on Linux.
