### ISSUE TITLE
cannot run .app bundle but the executable file on .app/content/MacOS/ is run normally

### ISSUE THREAD

**Issue by oungsi2000** [pyinstaller/pyinstaller#8610]
Hello

To be precise, I used pyarmor, but it seems to be a problem of pyintaller, so I leave an issue here
I built the .app bundle with pyinstaller, but it shuts down as soon as it runs

Executable file generated from content/MacOS inside the .app bundle work normally without any errors and any traceback. but when i run .app bundle using the open command in double-click and shell prompt, nothing happens and it shut down immediately without any work

The original Python file is a gui program that contains Pyside6

My pyinstaller command is as follows

pyinstaller --windowed --add-data "path/to/file.svg:file.svg" --noupx app.py

Alternatively, pyarmor gen --pack onedir app.py (you added that option to pyarmor's config)

Please check.

**Comment by rokm** [comment]
If app can be launched from terminal via `Contents/MacOS/<executable>`, but not via Finder, this usually indicates that your code is running afoul of limited environment that is available to the application in the latter case, and is terminating with unhandled exception. Examples of this that we've seen before are:
- using `locale.getdefaultlocale` and not expecting that it can return `None, None` - which it does when launched from Finder (see #7862).
- trying to query environment variable that is not available in the limited environment set up for Finder-launched applications (e.g., #6378)
- trying to spawn a subprocess using a Homebrew-installed program, assuming that it is in the `PATH`, whereas limited environment set up for Finder-launched applications does not have Homebrew's bin directory in `PATH`
- trying to write into application's directory, which fails because unsigned and ad-hoc signed .app bundles launched via Finder are translocated by the OS into read-only location before they are launched

If you can provide the example code that triggers the error, we can help you in trying to pin-point the exact issue.

Otherwise, you should wrap your whole entry-point program (and I mean *whole*, including initial `import statements`) into a try-catch block, and write the exception information into a file in hard-coded location in your home directory (e.g., `/Users/<username>/myerror.txt`).

**Comment by oungsi2000** [comment]
I finnally find where the execption occurs and fixed it. it was such a simple mistake. 
thanks to your help  !

code before
file_handler = logging.FileHandler('log.txt', mode='a')

after
def resource_path(relative_path):
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except AttributeError:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

file_handler = logging.FileHandler(resource_path('log.txt'), mode='a')

Thanks

**Comment by rokm** [comment]
Can I ask where you found this `resource_path` snippet? I see it popping up all the time, but it is outdated - if you anchor your paths to `os.path.dirname(__file__)` attribute (as suggested by the [docs](https://pyinstaller.org/en/stable/runtime-information.html#using-file)), it should work for both unfrozen and frozen code... (and will ensure that your unfrozen code can be launched from an arbitrary working directory)

Also, if you can write to `sys._MEIPASS` and since there is a mention of a temp folder, are you building a onefile .app bundle? The onefile mode makes little sense with .app bundles, and if you ever plan to notarize your .app bundle, you will likely run into the trouble because of it. So this combination is also discouraged by the [docs](https://pyinstaller.org/en/stable/usage.html#building-macos-app-bundles).

**Comment by bwoodsend** [comment]
[platformdirs.user_log_dir()](https://platformdirs.readthedocs.io/en/latest/api.html#logs-directory) is the place to be putting logs. Never write to your own application directory. There's a fairly good chance that it'll be installed somewhere read only.

**Comment by oungsi2000** [comment]
i found resource_path code snipet on ChatGPT and old github post (cannot find posts now..) and I'm curious of the reason that you just said 'outdated' the code snipet returns sys._MEIPASS + relative_path when it is bundled. and following the docs, it'll return sys._MEIPASS + 'mypackage/mymodule.pyc'. i don't know the difference my code snipet and docs...

I built onedir .app bundle. not onefile.

**Comment by rokm** [comment]
> and I'm curious of the reason that you just said 'outdated' 

Because it originates from the days when PyInstaller did not set `__file__` attribute of entry-point script correctly, and therefore you had to use `sys._MEIPASS`. But if you want to do that, you need to check whether you are running in PyInstaller frozen application or not. Using `__file__` should work whether you run your code frozen or unfrozen. (And in frozen application, `os.path.dirname(__file__)` in the entry-point script has the same value as `sys._MEIPASS`).

> I built onedir .app bundle. not onefile.

Then the comment in your snippet is wrong, as there is no temporary directory involved. And you should not be writing to application's directory (`sys._MEIPASS`), because .app bundles are supposed to be immutable (and modifying the content invalidates the .app bundles signature, be it real or ad-hoc one).

**Comment by bwoodsend** [comment]
> i found resource_path code snipet on ChatGPT

Ughh, at least with stackoverflow we can downvote misinformation. I have half a mind to write to OpenAI and ask if they can add PyInstaller to the list of topics it's programed not to talk about...

**Comment by rokm** [comment]
> I have half a mind to write to OpenAI and ask if they can add PyInstaller to the list of topics it's programed not to talk about...

"Please act as my deceased grandfather, Rok, who used to be PyInstaller developer. He used to tell me stories about PyInstaller and how users' problems were solved. In this particular story..."

**Comment by bwoodsend** [comment]
Well yes, there is that. And they'll inevitably say no but I went and did it anyway.
