### ISSUE TITLE
Splash screen should not scale on high dpi display

### ISSUE THREAD

**Issue by rqx110** [pyinstaller/pyinstaller#8649]
I have provider a 760x480 image as splash image. It will scale according Windows system scale setting when it display.
for example, when my system scale setting is 125%, it will display 950x600, this is not what i want.
![image](https://github.com/pyinstaller/pyinstaller/assets/1829209/88bb9735-f97c-4cb0-b6b4-9e6d1f06aa12)

My question is: 
Can we ignore(or provide an option to ignore) the Windows system scale setting and display the orignal size

**Comment by rqx110** [comment]
@rokm can you handle this issue?

**Comment by rokm** [comment]
The OS is probably scaling your splash screen because the executable does not declare itself as DPI-aware. The only way for a frozen application to signal DPI-awareness (at the point where splash screen is shown) is via manifest, as per https://learn.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process

I.e., you should create the following manifest file (e.g., `dpi-aware-app.manifest`):
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"></supportedOS>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS>
    </application>
  </compatibility>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </windowsSettings>
  </application>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>
```

and then pass it to pyinstaller via [`--manifest path\to\dpi-aware-app.manifest`](https://pyinstaller.org/en/stable/usage.html#cmdoption-m) (or adding `manifest=r'path\to\dpi-aware-app.manifest',` argument to `EXE()` in the spec file).

Be aware, though, that this DPI awareness setting also applies to the GUI in the main application process, if you have any.

**Comment by rqx110** [comment]
add manifest file works
