### ISSUE TITLE
Do not have a default-icon in the bootloader, add it when freezing

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#870]
**Original date**: 2014/03/07
**Original reporter**: _AdamS_

In my .spec file, I specify my own icon file using the following syntax:

```
exe = EXE(...
          ...
          icon='myicon.ico')
```

My application builds successfully and displays my own icon. However, when the exe is analysed using a tool such as PE Explorer([http://www.heaventools.com/overview.htm]), Pyinstaller seems to have added two of its own icons to the icon list (see attached for the icons in question).

I guess these icons are added so that they are used as the default in case the user-supplied icon is missing or corrupted. However, a better way to handle this would be to **not** add the Pyinstaller icons to the exe if the user supplies their own.

**Comment by htgoebel** [comment]
We could build the bootloader without any icon (which would save space, too) and add PyInstaller's own icon by default when building.

**Comment by htgoebel** [comment]
Given the many issues with the icons on windows, I'd appreciate is somebody could provide a pull-request for this. This requires rebuilding the bootloader, but otherwise is easy:

- [ ] In the bootloaders wscript, do not add the icon-resource, but keep the slot for the icon. This part requires knowledge about how resources are build into C programs on Windows (I don't know).

In PyInstaller/building/api.py, class `EXE`:
- [ ] in `__init__()`, Move setting `self.icon` near the end of the method. If `is_win`, `self.icon` should default to `os.path.normpath(os.path.join(exe, "../../images/icon-windowed.ico"))` resp. `console`.
- [ ] in `_GUTS`: Add entry `('icon_mtime', None), # checked below`
- [ ] in `_check_guts()`: near the end add a check for `icon_mtime` like it is done for `mtm`

**Comment by custozza** [comment]
is there any work around at the moment to create a start icon on windows10 64bit? using python3.[5-7]?

**Comment by hdf** [comment]
I think you might be overthinking this. Would it not be enough to change this line:
https://github.com/pyinstaller/pyinstaller/blob/a1f92c6a08b45ed53be369298c648627ba189205/PyInstaller/utils/win32/icon.py#L148
and this one:
https://github.com/pyinstaller/pyinstaller/blob/a1f92c6a08b45ed53be369298c648627ba189205/PyInstaller/utils/win32/icon.py#L241
to this?
```py
    hdst = win32api.BeginUpdateResource(dstpath, 1)
```
(Based on [this](https://pywin32-ctypes.readthedocs.io/en/stable/api/win32ctypes.pywin32.win32api.html#win32ctypes.pywin32.win32api.BeginUpdateResource).)

As it seems, that the only resource the loader exe has, is an icon (and icon group), and the icon resource is the first one to be checked, so resetting all resources should not cause any problems. 

This solution does work for me.
