### ISSUE TITLE
Including incorrect libcrypto.so.3 version (system instead of conda)

### ISSUE THREAD

**Issue by jdegenstein** [pyinstaller/pyinstaller#8797]
## Description of the issue

User reports that static build is not working on Ubuntu-22.04. I was able to reproduce also on Ubuntu-22.04 and it is complaining about the wrong OPENSSL version in libcrypto.so.3.
```
./CQ-editor.sh 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "run.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "cq_editor/__main__.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "cq_editor/main_window.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "logbook/__init__.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "logbook/base.py", line 1164, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "logbook/handlers.py", line 16, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "ssl.py", line 100, in <module>
ImportError: /home/oem/Desktop/CQ-editor-Linux-x86_64 (10)/CQ-editor/_internal/libcrypto.so.3: version `OPENSSL_3.3.0' 
not found (required by /home/oem/Desktop/CQ-editor-Linux-x86_64 (10)/CQ-editor/_internal/lib-dynload/_ssl.cpython-311-x86_64-linux-gnu.so)
````
After further investigation, it appears that pyinstaller is including `libcrypto.so.3` from ubuntu-22.04 instead of the conda env (OPENSSL versions 3.0.2 versus 3.3.0 respectively). This is introducing the above incompatibility.

Full build logs are available on CI here with log level debug enabled: https://github.com/jdegenstein/jmwright-CQ-Editor/actions/runs/10925849606/job/30328329933 

The above build logs list `libcrypto.so.3` twice -- in the first instance they are from the system, and the second instance they are from conda. I would have assumed that the second instance would override the first, but that does not appear to be the case when running `strings libcrypto.so.3 | grep OPENSSL_3.` against the packaged file. I have also verified there is only one copy of `libcrypto.so.3` in the package.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.10.0```
`pyinstaller-hooks-contrib     2024.8`
* Version of Python: ```3.11```
* Platform: ```Linux / ubuntu-22.04```
* How you installed Python: ```conda / micromamba```
* Did you also try this on another platform? Does it work there? ```verified as no issues on Windows```

**Comment by rokm** [comment]
Looks like the system copy is being pulled in by `cryptography` hook:
>```
>2024-09-18T16:04:58.2671489Z 29725 DEBUG: hook-cryptography: OpenSSL shared library location: '/lib/x86_64-linux-gnu/libssl.so.3'
>2024-09-18T16:04:58.2672592Z 29725 DEBUG: hook-cryptography: collecting OpenSSL modules directory: '/lib/x86_64-linux-gnu/ossl-modules'
>```

(and then the first occurrence of `libcrypto.so.3` is the system-wide copy that comes up during binary dependency analysis of a module from that `ossl-modules` directory).

I guess that's because we try to resolve the library via `bindepend.resolve_library_path` ([here](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/6a05c66c8966a3447a5278e1f68a1f5783527ba4/_pyinstaller_hooks_contrib/stdhooks/hook-cryptography.py#L98)) and that ends up resolving system-wide version because `LD_LIBRARY_PATH` is not set in the anaconda environment. (Which comes somewhat as surprise, because I thought it would be. But apparently, anaconda resolves library search path issues by setting RPATHs on the binaries that they ship...)

So we might need to amend that `libssl.so.3` search to instead perform binary dependency analysis on `cryptography/hazmat/bindings/_rust.abi3.so` and look for linked `libssl.so.3`. So that if `libssl.so.3` is linked with `RPATH` (as is the case with Anaconda-packaged `cryptography`), we would end up resolving the correct version.

---

However, that would not solve the specific scenario we are dealing with here, which is Anaconda python and pip-installed `cryptography`, because `cryptography/hazmat/bindings/_rust.abi3.so` in `cryptography` PyPI wheel is not linked against `libssl.so.3` with `RPATH` (in fact, it doesn't seem to be linked against `libssl.so.3` at all, and likely loads it dynamically at run-time). So even in Anaconda environment, it ends up resolving the system copy of `libssl.so.3` if available (same as we do).

---

You can probably work around this by setting `LD_LIBRARY_PATH=/home/runner/micromamba/envs/test/lib` before running pyinstaller.

Or not using Anaconda python in the first place - you seem to be installing all your dependencies via pip and apt, anyway.

**Comment by jdegenstein** [comment]
> You can probably work around this by setting LD_LIBRARY_PATH=/home/runner/micromamba/envs/test/lib before running pyinstaller.

That worked perfectly, thank you for the suggestion.

By the way, what I described above is new behavior, as I released an earlier version in March that worked perfectly. Unfortunately I do not have build logs to see what changed here. I suppose some of the run time hooks have changed since then, so perhaps it is related to that? Just an idea.

I prefer to use micromamba because actions/setup-python works very poorly on MacOS-arm64 in my experience and I would like to keep things relatively consistent across platforms.

**Comment by rokm** [comment]
> By the way, what I described above is new behavior, as I released an earlier version in March that worked perfectly. Unfortunately I do not have build logs to see what changed here. I suppose some of the run time hooks have changed since then, so perhaps it is related to that? Just an idea.

The cryptography hook was updated in April to collect modules from `ossl-modules` if OpenSSL 3 is used. (See https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/727)

> I prefer to use micromamba because actions/setup-python works very poorly on MacOS-arm64 in my experience and I would like to keep things relatively consistent across platforms.

On the other hand, you now have two sets of shared libraries - the ones in Anaconda environment and the ones on the base system. And seeing how you are installing PyQt5 via pip and its dependencies via apt *into the base system*, that's just asking for trouble. "Consistent" is the last word I would use for this build environment :)

**Comment by Pjumpod** [comment]
I found this issue too. I use the httpx and cryptography library on MacOS
