### ISSUE TITLE
Pyinstaller6.11 packages Python versions 3.12 and above, but contextvars standard library cannot be packaged

### ISSUE THREAD

**Issue by WangZhongDian** [pyinstaller/pyinstaller#8848]
## test code 
```python
import contextvars
def main():
    print("Hello from t1!")


if __name__ == "__main__":
    c1 = contextvars.ContextVar("test")
    c1.set("Hello from t1")
    main()
```

## screenshot
![image](https://github.com/user-attachments/assets/daed947b-fed0-4830-95fa-dfae47a0077c)

**Comment by bwoodsend** [comment]
Can we have the [full details](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)? I can't reproduce on either side of 3.12.

**Comment by WangZhongDian** [comment]
Can you package the above test code and not reproduce this error?

**Comment by rokm** [comment]
What happens if you run 
``` 
import _contextvars
print(_contextvars)
```
in the same python environment as you use for build? Is it a `built-in` or a `module '_contextvars' from '.../lib-dynload/_contextvars.cpython-312-x86_64-linux-gnu.so'>`?

`_contextvars` should be an extension module . I suppose one of the reasons it could be missing is if you are using a custom build of python that does not have a shared library (and has these extensions built-in), but then during the build, we end up collecting python shared library from system-provided python that does have a shared library.

**Comment by bwoodsend** [comment]
> Can you package the above test code and not reproduce this error?

Yes.

**Comment by WangZhongDian** [comment]
I encountered this problem in flask. After testing, I found that this problem occurred in context management using contextvars after 3.12. I am not sure how to solve it, or is it a bug

**Comment by WangZhongDian** [comment]
Django is also a common problem, although it is normal in 3.11, but I just want to know the cause of the problem, I am a Linux environment

**Comment by rokm** [comment]
What linux distribution? Are you using system python, or some other/custom python build?

**Comment by WangZhongDian** [comment]
> What linux distribution? Are you using system python, or some other/custom python build?

Ubuntu24.10 uses uv to create a Python virtual environment

**Comment by bwoodsend** [comment]
In that case, this is presumably just #8802 again. PyInstaller has known issues with the indygreg/python-build-standalone Python builds.

**Comment by WangZhongDian** [comment]
> In that case, this is presumably just #8802 again. PyInstaller has known issues with the indygreg/python-build-standalone Python builds.

I am not sure, is this a pyinstaller bug or the environment itself or the uv problem, is this problem not solved for the time being? My English is not very good

**Comment by rokm** [comment]
The python build that uv uses is incompatible with PyInstaller. Whether you consider that a PyInstaller bug or not is up to you, but the fact is that you won't be able to use it with PyInstaller.

And yeah, it does look like #8802 (full path to shared library stored in the python executable/shim), but with the added twist that the path seems to be invalid: 

``` 
ldd .venv/bin/python
	linux-vdso.so.1 (0x00007fdc6c338000)
	/example/.venv/bin/../lib/libpython3.13.so.1.0 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc6c324000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc6c31f000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fdc6c31a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdc6c22d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdc6c226000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc6c000000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdc6c33a000)
```
```
objdump -x .venv/bin/python | grep libpython
  NEEDED               $ORIGIN/../lib/libpython3.13.so.1.0
``` 

The actual libs are in 
```
~/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/libpython3.13.so.1.0
~/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/libpython3.so
~/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/libpython3.13.so
```

**Comment by WangZhongDian** [comment]
> The python build that uv uses is incompatible with PyInstaller. Whether you consider that a PyInstaller bug or not is up to you, but the fact is that you won't be able to use it with PyInstaller.
> 
> And yeah, it does look like #8802 (full path to shared library stored in the python executable/shim), but with the added twist that the path seems to be invalid: 
> 
> ``` 
> ldd .venv/bin/python
> 	linux-vdso.so.1 (0x00007fdc6c338000)
> 	/example/.venv/bin/../lib/libpython3.13.so.1.0 => not found
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc6c324000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc6c31f000)
> 	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fdc6c31a000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdc6c22d000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdc6c226000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc6c000000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007fdc6c33a000)
> ```
> ```
> objdump -x .venv/bin/python | grep libpython
>   NEEDED               $ORIGIN/../lib/libpython3.13.so.1.0
> ``` 
> 
> The actual libs are in 
> ```
> ~/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/libpython3.13.so.1.0
> ~/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/libpython3.so
> ~/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/libpython3.13.so
> ```

Sorry, there may be some problems with my expression. What I am concerned about is whether this problem will be solved in the future, because Python3.11 built by uv has no problems. Hopefully, you can use it in a higher version of Python. Finally, thank you for your service

**Comment by rokm** [comment]
I think the problem is python 3.12 specifically, because the same version is also provided by the system, and we (incorrectly) pick up the system `libpython3.12.so.1.0` instead of the uv-python one... 

I just tried to build your sample with 3.13 in the Ubuntu 24.10 container, and it (against my expectations) did find that `libpython3.13.so.1.0`. So probably one of the fallback search mechanisms that we have does manage to discover it, but if there is a copy of the library in the system directory, we pick that up first (and in this case, this is incorrect).

We'll look into what can be done about this and #8802, but as we commented there, supporting arbitrary python builds is not exactly high priority. So for the time being, you'll have to either not use uv-python, or use uv-python of version that does not have corresponding system-installed python (e.g., 3.11 or 3.13 on Ubuntu 24.10), or use a minimal system that does not have system python 3.12 installed (e.g., Ubuntu 24.10 container).

**Comment by WangZhongDian** [comment]
Okay, I get it. One small suggestion I have for this problem is if, in the future, there is an option to manually specify the absolute path to Python if the fallback search is invalid to avoid such problems. I don't know much about the inner workings of pyinstaller, so maybe this isn't a good solution. In the end, there were no more questions, and the topic probably ended there

**Comment by bwoodsend** [comment]
The `/example/.venv/bin/../lib/libpython3.13.so.1.0 => not found` invalid path twist seems to be specific to using venv and due to `.venv/bin/python` being a symlink to the original `bin/python`. I guess `ldd` is interpreting `$ORIGIN` as the symlink's location rather than it's target.
```fish
# Original Python environment works
> ldd python/install/bin/python | grep libpython
	/tmp/22854/python/install/bin/../lib/libpython3.13.so.1.0 (0x00007fc49f6a4000)

# Venv Python does not
> ./python/install/bin/python -m venv /tmp/env
> ldd /tmp/env/bin/python | grep libpython
	/tmp/env/bin/../lib/libpython3.13.so.1.0 => not found

# Resolving the symlink before passing to ldd fixes it
> ldd (realpath /tmp/env/bin/python) | grep libpython
	/tmp/22854/python/install/bin/../lib/libpython3.13.so.1.0 (0x0000774117cd3000)
```

No idea what the correct interpretation of `$ORIGIN` is for a symlinked binary.

**Comment by bwoodsend** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=25263

**Comment by bwoodsend** [comment]
I suppose a `pathlib.Path(sys.executable).resolve()` is an easy workaround.
