### ISSUE TITLE
Anybody can crack your python code

### ISSUE THREAD

**Issue by Pandurangbhor** [pyinstaller/pyinstaller#8892]
![Untitled](https://github.com/user-attachments/assets/ad0fb5bf-1511-47a5-b942-6d541605cce7)
How the One-File Program Works[](https://pyinstaller.org/en/stable/operating-mode.html#how-the-one-file-program-works)
The bootloader is the heart of the one-file bundle also. When started it creates a temporary folder in the appropriate temp-folder location for this OS.###  **The folder is named _MEIxxxxxx, where xxxxxx is a random number.**

The one executable file contains an embedded archive of all the Python modules used by your script, as well as compressed copies of any non-Python support files (e.g. .so files). The bootloader uncompresses the support files and writes copies into the the temporary folder. This can take a little time. That is why a one-file app is a little slower to start than a one-folder app.

**Comment by rokm** [comment]
> Anybody can crack your python code

True - it's straightforward to unpack embedded archive with python code, and then decompile it.

But note that the page you linked makes no promises about code protection. That's because PyInstaller is specifically *not* a code obfuscation/protection tool. If you need to obfuscate and protect your code, you'll have to look at other solutions.
